### ISSUE TITLE
'Choice' type in List fields

### ISSUE THREAD

**Issue by tiagojsag** [sonata-project/SonataAdminBundle#1023]
Hi,

I'm trying to display a choice-type field in a list. Everywhere, I use 'choice' type, pass the choice array, and the integer is rendered as the corresponding value (in my case, a human readable string). However, that doesn't happen in list view. No matter what field type I assign to it, I always get an integer displayed (the array key), not the corresponding value.
Can anything be done regarding this?

cheers

**Comment by iBasit** [comment]
Is editable feature added yet for select or choice? as @webdevilopers has asked 2 years ago? Just wondering if something changed, because need to implement it myself.

**Comment by marek-mazur** [comment]
is it implemented?

**Comment by idchlife** [comment]
It's the real question, yes. How to implement choice in list fields with editable => true.
With custom template there should be JS which will make api (also customly written) request and update field in html accordingly, yes?

**Comment by skobkin** [comment]
I'm also interested in this feature.

**Comment by alva2409** [comment]
How I see, now this feature not work

**Comment by alva2409** [comment]
> Thank you @rande your `getStatusName()` trick was really helping !

Can you show function code?
