### ISSUE TITLE
Problem with one-to-many ('sonata_type_collection') and file uploads

### ISSUE THREAD

**Issue by thomaskonrad** [sonata-project/SonataAdminBundle#1049]
I'm currently facing a problem with file uploads when using one-to-many relationships in Sonata Admin. In my example, I have a one-to-many relationship between `Client` and `ExchangeFile`. The `ExchangeFile` has a file column. I manage the file upload with VichUploaderBundle (which persists the file in Doctrine's `prePersist`).

Here's how I included the `ExchangeFile` in the `ClientAdmin`'s `configureFormFields` method:

``` php
$formMapper->add('exchangeFiles', 'sonata_type_collection', array('by_reference' => false), array(
    'edit' => 'inline',
    'inline' => 'table',
));
```

Now when i use Sonata Admin with Ajax and append a new Form row in the edit form, the entire form (including both the `Client` and all `ExchangeFile`s) is posted to the server and the `appendFormFieldElementAction` method in `Sonata\AdminBundle\Controller\HelperController` is called. There, the request is bound to the form, a new form row is appended to the `ExchangeFile` section, the entire form is sent back to the browser and the whole form is replaced by the new one. But as file inputs (`<input type="file" />`) cannot be pre-populated with data, previously added files are lost if the Client is not saved before a new `ExchangeFile` row is added. This happens because the file upload mechanism is only triggered when the entity is persisted (which makes sense).

For a more detailed description of the problem, see [the question I posted on StackOverflow](http://stackoverflow.com/questions/13648467/sonata-admin-one-to-many-relationship-with-file-upload-appendformfieldelement).

**Comment by krewetka** [comment]
I tried many different approaches and workaround and in the end I found out  that the best solution in the one described here http://stackoverflow.com/a/25154867/4249725

You just have to hide all the unnecessary list/delete buttons around the file selection.

In all other cases with file selection directly in the form you will face some other problems sooner or later - with form validation, form preview etc. In all these case input fields will be cleared.

So using  media bundle and sonata_type_model_list is probably the safest option despite quite a lot of overhead.

I'm posting it in case someone is searching for the solution the way I was searching.
