### ISSUE TITLE
add a language switcher

### ISSUE THREAD

**Issue by lsmith77** [sonata-project/SonataAdminBundle#1072]
basically just a way to switch the session to a different language. maybe use LuneticsLocaleBundle

**Comment by OskarStark** [comment]
can you post your solution here @lsmith77 ?

**Comment by jo66** [comment]
I followed @rande suggestion and created language switcher this way (using sf4 and autowiring):
1. Create LocaleSubscriber and UserLocaleSubscriber as explained [here](https://symfony.com/doc/current/session/locale_sticky_session.html).
2. Create controller to handle locale switch in src/Controller/LocaleController.php:
```
namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;

class LocaleController extends AbstractController
{
    /**
     * @Route("/locale/{locale}", name="locale")
     */
    public function index(Request $request, SessionInterface $session, $locale)
    {
        $session->set('_locale', $locale);
        $referer = $request->headers->get('referer');
        return new RedirectResponse($referer ?: '/');
    }
}
```
3. Extend SonataAdminBundle:
- Install Sonata Easy Extends Bundle: `composer require sonata-project/easy-extends-bundle`
- Run `bin/console sonata:easy-extends:generate SonataAdminBundle --dest=src --namespace_prefix=App`
- Add this to config/bundles.php:
```
return [
    ...
    App\Application\Sonata\AdminBundle\ApplicationSonataAdminBundle::class => ['all' => true],
];
```
4. Override standard_layout.html.twig:
- Add this to config/sonata_admin.yaml:
```
sonata_admin:
    ...
    templates:
        layout: '@ApplicationSonataAdminBundle/standard_layout.html.twig'
```
- Create src/Application/Sonata/AdminBundle/Resources/views/standard_layout.html.twig:
```
{% extends '@SonataAdmin/standard_layout.html.twig' %}

{% block sonata_top_nav_menu %}
    {{ parent() }}
    <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
            {% block sonata_top_nav_menu_locale_block %}
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-flag fa-fw" aria-hidden="true"></i>
                        <i class="fa fa-caret-down" aria-hidden="true"></i>
                    </a>
                    <div class="dropdown-menu multi-column dropdown-add">
                        <div class="container-fluid">
                            <div class="row">
                                <ul class="dropdown-menu">
                                    <li role="presentation" class="dropdown-header">
                                        <i class="fa fa-language"></i>
                                        {{ 'languages_title'|trans({}, 'SonataAdminBundle') }}
                                    </li>
                                    {% for locale in available_locales|split('|') %}
                                    <li role="presentation" class="{{ app.request.locale == locale ? 'active' : '' }}">
                                        <a role="menuitem" tabindex="-1" href="{{ path('locale', {'locale': locale}) }}">{{ locale|language|capitalize }}</a>
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </li>
            {% endblock %}
        </ul>
    </div>
{% endblock %}
```
5. Update your config to make it work:
- Create twig path and available_locales parameter by adding this to /config/packages/twig.yaml:
```
twig:
    ...
    paths:
        ...
        '%kernel.project_dir%/src/Application/Sonata/AdminBundle/Resources/views': ApplicationSonataAdminBundle
    ...
    globals:
        available_locales: '%app.locales%'
```
- Make sure app.locales is defined in config/services.yaml:
```
parameters:
    ...
    app.locales: en|fr
```
- Install Sonata Intl Bundle that is needed by our template to convert locale to language name with [twig locale helper](https://sonata-project.org/bundles/intl/2-x/doc/reference/locale.html): `composer require sonata-project/intl-bundle`
Alternatively, you can replace `{{ locale|language|capitalize }}` by `{{ locale }}` in template if you don't need locale switcher to display language.
6. That's all! You should now have working language switcher in top right corner of your admin :)

**Comment by kunicmarko20** [comment]
@jo66 would you like to provide a PR and add this to documentation?

**Comment by jo66** [comment]
@kunicmarko20 Sure! But can you first explain what is a PR? :-P

**Comment by jo66** [comment]
@kunicmarko20 done! Here is the [link](https://github.com/sonata-project/SonataAdminBundle/pull/5309).

**Comment by jo66** [comment]
Global locale switcher is now implemented in SonataTranslationBundle, see [doc](https://sonata-project.org/bundles/translation/master/doc/reference/global_locale_switcher.html).

**Comment by kunicmarko20** [comment]
Thank you @jo66!
