### ISSUE TITLE
make it possible to limit the maximum length of columns in the list view

### ISSUE THREAD

**Issue by lsmith77** [sonata-project/SonataAdminBundle#1073]
something like `->add('body', 'text', array('length' => 100))`

**Comment by krewetka** [comment]
:+1

**Comment by nlzet** [comment]
Will that cut off the rest of the text or will there be a toggle to expand the full text (something like http://jedfoster.com/Readmore.js/)

**Comment by krewetka** [comment]
@nlzet - who are you asking this question to ? :)

**Comment by nlzet** [comment]
@lsmith77 and probably @rande / anyone who decides what is allowed to change/add

**Comment by rande** [comment]
I will merge the PR if someone create one ;) There is one template per column's type, maybe the length is only relevant for text column..

**Comment by Soullivaneuh** [comment]
> Will that cut off the rest of the text or will there be a toggle to expand the full text (something like http://jedfoster.com/Readmore.js/)

This method could be nice to have on show view too, isn't it?
