### ISSUE TITLE
sonata_type_collection PersitentCollection could not be converted to string

### ISSUE THREAD

**Issue by waiting-for-dev** [sonata-project/SonataAdminBundle#1074]
When using `sonata_type_collection` for a form type, following exception is thrown:

    An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Object of class Doctrine\ORM\PersistentCollection could not be converted to string in /NS/Symfony/app/cache/dev/twig/e8/8b/d47661752a14d574f5fe6c050012.php line 302") in "SonataAdminBundle:CRUD:edit.html.twig".

This only happens when the collection already have some item.

Furthermore, if I pass the option `'edit'  => 'inline'`, the exception disappears but then the "Add New" button does nothing.

**Comment by Soullivaneuh** [comment]
@rande Symfony 2.3+ is now the minimum requirement.

Is this issue still actual? Can we close it?

**Comment by rande** [comment]
Yes, you can close it (in a few minutes ;)

**Comment by Soullivaneuh** [comment]
Indeed. :+1:
