### ISSUE TITLE
Form error messages are removed by javascript

### ISSUE THREAD

**Issue by waiting-for-dev** [sonata-project/SonataAdminBundle#1076]
Line 35 of `Resources/public/base.js` is removing the content of `.sonata-ba-field-error-messages`, and then no error is displayed when editing or creating an entity. That's the line:

    jQuery('div.sonata-ba-field-error-messages', element).html('');

Which is the purpose of this line? Is it a mistake and should be removed?

**Comment by ju1ius** [comment]
3 years later, this bug still exists.

The `Admin.add_pretty_errors()` function blindly removes all errors to try and show them in a popover.
Not only does it fail on certain types of fields (most commonly icheck), but hiding errors on a form and showing them on HOVER only is _really_ bad for UX (what about touchscreens, disabled users...)

IMO this anti-feature should be removed entirely, as it does more harm than good.
And it's not _that_ pretty.

Here's a backward-compatible fix:
```js
Admin.add_pretty_errors = function () {};
```

**Comment by OskarStark** [comment]
@core23 could you check this behavior? I'm not so familar with JS

**Comment by core23** [comment]
Could you create a PR for this @ju1ius ?

**Comment by ju1ius** [comment]
@core23, @OskarStark, @rande: I Would love to :heart: 
The one thing that prevent me (and I guess many other people) from doing it atm is a more general issue: I have no idea how do you core-guys work on this project. There are many bundles, some of which are inter-dependent. What's your dev setup ? How do you test that a commit in one bundle didn't introduce a regression in another one ? I'd love to have your input on this question.

**Comment by greg0ire** [comment]
Personally, I have a project, and I contribute fixes by working inside the vendor directory of that project if I feel there is a need for manual tests. If you don't, there is [the sandbox](https://github.com/sonata-project/sandbox), I think it can help you with that.

**Comment by ju1ius** [comment]
@greg0ire Hi, So I should install the sandbox, fork ze bundles & update composer deps to point to my master branch ? Is  2.4-develop the most up-to-date sandbox version ?

**Comment by ju1ius** [comment]
@core23 Done!

**Comment by greg0ire** [comment]
>@greg0ire Hi, So I should install the sandbox, fork ze bundles & update composer deps to point to my master branch ? 

I don't know for sure, but I think I would proceed like that.

> Is 2.4-develop the most up-to-date sandbox version ?

The [network view](https://github.com/sonata-project/sandbox/network) seems to say so.
