### ISSUE TITLE
Virtual fields with parameters

### ISSUE THREAD

**Issue by waiting-for-dev** [sonata-project/SonataAdminBundle#1086]
Even if I haven't seen it documented, it is allowed to add to `listMapper` and `showMapper` virtual fields through the name of one of the entity methods.

But what happens if that method has any parameter? How could we pass it?

One option would be to allow an array as the name of the field. The first value would be the method name, and the second would be an array of the parameters. For example:

`->add(array('getSomething', array('parameter1'), 'text)`

But now this is not allowed bacause `$name` is forced to be a string or to implement `FieldDescriptionInterface`.

If this is not an issue and it is already possible but not documented, please close it. Surely it is possible to achieve what I want implemeting `FieldDescriptionInterface`, but it is not very straighforward.

**Comment by core23** [comment]
Don't know if a virtual field should have parameters. Can you give an example?

**Comment by core23** [comment]
This issue is very old. Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.

**Comment by Jean-Gian** [comment]
@waiting-for-dev did you find any workaround for this?
