### ISSUE TITLE
hold a bug triage day?

### ISSUE THREAD

**Issue by jrobeson** [sonata-project/SonataAdminBundle#1112]
There seems to issues that are both obsolete and overlooked. It might be a good thing to get the community involved to get some of these cleaned out.

What do you think @rande?

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @jrobeson

**Comment by jrobeson** [comment]
wow, i forgot i filed this. I think the idea is still a good one, but I guess the ticket didn't generate enough interest. I will close it.
