### ISSUE TITLE
Export : file not found ?

### ISSUE THREAD

**Issue by ibasaw** [sonata-project/SonataAdminBundle#1138]
Hi,

When i try to do an export of the users, i got this error: 

File not found

Firefox can't find the file at http://local.symfony.tld/app_dev.php/admin/sonata/user/user/export?filter[_sort_order]=ASC&filter[_sort_by]=id&filter[_page]=0&filter[_per_page]=25&format=json.

why ?

**Comment by ticlekiwi** [comment]
I had the same problem, and after debug it, I think I found a solution : 
Problem is there is an error if you don't add default "ORDER BY" in your admin class : 
Just add this in your admin class resolve the problem for me : 
`
public function __construct($code, $class, $baseControllerName) {
        parent::__construct($code, $class, $baseControllerName);
        if (!$this->hasRequest()) {
            $this->datagridValues = array(
                '_page' => 1,
                '_sort_order' => 'DESC', // sort direction
                '_sort_by' => 'id' // field name
            );
        }
    }
`
