### ISSUE TITLE
Sonata_Type_Model doesn't work with dynamic relations

### ISSUE THREAD

**Issue by WouterJ** [sonata-project/SonataAdminBundle#1161]
It seems like the Model type of Sonata doesn't work with dynamic relations using the way that is described in the documentation: http://symfony.com/doc/master/cookbook/doctrine/resolve_target_entity.html

Does anyone know how to fix this?

More information in the related SO question: http://stackoverflow.com/questions/14718757/dynamic-relationship-and-the-sonataadminbundle

**Comment by core23** [comment]
If this is an active issue, please reopen @WouterJ
