### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by sinner** [sonata-project/SonataAdminBundle#1166]
For intallation I'm execute this command by composer:

    > composer require sonata-project/admin-bundle --no-update
    Please provide a version constraint for the sonata-project/admin-bundle requirement:
    
    > composer require sonata-project/doctrine-orm-admin-bundle --no-update
    Please provide a version constraint for the sonata-project/doctrine-orm-admin-bundle requirement:
    
    > composer require simplethings/entity-audit-bundle
    Please provide a version constraint for the simplethings/entity-audit-bundle requirement:
    
    > composer require sonata-project/intl-bundle --no-update
    Please provide a version constraint for the sonata-project/intl-bundle requirement:
    
    > composer require sonata-project/cache-bundle --no-update
    Please provide a version constraint for the sonata-project/cache-bundle requirement:
    
and for each command, composer asks me the version of each bundle required. I try typing "dev-master" but, in fact of execute "composer update" I get some problems by composer and response this:

    Loading composer repositories with package information
    Updating dependencies
    Your requirements could not be resolved to an installable set of packages.

    Problem 1
        - Installation request for sonata-project/admin-bundle dev-master -> satisfiable by sonata-project/admin-bundle dev-master.
        - sonata-project/admin-bundle dev-master requires sonata-project/jquery-bundle dev-master -> no matching package found.

    Potential causes:
        - A typo in the package name
        - The package is not available in a stable-enough version according to your minimum-stability setting
        see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

    Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Composer version 432955e
Symfony version 2.1.7
PHP version 5.4

**Comment by pulzarraider** [comment]
Closing as this is very old issue and everything should work now.
