### ISSUE TITLE
[RFC] Multiple admin pools

### ISSUE THREAD

**Issue by sstok** [sonata-project/SonataAdminBundle#1177]
At the moment everything is kept in one Admin\Pool, but looking at the code it should be no problem to add support for multiple admin pools!

The AdminBundle is great for creating a back-end, but when providing services for our users it would save a lot work to just create a new admin pool with its own dashboard and admins.

When no pools are configured it just fall back to the 'default' pool.

If I can get some feedback on this, I can start working on this.

**Comment by core23** [comment]
If this is an active issue, please reopen @sstok

**Comment by sstok** [comment]
No problem :) I'm not using the SonataAdminBundle anymore.
