### ISSUE TITLE
What's the best way to manage many-to-many relations that has extra columns on middle table?

### ISSUE THREAD

**Issue by scourgen** [sonata-project/SonataAdminBundle#1225]
I have 3 tables : A,AB,B. AB is the middle table of table A and B.

for some reason I need a extra column on the middle table AB,So I have to split the many-to-many relation to 2 one-to-many relations( A has many AB, B also has many AB ).

then I found out that It seems like not possible to manage the relation. Can I manage(link/unlink) B in the edit page of A ?

any one have any idea ?

**Comment by alymdrictels** [comment]
Oh thank God, I've been tearing my hair out over this for WAY too many hours.

An intermediary table for many to many with added data is a rather common use case and I'm surprised it was not covered in the Sonata documentation.

**Comment by AmaliDeveloper** [comment]
You can get the solution in this tutorial Good Work ;) [Link](https://youtu.be/HeIggSkjtdk)
