### ISSUE TITLE
Use Doctrine Tree Behavior with SonataAdmin

### ISSUE THREAD

**Issue by maikelohcfg** [sonata-project/SonataAdminBundle#1227]
Hi there i am using SonataAdmin for manipulate a Seccion Entity with NestedTree Behavior, the main problem i am encountered is that when I  insert or update one Seccion the fields lvl, lft and rgt remain with value 0. Any Idea.. thanks

**Comment by core23** [comment]
If this is an active issue, please reopen @maikelohcfg
