### ISSUE TITLE
Looking for a real solution to INVALID MODE : sonata_type_collection - mapping 

### ISSUE THREAD

**Issue by ornj** [sonata-project/SonataAdminBundle#1231]
I have a ManyToMany association in my entity and I am trying to edit those entities inline. I am attempting to use `sonata_type_collection` to display the form,

``` php
->add('galleries', 'sonata_type_collection', array(), array(
    'edit'    => 'inline',
    'inline'  => 'table',
))
```

When I render the form, I see `INVALID MODE : s5147816d591b7_galleries - type : sonata_type_collection - mapping : 8` instead of the form field.

I've seen similar issues such as #322 but the solution provided there, and every where else I've seen this referenced is a cop out. Instead of rendering the admin fields they are using the default Symfony form behavior as a close enough solution. I want to give users the ability to select existing entities or add new ones. According to the [Doctrine2 ORM Admin documentation](http://sonata-project.org/bundles/doctrine-orm-admin/master/doc/reference/form_field_definition.html#advanced-usage-one-to-many), the above should have worked.

**Comment by antoinefortin** [comment]
Still relevant six years later guys. If you would like to share a trick would be really appreciated.

**Comment by greg0ire** [comment]
You mean 3, right?

**Comment by vladkras** [comment]
I mean 4

**Comment by valdisAglonietis** [comment]
I think you meant 5

**Comment by patrickmaynard** [comment]
I spent more than an hour on this in the morning, so I thought I would post what worked for me here, in case others are still encountering this pesky error. See the link below. 

https://stackoverflow.com/questions/48823406/invalid-mode-s5a869f19a6c57-equivalents-type-sonata-type-collection-mapp/48827920#48827920
