### ISSUE TITLE
[HTML] Consider using data-objectId instead of objectid

### ISSUE THREAD

**Issue by sstok** [sonata-project/SonataAdminBundle#1257]
objectid is used as a tag parameter resulting in invalid HTML.
With HTML5 its better to use use data-objectid.

Once I have some time I will work on a pull request, OrmBundle needs updating as-well.

**Comment by sstok** [comment]
I'm no longer using Sonata nor can I remember what this was about 😄 if anyone is still having this problem feel free open a pr. Closing to clean my old issue reports.

**Comment by core23** [comment]
Refs https://github.com/sonata-project/SonataAdminBundle/issues/5132
