### ISSUE TITLE
MutableAclProviderInterface, null given,

### ISSUE THREAD

**Issue by matlow** [sonata-project/SonataAdminBundle#1263]
Got this error : 

```
Catchable Fatal Error: Argument 2 passed to Sonata\AdminBundle\Security\Handler\AclSecurityHandler::__construct() must be an instance of Symfony\Co
mponent\Security\Acl\Model\MutableAclProviderInterface, null given, called in app/cache/prod/appProdDebugProjectContainer.php on line 3798 and defined in vendor/sonata-project/admin-bundle/Sonata/AdminBundle/Security/Handler/AclSecurityHandler.php line 41
```

I don't know what to do, is it possible to give a null default value in the constructor for the param with type MutableAclProviderInterface ?

**Comment by ktanvir** [comment]
facing same error... but cudn't get how to resolve this

**Comment by sajad-kioumarsi** [comment]
But that is not the solution if you want to use acl and not roles to handle security. I have the same problem and still trying to find the solution

**Comment by greg0ire** [comment]
Argument 2 isn't supposed to be this, what outdated version of Sonata are you using?

**Comment by sajad-kioumarsi** [comment]
I recieve this which ask about Argument 3:


`Type error: Argument 3 passed to Sonata\AdminBundle\Security\Handler\AclSecurityHandler::__construct() must be an instance of Symfony\Component\Security\Acl\Model\MutableAclProviderInterface, null given`

**Comment by greg0ire** [comment]
Here is the [service definition](https://github.com/sonata-project/SonataAdminBundle/blob/240ecbd02d453f9acaf81e00112ff5d8dae4459b/Resources/config/security.xml#L25). I notice there is an `on-invalid="null"` attribute, might be the problem here.

**Comment by greg0ire** [comment]
You should use `debug:container` to check whether `security.acl.provider` is defined.

**Comment by sajad-kioumarsi** [comment]
yes it was not on services!

I just add this in my config file and it is working:

`    acl:
        connection: default`

**Comment by greg0ire** [comment]
Good job! Can you maybe improve the docs?
