### ISSUE TITLE
Break set_object_field_value after paginate a list using a sonata_type_model_list

### ISSUE THREAD

**Issue by Pop-Code** [sonata-project/SonataAdminBundle#1267]
1 the listener in "set_object_field_value" is a simple listener "click" and should be change as a live listener

```javascript
jQuery('a.sonata-ba-edit-inline', subject).click(function(event) {
...
```

TO

```javascript
jQuery('a.sonata-ba-edit-inline', subject).on('click', function(event) {
...
```

2 Even with this change, if i paginate a list in a sonata_type_model_list, i can't select a row anymore.

This problem occurs with the sonata media admin class.

![Capture d e cran 2013-04-03 a 18 27 31](https://f.cloud.github.com/assets/1117971/334757/f6fe6166-9c7b-11e2-9c60-09de6030013f.png)

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @Pop-Code
