### ISSUE TITLE
Error with Cyrillic name of form group

### ISSUE THREAD

**Issue by overfuse** [sonata-project/SonataAdminBundle#1269]
Yesterday, after another "composer update". I've got the following error:

Notice: iconv(): Detected an illegal character in input string in /Users/Air/project/mdm/vendor/sonata-project/admin-bundle/Sonata/AdminBundle/Twig/Extension/SonataAdminExtension.php line 254

It works fine before...
Until this commit https://github.com/sonata-project/SonataAdminBundle/commit/1f80e66fd8f985d8f19d6c2c2b484461d516d56b

I already fix it for me using translation. Just for your information.

**Comment by core23** [comment]
If this is an active issue, please reopen @overfuse
