### ISSUE TITLE
Virtual Form Fields

### ISSUE THREAD

**Issue by tiagojsag** [sonata-project/SonataAdminBundle#1277]
Hi,

http://symfony.com/doc/current/cookbook/form/use_virtuals_forms.html

I'm trying to implement a virtual field, using the above cookbook page, but for it to work, my entity must have a getter and a setter for "foo". It's not a big deal to have those functions, but it would be nice it it worked without them.

cheers

**Comment by core23** [comment]
If this is an active issue, please reopen @tiagojsag

**Comment by abouross** [comment]
virtual field work only for list definition not for form
