### ISSUE TITLE
Show only filters by default without loading any data

### ISSUE THREAD

**Issue by Stefun** [sonata-project/SonataAdminBundle#1281]
This is not an issue.I'm using Symfony 2.1 and Sonata Admin bundle for admin functionality.Now I have lot of data to show in list view .And I don't prefer to show all data by default.I want to display only filters first time and then based on filtering fields display only related data.Any options to do this?

**Comment by webdevilopers** [comment]
ping @Stefun

**Comment by core23** [comment]
If this is an active issue, please reopen @Stefun
