### ISSUE TITLE
[Form] 'Choice' field type not picking up Admin's translation domain

### ISSUE THREAD

**Issue by tiagojsag** [sonata-project/SonataAdminBundle#1290]
Hi,

I've set up my translation domain according to this: http://sonata-project.org/bundles/admin/master/doc/reference/translation.html

However, the 'choices' list in a 'choice' field type keep using the "message" translation domain, unless I specify it explicitly on the field itself with 'translation_domain' => '...', which is not practical.

According to the docs, 'sonata_type_translatable_choice' is deprecated, and the default "choice" should be used instead. I've cleared cache, and tried both suggested ways of setting the translation domain, and still no good. Is this a bug, or am I doing something wrong?

cheers

**Comment by brieuc28** [comment]
Hi,

Any updates about that issue? I'm experiencing the same issue. Even for a unique role i don't have the translation.

I added in SonataUserBundle.fr.xliff

            <trans-unit id="role_investor">
                <source>ROLE_INVESTOR</source>
                <target>Investisseur</target>
            </trans-unit>
            <trans-unit id="role_user">
                <source>ROLE_USER</source>
                <target>Utilisateur</target>
            </trans-unit>

All the labels are translated except the roles 

![ROLES](https://cloud.githubusercontent.com/assets/7518508/7371616/5a84b4c6-edc2-11e4-910e-847ce5492635.png)

**Comment by kaiwa** [comment]
+1

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
