### ISSUE TITLE
Admin routing bug

### ISSUE THREAD

**Issue by siciarek** [sonata-project/SonataAdminBundle#1293]
When edit action is removed from Admin (eg. when you want to make it readonly list):

    protected function configureRoutes(RouteCollection $collection)
    {
        $collection
            ->remove('edit')
            ->remove('create')
        ;
    }

Changing boolean fields value (enabled, is_active, etc.) is still available if field was defined:

            ->add("is_enabled", null, array("editable" => true))

**Comment by webdevilopers** [comment]
Close @siciarek?
