### ISSUE TITLE
Inverse "Many" Side in Embedded sonata_type_collection one-to-many Form Not Disassociating When "Delete" Checked

### ISSUE THREAD

**Issue by grichards** [sonata-project/SonataAdminBundle#1295]
I've seen similar reports, but no clear solution. I've followed the pattern given in SonataMediaBundle, but to no avail in this use case. Here is sample code:

```php
class Company {
    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="My\Bundle\Entity\User\Controller", mappedBy="company", cascade={"persist", "remove"})
     * @ORM\JoinColumn(name="controller_id", referencedColumnName="id")
     */
    private $controllers;

    public function setControllers($controllers)
    {
        $this->controllers = new ArrayCollection();

        if (count($controllers)) {
            foreach ($controllers as $controller) {
                $controller->setCompany($this);
                $this->addController($controller);
            }
        }
    }
}

class Controller {
    /**
     *
     * @var Company
     *
     *
     * @ORM\ManyToOne(targetEntity="My\Bundle\Entity\Company", inversedBy="controllers", cascade={"persist", "remove"})
     * @Assert\Type(type="TCS\TimecardBundle\Entity\Company")
     */
    private $company;
}

class CompanyAdmin {

    protected function configureFormFields(FormMapper $formMapper)
    {

        $formMapper
            ->with('Controllers')
                ->add('controllers', 'sonata_type_collection', array('label' => false, 'required' => false, 'by_reference' => false), array('edit' => 'inline', 'inline' => 'table'))
            ->end();
    }

    public function prePersist($company)
    {
        $company->setControllers($company->getControllers());
    }

    public function preUpdate($company)
    {
        $company->setControllers($company->getControllers());
    }

}
```

So that's the setup, pretty much taken right out of examples I've seen posted here, on StackOverflow, and in SonataMediaBundle.

My expectation is that when I check "delete" on a few "Controllers" in the embedded forms and then save the "Company" form... the selected Controllers will be disassociated with the Company (i.e. the company_id on the Controller objects will be set to null). I do NOT want the Controllers to be "deleted" just the relationship to be removed.

However, that is not the case... am I misunderstanding something or is this a real problem?

One possibly important thing I've noticed is that the the preUpdate and prePersist methods are ONLY retrieving the non-deleted controllers when I call $company->getControllers() and pass that to $company->setControllers()... but it just seems that Doctrine doesn't notice the missing Controllers need to be disassociated.

TY for any help.

**Comment by core23** [comment]
If this is an active issue, please reopen @grichards
