### ISSUE TITLE
SonataAdmin and Custom Security Handler

### ISSUE THREAD

**Issue by zion03** [sonata-project/SonataAdminBundle#1300]
I wanna write a custom Security handler and this will be a simple ACL which restrict data by user_id. I don't want use a standart ACL, no need to use all functional and create aditional database with permissions.

So I create my new handler and now I recieve $object as Admin class. With Admin class I can restrict access to services but can't restrict any rows in service.

The question is how I can recieve Entities and check permission per each row like this.

Shorter I wanna implement this http://stackoverflow.com/questions/12843677/sonata-admin-only-allow-show-what-logged-in-user-has-created solution in Security Handler

**Comment by core23** [comment]
If this is an active issue, please reopen @zion03
