### ISSUE TITLE
Filters cover the table

### ISSUE THREAD

**Issue by GDXbsv** [sonata-project/SonataAdminBundle#1302]
![Dashboard-List](https://f.cloud.github.com/assets/1261269/409648/efb1b6be-ab59-11e2-98ea-dd33aa3f59e4.png)

**Comment by pulzarraider** [comment]
In `dev-master` (upcoming 2.4) the filters were moved to top and are hidden by default to improve the UI.

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @GDXbsv
