### ISSUE TITLE
PostRemove & PreRemove doesnt work in template of ListAction

### ISSUE THREAD

**Issue by Chrysweel** [sonata-project/SonataAdminBundle#1314]
Hello.

I found an error.

I use the method PostRemove in my AdminController, and it works correctly.

But from template of listAction, sonata allows delete one or many rows, and in this action, the method preRemove doesnt work.

How can I to do this method works ?? Or other solution is that Sonata not show the button to delete.

Somebody can help me ?
Thanks!
: )

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @Chrysweel

**Comment by remoteclient** [comment]
@Chrysweel if your livecycle events don't work from your admin controllers, you can still use symfonys entity listeners.
