### ISSUE TITLE
Deleted elements from a one-to-many not working. orphanRemoval enabled

### ISSUE THREAD

**Issue by zion03** [sonata-project/SonataAdminBundle#1324]
Not working orphanRemoval (OneToMany) I try 2.2 and 2.3 Doctrine . The element from target entity trying to deleted but still available. I get not any error, just not deleted.
 
sonata from master "sonata-project/admin-bundle": "dev-master"

Configuration example: 

    class SecurityForm implements SecurityEntityInterface
    {
       ...
  
    /**
     *
     * @ORM\OneToMany(targetEntity="SecurityFormField", mappedBy="form", cascade={"persist"}, orphanRemoval=true)
     * @ORM\OrderBy({"order" = "ASC"})
     */
    private $formFields;

       ....

    }

**Comment by core23** [comment]
If this is an active issue, please reopen @zion03
