### ISSUE TITLE
Form Type: Add elements to an array of relation

### ISSUE THREAD

**Issue by Chrysweel** [sonata-project/SonataAdminBundle#1326]
Hello.

I read the documentation of Form Types. http://sonata-project.org/bundles/admin/master/doc/reference/form_types.html

But I didn't find a solution to my problem I think.

I have a entity channel and User. One Channel will have many operators (users), so I want to in my form Admin of Sonata, when I create a channel add operators.

My channel has a relation with user.
```
/**
	 * @ORM\OneToMany(targetEntity="myproject\MyBundle\Entity\User", mappedBy="channel")
	 */
	protected $operators;
```
And my User also:
```
/**
	 * @ORM\ManyToOne(targetEntity="myproject\MyBundle\Entity\Channel", inversedBy="operators")
	 * @ORM\JoinColumn(name="channel_id", referencedColumnName="id", onDelete="CASCADE")
	 * @ORM\Id
	 */
	protected $channel;
```

What form type or method I need ? Somebody can help me ?

**Comment by core23** [comment]
If this is an active issue, please reopen @Chrysweel
