### ISSUE TITLE
sonata_type_model - ManyToMany Unidirectional - not working

### ISSUE THREAD

**Issue by arthurlm** [sonata-project/SonataAdminBundle#1329]
Hi everyone,

This subject has maybe been previously talked about, but I don't find the solution !

I have a problem with sonata_type_model in the admin panel.
Indeed when I try to change the selected values for sonata_type_model's field, the admin panel return an error : " _This form should not contain extra fields_ "

There is the entity where I have a problem : 

    use Doctrine\Common\Collections\ArrayCollection;

	/**
	 * Cheminmed\ArticleBundle\Entity\Livre
	 *
	 * @ORM\Table()
	 * @ORM\Entity()
	 */
	class Livre {
		
		/**
		 * @ORM\ManyToMany(targetEntity="Cheminmed\DataBundle\Entity\Image", cascade={"PERSIST"})
		 */
		private $images;

		public function getImages() {
			return $this->images;
		}

		public function addImage($image) {
			$this->images[] = $image;
		}

		public function removeImage($image) {
			$this->images->removeElement($image);
		}

		public function __construct() {
			$this->images = new ArrayCollection();
		}
	}

My related entity is here : 

	/**
	 * Cheminmed\DataBundle\Entity\Image
	 *
	 * @ORM\Table()
	 * @ORM\Entity()
	 */
	class Image {
	}

And my form builder is : 

	protected function configureFormFields(FormMapper $formMapper) {
        $formMapper
                ->add('images', 'sonata_type_model', array(
					'required' => false,
					'multiple' => true,
					'by_reference' => false,
				))
        ;
    }

If anyone have an idea about this bugs, please help me to fix it.

**Comment by core23** [comment]
If this is an active issue, please reopen @arthurlm
