### ISSUE TITLE
Compile Error: AdminListBlockService::execute() 

### ISSUE THREAD

**Issue by dduuch** [sonata-project/SonataAdminBundle#1335]
Hello,
I have problem with my project after update. That's what I have updated:
sonata-project/exporter to version 1.2.2
sonata-project/block-bundle to dev master (26300bd)
sonata-project/cache-bundle dev master (2.1.3)
sonata-project/doctrine-orm-admin-bundle (4edb2bd)

My error message:

> FatalErrorException: Compile Error: Declaration of  Sonata\AdminBundle\Block\AdminListBlockService::execute() must be compatible with Sonata\BlockBundle\Block\BlockServiceInterface::execute(Sonata\BlockBundle\Block\BlockContextInterface $blockContext, Symfony\Component\HttpFoundation\Response $response = NULL) in C:\wamp\www\kiziemizie\vendor\sonata-project\admin-bundle\Sonata\AdminBundle\Block\AdminListBlockService.php line 29

If anyone have an idea about this bug, please help me to fix it.

**Comment by core23** [comment]
If this is an active issue, please reopen @dduuch
