### ISSUE TITLE
Use jQuery UI Bootstrap

### ISSUE THREAD

**Issue by dsoms** [sonata-project/SonataAdminBundle#1344]
Hi,

Evaluate the possibility to use **jQuery UI Bootstrap** for a better integration (visually). In my opinion the current design with the front-end framework Bootstrap is nice, but the jQuery UI style used in dialogs is breaking the design coherence.

http://addyosmani.github.io/jquery-ui-bootstrap/
https://github.com/addyosmani/jquery-ui-bootstrap

Sorry for my English.

Regards,
David.

**Comment by core23** [comment]
If this is an active issue, please reopen @dsoms
