### ISSUE TITLE
No attached service to type named `doctrine_orm_time`

### ISSUE THREAD

**Issue by viniciuswebdev** [sonata-project/SonataAdminBundle#1358]
Im getting this error with time type.

Thks!

**Comment by webdevilopers** [comment]
Can we close this @viniciuswebdev and recommend following your other issue?
- https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/221

**Comment by viniciuswebdev** [comment]
Yes! Thank you!

2015-02-12 10:05 GMT-02:00 webDEVILopers <notifications@github.com>:
