### ISSUE TITLE
Export doesn't work with Doctrine arrays

### ISSUE THREAD

**Issue by predavlad** [sonata-project/SonataAdminBundle#1364]
I have some db columns defined in the following way:

```
/**
 * @ORM\Column(type="array")
 */
```

I use this field as an array, and it's automatically serialized when saved in the database, and unserialized when returned.

The problem is that when I use the export functionality, those fields are blank. Does anyone know how this can be fixed, I couldn't figure out where to modify so it unserializes then implodes.

Thanks.

**Comment by cjuhong** [comment]
+1
Anyone help?

**Comment by cjuhong** [comment]
@stof , @rande , @pulzarraider , @EmmanuelVella , @Bladrak , @tiagojsag , @rmsint

Help Please! Thanks a lot.

**Comment by cjuhong** [comment]
Hi, I have found the sulotion,
/**
     * {@inheritdoc}
     */
    public function getExportFormats()
    {
        return array(
            'json', 'xml', 'csv', 'xls'
        );
    }

    /**
     * @return array
     */
    public function getExportFields()
    {
        return $this->getModelManager()->getExportFields($this->getClass());
    }

    /**
     * @return
     */
    public function getDataSourceIterator()
    {
        $datagrid = $this->getDatagrid();
        $datagrid->buildPager();

// Here is the solution
foreach ( $datagrid->getResults as $key => $value){
// to chanage value on each field using  getter and setters
}

        return $this->getModelManager()->getDataSourceIterator($datagrid, $this->getExportFields());
    }

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @predavlad
