### ISSUE TITLE
Dialog pop-up doesn't keep the request status after server side validation

### ISSUE THREAD

**Issue by idhard** [sonata-project/SonataAdminBundle#1366]
Use case:

user create a new page :
http://demo.sonata-project.org/admin/sonata/page/page/create?siteId=827

try to add a "Parent" with a popup and complete all the mandatory fields except the disable one "Url" , when the form is submitted we have a error message "error.uniq_url" witch is right , but if we submit the form once again the popup is closed and the system redirect us to the "Parent" form page.

This is happening with all the popups when there are some server side validation.

it happen in my environment and also in the   demo.sonata-project.org.

cheers

**Comment by core23** [comment]
If this is an active issue, please reopen @idhard
