### ISSUE TITLE
Can't add custom template to sonata_type_model many_to_many

### ISSUE THREAD

**Issue by zion03** [sonata-project/SonataAdminBundle#1389]
Can't add custom template to sonata_type_model many_to_many relation.
I want to override standart template `edit_orm_many_to_many.html.twig` only for one field.

Wrote something like this:

            ->add('forms', 'sonata_type_model', array('expanded' => true,
                                                      'multiple' => true,
                                                      'query' => $query,
                                                      'template' => 'MyBundle:Default:edit_orm_many_to_many.html.twig'
                                                      ));

But I can't recieve any reaction. I can add `'template' => 'qwe'` and I still see standart template, notify about errors not appear. Looks  like option template not working.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @zion03
