### ISSUE TITLE
Sonata list not work with entity when id field is associated with another entity

### ISSUE THREAD

**Issue by kuldippujara** [sonata-project/SonataAdminBundle#1392]
Sonata list not work with entity when id field is associated with another entity

found an issue when entity like following its breaking in ORM ProxyQuery.php
with error 

An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 18 near 'member FROM Acme\Bundle\Entity\Example': Error: Invalid PathExpression. Must be a StateFieldPathExpression.") in SonataAdminBundle:CRUD:list.html.twig at line 25.

```php
/**
 * Example
 *
 * @ORM\Table(name="example")
 * @ORM\Entity
 */
class Example
{
    /**
     * @var \Member
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="NONE")
     * @ORM\OneToOne(targetEntity="Member")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="member_id", referencedColumnName="id")
     * })
     */
    private $member;
....
```

**Comment by rande** [comment]
should be fixed by https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/407
