### ISSUE TITLE
CRUD List filtering with voters

### ISSUE THREAD

**Issue by Glideh** [sonata-project/SonataAdminBundle#1398]
I'm using SonataUser and I'm trying to use a custom voter to filter Users in the list grid.

I have set `unanimous` security strategy.

My voter registers implementations of `FOS\UserBundle\Model\UserInterface` and the attributes `EDIT`, `DELETE`, `VIEW`, `LIST`

`EDIT`, `DELETE`, `VIEW` are effectively taken into account, but not `LIST`, at least not as I expect (that is weither to display the corresponding `<tr>` in the grid, am I wrong ?)

I took a look at `AdminBundle/Resources/views/CRUD/base_list.html.twig` expecting to see some `isGranted('LIST', object)` occurrence at `<tr>` rendering time. But there is not.

```html
<tbody>
    {% for object in admin.datagrid.results %}
        <tr>
            {% for field_description in admin.list.elements %}
                {{ object|render_list_element(field_description) }}
            {% endfor %}
        </tr>
    {% endfor %}
</tbody>
```

Is `admin.datagrid.results` already filtered with 'LIST' permission ?
Or shouldn't we have something like

```html
    {% for object in admin.datagrid.results if isGranted('LIST', object) %}
```

Can someone tell me where the voter is interrogated for this 'LIST' permission, and how can I make mine to be taken into account ?

**Comment by webdevilopers** [comment]
You or me @krewetka ? ;)

Is there a way to assign an Issue to a none-contributing participant inside a repository, @rande ?

**Comment by krewetka** [comment]
@webdevilopers - If you could add it would be great. I won't be able to do it until 10.04. I can try after Easter break.

**Comment by webdevilopers** [comment]
Let's just ping the other when starting. :)

**Comment by greg0ire** [comment]
Sorry, wrong manipulation.

> Is there a way to assign an Issue to a none-contributing participant inside a repository, @rande ?

Nope.

@krewetka @webdevilopers , did either of you work on this?

**Comment by webdevilopers** [comment]
Sorry no, I replaced most of my lists with  vanilla code and own security and query message services.

**Comment by greg0ire** [comment]
Ok closing, @krewetka , reopen if you feel up to it.
