### ISSUE TITLE
postupdate actions not running on embedded forms

### ISSUE THREAD

**Issue by iJanki** [sonata-project/SonataAdminBundle#1400]
It seems I can't find elsewhere, postupdate and postpersist methods are not called on embedded forms (sonata_type_collection). Is there a reason why is so?
How can I run those methods? 
(the postUpdate method is on the child Admin class, not entity class)

**Comment by maxdmg** [comment]
I ran into the same issue. I followed this recipe: https://sonata-project.org/bundles/admin/master/doc/cookbook/recipe_file_uploads.html and it turns out that ```prePersist``` and ```preUpdate``` events on ```ImageAdmin``` class are never triggered, although the recipe states:
> [...] When a file is uploaded (and nothing else is changed on the form) there is no change to the data which Doctrine needs to persist so no preUpdate event would fire. _To deal with this we hook into SonataAdmin’s preUpdate event (**which triggers every time the edit form is submitted**) and use that to update an Image field which is persisted._ This then ensures that Doctrine’s lifecycle events are triggered and our Image manages the file upload as expected.

Maybe there should be a note that you had to call those from parent Admin class. I'll try adding it.

**Comment by maxdmg** [comment]
Ups, my bad. Seems like the doc has a section describing how to use embedded admins.

**Comment by maxdmg** [comment]
Read https://sonata-project.org/bundles/admin/master/doc/cookbook/recipe_file_uploads.html#advanced-example-works-with-embedded-admins

**Comment by bobemoe** [comment]
OK, i found another discussion:
https://github.com/sonata-project/SonataAdminBundle/issues/1400
which leads to some documentation and an example:
https://sonata-project.org/bundles/admin/master/doc/cookbook/recipe_file_uploads.html#advanced-example-works-with-embedded-admins

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.

**Comment by Koc** [comment]
@core23 yes, it still occurs

**Comment by core23** [comment]
Can you please use update this issue using the new issue template.

**Comment by jordisala1991** [comment]
Since this one is a subset of #1502 we can close one and keep ony the other to focus the discussion on one place.

Closing. If you think this one is not related to #1502 please ping me to reopen
