### ISSUE TITLE
ORA-01791

### ISSUE THREAD

**Issue by laherreria** [sonata-project/SonataAdminBundle#1403]
In vendor/sonata-project/doctrine-orm-admin-bundle/Sonata/DoctrineORMAdminBundle/Datagrid/ProxyQuery.php on lines 83 and 84 the select of a query is substituted with a DISTINCT entity.id
```
        $queryBuilderId->resetDQLPart('select');
        $queryBuilderId->add('select', 'DISTINCT ' . $select);
```

This causes an ORA-01791 error in Oracle when there's an ORDER BY, because, when there's a SELECT DISTINCT query with an ORDER BY clause, Oracle expects all the ORDER BY items to be constants, SELECT list expressions, or expressions whose operands are constants or SELECT list expressions.

**Comment by core23** [comment]
If this is an active issue, please reopen @laherreria
