### ISSUE TITLE
appendFormFieldElement: OneToMany relation deleted when adding a new element

### ISSUE THREAD

**Issue by marco-loche** [sonata-project/SonataAdminBundle#1411]
When a user click on "Add new" and there is a relation of the same type marked as delete, the children object will be removed from the new embedded form built by appendFormFieldElement. 
Moreover there will be 2 new relations (embedded forms) instead of 1.

IMHO the deletion should occur only after the user clicks on the update button and not when he tries to add a new element to the form

This is my $formMapper configuration :
```
 ->add('objects',
                    'sonata_type_collection',
                    array(
                        'by_reference' => false
                    ),
                    array(
                        'edit' => 'inline',
                        'inline' => 'table'
                    ))
```

Could be related to #766  #931

**Comment by core23** [comment]
If this is an active issue, please reopen @marco-loche
