### ISSUE TITLE
Adding of Submit Form Type fails with "sonata_field_description" does not exist 

### ISSUE THREAD

**Issue by zavalit** [sonata-project/SonataAdminBundle#1416]
Hi,

after upgrade to Symfony 2.3. i tried to extend an actual FormMapper object with `add('save', 'submit')`.

but that threw an `InvalidOptionsException` with a following message:

```
The option "sonata_field_description" does not exist. Known options are: "attr", "block_name", "disabled", "label", "translation_domain"
```

**Comment by aaronkmiller** [comment]
I have the same question as pcoipeault. Is the "button" type also not supported?
