### ISSUE TITLE
Dynamic forms for sonata_type_collection

### ISSUE THREAD

**Issue by tiagojsag** [sonata-project/SonataAdminBundle#1429]
Hi,

Currently, sonata_type_collection does not support dynamic forms generated like so:
http://symfony.com/doc/current/cookbook/form/dynamic_form_modification.html

I've tried adding fields using both the FormBuilder, but the missing FieldDescription make it crash. Using FormMapper, the field doesn't get added to the form.

I'd like to implement the changes needed for this to work, I just don't know the optimal way to do so. I'd like to get some ideas on how this could be best implemented.

cheers

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @tiagojsag
