### ISSUE TITLE
Reorder() in sonata_type_collection not working

### ISSUE THREAD

**Issue by tiagojsag** [sonata-project/SonataAdminBundle#1454]
Using SonataMedia as example: 

Using FormMapper's reorder() in GalleryHasMedia's configureFormFields() only works in GalleryHasMedia's edit page. 

When the same form is rendered in Gallery's edit page (inside the sonata_type_collection type field), it doesn't work, and the fields are displayed in their initial order.

If anyone can point me to the problem, I'll be more than happy to do a PR, I just can seem to spot the source of the it atm :/

**Comment by core23** [comment]
If this is an active issue, please reopen @tiagojsag
