### ISSUE TITLE
Adding item to sonata_type_collection using drag and drop

### ISSUE THREAD

**Issue by 76200** [sonata-project/SonataAdminBundle#1459]
Hello,

I am using sonata_type_collection configured to add new items inline, what I think is really cool :)

The next thing I need to do is to allow user to drag'n'drop item somewhere into the form and fill some fields with some data instead of clicking the 'new' button and filling the textboxes one after another.

In sum, I want to allow user to 'compose' his form with pre-defined data.

I presume that I need to deploy javascript function "start_field_retrieve_UNIQUE_ID_items(this);", but don't have no idea what to do next.

That's all that I know for now :(
Could You please help me to figure out how to do that?

**Comment by core23** [comment]
If this is an active issue, please reopen @76200
