### ISSUE TITLE
Coices Translation just work with attribute translation_domain set in field configuration

### ISSUE THREAD

**Issue by christian-kolb** [sonata-project/SonataAdminBundle#1462]
I have the translation Domain set in my admin class through

    protected $translationDomain = 'MyTranslationDomain';

The labels of all fields are pulled autmaticaly. This does not work for the coices of a field of type "choice". I have to set the attribute 'translation_domain' explicit to the field again.

Is there a reason for this behaviour or is this a bug? If there's a reason, it would be great if it would be documented here: http://sonata-project.org/bundles/admin/master/doc/reference/translation.html

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @christian-kolb
