### ISSUE TITLE
sonata_type_collection breaks on 8th entry in IE9

### ISSUE THREAD

**Issue by Tocacar** [sonata-project/SonataAdminBundle#1468]
When adding new relations to an entity using sonata_type_collection (in my case, a Grant has many Reports), on IE, the 8th press of the 'Add New' button to add Reports to a Grant takes me out of the pop-up window to the Report edit page.  

All reports added to the Grant before this happens (if I haven't pressed Update on the Grant form) are then lost.  

This problem does not happen in FF or Chrome on Mac or PC, only in IE (I only tested on IE9)

**Comment by core23** [comment]
If this is an active issue, please reopen @Tocacar
