### ISSUE TITLE
sonata_type_collection that uses sonata_type_model_list - filter form breaks pagination in pop-up window

### ISSUE THREAD

**Issue by Tocacar** [sonata-project/SonataAdminBundle#1469]
In my application, I have a Grant entity that has many GrantInvestigator entities and each GrantInvestigator entity has an Investigator entity.

So, on my GrantAdmin form, I add GrantInvestigators.  In the GrantInvestigatorAdmin form that pops open, I use sonata_type_model_list to add an Investigator.  This gives me a paginated list of investigators in a pop-up window to choose from.  If I use the filter form to find the investigator I'm looking for, when I click the investigator's name, instead of it appearing in the field on the GrantInvestigatorAdmin form, I am transported to the InvestigatorAdmin edit form page (away from the Grant form).  This does not happen if I choose an investigator in the first page of the paginated list (it works as expected).

If, instead of using the filter form, I use the pager buttons to find the investigator I want to add, the same problem occurs.  In fact, if I click 3rd paginator button, I am transported away from the list in the pop-up window and the InvestigatorAdmin list page is displayed.  Obviously, something is wrong.

My current workaround is to use sonata_type_model instead of sonata_type_model_list but I thought I should let you know about the issue.

**Comment by core23** [comment]
If this is an active issue, please reopen @Tocacar
