### ISSUE TITLE
personalize the admin experience

### ISSUE THREAD

**Issue by lsmith77** [sonata-project/SonataAdminBundle#1474]
this might turn into some sort of meta ticket .. but I believe that one if the big problems of CMS is that they need to offer a billion features but most users only use a handful. however different users use totally different parts. so while some might be responsible for writing new text, others are responsible for restructuring content and yet others simply add new entries to a few specific pages.

So what I am suggesting here is to optionally collect metrics about what "features" are used. Features can be forms but I guess it could also be used for reports etc. As such there would be a need for an API to add entries.

This in turn could then be used to for example create a dashboard block that just contains direct links to such features: f.e. if the admin tool has 40 lists/forms .. then this block would just list the 2-3 that the given user has used in the past. Actually if the user always edits the same page (f.e. about page), then it would provide a direct link to the edit form of the about page.

**Comment by core23** [comment]
If this is an active issue, please reopen @lsmith77
