### ISSUE TITLE
(ajax) sonata_type_collection does not care for elements javascript

### ISSUE THREAD

**Issue by tautrimas** [sonata-project/SonataAdminBundle#1489]
Create an Article entity that uses GenemuFormBundle Select2 element. ArticleAdmin will display an element correctly if one adds form_javascript(form) in the global template.

Then create one-to-many relationship to Article, and use sonata_type_collection to allow adding Articles to Publisher. This time, form_javascript(form) will output javascript for Article collection elements, however, it will not run the javascript for Article elements in any way after ajax fetches new Article form element. All Article elements that uses GenemuFormBundle will render incorrectly.

Workaround is to enable javascript for needed fieds manually after ajax call using (Coffeescript):

```coffeescript
        $(document).on("ajaxComplete", (event, xhr, settings) =>
            if settings.url.indexOf('append-form-field-element') isnt -1 \
            and settings.url.indexOf('some_id_of_a_field') isnt -1
                @onFormReload()
        )
```

**Comment by core23** [comment]
If this is an active issue, please reopen @tautrimas
