### ISSUE TITLE
No refresh after creation via popup in subclass case

### ISSUE THREAD

**Issue by tashanta** [sonata-project/SonataAdminBundle#1503]
When I create entities via popup in a many to one relation, the list is not refresh after post action.
I've got an error when i submit the refresh query .../get-form-field-element... (route sonata_admin_retrieve_form_element).
I think the 'subclass' parameter is missing in : 
 
```js
jQuery('#field_widget_{{ id }}').closest('form').ajaxSubmit({
                            url: '{{ url('sonata_admin_retrieve_form_element', {
                                'elementId': id,
                                'objectId':  sonata_admin.admin.root.id(sonata_admin.admin.root.subject),
                                'uniqid':    sonata_admin.admin.root.uniqid,
                                'code':      sonata_admin.admin.root.code
                            }) }}', ...
```

**Comment by rande** [comment]
This has been fixed a while ago: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/5054a3ea31df2366384e8447dc9e6e84909dea89
