### ISSUE TITLE
Docs: Clean up batch actions chapter

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#1533]
Improve [this chapter](https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/doc/reference/batch_actions.rst) and make it more accessible to newcomers by making the following changes:

- is there a way to set the custom list__batch template only in certain circumstances or only for certain Admins?

- 13.4 (core action logic) the example is a little unclear... coming from a DocctrineORM background you don't seem to be persisting anything and just doing delete(x[1..n]) then update(x[n])?? Can this example be made simpler?

- 13.4 if the parameter is null how do you access the items to manipulate? When would you do this and how?

Note the section numbers mentioned are based on the [rendered docs for this chapter](http://sonata-project.org/bundles/admin/master/doc/reference/batch_actions.html) on the sonata website.

**Comment by core23** [comment]
Docs have been refactored
