### ISSUE TITLE
Docs: Clean up advance chapter

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#1537]
Improve [this chapter](https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/doc/reference/advance.rst) and make it more accessible to newcomers by making the following changes:

- 17.2.1 show how you can do this (globally) in yml (if you can)

- if there are any other suggestions for adding to this page let me know!

Note the section numbers mentioned are based on the [rendered docs for this chapter](http://sonata-project.org/bundles/admin/master/doc/reference/advance.html) on the sonata website.

**Comment by core23** [comment]
Docs have been refactored
