### ISSUE TITLE
Docs: Recipe request: handling file uploads (important!)

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#1544]
This is a cookbook recipe request for...
- ~~a complete end-to-end example of managing file (e.g. image) uploads using DoctrineORM with SonataAdmin~~
- a complete end-to-end example of managing file (e.g. image) uploads using DoctrineODM with SonataAdmin
- a complete end-to-end example of managing file (e.g. image) uploads using Propel with SonataAdmin

This is a popular and common question around the web with various solutions. What is the best way to handle this in SonataAdmin? This particular issue is about directly uploading files to a single Admin class. For managing uploads with _embedded_ Admin classes see #1545, but perhaps both can be solved by a single contributor?

You can either make a ready-to-merge rst file or send me a hyperlink, document file, or detailed comment which I will then reformat and merge into the documentation.

See #1519 for details about the co-ordination of cookbook entries and other ways to contact me.

**Comment by AntonioCS** [comment]
@caponica commented on [19 Aug 2013 15:50 BST](https://github.com/sonata-project/SonataAdminBundle/issues/1544#issuecomment-22877398 "2013-08-19T14:50:18Z - Replied by Github Comment Enhancer"):
> It's live already, so you can see it here:
> 
> [http://sonata-project.org/bundles/admin/master/doc/reference/recipe_file_uploads.html](http://sonata-project.org/bundles/admin/master/doc/reference/recipe_file_uploads.html)
> 
> Or view the source file here:
> 
> [https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/doc/reference/recipe_file_uploads.rst](https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/doc/reference/recipe_file_uploads.rst)

None of these links work. Can you update the links please?

Thanks
