### ISSUE TITLE
Docs: Recipe request: sort a list view by multiple values (by default)

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#1548]
This is a cookbook recipe request for...
- how to sort a list view by multiple values (e.g. field1 DESC, field2 ASC) by default

In symfony 1.x admin generator you could define a custom `table_method` in your generator.yml and use that to do multi-column sort. How do you do something similar in SonataAdmin?

You can either make a ready-to-merge rst file or send me a hyperlink, document file, or detailed comment which I will then reformat and merge into the documentation.

See #1519 for details about the co-ordination of cookbook entries and other ways to contact me.

**Comment by mikeevstropov** [comment]
Why issue was closed? If it's not working???

``` php
array(
      '_sort_by' => array(
          array(
              'field'     => 'someField', // string will be replaced with a FieldDescriptionInterface obj
              'direction' => 'asc|desc'
          ),
          array(
              'field'     => 'otherField', // string will be replaced with a FieldDescriptionInterface obj
              'direction' => 'asc|desc'
          ),
      )
)
// > Expected argument of type "FieldDescriptionInterface", "array" given
```
and
``` php
protected $datagridValues = array(
    '_sort_order' => 'ASC',
    '_sort_by'    => 'p.root, p.lft'
);
// > Just not working without any error
```
Thank you @onema for your example. It's working.
``` php
public function createQuery($context = 'list')
/* $context argument is deprecated, but i can't remove it! */
{
    $proxyQuery = parent::createQuery('list');
    // Default Alias is "o"
    $proxyQuery->addOrderBy('o.root', 'ASC');
    $proxyQuery->addOrderBy('o.lft', 'ASC');
    
    return $proxyQuery;
}
```

**Comment by Tofandel** [comment]
@mikeevstropov Which version of the bundle are you using, because on stable 3.18.2 I can't find the method addOrderBy(), is it only on 4.dev ?

**Comment by hroux** [comment]
@mikeevstropov  It's better to use `$query->getRootAlias()` like this : 

public function createQuery($context = 'list')
{
    $proxyQuery = parent::createQuery('list');
    $proxyQuery->addOrderBy($proxyQuery->getRootAlias().'.root', 'ASC');
    $proxyQuery->addOrderBy($proxyQuery->getRootAlias().'.lft', 'ASC');

    return $proxyQuery;
}

**Comment by icedevelopment** [comment]
So is there any solution to keep 'sortable' => true in configureList while sorting by multiple fields at the same time in createQuery?
