### ISSUE TITLE
Docs: Recipe request: allow users to sort a list view by multiple values

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#1549]
This is a cookbook recipe request for...
- how to let a user sort a list view by multiple values (e.g. clicking a new field adds it to the sort order, instead of just replacing the previous choice)

You can either make a ready-to-merge rst file or send me a hyperlink, document file, or detailed comment which I will then reformat and merge into the documentation.

See #1519 for details about the co-ordination of cookbook entries and other ways to contact me.

**Comment by core23** [comment]
Docs are still missing
