### ISSUE TITLE
Docs: New section: Export functionality

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#1550]
When using SonataAdmin your list view shows options to export the data... but there's no mention of this in the current docs. What we need is a new chapter which covers:
- customisation options, e.g.
  - choose which formats to offer
  - customise the templates used for a given download format
  - control whether you export the current view only or the whole data set
- how to add a new format
- how to turn exports off completely
- how to control who sees these options and can execute the export
- any other options or relevant info

I'm new to SonataAdmin so I don't know what's possible with exports. I look forward to reading your docs to fill in this gap in my knowledge!

You can either make a ready-to-merge rst file or send me a hyperlink, document file, or detailed comment which I will then reformat and merge into the documentation.

See #1519 for details about the co-ordination of new documentation entries and other ways to contact me.

**Comment by ethernal** [comment]
@krewetka Any changes that you could add some info to the docs about Exports or show examples from your project? I am very interested in that, if I manage to learn I can add the docs myself I just need to know where to start and maybe few examples.

**Comment by rodrigobb** [comment]
@krewetka, it's quite an obscure feature, but export headers (labels) can be overwritten by using keys in getExportFields method. It can even be translated!!

I don't know where to modify Bundle doc by including this information, but you can code something like the following:
```
    public function getExportFields()
    {
        return array(
            'field label 1' => 'field1',
            $this->trans('field label 2') => 'field2',
            'field label 3' => 'field3',
            ...
        );
    }

**Comment by thoroc** [comment]
@rodrigobb actually looking at the output of ```$this->getModelManager()->getExportFields($this->getClass());```, I have found that it isn't an associative array as suggested. But thanks for pointing to the right direction. :)

**Comment by greg0ire** [comment]
3 years later is not to late I guess :P see #4029

**Comment by farwish** [comment]
Override `getDataSourceIterator` in your `XxxAdmin` controller in this way:
```
    // I will update `id` value to another mapped value in this function.
    public function getDataSourceIterator()
    {
        $iter = parent::getDataSourceIterator();
        $kv_map = $this->getContainer()->get('xx.service.xx')->getMap();
        $data = [];
        foreach ($iter as $current) {
            // php iterator value can not be updated by reference, so we do below.
            $tmp = $current;
            $tmp['id'] = $kv_map[ $current['id'] ] ?? ' ';
            $data[] = $tmp;
        }

        $iterator = new IteratorCallbackSourceIterator(new \ArrayIterator($data), function($iterator_current) {
            return $iterator_current;
        });

        return $iterator;
    }
```
It works fine.

Other, your also can override `exportAction` function in `XxxAdminController` to rewrite `$this->admin->getDataSourceIterator`.
