### ISSUE TITLE
Replace context and type literals with constants (as used in getLabel())

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#1559]
There are lots of literals used in the code to refer to the context and type when calling ``getLabel()``. For example:

    // In SonataAdminBundle\Admin\Admin.php
    $this->trans($this->getLabelTranslatorStrategy()->getLabel(
      'dashboard', 
      'breadcrumb', 
      'link'
    ), array(), 'SonataAdminBundle')

These literals, such as 'breadcrumb' and 'link' (and the 'SonataAdminBundle' one too), could be replaced by consistent references to a single class constant to make the code more robust.

**Comment by core23** [comment]
If this is an active issue, please reopen @caponica
