### ISSUE TITLE
Setting a boolean filter to false by default

### ISSUE THREAD

**Issue by jpetitcolas** [sonata-project/SonataAdminBundle#1569]
I am trying to generate a datagrid with an entity having a  `read` boolean field. I would like to filter on this property, setting it by default to false.

So, I added the following to my Admin class:

``` php
protected $datagridValues = array(
    'read' => array('value' => false),
);
```

Yet, it does not seem to work. The generated select list is the following:

``` xml
<select id="filter_read_value" name="filter[read][value]" class="span8">
    <option value=""></option>
    <option value="1">oui</option>
    <option value="2">non</option>
</select>
```
I suppose this is normal, as value for false would be 0, which is the empty option.

So, I used some constants such as:

``` php
const STATUS_READ = 1;
const STATUS_UNREAD = 2;
```

It works, but I am wondering if there is any proper solution to avoid these two unnecessary constants?

If not, what do you think about bringing a patch to solve it?

**Comment by webdevilopers** [comment]
Please have a look at an example that I am currently adding to the docs:
https://github.com/sonata-project/SonataAdminBundle/issues/2607

Use can use the existing constants of the filter type itself:
https://github.com/sonata-project/SonataCoreBundle/blob/master/Form/Type/BooleanType.php#L22-24
https://github.com/sonata-project/SonataCoreBundle/blob/master/Form/Type/EqualType.php#L21-23

Your could should look something like:
```php
use Sonata\CoreBundle\Form\Type\EqualType;
use Sonata\CoreBundle\Form\Type\BooleanType;

protected $datagridValues = array(
    'read' => array(
        'type' => EqualType::TYPE_IS_EQUAL // => 1 - forcing an `=` operator, not required in your case
        'value' => BooleanType::TYPE_NO // => 2
    ),
);
```

As mentioned we are recently updating docs with this.

**Comment by jpetitcolas** [comment]
Thanks for the answer. Unfortunately, I can't test it currently, as I have currently no project with such a case (it was a long time since I posted the issue). Closing it then.
