### ISSUE TITLE
Adding new item for 1-n entities works very slow

### ISSUE THREAD

**Issue by Koc** [sonata-project/SonataAdminBundle#1585]
There is post request for each new item `/_admin/core/append-form-field-element?code=metal.demands.admin.demand&elementId=s521343a3035f5_demandItems&objectId=12&uniqid=s521343a3035f5` and it works very slow.

Why we couldn't use form prototype for rendering new items?

**Comment by lukepass** [comment]
Same problem here, adding a new line is incrementally time consuming (about 200ms each row). Any solution?
