### ISSUE TITLE
array_combine() error

### ISSUE THREAD

**Issue by poneymagique** [sonata-project/SonataAdminBundle#1605]
Hello i have this exception when i try ad many to many

An exception has been thrown during the rendering of a template ("Warning: array_combine() [<a href='function.array-combine'>function.array-combine</a>]: Both parameters should have an equal number of elements in D:\wampserver\www\mumart_artsper\vendor\sonata-project\doctrine-orm-admin-bundle\Sonata\DoctrineORMAdminBundle\Model\ModelManager.php line 179") in "SonataAdminBundle:CRUD:edit.html.twig"

Here is my code

->add('galerieAdresses', 'sonata_type_model_list', array(
                'by_reference' => false,
                'required' => false
            ), array(
                'edit' => 'inline',
                'inline' => 'table',
                'sortable'  => 'position',
            ))

-----
in galerieadresses:

 table: galerie_adresses
    id:
        galerie:
          associationKey: true
        adresse:
          associationKey: true

-----

in galerie:
  galerieAdresses:
        targetEntity: GalerieAdresses
        mappedBy: galerie

---
in adresse:

 oneToMany:
      galerieAdresses:
        targetEntity: GalerieAdresses
        mappedBy: adresse

I really dont find how to solve it

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version.

If this is still present, feel free to reopen this issue @poneymagique

**Comment by jorenvh1** [comment]
Having the same issue, is there a fix?
