### ISSUE TITLE
Fuzzy documentation on custom columns

### ISSUE THREAD

**Issue by unusorin** [sonata-project/SonataAdminBundle#1609]
Hi guys,
I want to create a new column and display a custom value in that field depending on the subject. How I do that ? The only related things I found were related to custom templates for column fields. 

Thanks

**Comment by core23** [comment]
If this is an active issue, please reopen @unusorin

**Comment by unusorin** [comment]
Haha .. I will. More than 2 years passed since I've submitted this issue.

**Comment by core23** [comment]
That's why I closed this ;) No response in the last years
