### ISSUE TITLE
One-to-many file input are being reset

### ISSUE THREAD

**Issue by ZloeSabo** [sonata-project/SonataAdminBundle#1618]
Hello!
I'm using embedded form to add images for my entity.
Despite of form look which suggests adding lots of entries and then saving them all with one "save" button click, it doesn't work that way with files.

Every time I press "add" button js requests sonata_admin_append_form_element route with existing form as a parameter and server side code adds new row to it. Then js overwrites form with new one. That behavior is OK for usual input types like text, checkboxes, etc.
But when it comes to file inputs, they're all empty when returned back from server (for security reason I suppose). So I have to press "save" every time before I add new row.

I will appreciate some help by your advice or some code changes to handle multiple upload.

Thanks.

**Comment by krewetka** [comment]
I manged to find javascript workaround for that. It's far from optimal but it's better than nothing.

Is there any plan to fix this issue? I see it's been more than a year already and nothing has changed.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
