### ISSUE TITLE
sonata_type_collection fields are reset after new row add [delete]

### ISSUE THREAD

**Issue by tautrimas** [sonata-project/SonataAdminBundle#1628]
Previously discussed here: https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/issues/160

To summarize:
1. Add two a row to sonata_type_collection
2. Mark row for deletion
3. Add another row
4. First row will have it's values blanked and delete checkbox will be cleared

Expected behavior: 
First row must retain its values and delete checkbox must be checked.

This bug persist at least in https://github.com/sonata-project/SonataAdminBundle/commit/d53e38a. What is strange, is that if global form submit fails with validation error, deleted rows fields are preserved after the form is reloaded to display (any) error. 

I can help fixing it. Does anybody have any idea on the reason behind this bug?

**Comment by pulzarraider** [comment]
Thank you for reporting the issue. The reloading whole `sonata_type_collection` rows is mentioned also in #1304. So I am closing this issue.
