### ISSUE TITLE
Alternative route/url method

### ISSUE THREAD

**Issue by goetas** [sonata-project/SonataAdminBundle#1641]
Hi everybody!
I'm here to propose a little change inside admin bundle.

Currently route name/url generation is done using `getBaseRoutePattern()` and `getBaseRouteName()` methods .

They uses `$this->class` to crate valid route names (https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Admin.php#L852). 
Having an entity `User` a generated url looks like `user/list`, generated name looks like `admin_bundle_user_list`.

**Changing  `$this->class` to  `get_class($this)`  will allow to have multiple admins for same entity** (https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Admin.php#L852).

Generated url should be  `useradmin/list` and generated should be `admin_bundle_user_list`.

Can be a good idea?

**Comment by core23** [comment]
If this is an active issue, please reopen @goetas
