### ISSUE TITLE
"new" action from sonata_type_collection fail with error "Entities passed to the choice field must be managed"

### ISSUE THREAD

**Issue by Cethy** [sonata-project/SonataAdminBundle#1659]
With a one-to-many relation (Foo 1:* Bar) and a form like this :
```php
class FooAdmin extends Admin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('bars', 'sonata_type_collection', array(), array(
                'edit' => 'inline',
                'inline' => 'table',
                'sortable'  => 'position'
            ))
    }
}
```
When I create a new Foo entity and I click on the "new Bar" button, I get a 500 error with the message "Entities passed to the choice field must be managed".

What I get from this is the Foo entity should be persisted before doing whatever "new Bar" do.

It's on symfony2.0, but I didn't find anything related to this so I except it to do the same on earlier versions.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @Cethy

**Comment by Cethy** [comment]
@core23 Sorry, I don't work on the project anymore.
