### ISSUE TITLE
Catchable Fatal Error: Argument 1 passed to Symfony\Component\Form\FormRenderer::setTheme() must be an instance of Symfony\Component\Form\FormView, null given...

### ISSUE THREAD

**Issue by DjangoFR** [sonata-project/SonataAdminBundle#1662]
Catchable Fatal Error: Argument 1 passed to Symfony\Component\Form\FormRenderer::setTheme() must be an instance of Symfony\Component\Form\FormView, null given, called in /home/user/work/project/vendor/sonata-project/admin-bundle/Sonata/AdminBundle/Controller/HelperController.php on line 143 and defined in /home/user/work/project/vendor/symfony/symfony/src/Symfony/Component/Form/FormRenderer.php line 68 

``` php
protected function configureFormFields(FormMapper $formMapper)
{
        $query = $this->getModelManager()->createQuery('Company\CoreBundle\Entity\EventGroup', 'event_group');
        $query->orderBy('event_group.name', 'ASC');
        $query->where("event_group.provider = 0 ");

            $formMapper
                ->with('Groups')
                ->add('parentGroups', 'sonata_type_model', array(
                        'class' => 'Company\CoreBundle\Entity\EventGroup',
                        'expanded' => true,
                        'multiple' => true,
                        'query' => $query,
                        'required' => false,
                        'label' => 'Parent groups',
                        'read_only' => false
                    )
                )
                ->end();
}
```

Trying to create new "parent group" from "popup subform" works, but site does not reaod (after closing popup subform) and firebug shows the above error:

"NetworkError: 500 Internal Server Error - http://project.user.local.office/app_dev.php/admin/core/get-form-field-element?elementId=s523c1bb8a1027_parentEventGroups&objectId=1254&uniqid=s523c1bb8a1027&code=company.admin.admin.eventgroup"

**Comment by johndev182** [comment]
I encountered this error as well. Any updates on this?

**Comment by jlamur** [comment]
@johndev182 Could you please provide a stack trace and the list of your packages / versions installed ?

**Comment by Tobur** [comment]
I know how to reproduce and fix this bug.

Put break point here (AdminHelper):

```
    /**
     * @param string $elementId
     *
     * @return null|FormView
     */
    public function getChildFormView(FormView $formView, $elementId)
    {
        foreach (new \RecursiveIteratorIterator(new FormViewIterator($formView), \RecursiveIteratorIterator::SELF_FIRST) as $name => $formView) {
            if ($name === $elementId) {
                return $formView;
            }
        }
    }
```

And you can see why your formView is null.

In my case it was:
```
        $formMapper->tab('General')
            ->with('Main data')
                ->add('name')
            ->end()
            ->end();

        if (!$this->isRefer() {
              //here I dynamically added field for collection tab
              // it was add in popup and doesn't add in list action
             // by this reason I got this issue
        }
```
I hope it will help some body like me.

**Comment by Tobur** [comment]
So fix was, ugly but it will help:

```
        $route = $this->getRequest()->attributes->get('_route');

        if (!$this->isRefer() || $route === 'sonata_admin_retrieve_form_element') {
```
