### ISSUE TITLE
With active "Select2" (default) - Dropdown in the embedded form not updated anymore!

### ISSUE THREAD

**Issue by greenphp** [sonata-project/SonataAdminBundle#1694]
I have an ProductAdmin with embedded ProductHasItemsAdmin. In this ProductHasItemsAdmin, you can add new Items.

**Expected behaviour:**
- Click Button "Add new" in the embedded ProductHasItemsAdmin Form
- In the opened ItemAdmin Layer create a new Item "TestItemA" and Save
- ItemAdmin Layer  is closed and "TestItemA" is selected in the Dropdown of the embedded ProductHasItemsAdmin.

**Behaviour:**
- Dropdown of the embedded ProductHasItemsAdmin is not updated!

After **disabling use_select2** option in the **config.yml**, everything **work like expected**.

```
sonata_admin:
    options:
        use_select2: false
```

This is how i embed the ProductHasItemsAdmin in my **ProductAdmin** form:
```
->add('productHasItems', 'sonata_type_collection', array(), array(
  'sortable'  => 'position',
  'edit' => 'inline',
  'inline' => 'table',
))
```

**Comment by sfavot** [comment]
same problem

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @greenphp
