### ISSUE TITLE
ckeditor - field type 'ckeditor' not persisted while saving an embedded form!

### ISSUE THREAD

**Issue by greenphp** [sonata-project/SonataAdminBundle#1695]
I have 3 admin/entities. ProductAdmin, ProductHasAdmin and ItemAdmin.

In the forms for ProductAdmin and ItemAdmin i´ve the **field 'article'** set to **type 'ckeditor'**

**ProductAdmin**
```
->add('article', 'ckeditor')
```

**ItemAdmin**
```
->add('article', 'ckeditor')
```

If i create a new Product and Item directly, the field 'article' is persisted to the database!

**PROBLEM**

I have an ProductAdmin with embedded ProductHasItemsAdmin. In this ProductHasItemsAdmin, you can add new Items.

If you create a new Item, a overlay with the ItemAdmin opens. Every looks like expected. (ckeditor rendered correctly, input is possible)

After saving the Item Entity, **every field is stored** to the database **except the field 'article'**

**Test**

As an test i passed the context from the ProductHasAdmin to the ItemAdmin and **changed the 'article' field to type 'textarea' for the embedded** ItemAdmin. **If textarea is set, the field is stored like expected!**

In ProductHasAdmin ()
```
->add('item', 'sonata_type_model', array(), array(
  'link_parameters' => array(
    'context' => 'embedded'
  ),
))
```

In ItemAdmin (configureFormFields)
```
$articleFieldType = $this->getRequest()->get('context') == 'embedded' ? 'textarea' : 'ckeditor';
...
->add('article', $articleFieldType, array())
```

**Comment by dotlabel-gonzalo** [comment]
Hi,

If you are using IvoryCKEditorBundle you can use:

    ivory_ck_editor:
        input_sync: true

(https://github.com/egeloen/IvoryCKEditorBundle/blob/master/Resources/doc/usage.md#synchronize-the-textarea)

Cheers

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @greenphp
