### ISSUE TITLE
"sonata_type_model_list" - Delete Button don´t work - Point to a 404!

### ISSUE THREAD

**Issue by greenphp** [sonata-project/SonataAdminBundle#1702]
In my Admin:
```
$formMapper->add('item', 'sonata_type_model_list');
```

If i **click the DELETE Button**, i get a **404** Not Found.

The following route is not found: http://epicform.dev/app_dev.php/admin/core/get-short-object-description?objectId=&uniqid=s524d727679339&code=sonata.admin.item

All buttons for **"List" and "Add new" working perfectly**. Only the delete dont work.

Maybe this **issue is related**: https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/issues/55

**Comment by core23** [comment]
If this is an active issue, please reopen @greenphp
