### ISSUE TITLE
Feature Request: Embed Form "Min / Max" for "sonata_type_collection" (JS)

### ISSUE THREAD

**Issue by greenphp** [sonata-project/SonataAdminBundle#1704]
I don´t found this option after searching a little bit. Can i add Feature Requests here in the Issues?

If i open a new Form, i like to have for example 5 **forms already embedded / open** by default **"embed_min"**. (I´m a little bit lazy. Otherwise i have to hit 5 times the Button "Add new"!)

Also i love to see, if after **"embed_max"**, i cannot add new Forms by "Add new" Button (because disabled).

```
->add('bundleItems', 'sonata_type_collection', array(),
    array(
        'sortable'  => 'position',
        'edit' => 'inline',
        'inline' => 'table',
        'embed_min' => 5, // by default, 5 forms are embedded
        'embed_max' => 10 // maximum 10 forms, after the 9th, the "Add new" button is removed!
    )
)
```

If a Entity have already more embedded entities (e.g. 20) than "embed_max", this is no problem. All are 20 are visible.

No need to validate! This is done by the form/entity/whatever ...

Found this Idea/Commit "Added limit to the number of elements added with sonata_type_collection" by tiagojsag
https://github.com/tiagojsag/SonataDoctrineORMAdminBundle/commit/9f34a78376556dbd534c28959d2210f05451929f

![embed-form-min-max-sonata_type_collection](https://f.cloud.github.com/assets/827658/1261995/2ea2bab2-2c38-11e3-898c-839f90e2dbae.png)

**Comment by core23** [comment]
Can you provide a PR? @greenphp
