### ISSUE TITLE
Update jQuery Form Plugin "jquery.form.js"

### ISSUE THREAD

**Issue by camya** [sonata-project/SonataAdminBundle#1729]
The version of the "jquery.form.js" in the SonataAdmin project is 2.64 (25-FEB-2011)

The latest version available is 3.44.0-2013.09.15 http://malsup.com/jquery/form/#download

Updating to the new version fixes the problems with "Uncaught ReferenceError: jQuery is not defined".

Also the complete page is not reloaded on ajaxSubmit() in field_dialog_form_action_*()
(see edit_orm_many_association_script.html.twig)

**Comment by barik94** [comment]
how can I update jquery.form.js if it is in vendors?
