### ISSUE TITLE
sonata_type_collection not works properly with file upload.

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#1731]
The `sonata_type_collection` field type does't works properly when you have a `file` field type in the Admin child.

If you add a row, select a file, and add a row again, the file field of the first row is reset.

Is at an issue or I did it wrong ?

Here my parent `ProjectAdmin` class:

``` php
class ProjectAdmin extends Admin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $context = $this->getPersistentParameter('context');

        $formMapper
            ->add('name')
            ->add('description')
            ->add('illustrations', 'sonata_type_collection',
                array(
                    'by_reference'      => false,
                    'mapped'            => true,
                ),
                array(
                    'edit'              => 'inline',
                    'inline'            => 'table',
                    'link_parameters'   => array('context' => $context),
                ))
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('name')
        ;
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('name')
        ;
    }

    public function toString($object)
    {
        return $object->getName();
    }
}
```

And my child `ProjectIllustrationFileAdmin`:

``` php
class ProjectIllustrationAdmin extends Admin
{
    protected function configureRoutes(RouteCollection $collection)
    {
        $collection
            ->remove('list')
            ->remove('batch')
            ->remove('edit')
            ->remove('delete')
            ->remove('show')
            ->remove('export')
        ;
    }

    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('image', 'file', array(
                'required'      => $this->getSubject() === false || $this->getSubject()->getImagePath() === null
            ))
        ;
    }

    public function showIn($context)
    {
        if ($context === Admin::CONTEXT_DASHBOARD) {
            return false;
        }

        return parent::showIn($context);
    }
}
```

Thanks.

**Comment by beono** [comment]
Yep, very disappointing issue.
Obviously, submitting data every time you add new field has a number of downsides.
Especially when you attach large files.
It seems, the only way to overcome this issue is to use custom field type and render field by yourself

**Comment by luizsoliveira** [comment]
@beono and @Soullivaneuh you were able to resolve this problem?

**Comment by beono** [comment]
@luizsoliveira , 
We created custom field type, custom field view and custom handler for images.

**Comment by luizsoliveira** [comment]
@beono can you share this code?

An interesting proposal would be integrate the OneUpUploaderBundle with SonataAdminBundle.

https://github.com/1up-lab/OneupUploaderBundle

**Comment by beono** [comment]
@luizsoliveira ,

I really want to do that, but our code is tight coupled with our project now.
I'll do my best.

**Comment by fatmah** [comment]
@rand I use sonataMediaBundle and I have the same problem; if i try to add three new element, files of the first one  are removed after the click add for the third one

**Comment by sujayjaju** [comment]
+1
Is there a way to make it remember the file selection after reloading the form when a new row is added?
