### ISSUE TITLE
Move, Hide, Show, Fix table columns in Sonata Admin Bundle

### ISSUE THREAD

**Issue by amanvarshney** [sonata-project/SonataAdminBundle#1740]
i want to implement that independent list to control the table i.e moving the list items can move table columns, and clicking the ± shows/hides the columns. How can i implement this in sonata admin bundle list mapper.???

You can see the demostration via clicking on the link.
http://trentrichardson.com/examples/jQuery-Powertable/

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version.

If this is still present, feel free to reopen this issue @amanvarshney
