### ISSUE TITLE
Unexpected call to entity method "_batch()" when rendering a list

### ISSUE THREAD

**Issue by Faustop** [sonata-project/SonataAdminBundle#1752]
When fetching the values for the entity fields to render a list, an arbitrary method "_batch()" of the entity is improperly called.

Note: I'd like to write a unit test case for this issue but the abstract class Admin class have no unit testing. Should I create a separate issue for the lack of unit testing?

**Comment by core23** [comment]
If this is an active issue, please reopen @Faustop
