### ISSUE TITLE
EditSession functionality

### ISSUE THREAD

**Issue by zhil** [sonata-project/SonataAdminBundle#1767]
@rande We have a problem in our admin area - we have complicated entities and multiply admin users.
If use X start edit entity A, then user Y start edit entity A, then user Y save entity A, then user X save entity A - we got corrupted entity - long story, but the only way to fix it - do not allow anybody to edit entity A if some user already doing it.

We have implemented functionality like EditSession - each time when user open some entity for editing - its locked for him for 15 minutes. During that time other users cant edit this entity. After 15 minutes new session can be created, if it will be created - "old" user will not be able to save his changes without reloading edit page.

We can add this functionality to the core SonataAdminBundle, will you accept PR?

**Comment by core23** [comment]
If this is an active issue, please reopen @zhil
