### ISSUE TITLE
sonata_type_model_list doesn't set default value

### ISSUE THREAD

**Issue by brunoroux** [sonata-project/SonataAdminBundle#1770]
I have two entities, one called Souscription that has OneToMany relationship with Jeton

Here is how the two admin form are defined : 

In SouscriptionAdmin :

```php
$formMapper
             ->with('Jetons')
                ->add(
                    'jetons',
                    'sonata_type_collection',
                    array(
                        'required' => false,
                        'by_reference' => false,
                    )
                )
            ->end()
```

In JetonAdmin :

```php
$formMapper
            ->add('souscription', 'sonata_type_model_list')
```

When I edit a Souscription and try to add him a new Jeton, default value is not set for said souscription.

If I change my JetonAdmin to use sonata_type_model instead of sonata_type_model_list, default value is set.

It seems like sonata_type_model_list doesn't set default value in this case.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @brunoroux
