### ISSUE TITLE
How to use max() or sort_by on a sort_field_mapping?

### ISSUE THREAD

**Issue by spezifanta** [sonata-project/SonataAdminBundle#1783]
I have a ManyToOne association and added a new column to my Datagird like this:
```
$listmapper
    ->add(
        'laste_date',
        null,
        array(
            'label' => 'label.last_date',
            'sortable' => true,
            'sort_field_mapping' => array('fieldName' => 'startTime'),
            'sort_parent_association_mappings' => array(array('fieldName' => 'events', )),
            'template' => 'XeedeeIxAdminBundle:CRUD:list_event_group_last_date.html.twig'
        )
    )
}}}
```
This way I can sort my gird via an association field. Howerver the association is sorted ASC und I would like it be to sorted DESC.

Something like sort_by => [event.startTime, DESC] or sort by max(event.startTime) would be nice to have. How do I this?

**Comment by core23** [comment]
If this is an active issue, please reopen @spezifanta

**Comment by spezifanta** [comment]
Sorry, I am no longer assigned to this project. Have no chance of testing.

**Comment by OskarStark** [comment]
Thanks for the feedback @spezifanta
