### ISSUE TITLE
AutoComplete in Sonata admin bundle global Search 

### ISSUE THREAD

**Issue by amanvarshney** [sonata-project/SonataAdminBundle#1818]
Sonata Admin Bundle has a nice feature of global Search. It is very useful for end-user. But if you guys implements autocomplete functionality,it will be more useful.

**Comment by Soullivaneuh** [comment]
@amanvarshney Would you like to work on a PR?

**Comment by ju1ius** [comment]
Interesting idea. I'm curious to see how this will perform.

**Comment by OskarStark** [comment]
> Interesting idea. I'm curious to see how this will perform.

me too @ju1ius 😄

**Comment by greg0ire** [comment]
Reopen if you would like to work on this
