### ISSUE TITLE
Delete button doesn't work for "sonata_type_model_list".

### ISSUE THREAD

**Issue by drscre** [sonata-project/SonataAdminBundle#1827]
Ajax request which retrievs short object description fails with "Not found" since there is no _objectId_ after it is deleted:

/app_dev.php/admin/core/get-short-object-description?objectId=&uniqid=

This issue has already been referenced a couple of times, just duplicating once again to grab attention:
https://github.com/sonata-project/SonataAdminBundle/pull/1717
https://github.com/sonata-project/SonataAdminBundle/issues/1702

**Comment by core23** [comment]
If this is an active issue, please reopen @drscre
