### ISSUE TITLE
Ability to add validation constraints to data grid filters

### ISSUE THREAD

**Issue by benglass** [sonata-project/SonataAdminBundle#1834]
I am not able to add constraint violation messages to data grid filters (they do not appear in the form). This is related to https://github.com/sonata-project/SonataAdminBundle/pull/1833 which is the solution I added so I can use addViolation (not addViolationAt). Using $executionContext->addViolationAt the error messages do not appear with the fields. Here is my code (I know the validation is working but the messages are not associated with the right field.

```php
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {   
        $datagridMapper
            ->add('text', null, array(
                'field_options' => array(
                    'constraints' => new Callback(array(
                        'methods' => array(function($data, ExecutionContextInterface $executionContext) {
                                $executionContext->addViolationAt($executionContext->getPropertyPath(), 'Please enter an end date');
                            }   
                        })  
                    ))  
                ))

```

**Comment by Renrhaf** [comment]
up ?

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @benglass
