### ISSUE TITLE
Block Event

### ISSUE THREAD

**Issue by rande** [sonata-project/SonataAdminBundle#1835]
Hello,

The BlockEvent mechanism is now on the master, so we are ready to add event block ;)

// cc @nicolas-bastien

**Comment by core23** [comment]
@nicolas-bastien Can we close this?

**Comment by greg0ire** [comment]
> @nicolas-bastien Can we close this?

@nicolas-bastien reopen if this isn't fixed please.

**Comment by nicolas-bastien** [comment]
@greg0ire yes it's done since a long time !

Sorry I have missed the previous notification
