### ISSUE TITLE
AdminExtensionInterface getBatchActions?

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataAdminBundle#1841]
is there a particular reason the AdminExtensionInterface does not support getBatchActions? my use case would be to have the CmfCoreBundle PublishableExtension provide batch publish / unpublish actions. i guess one challenge would be how to route the batch to the right class, as the batch implementation seems to be a naming convention rather than a closure.

**Comment by core23** [comment]
Fixed in latest master
