### ISSUE TITLE
ManagerInterface & DoctrineBaseManager in Sonata\CoreBundle\Entity

### ISSUE THREAD

**Issue by virgileb** [sonata-project/SonataAdminBundle#1872]
Hi,

I'm a bit concerned about the location of the ManagerInterface and DoctrineBaseManager – Sonata\CoreBundle\Entity – as it may be parsed by the annotation driver. As a result the files could be included twice.

Best,

Virgile

**Comment by core23** [comment]
If this is an active issue, please reopen @virgileb
