### ISSUE TITLE
[RFC] Date/Time/DateTime javascript picker

### ISSUE THREAD

**Issue by pulzarraider** [sonata-project/SonataAdminBundle#1887]
Unfortunatelly html5 form type [`datetime` is not supported](http://caniuse.com/#feat=input-datetime) in all browsers. Datetime inputs (with option `'widget' => 'single_text'`) should have some mini calendar (datetime picker) which can be used as alternative to easily select date/time and helps to type correct date format.

It would save a lot of time of developers if SonataAdmin will come with default datetime picker available for all `single_text` date/time/datetime inputs. This default picker should be turned off in configuration if you have some already in your project to avoid conflicts.

Do you like this idea or do you think that this feature doesn't belong to default SonataAdmin?
There are many jquery and boostrap datetime pickers available. Which would you like to have in SonataAdmin?

**Comment by andyHobbs** [comment]
@AlmogBaku can leave only the choice of hours and minutes without the year?
