### ISSUE TITLE
[UX] Use buttons only for action otherwise use links

### ISSUE THREAD

**Issue by gagarine** [sonata-project/SonataAdminBundle#1888]
Everywhere buttons are used when is not an action.

For example:
- on listing page you have the an "edit" and "delete" button, both should be link as their is no direct action (you don't submit anythings, the delete has a confirmation page...)

-  on the confirmation page when you want to delete an entity. You have the "delete" button, this is correct has it's an action. But the "edit" button is not an action and should be a link.

- ...

This is a very basic UI rules than need to be follow.

The only exception I can think of is the "add a new" than I think can make sens to be a button even you just arrive to a form...

**Comment by core23** [comment]
If this is an active issue, please reopen @gagarine
