### ISSUE TITLE
Handle ACL in search

### ISSUE THREAD

**Issue by MrGreenStuff** [sonata-project/SonataAdminBundle#1893]
When [CoopTilleulsAclSonataAdminExtensionBundle](https://github.com/coopTilleuls/CoopTilleulsAclSonataAdminExtensionBundle) is installed the search don't work well the ACL list filtering don't have effect.

It's because the search handler add OR condition in the query without parenthesis around all filter condition. [Here the code](https://github.com/sonata-project/SonataAdminBundle/blob/master/Search/SearchHandler.php#L50).

#### Conclusion we have to add parenthesis around all filter conditions but i don't know how ?

If somebody know where filters conditions in inserted to the query please say me :)

**Comment by core23** [comment]
If this is an active issue, please reopen @MrGreenStuff
