### ISSUE TITLE
BUG : If field type date is not specified in configureFormFields() method

### ISSUE THREAD

**Issue by MrGreenStuff** [sonata-project/SonataAdminBundle#1894]
In the method configureFormFields() of an admin class if the field type 'date' is not specified then there is an error : 

#### Call to a member function format() on a non-object ..... DBAL/Types/DateType.php line 44

It's because in this case the default doctrine property type is not getted.

**Comment by core23** [comment]
If this is an active issue, please reopen @MrGreenStuff
