### ISSUE TITLE
Custom queries + group by

### ISSUE THREAD

**Issue by pmithrandir** [sonata-project/SonataAdminBundle#1900]
Hello,

I'm using sonata with a database that start to be complex, and I need to update my queries. 

I can do that obviously, but if I add a goupBy function, the count doesn't work anymore because it is not made correctly.

For a query like that : 
```
SELECT ticket.id, ticket.name
FROM ticket
WHERE name LIKE ('test%")
```
The query generated is currently : 
```
SELECT COUNT (DISTINCT ticket.id)
FROM ticket
WHERE name LIKE ('test%")
```

Which works.

But it could also be write like that : 
```
SELECT COUNT(*)
FROM (
  SELECT ticket.id, ticket.name
  FROM ticket
  WHERE name LIKE ('test%")
) query
```

The main advantage of the second solution would be if we start to add group by and having clause to the ticket.

Like that : 

```
  SELECT ticket.id, ticket.name, MAX(tr.resolution_date), COUNT(tr.id)
  FROM ticket
  JOIN ticket_resolution tr ON ticket.id = tr.ticket_id
  WHERE name LIKE ('test%")
  GROUP BY ticket.id, ticket.name
  HAVING tr.resolution_date> '2013-12-31 00:00:00'
```

The query generated by sonata actually doesn't works at all : 
```
  SELECT COUNT(DISTINCT ticket.id), COUNT(tr.id)
  FROM ticket
  JOIN ticket_resolution tr ON ticket.id = tr.ticket_id
  WHERE name LIKE ('test%")
  GROUP BY ticket.id, ticket.name
  HAVING tr.resolution_date> '2013-12-31 00:00:00'
```

Will generate a SQL alert for incorrect query formating.

The correct answer would be : 

```
SELECT COUNT(*)
FROM (
  SELECT ticket.id, ticket.name, MAX(tr.resolution_date), COUNT(tr.id)
  FROM ticket
  JOIN ticket_resolution tr ON ticket.id = tr.ticket_id
  WHERE name LIKE ('test%")
  GROUP BY ticket.id, ticket.name
  HAVING tr.resolution_date> '2013-12-31 00:00:00'
) query
```

I thought it was not possible with doctrine, but I realise inspecting the query from pagerfanta, the white october bundle, that they do it.
I checked a little bit and I think they are doing it here : 
https://github.com/whiteoctober/Pagerfanta/blob/master/src/Pagerfanta/Adapter/DoctrineORM/CountWalker.php

Maybe sonata could get inspired by this way to do it and to update the bundle ?

It would allow people to optimize muche more there queries and to have a whole possibility of filtering using sonata the datas.

Best regards,
Pierre Bonneau

**Comment by gianarb** [comment]
Same problem..
This is the stard query generatored by AdminBundle 
```sql
SELECT count(DISTINCT o.id) as cnt FROM event o LEFT JOIN o.shop s_shop LEFT JOIN o.vendor s_vendor LEFT JOIN o.brand s_brand LEFT JOIN o.categories s_categories
```
I modified createQuery method for listAction with a join and with a group by and this is the new query generated
```sql
SELECT count(DISTINCT o.id) as cnt FROM event o INNER JOIN r r BY r.event = o.id LEFT JOIN o.shop s_shop LEFT JOIN o.vendor s_vendor LEFT JOIN o.brand s_brand LEFT JOIN o.categories s_categories GROUP BY r.even
```
but doctrine trigger this exception `throw new NonUniqueResultException();` because the result is not scalar.

**Comment by webdevilopers** [comment]
Actually I havn't come across an acceptable solution yet either.
I suggested allowing / using Doctrine MIXED results inside the hydrator:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/399

I'm not sure if this will work, but maybe you could use a `WHERE id IN` subquery.
This will only SELECT those rows that have been grouped already inside the subquery.

This is something I tried to make use of a `MAX` statement:
```php
        $qb2 = $this->getModelManager()->getEntityManager('Plusquam\Bundle\ContractBundle\Entity\ContractState')->createQueryBuilder();
        $qb2->select('MAX(cs2.id)')
            ->from('Plusquam\Bundle\ContractBundle\Entity\ContractState', 'cs2')
            ->addOrderBy('cs2.date', 'desc')
            ->addOrderBy('cs2.createdAt', 'desc')
            ;
 
        $queryBuilder
            ->where($queryBuilder->expr()->orx(
                    $queryBuilder->expr()->in($alias .'.id', $qb2->getDql()),
                    $queryBuilder->expr()->eq('cs.state', ':state')
                ))
            ->setParameter('state', $value['value'])
        ;
```

Not sure if this will work with a `GROUP` on the subquery on the entity.id. But maybe on subentities or other aggregate fields.

**Comment by gianarb** [comment]
@webdevilopers but do you use this query to get a list of elements? 

Now I'm working to build a good query to add sum of reservation into the list of events..:)

**Comment by webdevilopers** [comment]
Yes I used it once overriding the `createQuery` query. Since this method did not accept my `HAVING` clause. Because just like `GROUP` these things get overriden by Sonata.
But conditions like `WHERE IN` would work for me. Most of the time I integrated them into `doctrine_orm_callback` filters.

**Comment by gianarb** [comment]
@webdevilopers this is my solution :)
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/297

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.

**Comment by er1z** [comment]
Still exists, exhausted by finding out how to make a workaround.
