### ISSUE TITLE
edit: remember currently opened tab on save

### ISSUE THREAD

**Issue by dbu** [sonata-project/SonataAdminBundle#1911]
after saving the page, we get a reload and end up on the first tab again. it would be nice to remember the currently opened tab and open on the same tab again after save.

/cc @benoitpointet

**Comment by Koc** [comment]
any news on this issue?

**Comment by OskarStark** [comment]
any news on this, i really need this feature :)

**Comment by Koc** [comment]
@OskarStark as you project member then you can open PR for this feature :)

**Comment by OskarStark** [comment]
@Koc i know, we implemented the feature in our project, but need to test this first with some customers

i will report any news later on

**Comment by ju1ius** [comment]
@pulzarraider This is indeed one way to do it. However changing the hash with `window.location.hash` adds an history entry each time you change the current tab. This can get annoying pretty quickly.

One way to avoid this kind of "history pollution" is to combine hash detection with `history.replaceState()`

**Comment by ju1ius** [comment]
```js
jQuery(document).on('click', '.sonata-ba-form .nav-tabs a', event => {
  history.replaceState({}, document.title, event.target.href));
});
```

**Comment by wadjeroudi** [comment]
@OskarStark any news ?

**Comment by nilov** [comment]
// show active tab on reload
    if (location.hash !== '' && location.hash.substring(1, 5) == 'tab_') {
        var currentTabNumber = location.hash.substring(5);
        var adminUniqid      = '{{ admin.uniqid }}';
    
        $('a[href="#tab_' + adminUniqid + '_' + currentTabNumber + '"]').tab('show');
    }
    
    // remember the hash in the URL without jumping
    $('a[data-toggle="tab"]').on('shown.bs.tab', function(e) {
        var tabName     = $(e.target).attr('href').substring(1);
        var tabParts    = tabName.match(/tab_\w+_(\d)/);
        var tabHashName = '#tab_' + tabParts[1];
    
        if(history.pushState) {
            history.pushState(null, null, tabHashName);
    
        } else {
            location.hash = tabHashName;
        }
    });
    
    // add the hash in action form when submit
    $('form').on('submit', function () {
        if (location.hash.substring(1, 5) == 'tab_') {
            $(this).attr('action', $(this).attr('action') + location.hash)
        }
    });

**Comment by core23** [comment]
Can you provide a PR @nilov ?

**Comment by nilov** [comment]
@core23 This is fast solution, it is not ready for repository.

**Comment by KacperKurek** [comment]
I used this code above and it still redirects to the first tab, what else I should do?
