### ISSUE TITLE
Links of associated entities in List view should point to show action, right ?

### ISSUE THREAD

**Issue by parijathakumar** [sonata-project/SonataAdminBundle#1916]
In the list view, in each record/row, the values of fields which are associated with other entities are promptly displayed as links. But the links are pointing to 'edit' action by default. Aren't they supposed to point to 'show' action by default ?

Anyway, how can I change them to point to 'show' action by default in the entire project ?

**Comment by 2b3ez** [comment]
Why is this issue closed while it is not solved ?
Your link pointed on the addIndentifier for the current admin but when an entity embed like a child in listmapper, the only link is edit.

```
'route'=>array('name'=>'show')
```

do not work and disable the link.

Could you explain me a way to make a working show link ?

Thanks !

**Comment by lukepass** [comment]
Thanks, the solution worked fine!
