### ISSUE TITLE
Array to String conversion error when trying to display array with custom template

### ISSUE THREAD

**Issue by smilesrg** [sonata-project/SonataAdminBundle#1928]
When I am trying to use custom template to display array in the list, I'm getting an exception:

ContextErrorException Array to string conversion in /home/ {path_to_my_working_copy} /app/cache/dev/twig/ea/2d/b7cae768d60eaf3012776f1c1aeb3f5a3a84fc399aee0a21c0baa0a1e92f.php line 83

the related code is:
```
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('keywords', 'array',  ['template' => 'AcmeDemoBundle:Admin:list_array.html.twig'])
            ->add('statuses', 'array', ['template' => 'AcmeDemoBundle:Admin:show_array.html.twig'])
        ;
    }
```
It doesn't matter what is inside that template: even if the file doesn't exists or it content is empty, I am getting that exception.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @smilesrg
