### ISSUE TITLE
Batch action translation context

### ISSUE THREAD

**Issue by markwilson** [sonata-project/SonataAdminBundle#1929]
When performing a batch action I get this message:-
> Confirm batch action 'action._delete'

`action._delete` should have been `action_delete` as far as I can tell. It looks like it's possibly an issue with the translator strategy. https://github.com/sonata-project/SonataAdminBundle/blob/master/Translator/UnderscoreLabelTranslatorStrategy.php

**Comment by pulzarraider** [comment]
Fixed in #2469, it will be included in the 2.3.1 version. Thank you for reporting the issue.
