### ISSUE TITLE
Image previews (taken from the cookbook recipe) do not work when embedding with sonata_type_collection

### ISSUE THREAD

**Issue by samyazza** [sonata-project/SonataAdminBundle#1956]
Hi!
Due to the much talked about problem with getSubject() returning the first object in a collection, when the embedded admin is inside a sonata_type_collection, the image previews won't properly appear:

```php
        if($this->hasParentFieldDescription()) { // this Admin is embedded
            // $getter will be something like 'getlogoImage'
            $getter = 'get' . $this->getParentFieldDescription()->getFieldName();
            // get hold of the parent object
            $parent = $this->getParentFieldDescription()->getAdmin()->getSubject();
            if ($parent) {

           /// this will return the image related to the first object in the collection
                $image = $parent->$getter();
            } else {
                $image = null;
            }
        } else {
            $image = $this->getSubject();
        } 
```

I've stumbled upon this problem when working on a project of my own. I have a QuizAdmin with a sonata_type_collection of QuizQuestions. I've tried adding the image admin as  a child to QuizQuestionAdmin, as well as added QuizQuestionAdmin as a child of QuizAdmin. Still, all my quiz questions have the same thumbnail picture as the first question in the admin panel. 

Is there a way I can work around this?

**Comment by core23** [comment]
If this is an active issue, please reopen @samyazza
