### ISSUE TITLE
configureListFields $listMapper->addDate() uses toString instead of getDate

### ISSUE THREAD

**Issue by olrandir** [sonata-project/SonataAdminBundle#1964]
This was introduced with our last update, we're currently running commit sha 6243ed9ee8b798284fbd3b0c938ff2aefec1a573.

We have a field 'date' in several entities, which is displayed in admin lists:
```php
protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
...
             ->add('date')
...
        ;
    }
```

With the latest update, this field started returning the object __toString function (confirmed this while debugging, just placed a print "test"; die(); and it never runs). This happens in all entities that have a 'date' field, and the only workaround we found was to create a getDateForAdmin() function and display that instead of the date field, like this:

```php
protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
...
             ->add('dateForAdmin', 'datetime', array('label'=>'Date'))
...
        ;
    }
```

Are we doing something wrong? Is there some deprecation warning we missed or something else?

**Comment by core23** [comment]
If this is an active issue, please reopen @olrandir
