### ISSUE TITLE
xeditable not working with boolean

### ISSUE THREAD

**Issue by jforet** [sonata-project/SonataAdminBundle#1968]
if you try to edit online a boolean field, it does not work.
to bypass this error, i put this code in HelperController.php

``` php
// tips for boolean
if($fieldDescription->getType() == 'boolean' && $value == 1)
{
    $value = true;
}
elseif($fieldDescription->getType() == 'boolean' && $value == 0)
{
    $value = false;
}
```

before

``` php
$propertyAccessor->setValue($object, $propertyPath, '' !== $value ? $value : null);
```

Moreover, i think this popin for boolean's field is not a good solution because when you want to change this value, you have to put false when it was true, or reverse. With this popin, you have to first-click, select reverse value and click-confirm. There are 3 actions where we want just one. 

What do you think ?

**Comment by silasjoisten** [comment]
Are there any other solutions? I tryed @Invis1ble 's solution and it's still not working.

**Comment by OskarStark** [comment]
Could this fix the problem?

https://github.com/sonata-project/SonataAdminBundle/pull/4369
