### ISSUE TITLE
Show Action documentation

### ISSUE THREAD

**Issue by codecowboy** [sonata-project/SonataAdminBundle#1972]
http://sonata-project.org/bundles/admin/master/doc/reference/action_show.html

The code in this section does not work or explain what it is doing in relation to the setup of an Admin class in the installation instructions. Why is a new class called ClientAdmin suddenly required?

http://sonata-project.org/bundles/admin/master/doc/reference/getting_started.html

If someone can explain to me how this integrates with the PostAdmin class in the earlier instructions, I will be happy to update the documentation.

**Comment by core23** [comment]
If this is an active issue, please reopen @codecowboy
