### ISSUE TITLE
Ignores attr definition in datagridFilter method

### ISSUE THREAD

**Issue by Tocacar** [sonata-project/SonataAdminBundle#1983]
I'm trying to add a class to a date filter field (definition below) but it is just ignored - am I doing this wrong?

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('title')
            ->add('description')
            ->add(
                'dateStart',
                'doctrine_orm_date',
                array(),
                'date',
                array(
                    'widget' => 'single_text',
                    'label' => 'Start Date',
                    'attr' => array('class'=>'calendar')
                )
            )
            ->add('dateEnd')
            ->add('isCompleting')
            ->add('isActive');
    }

**Comment by core23** [comment]
If this is an active issue, please reopen @Tocacar
