### ISSUE TITLE
Procedure to embed an entity into UserAdmin form

### ISSUE THREAD

**Issue by NelsonSR** [sonata-project/SonataAdminBundle#1985]
(This issue was already published in SonataUserBundle GitHub page a month ago: https://github.com/sonata-project/SonataUserBundle/issues/320. The advise given by  @rande was to use `admin_code` to fix the issue, but even so the error message still persists).

I've been trying to connect (or embed) two entities (Email and Phone) to the User entity in order to allow to the users to have more than just one email address and phone number.

```php
class UserAdmin extends Admin
{
    // more methods
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            // other fields
            ->with('Emails')
                ->add('emails', 'sonata_type_collection',
                    array(
                        'label' => 'Emails',
                        'cascade_validation' => true,
                        'by_reference' => false,
                    ),
                    array(
                        'edit' => 'inline',
                        'inline' => 'table',
                        'admin_code' => 'mercury.cargo_recognition.admin.email'
                    )
                )
            ->end()
            ->with('Phones')
                ->add('phones', 'sonata_type_collection',
                    array(
                        'label' => 'Phones',
                        'cascade_validation' => true,
                        'by_reference' => false,
                    ),
                    array(
                        'edit' => 'inline',
                        'inline' => 'table',
                        'admin_code' => 'mercury.cargo_recognition.admin.phone'
                    )
                )
            ->end()
        ;
    }
}
```

I'm using the same approach I've been using for months to embed forms in Sonata Admin Bundle, in this case one-to-many, but it's useless.

All the configuration in `config.yml` and `admin_sonata.xml` are OK, but if I put an `$email` property with the Doctrine annotation in the User class, Apache keeps trying for 3 minutes and a half to load an incomplete list. No matter if use or not the field in the list or the form, just use that property leads to same behavior.

There's some specific step not documented yet? (the official documentation covers until the 2.1 version).

I'm using SonataAdmin 2.2.9 and SonataUser 2.2.2 with Symfony 2.3.9.

All I get is the following error message, which is a kind of generic message, because it appears in many different situations:

``The current field `emails` is not linked to an admin. Please create one for the target entity : ``

The main obstacle in order to solve this issue is the lack of a proper error message.

**Comment by brunoreis** [comment]
Yep. +1 here. I also noticed that the setter is not called at this point. The trace is this: 

at FormContractor ->getAssociationAdminException ... at line 140   

at FormContractor ->getDefaultOptions ... at line 6254 

at FormMapper ->add ... at line 109

at XXXAdmin ->configureFormFields (object(FormMapper)) 
in kernel.root_dir/cache/dev/classes.php at line 2824   + 

at Admin ->defineFormBuilder (object(FormBuilder)) 
in ... at line 16   +

**Comment by rccc** [comment]
Hello,

in Sonata\DoctrineORMAdminBundle\Builde\FormContractor line 65 

```
        if (in_array($fieldDescription->getMappingType(), array(ClassMetadataInfo::ONE_TO_MANY, ClassMetadataInfo::MANY_TO_MANY, ClassMetadataInfo::MANY_TO_ONE, ClassMetadataInfo::ONE_TO_ONE ))) {
            $admin->attachAdminClass($fieldDescription);
        }
```

```
 $fieldDescription->getMappingType() is null as if Doctrine wasn't aware about field metada
```

```
php app/console doctrine:cache:clear-metadata
```

resolved the exception

**Comment by rccc** [comment]
Helo,

Also, one have to check this : http://stackoverflow.com/questions/27090270/onetoone-relation-with-sonata-type-admin-field-not-linked-to-an-admin

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @NelsonSR
