### ISSUE TITLE
MongoDB ReferenceMany manual sort solution

### ISSUE THREAD

**Issue by Thommas** [sonata-project/SonataAdminBundle#1988]
Hello,

I've been struggling a lot with sonata form types to find a working solution.

I want a quick & easy feature, and I have only two halves of the solution, can't find any nice solution.

I use MongoDB.

I have an Experience Class with : 

    /**
     * @MongoDB\ReferenceMany(targetDocument="Experience")
     */
    protected $experiences;

I have the methods (addExperience, removeExperience, getExperiences).

I have my ExperienceAdmin class with : 

    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('title')
            ->add('summary')
            ->add('xp')
            // CASE 1
            ->add('experiences', 'sonata_type_collection', array(
                'required' => false
            ), array(
                'edit' => 'inline',
                'inline' => 'table',
                'sortable' => 'position'
            ))
            // CASE 2
            ->add('experiences', 'sonata_type_model', array(
                'required' => false,
                'multiple' => true
            ))
        ;
    }

Let me explain why both CASE 1 and CASE 2 don't fit my needs.

CASE 1 : 

Great feature : I can sort existing sub-experiences !

But I can't create new sub-experience, if I "add new", MongoDB throws : 

    Cannot create a DBRef without an identifier. UnitOfWork::getDocumentIdentifier() did not return an identifier for class ThomasBullier\GlobalGenerationBundle\Document\Experience 

Besides there is no "add existing" option, this one I would need !

CASE 2 : 

Great feature : I can add existing experiences to sub-experiences !

But I can't sort them as it's a multiple select widget.

---

Conclusion : 

I need to code a whole bunch of AJAX/Controller to add a custom button in CASE 1 allowing me to "add existing" experience.

(This is ugly, I don't want to go custom over Sonata)

Am I missing something obvious there ?

For now I'll stick to CASE 2 and wait some day for a "manual sorting solution" so that MongoDB can store my references in the order I want.

Thank you for reading this !

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @Thommas

**Comment by Thommas** [comment]
Yup too old, hopefully it's better now.

Cannot test on master, the project is too old.
