### ISSUE TITLE
Form field with sortable enabled has conflict with Gedmo SortablePosition annotation

### ISSUE THREAD

**Issue by cincas** [sonata-project/SonataAdminBundle#1989]
Hi guys,

Kept trying to fix this issue for past few days.

Some details:

I have an entity called Recipe which has OneToMany relationship with another entity called MethodStep.

In Recipe.php

```
    /**
     * @var ArrayCollection(MethodStep)
     * @ORM\OneToMany(targetEntity="MethodStep", mappedBy="recipe", indexBy="position",cascade={"persist"}, orphanRemoval=true)
     * @Constraints\Count(
     *    min = "1"
     * )
     * @ORM\OrderBy({"position" = "ASC", "id" = "ASC"})
     */
    private $method;
```

and in MethodStep.php

```
    /**
     * @var integer
     *
     * @Gedmo\SortablePosition
     * @ORM\Column(name="position", type="integer", nullable=false)
     */
    private $position;
```

@Gedmo\SotablePosition annotation is working like a charme in my API bundle.

Here comes a problem with SonataAdminBundle

In RecipeAdmin.php, I defined methodStep as following definition.

```
            ->add(
                'method',
                'sonata_type_collection',
                array(
                    'by_reference' => false,
                    'cascade_validation' => true
                ),
                array(
                    'edit' => 'inline',
                    'inline' => 'table',
                    'sortable'  => 'position'
                )
            )
```

Background: For instance, I have 5 steps in a recipe

A 1
B 2
C 3
D 4
E 5

Scenario 1: if I just swipe b and c, then works fine, the result become
A 1
C 2
B 3
D 4
E 5

Scenario 2: I move B to between D and E, then the result become
A 1
C 2
D 3
E 4

element B will just disappear in front end.
But if you go to backend , you will see in position field, both E and B are marked as 4

I think the problem is caused by jQuery sortable widget in AdminBundle has updated B,C,D and E , and some how that make @Gedmo\SotablePosition confused 

Anyidea about how to fix this ?

I cant get rid of SortablePosition because I also use that in other places as well.

Thanks.

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. @cincas @Evgenas 

If this is still present, feel free to reopen this issue

**Comment by danaki** [comment]
No, it's not fixed in 3.x-dev.

Here's a part of admin code allowing inline sorting of related entities
```
                    ->add('videos', CollectionType::class, [
                        'by_reference' => false,
                    ], [
                        'edit' => 'inline',
                        'inline' => 'table',
                        'sortable' => 'position',
                    ])
```

Related entity looks like:
```
class ProductVideo
{
    // ...

    /**
     * @var Product
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Product\Product", inversedBy="videos")
     * @ORM\JoinColumn(name="product_id", referencedColumnName="product_id", nullable=false)
     * @Gedmo\SortableGroup
     */
    private $product;

    /**
     * @var int
     *
     * @ORM\Column(name="position", type="integer")
     * @Gedmo\SortablePosition
     */
    private $position;
    ...

```

However when I go to corresponding tab and attempt to drag and drop and save then it works but in the database some sorted entities have equal positions. For example if initially 4 related entities had positions accordingly 1, 2, 3, 4. After save ordering could become [4, 1, 2 1]. Can it be Gedmo/Sortable issue?

**Comment by DILL44** [comment]
I made a workaround:

config/packages/stof_doctrine_extensions.yaml
```yaml
stof_doctrine_extensions:
...
    orm:
        default:
            sortable: true
...
    class:
        sortable: App\Listener\SortableListener
```

src/Listener/SortableListener.php
```php
<?php

namespace App\Listener;

use Doctrine\Common\EventArgs;
use Gedmo\Sortable\Mapping\Event\SortableAdapter;
use Gedmo\Sortable\SortableListener as BaseSortableListener;

class SortableListener extends BaseSortableListener
{
        protected function processInsert(SortableAdapter $ea, array $config, $meta, $object)
        {
        }

        public function postFlush(EventArgs $args)
        {
        }
}
```
I'm waiting issue fixing
