### ISSUE TITLE
Delete function doesn't work when caching enabled

### ISSUE THREAD

**Issue by jeffersondarcy** [sonata-project/SonataAdminBundle#1996]
When I try to delete Items and press yes on the confirmation page the confirmation page gets reloaded again and no deletion happens. If I remove
$kernel = new AppCache($kernel);
from app.php everything works again

symfony 2.3.9 and 2.3.11
sonata dev-master (reference: 300bab3141fdaaa878dec6f1035480197bfc6584 in composer.lock)

**Comment by jakzal** [comment]
@rande what's wrong with AppCache in your opinion? Does admin bundle set any caching headers at all?

**Comment by rande** [comment]
@jakzal the AdminBundle does not set any cache headers. I just guess there are some edge cases with AppCache.
