### ISSUE TITLE
Checkbox field added in sonata_type_collection can be edited even though collection is read-only

### ISSUE THREAD

**Issue by Tocacar** [sonata-project/SonataAdminBundle#2003]
In parent admin class:

    ->add(
                'activities',
                'sonata_type_collection',
                array(
                    'by_reference' => false,
                    'label' => false,
                    'required' => false,
                    'btn_add' => false,
                    'type_options' => array('delete' => false),
                    'read_only' => true
                ),
                array(
                    'edit' => 'inline',
                    'inline' => 'table',
                )
            )

In ActivitiesAdmin class:

    ->add('Complete', 'checkbox', array('required' => false));

When viewing the embedded collection form in the parent form I can edit and successfully save the checkbox value, which obviously shouldn't be possible.

**Comment by jeremy-bruns** [comment]
+1 Same here.

**Comment by danielsippel** [comment]
@jeremy-bruns and me are on dev-master now and problem still occurs. we check if we can fix this issue.

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @Tocacar
