### ISSUE TITLE
$parentAssociationMapping add unexpected filter

### ISSUE THREAD

**Issue by gusdecool** [sonata-project/SonataAdminBundle#2020]
I have a class StudentRelative, this class is a child ( addChild() ) of Student.
When on StudentRelative i set property $parentAssociationMapping as 'student', it suddenly add unexpected student filter in dataGridFilter 
![screenshot](https://cloud.githubusercontent.com/assets/223657/2561859/b37ead78-b82d-11e3-8289-1d19818a28d5.jpg)

Is this a bug? if no, how do i remove that filter field?

**Comment by webdevilopers** [comment]
@gusdecool Could you try this feature recently implemented by @pulzarraider :
https://github.com/sonata-project/SonataAdminBundle/pull/2751

And see if forcing `'show_filter' => false` may force the filter to disappear.
