### ISSUE TITLE
the edit button on the Sonta interface / dashboard sent me to an empty page

### ISSUE THREAD

**Issue by belmasine** [sonata-project/SonataAdminBundle#2024]
Hi every body,

I learn from the tutorial jobeet arriving in the admin interface, when I click on the show button or the delete button they are ok, but if I click the edit button there is a problem in the CRUDCOntroller . php bug is on the line 
  / ** @ Var $ form \ Symfony \ Component \ Form \ Form * / 
         $ form = $ this-> admin-> getForm (); 
         $ form-> setData ($ object); 
it can not pass these two lines of code 

Thank you for your suggestions

**Comment by core23** [comment]
If this is an active issue, please reopen @belmasine
