### ISSUE TITLE
[RFC] Removing dependencies to assets => add bower.json

### ISSUE THREAD

**Issue by rande** [sonata-project/SonataAdminBundle#2036]
For now the SonataAdminBundle and other Sonata's bundles rely on external bundles to retrieve assets: jquery, bootstrap, etc ... 

This situation has been created 2 or 3 years ago when no "de-facto" standard for packaging management was available. Now, the situation changed, `bower` seems to be the tools to retrieve assets. 

Dropping support for those bundles creates a big issues: How many people are ready/can install bower (and nodejs) on there dev machine ?

This can be resolved by still using those bundles so the code can still be BC. However, the hard dependencies will be removed in `composer.json` (so the `sonata-project/jquery-bundle` must be defined in the main `composer.json`.

This will also required to be able to define javascript and css references in the configuration to define the correct path.

One last important point is: where the bower.json should be located? The main one will be in the sandbox.

**Comment by greg0ire** [comment]
Very very late to the party, but… I tried bowerphp, and I have some doubts : 

- it's beta software
- you have to edit your `/etc/hosts` file to access the homepage
- it does not work completely and exists with the following output : 
```
bower jquery-form#3.51        validate 3.51 against jquery-form#3.51

                            
  [ErrorException]          
  Undefined index: version  
                            

Exception trace:
 () at phar:///home/greg/bin/bowerphp.phar/src/Bowerphp/Bowerphp.php:110
 Bowerphp\Util\ErrorHandler::handle() at phar:///home/greg/bin/bowerphp.phar/src/Bowerphp/Bowerphp.php:110
 Bowerphp\Bowerphp->installPackage() at phar:///home/greg/bin/bowerphp.phar/src/Bowerphp/Bowerphp.php:153
 Bowerphp\Bowerphp->installDependencies() at phar:///home/greg/bin/bowerphp.phar/src/Bowerphp/Command/InstallCommand.php:74
 Bowerphp\Command\InstallCommand->execute() at phar:///home/greg/bin/bowerphp.phar/vendor/symfony/console/Command/Command.php:262
 Symfony\Component\Console\Command\Command->run() at phar:///home/greg/bin/bowerphp.phar/vendor/symfony/console/Application.php:826
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/greg/bin/bowerphp.phar/src/Bowerphp/Console/Application.php:180
 Bowerphp\Console\Application->symfonyDoRun() at phar:///home/greg/bin/bowerphp.phar/src/Bowerphp/Console/Application.php:64
 Bowerphp\Console\Application->doRun() at phar:///home/greg/bin/bowerphp.phar/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at phar:///home/greg/bin/bowerphp.phar/bin/bowerphp:43
 require() at /home/greg/bin/bowerphp.phar:14
```
- it's a port of another tool, which means it will always be lagging a bit behind in functionality

**Comment by jordisala1991** [comment]
Bower is not the best option now (npm/yarn is better) but it is already implemented. Closing. If I am missing something about this issue, feel free to reopen

**Comment by core23** [comment]
Not sure if this is about bower itself, but the way how we handle asset dependencies (e.g. jQuery, ...).

AFAIK there is no best practice for this problem. Including all assets under `Resources/public/vendor` is no good sultion.

**Comment by jordisala1991** [comment]
What should we do: Open a new issue or keep using this one?

**Comment by core23** [comment]
I'll open a new one on the dev-kit, 'cause this is a general problem accross all bundles.

**Comment by jordisala1991** [comment]
Perfect, thank you @core23

**Comment by core23** [comment]
Refs https://github.com/sonata-project/dev-kit/issues/387
