### ISSUE TITLE
Improve Select2 configuration  - incorrect width 

### ISSUE THREAD

**Issue by ghost** [sonata-project/SonataAdminBundle#2059]
Currently in admin bundle width calculation is not correct.

As a result i observe such narrow controls, in collapsed state content doesn't fit

![screenshot 2014-04-10 19 28 52](https://cloud.githubusercontent.com/assets/1198955/2670430/a6d5097a-c0cd-11e3-9ae8-eaa5903bf9c9.png)

**Comment by VBelozyorov** [comment]
[Here](https://sonata-project.org/bundles/admin/master/doc/reference/form_types.html#sonata-type-model-autocomplete) in the docs the `width` option is specified: 
> width 
>       defaults to “”. Controls the width style attribute of the Select2 container div.

But when I trying to use it:
```
…
->add('legalForm', 'sonata_type_model_autocomplete', [
                    'class' => 'MyBundle\Entity\Catalog\LegalForm',
                    'placeholder' => $this->translator->trans('undefined'),
                    'required' => false,
                    'property' =>  ['code', 'title'],
                    'width' => '100%'
                ])
…
```
It says
>The option "width" does not exist. Defined options are: "action", "allow_extra_fields", "attr", "auto_initialize", "block_name", "by_reference", "callback", "cascade_validation", "class", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_provider", "csrf_token_id", "csrf_token_manager", "data", "data_class", "description", "disabled", "dropdown_css_class", "empty_data", "error_bubbling", "error_mapping", "extra_fields_message", "horizontal_input_wrapper_class", "horizontal_label_class", "horizontal_label_offset_class", "inherit_data", "intention", "invalid_message", "invalid_message_parameters", "items_per_page", "label", "label_attr", "label_format", "label_render", "mapped", "max_length", "method", "minimum_input_length", "model_manager", "multiple", "pattern", "placeholder", "post_max_size_message", "property", "property_path", "read_only", "req_param_name_items_per_page", "req_param_name_page_number", "req_param_name_search", "req_params", "required", "route", "sonata_admin", "sonata_field_description", "sonata_help", "to_string_callback", "translation_domain", "trim", "url", "validation_groups", "virtual". 

What I'm doing wrong?

part of my `composer.lock`: 
```
{
            "name": "sonata-project/admin-bundle",
            "version": "2.3.7",
            "source": {
                "type": "git",
                "url": "https://github.com/sonata-project/SonataAdminBundle.git",
                "reference": "41efdd80e18abd793fe4d1d7d936b2d5f5d8d6d8"
            },
…
```
As far as I understand (2.3.7)[https://github.com/sonata-project/SonataAdminBundle/commits/2.3.7] was released at the end of October 2015 and should contain this feature (width option for `sonata_type_model_autocomplete`), isn't it?
