### ISSUE TITLE
SonataAdminBundle template marketplace

### ISSUE THREAD

**Issue by ziozec** [sonata-project/SonataAdminBundle#2066]
Where can I found different template for SonataAdminBundle?

What about creating a template site community?

Thanks,
Fabio

**Comment by thomas-koch-comsolit** [comment]
Related to this: Would it be possible, to split up Sonata-Admin into a backend-only bundle and allow for different frontent bundles? We prefer to use Zurb Foundation in our application and thus the Sonata Admin can not easily integrated in our site wide design.

**Comment by davidromani** [comment]
There is somebody still working on this issue?

**Comment by core23** [comment]
Feel free to be the first one 👍

**Comment by jordisala1991** [comment]
I dont think it makes a lot of sense to talk about a marketplace when we are so coupled with adminLTE. However, it would be nice to have an issue with a proposal to split admin frontend/backend. IMO it would be a huge pain to do it, but if someone has the time, it would be great at the end. so 👍 

Closing this one.
