### ISSUE TITLE
Issue with baseRouteName property when entities are outside of bundles

### ISSUE THREAD

**Issue by jameshalsall** [sonata-project/SonataAdminBundle#2068]
There's currently an issue when you store your entities outside of a bundle (for example, `Acme\Component\Entity` namespace). An exception is thrown...

> Cannot automatically determine base route name, please define a default `baseRouteName` value for the admin class `Acme\Bundle\AdminBundle\Admin\MyAdmin`

The reason this is failing is because of the regex used to automatically determine the base route name, in `\Sonata\AdminBundle\Admin\Admin::getBaseRouteName()` method (line 928). Currently this regex looks like...

`@([A-Za-z0-9]*)\\\(Bundle\\\)?([A-Za-z0-9]+)Bundle\\\(Entity|Document|Model|PHPCR|CouchDocument|Phpcr|Doctrine\\\Orm|Doctrine\\\Phpcr|Doctrine\\\MongoDB|Doctrine\\\CouchDB)\\\(.*)@`

This isn't usually a big deal when we're writing an admin class of our own, but it becomes a problem when we're using something like `SonataMediaBundle` where we have no control over the `$baseRouteName` property in the admin class.

**Comment by xenursXX** [comment]
to resole it go in the file composer.json and replace
"sonata-project/admin-bundle": "~2.3",
by
"sonata-project/admin-bundle": "dev-master@dev",

**Comment by edrush** [comment]
+1

Any plans on when v2.4 will be released (see #2496)?

@xenursXX Thank you, but does not work for me. And seems quiet a risk for our production system.

**Comment by jordisala1991** [comment]
This is fixed already. See #2594
