### ISSUE TITLE
[editable] how to disable popup for editable boolean field in list view

### ISSUE THREAD

**Issue by henter** [sonata-project/SonataAdminBundle#2080]
I just wanna disable popup for editable boolean field in list view,  it would be faster if I only click one time to toggle a boolean field.

PS: seems the old version support this,  so how to disable popup for current master version?

**Comment by Romashka** [comment]
@henter have you solve this problem?

**Comment by henter** [comment]
@Romashka not yet, have no time to dig it further.

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @henter

**Comment by fliespl** [comment]
I haven't found the resolution to this in docs. Probably still valid request.

**Comment by bobemoe** [comment]
Looking to do this myself too. I see the inline field editing uses [x-editable](https://vitalets.github.io/x-editable/)  but there isn't built in support for boolean. 

Using a select box makes sense as a workaround but is quite click consuming when the only possible edit action is a toggle!

Would someone like to re-open this? @core23, @henter

**Comment by core23** [comment]
Please open a new bug using the new issue template @bobemoe
