### ISSUE TITLE
form type horizontal issue

### ISSUE THREAD

**Issue by yuriricci** [sonata-project/SonataAdminBundle#2095]
I just updated sonata admin to master, but my forms styles changed from bootstrap horizontal to default. This causes problems in particular for the rendering of collection type (see picture).
I notice a recent update which says: "remove bootstrap horizontal support". It really means that is no more supported natively? I'm quite beginner with twig, but looking at the code it doesn't seem so... Suggestions? 

![collection](https://cloud.githubusercontent.com/assets/7250389/2808814/e9c59e9e-cd47-11e3-88c9-c197bf3a9ded.png)

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @yuriricci
