### ISSUE TITLE
Min-height increment loop with type collection...?

### ISSUE THREAD

**Issue by yuriricci** [sonata-project/SonataAdminBundle#2096]
I noticed a very strange behaviour using the collection type with sonata admin... when pressing the add row button (+)  a loop starts which increments the min-height property of the wrapper, resulting in a page height constant increment. It is a bug or affects only me for unknown reasons?

![wrapperloop](https://cloud.githubusercontent.com/assets/7250389/2809491/bbdfe708-cd71-11e3-862a-551d3eebd82f.png)

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @yuriricci
