### ISSUE TITLE
Export not complete issue

### ISSUE THREAD

**Issue by royraider** [sonata-project/SonataAdminBundle#2101]
Hello everyone !

I have an issue with the export system. 
In one of my entity i have "5618 results" (SonataAdmin said it itself). But when I do an export I dont get 5618 results, even worst, i got a variable result.
- first time in CSV: 5455 lines
- second try in XLS: 5330 lines
- third time in CSV: 5423 lines

I have no clue why, but I dont get the same amount of results at each try, and it dont depend on format or size file.
maybe it's due to a time limit or something like that ?

**Comment by roukmoute** [comment]
@rande : would it not be better to have the ini setting change directly in the exportAction ? If we are exporting data, we can safely assume that the max_execution_time should be increased in that case.
