### ISSUE TITLE
field with the name "children" in OneToMany "sonata_type_collection"

### ISSUE THREAD

**Issue by arffak** [sonata-project/SonataAdminBundle#2104]
I have a class A that has a OneToMany relationship with Class B 
Class B has a field named "children" when you use "sonata_type_collection" with "edit" "inline" when you click on "add new" nothing appears! but if I change the name "children" with another name it works!

**Comment by webdevilopers** [comment]
Duplicate of https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/34.

**Comment by arffak** [comment]
@webdevilopers, No its not a duplicated issue, its different

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
