### ISSUE TITLE
"The option "field_options" does not exist" in Datagrid Mapper

### ISSUE THREAD

**Issue by dunkelberg** [sonata-project/SonataAdminBundle#2148]
It seems that configured option 'field_option' in configureDatagridFilters is no more recognized in [entityname]Admin class. Thi is my code

			$datagridMapper
				->add('id')
				->add('itemType', 'doctrine_orm_choice', array('label'			=> 'Tipo item',
																'field_options' => array(
																'required' 		=> FALSE,
																'choices'		=> array("image"			=> "Immagine",
																						"video-youtube"	=> "Video Youtube",
																						"text" 			=> "Testo")
																					),
																'field_type' 	=> 'choice')
																)

class DatagridMapper extends BaseMapper {

    public function add($name, $type = null, array $filterOptions = array(), $fieldType = null, $fieldOptions = null)
    {
        if (is_array($fieldOptions)) {
            $filterOptions['field_options'] = $fieldOptions;
        }

**Comment by pulzarraider** [comment]
SonataDoctrineORMAdminBundle 2.3.1 was just released. It contains bugfixes for this issue.

**Comment by Renrhaf** [comment]
Thanks !

**Comment by marvoh** [comment]
How do i get to use datepicker after the fix? I cannot seem to get guidance anywhere

**Comment by elb** [comment]
@marvoh use the `sonata_type_datetime_range_picker`

_added for reference_

**Comment by webdevilopers** [comment]
BTW:
Does anybody know how to set default values for this filter when adding via $datagridMapper or inside $datagridValues property?

* https://github.com/sonata-project/SonataAdminBundle/pull/842

**Comment by dunkelberg** [comment]
La Sua mail &#232; stata correttamente ricevuta. Ricever&#224; una risposta nel pi&#249; breve tempo possibile.

Cordiali saluti.

**Comment by webdevilopers** [comment]
Please keep it english @dunkelberg , thanks!

**Comment by Soullivaneuh** [comment]
According to @webdevilopers https://github.com/sonata-project/SonataAdminBundle/issues/2148#issuecomment-66766123, I close this issue as it seems to work on 3.x.

2.x is not maintained anymore.

Feel free to open a new issue if you get this error again on 3.x
