### ISSUE TITLE
Sonata + Menu + Dashboard

### ISSUE THREAD

**Issue by kamalkech** [sonata-project/SonataAdminBundle#2156]
How i hide menu for some roles ?

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @kamalkech

**Comment by kamalkech** [comment]
@core23 are you date of my last comment ? it was on 22 May 2014 !!

**Comment by core23** [comment]
I'm housekeeping some issues. Feel free to close or is this question still active?
