### ISSUE TITLE
Add html5shiv.js and respond.min.js to get IE7 and IE8 compatibility

### ISSUE THREAD

**Issue by omkom-web** [sonata-project/SonataAdminBundle#2164]
Hi I think this could help 
Please add 

    
in 
SonataAdminBundle / Resources / views / standard_layout.html.twig header

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @omkom-web
