### ISSUE TITLE
Admin  data export (csv, json xml and xls) throws DummyException....

### ISSUE THREAD

**Issue by johnkrovitch** [sonata-project/SonataAdminBundle#2191]
Hi, 

when I click on csv export (does not work with other exports types either), the browser says that file is not found. When I check the logs, I just have a DummyException.....

request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\DummyException: "" at path\to\symfony/symfony/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php line 155 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\DummyException:  at path\to\symfony/symfony/vendor/symfony/symfony/src/Symfony/Component/Debug/ErrorHandler.php:155)"} []

Someone has ever had this problem ? How can I debug this ?

**Comment by pulzarraider** [comment]
I am closing the issue for now. @johnkrovitch if you will have more informations how to reproduce the error later, I can reopen it.
