### ISSUE TITLE
Fail to work if an admin class is related to an entity with a property named children

### ISSUE THREAD

**Issue by mikeSimonson** [sonata-project/SonataAdminBundle#2203]
I get an error when I try to list all the entites of a class that has a children property (boolean).

The relevant part of the code is as bellow.

``` php
    /**
     * @param DatagridMapper $datagridMapper
     */
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('id')
            ->add('children')
            ->add('youth')
            ->add('adult')
        ;
    }
```

I get this error :

```
Key "id" in object with ArrayAccess of class "Symfony\Component\Form\FormView" does not exist in SonataAdminBundle:CRUD:base_list.html.twig at line 203 .
```

I have no error if I map all the fields of the entity but that children one.
I don't have any issue neither if I refactor it to childrens.

I am betting there is a naming collision somewhere.

**Comment by OskarStark** [comment]
Same Problem, i can keep this in my Entity:

```php
    /**
     * @var int
     *
     * @ORM\Column(name="children", type="integer", nullable=true)
     *
     * @Assert\Type(type="integer")
     * @Assert\Range(min=0, max=200)
     */
    private $children;
```

but i have to remove all
```php
->add('children)
```
from my admin... :confused:

**Comment by OskarStark** [comment]
i renamed everything to ``$numberOfChildren`` and now it works

**Comment by OskarStark** [comment]
@rande can you explain WHAT is the problem here?

**Comment by rapemer** [comment]
I have the same problem when I use $children inside Entity. Try to only rename $fuckingChildren and it works fine....

**Comment by IwfY** [comment]
Is there a place were or way how Sonata Admin could throw a meaningful warning that there are problems with properties called 'children'?

The Twig exception one gets is not very helpful and without this bug report it would probably have cost me hours to find the error.

**Comment by jordisala1991** [comment]
This issue is relly old. I remember using the keyword children as a property name some times. 

Can anyone check with latest versions of sonata if this is still an issue?

**Comment by kunicmarko20** [comment]
still an issue.

**Comment by jordisala1991** [comment]
Do you have any idea where this could be? I mean the wrong code

**Comment by kunicmarko20** [comment]
The issue is with Symfony Forms, in our code, we have `form.children[filter.formName]` and then Symfony gives us the children FormView instead of the property in children array.

```
FormView {#1510 ▼
  +vars: array:30 [▶]
  +parent: null
  +children: array:7 [▼
    "name" => FormView {#1584 ▶}
    "value" => FormView {#1226 ▶}
    "children" => FormView {#1578 ▶}
    "_sort_by" => FormView {#1513 ▶}
    "_sort_order" => FormView {#1526 ▶}
    "_page" => FormView {#1588 ▶}
    "_per_page" => FormView {#1585 ▶}
  ]
  -rendered: false
  -methodRendered: false
}

```

I manage to fix it by chaning `form.children[filter.formName]` to ``form[filter.formName]``, will provide a PR.
