### ISSUE TITLE
admin_pool in template make it hard to use fos userbundle

### ISSUE THREAD

**Issue by onmomo** [sonata-project/SonataAdminBundle#2204]
Since the admin_pool is used for stylesheets and javascripts, its necessary to overwrite a lot of FOS User bundle code for adding the variable to the rendering templates.
Is there a workaround for this?

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @onmomo

**Comment by onmomo** [comment]
used the workaround described above.
