### ISSUE TITLE
Manage object with sonata_type_immutable_array?

### ISSUE THREAD

**Issue by dirkluijk** [sonata-project/SonataAdminBundle#2207]
I am working on a products widget that must show a list of products. The admin user must be able to choose from what ``Category`` the products will be displayed. I use ``SonataAdminBundle`` and ``SonataBlockBundle`` with its "blocks" to get the job done. 

This is a part of my ``ProductsBlockService`` class. As you can see, the user will get a ``choice`` form field with all the categories to choose from.
```
public function buildEditForm(FormMapper $form, BlockInterface $block)
    {
        $form
            ->add('settings', 'sonata_type_immutable_array', array(
                    'label' => false,
                    'keys' => array(
                        array('category', 'entity', array(
                            'property' => 'name',
                            'class' => 'MyCatalogBundle:Category',
                            'required' => false,
                        )),
                    )
                ));

    }
```
So far, so good. I use a ``Widget`` entity as implementation of ``BlockInterface``:
```
class Widget implements BlockInterface
{
    // ...
    
    /**
     * @var array
     * @ORM\Column(type="object")
     */
    protected $options;
    
    /**
     * Returns the block settings
     *
     * @return array $settings An array of key/value
     */
    public function getSettings()
    {
        return $this->options;
    }
```

As you can see, the ``Category`` object (which is stored in the ``options`` field) is being serialized and stored in a single database field. Yes, a copy of the original one. And that is very wrong. What is the ``Category`` changes?

The only solution I see is to only store the "categoryId" in the block settings array. But how should my ``buildEditForm()`` looks like? Is it possible to use the ``entity`` form type and only store the ``id`` in the object?

What is the best way to deal with this kind of situations?

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @dirkluijk
