### ISSUE TITLE
change show template for upload file

### ISSUE THREAD

**Issue by matlow** [sonata-project/SonataAdminBundle#2211]
Hello,
On show action, i would like to add a link to download a file uploaded 
In doc\cookbook\recipe_file_uploads.rst you ask to use sonataMediaBundle but not compatible with sf 2.4.
Is the best way is to create an admin extension and follow the logic in Sf docs http://symfony.com/fr/doc/current/cookbook/form/create_form_type_extension.html

**Comment by pulzarraider** [comment]
Show action is not using Symfony forms. To create your custom show field type, just create your own template as it is done [in the list action](http://sonata-project.org/bundles/doctrine-orm-admin/master/doc/reference/list_field_definition.html#custom-template).
