### ISSUE TITLE
How to get image preview in symfony collection images

### ISSUE THREAD

**Issue by ajeetvarma** [sonata-project/SonataAdminBundle#2213]
In my Admin class :

```
  class ApartmentsAdmin extends Admin
  {
   protected function configureFormFields(FormMapper $formMapper)
    {
           ->add('images', 'collection', array(
                    'type' => new ImageType(),
                    'allow_add' => true,
                    'allow_delete' => true,
                    'by_reference' => true,
                    'mapped' => true,
                    'label' => false,
                    'required' => false,
                    'label' => 'Apartment Images'
                  ))
           }
      }
```

It works fine ; but my issue is that , on edit page i want to let see preview of each images included in collection . In documentation of "SonataAdminBundle"  image preview is given for one individual image , but how is it possible to make preview for collection images ..

Please suggest me..

Thanks a lot ..

**Comment by blaues0cke** [comment]
For the people that came here using Google - I just posted a solution for Symfony3: http://stackoverflow.com/questions/11366278/how-to-display-the-current-picture-above-the-upload-field-in-sonataadminbundle/42158303#42158303

**Comment by greg0ire** [comment]
@blaues0cke : would you be willing to contribute it?
