### ISSUE TITLE
getExportFields in Sonata Admin

### ISSUE THREAD

**Issue by Siddharth22** [sonata-project/SonataAdminBundle#2221]
Hi,

I want to know that How I can customize getExportFields function in Sonata Admin extend Class.

1. My Problem is my class fields createdAt type is datetime but I want when admin download this class data then in CSV or XLS file createdAt format DATE, not a datetime.

2. I want show data in CSV or XLS file through join other tables.

I searched many times on google but nothing found.

This one I try for join but I am not success-

        public function getExportFields()
        {
		$em = $this->modelManager->getEntityManager('ABC\FroBundle\Entity\Model');
		$conn = $em->getConnection();
		$query = "SELECT mp.id, mp.userModel, u.email, m.model_name
				FROM model_p mp
				LEFT JOIN user u ON mp.user_id = u.id
				LEFT JOIN m_model m ON mp.model_id = m.id limit 1";
		$statement = $conn->prepare($query);
		$statement->execute();
		$results = $statement->fetchAll();
		foreach($results as $res){
			$reets = $res;
		}
		$fieldsArray = $reets;
	}

Any one know this type issue please help.

Thanks!

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version.

If this is still present, feel free to reopen this issue
