### ISSUE TITLE
Form embed not show correctly

### ISSUE THREAD

**Issue by Chrysweel** [sonata-project/SonataAdminBundle#2224]
Hello.

I use sonataAdminBundle, with forms embed.

I have a Entity "Convocatoria". In the form can choose oppositions.. here all correct.
![correct_example](https://cloud.githubusercontent.com/assets/1416870/3508350/05c17688-068a-11e4-9c59-9babc008da6b.png)

The problem comes when...In a third form, which I embed the form of "Convocatoria" the select to choose oppositions it see wrong

![incorrect_example](https://cloud.githubusercontent.com/assets/1416870/3508418/fe816ac6-068a-11e4-9a85-34d0faa50f87.png)

I use mozilla, but in browser Chrome this problem also happens.
This is my code:

In the Convocatoria Admin I have:

```
	// Fields to be shown on create/edit forms
	protected function configureFormFields(FormMapper $formMapper)
	{
		$reasonFieldOptions = array(); // see available options below
		
		$formMapper
			->add('edate', 'date', array('label' => 'Fecha de la convocatoria'))
			->add('opposition')
		;
	}
```
In the other admin, where I embed the form above I have:

```
// Fields to be shown on create/edit forms
	protected function configureFormFields(FormMapper $formMapper)
	{
		$formMapper
			->add('title')
			->add('edition', 'sonata_type_model_list', array('required'=> false, 'label' => 'Convocatoria'))
		;
	}
```
I want try show the form without popup to check if the problem persist..

I have not other idea ..

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @Chrysweel
