### ISSUE TITLE
Invalid state error, when displaying mapped entity

### ISSUE THREAD

**Issue by Elakioui** [sonata-project/SonataAdminBundle#2231]
Hello,

  I have a problem when displaying a mapped entity , therefore i defined __toString function.
The message displayed : An exception has been thrown during the rendering of a template ("invalid state") in SonataAdminBundle:Button:show_button.html.twig at line 12.

**Comment by cbastienbaron** [comment]
FYI reproductible when we had the same field 2 times on `FormMapper` or `ShowMapper` : 

            ->add('city', null, array('label' => 'city'))
            ->add('city', null, array('label' => 'city'))

boom Invalid state error, when displaying mapped entity

**Comment by OskarStark** [comment]
you're right, this fixxed it for me to:

error:
```
An exception has been thrown during the rendering of a template ("invalid state") in SonataAdminBundle:Button:show_button.html.twig at line 12.
```

before:
```php
    /**
     * @param ShowMapper $showMapper
     */
    protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->add('id')
            ->add('name')
            ->add('price')
            ->add('runtime')
            ->add('standalone')
            ->add('standalone')
        ;
    }
```

after:
```php
    /**
     * @param ShowMapper $showMapper
     */
    protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->add('id')
            ->add('name')
            ->add('price')
            ->add('runtime')
            ->add('standalone')
        ;
    }
```

Is it possible to get a better exception message?

Oskar

**Comment by OskarStark** [comment]
ping @Soullivaneuh @rande 

better exception msg possible?

**Comment by ethernal** [comment]
It also happens when in configureShowFields() method you add an empty element.

```php
    protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
                ->add()
        ;
    }
```

It's easy to spot, but the message is very unclear.

**Comment by OskarStark** [comment]
We should add better exceptions messages here

**Comment by greg0ire** [comment]
I think the error message comes from [this line](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Show/ShowMapper.php#L74)

**Comment by jordisala1991** [comment]
This closes this issue: https://github.com/sonata-project/SonataAdminBundle/pull/2988

Closing. If you still have this problem, please ping me to reopen with more information.
