### ISSUE TITLE
Bug metadata line 390

### ISSUE THREAD

**Issue by IvanBes** [sonata-project/SonataAdminBundle#2249]
When I click on 'enable' or 'lock', I get this html/log code instead of the user being enabled, disabled, locked, unlocked etc.
And I have the same problem for all list.

![fazd4](https://cloud.githubusercontent.com/assets/8203335/3649339/858bceae-1111-11e4-9e51-524dd3496aff.png)

Notice: Undefined index: *a variable* in 
/Sites/IB/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/ClassMetadata.php line 390

example of url request : http://localhost/IB/web/admin/core/set-object-field-value?context=list&field=close&objectId=8&code=sondagebundle.admin.sondage

I use symfony 2.5.2, sonata in dev-master (I know that the picture comes an older version and I still have the problem) and doctrine V2.4.4.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @IvanBes

**Comment by greg0ire** [comment]
Hi, sorry but as you may already know, Sonata 2 is no longer supported. Please ask us to reopen if you still experience this with Sonata 3.
