### ISSUE TITLE
Editable boolean listfield doesn't work - Notice: Undefined index enabled in classMetaData.php

### ISSUE THREAD

**Issue by ArFeRR** [sonata-project/SonataAdminBundle#2260]
Hello. I have a trouble with editable boolean field "enabled" in Sonata. When I try to change it the sent ajax request returns the 500 error:

Notice: Undefined index: enabled in /home/arferr/www/parfums/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/ClassMetadata.php line 390 (500 Internal Server Error)

And the popup starts look like this:
http://screencloud.net/v/sH0H

It's not only about the "enabled" field of sonataUserBundle... It's about all the editable boolean fields, defined in configureListFields method of the Admin Class.

            ->add('enabled', 'boolean', array('editable' => true))

I tried also:
                ->add('enabled', null, array('editable' => true))

but it's the same thing.
Please, help.

**Comment by KailZhang** [comment]
seems not fixed yet?

**Comment by Tocacar** [comment]
I'm having the same problem

**Comment by remoteclient** [comment]
For me the problem was gone after an update.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
