### ISSUE TITLE
delete Button on Many-To-Many over a Has-Bridge does not make sense

### ISSUE THREAD

**Issue by adyballa** [sonata-project/SonataAdminBundle#2272]
I have an Many-To-Many-relation:
Entity A <- Entity AHasB -> EntitiyB

I've declared in AdminA a sonata_type_collection field for AHasB-Entities.
There I've declared a sonata_type_model_list.

It is clear that Entity AHasB does not have any null field. So the delete-btn in the AHasBAdmin-sonata_type_model_list-field *must* delete the whole row. Either in Front-End or/and Backend.
In Frontend would be nice to avoid configuration-leaks.

I would advice a JS-Event, a new (perhaps i dont recoginzed it) configuration or a new field-type,
since it's the combination. Prehaps the orphan-removal can fix it 

Until then and if others had the same issues, I set btn_delete => false in the AHasBAdmin->configureFormFields.

I apologize, if I made a mistake and would be thankful for a correction. But it's not nice to have orphanic databse-tables

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @adyballa

**Comment by adyballa** [comment]
sry - its too long ago. I cannot reproduce
