### ISSUE TITLE
sonata.admin.event.persistence.pre_remove not triggered

### ISSUE THREAD

**Issue by bilougit** [sonata-project/SonataAdminBundle#2297]
Hi there,

I have an event listener which's supposed to be executed when post_persist and pre_remove are triggered. I have no problem with post_persist, but my listener doesn't do anything when I remove something. I even tried the pre_update event and it worked well. So I thought it'd to do with pre_remove.
<pre>

    tags:
      - { name: kernel.event_listener, event: sonata.admin.event.persistence.post_persist, method: onUserRegistration }
      - { name: kernel.event_listener, event: sonata.admin.event.persistence.pre_remove, method: onUserRemoval }
</pre>
ANy ideas?

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @bilougit
