### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by odeg36** [sonata-project/SonataAdminBundle#2298]
Hello,
well i've been working in a project, but i find an issue.

I have a few roles for the admin site, they have different entities under their responsibility, so every entity have a group secured by a role. but the relation between entities let me show some attributes of  one entity to other. for that reason, when i show the list of an entity I show the attribute of the other entity (which is secured by other role) and that list show that attribute with a link to edit that attribute, even knowing that this attribute is from an entity that only could managed by other role. 

Thank you for your attention (Sorry for my English)

**Comment by webdevilopers** [comment]
Can you provide the requested example and compare it with my issue, @odeg36 ?

**Comment by core23** [comment]
If this is an active issue, please reopen @odeg36
