### ISSUE TITLE
NewDesign. How to add items to Dashboard aside Admin Menu.

### ISSUE THREAD

**Issue by gam6itko** [sonata-project/SonataAdminBundle#2321]
I can't find (understand) how to add items and cathegories to Left Side Admin Menu.
There is no detailed tutorial how to do this.
I can add items to `sonata.admin.block.admin_list` but to aside Admin Menu

![sonataadmin](https://cloud.githubusercontent.com/assets/3841197/3973730/0c26b38a-27eb-11e4-8c62-3accf34b5b78.png)

Please Guide me

**Comment by AntonioCS** [comment]
@antoinemineau commented on [20 Aug 2014 11:00 BST](https://github.com/sonata-project/SonataAdminBundle/issues/2321#issuecomment-52755937 "2014-08-20T10:00:47Z - Replied by Github Comment Enhancer"):
> That's the problem so, you need an authenticated user to see the sidebar nav.
> 
> [https://github.com/antoinemineau/SonataAdminBundle/blob/master/Resources/views/standard_layout.html.twig#L181](https://github.com/antoinemineau/SonataAdminBundle/blob/master/Resources/views/standard_layout.html.twig#L181)
> 
> You could extend the SonataAdminBundle, rewrites the standard_layout.html.twig to remove this security part but an admin without security is a bad idea.
> 
> You can see sonata.admin.block.admin_list because you actually have no roles management.
> 
> [https://github.com/antoinemineau/SonataAdminBundle/blob/master/Resources/views/Block/block_admin_list.html.twig#L16](https://github.com/antoinemineau/SonataAdminBundle/blob/master/Resources/views/Block/block_admin_list.html.twig#L16)
> 
> [http://sonata-project.org/bundles/admin/master/doc/reference/dashboard.html](http://sonata-project.org/bundles/admin/master/doc/reference/dashboard.html)

I was logged in as ROLE_ADMIN and still was unable to see anything. I later discovered the ROLE_SONATA_ADMIN but this is completely ridiculous, I can see the dashboard, add/edit/list stuff but I cant see the menus. WOW

**Comment by kwn** [comment]
@AntonioCS 

I agree that it's ridiculous. What you can do is to consider include ```ROLE_SONATA_ADMIN``` in your ```role_hirarchy``` in ```app/config/security.yml``` file:

```yaml
security:
    [...]
    role_hierarchy:
        ROLE_ADMIN:       [ ROLE_USER, ROLE_SONATA_ADMIN ]
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
```

**Comment by cithukyaw** [comment]
@kwn is correct. Adding `ROLE_SONATA_ADMIN` in `app/config/security.yml` solved the problem.

**Comment by Titogelo** [comment]
Hi, I already have ROLE_SONATA_ADMIN under ROLE_ADMIN but I still don't see the side bar menu..

**Comment by kwn** [comment]
@Titogelo 
Could you show us your role hierarchy from security.yml? Are you sure, that the user that you are using has a role ROLE_ADMIN added?

**Comment by Titogelo** [comment]
http://pastebin.com/CKJgvSZB

![profiler](https://cloud.githubusercontent.com/assets/1598632/8059003/c442e3a8-0ebd-11e5-9c09-9ba5a96f586e.jpg)

**Comment by kwn** [comment]
Change ```ROLE_SONATA_ADMIN``` key (line 57) to something different (e.g. ```ROLE_SONATA_ADMINISTRATOR```) and then change your ```ROLE_ADMIN``` herarchy to:

```
ROLE_ADMIN:
    - ROLE_USER
    - ROLE_SONATA_ADMIN
    - ROLE_SONATA_ADMINISTRATOR
```

**Comment by Titogelo** [comment]
It works. But I also get rid of my customized layout... I had tried it before but I think your suggestion in hierarchy made the difference... so many thanks.

**Comment by kwn** [comment]
No problem.

The problem was, that you were overriding the default ```ROLE_SONATA_ADMIN``` role that comes from Sonata Bundle by a role with the same name in your security.yml
