### ISSUE TITLE
"editable" objects in list view

### ISSUE THREAD

**Issue by alex844** [sonata-project/SonataAdminBundle#2324]
I tried to use some "editable" fields, for example ">add('enabled', null, array('editable' => true))".
And it doesn't work at all, i got a 500 error and here is the post values from the profiler: 

Request POST Parameters
Key	Value
name	
pk	407
value	0

And from the dev.log
event.INFO: An exception was thrown while getting the uncalled listeners (You cannot create a service ("request") of an inactive scope ("request").) {"exception":"[object] (Symfony\\Component\\DependencyInjection\\Exception\\InactiveScopeException: You cannot create a service (\"request\") of an inactive scope (\"request\").

There's nothing in name, which I think it's not normal.
Do you have any information about that issue?

Thanks

**Comment by pulzarraider** [comment]
Thank you for reporting the issue @alex844, but I cannot reproduce the problem in current `dev-master` (upcoming 2.4). Editable option for boolean types for as expected.
