### ISSUE TITLE
Replace Pager with Knp Paginator for COUNT wrapping queries using HAVING clause

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2334]
My Entities:
- Offer: https://gist.github.com/webdevilopers/9f182b113c9130b2dc68#file-offer-php
- OfferStatusHistory: https://gist.github.com/webdevilopers/9f182b113c9130b2dc68#file-offerstatushistory-php
- OfferStatus: https://gist.github.com/webdevilopers/9f182b113c9130b2dc68#file-offerstatus-php

I need to select the latest status created `current_status` from `OfferStatusHistory`.

In order to use the `current_state` in my list view I can easily use a workaround with a custom template:

``` php
# OfferAdmin.php
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('currentStatus', null, array(
                'mapped' => false,
                'template' => 'SpsOfferBundle:OfferAdmin:list_current_status.html.twig'
            ));
    }
```

Calling the Entity method:

``` php
# Entity\Offer.php
    private $currentStatus;

    public function getCurrentStatus()
    {
        // Get latest status using ORM\OrderBy createdAt DESC
        $currentStatusHistory = $this->statusHistories[0];

        return $currentStatusHistory->getStatus()->getName();
    }
```

And use it inside my template:

``` twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}
    <div>
        {{ object.getCurrentStatus }}
    </div>
{% endblock %}
```

But now I need to filter the status which will not work that easy for `not mapped` fields.
I will have to extend the `queryBuilder`.

Talking raw SQL this can be achieved by the following two query variations:
- Using HAVING: https://gist.github.com/webdevilopers/9f182b113c9130b2dc68#file-current_status_having-sql
- USING subquery on WHERE: https://gist.github.com/webdevilopers/9f182b113c9130b2dc68#file-current_status_where_subquery-sql

I first tried to add the following SELECT to the `queryBuilder` addSelect() method:

``` php
    public function createQuery($context = 'list')
    {
        $query = parent::createQuery($context);

        $builder = $this->getModelManager()->getEntityManager('Sps\Bundle\BaseBundle\Entity\OfferStatusHistory')->createQueryBuilder();
        $builder->select($query->expr()->max('osh.createdAt'))
                ->from('Sps\Bundle\BaseBundle\Entity\OfferStatusHistory', 'osh')
                ->where('osh.offer = ' . $query->getRootAlias() . '.id');
        $currentStatusDql = $builder->getDql();

        $query->addSelect(
                'PARTIAL ' . $query->getRootAlias() . '.{id, number, date, name}',
                'PARTIAL sh.{id, createdAt}',
                'PARTIAL pqr.{id}',
                'c',
                'a',
                '(' . $currentStatusDql . ') AS current_state'
            )
            ->join($query->getRootAlias() . '.statusHistories', 'sh')
            ->leftJoin($query->getRootAlias() . '.priceQuoteRequest', 'pqr')
            ->leftJoin($query->getRootAlias() . '.customer', 'c')
            ->leftJoin('c.address', 'a')
         ;
    }
```

Which creates the following DQL:

``` sql
SELECT o,
PARTIAL o.{id, number, date, name},
PARTIAL sh.{id, createdAt},
PARTIAL pqr.{id},
c,
a,
(SELECT MAX(osh.createdAt) FROM Sps\Bundle\BaseBundle\Entity\OfferStatusHistory osh WHERE osh.offer = o.id) AS current_state,
PARTIAL p.{id},
PARTIAL pu.{id, username},
PARTIAL pc.{id, firstName, lastName}
FROM Sps\Bundle\BaseBundle\Entity\Offer o
INNER JOIN o.statusHistories sh
LEFT JOIN o.priceQuoteRequest pqr
LEFT JOIN o.customer c
LEFT JOIN c.address a
INNER JOIN o.partner p
INNER JOIN p.user pu
LEFT JOIN p.customer pc
WHERE o.deletedAt IS NULL
AND o.partner = 1
```

Error:
**An exception has been thrown during the rendering of a template ("Warning: get_class() expects parameter 1 to be object, array given ...) in SonataAdminBundle:CRUD:base_list_field.html.twig at line 12.**

As far as I understand the problem occurs because Doctrine will return an Array when using scalar values.
That's why changed my attempt and added this SELECT to the `configureDatagridFilters` instead:
https://gist.github.com/webdevilopers/9f182b113c9130b2dc68#file-offeradmin_configuredatagridfilters_addselect-php

So far so good! The generated DQL:

``` sql
SELECT o,
PARTIAL o.{id, number, date, name},
PARTIAL sh.{id, createdAt},
PARTIAL pqr.{id},
c,
a,
PARTIAL p.{id},
PARTIAL pu.{id, username},
PARTIAL pc.{id, firstName, lastName},
(SELECT MAX(osh.createdAt) FROM Sps\Bundle\BaseBundle\Entity\OfferStatusHistory osh WHERE osh.offer = o.id) AS HIDDEN current_state
FROM Sps\Bundle\BaseBundle\Entity\Offer o
INNER JOIN o.statusHistories sh
LEFT JOIN o.priceQuoteRequest pqr
LEFT JOIN o.customer c
LEFT JOIN c.address a
INNER JOIN o.partner p
INNER JOIN p.user pu
LEFT JOIN p.customer pc
WHERE o.deletedAt IS NULL
AND o.partner = 1

```

The problem occurs when adding the HAVING condition:

``` php
->having('sh.createdAt = current_state')
```

Error:
**'current_state' is not defined.**

This actually makes sense because the bundle creates two extra queries for COUNTing.
By this it removes the SELECT subquery required for HAVING part:

``` sql
SELECT count(DISTINCT o.id) as cnt FROM Sps\Bundle\BaseBundle\Entity\Offer o
INNER JOIN o.statusHistories sh
LEFT JOIN o.priceQuoteRequest pqr
LEFT JOIN o.customer c
LEFT JOIN c.address a
INNER JOIN o.partner p
INNER JOIN p.user pu
LEFT JOIN p.customer pc
WHERE o.deletedAt IS NULL
AND o.partner = 1
HAVING sh.createdAt = current_state
```

Since the bundle keeps at least the WHERE conditions I added the subquery there instead:

``` php
$queryBuilder->andWhere('sh.createdAt = (' . $currentStatusDql . ')');
```

Error:
**Maximum execution time of 30 seconds exceeded**

This actually makes sense again since this is a `MySQL` issue. A query that uses COUNT on a query with a conditional subquery simply takes endlessly:

``` sql
SELECT COUNT(DISTINCT a.angebot_id)
FROM
angebot a
JOIN angebot_status_historie ash USING (angebot_id)
WHERE ash.angebot_status_datum = (
    SELECT MAX(ash2.angebot_status_datum)
    FROM angebot_status_historie ash2
    WHERE ash2.angebot_id = a.angebot_id
)
```

Possibly related issue:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/297

At the bottom line there is no way to solve my use case using these solutions.

Does anybody else know a solution?

A possible workaround for the future will be to add a column to the `Offer` Entity that will store the `current_status` in addition to the `OfferStatusHistory`.
Going even one step further the database table will be moved to a `MongoDB` collection since the table has grown very big.
And the adding a `current_state` field strategy is a typcial practice for this.

Anyway, perhaps there is a solution I havn't figured out yet.
Thanks in advance!

Other possibly related issues:
- https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/353
- https://github.com/sonata-project/SonataAdminBundle/issues/2269
- https://github.com/sonata-project/SonataAdminBundle/issues/1900

**Comment by webdevilopers** [comment]
I took my `HAVING` query for my filter from SonataAdmin:
```php
    public function getCurrentStateFilter($queryBuilder, $alias, $field, $value)
    {
        if (!$value['value']) {
            return;
        }

        $selectLastUpdate = 'SELECT MAX(cs2.date) FROM Acme\ContractBundle\Entity\ContractState cs2 WHERE cs2.contract = ' . $alias . '.id';

        $having = 'state_last_created = cs.date'
            . ' AND (' . $queryBuilder->expr()->in('cs.state', array($value['value'])) . ')';

        $queryBuilder
            ->addSelect('PARTIAL cs.{id, state, date}')
            ->join($alias . '.states', 'cs')
            ->addSelect('(' . $selectLastUpdate . ') AS HIDDEN state_last_created')
            ->having($having)
            ;

        return true;
    }
```

And arranged it for the `Knp Paginator`:
```php
        $em    = $this->get('doctrine.orm.entity_manager');
        $qb = $em->createQueryBuilder();

        $selectLastUpdate = 'SELECT MAX(cs2.createdAt) FROM Acme\AppBundle\Entity\ContractState cs2 WHERE cs2.contract = c.id';

        $having = "state_last_created = cst.createdAt";

        $qb->select(array('PARTIAL c.{id, number}'))
            ->from('AcmeAppBundle:Contract', 'c')
            ->addSelect('PARTIAL cst.{id, state, date, createdAt}')
            ->join('c.states', 'cst')
            ->addSelect('(' . $selectLastUpdate . ') AS HIDDEN state_last_created')
        ;

        $query = $qb->getQuery();

        $paginator  = $this->get('knp_paginator');

        $pagination = $paginator->paginate(
            $query,
            $request->query->get('page', 1)/*page number*/,
            10/*limit per page*/,
            array('wrap-queries'=>true) // Cannot count query that uses a HAVING clause. Use the output walkers for pagination
        );
```

Using the `wrap-queries` parameter would make it work by creating this query:
```sql


SELECT 
  COUNT(*) AS dctrn_count 
FROM 
  (
    SELECT 
      DISTINCT id1 
    FROM 
      (
        SELECT 
          (
            SELECT 
              MAX(c0_.created_at) AS dctrn__1 
            FROM 
              contract_states c0_ 
            WHERE 
              c0_.contract_id = c1_.id
          ) AS sclr0, 
          c1_.id AS id1, 
          c1_.number AS number2, 
          c2_.id AS id3, 
          c2_.state AS state4, 
          c2_.date AS date5, 
          c2_.created_at AS created_at6 
        FROM 
          contracts c1_ 
          INNER JOIN contract_states c2_ ON c1_.id = c2_.contract_id 
        HAVING 
          (sclr0 = c2_.created_at) 
        ORDER BY 
          c2_.date DESC
      ) dctrn_result
  ) dctrn_table
```

This solution was provided by @emanuelecasadio in issue https://github.com/KnpLabs/KnpPaginatorBundle/issues/106 and should also work on https://github.com/KnpLabs/knp-components/issues/29.

Since @stof is contributing to both projects, Knp and SonataAdmin resp. SonataDoctrineORMAdmin maybe he can tell us if this would be a great improvement for SonataAdmin?

**Comment by rewotec** [comment]
:+1:

**Comment by webdevilopers** [comment]
A different approach would be using DTOs as suggested by @greg0ire in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/501 .

**Comment by webdevilopers** [comment]
I explained to @core23 on Twitter that I no longer maintain the projects that use Sonata.
I will try to comment on the issues anyway. I will close them if nobody else suggested a PR or similar.
