### ISSUE TITLE
[DX] Reduce bundle dependencies

### ISSUE THREAD

**Issue by wouterj** [sonata-project/SonataAdminBundle#2339]
This bundle requires a lot of other bundles to be registered, that doesn't make the bundle very friendly to install.

```
public function registerBundles()
{
    return array(
        new Sonata\CoreBundle\SonataCoreBundle(),
        new Sonata\BlockBundle\SonataBlockBundle(),
        new Sonata\jQueryBundle\SonatajQueryBundle(),
        new Knp\Bundle\MenuBundle\KnpMenuBundle(),
        new Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle(),
        new Sonata\AdminBundle\SonataAdminBundle(),
        // ...
    );
}
```

The SonatajQueryBundle can easily be removed and maybe the adapter bundle can have a parent/child relation with the SonataAdminBundle.

Or we should find a more friendly way to register these bundles.

**Comment by jordisala1991** [comment]
jQueryBundle is no longer required. Now with Symfony 4 and flex this should be less painful. Closing for now. If you think this needs to stay opened, just ping me
