### ISSUE TITLE
[DX] Add introduction in admin dashboard when no admin is available

### ISSUE THREAD

**Issue by wouterj** [sonata-project/SonataAdminBundle#2342]
When there are no admins, it would be nice if it could explain what you need to do. E.g. "There are no admins registered, create a class which extends `Sonata\AdminBundle\Admin\Admin`, register it as service and tag it with `sonata.admin`"

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by wouterj** [comment]
still valid

**Comment by core23** [comment]
Can you supply a PR for that @wouterj ?
