### ISSUE TITLE
AdminObjectAclData::getOwnerPermissions() does not exist

### ISSUE THREAD

**Issue by thomaskonrad** [sonata-project/SonataAdminBundle#2349]
Hello,

In the class `AdminObjectAclManipulator` from line 116 onwards, there is the following code:

``` php
// Restore OWNER and MASTER permissions
    if (!$data->isOwner()) {
        foreach ($data->getOwnerPermissions() as $permission) {
```

Now, the `AdminObjectAclData::getOwnerPermissions()` method does not exist and therefore throws a fatal PHP error if the owner of an object tries to revoke the owner permission from themselves.

How can this be fixed best? By the way, I'm on Sonata Admin Bundle v2.2.12.

Cheers
Tom

**Comment by ipalo** [comment]
+1
