### ISSUE TITLE
Deleting a oneToMany form in HTML results in database change even if user doesn't have DELETE permission

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#2352]
Without DELETE permission, the user cannot see a "Delete" box on each item in a oneToMany (`sonata_type_collection`) field. However, if the user deletes the HTML for that part of the form and submits it then the relationship is still removed from the database.

It would seem that checks are needed in the controller before unlinking entities from a oneToMany relationship, so the permissions are enforced in the back-end-processing as well as the front-end buttons?

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @caponica
