### ISSUE TITLE
Parent is rendered in filters in nested child admin list view though no other filters are defined by user

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2356]
I have a list view for an Entity `Operator` which is a child of `Contract` and has no filters.

When calling the `listView` without the Parent given via url `/admin/plusquam/contract/operator/list` everything is displayed correctely - no filters and additonal `contract_number` from the Parent reference:
```php
class OperatorAdmin extends Admin
{
    protected $parentAssociationMapping = 'contract';

    protected function configureListFields(ListMapper $listMapper)
    {
        if (!$this->isChild()) {
            $listMapper->add('contract.number');
        }

        $listMapper
            ->add('contract.projectManager.email')
            ->add('user.username')
            ->add('user.phone')
            ->add('user.email')
            ->add('instructed', 'boolean', array('editable' => true))
            ->add('responsible', 'boolean', array('editable' => true))
        ;
    }

//    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
//    {
//    }
```

When I call the `listView` with the given Parent via url `/admin/plusquam/contract/contract/2/operator/list` the filters appear though I have defined none:
```html
<div class="box-header">
<h4 class="box-title filter_legend active">Filter</h4>
</div>
<div class="box-body">
<form class="sonata-filter-form hide" role="form" method="GET" action="/admin/plusquam/contract/contract/2/operator/list">
<div class="filter_container active">
<div class="form-group">
<label for="filter_contract_value">Contract</label>
<input id="filter_contract_type" class="sonata-filter-option form-control" type="hidden" name="filter[contract][type]" style="display: none;">
<input id="filter_contract_value" class=" form-control" type="text" value="2" name="filter[contract][value]">
</div>
<input id="filter__page" type="hidden" value="1" name="filter[_page]">
<input id="filter__sort_by" class=" form-control" type="hidden" value="id" name="filter[_sort_by]">
<input id="filter__sort_order" class=" form-control" type="hidden" value="ASC" name="filter[_sort_order]">
<input id="filter__per_page" class=" form-control" type="hidden" value="25" name="filter[_per_page]">
<button class="btn btn-primary" type="submit">
<a class="btn btn-default" href="/admin/plusquam/contract/contract/2/operator/list?filters=reset">Zurücksetzen</a>
</div>
</form>
</div>
</div>
```

The filters are only generated because of the additional Parent filter. Anyway I don't think that this filter makes any sense. The "true filtering" is defined by the Parent ID in the URL:
`/admin/plusquam/contract/contract/2/operator/list`

An additonal filter from the form would make no sense and would have no effect anyway:
`/admin/plusquam/contract/contract/2/operator/list?filter[contract][value]=2`

Therefor the filters should be completey removed when no filters were defined by the user via the `configureDatagridFilters` method.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed. @webdevilopers

**Comment by webdevilopers** [comment]
Unfort. I don't have access to the scripts anymore. I will watch this behaviour on future projects though.
Thanks for doing an awesome cleanup @core23 !
