### ISSUE TITLE
Add support for `add` button in `sonata_type_model_autocomplete` 

### ISSUE THREAD

**Issue by pulzarraider** [sonata-project/SonataAdminBundle#2366]

**Comment by vlepeule** [comment]
+1

**Comment by pantelm** [comment]
:+1:

**Comment by dennisdag** [comment]
This would be great as possibility. I need this now for my project but can't get it to work in my sonata admin edit form for entity. To allow user to select tag from autocomplete or add new one. Something like Select2 with tagging support or similar to this: http://textextjs.com/manual/examples/autocomplete-with-tags.html

**Comment by julienrousseau** [comment]
:+1:

**Comment by NoScopie** [comment]
*bump*

Anyone a proper solution for this (or quickfix)?

**Comment by mushkin-v** [comment]
+1 will be very usefull

**Comment by webdevilopers** [comment]
I guess this is scheduled for after *2.4*, right @pulzarraider ?

**Comment by joshlopes** [comment]
+1

**Comment by ck-1** [comment]
:+1:

**Comment by npotier** [comment]
:+1:

**Comment by npotier** [comment]
Hello, 

I've created a quick fix for a project of mine, in order to allow **add** button in **autocomplete** fields. You can see it here : https://gist.github.com/npotier/a7b2b34f0daae7205f86.

Hope this helps

**Comment by rewotec** [comment]
:+1:

**Comment by bartoszmalec** [comment]
@npotier Why template added in array doesn't work? I get an error: The option "template" does not exist. Defined options are: ...

**Comment by OskarStark** [comment]
@npotier could you provide your fix as a PR

**Comment by npotier** [comment]
hi @OskarStark thanks for your message. I could make a PR, but i'm not sure how to propose a definitive solution:
- should I add an "allow_add" option to the ModelAutocompleteType ?
- should I create a new Type ModelAutocompleteTypeWithAdd ?
- should I just PR the template file and add in the documentation an entry to show how to configure the form Admin when you want the "add" feature ?

What do you guys think ?

**Comment by OskarStark** [comment]
thanks for your answer @npotier, IMO this would be   the best solution:

> should I add an "allow_add" option to the ModelAutocompleteType ?

ping @sonata-project/contributors

**Comment by npotier** [comment]
ok ! i'll wait for other opinions from @sonata-project/contributors and make the PR

**Comment by webdevilopers** [comment]
Definitely :+1: for "allow_add" option.

**Comment by OskarStark** [comment]
i think you can start the PR :smile: :smile:

2016-01-08 8:44 GMT+01:00 webDEVILopers <notifications@github.com>:

**Comment by webdevilopers** [comment]
You should wait for @pulzarraider and @rande - they are "the voice"! ;)

**Comment by OskarStark** [comment]
@npotier a PR would be great, if no one else raised there hands :smile:

**Comment by nicolaskern** [comment]
That's indeed a feature Sonata is highly lacking.
Another great thing would be to be able to add an entity when there is no result to the typed text!

**Comment by OskarStark** [comment]
> Another great thing would be to be able to add an entity when there is no result to the typed text!

We did this with `selectize` in our project instead of `select2`, because `select2` was a bit to complicated for this.

**Comment by nicolaskern** [comment]
I can't find a doc for that, where can I find it? Thanks ;)

**Comment by quiquegarcia** [comment]
@npotier PR please!

**Comment by npotier** [comment]
@quiquegarcia thanks for your feedbacks. I'll make a PR soon 😄

**Comment by psyray** [comment]
PR Created ;)

**Comment by psyray** [comment]
PR is ready to merge, functionality will be available soon ;)
