### ISSUE TITLE
Include link logout in Admin/dashboard

### ISSUE THREAD

**Issue by Chrysweel** [sonata-project/SonataAdminBundle#2371]
Hello.

I recently add the project Sylius to my project Symfony, so I had to remove the SonataUserBundle.
Because the version FOSUserBundle is unsupported by SonataAdminBundle.

But now I see that the link of logout when click in the icon user , in the top right corner of the screen, is empty..

How can I include the link to logout ? 

It was caused by remove SonataUserBUndle?
Thanks in advance !

**Comment by grekpg** [comment]
links do not work
