### ISSUE TITLE
Option to disable the sidebar (and the hamburger in the navbar)

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#2381]
Not everybody will want/need to use the sidebar on the left of the new theme so there should either be an easy option to turn it off or some documentation about how to do this.

The "hamburger" is the three lines in the `.sidebar-toggle` link, which are hard coded into the navbar at the moment.

(If I could figure out how to do it I'd be happy to write something...!)

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version.

If this is still present, feel free to reopen this issue

**Comment by daichihaji** [comment]
I guess there is still the same problem.

Even if I blank the {% block sonata_left_side %}{% endblock %} in 
{# customised_standard_layout.html.twig #}

The blank left pane appears.

**Comment by jordisala1991** [comment]
Does it happen on master?

**Comment by core23** [comment]
IMHO we don't need an option for everything. Sometimes you have to override the templates / css.

**Comment by daichihaji** [comment]
Happens on 3.9.0. I agreed that we don't need option for everything.

I have overrided standard_layout.html.twig and blank  {% block sonata_left_side %}{% endblock %}  in vain.

I am not sure how much people want to remove the left_side_pane though, if there is some indication, we really appreciate.

**Comment by caponica** [comment]
In my limited experience clients usually *don't* want the sidebar. They'd rather have a thin menu at the top of the screen, and sometimes insist on it.

However, so long as there's a clean (and ideally well documented) way to remove it, and the bundle doesn't expect/require there to be a sidebar for other reasons then there's no problem.
