### ISSUE TITLE
Current path for admin tabs are poining to the wrong direction

### ISSUE THREAD

**Issue by idhard** [sonata-project/SonataAdminBundle#2394]
You can reproduce the issue on Sonata Demo Site , for example when you have  child admin classes , in this case Post & Comments the tab for comments is pointing to the wrong direction when you go to the list of related Comments. 

steps for getting the issue:

http://demo.sonata-project.org/admin/sonata/news/post/list

click in some post 
http://demo.sonata-project.org/admin/sonata/news/post/1/edit

look at the comments
http://demo.sonata-project.org/admin/sonata/news/post/1/comment/list

if you check the tabs you will see the incorrect link
http://demo.sonata-project.org/admin/sonata/news/comment/list?id=1 
and should it be 
http://demo.sonata-project.org/admin/sonata/news/post/1/comment/list

Best

**Comment by ste93cry** [comment]
this seems to be related to #2505

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @idhard
