### ISSUE TITLE
The filter "doctrine_orm_date_range" with "sonata_type_filter_date_range" not work.

### ISSUE THREAD

**Issue by odimodugno** [sonata-project/SonataAdminBundle#2405]
Hi,
we upgraded "sonata-project/admin-bundle" and "sonata-project/doctrine-orm-admin-bundle" to dev-master version, but with this implementation in "configureDatagridFilters":

        $datagridMapper
            ->add('data', 'doctrine_orm_date_range', array(), 'sonata_type_filter_date_range', array(
                'widget' => 'single_text'
            ));

Sonata not submits the "between" rule to the query, so the result in list not change.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @odimodugno
