### ISSUE TITLE
How to change validations groups in "sonata_type_model_list" creation form?

### ISSUE THREAD

**Issue by Nadrshin** [sonata-project/SonataAdminBundle#2414]
"sonata_type_model_list" has "Add new" button. After click on it, I see creation form.
http://s019.radikal.ru/i607/1409/a8/85841d47f761.png
How to change validations groups in this form?

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue
