### ISSUE TITLE
Sonata admin export issue

### ISSUE THREAD

**Issue by zzforg** [sonata-project/SonataAdminBundle#2417]
Hi, I am trying to export a admin class data to csv file, but I am sure sure how to export the data with many to many? For example:
return [
        $this->getTranslator()->trans('Order Number') => 'id', 
        $this->getTranslator()->trans('First Name') => 'customer.First_name',
        $this->getTranslator()->trans('Last Name') => 'customer.Last_name',
        $this->getTranslator()->trans('Item name') => 'product.name, <- this is the part I working on, but failed
        ...]
Anyone have clue on it? I google it, comes a lot answer with overriding getDataSourceIterator method, but I really not sure how to do it, I'm new to sonata, please help!

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue
