### ISSUE TITLE
[Feature request] Default label translator strategy

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataAdminBundle#2419]
For the moment, I must specify the translator strategy for all admins, and it is always the same. I guess the ability to change the default label translator strategy would be quite helpful.

**Comment by tophsic** [comment]
Same as my comment on #3190

**Comment by OskarStark** [comment]
@greg0ire would you like to provide a PR?

**Comment by greg0ire** [comment]
Ok, I'll work on it this week-end!

**Comment by greg0ire** [comment]
see #3319

**Comment by jordisala1991** [comment]
To me, this seems the same as #3190

Im closing it for now, to unify issues. If you think those are 2 separate issues, please reopen again @greg0ire 

IMO we could open a new general issue about binding those generic services for all admins, instead of talking only about the translator
