### ISSUE TITLE
[Feature request]handle 401 gracefully in AJAX

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataAdminBundle#2428]
Scenario : 
1. I'm using an admin
2. My session ends (this happens when the cache is cleared).
3. I click on the "add" button that does an AJAX request to get the form for a related entity.
4. The server responds with a 401
5. The client does not get a popup.

I think there should be either be a popup indicating that the person should log again, or a page reload.

**Comment by webdevilopers** [comment]
I explained to @core23 on Twitter that I no longer maintain the projects that use Sonata.

**Comment by greg0ire** [comment]
I no longer care either, and cannot check easily, so let's close.
