### ISSUE TITLE
Proper way to use an embeded form type inside an Admin class

### ISSUE THREAD

**Issue by kminh** [sonata-project/SonataAdminBundle#2430]
Hi,

Currently I have a form type registered as a server, i.e. `my_form_type`. Attached to this form type is `my_entity` entity class. This form type is re-used in many places outside Admin.

What I would like to do is to use this form type inside Sonata Admin class as well, so I register `my_entity` as the entity class for `my_admin_class`, and then add this to the admin class:

``` php
    protected function configureFormFields(FormMapper $formMapper)
    {
        // Fields to be shown on create/edit forms
        $formMapper
            ->add('something', 'my_form_type', array(
                'label'  => false,
                'mapped' => false,
            ));
    }
```

With the above codes the form renders okay but when submitted validation fails because the data set on the actual form will be a blank new `my_entity` (the actual data is stored in the `something` child form, which gets validated successfully).

So, is there a way to solve this apart from having to re-add all the fields manually? Can I somehow modify the form builder to build using fields from `my_form_type`?

Thanks for any insight.

**Comment by ali-fassinet** [comment]
`// ....
class FooAdmin extends Admin {
    // disable validation
    protected $formOptions = array('validation_groups' => false);
    // ...
}`
