### ISSUE TITLE
How to get object value from admin class

### ISSUE THREAD

**Issue by zzforg** [sonata-project/SonataAdminBundle#2435]
Hi, I'm working on a project using sonata, just wondering if I create a method like getName() in admin class, how can I get the admin object? for example a admin class called: OrderAdmin.php, got a method getOrderName() defined by me:
protected function getOrderName(){
    //get the order object 
    $name = //To Do...
    return $name;
}
Please give a clue, I'm new to the framework. THX.

**Comment by core23** [comment]
If this is an active issue, please reopen @zzforg
