### ISSUE TITLE
Sonata's list doesn't work with PostgreSQL

### ISSUE THREAD

**Issue by Birmania** [sonata-project/SonataAdminBundle#244]
Hello,

I install Sonata AdminBundle on Symfony 2 with a PostgreSQL database and when I try to sort a list on a column, I obtain this error :
##
An exception has been thrown during the rendering of a template ("SQLSTATE[42P10]: Invalid column reference: 7 ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list
LINE 1: ..._.idsystem AS idsystem0 FROM systems s0_ ORDER BY s0_.codesy...
^") in "SonataAdminBundle:CRUD:base_list.html.twig" at line 28. 
##

It look like PostgreSQL need to have the "order by" columns in the SELECT statement to work contrary to MySQL.

Have you got a solution to solve this problem please ?

**Comment by Soullivaneuh** [comment]
Seems to be fixed by @helmer in #14.

BTW, this old issue seems to be not relevant anymore.

Going to close it.

@rande Please reopen it if i'm wrong.
