### ISSUE TITLE
[Feature request]DatePicker range

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataAdminBundle#2440]
[This comment](https://github.com/sonata-project/SonataAdminBundle/issues/2148#issuecomment-53071875) shows how to create a widget to get date range filter consisting of datepickers, but it would be great to be able to do this natively, by being able to somehow override the `field_type` option of the `sonata_type_date_range` widget.

**Comment by hidabe** [comment]
+1

**Comment by Renrhaf** [comment]
+1

**Comment by pulzarraider** [comment]
Fixed with sonata-project/SonataCoreBundle#155
