### ISSUE TITLE
Too many admin registered in mosaic mode

### ISSUE THREAD

**Issue by na-ji** [sonata-project/SonataAdminBundle#2461]
Hello !

I have two admin for the same entity. Everything worked fine. But now, when I go in mosaic mode, I got the error : 
```
An exception has been thrown during the rendering of a template ("Unable to found a valid admin for the class: , get too many admin registered: ") in SonataAdminBundle:CRUD:list_outer_rows_mosaic.html.twig at line 57.
```
In list mode, it is still working fine. 

Thanks ! :+1:

**Comment by core23** [comment]
If this is an active issue, please reopen @na-ji
