### ISSUE TITLE
BreadCrumbs create item - translate entity's name

### ISSUE THREAD

**Issue by Warxcell** [sonata-project/SonataAdminBundle#2468]
It would be nice to have opportunity to translate every class name. It's not very intuitive to have something like Company\Bundle\Entity\News:0000000036e0d9ea00007f83fb57cb4b in bread crumbs. I suggest CompanyBundleEntityNews as translatable.I don't think it's good to have check in your entity and return translated name if this is new entity. What do you think?

**Comment by AntonioCS** [comment]
I think the easiest thing to do is to overwrite the toString method in your admin class and return what you want.

This is what I have in mine:

    
```
public function toString($object) {
        if (!is_object($object)) {
            return '';
        }
        if (method_exists($object, '__toString') && null !== $object->__toString()) {
            return (string) $object;
        }
        
        $cname = explode('\\', get_class($object));
        return end($cname);
    }
```

This way in the create stage I just the name of my entity.

**Comment by richsage** [comment]
I'd agree with @Warxcell's suggestion of being able to specify a property to use - especially in cases where you are already using `__toString` for something else in your application (we are converting from a legacy admin bundle to Sonata at the moment).

**Comment by greg0ire** [comment]
@richsage : as @AntonioCS said, you're not obliged to use `Entity::__toString`, you can use `AbstractAdmin::toString`. Closing.
