### ISSUE TITLE
Remove link on relation ManyToOne OneToMany

### ISSUE THREAD

**Issue by TheKassaK** [sonata-project/SonataAdminBundle#2476]
I have an entity with a relation OneToMany (and another with ManyToOne.. yep)

When I display the list of my datas in my admin (show list), I can see a link on the field with a relation.

This link is for edit the data linked (url like /user/2/edit). I don't want it, how can I remove this link ?

**Comment by fsanter** [comment]
One year after, the easiest solution:
Instead of:
```
protected function configureListFields(ListMapper $listMapper)
{
    $listMapper
      ->add('user') // add a edit link to the related user entity
    ;
}
```
Just do:
```
protected function configureListFields(ListMapper $listMapper)
{
    $listMapper
      ->add('user', 'text') // 'text' type just display User toString method without link
    ;
}
```

**Comment by OskarStark** [comment]
@TheKassaK did this help?

If yes, please close this issue, thank you!

**Comment by webdevilopers** [comment]
Tried the solution provided by @cassianotartari with `null`, `false` etc., didn't work out.
Solution by @fsanter works just fine.

Please close @TheKassaK !

**Comment by OskarStark** [comment]
@webdevilopers would you create a PR for the docs? i think many people could use this trick

**Comment by webdevilopers** [comment]
Sure. Maybe @pulzarraider or @rande can confirm that this approach is best / only practice for this issue?

**Comment by ederrafo** [comment]
Hi Guys
The same but in **configureShowFields**  ?
I have in fiel **one-to-many** 

$showMapper
->add('segments', null, array('label' => 'Segments in payroll'))
;
I tried with: 'string', 'text', but it does not work

**Comment by Ehmz** [comment]
Same Problem with @ederrafo 

Even in my ListView it didn't work. @fsanter

**Comment by fabienCambournac** [comment]
I think it not the best way to do but you can use this trick for a fiel one-to-many : 
`$listMapper
     ->add('collection', null, [
                'route' => ['name' => ''],
     ]`
