### ISSUE TITLE
FosRestBundle braked SonataAdmin ajax call

### ISSUE THREAD

**Issue by spolischook** [sonata-project/SonataAdminBundle#2492]
When I try to submit popup with new entity, I get ajax error:
- Status: parsererror 
- Error: SyntaxError: Unexpected token

It happens because, in my FosRestBundle config I have 'fallbackFormat' as 'json', so Symfony response set as 'application/json' and in body of response I have html.
So, I suggest:

- Add log messages in all ajax calls for error event
- Add 'dataType' attribute to all ajax calls that expect html in response

In our application I temporary fix in child of CRUDController:
```php
public function render($view, array $parameters = array(), Response $response = null)
    {
        if (null === $response) {
            $response = new Response();
            $response->headers->set('Content-Type', 'text/html');
        }

        return parent::render($view, $parameters, $response);
    }
```
not the best solution, but it work.

**Comment by core23** [comment]
Can you provide a PR for this @spolischook

**Comment by spolischook** [comment]
@core23 if you find this issue maybe you can?

**Comment by core23** [comment]
Sorry, I am only cleaning up tickets ;) Never used the REST bundle.

**Comment by spolischook** [comment]
you can close if you wish? I don't need it anymore.

**Comment by core23** [comment]
Can you confirm that this issue doesn't occur anymore? @spolischook

**Comment by spolischook** [comment]
I don't use SontaAdmin anymore, so I can't. Don't care about it - if something went wrong next time, I will make a PR, For now, please, close this issue.

**Comment by spolischook** [comment]
oh I can close it ))
