### ISSUE TITLE
Using a bundle without vendor namespace causes route generation to fail

### ISSUE THREAD

**Issue by chartinger** [sonata-project/SonataAdminBundle#2493]
This issue is related to #2068

When using a bundle without a namespace, as suggested in [Official Symfony Best Practices](http://symfony.com/doc/download-best-practices-book/) an exception is thrown on cache warmup:

```
 [RuntimeException]                                                                                                                                 
  Cannot automatically determine base route name, please define a default `baseRouteName` value for the admin class `Sonata\UserBundle\Admin\Entity  
  \UserAdmin`
```

This may not be a problem for custom admins as you can set the baseRouteName but using a user entity outside a vendor-prefixed bundle will cause the build-in one to fail.

A suggestion would be changing the expression in [Admin.php](https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Admin.php#L58) to
```
const CLASS_REGEX  = '@(?:([A-Za-z0-9]*)\\\(Bundle\\\)?)?([A-Za-z0-9]+)Bundle\\\(Entity|Document|Model|PHPCR|CouchDocument|Phpcr|Doctrine\\\Orm|Doctrine\\\Phpcr|Doctrine\\\MongoDB|Doctrine\\\CouchDB)\\\(.*)@';
```
but i have not tested it extensively

**Comment by pulzarraider** [comment]
This issue was fixed by #2594 (merged into master, will be release as 2.4.0). Thank you for reporting the issue.
