### ISSUE TITLE
Datagrid filters hidden in base_list.html.twig

### ISSUE THREAD

**Issue by guidoheckmann** [sonata-project/SonataAdminBundle#2494]
In the latest version of the crud-template base_list.html.twig there is a function "hasDisplayableFilters" in line 213 which seems to hava a result value of "false", so my filters are not shown (display: hidden).
Also in the filters loop my defined filters are not shown because of the result of "{% if filter.isActive() and filter.options['show_filter'] %}" in line 223.

In the documentation I cannot find anything of these new features.
What do I have to do to get my filters shown? 
Help would be great!

**Comment by kakawi** [comment]
Hello,

I have the same problem, but I can't understand how you solved the problem
Could you explain decision for noob, please?

**Comment by guidoheckmann** [comment]
Hi Kawaki,

this issue is one and a half year old and was about a template feature 
of SonataAdminBundle which has got removed in newer versions. It was a 
mouseover dropdown where you could choose single filter items.
My problem was about an incompatibility between my own custom extension 
of standard_layout.html.twig and its parent after an update of 
SonataAdminBundle.

I suggest you to open a new issue with your problem or question.

Good luck, Guido



Am 25.02.2016 20:22, schrieb Gleb:
