### ISSUE TITLE
load content http instead of https

### ISSUE THREAD

**Issue by glasset** [sonata-project/SonataAdminBundle#2497]
i have a problem with sonata type collection or when i try to add a entity in other entity,like open a modal. modal dosen't pop because:

    [blocked] The page at 'https://*/edit' was loaded over HTTPS, but ran insecure content from 'http://***/app_dev.php/admin/core/append-form-field-…&elementId=s543f729f8fcc9_servicesPricing&objectId=1&uniqid=s543f729f8fcc9': this content should also be loaded over HTTPS.
     jquery.js:9631

    jquery.js:
    
        // Do send the request
        // This may raise an exception which is actually
        // handled in jQuery.ajax (so no try/catch here)
        xhr.send( ( options.hasContent && options.data ) || null );

i add x-forwarded-pro but dosen't work so i have no idea thx

**Comment by pulzarraider** [comment]
@glasset Did you find out the problem with losing https?

**Comment by rande** [comment]
closing this for now.

**Comment by ishapkin** [comment]
It is not sonata problem. It is solved by routing settings in your routing.yml
http://symfony.com/doc/2.8/routing/scheme.html

**Comment by ishapkin** [comment]
Or your nginx settings is wrong for symfony and https :)
http://blog.servergrove.com/2011/04/04/symfony2-quick-tip-generateurl-with-https-on-nginx/
