### ISSUE TITLE
Callback Filter

### ISSUE THREAD

**Issue by Warxcell** [sonata-project/SonataAdminBundle#2513]
Hello, when you have CallbackFilter, when page is refreshed the filter is hidden and you have to show it again.

Btw: I really like that filters are above table. It's very convenient. :)

**Comment by pulzarraider** [comment]
@Warxcell @webdevilopers @bobman38 can you please provide an example?

**Comment by bobman38** [comment]
Hi, here is a part of my CompanyAdmin :

    // Fields to be shown on filter forms
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $partnerCompanyOptions = array(
            'class' => 'Gbs\SupportBundle\Entity\Company',
            'required' => false,
            'query_builder' => function($repository) {
                return $repository->getPartners();
            },
        );

        $salesRepOptions= array(
            'class' => 'Gbs\SupportBundle\Entity\User',
            'required' => false,
            'query_builder' => function($repository) {
                return $repository->findSalesQB();
            },
        );

        $datagridMapper
            ->add('name')
            ->add('client', 'doctrine_orm_string', array(), 'choice', array('choices' => Company::$CLIENT))
            ->add('isPartner')
            ->add('partnerCompany', null, array(), null, $partnerCompanyOptions)
            ->add('salesRep', null, array(), null, $salesRepOptions)
            ->add('sector')
            ->add('canInvoice')
            ->add('address')
            ->add('country')
        ;

        $datagridMapper->add('geoLat', 'doctrine_orm_callback', array(
            'label' => 'GeoData',
            'callback' => function($queryBuilder, $alias, $field, $value) {
                if ($value['value'] == 1) {
                    $queryBuilder->andWhere($alias . '.geoLat IS NOT NULL');
                }
                else if ($value['value'] == 2) {
                    $queryBuilder->andWhere($alias . '.geoLat IS NULL');
                }
            }
            ), 'choice', array(
                'choices' => array('All', 'Provided', 'Not Provided')
            )
        );
    }

With the callback definition, this is doing the issue. Let me know if you need more info,
THANKS !

**Comment by Warxcell** [comment]
In code there is check if callback function returns true then it's shown, otherwise not.

**Comment by pulzarraider** [comment]
Yes, the return [value is checked](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Filter/CallbackFilter.php#L35). So the callback function should return `true` if it's applied (if does not contain empty value).

@bobman38 can you add `return true;` and the end of callback and test if everything works?

**Comment by bobman38** [comment]
OK it works I understand... So in my case the function must return true if value is equal to 1 or 2. And then the filter is correctly shown after the page refresh.

Sorry for the noise and thanks for the tip.

**Comment by pulzarraider** [comment]
@bobman38 thank you for feedback.

If everything is clear now, can we close thois issue @Warxcell?

**Comment by webdevilopers** [comment]
Everything looks fine. Should be closed @Warxcell !
