### ISSUE TITLE
Inner Scroll in List

### ISSUE THREAD

**Issue by Warxcell** [sonata-project/SonataAdminBundle#2514]
You can see in screenshot.
![inner-scroll](https://cloud.githubusercontent.com/assets/3340882/4744520/9ac6ffe2-5a30-11e4-8095-53044dbc7563.png)

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @Warxcell
