### ISSUE TITLE
[Feature] Layout Override with Twig Embed

### ISSUE THREAD

**Issue by Warxcell** [sonata-project/SonataAdminBundle#2517]
What do you think about Embed tag in Twig? I think the layout can be made editable with that tag. I can try to realize it and make PR.

**Comment by core23** [comment]
Can you create a PR for this @Warxcell

**Comment by jordisala1991** [comment]
Not sure if we need to keep these kind of issues opened that many years without any response. IMO it only generates noise.

Closing for now. @core23 if you think we should keep them opened, just reopen. And if @Warxcell wants to keep working on this, probably a new issue would be better.
