### ISSUE TITLE
Template problem with new version

### ISSUE THREAD

**Issue by graille** [sonata-project/SonataAdminBundle#2524]
Hi everyone !

Since the version 2.3 I have a problem when a load the administration : 

![admin tableau de bord](https://cloud.githubusercontent.com/assets/7689997/4781424/16f194a0-5c9e-11e4-830b-e7c6bdb96b7c.png)

I have searched during 3 days, but no ideas to solve this problem :(

Any idea ?
Ty ! :D

**Comment by pulzarraider** [comment]
Version 2.3.1 of `SonataCoreBundle` was released, so I am closing this issue.
