### ISSUE TITLE
sonata_type_model doesn't update when add a new entry

### ISSUE THREAD

**Issue by Fred-X** [sonata-project/SonataAdminBundle#2526]
Hello everyone,

I have a problem sonata_type_model field. I have a many-to-one relation between two entities News and Author.

Here is the field in the Newsadmin class:

```(php)
->add('author', 'sonata_type_model', array(
    'by_reference' => false,
    'empty_value' => 'Choose an author',
    'attr' => array(
        'style' => 'width:300px'
    ),
    'query' => $query_author,
))
```

it look like this:
![sonata-admin](https://cloud.githubusercontent.com/assets/8371785/4788126/b535819a-5db5-11e4-854c-6b3f44644f8a.png)

The problem is, when I click on the **Add new** and successfully add a new author, the field doesn't update with the new created author. I have no error and a success ajax call (nothing custom) with the right html (with the new author).

I have found, in javascript at **edit many association**, function **field_dialog_form_action_objectID_relation-name**, that the **.replaceWith(html)** is selecting **#field_container_content_objectID_relation-name**  and I only have **field_container_objectID_relation-name** in the html.

![sonata-admin-js](https://cloud.githubusercontent.com/assets/8371785/4788174/95cabcde-5db6-11e4-8fd3-ef26460436e1.png)

![sonata-admin-html](https://cloud.githubusercontent.com/assets/8371785/4788192/cfb083de-5db6-11e4-9b20-caea5e79eacd.png)

Is anyone have an idea to help me to resolve this problem?

Thanks!

**Comment by yuriricci** [comment]
Exactly the same problem for me... Did you solved?

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @Fred-X
