### ISSUE TITLE
wrong default object set in Admin.php at line 2541

### ISSUE THREAD

**Issue by oonxt** [sonata-project/SonataAdminBundle#2531]
The left menu is blank if login as a non superadmin.

change
$this->cacheIsGranted[$key] = $this->securityHandler->isGranted($this, $name, $object ?: $this);
to
$this->cacheIsGranted[$key] = $this->securityHandler->isGranted($this, $name, $object ?: $this->getNewInstance());

then it works.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @oonxt
