### ISSUE TITLE
Average for a list

### ISSUE THREAD

**Issue by glasset** [sonata-project/SonataAdminBundle#2532]
hello, 
i would like calculate a average on one field in my result filter, so i overwrite createQuery ,  work fine except the calculate average take all my db and no just the result of filter

   public function createQuery($context = 'list')
    {
      $query = parent::createQuery($context);

      $queryAvg = parent::createQuery($context);
      $queryAvg->select("avg(".$queryAvg->getRootAlias().".vatInclusivePrice)")
          ->getQuery();

        $this->getConfigurationPool()->getContainer()->get('session')->getFlashBag()->add('sonata_flash_info', $queryAvg->getSingleScalarResult() );
      return $query;
    }

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @glasset
