### ISSUE TITLE
ZipArchive::extractTo error due to filename on windows

### ISSUE THREAD

**Issue by aurelie-aimard** [sonata-project/SonataAdminBundle#2533]
Hi, 

Im not a dev but i get this error on windows when i try to install the sonata admin budle.
I guess its due to the directory/filename containing a dot. Can you fix that please it's blocking me. :'(

![capture](https://cloud.githubusercontent.com/assets/8122328/4824185/95bee628-5f57-11e4-9857-974dbb92f470.PNG)

**Comment by greg0ire** [comment]
Related : #2632
