### ISSUE TITLE
jQuery callback for Ajax calls on sonata_type_model fields

### ISSUE THREAD

**Issue by SiliconMind** [sonata-project/SonataAdminBundle#2541]
I have an admin form that uses jQuery to show/hide some form elements based on user selections. The problem is that this code needs to run also after user adds new entities with `btn_add`.

Is there any way to add a jQuery callback that will be invoked after an item is added to the `sonata_type_model` field?

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @SiliconMind
