### ISSUE TITLE
Add support for Doctrine Embeddables in list view

### ISSUE THREAD

**Issue by jamesmoss** [sonata-project/SonataAdminBundle#2542]
We've started using Doctrine Embeddables in our entities (http://doctrine-orm.readthedocs.org/en/latest/tutorials/embeddables.html) and noticed it's impossible to access their properties within a list view.

A colleague has put together a workaround for this (https://github.com/charlie-hadden/SonataDoctrineORMAdminBundle/compare/sonata-project:master...master) but it's a hack, it'd be great to get proper support.

**Comment by greg0ire** [comment]
1. wrong bundle, this is the admin bundle
2. might have been fixed since then, you should check
