### ISSUE TITLE
Value of the first field of form causes an unexpected behavior

### ISSUE THREAD

**Issue by laSyntez** [sonata-project/SonataAdminBundle#2543]
Hi everyone,

versions: Symfony: 2.3.9 | Sonata Admin: 2.2

I have noticed a strange behaviour when i try to validate one of my entities.
It happens when the property linked to the first field displayed in my form 
has a regex constraint to exclude brackets (pattern="#^[^<>\\]+$#").

This problem appears in 2 cases and only because of the value of the first field :

Case 1: if the value is "&lt;script" the entire page except the navigation bar
        is inside the html element which is supposed to contain the error message.
![sonata_admin-bug3](https://cloud.githubusercontent.com/assets/7249826/4883549/cfe5766e-6362-11e4-9277-19e18810e2d9.png)

Case 2: if the value is "&lt;script&gt;" the entire page disappears except the navigation bar
        and the error message.
![sonata_admin-bug2](https://cloud.githubusercontent.com/assets/7249826/4883564/203a05c6-6363-11e4-9568-4a6526b74e46.png)

Thanks in advance and sorry for my poor english.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @laSyntez
