### ISSUE TITLE
Firebug breaks controls in SonataAdmin 2.3

### ISSUE THREAD

**Issue by ethernal** [sonata-project/SonataAdminBundle#2546]
When I have firebug open all controls in Sonata Admin stop working properly: checkboxes cannot be clicked/Select2 enabled elements show no results and focused elements cannot be "unfocused" forcing me to reload the page if I need to click on another element.

I am using Firefox 33.0.2, Sonata Admin 2.3 stable, Symfony 2.5.6

**Comment by danielanteloagra** [comment]
Getting similar issue. 

In my case, my local project running dev-master works fine on chrome and safari, but gives js errors in Firefox 34.0.5 (Mac OSX Yosemite) when clicking on dropdowns, checkboxes etc.

Have just tried the official demo, and although is see no js errors in the console, the selects and filters do not work and lock up the controls (i need to refresh the page to get it to do anyting). Heres a quick video record if it helps:  https://www.youtube.com/watch?v=hW_IjoGhBvU&feature=youtu.be

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @ethernal
