### ISSUE TITLE
Configuration or Admin Class option to enable / disable mosaic list mode

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2551]
Related to my question here:
https://github.com/sonata-project/SonataAdminBundle/issues/2461#issuecomment-60731284

there seems to be no option (at least not documented yet in http://www.sonata-project.org/bundles/admin/master/doc/cookbook/recipe_customizing_a_mosaic_list.html) to disable the `mosaic list` view globally (except overriding the template) or oer Admin Class.

Are these options of interest?

**Comment by Soullivaneuh** [comment]
Also interested.

Is mosaic disabled global option already present for now? And per class?

For the moment, I found an ugly (for my opinion) method to disable mosoaic on one admin class:

```php
    /**
     * @param ListMapper $listMapper
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        unset($this->listModes['mosaic']);

        $listMapper
            // [...]
        ;
    }
```

But I have 49 admin's classes on my project, It will be very painful to add this on each class.

**Comment by webdevilopers** [comment]
@rande mentioned it on the *2.4* wish list under "Mozaic view list"
https://github.com/sonata-project/SonataAdminBundle/issues/2406

Not sure if this means that a configurable option will be available.

But there were some changes on the layout:
https://github.com/sonata-project/SonataAdminBundle/issues/1723

**Comment by OskarStark** [comment]
i added a custom BaseAdmin and added this method:
```php
{
    /**
     * @param ListMapper $listMapper
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        unset($this->listModes['mosaic']);
    }
```

and in my Admin:
```php
    /**
     * @param ListMapper $listMapper
     */
    protected function configureListFields(ListMapper $listMapper)
    {
        parent::configureListFields($listMapper);
        // ...
    }
```

but if you manipulate the url... you are allowed to visit the mosaic view...

**Comment by clytemnestra** [comment]
Any update on this? Manipulating the URL still works.

**Comment by linkito** [comment]
Again.... Any update?

For now, i have a javascript extending standard_layout.html.twig with:

```javascript
$(".fa.fa-th-large.fa-fw").parent().parent().remove();
````
But please, any better solution?

**Comment by clytemnestra** [comment]
I think

```php
$this->setListMode('list');
```

could be a temporary solution. This disables any other mode(like tree) or custom ones, if you've made any. How's that?

**Comment by kriodev** [comment]
@OskarStark or you can do it right in the constructor of BaseAdmin:

```
public function __construct($code, $class, $baseControllerName)
{
    parent::__construct($code, $class, $baseControllerName);

    // Disable mosaic list mode
    unset($this->listModes['mosaic']);
}
```

**Comment by OskarStark** [comment]
this is a better solution by far @kriodev 👍 

but anyway we should add a configuration option, maybe it would be better to deactivate it and make it opt-in

**Comment by Soullivaneuh** [comment]
> @OskarStark or you can do it right in the constructor of BaseAdmin:

@kriodev Maybe something can be done on the AdminExtension too.

**Comment by kriodev** [comment]
@OskarStark configuration option would be perfect indeed!

@Soullivaneuh BaseAdmin is part of my bundle and it extends \Sonata\AdminBundle\Admin\Admin if that is what you meant.

**Comment by Soullivaneuh** [comment]
@kriodev No I'm just saying that you may do something on class extending `AdminExtension` to avoid repetition.

**Comment by kriodev** [comment]
@OskarStark @Soullivaneuh I just realized that visibility of **listModes** property is set to **protected**, so there is even more elegant solution for BaseAdmin class without extending the constructor:

```
use Sonata\AdminBundle\Admin\Admin;

class BaseAdmin extends Admin
{
    protected $listModes = [
        'list' => array(
            'class' => 'fa fa-list fa-fw',
        ),
    ];
}
```

**Comment by tim96** [comment]
@Soullivaneuh @OskarStark hello. I created a small PR to add parameter in configuration file to show/hide mosaic button.
