### ISSUE TITLE
multiple nested collection fields & sonata_type_collection

### ISSUE THREAD

**Issue by Lavinia-Dan** [sonata-project/SonataAdminBundle#2552]
I'm pretty new to sonata admin bundle, and I could use some help.
Problem:
I have a Quiz entity, a Question entity, an Answer entity. And I need a form where I can add multiple questions to a lesson and each question can have one or multiple answers, these answers should also have a true or false flag.
So basically I need something like this:

![questions](https://cloud.githubusercontent.com/assets/5837544/4920000/cee19214-64fe-11e4-9428-59f569f0c53a.png)

So far I managed to make work only adding multiple questions from the admin. Actually a couple of versions ago (both sonata admin and doctrine) I had both questions and answers working. But now I can only add multiple questions while I can't add any answers. 
This is my QuestionType class:
```
<?php

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilder;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class QuestionType extends AbstractType {

    public function buildForm( FormBuilderInterface $builder, array $options )
    {
        $builder
            ->add('text', 'text', array( 'required' => false, 'label' => 'question' ) )
            ->add('answers', 'collection', array(
                    'type'               => new AnswerType(),
                    'allow_add'          => true,
                    'allow_delete'       => true,
                    'by_reference'       => false,
                    'delete_empty'       => true,
                    'cascade_validation' => false,
                    'label'              => 'Answers',
                    'options'            => array( 'label' => false ),
                    'label_attr'         => array( 'class' => 'answers' ),
            ));
    }

   
    public function getName()
    {
        return 'questions';
    }

    public function setDefaultOptions( OptionsResolverInterface $resolver )
    {
        $resolver->setDefaults( array(
            'data_class' => MyBundle\CoreBundle\Entity\Question',
        ));
    }

}
```
This is my AnswerType class:
```
<?php

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class AnswerType extends AbstractType {
    
    public function buildForm( FormBuilderInterface $builder, array $options )
    {
        $builder
            ->add('text', 'text', array( 'required' => true, 'label' => 'answer' ) )
            ->add('correct', 'checkbox', array( 'required' => false ) );
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'answers';
    }

    public function setDefaultOptions( OptionsResolverInterface $resolver )
    {
        $resolver->setDefaults( array(
            'data_class' => 'MyBundle\CoreBundle\Entity\Answer',
        ));
    }

}
```
This is my QuizAdmin class:
```
<?php 

use MyBundle\CoreBundle\Form\QuestionType;
use Sonata\AdminBundle\Admin\Admin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Route\RouteCollection;

class QuizAdmin extends Admin
{

    // Fields to be shown on create/edit forms
    protected function configureFormFields( FormMapper $formMapper )
    {
        $formMapper
            ->add('title', 'text', array( 'label' => 'Quiz Title' ) )
            ->add('description', 'textarea', array( 'label' => 'Quiz Description' ) )
            ->add('private', 'checkbox', array('required' => false ) )
            ->add('questions', 'collection', array(
                    'type'               => new QuestionType(),
                    'allow_add'          => true,
                    'allow_delete'       => true,
                    'cascade_validation' => false,
                    'by_reference'       => false,
                    'delete_empty'       => true,
                    'options'            => array( 'label' => false ),
            ));
    }

    // Fields to be shown on filter forms
    protected function configureDatagridFilters( DatagridMapper $datagridMapper )
    {
        $datagridMapper
            ->add( 'title' );
    }

    // Fields to be shown on lists
    protected function configureListFields( ListMapper $listMapper )
    {
        $listMapper
            ->addIdentifier( 'title' );
    }
}
```

I have also tried using sonata_type_collection but it does not work it returns this error:
"The current field "questions" is not linked to an admin. Please create one for the target entity"
I've looked this up and tried everything that was suggested on stackoverflow but I could not get it working. 
I would very much appreciate any advice on this matter.

And this is how the admin page for the quiz currently looks like with questions and answers:
![selection_003](https://cloud.githubusercontent.com/assets/5837544/4920018/dff66192-64fe-11e4-954a-32ae7f930a2b.png)

As I mentioned before some couple of versions ago before running composer.phar update I could add both questions and answers ( I do not remember the versions, but then I had some other problems with unique fields, I was happy that got fixed, but now I have this problem).

If you have any advice I would be happy to follow.

Thank you!

**Comment by webdevilopers** [comment]
If `Question` is an entity in your `Quiz` App then
**"The current field "questions" is not linked to an admin. Please create one for the target entity"**
means that you have not created an Admin Class / Service for it.

Just add it as you did with `Quiz` to your service and then THAT error should be gone.

**Comment by webdevilopers** [comment]
Feedback @Lavinia-Dan ? Close?

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @Lavinia-Dan

**Comment by dlespinosa365** [comment]
Check you sonata_services.yml. When declare you services, the second  argument is the entity linked to the service. 
arguments: [~,YourBundle\Entity\Quiz, ~]
