### ISSUE TITLE
Override action - list from other entity instead of show

### ISSUE THREAD

**Issue by ghostiiq** [sonata-project/SonataAdminBundle#2558]
Hey Guys,

Let's say we have 2 entities. One is Category and the other is Post.

What I want to do in Admin Backend is to list all posts related to category as soon as I click on the one of the listed categories. It's quite easy just to override action and list posts but I would love to leave all admin header, sortable options, etc.

I guess the point is to get correct datagrid in CategoryAdminControler.php and then add criteria somehow but I couldn't get through these steps.

Could You help me with handling this issue?

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @ghostiiq
