### ISSUE TITLE
Dasboard block roles

### ISSUE THREAD

**Issue by rccc** [sonata-project/SonataAdminBundle#2561]
Hello,

I don't see in the documentation is there is a way to display some blocks in the dashboards only for specified roles.

Thanks by advance

**Comment by krewetka** [comment]
Hi!

I think what @rccc meant is roles option for any block not only for dashboard groups.

For dashboard groups there is  ```roles: [ ROLE_ONE, ROLE_TWO ]``` but if you try to do something like:

``` 
dashboard:
        blocks:
          - { position: right,   roles: [ ROLE_ONE, ROLE_TWO ], type:  [...] }
```
you get "InvalidConfigurationException: Unrecognized options "roles" under "sonata_admin.dashboard.blocks.2"

I found this issue after searching for the solution for this problem.

I have many sonata admins visible only for some type of users and I need for example "recent orders" block visible only for some type of users.

I guess I'll have to make roles changing inside of the block and just return empty template if user shouldn't see the block at all.

**Comment by rande** [comment]
I just add the feature: https://github.com/sonata-project/SonataAdminBundle/commit/b8cc89f3edeee9c5749754e1e095953971e2364f

**Comment by Koc** [comment]
@rage please add support of call `AdminInterface::isGranted`, for example if we are having block with last N demands - depends from possibility to list this demands

**Comment by krewetka** [comment]
Thanks :+1:  Appreciate it.

Still it doesn't take roles into consideration everywhere. For example:

```<div class="{% if blocks.center|length > 0 %}col-md-4{% else %}col-md-6{% endif %}">```

You can have one central block which user has no rights to see. In this case there should be col-md-6 not col-md-4. The same in next part:

```
{% if blocks.center|length > 0 %}
<div class="col-md-4">
```
 There will be empty central section rendered.

**Comment by rande** [comment]
Can you try to make a PR ?

**Comment by krewetka** [comment]
Ok, I'll try tomorrow. Today I'm too busy.

**Comment by antoinemineau** [comment]
I am wondering why this feature is not in the 2.3.8+ releases.
