### ISSUE TITLE
Day, month and year select boxes of a date field rendered on different rows

### ISSUE THREAD

**Issue by wag-too** [sonata-project/SonataAdminBundle#2571]
I'm using Sonata Admin bundle 2.3.0 with symfony 2.5.6

I have the following issue:

I have an entity with property named 'validThrough' of type DateTime

I add the property to an edit form in the Admin class for the entity

```php
    protected function configureFormFields( FormMapper $formMapper )
    {
		$formMapper
			->add('validThrough', null,
				array(
					'format' =>  'dd MMM yyyy' ,
					'widget' => 'choice'
				)
			);
	}
```

This renders the day, month and year select boxes on 3 rows, instead of putting them on the same row.
![select2_enabled](https://cloud.githubusercontent.com/assets/3600794/5069144/24fb485c-6e5f-11e4-8fa5-a23331298365.jpg)

I tried adding a width attribute, but the same happens:

```php
'attr' => array (
    'style' => 'width: 200px;'
)
```

If I disable select2 via the config file, the 3 select boxes are on the same row.

![select2_disabled](https://cloud.githubusercontent.com/assets/3600794/5069147/37ddbbb2-6e5f-11e4-9c0d-722db5cb4a20.jpg)

**Comment by gotu** [comment]
I assume this is related to #2059 

I think it could be fixed by changing https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/public/css/layout.css#L202

to something like:
```css
div.sonata-medium-date .select2-container {
    width: 85px !important;
}
div.sonata-medium-date > div {
    float: left;
}
```

To quick-fix your instance you could do something like this:
```php
$formMapper->add('aDateTimeFieldName', 'datetime', array('attr' => array('class' => 'sonata-medium-date-custom')));
```
Integrating custom CSS, something like:
```
div.sonata-medium-date-custom {
    overflow: hidden;
}
div.sonata-medium-date-custom .select2-container {
    width: 85px !important;
}
div.sonata-medium-date-custom > div {
    float: left;
}
```

**Comment by wag-too** [comment]
Thanks! It works!

**Comment by tobemedia** [comment]
you could also use a datepicker. See: http://stackoverflow.com/questions/14443558/sonata-admin-bundle-datepicker-range

**Comment by OskarStark** [comment]
thank you @tobemedia :+1:
