### ISSUE TITLE
Popup pops out of bounds

### ISSUE THREAD

**Issue by karadza3a** [sonata-project/SonataAdminBundle#2572]
Pop up used for editing is getting below the top bar.

![screen shot 2014-11-17 at 12 58 13 pm](https://cloud.githubusercontent.com/assets/6049948/5069369/b677f07e-6e59-11e4-8793-109cd099368d.png)

**Comment by pulzarraider** [comment]
Fixed by PR #2965. Thank you @karadza3a for reporting the issue.
