### ISSUE TITLE
Enable allowClear and empty value for select2 on required field

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#2579]
With the `data-sonata-select2-allow-clear` attribute, it's possible to deactivate allowClear for no-required fields. That's good.

I think being able to activate allowClear for **required** field could be nice too.

Indeed, it's required field. But have a empty value on default will force user to choose a value and avoid human error.

Thanks.

**Comment by core23** [comment]
Can you check this again @Soullivaneuh
