### ISSUE TITLE
Try to avoid use of !important in CSS

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#2583]
E.g. in styles.css there is an entry:

    div.form-group div.select2-container {
        width: 80% !important;
    }

In my project I want to be able to vary this width in different scenarios, but to do so I'm going to have to add `!important` to all my related styles all the way down the cascade... if there's any way to avoid using !important in the plugin style sheets it would be much easier to work with them.

**Comment by core23** [comment]
Think this is fixed
