### ISSUE TITLE
list__action_* templates sould be cutsomizable

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#2586]
I think list__action_*.html.twig should be cutsomizable by the sonata configuration.

list__actions.html.twig should be customizable too.

**Comment by webdevilopers** [comment]
:+1: 

Sometimes it would be nice to simply add a line break between the action buttons.
https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/list__action.html.twig

**Comment by rande** [comment]
Feel free to send a PR to alter https://github.com/sonata-project/SonataAdminBundle/blob/master/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L317-L348 and related bundles ;)

**Comment by Soullivaneuh** [comment]
Yes I know, will do it when I'll got some time.

Thanks for the code clue anyway! :)
