### ISSUE TITLE
Search block admin - "The Request object has not been set"

### ISSUE THREAD

**Issue by cassianotartari** [sonata-project/SonataAdminBundle#2591]
Almost the same issue like here: http://stackoverflow.com/questions/19551715/sonata-admin-search-feature

When I try to search it throws: 

```
An exception has been thrown during the rendering of a template ("The Request object has not been set") in SonataAdminBundle:Core:search.html.twig at line 48. 
```

Tried to solve like in Stackoverflow but didn't work.

**Comment by ibasaw** [comment]
got same now on my project, work before, don't know why it doesn't now

i don't use $request in any of my admin class, i had disabled sonata.admin.block.admin_list in the blocks

**Comment by greg0ire** [comment]
Please reopen if you still experience this bug with Sonata 3.

**Comment by sujayjaju** [comment]
This is still a problem in Sonata 3

**Comment by sonars** [comment]
~~~~
return $this->request = $this->getConfigurationPool()->getContainer()->get('request_stack')->getCurrentRequest();

This worked when i checked it in AbstractAdmin (Symfony 3).

>> Are we expecting any fix for this.

**Comment by sujayjaju** [comment]
The workaround posted by @MKhalidJunaid made it work. It should have worked without the additional code in the Admin, right?

**Comment by kunicmarko20** [comment]
This was connected to Translations. TranslatableExtension in SonataTranslations had a call `getRequest()` that throws an exception, this is fixed with https://github.com/sonata-project/SonataTranslationBundle/pull/185. If someone still encounters this with search we will reopen.

**Comment by lukepass** [comment]
I am still experiencing this with Translation Bundle 2.2 (latest update).

**Comment by kunicmarko20** [comment]
Can you try with 2.x branch? As new version is still not released

**Comment by lukepass** [comment]
I am now receiving this error:

`An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 94 near 'tff WHERE ((tff.field': Error: Class AppBundle\Entity\CardMatch has no association named translations").`

My entity is an `AbstractTranslatable` and has no personal translation table, therefore it doesn't have a `translations` property.

**Comment by kunicmarko20** [comment]
Can you open a new issue on https://github.com/sonata-project/SonataTranslationBundle repo as this is no longer connected to this one.
