### ISSUE TITLE
Dual linked drop down

### ISSUE THREAD

**Issue by nepfrank** [sonata-project/SonataAdminBundle#2592]
I am trying to create linked drop down using sonata admin bundle.

There are
product
product_categories (many to many with product)
product_features (linked with product_categories) (Cardinality: many to many with product and many to one with category i.e. a category can have many features but a feature is link with one category)

Everything is working fine and one multi select enabled combo(for categories) field and another group of check boxes(for product_features) field are being displayed using this

In product entry form:
  protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper            
    ->add('category', 'sonata_type_model', array('required' => false, 'expanded' => false, 'multiple' => true, 'label' => 'Choose your categories'))
   ->add('features', 'sonata_type_model', array('required' => false, 'expanded' => true, 'multiple' => true, 'label' => 'Choose Features'))

But what I want is when I select value in first combo i.e. categories, the second list of checkboxes i.e. features should be dynamically loaded accordingly (only features linked with that category)

As the first select box is multi select enabled it will be even better is second list is cumulative i.e when category 1 is selected shows features related to category1 then when category 2 is selected(with 1 also selected) it shows features linked with cat 1 and cat 2

How can I do it?

Any help? Thanks in advance.

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @nepfrank
