### ISSUE TITLE
using `sonata_type_model_list` outside the admin edit

### ISSUE THREAD

**Issue by AlmogBaku** [sonata-project/SonataAdminBundle#2598]
Hi,
I'm trying for almost 5 hours to embed the `sonata_type_model_list` outside the admin edit.
I am working on replacement for the current Acl management, and I'm trying to embed the `sonata_type_model_list` for the users.. but I just cant do it.

I succeed to add form that built by the contractor.. but I can't add a `sonata_type_model_list` without adding an actual model with `users` member.
Is anyone have an idea?

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @AlmogBaku
