### ISSUE TITLE
Cannot use calls in an abstract admin service

### ISSUE THREAD

**Issue by he-li** [sonata-project/SonataAdminBundle#2606]
Hello,
In my project I'd like all my admin service using ```@sonata.admin.label.strategy.underscore```.
So i created a base_admin as this:
```
base_admin:
    abstract: true
    calls:
        - [ setLabelTranslatorStrategy, [@sonata.admin.label.strategy.underscore] ]
```
And then adding a line for other admin services :
```
some_admin:
    parent: base_admin
```
But it didn't work. I dug a little and found that the [compiler pass](https://github.com/sonata-project/SonataAdminBundle/blob/47384d43086d273e39eccbba933bd4959cc335d7/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L181) of SonataAdminBundle adds some services by default. And it checks only the definitions of the service itself but not their parent's. So the "calls" made in the parent service was overwritten.
So I added some code [here](https://github.com/sonata-project/SonataAdminBundle/blob/47384d43086d273e39eccbba933bd4959cc335d7/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L215) to check if his parent has the method.
Here is a quick solution:
```
if (isset($addServices[$attr]) || !$definition->hasMethodCall($method))
{
    // the parent service may have the method 
    if ($definition instanceof DefinitionDecorator
          && $container->getDefinition($definition->getParent())->hasMethodCall($method)) {
        continue;
    }
    $definition->addMethodCall($method, array(new Reference(isset($addServices[$attr]) ? $addServices[$attr] : $addServiceId)));
}
```

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @he-li
