### ISSUE TITLE
subclasses do not display in list views

### ISSUE THREAD

**Issue by asctSoftware** [sonata-project/SonataAdminBundle#2608]
Currently I cant get subclasses to appear in a list view.

I can get it working for create forms as per the advanced config page (http://sonata-project.org/bundles/admin/2-1/doc/reference/advance.html) but how can you do this with the list view? 

If i pass the subclass in the url - list?subclass=MySubClassName
and set the object in my listAction
```php
$object = $this->admin->getNewInstance();
$this->admin->setSubject($object);
```
I can get the subject and configure the correct fields with configureListFields()
```php
if ($subject instanceof MySubClassName) {
      $listMapper->add('MySubClassNameID');
      $listMapper->add('MySubClassNameKey');
      $listMapper->add('MySubClassNameStatus','text');
    }
```
but the end results table is always blank and the symfony debug toolbar seems to show that the db queries are looking for the parent class. Anyone got this to work?

**Comment by core23** [comment]
Please check this issue again and reopen if this is still active @asctSoftware
