### ISSUE TITLE
Add docs on using getRequest method to retrieve submitted (none-mapped) form data in callbacks

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2610]
In my `preUpdate` method I need to access the value of a none-`mapped` field.
Though this can be easily achieved by accessing the request object I have seen a "smarter" solution in some posts:

``` php
    public function preUpdate($object)
    {
        $uniqid = $this->getRequest()->query->get('uniqid');
        $formData = $this->getRequest()->request->get($uniqid);
        var_dump($formData);exit;
    }
```

This may help some people handling the form data in their callbacks.
Should I add it do the docs?
- https://groups.google.com/forum/#!topic/sonata-users/NS0mTAAHt7o
- http://stackoverflow.com/questions/22047454/sonata-admin-get-post-data/27405446#27405446
- http://stackoverflow.com/questions/21923548/sonata-admin-why-the-password-field-is-not-encrypted#21947488
- http://stackoverflow.com/questions/21515172/access-post-data-from-a-form-in-sonataadmin

**Comment by core23** [comment]
Feel free to create a docs update @webdevilopers

**Comment by webdevilopers** [comment]
After **2.4** release if that is ok with you?

**Comment by webdevilopers** [comment]
I explained to @core23 on Twitter that I no longer maintain the projects that use Sonata.
I will try to comment on the issues anyway. I will close them if nobody else suggested a PR or similar.
