### ISSUE TITLE
sonata_type_collection contains a form with sonata_type_collection: cannot sort 

### ISSUE THREAD

**Issue by Bomere** [sonata-project/SonataAdminBundle#2611]
Hello,

I'm facing a problem and I don't know if it's possible to use sonata collections embedded.

I'm trying to construct an array with lines and columns. In array form, the first sonata collection is lines. In lines form, sonata collection is columns. 

```php
class ArrayAdmin extends Admin {
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
                ->add('lines', 'sonata_type_collection', array(
                    'type_options' => array(
                        'delete' => true,
                    ),
                ), array(
                    'edit' => 'inline',
                    'inline' => 'table',
                    'sortable' => 'position'
            ));
    }
}

class LinesAdmin extends Admin {
    protected function configureFormFields(FormMapper $formMapper) 
    {
        $formMapper
                ->add('columns', 'sonata_type_collection', array(
                        'type_options' => array(
                            'delete' => true,
                        ),
                    ), array(
                        'edit' => 'inline',
                        'inline' => 'table',
                        'sortable' => 'position'
                    )
                )
            ;
    }
}
```
It's work well! 

You can see this on screen:
![begin](https://cloud.githubusercontent.com/assets/8299312/5395375/7de0dab2-8148-11e4-8e44-216ca31454b0.png)

![begincolor](https://cloud.githubusercontent.com/assets/8299312/5395371/70043718-8148-11e4-9091-c7dc549c9e4f.png)

But when you move a line ... The line is moved to the list of columns ... It can be avoid, but it's really tricky ! I can't imagine when an end user is going to use this ... 

The result:
![after_move](https://cloud.githubusercontent.com/assets/8299312/5395286/5145fa10-8147-11e4-87b8-d2163fdce7d9.png)

Can I fix this with a parameter or something else ? 
It's a problem if I use the property "position" in both ? 

Thank you,
Raphaël.

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @Bomere
