### ISSUE TITLE
Editing blocks from Composer, cannot go back to current Page

### ISSUE THREAD

**Issue by ronanguilloux** [sonata-project/SonataAdminBundle#2613]
This affects the admin-bundle, "~2.2,>=2.2.9" versions:

Using Admin interface, in Page edition, editing blocks using block edition (menu entry) leads you to  `/admin/sonata/page/page/[pageId]/block/list`.
There, editing a block now leads you to `/admin/sonata/page/page/[pageId]/block/[blockId]/edit`. Arrived at this point, you can always go back to the page edition using both a contextual page edition menu (left-hand side) or the breadcrumb links.

Instead, editing blocks using the (great!) Composer, which is in a Beta Version, leads you to a `/admin/sonata/page/block/[blockId]/edit` (no pageId variable in this URL) view, where there is no contextual page edition menu or available breadcrumb link to click on : you cannot go back to the page edition from this view.

**Comment by pulzarraider** [comment]
This issue seems to be related to [SonataPageBundle](https://github.com/sonata-project/SonataPageBundle) so please report the issue to the correct place.
