### ISSUE TITLE
sonata_type_date_picker gives incorrect date

### ISSUE THREAD

**Issue by ENDaZONELT** [sonata-project/SonataAdminBundle#2616]
Always when i edit my entity sonata_type_date_picker gives incorrect date
![screen5](https://cloud.githubusercontent.com/assets/1504224/5427445/50284b28-83a5-11e4-8748-6e42af5729a2.png)

![screen1](https://cloud.githubusercontent.com/assets/1504224/5427427/9b200c16-83a4-11e4-94af-cd35b43f0f84.png)

Information from debug toolbar
![screen2](https://cloud.githubusercontent.com/assets/1504224/5427428/9b20b79c-83a4-11e4-8bdf-8afc9ae9e25f.png)

Doctrine configuration
![screen4](https://cloud.githubusercontent.com/assets/1504224/5427425/9af07f82-83a4-11e4-873e-787ad0365363.png)

Any workaround ?

**Comment by pulzarraider** [comment]
@ENDaZONELT can you also paste here the related code from youd admin?

**Comment by ENDaZONELT** [comment]
From admin file:
->add('saleDate', 'sonata_type_date_picker')

Entity:
    /**
     * @var \DateTime
     */
    protected $saleDate;

    function __construct()
    {
        $this->saleDate = new \DateTime();
    }

**Comment by bobman38** [comment]
I have I think the same issue here.

My admin code is very simple:

    $formMapper->add('endMaintenance', 'date', array('widget' => 'single_text', 'required' => false,  'attr' => array('class' => 'datepicker')))

(endMaintenance is type date in db)

In DB I have 2015-07-13

![selection_009](https://cloud.githubusercontent.com/assets/4988590/5758890/96b3e646-9cc9-11e4-8c68-342da564aea8.png)

Each time the object is saved => minus 1 day...

**Comment by bobman38** [comment]
workaround:

    $formMapper->add('endMaintenance', 'datetime', array('widget' => 'single_text', 'required' => false,  'attr' => array('class' => 'datepicker')))

**Comment by pulzarraider** [comment]
I cannot reproduce the issue. 

@ENDaZONELT @bobman38 can you please test your code with current `master` version of `SonataCoreBundle`, `SonataAdminBundle` and `SonataDoctrineORMAdminBundle` if this bug still exists?

**Comment by drAlberT** [comment]
I have the same issue here

**Comment by drAlberT** [comment]
@pulzarraider Just tested with `master` version .. same issue

I think the problem could be the timezone 

    Model Format	same as normalized format
    Normalized Format	
    Object(DateTime) - 2015-04-30T00:00:00+0200
    View Format	
    Apr 30, 2015

My guess is the `+0200` has something to do ..

**Comment by jsampedro77** [comment]
It may be related to this symfony bug. It's already fixed.
symfony/symfony#12808

**Comment by Soullivaneuh** [comment]
@jsampedro77 is right. Just upgrade your Symfony version.

**Comment by drAlberT** [comment]
:+1:

**Comment by Arkemlar** [comment]
THIS IS STILL HAPPENING! Symfony 3.2.13. Is sonata that much retarded? Workaround shown above not work.

**Comment by greg0ire** [comment]
> THIS IS STILL HAPPENING! Symfony 3.2.13. Is sonata that much retarded?

![k59iepb](https://user-images.githubusercontent.com/657779/32861422-e3c44208-ca54-11e7-9c0e-418a0ab24f8b.gif)

Dude, your yelling at software! Written by benevolent people! If there is an issue, fix it with your superior intellect and make a PR, otherwise, let me refund you the $0 you spend on this, and don't use Sonata ever again.

**Comment by Arkemlar** [comment]
Well, it was impressive bombardment by me, too emotional actually, but it is cumulative effect of many silently silenced "WTF?!" exclamations. I refused to use Sonata but it is used in current project, so..
Cool gif tho))
