### ISSUE TITLE
Access control on datagrid filters of admin classes a current User can not access due to role

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2619]
I have an admin `SupplierContact` that has a `user` `sonata_type_model`.

``` php
abstract class AbstractContactAdmin extends Admin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->add('user', 'sonata_type_model', array(), array(
                    'property' => 'full_text',
                ), array(
                    'link_parameters' => $link_parameters
                ));
    }
}
```

The logged in user has the role to create and edit the `SupplierContact` but is forbidden to access any `User` related information.

Of course the final solution will allow him access to create the entity but I disabled the access to demonstrate my issue.

Though the user can not access the `User` list (role `ROLE_SONATA_USER_ADMIN_USER_LIST`) he can filter the usernames through the User Admin.

``` php
class UserAdmin extends SonataUserAdmin
{
    protected function configureDatagridFilters(DatagridMapper $filterMapper)
    {
        $filterMapper
            // Can be accessed by user even without role `ROLE_SONATA_USER_ADMIN_USER_LIST`
            ->add('full_text', 'doctrine_orm_callback', array(
                'callback' => array($this, 'getFullTextFilter'),
                'field_type' => 'text',
            ))
    }

    public function getFullTextFilter($queryBuilder, $alias, $field, $value)
    {
        if (!$value['value']) {
            return;
        }

        $queryBuilder->andWhere($queryBuilder->expr()->orX(
            $queryBuilder->expr()->like($alias.'.username', $queryBuilder->expr()->literal('%' . $value['value'] . '%')),
            $queryBuilder->expr()->like($alias.'.firstName', $queryBuilder->expr()->literal('%' . $value['value'] . '%')),
            $queryBuilder->expr()->like($alias.'.lastName', $queryBuilder->expr()->literal('%' . $value['value'] . '%')),
            $queryBuilder->expr()->like($alias.'.email', $queryBuilder->expr()->literal('%' . $value['value'] . '%'))
        ));

        return true;
    }
}
```

Is this the expected behaviour? Do I have to manually restrict access to the Datagrid filters?
Wouldn't it be an improvement to add a role like `ROLE_SONATA_USER_ADMIN_USER_FILTER`?

Possibly related:
- https://github.com/sonata-project/SonataAdminBundle/issues/1893

**Comment by jordisala1991** [comment]
Closing because this is a really old issue without any activity over the years.

This is the expected behavior, because the filter dont have any relation with the user.
Anyway you can add conditionals on your datagrid mapper to block certain filters to some users.

If you still think we should keep this issue opened because it is not enough, please ping me to reopen.
