### ISSUE TITLE
Multiple admins for same entity/document and child admins

### ISSUE THREAD

**Issue by krewetka** [sonata-project/SonataAdminBundle#2623]
Right now there is no way to add two admins for the same entity and use one of it as child for another admin. It's also described here: https://groups.google.com/forum/#!topic/sonata-devs/bziquOk3LYY

I proposed my change here: https://github.com/sonata-project/SonataAdminBundle/pull/2622

If there is better solution for this problem let me know.

**Comment by webdevilopers** [comment]
:+1:

**Comment by greg0ire** [comment]
I think this was fixed.
