### ISSUE TITLE
[Filter] 'choice' datatype

### ISSUE THREAD

**Issue by tiagojsag** [sonata-project/SonataAdminBundle#263]
From what I can see in the docs, no option to filter by a choice box (single or multi selection) is available. It used to work on previous versions (declaring the type as 'choice') but the dropdown never actually got populated with values passed on the array index "choices".
Right now, explicitly declaring a filter field type as 'choice' throws the following error:
No attached service to type named `choice`
vendor/bundles/Sonata/AdminBundle/Filter/FilterFactory.php at line 48

**Comment by hieuit7** [comment]
Great, thanks for help!!

**Comment by Zuhayer** [comment]
@tiagojsag Thanks for the reference.
