### ISSUE TITLE
[DX] Can't install on windows sometimes

### ISSUE THREAD

**Issue by wouterj** [sonata-project/SonataAdminBundle#2632]
This bundle contains some very long path names, which results in an error in Windows if I install it in my sf directory, as the path is then longer than the allowed length.

This means Composer throws an exception:

```
  [ErrorException]
  ZipArchive::extractTo(vendor/composer/fff56f00/sonata-project-SonataAdminBundle-68a836e\Resources\public\vendor\x-editable\dist\jquery-editable\jquery-ui-datepicker\css\redmond\images/ui-bg_gloss-wave_55_5c9ccc_500x100.png): failed to open stream: No such file or directory
```

I think we need to find a way to fix this.

**Comment by greg0ire** [comment]
How do you know it is a problem with length and not the mix of slashes and backslashes, for instance? Please reopen if this is still relevant.

**Comment by wouterj** [comment]
> How do you know it is a problem with length and not the mix of slashes and backslashes, for instance? Please reopen if this is still relevant.

Because Windows PHP doesn't care about the mixed slashes. And because Windows has a [maximum path length of 260 characters](https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath). The path shown is longer than 260 characters (if you transform it into an absolute path).

The bundle still contains this deep folder structure causing the issue (https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/public/vendor/x-editable/dist/jquery-editable/jquery-ui-datepicker/css/redmond/images/ui-bg_gloss-wave_55_5c9ccc_500x100.png).

A way to fix this is to flatten the directory structure a bit.

*(If a maintainer closes an issue, only maintainers can reopen it. Can a maintainer please reopen? Thanks!)*

**Comment by greg0ire** [comment]
> If a maintainer closes an issue, only maintainers can reopen it.

I did not know this… as per the path length issue, not sure how we could flatten this (at which point), and also, this will probably cause a huge BC-break.

Also, you say this fails only "sometimes". Am I to understand that it will succeed in `C:\`, but not in `C:\deep\deep\deep\directory`?

**Comment by wouterj** [comment]
> Also, you say this fails only "sometimes". Am I to understand that it will succeed in C:\, but not in C:\deep\deep\deep\directory?

Correct. (recently changed my dev root to C:\dev to avoid problems like this, but I can imagine it'll cause confusion for some beginners).

If the directory structure can't be flatten, maybe we should improve Composer to show a better error message?

**Comment by greg0ire** [comment]
> recently changed my dev root to C:\dev to avoid problems like this, but I can imagine it'll cause confusion for some beginners

Yeah, plus you're not the first to report this, see #2533

> If the directory structure can't be flatten, maybe we should improve Composer to show a better error message?

Or maybe `ZipArchive` itself ?

**Comment by jordisala1991** [comment]
As @greg0ire said, we can't do much on Sonata bundles to avoid this problem. Probably an issue on composer or php itself would be better, to atleast show a better error message.

Closing. If you feel like there is anything we could do, please ping me to reopen.
