### ISSUE TITLE
Stop events in preCreate, preUpdate or preDelete

### ISSUE THREAD

**Issue by INHack20** [sonata-project/SonataAdminBundle#2636]
Hello friends, please would be good in PreCreate, Preupdate preDelete (sonata.admin.event.persistence.pre_update) event could stop the event or workflow, validation logic for the event.

**Comment by jordisala1991** [comment]
There is a similar feature but you need to edit the hooks on the controller side: https://sonata-project.org/bundles/admin/3-x/doc/reference/saving_hooks.html

Read chapter 12.2

Closing this for now, if you still having this issue after reading the docs and using latest versions of Sonata, please ping me to reopen.
