### ISSUE TITLE
Object name - sonata admin bundle should escape it

### ISSUE THREAD

**Issue by DaliusK** [sonata-project/SonataAdminBundle#2637]
Sonata\AdminBundle\Admin\Admin::toString($object) has the following code:

    if (method_exists($object, '__toString') && null !== $object->__toString()) {
        return (string) $object;
    }

If, for some reason an object has __toString defined and it returns unsafe for html output value, it gets displayed with twigs' 'raw' filter.

standard_layout.html.twig lines 293-295:

    {% block notice %}
        {% include 'SonataCoreBundle:FlashMessage:render.html.twig' %}
    {% endblock notice %}

SonataCoreBundle:FlashMessage:render.html.twig:

    {% for type in sonata_flashmessages_types() %}
        {% set domain = domain is defined ? domain : null %}
        {% for message in sonata_flashmessages_get(type, domain) %}
            <div class="alert alert-{{ type|sonata_status_class }} alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                {{ message|raw }}
            </div>
        {% endfor %}
    {% endfor %}

This ofcourse leads to direct output of the user input, which may include html tags and it's too easy to make an xss vulnerability. Escaping the value for safe output to html in an doctrine entity __toString method does not make sense to me. I believe the Sonata\AdminBundle\Admin\Admin::toString should be responsible for properly escaping this value.

**Comment by pulzarraider** [comment]
The raw flash messages were introduces in #1862 to allow html inside the flash message so changing them will be a BC break. But I agree with you @DaliusK. Sonata should escape it by default. If anyone needs html in flash messages, he can overload the template.

**Comment by pulzarraider** [comment]
Fixed in #2665. Thank you @DaliusK for reporting the issue.

**Comment by pulzarraider** [comment]
@rande we should also release new 2.3.1 version of SonataAdmin. Will you please do it or can I?

**Comment by rande** [comment]
@pulzarraider yes please do it ;)

**Comment by pulzarraider** [comment]
Thank you :) New tag 2.3.1 created on branch 2.3.

**Comment by rande** [comment]
@pulzarraider GG
