### ISSUE TITLE
Add filter to form + Many To One

### ISSUE THREAD

**Issue by nielvrom** [sonata-project/SonataAdminBundle#2638]
I have 3 entities:
- Author
- Picture
- PictureLocale

These are the relations between them:
In my Picture Entity:
<pre>
/**
  * @var \DX\MyBundle\Entity\Author
  *
  * @ORM\ManyToOne(targetEntity="DX\MyBundle\Entity\Author")
  * @ORM\JoinColumns({
  *   @ORM\JoinColumn(name="authorID", referencedColumnName="authorID")
  * })
*/
private $author;
</pre>

In my PictureLocale Entity:
<pre>
/**
     * @var \DX\MyBundle\Entity\Picture
     *
     * @ORM\ManyToOne(targetEntity="DX\MyBundle\Entity\Picture")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="pictureID", referencedColumnName="pictureID")
     * })
     */
    protected $picture;
</pre>

I my PictureAdmin I have:
<pre>
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('picture.author', 'entity', array('class' => 'DX\MyBundle\Entity\Author'))
        ;
    }
</pre>

But I get the error Expected argument of type "object or array", "NULL" given . What am I doing wrong?

**Comment by afurculita** [comment]
Or @nielvrom you may try:

```php
protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('author', 'sonata_type_model')
        ;
    }
```

to add more functionality for the ```choice``` type. 

http://sonata-project.org/bundles/admin/2-3/doc/reference/form_types.html

**Comment by aivus** [comment]
No, you are not understand.

@nielvrom get error `Expected argument of type "object or array", "NULL" given (500 Internal Server Error)` when try to use 
` ->add('picture.author')` (with **dot**)

Dot mean something like this:` $pictureEntity->getAuthor()`

**Comment by afurculita** [comment]
Yes, @aivus, I do understand what ```dot``` stands for and what @nielvrom tries to do.

**Comment by aivus** [comment]
@afurculita, in author case
`PictureAdmin` have picture field (`PictureLocale` Entity). After this need get author from PictureLocale entity

**Comment by afurculita** [comment]
If ```PictureAdmin``` is the admin for the ```Picture``` Entity, you might want to do this:

```php
protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('author', 'sonata_type_model')
            ->add('locales', 'sonata_type_collection', array(), array(
                'edit' => 'inline',
                'inline' => 'table'
            ));
    }
```
You add ```locales``` field only if you have a bidirectional one-to-many association between ```Picture``` and ```PictureLocale```.

But I don't really know what is PictureLocale used for.

**Comment by core23** [comment]
If this is an active issue, please reopen @nielvrom
