### ISSUE TITLE
No CSRF token in the forms

### ISSUE THREAD

**Issue by Glideh** [sonata-project/SonataAdminBundle#2639]
I saw the issue #97, and it seems I have _quite_ the same symptoms. Here is the context:

* Using sonata-admin 2.4.x
* My forms with sonata-user 2.2.4 come with **no CSRF token**
* I have customized **no** template
* I can see the `form_rest()` in the related vendor template
* The **rewrite module activated** (by default) in NginX
* The forms are submitted with **no error** in my dev env (despite the lack of CSRF token !?)
* In production the submitted forms are redisplayed (empty) with the **error**

> The CSRF token is invalid. Please try to resubmit the form

Can someone help me with this ?

**Comment by pulzarraider** [comment]
@Glideh did you solve the issue?

**Comment by Glideh** [comment]
I didn't try yet.
There are so many classes I don't know exactly which one I have to subclass to be able to output the params.

**Comment by rande** [comment]
@Glideh you can try with the app.php file and dump the ``$_POST`` and ``$_GET`` variables. It is mostly something wrong on the layers: webserver, reverse proxy, etc ...

**Comment by Glideh** [comment]
Thanks, I didn't though of `app.php`, just added:
```php
print_r($_REQUEST);
die();
```
Gives me
```
Array
(
    [s54aa54180f8ba] => Array
        (
            [username] => preteur_test
            [email] => preteur@test.com
            [firstname] => Machin
            [lastname] => Chouette
            [website] => 
            [biography] => 
#[...]
            [_token] => 98lHPoCbFezPr3JX6wR7mIwaUtgUN56p8xsUVgMXEDg
        )
    [btn_update_and_list] => 
)
```
`uniqid` seem's not there indeed

**Comment by Glideh** [comment]
Ho I checked my nginx conf against the one from the official [cookbook](http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#nginx) and I saw
My conf
```ini
location / {
    try_files $uri /app.php;
}
```

Suggested conf
```ini
location / {
    try_files $uri /app.php$is_args$args;
}
```

This fixed my problem ! Thank guys for having pointed out nginx and the `GET` params

**Comment by Glideh** [comment]
Ho I checked my nginx conf against the one from the official [cookbook](http://symfony.com/doc/current/cookbook/configuration/web_server_configuration.html#nginx) and I saw
My conf
```ini
location / {
    try_files $uri /app.php;
}
```

Suggested conf
```ini
location / {
    try_files $uri /app.php$is_args$args;
}
```

This fixed my problem ! Thank guys for having pointed out nginx and the `GET` params
