### ISSUE TITLE
grid list performance problem

### ISSUE THREAD

**Issue by apoberez** [sonata-project/SonataAdminBundle#2648]
Grid list template rendering is extremely slow, 30-60 seconds because of associations mapping.

```
\Sonata\DoctrineORMAdminBundle\Admin\FieldDescription

public function getValue($object)
 {
        foreach ($this->parentAssociationMappings as $parentAssociationMapping) {
            $object = $this->getFieldValue($object, $parentAssociationMapping['fieldName']);
        }
        return $this->getFieldValue($object, $this->fieldName);
 }
```

what for that foreach?

with this, everything works ok:

```
public function getValue($object)
{
    $getter = 'get' . ucfirst($this->getFieldName());
    $value = null;
    if(method_exists($object, $getter)){
        $value = $object->$getter();
    }
    return $value;
}

```

**Comment by pulzarraider** [comment]
Indeed, the `foreach` is useless.

**Comment by rande** [comment]
The ``parentAssociationMappings`` is an empty array unless the grid is used to display an association. @pulzarraider the ``foreach`` is used to retrieve the valid target object: like ``post.author.name``

**Comment by pulzarraider** [comment]
Thank you @rande. So it;s not a bug.

**Comment by rande** [comment]
The ``getFieldValue`` might be optimised to cache the correct getter for the property.
