### ISSUE TITLE
Missing assets

### ISSUE THREAD

**Issue by danielanteloagra** [sonata-project/SonataAdminBundle#2671]
I'm setting up a fresh install of SonataAdminBundle, and several assets are missing after an asset:install and a bower install.

    404 Not Found
    /bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
    /bundles/sonatacore/vendor/components-font-awesome/css/font-awesome.min.css
    /bundles/sonatacore/vendor/select2/select2.css
    /bundles/sonatacore/vendor/ionicons/css/ionicons.min.css
    /bundles/sonatacore/vendor/select2/select2-bootstrap.css   
    /bundles/sonatacore/vendor/select2/select2.min.js

Assets after asset:install
![](http://i58.tinypic.com/20ilo4.png)

Assets after bower install 
![](http://i59.tinypic.com/35j9xmw.png)

*Note:* select2.min.js and select2.css are actually in /bundles/sonatacore/select2/  (outside vendor)

And also i´ve noticed that most dependencies in /bundles/sonatacore/vendor/ are reapeated in /bundles/sonataadmin/vendor/ , should they not bee sharing the same assets?

My bower conf is as follows:

    #bower.json
    "dependencies": {
        "sonata-project-admin-bundle": "master"
     },

    #.bowerrc
    "directory": "web/bundles/sonatacore/vendor"

My composer dependencies:

        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "2.1.*@dev",
        "sonata-project/datagrid-bundle": "2.2.x@dev",
        "sonata-project/user-bundle": "2.3.*@dev"

Thanks!

**Comment by pulzarraider** [comment]
The problem occurs because you are using `dev-master` of SonataAdmin which depends on SonataCoreBundle. Composer downloads you stable version of SonataCoreBundle which does not contain the assets.

If you want to use unstable master version of SonataAdmin, please, add this to your composer.json file:
```
"sonata-project/core-bundle": "dev-master",
```

**Comment by danielanteloagra** [comment]
makes sense, thanks sorted  now.
