### ISSUE TITLE
Use custom form template for each different form

### ISSUE THREAD

**Issue by nielvrom** [sonata-project/SonataAdminBundle#2672]
What I would like to do is:

add some text before a label in my form. I have a form like this:
<pre>
protected function configureFormFields(FormMapper $formMapper)
{
     $formMapper
         ->add('locale', 'choice', array(
             'choices'   => array('nl' => 'NL', 'en' => 'EN'),
             'required'  => true,
         ))
         ->add('pageid.tag', 'text', array('label' => 'Tag'))
         ->add('description', 'text', array('label' => 'Beschrijving'))
         ->add('content', 'textarea', array('label' => 'Tekst', 'attr' => array('class' => 'ckeditor')))
         ->add('files', 'file', array('required' => false, 'multiple' => true))
    ;
}
</pre>

Now I would like to add some text before my files field. What I've done now is:
Add this to my config.yml (overload the templates/form configuration option):
<pre>
sonata_doctrine_orm_admin:
    # default value is null, so doctrine uses the value defined in the configuration
    entity_manager: ~

    templates:
        form:
            - MurisBundle:PageAdmin:form_admin_fields.html.twig
</pre>

But this will be used for every form, can't I set specific form templates for specific forms?

**Comment by cassianotartari** [comment]
Have you read this: http://sonata-project.org/bundles/admin/master/doc/reference/templates.html#configuring-templates ? search for "setTemplate"

**Comment by webdevilopers** [comment]
The solution provided by @cassianotartari should work. Can we close this issue @nielvrom ?

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
