### ISSUE TITLE
Inline validation is broken for embeded admin classes

### ISSUE THREAD

**Issue by shkkmo** [sonata-project/SonataAdminBundle#2673]
It seems like this was done intentionally.

https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Admin.php#L1361

It prevents the admin->validate() from being called on embeded admins.

Why was this done? It seems like there should be a better solution for whatever this was trying to fix.

**Comment by MortisQc** [comment]
If I understand you problem correctly, that is what you need to validate embedded admins:
protected $formOptions = array(
        'cascade_validation' => true        
    );

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to reopen if this error still exists.
