### ISSUE TITLE
Change all entities values on check

### ISSUE THREAD

**Issue by vittore** [sonata-project/SonataAdminBundle#2674]
I have an entity with a boolean variable (default).
I would like when this variable change state to True the other one for the same table go to False. 
In fact I would like only one variable (default) for the same table is at True.

How to do this in sonata admin? Or is better to do in entity manager (listener)?

v.

**Comment by pulzarraider** [comment]
@vittore you can simply add this logic into yout entity (set another value when the first value is set inside setter):

```
class Article {
    
    private $foo;
    private $bar;
    
    public function setFoo($foo)
    {
        $this->setBar($foo);
        
        $this->foo = $foo;     
    }

    public function setBar($bar)
    {
        $this->bar = $bar;
    }
     //....
}
```

**Comment by vittore** [comment]
See my answer at:

http://stackoverflow.com/questions/26056810/sonata-admin-enable-action/27959091#27959091
