### ISSUE TITLE
[Form] Immutable array checkbox style is broken

### ISSUE THREAD

**Issue by WouterJ** [sonata-project/SonataAdminBundle#2679]
The AdminLTE immutable array checkbox form type style is broken (in other words, I hope you don't the lay-out of it too):

![sonata-immutable-array-checkbox](https://cloud.githubusercontent.com/assets/749025/5816097/cd9dc1fa-a09c-11e4-8882-71f06694a876.png)

Imo, the checkbox should either be on the left of the label or on the right. At least, it should be on the same line as the label.

**Comment by LordSpock** [comment]
Je obtiens la même erreur avec la participation de balises dans la classification paquet!
Une solution?

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @WouterJ
