### ISSUE TITLE
Bazinga hateoas integration

### ISSUE THREAD

**Issue by dantleech** [sonata-project/SonataAdminBundle#2683]
I am currently writing a Rest API for the CMF. We would like to expose the Sonata routes for the Objects which are managed by Sonata.

Would it make sense to integrate a Hateoas RelationProvider into the Sonata stack somewhere?

With such a relation provider we would be able to serialize to a Hateoas JSON document:

````php
$res = $hateoasSerializer->serialize($mySonataManagedObject);
````

````javascript
{
    "_links": {
         "html_edit" : "/admin/foobar/edit/123"
         "html_view" : "/admin/foobar/view/123"
         "html_delete" : "/admin/foobar/delete/123"
         "html_create" : "/admin/foobar/create"
    },
    "title": "My something"
}
````

What do you think @rande?

In the meantime I will try and implement this on the CMF side.

**Comment by dantleech** [comment]
See also https://github.com/willdurand/BazingaHateoasBundle/pull/35

**Comment by rande** [comment]
@dantleech So you want to expose admin information with Hateoas ? Can you explain the use case ?

**Comment by rande** [comment]
closing this ... moving discussion too the related PR.
