### ISSUE TITLE
Custom menu url in side menu

### ISSUE THREAD

**Issue by AntonioCS** [sonata-project/SonataAdminBundle#2691]
Hey,
I understand that the side menus are generated from the dashboard groups, but there is no way to change the url generated.

From what I have been reading it will always create a url to the list section.
I just want something like this:

![menus](https://cloud.githubusercontent.com/assets/1086401/5917606/9470059e-a616-11e4-8ae1-e08e5943b416.png)

The problem with this is that the Add link will go to the list url.
Is there any way to do this?

My current cms is not that big and having to go to the list page and then to the create page is hassle. It would be simpler to give the option to go to the create (or add) page directly in the side menu

**Comment by hason** [comment]
This issue should be solved by #2711.

**Comment by greg0ire** [comment]
#2711 has been merged, reopen if it does not fix your problem.
