### ISSUE TITLE
Dynamically generate labels for option values using filters

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2696]
Currently if you want to change the value for an option inside a filter you can use the `__toString()` method.

``` php
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('branch', 'doctrine_orm_model_autocomplete', array(
                    'operator_type' => 'hidden',
                ), null, array(
                    'property' => 'name'
                ));
    }
```

``` php
/**
 * @ORM\Entity
  */
class Branch
{
    public function __toString()
    {
        return sprintf('%s, %s', $this->getCompany()->getName(), $this->getName());
//        return $this->getName();
    }
}
```

I don't think it is possible to change this behaviour with filters at the moment.

But there is a promising feature coming up with Symfony:
https://github.com/symfony/symfony/issues/4067

The filters could do this:

``` php
        $datagridMapper
            ->add('branch', 'doctrine_orm_model_autocomplete', array(
                    'operator_type' => 'hidden',
                    'choice_labels' => function ($obj) {
                        return sprintf('%s, %s', $obj->getCompany()->getName(), $obj->getName());
                    }
                ), null, array(
                    'property' => 'name'
                ));
```

**Comment by webdevilopers** [comment]
BTW: There already is a property `to_string_callback` available for the `sonata_type_model_autocomplete`:
https://sonata-project.org/bundles/admin/master/doc/reference/form_types.html#sonata-type-model-autocomplete

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome to if you reopen this issue.

**Comment by webdevilopers** [comment]
Sorry, but I'm no longer working on this project.
