### ISSUE TITLE
Option operator_type not supported by every filter type e.g. doctrine_orm_datetime_range

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2698]
In issue https://github.com/sonata-project/SonataAdminBundle/issues/556#issuecomment-60874851 @pulzarraider mentions the `operator_type` which for instance can be used to hide the operator via:

``` php
$datagridMapper
            ->add('projectManager', 'doctrine_orm_model_autocomplete', array(
                    'operator_type' => 'hidden',
                ), null, array(
                    'property' => 'full_text',
                ));
```

Also see: https://github.com/sonata-project/SonataAdminBundle/issues/2360#issuecomment-60709236

Unfortunately this option does not exist for filters like `doctrine_orm_datetime_range`.

Hasn't it been added globally?

**Comment by pulzarraider** [comment]
Parameter `operator_type` contains only filters that use [DefaultType](https://github.com/sonata-project/SonataAdminBundle/blob/master/Form/Type/Filter/DefaultType.php). Other filters, like [DateTimeRangeType](https://github.com/sonata-project/SonataAdminBundle/blob/master/Form/Type/Filter/DateTimeRangeType.php) defines the operator directly as `choice`.

**Comment by webdevilopers** [comment]
Same for `doctrine_orm_choice`:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Filter/ChoiceFilter.php#L92

```php
        $datagridMapper
            ->add('branch', 'doctrine_orm_choice', array(
                'field_type' => 'choice',
                'field_options' => array('choices'=> $branchChoices),
                'operator_type' => 'hidden' // cannot be hidden?
            ))
        ;
```

I guess the easiest solution would be changing the `getRenderSettings` method to use the `getOption('operator_type')` method?
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Filter/ModelAutocompleteFilter.php#L125

Still have to check if the `operator_type` `hidden` is correctely (not) rendered in the twig template.

**Comment by webdevilopers** [comment]
Can you give me a short feedback on my last question @pulzarraider ?
I could create some PRs then.

**Comment by webdevilopers** [comment]
I explained to @core23 on Twitter that I no longer maintain the projects that use Sonata.
I will try to comment on the issues anyway. I will close them if nobody else suggested a PR or similar.
