### ISSUE TITLE
Unable to overwrite SonataAdminBundle:CRUD:base_list_field.html.twig

### ISSUE THREAD

**Issue by AntonioCS** [sonata-project/SonataAdminBundle#2704]
Hey,

I have overwrite the method getTemplate to return my template when base_list_field is called but I am still seeing the original template.

Here is the code:

    public function getTemplate($name) {
        $template = null;

        switch ($name) {          
            case 'base_list_field':
                $template = 'TestBundle:Admin:test_base_list_field.html.twig';
                break;
            default:
                $template = parent::getTemplate($name);
                break;
        }

        return $template;
    }

I have also tried overwriting directly in AddDependencyCallsCompilerPass.php, changing this:

base_list_field'          => 'SonataAdminBundle:CRUD:base_list_field.html.twig',
to
base_list_field'          => 'TestBundle:Admin:test_base_list_field.html.twig',

but I still get the original template.

What am I doing wrong here???

**Comment by amine26tz** [comment]
@AntonioCS, you don't have to overwite getTemplate, if you define your base_list_field (TestBundle:Admin:test_base_list_field.html.twig) in configuration. the getTemplate('base_list_field') will return your template.
