### ISSUE TITLE
Sonata Preview Mode Problem with Upload File Field

### ISSUE THREAD

**Issue by luizsoliveira** [sonata-project/SonataAdminBundle#2705]
The Sonata Preview feature allows viewing for updates for before effect it.

http://sonata-project.org/bundles/admin/master/doc/reference/preview_mode.html

This is working well for me, with text fields, numeric, date and others. But does not act when a file upload field.

In the first request, the preview, the file is successfully received, but the second request, the approval, the file is not sent.

The bundle can manage this automatically?

**Comment by rande** [comment]
The way files are handled by the form component make it impossible to use the preview feature as data are reposted (files are not for security reason).

**Comment by luizsoliveira** [comment]
@rande thanks for the reply.

have any suggestions on how I can solve this in my application?

**Comment by rande** [comment]
You need to implement your own FileType to store the file content somewhere so you can reuse this file when you are in the preview mode.
