### ISSUE TITLE
Dynamically select the columns that appear in the list action

### ISSUE THREAD

**Issue by luizsoliveira** [sonata-project/SonataAdminBundle#2706]
Dear, I would first like to thank the developers for this amazing bundle, it is truly fantastic!

I would suggest the following functionality:

Allow user to dynamically select the columns that appear in the list grid. The developer would set on $listMapper the available columns, and the user would select those of interest.

This is especially interessant when different users work on the same data, but each one is more interested in a fields subset. With this feature, I believe the inline editing could be even more applicable.

The selected columns could persisir only during the session, the developer could provide templates column groups, or in a more complete version, the selection could be persisted and associated with the user.

Here are my questions:

1) The functionality looks interesting?

2) What is the complexity, which would be the likely steps for development?

3) Is there something similar in the roadmap?

**Comment by webdevilopers** [comment]
Maybe there is a "select columns to show" feature in the 2.4 wishlist:
https://github.com/sonata-project/SonataAdminBundle/issues/2406

But you could also add a datagrid filter with the available columns. Then get the desired columns from request and dynamically add them on the `$listMapper`.

**Comment by core23** [comment]
Can you provide a PR for this @luizsoliveira
