### ISSUE TITLE
[Export] customize csv delimiter

### ISSUE THREAD

**Issue by omega19** [sonata-project/SonataAdminBundle#2707]
Hi,

I don't think it is possible to customize csv delimiter. (default delimiter is ',')

**Comment by OskarStark** [comment]
:+1:  good Job

@Soullivaneuh @rande can we merge this?

**Comment by Soullivaneuh** [comment]
@OskarStark please see https://github.com/sonata-project/SonataAdminBundle/pull/2708 and reason for this close.

cc @pulzarraider

**Comment by OskarStark** [comment]
thank you!

**Comment by greg0ire** [comment]
Uuuuh, why was this not closed?
