### ISSUE TITLE
sonata_type_admin shown as sonata_type_model

### ISSUE THREAD

**Issue by seb0zz** [sonata-project/SonataAdminBundle#2709]
I am trying to embed an entity for inline editing with the field type "sonata_type_admin". The strange thing is that it as shown sonata_type_model so I can only select entities from a list and not edit an entity inline.

Does anyone have a clue how this happens? This is the basic code of my entity, just omitted the irrelevant parts.

```
/**
 * @ORM\Entity
 */
class Parent
{
    /**
     * @ORM\OneToOne(targetEntity="Child", mappedBy="parent")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="child_id", referencedColumnName="id")
     * })
     */
    private $child;
}
```

This is the configureFormFields method of my admin class

```
protected function configureFormFields(FormMapper $formMapper)
{
    $formMapper
        ->add('child', 'sonata_type_admin')
}

**Comment by pulzarraider** [comment]
@seb0zz do you have the admin service for the `child` entity?  Can you please paste here the service definition of both services and the `configureFormFields` of the `child` entity?

**Comment by core23** [comment]
If this is an active issue, please reopen @seb0zz
