### ISSUE TITLE
Tab naming conflicts

### ISSUE THREAD

**Issue by lightglitch** [sonata-project/SonataAdminBundle#2715]
When you are adding a relation entity form in popup inside other entity admin, the tabs name are in conflict.

We should change "base_edit_form.html.twig":

```
href="#tab_{{ loop.index }}"
```
to 
```
href="#tab_{{ admin.code| slug }}_{{ loop.index }}"
```
and 
```
id="tab_{{ loop.index }}"
```
to 
```
id="tab_{{ admin.code| slug }}_{{ loop.index }}"
```

to avoid conflicts.

**Comment by blaues0cke** [comment]
Hopend that your solution also fixes https://github.com/sonata-project/SonataAdminBundle/issues/2862 but it does not. In addition `admin.code` was not available for me, I used `admin.uniqid` unstead.

**Comment by rande** [comment]
@blaues0cke can you send a PR ?

**Comment by lightglitch** [comment]
Fix at https://github.com/sonata-project/SonataAdminBundle/commit/10e4aed06e56e6972cc4d302586dac0026ca9236
