### ISSUE TITLE
Ivory\OrderedFormBundle\IvoryOrderedFormBundle and SonataAdminBundle

### ISSUE THREAD

**Issue by sinenco** [sonata-project/SonataAdminBundle#2723]
Hi, I write this issue cause with sonata_type_collection, there is a problem when we use Ivory\OrderedFormBundle\IvoryOrderedFormBundle. 

Bye.

**Comment by pulzarraider** [comment]
Can you please provide more informations and example?

**Comment by jordandegea** [comment]
If you want to see the bug : 

- Create a simple project. 
- Add SonataAdminBundle and https://github.com/egeloen/IvoryOrderedFormBundle
(The IvoryOrderedFormBundle overrides Forms)
- Create 2 entities (Entity1 and Entity2) and create a OneToMany Relation. 
( imagine property link is the OneToMany )
- Create an Admin Page:
       $formMapper->add('prices', 'sonata_type_collection', array('label' => 'Prices'), array(  'edit' => 'inline', 'inline' => 'table' )

And watch the result. we can see a tab with entity2 linked, but we can't add an other. 

I hope you can reproduce the bug.

**Comment by jordandegea** [comment]
Hi, is the problem fixed ?

**Comment by Soullivaneuh** [comment]
Maybe with #3714? Please close the issue if yes.

**Comment by greg0ire** [comment]
> Please close the issue if yes.

Please reopen the issue if no.
