### ISSUE TITLE
Breadcrumb displaying not friendly hash when creating new entity

### ISSUE THREAD

**Issue by pyrech** [sonata-project/SonataAdminBundle#2729]
Hi,

Currently, when creating a new entity, the breadcrumb is not really user friendly and looks like this:
![capture du 2015-02-19 16 05 43](https://cloud.githubusercontent.com/assets/2021641/6269047/314b2190-b851-11e4-87a3-8167cd8860c1.png)

Why not displaying a translatable string like 'new entity' instead?

**Comment by rande** [comment]
just define a toString method inside the Admin instance or add a __toString method inside your entity
