### ISSUE TITLE
Preview mode and re-validation problems

### ISSUE THREAD

**Issue by krewetka** [sonata-project/SonataAdminBundle#2731]
I have form with collection of media in it.

First I had a problem like the one described here https://github.com/sonata-project/SonataAdminBundle/issues/1618 and in many other places.

I manged to make it work with some javascript (changing input names and recreating it later on) but now I'm stuck with file field inputs resetting after entering preview mode despite description from docs :

"While in preview mode two buttons will be shown to approve or decline persistence of the entity. Decline will send you back to the edit mode with all your changes unpersisted but still in the form so no data is lost and the entity can be further adjusted".

I have similar problem when someone select not the correct file type. Then error message appear on this one file field but all other file fields are being reset as well.

Does anyone has the idea for any workaround? Is the only option avoiding file inputs in all the forms and using sonata_type_model_list and media bundle?

I really need user preview before submit and it makes required file input fields empty.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.
