### ISSUE TITLE
AppCache disables DELETE http method for delete in list view

### ISSUE THREAD

**Issue by scasei** [sonata-project/SonataAdminBundle#2735]
if you use following line in app.php:
```php
$kernel = new AppCache($kernel);
```
you have chances that you cant delete an object from the list view.
cause the http method overwrite doesnt work correctly

**Comment by pulzarraider** [comment]
Try add this code in app.php (after `$kernel = new AppCache($kernel);`):
```
Request::enableHttpMethodParameterOverride();
```

**Comment by scasei** [comment]
Dont you think this should work automatically?

**Comment by rande** [comment]
It should work unless there is a regression, see https://github.com/sonata-project/SonataAdminBundle/blob/master/Controller/CRUDController.php#L88-L97

**Comment by scasei** [comment]
seems to be solved.

thank you
