### ISSUE TITLE
ConfigureRoutes in Admin class

### ISSUE THREAD

**Issue by Ryxeuf** [sonata-project/SonataAdminBundle#2736]
I'm currently working on a project using SonataAdminBundle.
I was wondering why the protected function configureRoutes is called with a agument of the class itself (line 1213 in Admin.php).
What's lthe matter of giving an argument that the method knows as it's in the same class ?

Thank you

**Comment by pulzarraider** [comment]
This is mainly for clarity of the child admins, because the Admin class is now too complex.
In child admin It's clearer to write:

```
    protected function configureRoutes(RouteCollection $collection)
    {
        $collection->clearExcept(array('list'));
    }
```
than 
```
    protected function configureRoutes()
    {
        $collection->routes->clearExcept(array('list'));
    }
```
