### ISSUE TITLE
Unnecessary entyty in left menu (ignoring security config)

### ISSUE THREAD

**Issue by Slavenin** [sonata-project/SonataAdminBundle#2746]
After commit 41ecba8f2cd207be217035f9439a6219917cfd0d in left menu appeared entity that hidden for this role in security config. On dashboard there are none, only in left menu

**Comment by pulzarraider** [comment]
Commit 41ecba8f2cd207be217035f9439a6219917cfd0d is only fix of doc. It can't break any functionality of left menu or dashboard. Can you please add some examples of bug you have mentioned?

**Comment by SkyAgency** [comment]
I have the same problem, in dashboard (homepage admin) security works (I can see entity which I have access to) but in left menu I see all entity which shout have been seen only fot role ROLE_SUPER_ADMIN not user eg. ROLE_USER. Everything has been worked good earlier (bootstrap 2 template)

**Comment by SkyAgency** [comment]
Thank You, it works!

**Comment by Slavenin** [comment]
> Commit 41ecba8 is only fix of doc. It can't break any functionality of left menu or dashboard. Can you please add some examples of bug you have mentioned?
Yes, he did not break, and the next df42796fde5d850f04440fb344cac25caad25268

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.
