### ISSUE TITLE
no error messages from Constraints with inline validation

### ISSUE THREAD

**Issue by mltrx** [sonata-project/SonataAdminBundle#275]
There is no error message on field with inline validation.

Ex.

Entity Email field:

``` php

/**
 * @Assert\Email(message="No email")
 */
$private $email;

```

UserAdmin class form field defined with one-to-many (to Email entities):

``` php

                ->add(
                    'emails',
                    'sonata_type_collection',
                    array('required' => true),
                    array(
                        'edit' => 'inline',
                        'inline' => 'table'
                    )
                )

```

When a value of entity field "email" is not a correct email there is a global error under a form, but field on inline table is not marked with error - no div error class exists.

**Comment by xavierleune** [comment]
For those who are trying to find an answer, it has been given here: http://stackoverflow.com/questions/15497197/sonata-admin-type-collection-cascade-validation (this thread shows up on google so it can be useful to many people)
