### ISSUE TITLE
Sonata project filters do not appear.

### ISSUE THREAD

**Issue by Malstrom** [sonata-project/SonataAdminBundle#2752]
after a composer update and disappeared from sonata backend menu to filter records

**Comment by pulzarraider** [comment]
In `master` (upcoming 2.4) are filters hidden by default to improve the UI. User have to click which filters he want to use.

If you need some filters to be always visible, Use option [`'show_filter'=>true`](2751)

**Comment by Malstrom** [comment]
@pulzarraider thanks, but i new in sonata, where i should insert this code: 
'show_filter'=>true

**Comment by pulzarraider** [comment]
See [action_list.rst](https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/doc/reference/action_list.rst#filters)
