### ISSUE TITLE
New theme: Admin LTE 2.0

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataAdminBundle#2753]
Admin LTE 2.0 is out! https://github.com/almasaeed2010/AdminLTE/tree/v2.0.2

Did you plan an upgrade for sonata-admin 2.4 before stabilization?

I can start a PR about it if you are interested.

Thanks.

**Comment by rande** [comment]
Hello,

Can you evaluate the change before starting to work on it ? We need to know if there are any major BC break.

**Comment by Soullivaneuh** [comment]
According to this [upgrade note](http://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#upgrade) and the [preview](http://almsaeedstudio.com/themes/AdminLTE/index2.html), I don't think that will create major BC break.

It's generally some re-factoring and optimization plus, some optional new functionalities.

But the better way I think it's to try this out! ;)

**Comment by desarrolla2** [comment]
See upgrade guides.
http://getbootstrap.com/migration/ and http://almsaeedstudio.com/themes/AdminLTE/documentation/index.html#upgrade

**Comment by Soullivaneuh** [comment]
@desarrolla2: please note that last version of sonata admin is already on twitter bootstrap 3.x.

**Comment by desarrolla2** [comment]
Sorry, I was confused, I thought the AdminLTE1 used boostrap2.

**Comment by Soullivaneuh** [comment]
@rande: Just one question: Should I fully copy the library or integrate it with bower?

**Comment by rande** [comment]
@Soullivaneuh you can create a PR, but not sure if we can merge it with the 2.4 release. I will test it with the sonata sandbox. Anyway if it is not merge in a 2.4 release it will be for the next release. 

You can use bower like the current theme.

**Comment by Soullivaneuh** [comment]
Ok so I'll remove actual source code and work with you to update the documentation.

Thanks.

**Comment by adyballa** [comment]
broke my installation:
"AdminLTE.js" not found

**Comment by adyballa** [comment]
please do not use master-branches if possible.

**Comment by rande** [comment]
@adyballa don't know what you are talking about.

**Comment by adyballa** [comment]
"AdminLTE": "https://github.com/almasaeed2010/AdminLTE.git#master"

**Comment by Soullivaneuh** [comment]
@adyballa It's normal because last version of admin-lte is not incorporated yet.

@rande: I'm trying to use sonata-sandbox 2.4-develop but I get a blank page.

Which branch could I try to run sonata sandbox properly with last version of sonata-admin?

Thanks.

**Comment by adyballa** [comment]
can I use without AdminLTE. Do some statitcs.
This broke my installation and i dont bother much about css.
btw: 
                                'bundles/sonataadmin/vendor/AdminLTE/css/font-awesome.min.css',
                                'bundles/sonataadmin/vendor/AdminLTE/css/ionicons.min.css',
(Configuration.php line: 194-195 is now comming from an CDN)

**Comment by adyballa** [comment]
@Soullivaneuh did it mean that you cant go back? So I always use versions.

**Comment by Soullivaneuh** [comment]
@adyballa: Which version are you using?

Btw, nothing was comited about that update on master, I didn't event start the PR! ;)

**Comment by adyballa** [comment]
@Soullivaneuh Sry - you'r perhaps right, it's offtopic (perhaps what u mean with PR). But I'm really dissapointed that I loose a day by "composer update". This on a behaviour I dont bother about. In the newest commit in LTE is an error in the bower.json, if i understand it right. But i understand that u do not rely on master. Thats not good and it s not good to hardcode some dependencies in the configuration-file. thats error-prone.
I'm using 2.3

**Comment by adyballa** [comment]
@Soullivaneuh I will test it by tomorrow. Is "#admin-lte-2.0" tag I can use via composer?
I can hope for 2.3 or other stable versions which rely on LTE to change the master dependency and change at the best to a tag or version.

**Comment by adyballa** [comment]
I've got some replies from almasaeed2010
"you should only use usable releases since the master branch changes a lot and contains known errors"
and
"AdminLTE.js was available for v1 only. AdminLTE 2.0 uses app.js instead. "
So every #branch will include v2.0 even if it wants to include "v1.0".

**Comment by Soullivaneuh** [comment]
@adyballa: To be clear, sonata 2.3 use adminLTE v1 with good css/js files.

If you use adminLTE#master from bower, and replace it on sonata, use it as your own risks, it is not sonata fault.

**Comment by adyballa** [comment]
And what does this?
https://github.com/sonata-project/SonataAdminBundle/commit/0a410b05b91e50c6f2345c53bdd46722318fbed9

/bower.json line10

**Comment by Soullivaneuh** [comment]
Hmm didn't know about that.

I was not using bower installation but directly vendors on sonata repo.

**Comment by adyballa** [comment]
@Soullivaneuh And how can I fix it without disturbing the update-cycles?

For me this is a bug or at the best the file is not necessary

**Comment by Soullivaneuh** [comment]
@adyballa I think of two solutions:

 * Use directly the default assets store on repo. Like a classic installation of the bundle.
 * Use your assets by overriding `standard_layout.html.twig` and tell you bower to use 1.3.x version of AdminLTE.

Hope this help.

**Comment by adyballa** [comment]
@Soullivaneuh I dont know if we understand us right. I use SPBowerBundle and I cannot update. I used Sonata to make a rapid installation of some db-calculation and i dont know much about bower and i dont use ADminLTE at all. It seems that I have to dig into bower. I appreciate your kind and fast help, but i dont like the general underlying way of thinking (not yours especially). You have to try to make your model as explcit as possible and use as few couplings as possible. It doesnt make any sense to use such rules if their essentials are not understand. Each of this "feature" means that I have to learn some technique which must be clear if you make the decision (a.k.a. explicit) and not after some digging (a.k.a. implicit). But its not bad to learn something and perhaps i can use AdminLTE/bower for some other projects.

**Comment by Soullivaneuh** [comment]
Closed in favor of PR.

**Comment by paquitodev** [comment]
@Soullivaneuh is this already merged on SonataAdmin? If not I would like to use it, could you help me to achieve this?

**Comment by Soullivaneuh** [comment]
@paquitodev Admin-LTE 2 is running on Sonata 2.4.
