### ISSUE TITLE
AdminLTE v2 instead of v1 in 2.3

### ISSUE THREAD

**Issue by adyballa** [sonata-project/SonataAdminBundle#2758]
https://github.com/sonata-project/SonataAdminBundle/commit/0a410b05b91e50c6f2345c53bdd46722318fbed9

/bower.json is broken in line10. It includes master-branch with known errors of AdminLTE (v2 at the current moment)

**Comment by adyballa** [comment]
Versions <1.3.0 are compatible with DIC-configuration-defaults. So I suggest to update /bower.json with
"AdminLTE": "https://github.com/almasaeed2010/AdminLTE.git#<1.3.0"

**Comment by adyballa** [comment]
If anyone uses SPBowerBundle like I do and has some troubles (like I do).
The configurations are useful like this:
sp_bower:
......
    bundles:
        SonataAdminBundle:
            config_dir: .
            asset_dir: Resources/public/vendor

**Comment by rande** [comment]
AdminLTE2 will be available for Sonata2.4

**Comment by adyballa** [comment]
@rande There is a bug in /bower.json in at least 2.3
it includes the master-branch. Which you should not do (said the owner of the AdminLTE. master includes and WILL include bugs). It is now version 2 
its not clear if the file is obsolete or the include is a bug

**Comment by adyballa** [comment]
@rande so its still open
