### ISSUE TITLE
batch delete fails due to foreign key constrain

### ISSUE THREAD

**Issue by AntonioCS** [sonata-project/SonataAdminBundle#2759]
I have override the delete action in my admin class but I noticed that there is no way to override the batchDelete without override the CRUDController.

I am getting a foreign key constraint error because the code just issues a batchDelete from the $modelManager.

Is is not possible to just get the entities from the ids that were submitted and just run the delete action on all of them? I also want to do a soft delete.

**Comment by greg0ire** [comment]
I don't think it is possible.
