### ISSUE TITLE
Error messages displayed twice with form type "sonata_type_native_collection" and "error_bubbling" sets to false

### ISSUE THREAD

**Issue by fancyweb** [sonata-project/SonataAdminBundle#2761]
Admin class : 

``` php
protected function configureFormFields(FormMapper $formMapper)
{
    $formMapper
        ->add('aliases', 'sonata_type_native_collection', array(
            'type' => 'text',
            'error_bubbling' => false
        ));
}
```

If validation fails for the field "aliases", the error message will be shown twice.

The first time comes `sonata_type_native_collection_widget` (https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Form/form_admin_fields.html.twig#L230), the second time  from `form_row` (https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Form/form_admin_fields.html.twig#L200).

I think we have to delete the call to `form_errors` in the `sonata_type_native_collection_widget` because `sonata_type_native_collection_widget` is called from `form_row`.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by Nadrshin** [comment]
I use sonata-project/admin-bundle 3.16.0. This bug has not been fixed yet.

**Comment by ketamina96** [comment]
Did anyone found any solution for this problem ?

**Comment by Nadrshin** [comment]
@ketamina96, add this code to from theme:

```
{% block sonata_type_native_collection_errors %}
    {% if form.rendered %}
        {{ form_errors(form) }}
    {% endif %}
{% endblock %}
```

**Comment by ketamina96** [comment]
@Nadrshin it doesn't work. It still shown twice.

**Comment by sad270** [comment]
Hello, i have same issue on SonataAdminBundle 4.31.0

<img width="719" alt="Screenshot 2024-08-29 at 16 37 40" src="https://github.com/user-attachments/assets/68202e01-e0fc-4bac-83af-caa498cde3cd">
