### ISSUE TITLE
Select2 4.0

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataAdminBundle#2773]
Well, we have nearly integrated Admin LTE 2.0 (#2754).

It's beautiful, isn't it? :)

Another proposition before 2.4.x stabilization: Integrate select2 4.0

I already made it on some of my project, works like a charm without lot of modification. You heard it @rande? Nearly no BC breaks! :+1: 

Furthermore, the big advantage is the twitter bootstrap integration directly on library core, no need of another tricky substitute.

See here: https://select2.github.io/examples.html

Select2 is on 4.0.0-rc.1 for the moment, near to stable release. It would be so bad to miss it integration on 2.4.

4.0 milestone: https://github.com/select2/select2/milestones/4.0

What do you think about that?

Thanks.

**Comment by rande** [comment]
@Soullivaneuh let's go!

**Comment by Soullivaneuh** [comment]
Select2 seems to be configured on core-bundle and use on admin-bundle.

Here is another bundle using select2 from core-bundle?

**Comment by Soullivaneuh** [comment]
Closed in favor of pull-request.
