### ISSUE TITLE
Filter for a "IS_NULL" Field

### ISSUE THREAD

**Issue by JackJones** [sonata-project/SonataAdminBundle#279]
Currently it isn't possible in the Filter for filtering on a field with one have the values "NULL" and "1".

**Comment by webdevilopers** [comment]
Can you provide a code example? Have you tried `doctrine_orm_callback`?
http://sonata-project.org/bundles/doctrine-orm-admin/master/doc/reference/filter_field_definition.html#callback

**Comment by webdevilopers** [comment]
No feedback. Possible solution by @joergbasedow:
https://gist.github.com/joergbasedow/5964815

If we don't want to feature this filter type the issue should be closed @Soullivaneuh .

**Comment by Soullivaneuh** [comment]
@webdevilopers your links are workaround with callback method IMO.

I keep this issue open. Having a IS_NULL filter is not a bad idea and contributors are free to make PR about that. :+1:

**Comment by webdevilopers** [comment]
:+1:

**Comment by jordisala1991** [comment]
Is there any change that this has been implemented in all those years?

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/649
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/650

WDYT @Soullivaneuh , can this be closed or it is still relevant?

**Comment by core23** [comment]
This issue is very old. Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
