### ISSUE TITLE
FatalErrorException incompatible interface AdminInterface

### ISSUE THREAD

**Issue by xaben** [sonata-project/SonataAdminBundle#2796]
I am getting a fatal exception after today's vendor update.

FatalErrorException in Admin.php line 48: Compile Error: Declaration of Sonata\AdminBundle\Admin\Admin::validate() must be compatible with Sonata\AdminBundle\Admin\AdminInterface::validate(Sonata\AdminBundle\Validator\ErrorElement $errorElement, $object)

The issue is located here:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/AdminInterface.php#L21

The interface still references the validator from Admin Bundle but not from CoreBundle.

**Comment by Atko** [comment]
Same here.

**Comment by ajeetvarma** [comment]
Same here also

**Comment by rande** [comment]
Fix https://github.com/sonata-project/SonataAdminBundle/commit/c30b4889d9b02ccefaead92e592d02235bbbd7b1
