### ISSUE TITLE
List entity with two primary keys

### ISSUE THREAD

**Issue by Chrysweel** [sonata-project/SonataAdminBundle#2798]
I have three entities. Channel, IrcChannel and channelIrcChannel which has channel, ircChannel and order.

From my dashboard I can list and create channel and ircChannel without problems.
channelIrcChannel I can create a new entity but when I list ...

I get the following error:

>An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 18 near 'channel FROM': Error: Invalid PathExpression. Must be a StateFieldPathExpression.") in SonataAdminBundle:CRUD:base_list.html.twig at line 33.

The entity channelIrcChannel has:

```
class ChannelIrcChannel
{
	
    /**
	 * @ORM\Id
	 * @ORM\ManyToOne(targetEntity="...\ChannelBundle\Entity\Channel", inversedBy="channelIrcChannel")
	 * @ORM\JoinColumn(name="channel_id", referencedColumnName="id")
	 */
	private $channel;
	
	/**
	 * @ORM\Id
	 * @ORM\ManyToOne(targetEntity="...\ChannelBundle\Entity\IrcChannel", inversedBy="channelIrcChannel")
	 * @ORM\JoinColumn(name="irc_channel_id", referencedColumnName="id")
	 */
	private $ircChannel;
```
This entity has two primary keys.

The error I can solve with:

SELECT IDENTITY(c.parent) ...

>http://stackoverflow.com/questions/14216470/symfony2-and-doctrine-error-invalid-pathexpression-must-be-a-statefieldpathe

I have this composer. I include versions stable of sonataAdmin.. etc

```
"require" : {
		"symfony/symfony" : "2.3.*",
		"symfony/swiftmailer-bundle" : "2.3.*",
		"doctrine/orm" : ">=2.2.3,<2.4-dev",
		"symfony/assetic-bundle" : "2.3.*",
		"incenteev/composer-parameter-handler" : "~2.0",
		"jms/debugging-bundle" : "dev-master",
		"twig/extensions" : "1.0.*",
		"php" : ">=5.3.3",
		"sensio/generator-bundle" : "2.3.*",
		"cypresslab/less-elephant-bundle" : "dev-master",
		"gregwar/captcha-bundle" : "dev-master",
		"raulfraile/ladybug-bundle" : "v0.7",
		"symfony/monolog-bundle" : "2.3.*",
		"sensio/framework-extra-bundle" : "2.3.*",
		"whiteoctober/breadcrumbs-bundle" : "dev-master",
		"sensio/distribution-bundle" : "2.3.*",
		"doctrine/doctrine-bundle" : "1.2.*",
		"gregwar/captcha-bundle": "dev-master",
		"knplabs/knp-paginator-bundle": "dev-master",
		"presta/sitemap-bundle": "dev-master",
	  	"frequence-web/contact-bundle": "dev-master",
		"sonata-project/intl-bundle" : "~2.2",
		"sonata-project/media-bundle": "2.3.1",
	    "sonata-project/core-bundle": "~2.2",
		"sonata-project/cache-bundle" : "*@dev",
	    "sonata-project/admin-bundle" : "2.3.1",
	    "sonata-project/doctrine-orm-admin-bundle" : "~2.3.1",
	  	"sonata-project/easy-extends-bundle": "~2.1"
	},
```
Any idea how solve it in sonataAdmin ?
Somebody can help me ? 

Thanks in advance

**Comment by nlzet** [comment]
Correct me if I'm wrong but I believe composite keys are not (yet) supported by SonataAdmin.

Referring to the comments in #482

**Comment by Soullivaneuh** [comment]
This is now supported: https://github.com/sonata-project/SonataAdminBundle/pull/3873
