### ISSUE TITLE
fatal error after update

### ISSUE THREAD

**Issue by roozbeh360** [sonata-project/SonataAdminBundle#2801]
FatalErrorException: Compile Error: Declaration of Sonata\AdminBundle\Block\AdminListBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockServiceInterface::validateBlock(Sonata\AdminBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in 

sonata-project\admin-bundle\Block\AdminListBlockService.php line 105

after update i am getting this error !

**Comment by chiqui3d** [comment]
I have the same error.

Thanks

**Comment by rande** [comment]
Please review this: https://gist.github.com/rande/9c0cfbd751d3e64b893f
