### ISSUE TITLE
"Parameter "id" for route must match "[^/]++"

### ISSUE THREAD

**Issue by lethak** [sonata-project/SonataAdminBundle#2823]
when trying to access 

>https://domain.tld/admin/ltk/teamspeak/identity/list

I get

>An exception has been thrown during the rendering of a template ("Parameter "id" for route "admin_ltk_teamspeak_identity_edit" must match "[^/]++" ("1SCzaBOM0OK/Wyw3/5TYgvbO2oI=" given) to generate a corresponding URL.") in SonataDoctrineORMAdminBundle:CRUD:list_orm_many_to_one.html.twig at line 17.

>500 Internal Server Error - Twig_Error_Runtime
>1 linked Exception: InvalidParameterException

In my entity I have

```php
class Identity
{

	/**
	 * @var string
	 *
	 * @ORM\Column(name="uid", type="string", length=255)
     * @ORM\Id
	 */
	private $uid;
```

indeed teamspeak unique identity can have multiple "/" like this one
>1SCzaBOM0OK/Wyw3/5TYgvbO2oI=

when this is used as an id, SonataAdmin cannot generate edit/show/delete link.

**Comment by rande** [comment]
Having ``/`` in an id is not quite good. You can try to use the ``sonata.admin.route.query_string`` service for your admin by calling the ``setRouteBuilder`` in your service definition.

However, it will be better to have a proper ``id`` and keep ``uid`` value as unique field.
