### ISSUE TITLE
migrate ErrorElement

### ISSUE THREAD

**Issue by AntoineLemaire** [sonata-project/SonataAdminBundle#2824]
On branche 2.3, `AdminListBlockService` is using

```use Sonata\AdminBundle\Validator\ErrorElement;```
instead of
```use Sonata\CoreBundle\Validator\ErrorElement;```

https://github.com/sonata-project/SonataAdminBundle/blob/2.3/Block/AdminListBlockService.php

So composer update is failling with 

```
"sonata-project/admin-bundle": "2.3.*",
"sonata-project/block-bundle" : "2.3.*"
```

Output error : 
```
PHP Fatal error:  Declaration of Sonata\AdminBundle\Block\AdminListBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in /var/www/yoopies/vendor/sonata-project/admin-bundle/Block/AdminListBlockService.php on line 108
```

**Comment by rande** [comment]
@AntoineLemaire I am fixing the composer.json file.

In the mean time, you can use these settings in your composer.json file:

        "sonata-project/block-bundle": "~2.2,>=2.2.7,<2.3",
        "sonata-project/core-bundle": "~2.2,<2.3.1",

**Comment by AntoineLemaire** [comment]
Thanks, already done. I just wanted to warn ;)

**Comment by rande** [comment]
done: https://github.com/sonata-project/SonataAdminBundle/commit/ed1882b7cb79c1f406a37dc8556e98da5bee35c9
