### ISSUE TITLE
composer update error, v.2.3-dev

### ISSUE THREAD

**Issue by a-salihov** [sonata-project/SonataAdminBundle#2826]
I get an error during composer update with these dependencies:

    "sonata-project/doctrine-orm-admin-bundle": ">=2.2.4,<2.3-dev",
    "sonata-project/intl-bundle": ">=2.1,<2.3-dev",
    "sonata-project/notification-bundle": ">=2.2,<2.3-dev",
    "sonata-project/admin-bundle": ">=2.2,<2.3-dev",
    "sonata-project/media-bundle": ">=2.2.5,<2.3-dev",
    "sonata-project/user-bundle": ">=2.2.0,<2.3-dev",
    "sonata-project/formatter-bundle": ">=2.3.0",

Error:

PHP Fatal error:  Declaration of Sonata\AdminBundle\Block\AdminListBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in /home/salikhov/projects/campgite/vendor/sonata-project/admin-bundle/Block/AdminListBlockService.php on line 32

These versions worked correctly in the past few months. The error had appeared in the last few days.

**Comment by rande** [comment]
Please review: https://gist.github.com/rande/9c0cfbd751d3e64b893f
