### ISSUE TITLE
[Composer] Update to 2.3.2

### ISSUE THREAD

**Issue by Th3Mouk** [sonata-project/SonataAdminBundle#2827]
Hello @rande !

I've a question on the deployment of new releases.
The last release of SonataAdminBundle 2.3.2, blocks the version of block-bundle to ~2.2,
while ~2.3 is mandatory for update sonata-page from 2.3.8 to 2.3.9, with somes importants bug resolution like in composer templates and url generation.

SonataAdminBundle 2.3.2
```
sonata-project/block-bundle: ~2.2,>=2.2.7,<2.3
```

SonataPageBundle 2.3.9
```
sonata-project/block-bundle: ~2.3@dev,
```

Is this temporary while you continue the transition with sonata-core-bundle 2.3.1 ? Or an another problem i've missed ?

Thank for your help

**Comment by rande** [comment]
This is a mistake

**Comment by rande** [comment]
Looks like I did something wrong ....

**Comment by rande** [comment]
Ok, should be fixed, I update the 2.3.9 tag. Thanks for reporting this issue.

**Comment by Th3Mouk** [comment]
@rande thanks to you ! I help as I can :blush:

**Comment by Th3Mouk** [comment]
The problem seems persist but with the SonataCoreBundle this time

```
sonata-project/admin-bundle              2.3.2              Symfony SonataAdminBundle
sonata-project/block-bundle              2.2.13             Symfony SonataBlockBundle
sonata-project/cache                     1.0.4              Cache library
sonata-project/cache-bundle              2.2.0              This bundle provides caching services
sonata-project/core-bundle               2.3.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           dev-master dba166c Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 2.3.1              Symfony Sonata / Integrate Doctrine ORM into the Son...
sonata-project/easy-extends-bundle       2.1.9              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.3.4              Lightweight Exporter library
sonata-project/formatter-bundle          2.3.3              Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2              Library to integrate Google Authenticator into a PHP...
sonata-project/intl-bundle               2.2.1              Symfony SonataIntlBundle
sonata-project/media-bundle              2.3.1              Symfony SonataMediaBundle
sonata-project/notification-bundle       2.3.0              Symfony SonataNotificationBundle
sonata-project/page-bundle               2.3.9              Symfony SonataPageBundle
sonata-project/seo-bundle                1.1.10             Symfony SonataSeoBundle
```

You have requested a non-existent service "sonata.core.slugify.native".

This is normal because the slugify services come with the SonataCoreBundle 2.3.1.

I haven't find yet which bundle prevents <2.3.1

Good evening @rande

**Comment by 1ed** [comment]
@rande allowing "sonata-project/block-bundle": "~2.3" (https://github.com/sonata-project/SonataAdminBundle/commit/b891be443be15083423bff6e92b9b6c03e267ebe#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R36) actually breaks the admin, I think it should be reverted.

```
FatalErrorException in AdminListBlockService.php line 32:
Compile Error: Declaration of Sonata\AdminBundle\Block\AdminListBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block)

**Comment by Th3Mouk** [comment]
@1ed this is this block AdminListBlockService.php should be update due to the migration of ErrorMapper. The block bundle shouldn't be revert because the 2.3.9 sonata-page-bundle depends on it.

**Comment by Th3Mouk** [comment]
But the https://github.com/sonata-project/SonataCoreBundle/blob/2.3.1/Validator/ErrorElement.php appears only with the 2.3.1 SonataCoreBundle too.

**Comment by 1ed** [comment]
OK, but I thnik applying that commit on 2.2 would be a BC break, wouldn't it?

**Comment by Th3Mouk** [comment]
Yes the migration of ErrorMapper it's a BC breaks so all bundles where blocks required this Validator must be updated. It's this migration that posing problem between minor releases

**Comment by 1ed** [comment]
Ohh sorry, I overlooked something... actually my problem is not related to that commit. I'm sill using admin-bundle 2.2 and addig  "sonata-project/block-bundle": "2.2.*" to my composer.json fixed the problem. Should I create a pull request to adding "sonata-project/block-bundle": "<2.3" into the 2.2 branch or it is not maintained anymore?

**Comment by Th3Mouk** [comment]
I don't know sorry, i'm just a little contributor i'm not part of team only @rande seems could help up these days

**Comment by Th3Mouk** [comment]
Thanks @rande https://github.com/sonata-project/SonataAdminBundle/commit/3fbeb0037a4dd9792840e804147e1b2f3df2d778
