### ISSUE TITLE
Problem with knp-menu v2.0

### ISSUE THREAD

**Issue by SkyAgency** [sonata-project/SonataAdminBundle#2832]
Hi today I updated the project and I got message: - sonata-project/admin-bundle dev-master requires knplabs/knp-menu-bundle >=2.0,<3.0.0

I changed in composer.json to "knplabs/knp-menu-bundle": "2.0.x-dev" and updated but in knp-menu-bundle-2.0 doesn't works current active link (no add class="active" to li) in sidebar menu ( ul class="nav navbar-nav ...) with knp-menu-bundle 1.1 it works.

**Comment by nandorstanko** [comment]
Same problem here...

**Comment by acrozes** [comment]
+1

**Comment by Soullivaneuh** [comment]
Hi @SkyAgency,

Can you please update your sonata dependencies to latest versions and tell me if you still have this issue?

**Comment by rande** [comment]
@Soullivaneuh you can add the tags "wait for user reply"

**Comment by lucile-fievet** [comment]
I think it is steel there, some picto are missing and I cannot click in batch radio button  with :   
 sonata-project/admin-bundle              dev-master ad76edb 
 sonata-project/core-bundle               dev-master 710aba9 
 sonata-project/datagrid-bundle           dev-master f3be409 
 knplabs/knp-menu                         dev-master 03badd4 
 knplabs/knp-menu-bundle                  dev-master 7c0d579

**Comment by Soullivaneuh** [comment]
> some picto are missing and I cannot click in batch radio button

This are different problem (and the first one could be fixed by installing assets).

Is your original issue still here? If not, please close this one.

**Comment by lucile-fievet** [comment]
The assets have been plublished, I usually got then as symbolic links. But I am migrating an application with lot of adaptations, and the twig have been mofied, so I think my probleme is our old twig.

**Comment by Soullivaneuh** [comment]
I close this issue as no answer from author and not related another issues.
