### ISSUE TITLE
How to Customize the Templates of SonataAdminBundle

### ISSUE THREAD

**Issue by kadiyalasainath** [sonata-project/SonataAdminBundle#2841]
Hi, 
I have integrated the SonataAdminBundle into my Symfony application. Now, I would like to have my own Dashboard, Would like to know the process of customizing the default templates of the SonataAdminBundle. Looking for people who can help me. Thanks in advance for your help.

**Comment by amine26tz** [comment]
@kadiyalasainath you can find all answer in the documentation https://sonata-project.org/bundles/admin/master/doc/reference/dashboard.html :)

**Comment by kadiyalasainath** [comment]
@amine26tz Thanks a lot for the information you have shared. I am going through the documentation. I will post if I come across with any issues. Appreciate your help.

**Comment by kadiyalasainath** [comment]
Hi, Can anyone help me in designing custom admin dashboard using SonataAdminBundle ? Also would like to know in detailed about the blocks used in it. Thanks in advance for your help.

**Comment by pulzarraider** [comment]
To customize dashboard you can create your own blocks. Please look at the [documentation](https://sonata-project.org/bundles/admin/master/doc/reference/dashboard.html#adding-more-blocks) and the [existing blocks](https://github.com/sonata-project/SonataAdminBundle/tree/master/Block).
