### ISSUE TITLE
Add several items to a form by using admin_code

### ISSUE THREAD

**Issue by ThibautAlgrin** [sonata-project/SonataAdminBundle#2851]
Hello the guys,

Here is it would be nice if we could have a type who looks like the type `sonata_type_admin `or `sonata_type_model `but for the relations ManytoMany or OneToMany.

I give some explanation: let us take an example, I have two entities `User` and `Group`. There is naturally a connection ManyToMany between these two entities.
Also, I have naturally two Admin `UserAdmin `and `GroupAdmin '.

What would be nice, it is when we are on the edition or the creation of a user, during the attribution of a group, one pop-up which displays where we can see the list of the groups (using the method `configureListField `of the class `GroupAdmin ')
So, we would have the possibility of checking several checkbox and after the validation of a button, these would be added automatically to the form of said user.

What do you think about it?

**Comment by EmmanuelVella** [comment]
I think you are talking about [this](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/438) ?

**Comment by ThibautAlgrin** [comment]
Yes it ils exactly the dame idéal. Sorry for My question.

I close that
