### ISSUE TITLE
Enable adding child to tab menu with uri not related to admin class

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2853]
Normally I add a child to the tab menu by generating the admin related Url like this:

``` php
    protected function configureTabMenu(MenuItemInterface $menu, $action, AdminInterface $childAdmin = null)
    {
        if (!$childAdmin && !in_array($action, array('edit', 'show', 'list'))) {
            return;
        }

        if ($this->isGranted('SHOW')) {
            $menu->addChild('Show Contract', array('uri' => $admin->generateUrl('show', array('id' => $id))));
        }
    }
```

But when I try to add an uri that is not related to an admin but for instance a standalone Controller:

``` php
class BundleController extends Controller
{
    /**
     * @Route("/qis/contract/{contractId}/bundle/egz", name="qis_contract_bundle_egz")
     */
```

like this:

``` php
$menu->addChild('EGZ Report', array('uri' => $this->generateUrl('qis_contract_bundle_egz', array('contractId' => $id, 'pdf' => 1))));

/*
$admin = $this->isChild() ? $this->getParent() : $this;
$menu->addChild('EGZ Report', array('uri' => $admin->generateUrl('qis_contract_bundle_egz', array('contractId' => $id, 'pdf' => 1))));
*/
```

I get an exception:
*_An exception has been thrown during the rendering of a template ("unable to find the route `sonata.admin.contract.qis_contract_bundle_egz`") in SonataAdminBundle:CRUD:base_edit.html.twig at line 34. *_

The Url generator assumes there is an admin class and prefixes the `uri` with `sonata.admin.contract.`.

How can I change this behaviour?

Possibly related issue:
- https://github.com/sonata-project/SonataAdminBundle/issues/1641
- https://github.com/sonata-project/SonataAdminBundle/issues/2505
- https://github.com/sonata-project/SonataAdminBundle/issues/2394

**Comment by webdevilopers** [comment]
So far this is a possible workaround:
```php
            $container = $this->getConfigurationPool()->getContainer();
            $menu->addChild('EGZ Report', array('uri' => $container->get('router')->generate('qis_contract_bundle_egz', array('contractId' => $id, 'pdf' => 1))));
```

A good solution? Or better to inject the container?

**Comment by webdevilopers** [comment]
Same problem when coming from a template:
```twig
<a href="{{ admin.generateUrl('admin_appbundle_contract_timekeepingentry_list', { 'id': object.id }) }}"></a>
```
results in:
**An exception has been thrown during the rendering of a template ("unable to find the route `sonata.admin.contract.admin_appbundle_contract_timekeepingentry_list`")**

**Comment by aivus** [comment]
This issue was resolved after command `rm -rf app/cache/*`.
`app/console cache:clear` doesn't help me.

Also, @webdevilopers you should call addChild in service. Like
```
<service id="acme.admin.test"
                 class="Acme\AcmeBundle\Admin\TestAdmin">
            <tag name="sonata.admin"
                 manager_type="orm"
                 group="test"
                 label="Test"/>
            <argument />
            <argument>Acme\AcmeBundle\Entity\Test</argument>
            <argument />
            <call method="addChild">
                <argument type="service" id="survey.admin.another"/>
            </call>
</service>
```

**Comment by webdevilopers** [comment]
I think we are talking about different things, @aivus .

The `addChild` method is called on the `menu` not the admin class since I stated:
`I try to add an uri that is not related to an admin`.

It is a general problem with the added prefix to the url.

**Comment by damienalexandre** [comment]
:+1: 

It look likes we even can't just link to another admin if they are not parent/child:

```
An exception has been thrown during the rendering of a template ("unable to find the route `sonata.admin.gallery|sonata.admin.user.list`") in SonataAdminBundle:CRUD:base_edit.html.twig at line 34.
```

```php
            $menu->addChild(
                "Users",
                $admin->generateMenuUrl('sonata.admin.user.list', array('filter' => ['gallery' => ['value' => $id]]))
            );
```

Too bad this is not allowed :]

**Comment by lucile-fievet** [comment]
Maybe the routes of child admin are not generated ..?
http://stackoverflow.com/questions/28636229/child-admin-route-is-not-being-generated-sonata-admin-bundle

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome to if you reopen this issue.

**Comment by webdevilopers** [comment]
Sorry, but I'm no longer working on this project.
