### ISSUE TITLE
Multiple tab controls controls on a single page conflict each other 

### ISSUE THREAD

**Issue by blaues0cke** [sonata-project/SonataAdminBundle#2862]
When you have multiple tab controls on a single page/and or rendered by some inline-editing-list-forms all the tabs control each other. See: 

![img_251_-_1389x885 1](https://cloud.githubusercontent.com/assets/5159398/6867951/492eadfc-d487-11e4-92ac-f13ba237471e.png)

When I click on "Es" on the top all the fields (not the tabs) are also changed to their "es" page. I am using `sonata-project/admin-bundle": "2.4.*@dev"`, `"a2lix/translation-form-bundle": "2.*@dev"` and `"prezent/doctrine-translatable-bundle": "dev-master"` to generate this view.

This may also relate to https://github.com/sonata-project/SonataAdminBundle/issues/2715

**Comment by rande** [comment]
Seems to be related to ``a2lix/translation-form-bundle``.
