### ISSUE TITLE
Datepicker filter problem with doctrine_orm_callback and date_range

### ISSUE THREAD

**Issue by quiche** [sonata-project/SonataAdminBundle#2863]
After upgrade to 2.4, the date range filter with datepicker have a problem,
I use `doctrine_orm_callback` filter type like that:

    $datagridMapper
        ->add('dateReport', 'doctrine_orm_callback', array(
                'callback' => function($queryBuilder, $alias, $field, $value) {
                    if (empty($value['value'])) { return; }

                     $date = $value['value'];
                     $queryBuilder->andWhere($alias.'.dateReport BETWEEN :start AND :end');
                        $queryBuilder->setParameter('start', $date->start);
                        $queryBuilder->setParameter('end', $date->end);

                        return true;
                    },
                    'field_type' => 'date_range',
                    )
                );

sonata admin 2.3
![selection_263_274_018](https://cloud.githubusercontent.com/assets/193349/6868177/a01357a6-d489-11e4-95d8-68de691550e3.jpg)
I can choose day, month...
but after upgrade 2.4
![selection_276_321_017](https://cloud.githubusercontent.com/assets/193349/6867986/b9d3de1a-d487-11e4-83a9-5e76e8f7d115.jpg)
everything is disabled...

I fixed the problem by adding `field_options` conf

    $now  = new \DateTime();
    $datagridMapper
        ->add('dateReport', 'doctrine_orm_callback', array(
                'callback' => function($queryBuilder, $alias, $field, $value) {
                    if (empty($value['value'])) { return; }

                     $date = $value['value'];
                     $queryBuilder->andWhere($alias.'.dateReport BETWEEN :start AND :end');
                        $queryBuilder->setParameter('start', $date->start);
                        $queryBuilder->setParameter('end', $date->end);

                        return true;
                    },
                    'field_type' => 'date_range',
                    'field_options' => array(
                        'start_options' => array(
                            'years'           => range(2014, $now->format('Y')),
                            'dp_min_date'     => '12/1/2014',
                            'dp_max_date'     => $now->format('m/d/Y'),
                            'dp_default_date' => $now->format('m/d/Y'),
                            'dp_language'     => 'fr',
                            ),
                        'end_options' => array(
                            'years'           => range(2014, $now->format('Y')),
                            'dp_min_date'     => '12/1/2014',
                            'dp_max_date'     => $now->format('m/d/Y'),
                            'dp_default_date' => $now->format('m/d/Y'),
                            'dp_language'     => 'fr',
                            )
                        )
                    )
                );

**Comment by pulzarraider** [comment]
From where does the `date_range` field type come from? It's your overloaded form type?

**Comment by quiche** [comment]
Yes, `date_range` is a custom form type
the problem was with the date format overload in this form type,
but now, i changed and i use `sonata_type_date_range` field type with custom javascript datetimepicker. It works.

    $current = new \DateTime();

        $datagridMapper
            ->add('dateReport', 'doctrine_orm_date_range',  array(
                    'label' => 'Date',
                    'field_type' => 'sonata_type_date_range',
                    'field_options' => array(
                        'field_options_start' => array(
                            'years'  => range(2014, $current->format('Y')),
                            'format' => 'dd/MM/y',
                            'widget' => 'single_text',
                                'attr' => array(
                                    'class'             => 'datepicker_start',
                                )
                            ),
                        'field_options_end' => array(
                            'years'  => range(2014, $current->format('Y')),
                            'format' => 'dd/MM/y',
                            'widget' => 'single_text',
                                'attr' => array(
                                    'class'             => 'datepicker_end',
                                )
                            )
                        )
                    )
                )
        ;
