### ISSUE TITLE
Demo doesnt work

### ISSUE THREAD

**Issue by sebastianneubert** [sonata-project/SonataAdminBundle#2868]
http://demo.sonata-project.org/admin/dashboard isn't working

    Oops! An Error Occurred
    
    The server returned a "500 Internal Server Error".
    Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by oscariugo** [comment]
Clear all your cookies set by sonata-project.org. I believe the site resets itself every periodically and the cookies hashes become invalid. The site should add some code to handle this case though.
