### ISSUE TITLE
glyphicon for editable fields in list view no longer showing with blank value

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2881]
In an earlier version making a field `editable` would show a `glyphicon-edit`:
![bildschirmfoto vom 2015-04-01 10 38 28](https://cloud.githubusercontent.com/assets/3479626/6937306/f9d2f61e-d85a-11e4-9bca-4ed576ce162b.png)

In current `dev-master` it longer shows when the content of a field is empty which makes it impossible to edit a blank field - which was possible before.

Comparing old and new versions the `html` has not changed:
<span
class="x-editable editable editable-pre-wrapped editable-click editable-empty btn btn-sm btn-default" data-url="/qis/core/set-object-field-value?context=list&field=invoiceComment&objectId=5145&code=sonata.admin.contract"
data-pk="5145"
data-title="Invoice comment"
data-value=""
data-type="textarea">
<i class="glyphicon glyphicon-edit"></i>
</span>
</source>

It looks like in `dev-master` there are some new css e.g.:
```css
td.sonata-ba-list-field .editable-empty:not(.editable-open) {
    display: none;
}
```
that hide the `span` `html` above and disable it in my firebug too.

Commenting out the `display: none;` will show the glyphicon.

Is this a new expected behaviour - did I miss a new option `'allow_editable_blank' => false`?

**Comment by pulzarraider** [comment]
This icon is [displayed on `hover` effect](https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/public/css/styles.css#L336-L338). It's done this way since the [first implemntation](https://github.com/sonata-project/SonataAdminBundle/pull/1867/files#diff-82166add900f62398a221f90e2ddd9c8R406), so nothing is broken here. 

But I am not sure, how usable it is on the touch devices.

**Comment by webdevilopers** [comment]
Yes but as far as I remember there is no hover effect available when the "displayed" value is not there resp. empty

**Comment by pulzarraider** [comment]
I have tested it in FF 37, Chrome 42, IE 11 and in all tested browsers is the glyphicon correctly displayed on mouse hover effect even the content (the html for the glyphicon) is hidden by default.

Anyway I am :+1: to make it always visible to better support touch devices.

**Comment by webdevilopers** [comment]
Just tested my use case which now works again in current `dev-master`!
