### ISSUE TITLE
Tab menu in CRUD base_edit template looking for removed show route

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2882]
In my admin class I removed the `show` route:

```
class ParttypeGroupAdmin extends Admin
{
    protected function configureRoutes(RouteCollection $collection)
    {
        $collection
            ->remove('show')
            ->remove('export')
        ;
    }
}
```

When calling the `edit` action on this class I get:
**An exception has been thrown during the rendering of a template ("unable to find the route `sonata.admin.parttype_group.show`") in SonataAdminBundle:CRUD:base_edit.html.twig at line 34.**

The tab menu still seems to try to render the `show` route:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/base_edit.html.twig#L34

While the block action correctely handles non-existing routes:
- https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/base_edit.html.twig#L26-32
- https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Button/show_button.html.twig#L12

Possible realted issues:
- https://github.com/sonata-project/SonataAdminBundle/issues/1619
- https://github.com/sonata-project/SonataAdminBundle/pull/2750
- https://github.com/sonata-project/SonataAdminBundle/issues/2740

**Comment by jordisala1991** [comment]
I just tested this and it works. There are a lot of issues related ( you linked them ) and the code you linked is not there anymore, probably changed a few times.

Closing for now as this is not reproducible with latest sonata version. If you still having this issue, please provide more information and I will reopen.
