### ISSUE TITLE
Add callback to doctrine_orm_model_autocomplete filter to prevent extra joins

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2884]
My Entity structure looks like this:
Contract 1:n Items 1:1 Parttype 1:1 ParttypeGroup

Currently I have a filter that is looking for all Contracts with ParttypeGroup X and the `doctrine_orm_callback` solution works fine:
```php
        $datagridMapper
            ->add('parttypeGroup', 'doctrine_orm_callback', array(
                    'callback' => function($queryBuilder, $alias, $field, $value) {
                        if (!$value['value']) {
                            return;
                        }

                        $queryBuilder
                            ->andWhere('iptptg.id = :parttypeGroup')
                            ->setParameter('parttypeGroup', $value['value'])
                    ;
                    return true;
                },
            ))
```

Since I needed the JOIN tables on other filters too I added them to the `queryBuilder` on the `createQuery` method:
```php
    public function createQuery($context = 'list')
    {
        $query = parent::createQuery($context);

        $query->addSelect(
                'PARTIAL ' . $query->getRootAlias() . '.{id, updatedAt, number, problemDescription}',
                'PARTIAL i.{id}',
                'PARTIAL ipt.{id}',
                'PARTIAL iptptg.{id, name}'
            )
            ->leftJoin($query->getRootAlias() . '.items', 'i')
            ->leftJoin('i.parttype', 'ipt')
            ->leftJoin('ipt.parttypeGroup', 'iptptg')
        ;

        return $query;
    }
```

The query result would look something like this:
```sql
SELECT 
  c0_.id AS id0
  #...#
  LEFT JOIN contract_items c11_ ON c0_.id = c11_.contract_id 
  LEFT JOIN parttypes p12_ ON c11_.parttype_id = p12_.id 
  LEFT JOIN parttype_groups p13_ ON p12_.parttype_group_id = p13_.id ;
```

Though there are a lot(!) of rows for `items` the query is still ok.

But for now the filter only allows entering the `id` for the `parttypeGroup`. Of course the user wants to select a name instead. Since I have hundreds of parttypes I can not simply make it a select because pre-loading all options would take to long.

Instead I switch to the `doctrine_orm_model_autocomplete` which is based on the `sonata_type_model_autocomplete` which has been added by @pulzarraider recently:
- https://github.com/sonata-project/SonataAdminBundle/pull/2454
- https://github.com/sonata-project/SonataAdminBundle/pull/1764

My first problem now is that the `callback` is not called. Though the `doctrine_orm_model_autocomplete` is based on the `sonata_type_model_autocomplete` which does support it
https://sonata-project.org/bundles/admin/master/doc/reference/form_types.html#sonata-type-model-autocomplete
it does not seem to implement this feature yet:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Filter/ModelAutocompleteFilter.php#L106-115

It seems that it has to be implemented similar to this:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Filter/CallbackFilter.php#L31-35

But the missing `callback` is not the major problem since the following existing setup does indeed filter correctly:
```php
        $datagridMapper
            ->add('items.parttype.parttypeGroup', 'doctrine_orm_model_autocomplete', array(
                    ), null, array(
                    'property' => 'name',
            ))
```

The real problem is that contrary to my first `doctrine_orm_callback` example the `queryBuilder` is NOT RECOGNIZING that the desired JOINs have already been added to the query.

So it adds it once again:
```sql
SELECT 
  c0_.id AS id0
  #...#
  LEFT JOIN contract_items c11_ ON c0_.id = c11_.contract_id 
  LEFT JOIN parttypes p12_ ON c11_.parttype_id = p12_.id 
  LEFT JOIN parttype_groups p13_ ON p12_.parttype_group_id = p13_.id 
  LEFT JOIN contract_items c17_ ON c0_.id = c17_.contract_id 
  LEFT JOIN parttypes p18_ ON c17_.parttype_id = p18_.id 
  LEFT JOIN parttype_groups p19_ ON p18_.parttype_group_id = p19_.id 
;
```

This will make my query unperformant and unuseable.

Originally I thought the extra JOINs were created because of the naming of my filter.
My first examlpe simply was named `parttypeGroup` instead of `items.parttype.parttypeGroup`.
This made it shorter to add the filter parameters to the URL.
But even if I use the full path `items.parttype.parttypeGroup` on my first example I don't get any extra JOINs.
The callback recognizes that the JOINs already exist in the query (from the `createQuery` method).

I assume that the `association` method is actually adding the extra JOINs:
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Filter/ModelAutocompleteFilter.php#L98

If the extra JOINs could be removed my filter would even work without the callback.
But I guess the callback is still an interesting feature.

**Comment by pulzarraider** [comment]
I wil fix this issue this weekend. Thank you @webdevilopers

**Comment by pulzarraider** [comment]
I have created new PR sonata-project/SonataDoctrineORMAdminBundle#447 to fix the problem with unneeded `leftJoin`s. @webdevilopers can you please test it?

**Comment by webdevilopers** [comment]
:+1: Fixed!
