### ISSUE TITLE
Admin Form

### ISSUE THREAD

**Issue by Siddharth22** [sonata-project/SonataAdminBundle#2887]
Hi,

I want to add template in form Sonata Admin like this :- 

    $formMapper
                ->add('description','ckeditor',array('required' => true, 'attr' => array('style' => 'width:400px;')))
                ->add('media', 'sonata_type_model_list', array('required' => true), array(
                'link_parameters' => $link_parameters
            ))
                ->add('productMap','entity', array(
                                            'class' => 'ApplicationMediaBundle:Model',
                                            'query_builder' => function($er) {
                                            return $er->createQueryBuilder('mt')
									   ->Where('mt.status = 1 order by mt.updated desc')->setMaxResults(200);
					  },
                                                  'multiple'=>true,
                                                  'required'=>true,
                                                  'label'=>'Mapped Product',
                                                  'empty_value'=>"Select Product"))
                ->add('position', 'hidden')
            ;
         }

I know template is working in configureListFields function in admin but I want to use in configureFormFields fuction.

It is possible ? If yes then How ?

Thnaks!

**Comment by rande** [comment]
No it is not possible, you need to use the Symfony Form solution to define form's blocks.
