### ISSUE TITLE
Admin Sonata for Business Application

### ISSUE THREAD

**Issue by kzweb** [sonata-project/SonataAdminBundle#2893]
I'm using the Sonata for an ERP application, because I really like how it works. For this removed the frontend and the backend use only. I also made some changes in the main menu and ROLES.

My question is: Admin Sonata can be used for this? Or am I doing wrong and I must look for another solution?

Thanks You.

**Comment by rande** [comment]
Depends on your need of customisation. The AdminBundle is build to provide CRUD operations. You might also want to consider http://www.orocrm.com/oro-platform
