### ISSUE TITLE
Using one association in two or more filter fields

### ISSUE THREAD

**Issue by seydu** [sonata-project/SonataAdminBundle#2895]
I have an entity A (Player) that has a relation one-to-many with B (TrajectoryPoints). B has a relation many-to-one with C (Point).
I want to add two filter fields to let users select only players who have been between two points (entity C).
Obviously I cannot use the same name (B.A, meaning TrajectoryPoints.Point) two times. When I use some other name the field description ends up not being configured by the datagrid builder (using the guessers). Why? Because all this guessing relies on the field name.
So I had to do it manually. And I have many times this situation.

Is there a way the configure the field description that allows the datagrid builder to complete its configuration even if its name is not a valid property path ?

I was thinking of making the datagrid builder use something other than the field name to complete the configuration of the field description. This would kind of "break the hard link" between the field name and the configuration guessing.
I would create an attribute propertyName in a field description class that defaults to the name. But this value could be set (in my case I would set it to TrajectoryPoints.Point). 
The datagrid builder too will change so that it calls getPropertyName() instead of getName().

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.

Btw. some types allow setting a `field_name` option.
