### ISSUE TITLE
empty_data resp. empty_value support for sonata_type_model_autocomplete

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2901]
A known option for the `sonata_type_model_autocomplete` is `empty_data` but it is not yet supported.

It can be easily added to the `buildView` method:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Form/Type/ModelAutocompleteType.php

Not sure if there should be an `empty_data` by default - e.g. an empty string resp. no selected option.

It still has to be added to the template:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig

Looking at other form fields the option is called `empty_value` instead:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Form/form_admin_fields.html.twig#l149

Thoughts?

Related issues:
- https://github.com/sonata-project/SonataAdminBundle/pull/2898
- https://github.com/sonata-project/SonataAdminBundle/pull/1581/files
- https://github.com/sonata-project/SonataAdminBundle/issues/2360

**Comment by webdevilopers** [comment]
Another missing option is `link_parameters`. There are `url` and `route` as mentioned in the docs though:
https://sonata-project.org/bundles/admin/master/doc/reference/form_types.html#sonata-type-model-autocomplete

The class also offers `req_params`:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Form/Type/ModelAutocompleteType.php#l72

Can this be used to add `link_parameters`?

**Comment by core23** [comment]
Can you provide a PR for that @webdevilopers ?

**Comment by webdevilopers** [comment]
Sorry but I'm no longer working on the projects I used Sonata with.

**Comment by webdevilopers** [comment]
I explained to @core23 on Twitter that I no longer maintain the projects that use Sonata.
I will try to comment on the issues anyway. I will close them if nobody else suggested a PR or similar.
