### ISSUE TITLE
js calls throws a mixed content warning on firefox

### ISSUE THREAD

**Issue by matlow** [sonata-project/SonataAdminBundle#2903]
Our website is encrypted by https.
Since a few, loading this kind of url path : */core/append-form-field-element* 
throw a mixed content warning on firefox 
(see [https://developer.mozilla.org/fr/docs/S%C3%A9curit%C3%A9/MixedContent])
Do you know how to turn all js call to https ?

**Comment by nlzet** [comment]
Do you have an example of assets loaded, and where they are loaded?

If they are loaded with an URL of "/.." and your website is on a https:// URL they should load via https on the same server. The problem is probably an external asset or a wrong absolute URL to a non-https asset.

**Comment by matlow** [comment]
Thx nlezt for your comment.
Certificate on server was wrong;
After adding the good one, Firefox now load ajax via https and don't throw mix content error
