### ISSUE TITLE
Override createQuery with default sort

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#2905]
I want to override createQuery to add some special multiple order by statements:

``` php
public function createQuery($context = 'list')
{
    $query = parent::createQuery($context);

    if ($context === 'list') {
        $query->orderBy('o.state', 'ASC');
        $query->addOrderBy('o.priority', 'DESC');
        $query->addOrderBy('o.id', 'DESC');
    }

    return $query;
}
```

This works but breaks all sort option on the UI like this:

```
?filter%5B_sort_order%5D=DESC&filter%5B_sort_by%5D=id&filter%5B_page%5D=1&filter%5B_per_page%5D=32
```

So I tried to get the concerned filter with `$this->getFilterParameters();`. The results:

```
array (size=4)
  '_sort_order' => string 'DESC' (length=3)
  '_sort_by' => string 'id' (length=2)
  '_page' => string '1' (length=1)
  '_per_page' => string '32' (length=2)
```

This is cool. But I got **excatly the same** without any GET parameter on the URL.

So, I can't determine if user had manually set a sort option or not.

It could be very useful to have a method like `hasUserSortFilters` which will determine if user had set some extra sort filters.

What do you think?

Regards.

**Comment by amine26tz** [comment]
The default parameters are merged with the user parameters (from request) in https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Admin.php#L831. so you can access to your extra sort filters from $this->getFilterParameters();

**Comment by Soullivaneuh** [comment]
Yes @amine26tz it's exactly what I said.

I use `$this->getFilterParameters();` but it's return the same result if I try with `/list` without GET parameters:

```
array (size=4)
  '_sort_order' => string 'DESC' (length=3)
  '_sort_by' => string 'id' (length=2)
  '_page' => string '1' (length=1)
  '_per_page' => string '32' (length=2)
```

**Comment by amine26tz** [comment]
@Soullivaneuh you can override defaut sort by adding:
```
protected $datagridValues = array(
        '_page' => 1,            // display the first page (default = 1)
        '_sort_order' => 'DESC', // reverse order (default = 'ASC')
        '_sort_by' => 'updated'  // name of the ordered field
                                 // (default = the model's id field, if any)
    );
```

and for multiple sorting feature i'think that it's not implemented yet. check https://sonata-project.org/bundles/admin/master/doc/reference/action_list.html in ``` 7.4.1. CONFIGURE THE DEFAULT ORDERING IN THE LIST VIEW``` section. 

hope that i understand what you want to do ;)

**Comment by Soullivaneuh** [comment]
@amine26tz I'm sorry but no. Re-read my post. ;)

I know for the `datagridValues` options but works for only on field sort. I have a special sort system based on 3 field as you can see on the first code extract.

**Comment by ThibautAlgrin** [comment]
Hey,

If I understand well, you want add native order in list action, but you want reset this it when you have this url
`?filter%5B_sort_order%5D=DESC&filter%5B_sort_by%5D=id&filter%5B_page%5D=1&filter%5B_per_page%5D=32`

If it's correct, you can't do what. But you can have both. So you must add `addOrderBy` instead of `orderBy`. Like this.
```
public function createQuery($context = 'list')
{
    $query = parent::createQuery($context);

    if ($context === 'list') {
        $query->addOrderBy('o.state', 'ASC');
        $query->addOrderBy('o.priority', 'DESC');
        $query->addOrderBy('o.id', 'DESC');
    }

    return $query;
}
```

Indeed, the `orderBy` method reset it.

**Comment by Soullivaneuh** [comment]
@ThibautAlgrin Interested suggestion but using `addOrderBy` will keep the base order with high priority.

I need this:

 * User just arrived to the list page with no order selection => Use my custom order by query
 * User select on of the proposed orders (GET params) => Don't override the query, let's Sonata doing it itself.

**Comment by ThibautAlgrin** [comment]
You can do this:
```
public function createQuery($context = 'list')
    {
        $query = parent::createQuery($context);
        $requestQuery = $this->getRequest()->getQueryString();
        if ($requestQuery == NULL || strpos($requestQuery, 'sort_by') === false) {
            $query->orderBy('o.state', 'ASC');
            $query->addOrderBy('o.priority', 'DESC');
            $query->addOrderBy('o.id', 'DESC');
        }
        return $query;
    }
```
It's working, but I don't like that.

**Comment by Soullivaneuh** [comment]
@ThibautAlgrin Nice try but not fully functional. :-)

If you add some search filters without touch any of the order filter, the `sort_by` param is passed to the url and my custom orderBy query is not loaded.

And yes, I don't like that either.

I think we should really modify the behavior. Two possibilities with default page without selected orders:

 * Don't add `_sort_order` and `_sort_by` from filter parameters if none selected.
 * Add a `_default_order` boolean with `true` value if none selected.

**Comment by ThibautAlgrin** [comment]
Lol, sorry for that.

Personally, I prefer the second solution. Indeed, it's better and more sexy than the first.

**Comment by gallart** [comment]
UP !
