### ISSUE TITLE
Wrong event name?

### ISSUE THREAD

**Issue by norkunas** [sonata-project/SonataAdminBundle#2906]
https://github.com/sonata-project/SonataAdminBundle/blob/master/Event/PersistenceEvent.php#L35

**Comment by pulzarraider** [comment]
@norkunas can you please provide more informations about this issue?

**Comment by norkunas** [comment]
This was more as a question not that I faced some issue.

**Comment by norkunas** [comment]
Also as i can see it's now line 37 not 35

**Comment by pulzarraider** [comment]
It was a bug. Thank you @norkunas. It is fixed now.
