### ISSUE TITLE
allow custom stylesheets to be added easily via config.yml

### ISSUE THREAD

**Issue by michaelkonecny** [sonata-project/SonataAdminBundle#2914]
I didn't find a good way to include my own stylesheets in the admin bundle.

It would be very practical, if I could simplty add in config.yml something like:

    sonata_admin:
        custom_stylesheets:
            - MyBundle:Admin:admin.css

Reason: In this file I could add all the css I need, like the one to limit the size of image previews:

    img.admin-preview {
      max-height: 200px;
      max-width: 200px;
    }

**Comment by nlzet** [comment]
I think you are looking for https://github.com/sonata-project/sandbox/blob/2.3/app/config/assetic.yml#L108

**Comment by michaelkonecny** [comment]
Can you please explain? How would I use this to add my own css file?

**Comment by nlzet** [comment]
Is your project based on the sandbox setup ? After changing assets in assetic.yml you can run php app/console assetic:dump to generate new asset files with your configuration (combining the list of assets into single files).

**Comment by rande** [comment]
@michaelkonecny the path must be relative to your webserver. You cannot use template syntax to reference an asset.

@nizet The assetic file is only mandatory if you want to minify and concatenate your assets

**Comment by michaelkonecny** [comment]
@rande Of course. Sorry. I was too tired yesterday.

What I meant was, I would appreciate to have:

    sonata_admin:
        custom_stylesheets:
            - bundles/mydemo/css/admin.css
