### ISSUE TITLE
SonataAdminBundle use incorrect translation locale

### ISSUE THREAD

**Issue by zhil** [sonata-project/SonataAdminBundle#292]
For some reasons I cant force SonataAdminBundle to use my local
1. I have created bundle and placed file Resources/translations/SonataAdminBundle.ru.yml
2. I have set in config.yml    [code]translator:      { fallback: ru }[/code]

My locale loaded correctly - because messages which are missed in SonataAdminBundle locale (breadcrumbs, my custom messages) are translated correctly. 

But for all messages, which exists in Sonata locale files - 'en' translation used and I cant override it in my locale.
I supposed, maybe they have something like 
[code]$this->get('session')->setLocale('en_US');[/code]
and some kind of language selection in some settings page, but no function setLocale calls was founded in bundle.

Right now I dont have any ideas what can I do next, any suggestions are welcome :)

Topic is reposted here http://forum.symfony-project.org/viewtopic.php?f=23&t=37100

**Comment by riki137** [comment]
If anybody here wants to force locale, you can just do:
```yaml
defaults:
        _locale: en
```
in `project/config/routes/sonata_admin.yaml`
