### ISSUE TITLE
update dev-master break dependencies

### ISSUE THREAD

**Issue by rccc** [sonata-project/SonataAdminBundle#2924]
Hello,

I would like to use the sonata_type_model_autocomplete widget merged in 2.4

When i update my composer with "sonata-project/admin-bundle": "dev-master", i have these errors :

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for symfony/framework-standard-edition 2.5.x-dev -> satisfiable by symfony/framework-standard-edition[2.5.x-dev].
    - symfony/framework-standard-edition 2.5.x-dev requires sonata-project/block-bundle 2.2.*@dev -> satisfiable by sonata-project/block-bundle[2.2.x-dev, 2.2.0, 2.2.1, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.10].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.11].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.12].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.13].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.7].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.8].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.9].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.x-dev].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.x-dev].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.0].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.1].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.2].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.3].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.4].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.5].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.6].
    - sonata-project/admin-bundle dev-master requires sonata-project/block-bundle ~2.3 -> satisfiable by sonata-project/block-bundle[2.3.x-dev].
    - Installation request for sonata-project/admin-bundle dev-master -> satisfiable by sonata-project/admin-bundle[dev-master].

When the 2.4 will be available as stable package ?

Thanks

**Comment by Soullivaneuh** [comment]
@rccc can you put your `composer.json` file? Especially sonata-project packages extract.

**Comment by rccc** [comment]
Hello,

Thanks for response.

Here is a part of the composer.json i'm using : 

    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.5.*",
        "doctrine/orm": "2.4.*",
        "doctrine/doctrine-bundle": "1.2",
        "twig/extensions": "~1.2.0",
        ....

         "sonata-project/admin-bundle": "2.3",
        "sonata-project/block-bundle": "2.2.*@dev",
        "sonata-project/cache-bundle": "~2.2",
        "sonata-project/classification-bundle": "2.2.*@dev",
        "sonata-project/doctrine-orm-admin-bundle": "2.3",
        "sonata-project/datagrid-bundle": "2.2.*@dev",
        "sonata-project/easy-extends-bundle": "dev-master",
        "knplabs/knp-markdown-bundle": "~1.2.0", 
        "sonata-project/formatter-bundle": "~2.3",
        "sonata-project/intl-bundle": "~2.2",
        "sonata-project/media-bundle": "~2.3", 
        "sonata-project/seo-bundle": "1.1.1",
        "sonata-project/notification-bundle": "2.3.0",
    
       ...

**Comment by Soullivaneuh** [comment]
Can't see your `"sonata-project/admin-bundle": "dev-master"` on your `composer.json`.

BTW, if you want to upgrade on admin-bundle 2.4, you wish update dependencies too.

See: https://github.com/sonata-project/SonataAdminBundle/blob/master/composer.json#L36-L37

**Comment by rccc** [comment]
Hello,

I had to change from 'dev-master' to 2.3 to kep my project working, it's the reason why you see `"sonata-project/admin-bundle": "2.3"` rather than `"sonata-project/admin-bundle": "dev-master" `.

I tried to upgrade to 2.4 : `"sonata-project/admin-bundle": "2.4.x-dev"` and then i get these errors : 

```
  Problem 1
    - Installation request for symfony/framework-standard-edition 2.5.x-dev -> satisfiable by symfony/framework-standard-edition[2.5.x-dev].
    - symfony/framework-standard-edition 2.5.x-dev requires sonata-project/block-bundle 2.2.*@dev -> satisfiable by sonata-project/block-bundle[2.2.x-dev, 2.2.0, 2.2.1, 2.2.10, 2.2.11, 2.2.12, 2.2.13, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.10].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.11].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.12].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.13].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.7].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.8].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.9].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.x-dev].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.x-dev].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.0].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.1].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.2].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.3].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.4].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.5].
    - Can only install one of: sonata-project/block-bundle[2.3.x-dev, 2.2.6].
    - sonata-project/admin-bundle 2.4.x-dev requires sonata-project/block-bundle ~2.3 -> satisfiable by sonata-project/block-bundle[2.3.x-dev].
    - Installation request for sonata-project/admin-bundle 2.4.x-dev -> satisfiable by sonata-project/admin-bundle[2.4.x-dev].
```  

Cheers

**Comment by Soullivaneuh** [comment]
I explained why before:

> BTW, if you want to upgrade on admin-bundle 2.4, you wish update dependencies too.
>
> See: https://github.com/sonata-project/SonataAdminBundle/blob/master/composer.json#L36-L37

**Comment by rande** [comment]
If you want stable components, see the sandbox's composer.json file: https://github.com/sonata-project/sandbox/blob/2.3/composer.json

If you want unstable components, see https://github.com/sonata-project/sandbox/blob/2.4-develop/composer.json

**Comment by rccc** [comment]
@Soullivaneuh @rande : thanks a lot.
