### ISSUE TITLE
Use FormMapper without Admin Class

### ISSUE THREAD

**Issue by AlexL5** [sonata-project/SonataAdminBundle#2926]
Hello,

Is there any way to use FormMapper without Admin Class ?

I have an admin class with stantard CRUD and I would like tu create an new Admin action where user can upload a file.

If I use $form = $this->createFormBuilder() I've got an error : Impossible to access a key ("default") on a boolean variable ("") in SonataAdminBundle:CRUD:base_edit_form.html.twig at line 56

I don't understand.

Thanks.

**Comment by ThibautAlgrin** [comment]
Hey,

Can you give us more information like examples, code about you problem?

Thx

**Comment by rande** [comment]
No it is not possible. The point of the ``FormMapper`` is to link the ``Form`` with the ``Admin``
