### ISSUE TITLE
Dependency / version number bug

### ISSUE THREAD

**Issue by adamquaile** [sonata-project/SonataAdminBundle#2927]
Hi..

I'm trying to use the latest stable versions of a few sonata packages. So, I have page bundle at `~2.3` (`2.3.9` installed). `2.3.9` requires this repo, the admin bundle, at least `2.2.9` (https://github.com/sonata-project/SonataPageBundle/blob/2.3.9/composer.json#L21). 

Version `2.3` of the admin-bundle is being chosen (latest stable), but this requires the block bundle from `2.2.7` up-to (*not including*) `2.3`. https://github.com/sonata-project/SonataAdminBundle/blob/2.3.3/composer.json#L34

The page-bundle at `2.3.9` calls a `getBlockMetadata` method of `Sonata\BlockBundle\Block\BaseBlockService`, which was not introduced until version `2.3`. 

As far as I can tell, this makes the latest stable versions of the admin-bundle, page-bundle and block-bundle incompatible. 

The resolution would be to change the constraint of this repository to allow `2.3` of the block-bundle. This has been done in master by this commit https://github.com/sonata-project/SonataAdminBundle/commit/b891be443be15083423bff6e92b9b6c03e267ebe so afaik, creating a point-release `2.3.4` in the admin bundle from the current master should solve everything. 

Do you agree, or have I missed something? Thanks.

**Comment by adamquaile** [comment]
Having tried to work around this, it appears that there are further incompatibilities more than just version mismatches, so the latest tagged versions do not work together at all. I will revert back to the versions from the stable sandbox build.

**Comment by greg0ire** [comment]
We don't support 2 anymore so… closing, sorry.
