### ISSUE TITLE
bradcrumb not translated

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataAdminBundle#2938]
My Navigation:
![bildschirmfoto 2015-04-22 um 13 47 27](https://cloud.githubusercontent.com/assets/995707/7273655/3088aa9a-e8f6-11e4-9272-def955295e28.png)

My Breadcrumb:
![bildschirmfoto 2015-04-22 um 13 47 22](https://cloud.githubusercontent.com/assets/995707/7273659/380e222c-e8f6-11e4-8f63-eff313b15cab.png)

The Breadcrumb should be: ```Pressemitteilungen Liste``` instead of ```Press Release List```

**Comment by ThibautAlgrin** [comment]
Hello,

Which version do you have?
Do you clear the cache?

**Comment by OskarStark** [comment]
Yes, cleared the cache:

````
oskar.stark:/Volumes/development/workspaces/project $ composer show -i | grep admin-bundle
sonata-project/admin-bundle                2.3.3              Symfony SonataAdminBundle
sonata-project/doctrine-orm-admin-bundle   2.3.2              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/propel-admin-bundle         dev-master 9bc76cc Symfony Sonata / Integrate Propel into the SonataAdminBundle
````

**Comment by ThibautAlgrin** [comment]
Ok,
I have the same version.
What is the name of the file containing the translations?

**Comment by OskarStark** [comment]
I have to Translate it Manually?

**Comment by ThibautAlgrin** [comment]
Yes the catalog must be called absolutely "messages".
Clear the cache and check again.

**Comment by OskarStark** [comment]
then i will fix the logic, so that it will use the same name like in the navigation, i dont want to translte things twice

thx

**Comment by rande** [comment]
Correct, the catalogue is not defined in the ``buildBreadcrumb`` method https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Admin.php#L2135-L2138

**Comment by rande** [comment]
Not sure we can fix that unless we introduce an important BC.

**Comment by rande** [comment]
Actually, it is weird, the ``trans`` method will get the default admin translation domain.

https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Admin.php#L2207-L2216

**Comment by greg0ire** [comment]
Please reopen if this is still not fixed.

**Comment by seeeppp** [comment]
Hey @OskarStark how did you fix that? I'm still running into this issue (Version 3.13.0).
