### ISSUE TITLE
Templates dev-master are not updated

### ISSUE THREAD

**Issue by joshlopes** [sonata-project/SonataAdminBundle#2939]
For some reason the templates are not the last ones -- I removed the vendor folder and installed it again dev-master and the templates that i got are different from the demo one.

It appears to be using blank buttons, no fa-icons and no classes defined such btn-info btn-success etc.

Where can i grab the last twig templates or are they in a specific tag / Branch?

Example: http://grab.by/GEt2 should look like this http://grab.by/GEtg

Regards

**Comment by joshlopes** [comment]
Another thing that i think it may be related -- After adding a new Record i need to use Admin.setup_icheck(); otherwise my icheck options are all broken. I saw some references to this on the past but i think the problem is back on the newer versions

**Comment by pulzarraider** [comment]
If you want to use dev-master version of SonataAdmin, please make sure you use `SonataCoreBundle`, `SonataAdminBundle` and `SonataDoctrineORMAdmin` in dev-master version. Do not mix stable and unstable versions of bundles.

**Comment by joshlopes** [comment]
@pulzarraider as you can see i am importing all as dev-master

"sonata-project/admin-bundle": "dev-master",
"sonata-project/doctrine-mongodb-admin-bundle": "dev-master",
"sonata-project/formatter-bundle": "dev-master",
"sonata-project/datagrid-bundle": "dev-master",
"sonata-project/user-bundle": "dev-master",

**Comment by joshlopes** [comment]
@pulzarraider one thing just popped to my mind -- i am using mongodb and mongodb has its own templates  -- could it be the reason ? even 2.3 seems to be broken -- no icons being displayed.

**Comment by pulzarraider** [comment]
Yes, that`s probably the reason. The design of `SonataAdmin` was upgraded and in `SonataDoctrineMongoDBAdminBundle` are old templates. This issue should be open there. Probably only some CSS classes are missing.
