### ISSUE TITLE
http query with autocomplete type

### ISSUE THREAD

**Issue by pmithrandir** [sonata-project/SonataAdminBundle#2941]
Hello,

All my application works fine on http, but on https, the autocomplete field type is not working.
It's trying to access an url in http, leading to the following error : "mixed active content"

I tried to check where was done this check actually, to switch from http to https, but I didn't find it.

Any idea where it could be ?
Pierre Bonneau

**Comment by rande** [comment]
Please review https://github.com/sonata-project/SonataAdminBundle/issues/2497
