### ISSUE TITLE
Use locale settings for datepicker

### ISSUE THREAD

**Issue by Koc** [sonata-project/SonataAdminBundle#2948]
Looks like http://www.eyecon.ro/bootstrap-datepicker/ doesn't support l10n

**Comment by pulzarraider** [comment]
`sonata_type_datetime_picker` is using https://github.com/Eonasdan/bootstrap-datetimepicker. This datetime picker supports i18n with moment js and this is enabled by defualt in `master` branch.

**Comment by pulzarraider** [comment]
Seems that http://www.eyecon.ro/bootstrap-datepicker/  is used in x-editable js only. But the datetime fields are not yet supported by Sonata to be editable. 

So I am closing this issue.
