### ISSUE TITLE
Field type removed via PRE_SET_DATA FormEvent still exists inside TWIG template

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#2968]
In my admin class I remove a field when a `Subject` exists and it has a `Contract`:
https://gist.github.com/webdevilopers/c45a5c15d64125c21eca#file-timekeepingentryadmin-php
The field has been set before.

In my TWIG I check if the field type `is defined`. Only then I would add it to the template.
This way I get an **Key "absenceType" in object with ArrayAccess of class "Symfony\Component\Form\FormView" does not exist**.

When I debug and comment out the `absenceType` form field and dump the formgroups fields...
https://gist.github.com/webdevilopers/c45a5c15d64125c21eca#file-edit-html-twig

I get this:
![bildschirmfoto vom 2015-05-05 13 29 40](https://cloud.githubusercontent.com/assets/3479626/7472276/2c67ce60-f331-11e4-8057-cd5082e4bb3a.png)

Allthough the element was removed in the `PRE_SET_DATA` FormEvent it is still present.

Not sure if this is a general Symfony form issue or Sonata related.
Of course I could add the element on demand instead of removing it afterwars. But I need the FormEvent on other elements anyway to set `disabled` and `readonly` options.

- Is there a way to check if a field type exists other then looking up the key inside the `admin.formgroup'  array e.g. `admin.formgroups['Entry']['fields']['absenceType']`?
- Shouldn't the key `absenceType`have been removed from the array after calling the `remove` method inside the form event?

Possibly related:
- https://github.com/sonata-project/SonataAdminBundle/issues/2847
- https://github.com/symfony/symfony/pull/4552
- https://github.com/symfony/symfony/pull/7878

**Comment by webdevilopers** [comment]
I just figured out that I can use the `admin.form` to check if a field type is defined.

Instead of using the `formgroup` array:
```twig
{% if admin.formgroups['Entry']['fields']['absenceType'] is defined %}
```

do this:
```twig
{% if admin.form.absenceType is defined %}
```

As mentioned I still think not removing the `fields` key `absenceType` from the `formgroup` is an issue and can be a problem.

**Comment by pulzarraider** [comment]
Not sure if we can do something here. `form` is instance of `Form` from Symfony that doesn't know about the Sonata's groups. If you remove the form type in the event, the form array, that contains form informations gets unsynchronized. Maybe we can create some `PRE_SET_DATA` form event, that will be called after all other events and check if something was removed in previous events.

Or you can just remove the form type from the mapper (and the group) in the event manully:

```php
    $formMapper->getFormBuilder()->addEventListener(FormEvents::PRE_SET_DATA,
        function (FormEvent $event) use ($formMapper, $subject) {
        $form = $event->getForm();

        if ($subject->getContract() !== null) {
            $formMapper->remove('absenceType');
            $form->remove('absenceType');
        }
    });
```

**Comment by webdevilopers** [comment]
You are right, @pulzarraider . The field must be removed from the mapper itself to in order to make my first approach work.

Since nobody else seems to complan about this problem you should decide if such an event should be added.

At least I could add a chapter to the docs about "Working with events - removing fields" and provide your sollution.

**Comment by webdevilopers** [comment]
Please open a new PR if an event should be added or docs should be improved.

**Comment by pulzarraider** [comment]
Sorry for late anwser @webdevilopers. I am too busy now in my work atm. I prefer improving docs for now.
