### ISSUE TITLE
Admin crash (dev-master)

### ISSUE THREAD

**Issue by magedan** [sonata-project/SonataAdminBundle#2969]
Just updated my composer dependencies with the latest SonataAdminBundle changes and got following error on every admin page:

> Attempted to call method "isGranted" on class "Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage". 
> Stack Trace
>    in vendor/sonata-project/admin-bundle/Security/Handler/RoleSecurityHandler.php at line 64

```php
            try {
                return $this->tokenStorage->isGranted($this->superAdminRoles)
                    || $this->tokenStorage->isGranted($attributes, $object);
            } catch (AuthenticationCredentialsNotFoundException $e) {
                return false;
            }
```

That's expected exception since `$tokenStorage` is instance of `Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface` which doesn't have `isGranted()` method.

I use Symfony 2.6.6.

Please advice.

**Comment by rande** [comment]
@Soullivaneuh ;) it is for you.

**Comment by Soullivaneuh** [comment]
@rande Hmm I maybe made a mistake here. :-)

I'll take a look and, if possible, add test to reveal it.
