### ISSUE TITLE
[Bug 2.4.x] Validation error messages duplication if validation is specified in child admin

### ISSUE THREAD

**Issue by metamaker** [sonata-project/SonataAdminBundle#2971]
Validation error messages appear more than once in child admin if validation procedure is specified in **validate()** method of **child admin class**. If constraints/asserts are specified in **entity class** then everything works fine.

The bug is present in the next code: <https://github.com/metamaker/goblinov_net/tree/1f3a495fe0e247034dca0c4023e5bb82c0023758>

The schema is next: PortfolioItem ---- 1 .. N ----- < Image

Steps to reproduce the bug:
1. Go to PortfolioItem edit/create page.
2. Add two new Image entities with "Add row" button.
3. Select "bad" file (not an image) in one row and leave second row empty.
4. Click "Update" button.

![Bug screenshot](http://s017.radikal.ru/i438/1505/97/2a11ba6a1c60.png)

Files important for bug are:
- src/GoblinovWebsite/PortfolioBundle/Admin/ImageAdmin.php (bug appears when custom validator is assigned in Admin to check Image entities)
- src/GoblinovWebsite/PortfolioBundle/Admin/PortfolioItemAdmin.php (admin which contains ImageAdmin as child)
- src/GoblinovWebsite/PortfolioBundle/Entity/PortfolioItem.php (contains collection of images)
- src/GoblinovWebsite/PortfolioBundle/Entity/Image.php

![Everything just OK](http://s017.radikal.ru/i406/1505/19/f384cb1af579.png)

Code without bug: <https://github.com/metamaker/goblinov_net/tree/fca43b63640b6ee5044f9f9b27695a868277b173>

What I did to solve the problem in my case:
1. Removed **validate()** method from **Admin\ImageAdmin.php**.
2. Added **@Assert\Image()** in **Entity\Image.php** on field which I wanted to check.

**Comment by milokmet** [comment]
Facing the same issue. Anyway thanks for you proposal to use annotation validation in the Entity.

**Comment by OskarStark** [comment]
could you provide a PR with the Annotation @metamaker ?

**Comment by OskarStark** [comment]
or a fix :smile:

**Comment by core23** [comment]
We don't support this branch anymore. Please check this issue against the latest stable / master version.

Feel free to create a new issue following the issue template, if this error ist still present.
