### ISSUE TITLE
Don't show batch actions's checkboxes in sonata_type_model_list

### ISSUE THREAD

**Issue by Yonn-Trimoreau** [sonata-project/SonataAdminBundle#2979]
Hi,
I would like to hide batch actions's checkboxes in sonata_type_model_list, because there's no batch actions displayed, and you're not coming in the list for that purpose, only to select an object.. Is that an issue ?
Thank you in advance ;)

**Comment by rccc** [comment]
Hello,

I wonder if you can resolve your pb with this : http://stackoverflow.com/questions/28854170/sonata-admin-remove-the-batch-column-from-list-view.

++

**Comment by Yonn-Trimoreau** [comment]
I don't want to remove batch actions in global list, just in nested list !

**Comment by rccc** [comment]
Hello,

Have you tried with route configuration ? 

https://sonata-project.org/bundles/admin/master/doc/reference/routing.html#removing-a-route

**Comment by beono** [comment]
I think Yonn means the following issue:
When you add a field with "sonata_type_model_list" type it is displayed with checkboxes despite that there are no actions. This issue is not related to his project and should be solved in Sonata bundle

    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
             ->add('program', 'sonata_type_model_list') 
        ...
    }

**Comment by Yonn-Trimoreau** [comment]
+1

**Comment by yuriricci** [comment]
+1

**Comment by core23** [comment]
Are you talking about the edit page?

![bildschirmfoto 2016-08-13 um 08 10 08](https://cloud.githubusercontent.com/assets/3440437/17641752/656c8d84-612d-11e6-9d44-98bd6820e30f.PNG)

This checkbox isn't used for batch actions, but for deleting child entities.

**Comment by Yonn-Trimoreau** [comment]
A year later... As @yuriricci said, you'd better be 

> fixing/refactoring of existing components and the definition of proper documentation, instead of adding new functionalities.

Or even be taking a look at your issues on Github ;)

Now I uninstalled your bundle and made my own custom, sorry..

Still, Sonata is the best for a quick, fancy and "not presented to anyone except developers" administration solution

**Comment by greg0ire** [comment]
If you look closely you'll see that's pretty much what we are doing right now : trialing issues and PRs. We also have much higher standards regarding quality, testing and docs.
