### ISSUE TITLE
Update theme AdminLTE 2.1

### ISSUE THREAD

**Issue by hason** [sonata-project/SonataAdminBundle#2983]
Did you plan an upgrade? In AdminLTE 2.1 has been added right sidebar and light skin.

**Comment by AlexL5** [comment]
Maybe I'm wrong but, but AdminLTE will be available in 2.4

**Comment by hason** [comment]
@AlexL5 The 2.4 version contains AdminLTE 2.0.3.

**Comment by hason** [comment]
Fixed in #3142
