### ISSUE TITLE
Delete button in sonata_type_model

### ISSUE THREAD

**Issue by yuriricci** [sonata-project/SonataAdminBundle#2986]
From the documentation, it seems that a delete button is also available, in addition to the default add button, when dealing with sonata_type_model ( from doc. 'btn_add, btn_list, btn_delete and btn_catalogue:'). However passing as an option 'btn_delete'=>true has no effect.

Thinking about it, it makes sense to allow also delete and edit functionalities, together with contextual "on the fly" addition of the related -toOne entity. Otherwise it is necessary to build a separated, dedicated admin block, making the 'add' functionality quite useless.

N.B I'm working with last stable release of Sonata Admin 2.3.3

**Comment by rccc** [comment]
Hello,

it seems that this option is for label only : The labels on the add, list and delete buttons can be customized with these parameters. Setting any of them to false will hide the corresponding button. 

++

**Comment by yuriricci** [comment]
Thank you for your answer. Anyway, concerning sonata_type_model, if no buttons are available except for the add one (I recently saw on a earlier release documentation that only the add functionality is available, provided that nothing has changed in the meanwhile) such description is quite inconsistent

**Comment by rccc** [comment]
Can you confirm you have a delete button once you have added an element ?

**Comment by yuriricci** [comment]
Actually, there's no delete button at all, no matter what operation I do. There's only the choice field for the -toOne entity, as expected, and the -Add new- button. I suspect that only the add functionality is implemented for such a many-to-one use case.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.
