### ISSUE TITLE
Sonata Admin 2.4.x@dev (dev-master) broken style

### ISSUE THREAD

**Issue by koninka** [sonata-project/SonataAdminBundle#2989]
After I have upgraded from SonataAdmin 2.3 to SonataAdmin 2.4.x@dev the styles of buttons for `sonata_type_model_list` has been broken. There is no borders and you hover to the link everything blanks out.
Also styles for choice field doesn't work.
`sonata_type_model_list`:
![screenshot from 2015-05-14 21 49 49](https://cloud.githubusercontent.com/assets/3918095/7631284/ce5be4ea-fa7a-11e4-89ea-2bd232d87bdb.png)

`choice` field:
![screenshot from 2015-05-14 16 53 08](https://cloud.githubusercontent.com/assets/3918095/7631274/aec322b0-fa7a-11e4-8023-fe352ca87828.png)
How can I fix this?

**Comment by Soullivaneuh** [comment]
Hi @koninka.

Can you please update your sonata dependencies to latest version and tell me if you still have this issue?

**Comment by Soullivaneuh** [comment]
Closing as no answer. Feel free to reopen it if you still have this issue.

**Comment by edouardkombo** [comment]
Same error, after upgrading from SonataAdmin 2.3 to SonataAdmin 2.4.x@dev, NO STYLES on my admin dashboard.

I'm using sonata Core to dev master version also.

**Comment by Soullivaneuh** [comment]
@edouardkombo Can you please provides screenshots, sonata configs and results of `composer info -i | grep sonata`?

**Comment by OskarStark** [comment]
did you install the assets?

**Comment by efiorello** [comment]
i have the same error.

composer info -i | grep sonata

sonata-project/admin-bundle              dev-master ceffa13 Symfony SonataAdminBundle
sonata-project/block-bundle              2.3.9              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               2.3.10             Symfony SonataCoreBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 2.3.3              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10             Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.4.1              Lightweight Exporter library
sonata-project/google-authenticator      1.0.2              Library to integrate Google Authenticator into a PHP project
sonata-project/user-bundle               2.2.4              Symfony SonataUserBundle

`sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:
        sonata.user.block.account:
        sonata.block.service.text:
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_user:
    security_acl: true
    manager_type: orm

sonata_admin:
    templates:
        dashboard: SonataAdminBundle:Core:dashboard.html.twig`

**Comment by Soullivaneuh** [comment]
As 2.4 is now 3.0, this issue is not relevant anymore.
