### ISSUE TITLE
add method to retrieve validation metadata of a field

### ISSUE THREAD

**Issue by ghost** [sonata-project/SonataAdminBundle#2999]
I need the validation metadata of a field in the Admin:

``` PHP
$numberMetaData = $this
  ->getValidator()
  ->getMetadataFactory()
  ->getMetadataFor($this->getClass())
  ->getPropertyMetaData('number');
```

This could be made easier by adding two methods to the admin: getValidationMetaData() and getPropertyValidationMetaData($fieldName).

The former method could also be reused here:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Admin.php#L1364

**Comment by core23** [comment]
Can you provide a PR?

**Comment by jordisala1991** [comment]
Adding new methods to the admin is not a great idea, since the admin is pretty big.

Closing for now, if you want to provide an RFC on how we could add those methods (not on admin class) feel free to open a new issue
