### ISSUE TITLE
Status labels disappeared in User editing

### ISSUE THREAD

**Issue by maalicki** [sonata-project/SonataAdminBundle#3003]
I don't know exactly why but since today labels in 'Status' section just gone..

![screenshot-localhost 2015-05-26 11-47-22](https://cloud.githubusercontent.com/assets/193701/7811134/2b7ace4e-03a8-11e5-9eb3-e3d95089292a.png)

![screenshot-localhost 2015-05-26 11-44-11](https://cloud.githubusercontent.com/assets/193701/7811135/2b7b004e-03a8-11e5-8964-6ea390bf1dfe.png)

My configuration:
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "friendsofsymfony/user-bundle": "1.3.*@dev",
        "sonata-project/block-bundle": "2.3.*@dev",
        "sonata-project/easy-extends-bundle": "^2.1",
        "sonata-project/datagrid-bundle": "~2.2@dev",
        "sonata-project/admin-bundle": "~2.3@dev",
        "sonata-project/doctrine-orm-admin-bundle": "~2.3@dev",
        "stof/doctrine-extensions-bundle": "1.2.*@dev",
        "sonata-project/user-bundle": "~2.3@dev",
        "knplabs/doctrine-behaviors": "1.1.*@dev",
        "a2lix/translation-form-bundle": "2.*@dev"
    }

I have also asked at stackoverflow
http://stackoverflow.com/questions/30455185/

**Comment by tim96** [comment]
Hello @maalicki .
You override the default twig configuration:
``` 
form:
        resources: ['bootstrap_3_layout.html.twig']
#        resources: ['bootstrap_3_horizontal_layout.html.twig]
```
if you comment this line I think you label appear.
```
#form:
#        resources: ['bootstrap_3_layout.html.twig']
#        resources: ['bootstrap_3_horizontal_layout.html.twig]
```
I don't know what difference between templates but I think you can ask about it in twig or symfony repositories. I think it isn't a problem of sonata admin bundle.

**Comment by maalicki** [comment]
Yes, that was it! Thank you.
I've reported it to Symfony because it's their configuration ;-)

https://github.com/symfony/symfony/issues/14760

**Comment by Soullivaneuh** [comment]
Closing as this seems to not be a sonata issue.
