### ISSUE TITLE
Simple Pager + Mongo

### ISSUE THREAD

**Issue by joshlopes** [sonata-project/SonataAdminBundle#3004]
Simple pager seems not to work with Mongo

I'm getting the follow error:

```
Warning: array_slice() expects parameter 1 to be array, object given
```

https://github.com/sonata-project/SonataAdminBundle/blob/ad15a5beb8496ecc44cfee44cfb6183c11b1d023/Datagrid/SimplePager.php#L99

```
# SimplePager: Line 99
$this->results = new ArrayCollection(array_slice($this->results, 0, $this->getMaxPerPage()));           
```

$this->result instance of Doctrine\ODM\MongoDB\LoggableCursor
http://www.doctrine-project.org/api/mongodb_odm/1.0/class-Doctrine.ODM.MongoDB.Cursor.html

Ideas? :)

**Comment by joshlopes** [comment]
Right now you can't even use Simple Pager as Tag on mongo -- but i will do a PR that will fix that

**Comment by rande** [comment]
@joshlopes Not all features are implemented on all admin bundles. It depends on maintainers.

**Comment by joshlopes** [comment]
I guess it doenst make sense for mongo anyway -- my problem was sorting by ID ASC when my key was indexed DESC -- from 60 secs to 6 secs
