### ISSUE TITLE
The show action got blank and no field are shown

### ISSUE THREAD

**Issue by cithukyaw** [sonata-project/SonataAdminBundle#3008]
I'm integrating [Sonata Admin Bundle](https://sonata-project.org/bundles/admin/2-3/doc/index.html) into my Symfony 2.6 application by following [Symfony 2 jobeet tutorial](http://jobeet.symfony.gr.jp/en/day-12-sonata-admin-bundle.html). Everything is fine except [the Show action](https://sonata-project.org/bundles/admin/2-3/doc/reference/action_show.html). I have an entiry "Job" and so I have `src/Ibw/JobeetBundle/Admin/JobAdmin.php` which have a function `configurShowField(ShowMapper $showMapper)` like below

    <?php
    namespace Ibw\JobeetBundle\Admin;

    use Sonata\AdminBundle\Admin\Admin;
    use Sonata\AdminBundle\Datagrid\ListMapper;
    use Sonata\AdminBundle\Datagrid\DatagridMapper;
    use Sonata\AdminBundle\Validator\ErrorElement;
    use Sonata\AdminBundle\Form\FormMapper;
    use Sonata\AdminBundle\Show\ShowMapper;

    use Ibw\JobeetBundle\Entity\Job;

    class JobAdmin extends Admin
    {
        // ....

        protected function configureShowField(ShowMapper $showMapper)
        {
            $showMapper
                ->add('category')
                ->add('type')
                ->add('company')
                ->add('webPath', 'string', array('template' => 'IbwJobeetBundle:JobAdmin:list_image.html.twig'))
                ->add('url')
                ->add('position')
                ->add('location')
                ->add('description')
                ->add('how_to_apply')
                ->add('is_public')
                ->add('is_activated')
                ->add('token')
                ->add('email')
                ->add('expires_at')
            ;
        }

        // ....
    }

When I click the Show button and go to the view page (admin/ibw/jobeet/job/xxx/show), it shows none of the fields. The original template processed is `/vendor/sonata-project/admin-bundle/Resources/views/CRUD/base_show.html.twig`:

    {% extends base_template %}

    {% block actions %}
        <li>{% include 'SonataAdminBundle:Button:edit_button.html.twig' %}</li>
        <li>{% include 'SonataAdminBundle:Button:history_button.html.twig' %}</li>
        <li>{% include 'SonataAdminBundle:Button:list_button.html.twig' %}</li>
        <li>{% include 'SonataAdminBundle:Button:create_button.html.twig' %}</li>
    {% endblock %}

    {% block tab_menu %}{{ knp_menu_render(admin.sidemenu(action), {'currentClass' : 'active', 'template': admin_pool.getTemplate('tab_menu_template')}, 'twig') }}{% endblock %}

    {% block show %}
        <div class="sonata-ba-view">
            ***
            {{ sonata_block_render_event('sonata.admin.show.top', { 'admin': admin, 'object': object }) }}

            {% for name, view_group in admin.showgroups %}
                <table class="table table-bordered">
                    {% if name %}
                        <thead>
                            {% block show_title %}
                                <tr class="sonata-ba-view-title">
                                    <th colspan="2">
                                        {{ admin.trans(name) }}
                                    </th>
                                </tr>
                            {% endblock %}
                        </thead>
                    {% endif %}

                    <tbody>
                        {% for field_name in view_group.fields %}
                            {% block show_field %}
                                <tr class="sonata-ba-view-container">
                                    {% if elements[field_name] is defined %}
                                        {{ elements[field_name]|render_view_element(object) }}
                                    {% endif %}
                                </tr>
                            {% endblock %}
                        {% endfor %}
                    </tbody>
                </table>
            {% endfor %}

            {{ sonata_block_render_event('sonata.admin.show.bottom', { 'admin': admin, 'object': object }) }}

        </div>
    {% endblock %}

The inner content of `<div class="sonata-ba-view"></div>` is not shown except three asterisks I printed. Is there any configuration I'm missing?

**Comment by cithukyaw** [comment]
I traced in `configureShowField()`, but it seems not calling the method.

**Comment by ThibautAlgrin** [comment]
Hello,

It's not ``configureShowField()`` but ``configureShowFields()``: you are missing the 'S'.

**Comment by cithukyaw** [comment]
Oh, that's correct. Thank you. The jobeet tutorial is wrong.

**Comment by hieuit7** [comment]
i want to override block show in base_show.html.twig but, i can't. my config is the same above!!

**Comment by cithukyaw** [comment]
@hieuit7 I think you could create `\app\Resources\SonataAdminBundle\views\CRUD\base_show.html.twig`.

**Comment by hieuit7** [comment]
@cithukyaw i sorry, i sloved my problem! incorrect in my code!! setTemplate instead of setTemplates for array templates!!!
