### ISSUE TITLE
Cannot use multiple route parameters in the sonata_type_model_autocomplete form type

### ISSUE THREAD

**Issue by fancyweb** [sonata-project/SonataAdminBundle#3011]
I'm using the `sonata_type_model_autocomplete` form type (https://sonata-project.org/bundles/admin/master/doc/reference/form_types.html) and I use the `route`option. So I provide my custom route and the parameters of this route in the `route` option.

The problem is that the javascript widget does not escape the url (master : https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig#L45, 2.3 : https://github.com/sonata-project/SonataAdminBundle/blob/2.3/Resources/views/Form/form_admin_fields.html.twig#L284).

So if my route has several parameters (and it's the case), the url contains `&amp;` instead of `&` to separate the query parameters. If the url is filtered by the js escape filter (`|escape('js')`) or the raw filter (`|raw`), then it's working as expected. The fix seems easy.

**Comment by pulzarraider** [comment]
Can you please create a PR?

**Comment by pulzarraider** [comment]
Thank you for reporting the issue and your PR #3037
