### ISSUE TITLE
dashboard with 2 groups

### ISSUE THREAD

**Issue by titom59280** [sonata-project/SonataAdminBundle#3012]
Hello,

I have configured two different group in the dashboard, and I have in a page of my website two buttons one with "group 1" and the other "group 2".

What I need is when we click on a button we are redirecting on the sonata dashboard but only the correct group is displaying.

Does it possible to do so with sonata?

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
