### ISSUE TITLE
Custom form "submit" action

### ISSUE THREAD

**Issue by seydu** [sonata-project/SonataAdminBundle#3013]
I have an entity that is edited thru a wizard (3 steps). I have 3 actions. I added the necessary logic in the admin class to generate 3 different forms. 
To have the form sumitted to the right action I had to override two templates: SonataAdminBundle:CRUD:base_edit_form.html.twig and SonataAdminBundle:CRUD:base_edit.html.twig. 
Since the parts I wanted to change are not in Twig bocks, the templates I created are plain duplicates of those defined by the bundle (which is not good!)

If defining different forms to edit an entity (wizard) is not a wrong way of doing things in Sonata Admin, there should be an easy way of using a custom submit action for the edit forms.
Changing line 3 of template SonataAdminBundle:CRUD:base_edit_form.html.twig from 
{% set url = admin.id(object) is not null ? 'edit' : 'create' %}
 to 
{% set url = action_route|default(admin.id(object) is not null ? 'edit' : 'create') %} 
would be enough.

**Comment by pulzarraider** [comment]
The `action` value is in `master` (upcoming 2.4) defined inside block [`sonata_form_action_url`](https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/base_edit_form.html.twig#L14). You can overload this block in your custom template with your own target url.

**Comment by seydu** [comment]
Thanks. Closing
