### ISSUE TITLE
RouteCollection action removing

### ISSUE THREAD

**Issue by everio** [sonata-project/SonataAdminBundle#3014]
I have 2 admin entities : entity2 linked with parentAssociationMapping's attribute to entity1
```
protected $parentAssociationMapping = 'entity1';
```

So I have 2 routes to create entity2:
```
admin_app_entity2_create
admin_app_entity1_entity2_create
```

I want to remove only first route, but I try this :
```
protected function configureRoutes(RouteCollection $collection)
    {
        $collection->remove('create');
    }
```
all routes are removed.

Any solutions ?

**Comment by jvasseur** [comment]
You can do something like this:

```php
if (!$this->isChild()) {
    $collection->remove('create');
}
```

**Comment by everio** [comment]
So easy.... thanks !
