### ISSUE TITLE
Update ACL on programmatically created object with Sonata Admin

### ISSUE THREAD

**Issue by n3o77** [sonata-project/SonataAdminBundle#3023]
I'm using the Sonata-Admin bundle with ACL, but I have to create some objects programmatically. But I can't figure out how I properly update the ACL tables for the created entity. So I always have to execute

    php app/console sonata:admin:generate-object-acl

which is of course not a permanent solution.

I tried doing it like described here: http://symfony.com/doc/current/cookbook/security/acl.html#creating-an-acl-and-adding-an-ace so I implement the DomainObjectInterface in my entity and added the getObjectIdentifier method.

But now I'm getting an Symfony\Component\Security\Acl\Exception\AclAlreadyExistsException exception when executing:

    php app/console sonata:admin:generate-object-acl

So I guess that's not the proper way to do it when using sonata-admin. But I can't find anything in the docs.

( related SO: http://stackoverflow.com/questions/30488874/update-acl-on-programmatically-created-object-with-sonata-admin )

**Comment by n3o77** [comment]
I guess i found the solution by myself:

Ok, I took some time to debug a little more and I think I found a good solution:

Get the admin class of the object you want to create:



    $whateverAdmin = $this->get('app.admin.whatever');
    
    //create the object
    $whatever = new Whatever();
    $whatever->setName('test');

And now use the admin class to create the object:



    $whateverAdmin->create($whatever);

Or if you want to use the entityManager to persist you could just update the ACL with the admin class:



    $em->persist($whatever);
    $em->flush(); // important to flush first so an ID ist generated
    
    $whateverAdmin->createObjectSecurity($whatever);

**Comment by imajim** [comment]
hello,
thanks for this trick, but when the entity is removed, the ACL Table are not updated.
Example: I delete a project in my sonata project admin

**Comment by n3o77** [comment]
You can either use the `delete` method of the admin, or get the `securityHandler` and call `deleteObjectSecurity`. https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/AbstractAdmin.php#L679-L693

**Comment by imajim** [comment]
yop!
After some tests Sonata remove ACL entries in table ONLY if i delete entity (click action delete's button in the view Show, on backend admin sonata). But The ACL entries are not removed by BATCH actions.

**Comment by n3o77** [comment]
Ah, that's because for the batchAction it uses the modelManager and not the admin class. https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Model/ModelManager.php#L434-L458

Maybe you can create a PR in the [`DoctrineORMAdminBundle`](https://github.com/sonata-project/SonataDoctrineORMAdminBundle) which would fix that or open an issue there.
