### ISSUE TITLE
removing a field that doesn't exist

### ISSUE THREAD

**Issue by TeoGoddet** [sonata-project/SonataAdminBundle#3028]
when you try to remove a field that doesn't exist in an admin class, you got an error saying undefined index : translation_domain doesn't exist and i thing it a good idea to handle this type of error better.

**Comment by Soullivaneuh** [comment]
Can you explain a little bit more?

For example:

 * Steps to reproduce this error
 * Relevant code and config extracts
 * Screenshots if needed

**Comment by thebesttogt** [comment]
In configureFormType() (or any method like configurexxxType I think)
and then if you try to make $formMapper->remove('yyy') if the $formMapper->add('yyy) has never been executed then you will receive  undefined index : translation_domain doesn't exist
![image](https://cloud.githubusercontent.com/assets/9885447/8013329/a60095b8-0bc8-11e5-9db0-453147843894.png)
![image](https://cloud.githubusercontent.com/assets/9885447/8013338/c63cbff0-0bc8-11e5-9de9-54ce12a80422.png)

I think the error should be better handled

**Comment by Soullivaneuh** [comment]
Can you please paste your concerned admin class?

**Comment by thebesttogt** [comment]
<?php namespace StGenis\Bundle\UserBundle\Admin;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use StGenis\Bundle\UserBundle\Form\Type\SkieurFormType;
use StGenis\Bundle\UserBundle\Form\Type\AdresseFormType;
use Sonata\UserBundle\Admin\Model\UserAdmin as BaseAdmin;

class UserAdmin extends BaseAdmin
{

    protected $translationDomain = 'StGenisUserBundle';

    protected function configureFormFields(FormMapper $formMapper)
    {
		parent::configureFormFields($formMapper);
        $formMapper
            ->with('General', array('class' => 'col-md-6'))   
				/// here is the problem////
				->remove('somethingthathasnotbeenadded
				//////////////////////////
				')
				->add('email' , null, array('label' => 'form.email'), array('translation_domain' => 'FOSUserBundle'))
                ->add('prenom', null, array('label' => 'form.prenom'), array('translation_domain' => 'StGenisUserBundle'))
				->add('nom', null, array('label' => 'form.nom'), array('translation_domain' => 'StGenisUserBundle'))
				->add('password', null, array('label' => 'form.password'), array('translation_domain' => 'FOSUserBundle'))
            ->end()
			->with('form.adresse', array('translation_domain' => 'StGenisUserBundle', 'class' => 'col-md-6'))
				->add('adresse', 'sonata_type_admin', array('btn_add' => false, 'btn_delete' => false, 'label' => false))
			->end();
	}

**Comment by Soullivaneuh** [comment]
@thebesttogt can you please use code markdown tag to make it readable?

https://guides.github.com/features/mastering-markdown/

**Comment by thebesttogt** [comment]
'namespace StGenis\Bundle\UserBundle\Admin;

use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use StGenis\Bundle\UserBundle\Form\Type\SkieurFormType;
use StGenis\Bundle\UserBundle\Form\Type\AdresseFormType;
use Sonata\UserBundle\Admin\Model\UserAdmin as BaseAdmin;

class UserAdmin extends BaseAdmin
{

    protected function configureFormFields(FormMapper $formMapper)
    {
		parent::configureFormFields($formMapper);
        $formMapper
            ->with('General', array('class' => 'col-md-6'))   
				

                                 /// here is the problem////
				->remove('somethingthathasnotbeenadded')
				

                                 ->add('email' , null, array('label' => 'form.email'), array('translation_domain' => 'FOSUserBundle'))
                ->add('prenom', null, array('label' => 'form.prenom'), array('translation_domain' => 'StGenisUserBundle'))
				->add('nom', null, array('label' => 'form.nom'), array('translation_domain' => 'StGenisUserBundle'))
				->add('password', null, array('label' => 'form.password'), array('translation_domain' => 'FOSUserBundle'))
            ->end()
			->with('form.adresse', array('translation_domain' => 'StGenisUserBundle', 'class' => 'col-md-6'))
				->add('adresse', 'sonata_type_admin', array('btn_add' => false, 'btn_delete' => false, 'label' => false))
			->end();
	}'

**Comment by thebesttogt** [comment]
```php
namespace StGenis\Bundle\UserBundle\Admin;

use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Show\ShowMapper;
use StGenis\Bundle\UserBundle\Form\Type\SkieurFormType;
use StGenis\Bundle\UserBundle\Form\Type\AdresseFormType;
use Sonata\UserBundle\Admin\Model\UserAdmin as BaseAdmin;

class UserAdmin extends BaseAdmin
{

    protected function configureFormFields(FormMapper $formMapper)
    {
		parent::configureFormFields($formMapper);
        $formMapper
            ->with('General', array('class' => 'col-md-6'))   
				

                                 /// here is the problem////
				->remove('somethingthathasnotbeenadded')
				

                                 ->add('email' , null, array('label' => 'form.email'), array('translation_domain' => 'FOSUserBundle'))
                ->add('prenom', null, array('label' => 'form.prenom'), array('translation_domain' => 'StGenisUserBundle'))
				->add('nom', null, array('label' => 'form.nom'), array('translation_domain' => 'StGenisUserBundle'))
				->add('password', null, array('label' => 'form.password'), array('translation_domain' => 'FOSUserBundle'))
            ->end()
			->with('form.adresse', array('translation_domain' => 'StGenisUserBundle', 'class' => 'col-md-6'))
				->add('adresse', 'sonata_type_admin', array('btn_add' => false, 'btn_delete' => false, 'label' => false))
			->end();
	}
```
Sorry

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by jordisala1991** [comment]
The bug is real. Now happens because of other reasons, but it is still present.

**Comment by kunicmarko20** [comment]
This only happens if the remove is first because we have:

https://github.com/sonata-project/SonataAdminBundle/blob/5782acb292909110f16d514de2f8175122bcf572/src/Admin/AbstractAdmin.php#L1477-L1486

because fields are empty and it unsets the whole group. Do we need that if? not sure how can this be avoided with that `if`

**Comment by jordisala1991** [comment]
I think it happens before, because formGroups is initialized with false instead of empty array

**Comment by kunicmarko20** [comment]
when I comment out `unset($this->formGroups[$name]); ` everything works and when I dump that var I see initialised group

**Comment by kunicmarko20** [comment]
if it is the first field and there is no group, you are right it fails `Warning: Invalid argument supplied for foreach()` so we have 2 problems then :sweat_smile:

**Comment by jordisala1991** [comment]
Thats the initial error I saw, but if you try adding something first, another field, then you can safely remove anything

**Comment by kunicmarko20** [comment]
same here, only if remove is first, this is triggered:

```
             if (empty($this->formGroups[$name]['fields'])) { 
                 unset($this->formGroups[$name]); 
             }
```

because the group is empty

**Comment by jordisala1991** [comment]
And what happens when you unset the group? It breaks?

It should be normal to remove the group if it is empty right?

**Comment by kunicmarko20** [comment]
I get the first mentioned error: https://github.com/sonata-project/SonataAdminBundle/issues/3028#issuecomment-109411671

**Comment by jordisala1991** [comment]
Added here: https://github.com/sonata-project/SonataAdminBundle/pull/1864
