### ISSUE TITLE
Datepicker not working in French locale

### ISSUE THREAD

**Issue by florentdestremau** [sonata-project/SonataAdminBundle#3029]
Hello everyone,

I have a strange issue here: my website is using sonata-admin 2.3, and for the dates in my forms I am trying to use the datepicker:

    ->add('birthDate', 'sonata_type_date_picker')

Display is fine, but when I submit a date, i get a "This value is not valid" (in french..) for the date, while with the standard `date` widget everything works fine. I tried setting the locale at `en` instead of `fr` and everything went back to place, the datepicker worked just fine.

This is a pretty nasty bug for me as the `date``widget is not very user-friendly and my client asks for the datepicker...Any workaround or soon-to-come fix ?

**Comment by pulzarraider** [comment]
Which version of Symfony and SonataCoreBundle do you use? Can you please try the latest SonataCoreBundle and SonataAdminBundle if this bug occurs there, too?

**Comment by florentdestremau** [comment]
"symfony/symfony": "2.6.*",
    "sonata-project/admin-bundle": "~2.3",

**Comment by Soullivaneuh** [comment]
@florentdestremau Please try with "sonata-project/admin-bundle": "2.4.*@dev".

**Comment by florentdestremau** [comment]
@Soullivaneuh worked ! I guess it was fixed in the meanwhile. Thanks

**Comment by Soullivaneuh** [comment]
Glad to see that. :+1: 

@pulzarraider I think this issue can be closed.
