### ISSUE TITLE
Google fonts imported

### ISSUE THREAD

**Issue by samuel4x4** [sonata-project/SonataAdminBundle#3040]
Hello,

I just noticed in https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/public/vendor/admin-lte/dist/css/AdminLTE.css

you import some external google fonts

@import url(//fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,300italic,400italic,600italic);

@import url(//fonts.googleapis.com/css?family=Kaushan+Script);

Some Symfony applications we create are not designed to have any internet access, so we're geting some issues here.

Don't you think is better to put the sources of those 2 fonts in two distinct .css files, inside the Sonata Admin Bundle project, use them from there and not trying to make internet requests?

Something else, when do you think we'll have a stable 2.4 version?

Thanks a lot for your great job ;)

**Comment by Soullivaneuh** [comment]
Hello @samuel4x4 

I think it's an issue for https://github.com/almasaeed2010/AdminLTE since it's a vendor css.

Maybe make a proposition to separate `@import` from main css file in order to make ours rules inside Sonata.

Regards.

**Comment by samuel4x4** [comment]
https://github.com/almasaeed2010/AdminLTE/issues/498

thanks

**Comment by jordisala1991** [comment]
This belongs to AdminLTE . Closing
