### ISSUE TITLE
Missing icons in the left navbar

### ISSUE THREAD

**Issue by vihuvac** [sonata-project/SonataAdminBundle#3045]
Missing icons in the left navbar after upgrading the sonata admin bundle!

```json
...
"sonata-project/admin-bundle":  "~2.4",
...
```

![Sonata Admin Left Navbar](http://f.cl.ly/items/2L3e0R0R102Y2r3c373t/missing_icons_in_the_left_navbar.png "Sonata Admin Left Navbar")

**Comment by Soullivaneuh** [comment]
Possibly related to #3015.

@vihuvac Which version did you have before upgrading?

**Comment by vihuvac** [comment]
@Soullivaneuh yeah, this is the problem:

```twig
...
{% set icon = item.attribute('icon')|default ? item.attribute('icon') : '' %}
{{ icon|default|raw }}
...
```
I just left a comment in the pull request!

That two lines were removed.

**Comment by Soullivaneuh** [comment]
@vihuvac Which version (commit-id) did you have before upgrading?

**Comment by Soullivaneuh** [comment]
#3015 merged.
