### ISSUE TITLE
Usind admin bundle without the /admin route prefix, causes redirect issues

### ISSUE THREAD

**Issue by Brainshack** [sonata-project/SonataAdminBundle#3049]
Hello,

I want to use the admin without the /admin route prefix. I included the routeing configuration in my routing.yml:

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix:
_sonata_admin:
    resource: .
    type: sonata_admin

I am using fosuserbundle to manage my users and login. Redirecting to the login itself works. However, once I logged in and get redirected towards the dashboard, the url is messed up like this: admin.dev/app_dev.php//dashboard . This leads to an exception:

 NotFoundHttpException: No route found for "GET //dashboard" (from "http://sf2admin.dev/app_dev.php/login"). The same problem appears, when I log out, it will redirect me to admin.dev/app_dev.php//login after the logout.

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
