### ISSUE TITLE
Hi I found some deprecated calls?

### ISSUE THREAD

**Issue by milosmoto** [sonata-project/SonataAdminBundle#3050]
DEPRECATED - The "pattern" option in file "...../vendor/sonata-project/admin-bundle/Resources/config/routing/sonata_admin.xml" is deprecated since version 2.2 and will be removed in 3.0. Use the "path" option in the route definition instead.

I am working with symfony 2.7.0 version

Thanks

**Comment by Soullivaneuh** [comment]
Was already fixed on #2745.

Please upgrade to sonata/admin-bundle `^2.4`.

**Comment by milosmoto** [comment]
Hi,


I try with this one but it has problem:

"sonata-project/admin-bundle": "^2.4",
"sonata-project/doctrine-orm-admin-bundle": "^2.3",


Here is composer problem
Problem 1
    - The requested package sonata-project/admin-bundle could not be found in any version, there may be a typo in the package name.

**Comment by Soullivaneuh** [comment]
It's because your composer does not allow stable dependencies.

You can enable it by adding these two lines on your config:

```json
"minimum-stability": "dev",
"prefer-stable": true,
```

And please, use the code special tag for your code pasting: https://guides.github.com/features/mastering-markdown/

**Comment by milosmoto** [comment]
You are right , tnx
