### ISSUE TITLE
XSS vulnerability 

### ISSUE THREAD

**Issue by adrcal** [sonata-project/SonataAdminBundle#3051]
I have found that the flash messages displayed on the edit form are vulnerable to XSS attack. 

If i create an article let's say, and i set the title to a js snippet, when i click submit, the flash message "flash_edit_success" which contains the title of the article is executed in render.html.twig on:
```
    {% for message in sonata_flashmessages_get(type, domain) %}
        <div class="alert alert-{{ type|sonata_status_class }}">
            {{ message|raw }}
        </div>
    {% endfor %}
```

**Comment by Soullivaneuh** [comment]
@adrcal Thanks for your contribution.

Could you provide a PR with a revealing test case and a fix?

**Comment by rande** [comment]
@adrcal I cannot reproduce the issue, see:

![screen shot 2015-06-12 at 10 40 36](https://cloud.githubusercontent.com/assets/14672/8126523/824bedd0-10ef-11e5-85f6-16387b149d49.PNG)

**Comment by adrcal** [comment]
@rande is the render.html.twig file different? in my tests there is where the code is being executed because the |raw filter is added. 

We are using version "2.2.11" of admin-bundle.

**Comment by rande** [comment]
There is also a ``|raw`` in my file.

**Comment by adrcal** [comment]
I have tried it on another project and the issue persists.

![xss](https://cloud.githubusercontent.com/assets/12035044/8127137/2e6e27ec-10fd-11e5-8b2d-040f8cffff4e.png)

**Comment by rande** [comment]
@adrcal can you print all the sonata's bundles version: ``composer licenses | grep sonata``

Thanks

**Comment by rande** [comment]
Ok found, the 2.2 release does not call the ``escapeHtml`` method : https://github.com/sonata-project/SonataAdminBundle/blob/2.2/Controller/CRUDController.php#L247

as used here https://github.com/sonata-project/SonataAdminBundle/blob/2.3/Controller/CRUDController.php#L292

**Comment by rande** [comment]
Here the patch https://github.com/sonata-project/SonataAdminBundle/commit/e5bd3b55c6e9407f80919efd22c91eed0277efe2 from @pulzarraider for the 2.3 and up release.

**Comment by Soullivaneuh** [comment]
@rande as a security issue, this patch should be cherry-picket on 2.2 with a new patch release, isn't it?

**Comment by Soullivaneuh** [comment]
https://github.com/sonata-project/SonataAdminBundle/commit/e5bd3b55c6e9407f80919efd22c91eed0277efe2#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR5

Why is this BC break?

**Comment by rande** [comment]
@Soullivaneuh yes working on it, but the AdminBundle 2.2 is not maintained anymore, and there is some issue with composer packages ...

**Comment by rande** [comment]
@adrcal can you try this patch https://github.com/sonata-project/SonataAdminBundle/commit/5cddf62d05a55b4cfa716d2a45d6ace683a47f14 (ie, update your composer.json file)

**Comment by adrcal** [comment]
how can i apply the patch via the composer.json file ?

**Comment by rande** [comment]
@adrcal open the composer.lock file, search the admin-bundle entry and use the full sha1 5cddf62d05a55b4cfa716d2a45d6ace683a47f14

**Comment by adrcal** [comment]
a, through the composer.lock yes. it's ok, the initial issue is fixed, the js code is not executed anymore.

on the other hand assets from /bundles/sonatajquery/ are not loaded anymore, but i am not sure this is a consequence of the patch.

**Comment by Soullivaneuh** [comment]
@rande What is the ETA of this issue? Is the bug also present on 3.x?

**Comment by greg0ire** [comment]
Not since e5bd3b55c6e9407f80919efd22c91eed0277efe2 I guess. Closing
