### ISSUE TITLE
sonata_collection formType throws "Cannot use object of type _class_ as Array" inside ResizeFormListener.php

### ISSUE THREAD

**Issue by lemorragia** [sonata-project/SonataAdminBundle#3057]
Hi there, i think there's an issue with one recent update. 
I'm actually working on a project with many admin pages, and after an update on friday (june, 12,2015), none of them appears to be working anymore.
Apparently the issue is within the sonata_collection formtype

here's one example:

```php
->add('panellobozza', 'sonata_type_collection', array('by_reference' => false), array(
                'edit' => 'inline',
                'inline' => 'table',
            ))

and the relative model:
public function __construct()
{
  $this->pannellobozza = new \Doctrine\Common\Collections\ArrayCollection();
}

public function setPanellobozza(ArrayCollection $path)
{
  $this->pannellobozza = new ArrayCollection();
  foreach ($pannellobozza as $p) {
    $this->addPannellobozza($p);
  }
}
```

The admin is displayed correctly, but when i'm trying to create a new one(or update an existing one) the admin throws an error:

```
Fatal error: Cannot use object of type AppBundle\Entity\PannelloBozza as array in /projectRoot/vendor/sonata-project/core-bundle/Form/EventListener/ResizeFormListener.php on line 166

and the relative line in ResizeFormListener is:
if (isset($value['_delete'])) { <-this one 
  $this->removed[] = $name;
}
```

at first i thought that i made a mistake while coding, but i proceeded to test the other admin pages, where sonata_collection was used, and none of them is working anymore.

Is this a bug or am I missing something? Thanks

ps: while i'm writing, i checked out the commit c147462a39d9b38e3eab02cf2377a3325adeae8d inside sonata/core-bundle and it's working again. The behaviour appears to have emerged friday.

**Comment by wadjeroudi** [comment]
Same probleme here.
https://github.com/sonata-project/SonataCoreBundle/pull/165

**Comment by lemorragia** [comment]
Yes..that one...so in the end is a core-related issue :+1: i'm closing this one! :-)
