### ISSUE TITLE
Restrict defaults method for auto-generated routing

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#3062]
Will be feasible when #3061 will be merged.

Lot of routes should not accept `ANY` methods. We could make some defaults like this (`UserAdmin`):

| Route | Methods |
| --- | --- |
| admin_user_list | `GET` |
| admin_user_create | `GET|POST` |
| admin_user_batch | `GET` |
| admin_user_edit | `GET|POST` |
| admin_user_delete | `POST|DELETE` |
| admin_user_show | `GET` |
| admin_user_export | `GET` |

**Comment by VincentLanglet** [comment]
Closing due to lack of interest
