### ISSUE TITLE
Profile User Dropdown - Style

### ISSUE THREAD

**Issue by MM-Psiiirus** [sonata-project/SonataAdminBundle#3063]
Hiya,
i was wondering why my User-Profile-Dropdown looks different to the one in the soanta-admin demo?
Do i have to set a specific config parameter or something else like that?

My-Admin 2.4
![bildschirmfoto 2015-06-18 um 14 44 40](https://cloud.githubusercontent.com/assets/593363/8231436/e4a7df38-15c8-11e5-9cf6-dcb380fbff3d.png)

Demo-Admin 2.4 
![bildschirmfoto 2015-06-18 um 14 45 11](https://cloud.githubusercontent.com/assets/593363/8231445/f0468f9c-15c8-11e5-9bc4-140a02f58a8a.png)

```
"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3",
        "sonata-project/user-bundle": "2.2.x-dev",
        "sonata-project/admin-bundle": "dev-master",
        "genemu/form-bundle": "dev-master"
```

**Comment by Soullivaneuh** [comment]
Looks like some missing CSS files.

Do you overwrite `stdandard_layout.html.twig`?

**Comment by MM-Psiiirus** [comment]
No, i don't. :-/

**Comment by Soullivaneuh** [comment]
Maybe sonata-user version issue.

If yes, requirements should be changed (ping @rande)

@MM-Psiiirus Could you try with `"sonata-project/user-bundle": "2.3.x-dev"`

**Comment by MM-Psiiirus** [comment]
I tried this before and run into this issue

```
  Problem 1
    - Installation request for sonata-project/user-bundle 2.3.x-dev -> satisfiable by sonata-project/user-bundle[2.3.x-dev].
    - sonata-project/user-bundle 2.3.x-dev requires sonata-project/datagrid-bundle ~2.2 -> no matching package found.
```

**Comment by Soullivaneuh** [comment]
Hmm dunno for the moment.

Maybe @rande could give us an idea about it.

**Comment by MM-Psiiirus** [comment]
kk, cheers

**Comment by core23** [comment]
This issue should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue
