### ISSUE TITLE
how to different set of fields in collection and edit view

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataAdminBundle#3075]
class FooAdmin

Fields in configureFormFields:
- id
- name
- date

in class BarAdmin, FooAdmin is used as `sonata_type_collection`

but i only need name in this context, do have an example?

thanks

oskar

**Comment by Soullivaneuh** [comment]
You need to make a FooAdminClass with the correct `configureFormFields` inside I think.

**Comment by OskarStark** [comment]
Yes that is correct, but the ```FooAdmin``` itself need all the fields in the configureFormFields

```FooAdmin``` is on Top of ```FooEntity```

i tried now to add a second Admin, lets say: ```FooShortAdmin```, which contains only the name field in the configureFields()

```FooAdmin``` is responsible for the same ```FooEnitity```
```FooShortAdmin``` extends ```FooAdmin```

in ```BarAdmin``` i used this code:
```php
                ->add('foo', 'sonata_type_collection', array(
                    'by_reference'       => false,
                    'cascade_validation' => true
                ), array(
                    'edit' => 'inline',
                    'inline' => 'table',
                    'admin_code' => 'app.admin.foo.short'
                ))
```

but i get this error:
```
An exception has been thrown during the rendering of a template ("Unable to find a valid admin for the class: AppBundle\Entity\FooEntity, there are too many registered: app.admin.foo,app.admin.foo.short") in SonataAdminBundle:Button:show_button.html.twig at line 12.
```

When i try to create a new ```BarAdmin``` and add a collection entry, it uses the correct admin (with less fields). Click save:
![bildschirmfoto 2015-06-25 um 15 39 00](https://cloud.githubusercontent.com/assets/995707/8355596/70ae7e2e-1b50-11e5-84fa-450fce334edc.png)

**Comment by OskarStark** [comment]
no this isn't working

baseRouteName and pattern set, call setTemplate for the ShortAdmin and remove actions block in base_edit.html, but this seems not be working... :(

**Comment by epci** [comment]
In your FooAdmin configureFormFields method, you can add :

```
// field for All admin 
if ($this->getRoot()->getClass() == 'AppBundle\Entity\Bar') {
   // only field for BarAdmin
}

**Comment by OskarStark** [comment]
PERFECT!

Thank you very much @epci

**Comment by OskarStark** [comment]
@epci 

now i want to have a button in the form view to go directly to the AllAdmin in the list.
a screenshot for example:
![screen](https://cloud.githubusercontent.com/assets/995707/8568759/e6273914-2570-11e5-870d-0dc40efb3dad.jpg)

**Comment by davidromani** [comment]
@OskarStark did you achieve it? It is possible to add a custom column?

**Comment by OskarStark** [comment]
is use something like this:

this one is used as collection:
```php
    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        if ($this->getRoot()->getClass() == 'ProfileBundle\Entity\Profile') {
            $this->configureProfileFormFields($formMapper);
        } else {
            $this->configureDefaultFormFields($formMapper);
        }
    }

    /**
     * @param FormMapper $formMapper
     */
    protected function configureProfileFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('mapping')
        ;
    }


    /**
     * @param FormMapper $formMapper
     */
    protected function configureDefaultFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('mapping')
            ->add('profile', 'sonata_type_model_list')
        ;
    }
```

here:
```php
/**
 * @param FormMapper $formMapper
 */
protected function configureFormFields(FormMapper $formMapper)
{
    $formMapper
        // ...
        ->add(
            'teleplanMappings',
            'sonata_type_collection',
            array(
                'label' => false,
                'cascade_validation' => true,
                'required' => false,
            ),
            array(
                'edit' => 'inline',
                'inline' => 'table',
            )
        )
    ;
}
```


hope this helps

**Comment by davidromani** [comment]
More or less... I'm looking for something more customized like this:

<img width="1038" alt="captura de pantalla 2015-12-04 a les 9 58 48" src="https://cloud.githubusercontent.com/assets/698779/11585725/5945006c-9a6e-11e5-82b9-ff40e7d979fb.png">

I think that it would be interesting to define a sonata_type_button, I can try to make a PR. @Soullivaneuh @rande is this feature interesting enough?

**Comment by OskarStark** [comment]
i would like this PR :+1:, maybe we can handle a possible BC break and use this for the current action buttons

**Comment by jordisala1991** [comment]
The initial issue was fixed (with a provided solution).

The second issue is not related to the first one and there are other issues about that: https://github.com/sonata-project/SonataAdminBundle/issues/3217

Closing this one for now. If you think this is still relevant please reopen @OskarStark
