### ISSUE TITLE
How to get container instance in sonata Admin class?

### ISSUE THREAD

**Issue by toxicity1985** [sonata-project/SonataAdminBundle#3076]
I need to parse some configurations parameters from my config.yml such as enabled languages. But when i try to do that by using the normal symfony method: $this->container->get('my_params'); it fails because my admin class extends Sonata\AdminBundle\Admin\Admin class which does not extend the Symfony\Component\DependencyInjection\ContainerAware class.

Please, How to get the container inside the sonata Admin class ?

**Comment by AlexL5** [comment]
Have try this : $this->getConfigurationPool()->getContainer(); ?

**Comment by toxicity1985** [comment]
No, it's the new way to get container in admin bundle ?

**Comment by pulzarraider** [comment]
The prefered way is not to use the container directly but send all parameters and services that you need inside your admin class by setters when you define [the admin service in the yaml/xml file](https://sonata-project.org/bundles/admin/2-3/doc/reference/architecture.html#the-admin-class).

**Comment by Soullivaneuh** [comment]
@toxicity1985 please follow @pulzarraider indication, that is the good way to do.

I close this one as it's answered. Feel free to reopen if this does not resolve your issue.

**Comment by toxicity1985** [comment]
The prefered way doesn't work in my case. 
The  Sonata\AdminBundle\Admin\Admin class does not extend the Symfony\Component\DependencyInjection\ContainerAware.

**Comment by Soullivaneuh** [comment]
> The Sonata\AdminBundle\Admin\Admin class does not extend the Symfony\Component\DependencyInjection\ContainerAware.

Yes, it should not.

Don't think you followed exactly the recommendation. Could you please paste your admin service declaration?

**Comment by toxicity1985** [comment]
sonata.admin.produit:
        class: CoyotePrint\ProductBundle\Admin\ProduitAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: CoyotePrint, label: Produit }
        arguments:
            - ~
            - CoyotePrint\ProductBundle\Entity\Produit
            - 'PixSortableBehaviorBundle:SortableAdmin'
        call:
            - [ setContainer, [ @service_container ] ]
            - [ setPositionService, [@pix_sortable_behavior.position]]
            - [ setUploadableManager, [@pix_sortable_behavior.position]]

**Comment by toxicity1985** [comment]
Any news ?

**Comment by OskarStark** [comment]
@toxicity1985 

how is your param named you whish to inject?

**Comment by toxicity1985** [comment]
It's setPositionService and SetUploadableLManager.
With the call method, i have to write method in my Admin.
But the function is never called.
Here is the Admin Class.

<?php

/*
 * This file is part of the Sonata package.
 *
 * (c) Thomas Rabaix <thomas.rabaix@sonata-project.org>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace CoyotePrint\ProductBundle\Admin;

use Sonata\AdminBundle\Admin\Admin;
use Sonata\AdminBundle\Show\ShowMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use CoyotePrint\ProductBundle\Entity\Produit;
use Sonata\AdminBundle\Route\RouteCollection;

/**
 * @author Thomas Rabaix <thomas.rabaix@sonata-project.org>
 */
class ProduitAdmin extends Admin
{
	public $last_position  = 0;
	public $positionService;
	public $uploadableManager;
	
	public $positionService;
	
	public function setPositionService(\Pix\SortableBehaviorBundle\Services\PositionHandler $positionHandler)
	{
		$this->positionService  = $positionHandler;
	}
?>

**Comment by OskarStark** [comment]
why do you define positionService twice?

```php
public $positionService;
public $uploadableManager;

public $positionService;
```

can you please format your code with a code block?

**Comment by toxicity1985** [comment]
It's a mistake.

**Comment by OskarStark** [comment]
this should work i think and the way how you inject looks correct

did you get an error?

**Comment by toxicity1985** [comment]
No error, it's strange.

**Comment by pulzarraider** [comment]
@toxicity1985  please make sure there is no other service that is called `sonata.admin.produit:`. Maybe you have the same service duplicated somewhere without calling the setter in the service definition.

**Comment by toxicity1985** [comment]
No, i find the mistake. It's calls and not call method ...
Hard to see !

**Comment by OskarStark** [comment]
??
