### ISSUE TITLE
The block type "sonata.admin.block.search_result" does not exist

### ISSUE THREAD

**Issue by liquorvicar** [sonata-project/SonataAdminBundle#3079]
New installation of the SonataAdminBundle is throwing this Exception when using the search box in the top-left corner:
An exception has been thrown during the rendering of a template ("The block type "sonata.admin.block.search_result" does not exist") in SonataAdminBundle:Core:search.html.twig at line 52. 

\Sonata\AdminBundle\Block\AdminSearchBlockService exists and the service is defined:
```
<service id="sonata.admin.block.search_result" class="Sonata\AdminBundle\Block\AdminSearchBlockService">
        <tag name="sonata.block"/>
        <argument>sonata.admin.block.search_result</argument>
        <argument type="service" id="templating" />
        <argument type="service" id="sonata.admin.pool" />
        <argument type="service" id="sonata.admin.search.handler" />
</service>
```

Not sure where else to look for the issue.

**Comment by Soullivaneuh** [comment]
Please paste result of `composer info -i | grep sonata` and your `composer.json` file.

**Comment by rande** [comment]
You need to enable it: https://github.com/sonata-project/sandbox/blob/2.4-develop/app/config/sonata/sonata_block.yml#L16-L17

**Comment by liquorvicar** [comment]
@rande Perfect, thanks.

**Comment by Rotimi-Best** [comment]
Great thanks, it did the job
