### ISSUE TITLE
Form Event PRE_SET_DATA creates loop in configureFormFields only valid on 3rd run

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3080]
I was able to reproduce my original issue started in https://github.com/sonata-project/SonataAdminBundle/issues/2847 to a short piece of code.

Here is a basic `configureFormFields` setup:

``` php
class WageTypeAdmin extends Admin
{
    private $wt = 1;

    // Fields to be shown on create/edit forms
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->add('id');
        $formMapper->add('name', null, array('label' => 'Run ' . $this->wt));

        $formMapper->getFormBuilder()->addEventListener(FormEvents::PRE_SET_DATA,
            function (FormEvent $event) use ($formMapper) {
                $wageType = $event->getData();
                $form = $event->getForm();

                dump("Loop " . $this->wt);
                dump($wageType);

//                if ($this->wt > 2) {
                    $formMapper->add('name', null, array('label' => 'Run ' . $this->wt));
//                }

                $this->wt++;
            }
        );
    }
```

Full code: https://gist.github.com/webdevilopers/095d5c6a8cd635d0fb63#file-no_label_change-php

First of all I recognized that the event runs at least _2_ times as you can see in my template showing the dumps. In addition to that the `label` of the `name` field has not changed (removing the field before doesn't change that behaviour btw).

![bildschirmfoto vom 2015-06-30 11 30 24](https://cloud.githubusercontent.com/assets/3479626/8427889/18f4ae00-1f1b-11e5-9570-47f89ed9aee4.png)
![bildschirmfoto vom 2015-06-30 11 30 54](https://cloud.githubusercontent.com/assets/3479626/8427891/23900990-1f1b-11e5-9c25-781ebc51f114.png)

If I do not add the `name` field in the first instance like this:
https://gist.github.com/webdevilopers/095d5c6a8cd635d0fb63#file-key_does_not_exist-php
I get the following error from my template:

```
Key "name" in object with ArrayAccess of class "Symfony\Component\Form\FormView" does not exist in SonataAdminBundle:CRUD:base_edit_form_macro.html.twig at line 23
```

Now if I use my internal counter to prevent the first loops like this:
https://gist.github.com/webdevilopers/095d5c6a8cd635d0fb63#file-no-error-php
the error disappears. But no `name` element is ever added:
![bildschirmfoto vom 2015-06-30 11 39 37](https://cloud.githubusercontent.com/assets/3479626/8428094/63d264f2-1f1c-11e5-83b0-031874c42292.png)

This makes it impossible to dynamically add fields depending on the `PRE_SET_DATA`. And it is impossible to change / overwrite existing fields.

Another workaround is this:
https://gist.github.com/webdevilopers/095d5c6a8cd635d0fb63#file-workaround-php

Without adding the `name` in the first instance using `$form` will create:
![bildschirmfoto vom 2015-06-30 11 58 23](https://cloud.githubusercontent.com/assets/3479626/8428462/fde4612e-1f1e-11e5-9c41-47ee08657270.png)

As soon as I add the `name` in the first instance I get the desired result:
![bildschirmfoto vom 2015-06-30 11 59 20](https://cloud.githubusercontent.com/assets/3479626/8428486/1d5319ce-1f1f-11e5-9e17-0d150b1bf484.png)

Of course this will only work for non-sonata-field-types. You cannot use `$form` to use field types like `doctrine_orm_choice` etc. - they require using the `$formMapper`!

I hope these examples made the root of the issue more clear @rande ?

Possibly related:
- https://github.com/symfony/symfony/pull/4552 by @MDrollette 
- https://github.com/symfony/symfony/pull/7878

**Comment by bertterheide** [comment]
I'm currently working on a project that requires dynamic form fields based on a ChoiceType-field selection, but I'm getting the same error message as described here:

`Key "test" in object with ArrayAccess of class "Symfony\Component\Form\FormView" does not exist.`

As a result, I am not able to complete this feature.

Is there any progress on this issue, or do you have another solution to circumvent this?

**Comment by core23** [comment]
Looks like nobody fixed this issue. Feel free to fix :+1:

**Comment by webdevilopers** [comment]
I explained to @core23 on Twitter that I no longer maintain the projects that use Sonata.
I will try to comment on the issues anyway. I will close them if nobody else suggested a PR or similar.

There have been some proposals for this issue. From my POV it can be closed.
Please tell me if I have to close it personally.
