### ISSUE TITLE
Improve docs for custom edit templates using dynamic form modifications

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3083]
Came from https://github.com/sonata-project/SonataAdminBundle/issues/2968 and opening new issue as suggested by @pulzarraider to improve docs.

It can be assigned to me and labeled as docs. Just need to know where to put this topic.

A custom `edit` template topic has been opened here:
- https://sonata-project.org/bundles/admin/2-3/doc/reference/templates.html#configuring-templates

There is a chapter about form modification here:
- https://sonata-project.org/bundles/admin/master/doc/cookbook/recipe_dynamic_form_modification.html

And a general one about form mapper here:
- https://sonata-project.org/bundles/doctrine-orm-admin/master/doc/reference/form_field_definition.html

This improvement could primary concentrate on the custom `edit` template and how to use `is defined` in your twig template or the `admin.formgroups`.

This could be shown without even mentioning any form events which still seem to be a little bit buggy atm:
- https://github.com/sonata-project/SonataAdminBundle/issues/3080

**Comment by greg0ire** [comment]
Very late to the party, but if you're still interested in writing some docs, I'd say use the second link, it's about modifying a form based on the underlying data, which is your case, right?
