### ISSUE TITLE
[2.4] [AdminPoolLoader] Deprecated usage

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataAdminBundle#3091]
```
DEPRECATED - Not calling the parent constructor in Sonata\AdminBundle\Route\AdminPoolLoader which extends Symfony\Component\Config\Loader\FileLoader is deprecated since version 2.7 and will not be supported anymore in 3.0.
```

Ref:  [Sonata\AdminBundle\Route\AdminPoolLoader::__construct()](https://github.com/sonata-project/SonataAdminBundle/blob/18a76b7bd6e2ff3fe0a4f497c08b648a1ab24bf9/Route/AdminPoolLoader.php#L46)

**Comment by Soullivaneuh** [comment]
By what it should be replaced?

**Comment by phansys** [comment]
I don't know, that's the reason because I've opened an issue instead a PR.

**Comment by desarrolla2** [comment]
I'm reading about how upgrade to 2.7 and not more information is provided

https://github.com/symfony/symfony/blob/2.7/UPGRADE-2.7.md so i'm not sure if it is realy deprecated.

**Comment by Soullivaneuh** [comment]
Oh I got it! Just re-read the warning message:

> Not calling the parent constructor is deprecated since version 2.7 and will not be supported anymore in 3.0.

So the `AdminPoolLoader` class should call parent constructor.

But why? I don't know, nothing on the documentation about that: https://github.com/symfony/symfony/search?l=markdown&q=FileLoader&utf8=%E2%9C%93

**Comment by fracsi** [comment]
The `AdminPoolLoadeWhy does the `AdminPoolLoader` class extend the `\Symfony\Component\Config\Loader\FileLoader`? The simple `Symfony\Component\Config\Loader\Loader` would be sufficient (i did not run the tests). Thus the deprecation warning would be gone.

**Comment by Koc** [comment]
Looks like related PR was merged and this issue can be closed. @phansys can you verify?
