### ISSUE TITLE
How can you access data from a form embedded inside embedded form?

### ISSUE THREAD

**Issue by MortisQc** [sonata-project/SonataAdminBundle#3098]
I have Product, it can have many urls and urls can have many tags. 
I want, from Product edit view, to be able to add urls (that works) and to be able to add tags to those urls. 
The trick is that I don't want to add ProducturlTag by inline form, I want a multiselect to add all the tags at once, 

I got it to work with Product <-> Countries association where I defined countries as not mapped field, then I can add the countries manually to the product by getting them from the form. 
But here I don't find the tags selected. 

Thanks in advance for your help. 

in ProductAdmin:

``` php
protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
                ->add('name', null, array('required' => true))
                ->add('countries', 'entity',array(
                    'mapped' => false,
                    'query_builder' => function (\AppBundle\Entity\Repository\CountryRepository $repository) {
                        return $repository->findAllSorted('country');
                    },
                    'class' => 'AppBundle:Country',
                    'expanded' => true,
                    'multiple' => true,
                ))
                ->add('producturls', 'sonata_type_collection',array(
                     'type_options' => array( 
                     )), array(
                    'edit' => 'inline',
                    'inline' => 'table',
                ))
        ;
    }
```

in ProducturlAdmin:

``` php
protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('url', 'url')
            ->end();
        if (!$this->hasParentFieldDescription()) {
            //whatever...
        } else if ($this->hasParentFieldDescription() && $this->getParentFieldDescription()->getAdmin()->getClass()=='AppBundle\Entity\Product') {
            $formMapper
                ->add('tags',null,array(
                    'mapped' => false,
                    'query_builder' => function (\AppBundle\Entity\Repository\TagRepository $repository) {
                        return $repository->findAllSorted('name');
                    },
                    'class' => 'AppBundle:Tag',
                    'multiple' => true,
                    'attr'=>array('data-sonata-select2'=>'false')
                ))
                ->end();
        }
    }
```

so, it looks good (in product edit view you have your list of producturls and can click 'add new' to add a new producturl and each producturl line has a multiselect with tags), but I don't know how to access the tags selected for each url. 
To add countries to my product I use that code in ProductAdmin, (prePersist() and PreUpdate() ):

``` php
$form_countries = $this->getForm()->get('countries')->getData();
$object_countries = $object->getCountries();
```

Then you can compare the 2 collections and do your business. 
Thanks for your help.

**Comment by tbyte80** [comment]
Ok so you have a one-to-many connection between "Product" and "Url" and a many-to-many connection between "Url" and "Tag". Is that correct? If you use ORM did you specify the relation in your metadata somehow like that?
```xml
<many-to-many field="tags" target-entity="Tag">
      <join-table name="url2tag">
        <join-columns>
          <join-column name="url_id" referenced-column-name="id" />
        </join-columns>
        <inverse-join-columns>
          <join-column name="tag_id" referenced-column-name="id" />
        </inverse-join-columns>
      </join-table>
</many-to-many>
```
see http://doctrine-orm.readthedocs.org/en/latest/reference/association-mapping.html#many-to-many-unidirectional

In your ProducturlAdmin you could then write

```php
->add('tags', null, array('label' => 'URL tags', 'expanded' => true, 'by_reference' => false, 'multiple' => true))
```

to get a fancy select2 dropdown. 
Don't forget to add 

```php
public function __toString()
{
    return $this->getName();
}
```
to your Tag Entity.

**Comment by jordisala1991** [comment]
No response in 3 years and no stack trace. There was a provided solution, but no answer.

Closing for now, as there is not enough information to solve the problem. If you still having this issue, please ping me to reopen, but provide more information.

Possible related (or not) issues: https://github.com/sonata-project/SonataAdminBundle/issues/3583 https://github.com/sonata-project/SonataAdminBundle/issues/4752
