### ISSUE TITLE
createQuery in not correctly generated

### ISSUE THREAD

**Issue by morkers** [sonata-project/SonataAdminBundle#3099]
Entity (property in camel case, database column name uses underscore):
```php
/**
 * @var integer
 *
 * @ORM\Column(name="period_start", type="integer")
 */
private $periodStart;
```

When i override query to sort the list
```php
public function createQuery($context = 'list')
	{
		$query = parent::createQuery($context);
		$query->orderBy($query->getRootAliases()[0] . '.periodStart', 'asc');

		return $query;
	}
```
i get exception
> Column not found: 1054 Unknown column `'m0_.periodStart'` in 'order clause'

If i use underscore in queryBuilder ('.period_start') i get
> Entity has no field or association named period_start

**Comment by pulzarraider** [comment]
You have probably wrong alias. Please try to replace `$query->getRootAliases()[0]` with `$query->getRootAlias()`.

**Comment by morkers** [comment]
No. The alias is ok, If i change the column name to periodStart, then the query works

**Comment by pulzarraider** [comment]
@morkers Are you sure, you have `period_start` database column in the related database table?

**Comment by morkers** [comment]
@pulzarraider Yes, property name is `periodStart` and database column is `period_start`.

**Comment by pulzarraider** [comment]
Can you please paste here the whole sql query and the result of command `composer licenses | grep sonata`?

**Comment by morkers** [comment]
`composer licenses | grep sonata`
sonata-project/admin-bundle               2.3.x-dev 5f51bc6   MIT           
sonata-project/block-bundle               2.2.13              MIT           
sonata-project/cache                      dev-master 0f2437f  MIT           
sonata-project/cache-bundle               2.2.0               MIT           
sonata-project/core-bundle                2.3.1               MIT           
sonata-project/datagrid-bundle            dev-master fec0147  MIT           
sonata-project/doctrine-extensions        1.0.2               MIT           
sonata-project/doctrine-orm-admin-bundle  2.3.x-dev c7e5119   MIT           
sonata-project/easy-extends-bundle        dev-master 55deba6  MIT           
sonata-project/exporter                   dev-master 92835b5  MIT           
sonata-project/intl-bundle                2.2.1               MIT           
sonata-project/media-bundle               2.3.0               MIT           
sonata-project/notification-bundle        dev-master a7023e2  MIT 

`Exception`
An exception has been thrown during the rendering of a template ("An exception occurred while executing 'SELECT DISTINCT m0_.id AS id0, m0_.id AS id1 FROM medium_availability m0_ ORDER BY m0_.day ASC, m0_.periodStart ASC, m0_.id ASC LIMIT 25 OFFSET 0':

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'm0_.periodStart' in 'order clause'") in SonataAdminBundle:CRUD:base_list.html.twig at line 33.

**Comment by greg0ire** [comment]
Sonata 2 is no longer supported, sorry. Please reopen if you experience this bug with Sonata 3.
