### ISSUE TITLE
can i use these bundle in laravel 5

### ISSUE THREAD

**Issue by rayhan0421** [sonata-project/SonataAdminBundle#3100]

**Comment by jvasseur** [comment]
Probably not, laravel doesn't use the same DI system as Symfony so this would need a lot of work to make them work with laravel.

**Comment by rayhan0421** [comment]
can i use as standalone ?

**Comment by Soullivaneuh** [comment]
As I said in https://github.com/sonata-project/SonataPageBundle/issues/506#issuecomment-119898713, it's not possible to use it with Laravel.

Bundle system is directly linked to Symfony.

No standalone possible.

Just make a quick search about "Laravel admin generator" on google. Found this as a example: https://github.com/krafthaus/bauhaus
