### ISSUE TITLE
any documentation for theme customization ?

### ISSUE THREAD

**Issue by rayhan0421** [sonata-project/SonataAdminBundle#3101]

**Comment by OskarStark** [comment]
is this a question?

**Comment by rayhan0421** [comment]
yas

**Comment by rayhan0421** [comment]
i mean frontend customization

**Comment by Soullivaneuh** [comment]
You have template options doc here: https://sonata-project.org/bundles/admin/master/doc/reference/templates.html

For the rest, please see Symfony documentation about bundles templates override: http://symfony.com/doc/current/book/templating.html#overriding-bundle-templates
