### ISSUE TITLE
->with() not working in children admin class if include with sonata_type_admin

### ISSUE THREAD

**Issue by 2ball** [sonata-project/SonataAdminBundle#3102]
Hi. Today I add sonata_type_admin to tab and noticed that Sonata not include my layout from children admin class. I create 3 cols, and I see him in children entity admin class, but if I load this to tab in parent admin class all layouts exluded.

->with() not working in children admin class if include with sonata_type_admin

    ---prev parent fields---
    ->tab('Contacts')
         ->add('contacts', 'sonata_type_admin', ['required' => false, 'delete' => false, 'btn_add' => false])
    ->end()
    ---next parent fields---

And children admin class method

    $formMapper
            ->with('Способы связи', ['class' => 'col-md-4'])
                ->add('phones', 'collection',
                    [
                        'label' => 'Телефоны',
                        'type' => new ClubPhonesListType(),
                        'required' => false,
                        'allow_add' => true,
                        'allow_delete' => true,
                        'attr' => ['class' => 'emails-list'],
                        'options' => ['label' => ' ', 'required' => false],
                    ],
                    [
                        'edit' => 'inline',
                        'inline' => 'table',
                        'sortable' => 'position',
                    ])
                ->add('emails', 'collection',
                    [
                        'label' => 'Электронная почта',
                        'type' => new ClubEmailsListType(),
                        'required' => false,
                        'allow_add' => true,
                        'allow_delete' => true,
                        'attr' => ['class' => 'emails-list'],
                        'options' => ['label' => ' ', 'required' => false],
                    ],
                    [
                        'edit' => 'inline',
                        'inline' => 'table',
                        'sortable' => 'position',
                    ])
            ->end()
            ->with('Геоданные', ['class' => 'col-md-4'])
                ->add('latitude', 'text', ['label' => 'Широта'])
                ->add('longitude', 'text', ['label' => 'Долгота'])
                ->add('polygon', 'text', ['label' => 'Полигон на карте'])
                ->add('country', 'text', ['label' => 'Город'])
                ->add('region', 'text', ['label' => 'Регион'])
                ->add('city', 'text', ['label' => 'Город'])
                ->add('address', 'text', ['label' => 'Полный адрес'])
            ->end()
            ->with('WEB', ['class' => 'col-md-4'])
                ->add('site', 'text', ['label' => 'Адрес сайта'])
                ->add('vk', 'text', ['label' => 'Сообщество Вконтакте'])
                ->add('facebook', 'text', ['label' => 'Сообщество Facebook'])
                ->add('twitter', 'text', ['label' => 'Канал twitter'])
                ->add('instagram', 'text', ['label' => 'Instagram'])
            ->end()
            ->with('Оперативная связь', ['class' => 'col-md-4'])
                //@todo: ссылка на аккаунт менеджера с выводом имени
                ->add('managerPhone', 'text', ['label' => 'Телефон менеджера'])
                ->add('managerInWhatsApp', 'checkbox', ['label' => 'Есть в WhatsApp'])
                ->add('managerInViber', 'checkbox', ['label' => 'Есть в Viber'])
                ->add('managerInTelegram', 'checkbox', ['label' => 'Есть в Telegram'])
                ->add('skype', 'text', ['label' => 'Skype'])
            ->end();

**Comment by core23** [comment]
This issue should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue

**Comment by FireLizard** [comment]
I've got the same problem as @2ball .
Is there any solution?

```
$ composer show sonata-project/*
sonata-project/admin-bundle              3.13.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.2.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0  Lightweight Exporter library
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/translation-bundle        2.1.0  SonataTranslationBundle
sonata-project/user-bundle               3.2.0  Symfony SonataUserBundle
```

Greetings
