### ISSUE TITLE
Datepicker format is incorrect

### ISSUE THREAD

**Issue by muka** [sonata-project/SonataAdminBundle#3104]
Hi
I'm using sonata 2.4@dev and using "sonata_type_datetime_picker" I have the bootstrap date picker but the default date format shown upon selection is wrong and doesn't allow to submit the value

Eg. "July 14, 0000 9:00 AM 14, 0000 9:00:00 am"
The one that come by default is `LLL D, YYYY h:mm:ss a`

This works instead `'date_format'           => 'MMM D, YYYY h:mm:ss A'`

(My current locale is it_IT)

update: I've installed `intl` and Sonata i18n and now I'm unable to find a compatible format

**Comment by pulzarraider** [comment]
@muka please, try just the `it` locale, not `it_IT`.
