### ISSUE TITLE
Issues with Date and Time form types and the Datepicker plugin

### ISSUE THREAD

**Issue by MeloAndroid** [sonata-project/SonataAdminBundle#3109]
I have a Symfony 2.7 project with this requirements in composer.json:
        ....
        "sonata-project/admin-bundle": "^2.3",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3",
        "sonata-project/user-bundle": "^2.2"

The adminbundle works and I can't manage my Admin classes but I have issues with the date and time fields. 

First, I don't like to see each date-field (day, month and year) or time field (hour, minutes) each in a different row but I can't get to change that behaviour. Maybe it's not admin-bundle related. I can get 3 select boxes inline with some custom css but I think it isn't the proper solution.

Second, I have see that there is a bootstrap datepicker included in sonata-core. I can configure it for date fields but I have some time fields in my database and I can't get only the time-picker button of the plugin. The plugin documentation shows that its possible in a example (https://eonasdan.github.io/bootstrap-datetimepicker/#custom-formats). We have only sonata_type_date_picker and sonata_type_datetime_picker and I would need a sonata_type_time_picker. To see if it's possible I have try to mannually change datepicker.html.twig to change the html markup accordingly to the example and put the class "glyphicon-time" instead of "glyphicon-calendar" but everytime the widget is rendered with "glyphicon-calendar". Any solution for edit time fields (without date?) with the included datepicker?

Third. If the datepicker is not enabled by default, why are the assets added by default?

Thanks.

**Comment by AlexandreKilian** [comment]
datetime seems to be broken at the moment, getting weird formatting 
`July 21, 0000 12:00 AM 21, 0000 12:00:00 am`

**Comment by tbyte80** [comment]
Regarding the select boxes you can change that pretty easily by using "sonata_type_datetime_picker" as type for your field and adapting your config.yml like this:
```
twig:
    # ...
    form:
        resources:
            # ...
            - 'SonataCoreBundle:Form:datepicker.html.twig'
```
as documented here: https://sonata-project.org/bundles/core/master/doc/reference/form_types.html

**Comment by frak** [comment]
@AlexandreKilian did you manage to fix or workaround this issue?

**Comment by frak** [comment]
Of course, as soon as I ask, I find my own solution - doh!  For me the problem was that I was specifying the year part of my custom format with YYYY, I changed that to yyyy and it fixed it, so I no longer use the broken default format.

**Comment by AlexandreKilian** [comment]
@frak my solution was adding a php extension, don't know by heart which one though...

**Comment by frak** [comment]
intl by any chance?

> Alexandre Kilian <mailto:notifications@github.com>
> 21 March 2016 at 16:21
>
> @frak <https://github.com/frak> my solution was adding a php 
> extension, don't know by heart which one though...
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub 
> <https://github.com/sonata-project/SonataAdminBundle/issues/3109#issuecomment-199363546>
>

-- 
Sent with Postbox <http://www.getpostbox.com>

**Comment by AlexandreKilian** [comment]
that's the one

**Comment by jordisala1991** [comment]
The initial issue with dates and times is solved, you need to add some form themes and configure the form mapper correctly.

The second issue about docs missing... There is already a recommendation on Symfony side: https://github.com/symfony/requirements-checker/blob/master/src/SymfonyRequirements.php#L272

Closing this one as the main issue is fixed.

If you think the requirements checker for Symfony aren’t enough, please open an issue focused on adding intl recomendation on CoreBundle.

If the main issue is not solved, please ping me to reopen
