### ISSUE TITLE
Attempted to load class "InlineConstraint" from namespace "\Symfony\Component\Validator\Constraints\Sonata\AdminBundle\Validator\Constraints

### ISSUE THREAD

**Issue by edouardkombo** [sonata-project/SonataAdminBundle#3115]
Hi,

I'm using the version master of Admin Bundle and Core bundle.
When I try to access Nelmio api doc, I get this error message:

    CRITICAL - Uncaught PHP Exception Symfony\Component\Debug\Exception\ClassNotFoundException: "Attempted to load class "InlineConstraint" from namespace "\Symfony\Component\Validator\Constraints\Sonata\AdminBundle\Validator\Constraints". Did you forget a "use" statement for "Sonata\CoreBundle\Validator\Constraints\InlineConstraint"?" at /var/www/back_entrepatients/vendor/symfony/symfony/src/Symfony/Component/Validator/Mapping/Loader/AbstractLoader.php line 89 

Could someone please help me?

**Comment by Soullivaneuh** [comment]
What is the relation between nelmio and our bundles?

As the error says, it seems to be a use key missing.

Please be more explicit and paste the full code of the concerned file.

**Comment by fnagel** [comment]
@edouardkombo Could be related to https://github.com/sonata-project/SonataMediaBundle/issues/680

**Comment by greg0ire** [comment]
No answer… closing.
