### ISSUE TITLE
Passing a parameter when adding new entity with "sonata_type_collection"

### ISSUE THREAD

**Issue by tameribrahim** [sonata-project/SonataAdminBundle#3116]
Can I send a parameter when press on "Add new" in a sonata_type_collection form type , that filters the list in the popup?
My entities
Category (name)
Newsletter (name - category_id - newsletter_posts)
Post ( title - category_id - body )
NewsletterPost ( newsletter_id - post _id )
In the Newsletter form , when the user selects a category , and starts to add posts, I want the list to open only the posts related to the selected category.
Thanks in advance

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
