### ISSUE TITLE
getAdminByClass tries to find admin classes with null classname

### ISSUE THREAD

**Issue by kminh** [sonata-project/SonataAdminBundle#3120]
Hi,

Recently I'm using this bundle for non-entity admin classes, i.e. those that are used for non-CRUD purpose such as displaying statistics. To do this I have to define the admin service like so:

``` yaml
    admin.service:
        tags: ...
        arguments:
            - ~
            - ~
     ...
```

This makes the `$class` property of the `Sonata\AdminBundle\Admin\Admin` become `null`.

Now when this bundle calls `Sonata\AdminBundle\Admin\Admin::attachAdminClass` which ends up in `Sonata\AdminBundle\Admin\Admin::getAdminByClass`, if there is no target entity (which is null) the `getAdminByClass` method will try to get the admin class of the above admin service (with entity class set to null). This happens for all admin services that have association fields.

This can be reproduced by installing https://github.com/symfony-cmf/SimpleCmsBundle and then setup **more than one** admin services with null entity.

If there is no target entity, shouldn't `attachAdminClass` return immediately?

Right now I have to set the entity class to `false` instead of `~` to work around this issue.

Any insight is much appreciated.

**Comment by core23** [comment]
AFAIK every entity should have a associated admin class. Feel free to contribute to change this behavior.
