### ISSUE TITLE
action in crud controller is never used.

### ISSUE THREAD

**Issue by toxicity1985** [sonata-project/SonataAdminBundle#3129]
Hi,

When i try to make my own crud controller, I have the possibility to define the action for the submit form.

```
$this->get('twig')->getExtension('form')->renderer->setTheme($view, $this->admin->getFormTheme());
        return $this->render($this->admin->getTemplate($templateKey), array(
            'action' => 'generateArticle',
            'form'   => $view,
            'object' => $object,
        ));
```

And when i go to see the base_edit_form.html.twig, we can see that the action is never used.

```
 {% set url = admin.id(object) is not null ? 'edit': 'create' %}
```

So my question is, does a basic template exist for rendering basic form with custom action ?
If no, i have to create it i think but it will be interesting to add one in the bundle.

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
