### ISSUE TITLE
Add styles to list mapper fields

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3130]
This may sound like an easy task but at the moment I'm just too blind to see how to add `attr`ibutes like `style` to the generated header columns in my `configureListFields` without overriding the `list` template:

``` php
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('supplierBranch.company.name', null, array(
                'label' => 'list.fields.supplier_branch',
                'template' => 'AppBundle:ContractAdmin:list__supplier_branch.html.twig',
                'attr' => array('style' => 'width:400px;'),
                'class' => 'foo'
        ));
    }
```

This does not change the cell and it wouldn't be helpful since the `style` e.g. `width` needs to be applied to the header cell.

``` html
<th class="sonata-ba-list-field-header-text sonata-ba-list-field-header-order-asc "> Supplier Branch </th>
...
<td class="sonata-ba-list-field sonata-ba-list-field-text" objectid="6323">...</td>        
```

**Comment by welcoMattic** [comment]
:+1:

**Comment by QuentinPolantis** [comment]
I'm facing the same problem. 

I add "header_class" =>"col-md-5" like it is explained in the documentation, but like @webdevilopers , nothing change. (https://sonata-project.org/bundles/admin/master/doc/reference/action_list.html#visual-configuration)

**Comment by ureimers** [comment]
According to https://sonata-project.org/bundles/admin/master/doc/reference/action_list.html#visual-configuration you have to use `header_style`, so you would end up with:

```
protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('supplierBranch.company.name', null, array(
                'label' => 'list.fields.supplier_branch',
                'template' => 'AppBundle:ContractAdmin:list__supplier_branch.html.twig',
                'header_style' => 'width:400px;',
                'class' => 'foo'
        ));
    }
```

That actually worked for me.

**Comment by webdevilopers** [comment]
Can you confirm this indeed does work for you @QuentinPolantis ? Then we can close this issue.

**Comment by QuentinPolantis** [comment]
Hello,

Yes, this issue seems to have been fixed now and it's working for me as well.

**Comment by greg0ire** [comment]
Thanks for figuring that one out.
