### ISSUE TITLE
Autocompleter needs LIST permission of target Admin

### ISSUE THREAD

**Issue by nixoschu** [sonata-project/SonataAdminBundle#3131]
Hey,

I have the following Use-Case:

---

I have an Admin which can manage Users of the SonataAdmin (CRUD).
No other User-Role is allowed to do that.

I have one Form for an Entity where I need an Autocompleter to search for existing Users.
The Autocompleter is working fine if I ' am the Admin-User. If I choose another User I get an Error "Access Denied" when using the Autocompleter.

---

In **Controller/HelperController.php at line 341** there is a check if the current User has permissions for the LIST view of the **$targetAdmin**.

With this check I would need to shift around the permissions. I would need to grant the other User-Role the permission for the USER_LIST even if I don't want them to see the list.

I think it would be better if another permission would be requested, something like "AC" or "AC_REQUEST"

**Comment by pulzarraider** [comment]
We should make it configurable so changing the permissions will not break the BC.

**Comment by pulzarraider** [comment]
@nixoschu this problem was fixed in SonataAdminBundle version `3.17.0`. Thank your for reporting the problem.
