### ISSUE TITLE
$(...).slimscroll is not a function, $(...).datetimepicker is not a function

### ISSUE THREAD

**Issue by naokha** [sonata-project/SonataAdminBundle#3137]
Hello,

I'm using Sonata Admin. Here is the corresponding line in my composer :
"require": {
    ....,
    "sonata-project/admin-bundle": "^2.3",
}

When I try to access to a list (path is like app_name/admin/core/entity_name/list), I see some errors in my web browser :
- Uncaught TypeError: $(...).datetimepicker is not a function (from my current view which extends SonataAdminBundle:CRUD:base_list.html.twig)
- Uncaught TypeError: $(...).slimscroll is not a function (from file sonataadmin/vendor/App.js line 70)

Do you have any idea why it happens ? 
SlimScroll seems to be defined in the App.js file beginning at line 415.
DatetimePicker is in bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker.

I ran a "composer update", cleared cache and installed assets.

Thanks.

**Comment by greg0ire** [comment]
We no longer support Sonata 2, please reopen if you experience this with Sonata 3
