### ISSUE TITLE
Bug in rendring edit form

### ISSUE THREAD

**Issue by egordanilenko** [sonata-project/SonataAdminBundle#3140]
Option "form_type" does not pass to SonataAdminBundle:Form:form_admin_fields.html.twig
composer.json
"sonata-project/core-bundle": "dev-master",
"sonata-project/admin-bundle": "dev-master",
"sonata-project/doctrine-orm-admin-bundle": "dev-master",

Exception: 
Key "form_type" does not exist as the array is empty in SonataAdminBundle:Form:form_admin_fields.html.twig at line 261
500 Internal Server Error - Twig_Error_Runtime

To produce:
Create/edit an entity via Admin class

This problem appeared after yesterday's update, previos date of update ~ 20-21 July

**Comment by Soullivaneuh** [comment]
More information is needed:

* Code related to your issue (Admin class, service declaration...)
* Do you have some sonata admin template override? If yes, could you test without?
* Please paste `composer info -i | grep sonata` result

Thanks

**Comment by egordanilenko** [comment]
All right, i'm was wrong @ override service, at 2.3 this work without exception. Thanks for help.
