### ISSUE TITLE
Pager: Where condition not reset after Id Query

### ISSUE THREAD

**Issue by anvaya** [sonata-project/SonataAdminBundle#3146]
Hey,

File: sonata-project\doctrine-orm-admin-bundle\Datagrid\ProxyQuery.php
Method: private function getFixedQueryBuilder(QueryBuilder $queryBuilder)

=> Using Simple pager for a db with over 40 million rows.
=> Added a Callback filter.
=> Now when we analyze the queries, it turns out the ProxyQuery class issues two queries:
1. Select id, id from table where condition
2. Select id, col1,col2, col3 <etc> from table where ids in (<ids received in first query>)  AND rest of the where query from the first query.

=> This is therefore causing the where condition executed twice despite the first query already returning the ids, hence the where part of the original query is no longer required.  Causing major performance hit and unnecessary DB query.

=> To resolve this, I reset the "where" part of the query in the second query which actually returns the columns:

 /**
     \* This method alters the query to return a clean set of object with a working
     \* set of Object
     *
     \* @param \Doctrine\ORM\QueryBuilder $queryBuilder
     *
     \* @return \Doctrine\ORM\QueryBuilder
     */
    private function getFixedQueryBuilder(QueryBuilder $queryBuilder)
    {
        //....

```
    // step 4 : alter the query to match the targeted ids
    foreach ($idxMatrix as $idName => $idx) {
        if (count($idx) > 0) {
            $idxParamName = sprintf('%s_idx', $idName);
            $queryBuilder->resetDQLPart("where"); //Added by mrugendra.
            $queryBuilder->andWhere(sprintf('%s IN (:%s)', $selects[$idName], $idxParamName));
            $queryBuilder->setParameter($idxParamName, $idx);
            $queryBuilder->setMaxResults(null);
            $queryBuilder->setFirstResult(null);
        }
    }

    return $queryBuilder;
}
```

=> While the where part of the original query may be worth it in a database which changes constantly, in most other situation is a time and resource waster. Please consider updating the code similarly to avoid this issue.

**Comment by pulzarraider** [comment]
You are right @anvaya the additional conditions are not needed. I will create a PR tomorrow after some testing.
