### ISSUE TITLE
Pager: The 'DISTINCT' issue.

### ISSUE THREAD

**Issue by anvaya** [sonata-project/SonataAdminBundle#3147]
Hey,

=> We have a MySQL database with over 40 million rows.

=> Did a simple "select id, field1, field2,.... from table limit 32", returns in 1 sec.

=> Built Admin over it using Sonata admin, takes forever to load practically the same thing.

=> When the query was analyzed, it turns out sonata pager adds a "DISTINCT" keyword to the select statement.

=> While I can understand its requirement in join queries, but when you have a query which includes the primary key, and no one-to-many joins, this practically kills performance. Pager needs to be smarter.  I had to comment this part of code to get things working.

=> Is there a better option, perhaps I override this method in extended class and use that as the pager ? 
# Code: 

sonata-project\doctrine-orm-admin-bundle\Datagrid\ProxyQuery.php

/**
     \* This method alters the query to return a clean set of object with a working
     \* set of Object
     *
     \* @param \Doctrine\ORM\QueryBuilder $queryBuilder
     *
     \* @return \Doctrine\ORM\QueryBuilder
     */
    private function getFixedQueryBuilder(QueryBuilder $queryBuilder)
    {
        $queryBuilderId = clone $queryBuilder;

```
    // step 1 : retrieve the targeted class
    $from  = $queryBuilderId->getDQLPart('from');
    $class = $from[0]->getFrom();
    $metadata = $queryBuilderId->getEntityManager()->getMetadataFactory()->getMetadataFor($class);

    // step 2 : retrieve identifier columns
    $idNames = $metadata->getIdentifierFieldNames();

    // step 3 : retrieve the different subjects ids
    $selects = array();
    $idxSelect = '';
    foreach ($idNames as $idName) {
        $select = sprintf('%s.%s', $queryBuilderId->getRootAlias(), $idName);
        // Put the ID select on this array to use it on results QB
        $selects[$idName] = $select;
        // Use IDENTITY if id is a relation too. See: http://doctrine-orm.readthedocs.org/en/latest/reference/dql-doctrine-query-language.html
        // Should work only with doctrine/orm: ~2.2
        $idSelect = $select;
        if ($metadata->hasAssociation($idName)) {
            $idSelect = sprintf('IDENTITY(%s) as %s', $idSelect, $idName);
        }
        $idxSelect .= ($idxSelect !== '' ? ', ' : '') . $idSelect;
    }        

    $queryBuilderId->resetDQLPart('select');
    //$queryBuilderId->add('select', 'DISTINCT '.$idxSelect); //Commented by Mrugendra.
    $queryBuilderId->add('select', $idxSelect);
```

//        .....

```
    return $queryBuilder;
}
```

**Comment by pulzarraider** [comment]
Disabling the DISTINCT keyword is frequently demanded feature. I will look at it.

**Comment by pulzarraider** [comment]
Related issues: 
- sonata-project/SonataDoctrineORMAdminBundle#297
- sonata-project/SonataDoctrineORMAdminBundle#473
- sonata-project/SonataDoctrineORMAdminBundle#56
- sonata-project/SonataDoctrineORMAdminBundle#476

**Comment by FractalizeR** [comment]
I think we need to get 'must have' label back, because the PR in question was rejected and it seems to be never retargetted any other Sonata branch

**Comment by OskarStark** [comment]
@FractalizeR we do not have `must have` label anymore in our repos.

If it is critical for you, maybe you can work on a PR? Or at least an issue we we could discuss a possible solution?

**Comment by FractalizeR** [comment]
I see. Yes, this is rather important and I will try to look into the issue to propose a solution if possible. Thanks a lot for your response.

**Comment by FractalizeR** [comment]
@greg0ire @romainneutron Guys, I've written a reply [here](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/473#issuecomment-349053305). Are you interested to continue our talk? Or did I write something completely stupid? :)

**Comment by jordisala1991** [comment]
Duplicated of https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/473

Closing
