### ISSUE TITLE
Interface 'Symfony\Component\Security\Acl\Model\DomainObjectInterface' not found

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataAdminBundle#3150]
This error seems to occur since: https://github.com/symfony/symfony/commit/b26a449d463d44620ecad68a5ff43c99c33b9ae3

@rande We can simply add `symfony/security-acl` on requirement to fix it but I think we should make it optional and handle it properly for dev not using ACL.

What do you think?

**Comment by Soullivaneuh** [comment]
```php
abstract class Admin implements AdminInterface, DomainObjectInterface
```

Ok so no choice for the moment.

@rande Could be possible to think about optional implement? What the goal of this implements?

**Comment by andrewtch** [comment]
confirmed )
