### ISSUE TITLE
Required (*) icon not showing in Symfony 2.7.3

### ISSUE THREAD

**Issue by TisLars** [sonata-project/SonataAdminBundle#3155]
``` php
protected function configureFormFields(FormMapper $formMapper)
{
    $formMapper
        ->with('form.group_general')
            ->add('title', 'text', array('required' => true))
            ->add('body', 'ckeditor', array(
                'required' => false,
                'config_name' => 'simple'))
    ...
```

I upgraded to Symfony 2.7.3 and can't think of anything else I have done that made the required fields dissapear. The fields/labels do not show a \* (_asterisk_) anymore.

**Comment by Vincent-florajet** [comment]
Hi,

Please give me your entity class , the complete admin class and your orm file for this object before 

Thx

**Comment by jordisala1991** [comment]
We do not support sf 2.7 anymore
