### ISSUE TITLE
Wrong search results when using custom query (Followup)

### ISSUE THREAD

**Issue by soerenbernstein** [sonata-project/SonataAdminBundle#3160]
This is a followup on #2850.
I suggested a - rather dirty - fix for the problem, which was rejected for good reasons. So, I changed it to a not so dirty version, incorporating your suggestions. Now the PR is in 2 parts: 
- PR #2854: sonata-project/SonataAdminBundle Fixing #2850 - Part 1
- PR #441: sonata-project/SonataDoctrineORMAdminBundle Fixing #2850 - Part 2

Both of them were working the day I suggested them. Maybe, noone noticed the new PR but it would be nice if someone could decide, if they are accepted or rejected. Either way is fine for me.

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest master version? 

Feel free to close if you don't use this bundle anymore or the issue is fixed.

**Comment by soerenbernstein** [comment]
This issue still remains in SonataAdmin 3.4.

**Comment by soerenbernstein** [comment]
Ok, so obviously you don't care. And I you don't care, I don't care.
