### ISSUE TITLE
Flashbag on Admin class

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataAdminBundle#3167]
I propose, if possible, to add session flashbag on Admin service.

With this, we could add some flashes without overriding the whole controller action, like this:

```php
/**
 * {@inheritdoc}
 */
public function preRemove($object)
{
    if (false === $this->manager->doStuff()) {
        $this->getFlashBag()->add('warning', 'something wrong happened');
    }

    // Other stuff
}
```

What do you think? Ping @rande

**Comment by lucasgranberg** [comment]
Should this build on core flash messages?
https://sonata-project.org/bundles/core/master/doc/reference/flash_messages.html

**Comment by Soullivaneuh** [comment]
I think we can let user choice.

**Comment by Storke** [comment]
:+1:

**Comment by core23** [comment]
:-1: IMO an admin is only a definition class which has no concreate actions.

**Comment by OskarStark** [comment]
:-1: too
