### ISSUE TITLE
Throw error on missing needed route 

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#3168]
If you have this configuration:

``` php
/**
 * {@inheritdoc}
 */
protected function configureRoutes(RouteCollection $collection)
{
    $collection
        ->clearExcept(['list', 'edit'])
    ;
}

/**
 * {@inheritdoc}
 */
protected function configureListFields(ListMapper $list)
{
    $list
        ->add('id')
        ->add('_action', 'actions', [
            'actions' => [
                'edit'     => [],
                'delete'   => [],
            ],
        ])
    ;
}
```

The `delete` button will simply not appear because route does not exists.

But no error thrown. This could be confused on lose time for devs.

Would be better to throw an error instead.

Could be BC break as misconfiguration that works actually will not later.

I don't know if we can keep BC, I'll put it on next major instead.

**Comment by OskarStark** [comment]
i agree with you @Soullivaneuh 

i would throw an ```LogicException```then

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
