### ISSUE TITLE
Unable to set custom data in show action field

### ISSUE THREAD

**Issue by AntonioCS** [sonata-project/SonataAdminBundle#3171]
Hey,

I have a show page and I want to add a custom value.
I have tried doing what I did in other actions which is to add an array to the third parameter with the data key like so:

```php
    protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->add('name')                      
            ->add('dateEnd')
            ->add('example', null,
                array('data' => 'example value')
            )
        ;
    }
```

In the configureListFields action this works. I have injected custom values with the data attribute.

How is this suppose to work or is the data key ignored?

**Comment by balazscsaba2006** [comment]
Did you manage to solve this?
I'm having the same issue, it even ignores the query builder function, on the showMapper fields!

**Comment by AntonioCS** [comment]
@balazscsaba2006 There is no way to fix this. The show page will not read any data keys of the options array. (I believe that at the time the feature I was trying to add was dropped so I didn't have to worry about this).

**Comment by balazscsaba2006** [comment]
What I did is a workaround, and in any case it's ugly and should not be done like this, but unless Sonata actually gives a way to make custom queries in the show fields, we have no other choice.

I've set a public property in the ``Admin`` and in the ```php configureShowFields()``` I set that property like this:
```php
$repository = $this
    ->getConfigurationPool()
    ->getContainer()
    ->get('doctrine')
     ->getRepository('MyRepo:MyEntity');
$this->affiliate = $repository->getPartnerByOrderId($orderId);
```

Added a field to the ```php $showMapper``` object like this:
```php
$showMapper->add('affiliate', 'entity', [
    'label' => 'venue.bookings.list.affiliate.label',
    'template' => 'MyBundle:Admin:affiliate.html.twig'
])
```

Then in the template I accessed it like this:
```twig
{% block field %}
    {% if admin.affiliate is not empty %}
        {{ admin.affiliate.label }}
    {% endif %}
{% endblock field %}
```

I hope this helps anyone.

**Comment by LouWii** [comment]
I'm sorry to answer an old post, but I'm wondering if such feature is supposed to be added at some point ?

**Comment by iBasit** [comment]
+1

**Comment by jordisala1991** [comment]
Can someone provide a PR to make this work? :)

**Comment by idchlife** [comment]
Hmmm... Guys, look at this: https://github.com/sonata-project/SonataAdminBundle/pull/4504

**Comment by BarraudLilian** [comment]
I might be mistake but IMO the topic #4504 has absolutely nothing to see with initial problem.
Initial problem consists in adding custom data to configureShowFields (i.e. an array of value that does not belong to entity's attributes), and what your topic is talking about is how to add custom template to a show field..

**Comment by kunicmarko20** [comment]
@BarraudLilian any chance you are able to provide a PR?

**Comment by BarraudLilian** [comment]
@kunicmarko20 (sorry i'm pretty new using this kind of stuff) I think i can't provide a PR because i'm working on my own private project and i just met the same problem as OP. Haven't found a solution yet.

**Comment by smilesrg** [comment]
>Is this still relevant?

Yes, in 2021.

**Comment by VincentLanglet** [comment]
I don't understand the issue. You can do basically what you want with a custom template for the field in the show view.

**Comment by smilesrg** [comment]
>You can do basically what you want with a custom template for the field in the show view.

How to pass custom data to the custom template?

**Comment by VincentLanglet** [comment]
> > You can do basically what you want with a custom template for the field in the show view.
> 
> How to pass custom data to the custom template?

I can write "Example data" in a template.
And when the data is dynamic, there is twig extension.

**Comment by smilesrg** [comment]
>And when the data is dynamic, there is twig extension.

I need to pass some custom entity that is not directly related to the current admin entity.  The custom entity is retrieved by some custom logic. Do you propose to write a Twig extension to query the custom entity from the template?

**Comment by smilesrg** [comment]
Anyone who still looks for a solution, I answered here https://stackoverflow.com/a/69740519/2051414
And just duplicate the answer here:

I used this solution. In the `configureShowFields()` method of an Admin class:

    $showMapper
            ->with('Tab Name')
            ->add(
                'any_name',
                null,
                [
                    'template' => 'Admin/Custom/any_name_show_template.html.twig',
                    'customData' => $this->someRepository->getSomeEntityBy($field),
                    'anotherCustomData' => $this->someService->getSomeDataBy($value),
                ]
            )
        ;

In the custom template, you can access custom data by `field_description.options.<customFieldName>`, so for provided example data accessors would be `{{ field_description.options.customData }}` and `{{  field_description.options.anotherCustomData }}`

For the shorter field name in the Twig template, you can do like this:

    {% set customData = field_description.options.customData %}

and access the custom data like `{{ customData }}`

Hope this helps and saves time.

**Comment by domis86** [comment]
@smilesrg your solution is good - but is missing one thing: 'any_name' field should not need to exist in the entity from Admin.
To achieve that **virtual_field** option ( docs: https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/cookbook/recipe_virtual_field/ ) should be added :

```
$showMapper
        ->with('Tab Name')
        ->add(
            'any_name',
            null,
            [
                'template' => 'Admin/Custom/any_name_show_template.html.twig',
                'customData' => $this->someRepository->getSomeEntityBy($field),
                'anotherCustomData' => $this->someService->getSomeDataBy($value),
                'virtual_field' => true,
            ]
        )
    ;
```

and template should look like this:

```
{% extends '@SonataAdmin/CRUD/base_show_field.html.twig' %}

{% block field%}
    blabla: {{ field_description.options.customData }}
{% endblock %}
```
