### ISSUE TITLE
Centralize association JavaScript

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#3173]
The JavaScript "edit___one_association_script.html.twig" and "edit___many_association_script.html.twig" in the different bundles (ORM, Mongo, PHPCR) are nearly the same and should be centralized at the AdminBundle. Maybe this could be integrated in the Admin.js file.
- [ ] Add association scripts to Admin.js in `AdminBundle`
- [ ] Remove inline scripts in [DoctrineORMAdminBundle](https://github.com/sonata-project/SonataDoctrineORMAdminBundle) 
- [ ] Remove inline scripts in [PhpcrAdminBundle](https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle) 
- [ ] Remove inline scripts in [DoctrineMongoDBAdminBundle](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle)

**Comment by jordisala1991** [comment]
I think this is already done. All templates from relations are deprecated on all bundles. Closing. Reopen if I am wrong
