### ISSUE TITLE
Missing label on breadcrumb menu when using custom action in CRUDController

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3174]
I have created a custom `show` action (`inspection_results`) and route inside my `ContractAdminController`.

```php
class ContractAdmin extends Admin
{
    protected function configureRoutes(RouteCollection $collection)
    {
        $collection
            ->remove('delete')
            ->remove('export')
        ;

        $collection->add('inspection_results', $this->getRouterIdParameter().'/inspection_results');
    }
}
```

Technically everything works fine so far!

The I recognized that my breadcrumb menu was missing the label for my `Contract` entity. Instead it was directely showing the menu label `Ergebniszusammenstellung` for my action:
![bildschirmfoto vom 2015-08-14 10 37 15](https://cloud.githubusercontent.com/assets/3479626/9270201/0fcc57ec-4270-11e5-8c9e-ef4e41805a28.png)

Looking at the `showAction` of the `CRUDController` I add the `setSubject` method:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Controller/CRUDController.php#L843

Now the label for my `Contract` entity appears:
![bildschirmfoto vom 2015-08-14 10 40 09](https://cloud.githubusercontent.com/assets/3479626/9270249/773c5d00-4270-11e5-8277-8b5fbae6112b.png)

But as you can see now the label of the action `Ergebniszusammenstellung` is missing at the final position.

Is there another variable I have to pass to the template?
```php
            return $this->render('AppBundle:ContractAdmin:inspection_results.html.twig', array(
                'action'                         => 'inspection_results',
//                'action'                         => 'show',
                'object'                         => $contract
            ));
```

Possibly related:
* https://github.com/sonata-project/SonataAdminBundle/pull/1436#issuecomment-20334259

**Comment by core23** [comment]
This issue should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue
