### ISSUE TITLE
Using filtering in 'sonata_type_model_list' list popup

### ISSUE THREAD

**Issue by pauliuspalevicius** [sonata-project/SonataAdminBundle#3175]
When pressing "Filters" in 'sonata_type_model_list' list popup a parent form is being loaded in a popup window.

symfony/symfony                          v2.7.3             The Symfony PHP framework
sonata-project/admin-bundle              dev-master 5107cdb Symfony SonataAdminBundle

```php
        $formMapper
            ->with('General')
                ->add('customer', 'sonata_type_model_list', array('required' => false))
                ....
            ->end()
        ;
```

**Comment by pauliuspalevicius** [comment]
I had an old version of other packages.

**Comment by ademellopthealth** [comment]
@pauliuspalevicius can you let me know which packages were out of date? I am experiencing the same issue.

**Comment by kwuerl** [comment]
+1
