### ISSUE TITLE
Not saving

### ISSUE THREAD

**Issue by blackstarek** [sonata-project/SonataAdminBundle#3178]
Hey guys, 

When i create my admin class with custom choices, but its not saved afterwards ...

    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('date', 'sonata_type_date_picker', array(
                'dp_use_current' => true,
                'label' => 'Datum',
                'format' => 'dd/MM/yyyy',
                'auto_initialize' => true,
                'dp_language' => 'cs'
            ));
        $entity = new \AppBundle\Entity\Course();
        $categories = $this->modelManager->getEntityManager($entity)->createQuery('SELECT DISTINCT IDENTITY(s.category) FROM AppBundle\Entity\Course s')->getResult();

        $categoryEntity = new \AppBundle\Entity\Category();
        foreach ($categories as $categoryid) {
            $categoryid = $categoryid[1];

        $category = $this->modelManager->getEntityManager($categoryEntity)->createQuery('SELECT DISTINCT s FROM AppBundle\Entity\Category s WHERE s.id = '.$categoryid)->getResult();
            $catName = $category[0]->getName();
            $choices = $this->getCategoryCourses($categoryid);
            $formMapper->add($categoryid, 'choice', array(
                'mapped' => false,
                'required' => false,
                'choices' => $choices,
                'by_reference' => false,
                'choices_as_values' => true,
                'multiple' => true,
                'expanded' => true,
                'label' => $catName,
                'choice_label' => 'Course',
                'attr' => array('class' => 'collapsable'),
            ));
        }

    }

I want the Choice to be all saved into my entity LunchMenu , along with the Date

**Comment by pulzarraider** [comment]
A form field with option [`'mapped' => false`](http://symfony.com/doc/current/reference/forms/types/form.html#mapped) is not stored in entity (and in the database). If you want to store the value, you have to remove this option or set it to `true`.

**Comment by blackstarek** [comment]
Yea, the problem is, i have one field for Courses in the LunchMenuEtity, But I need to render it by category like this and then next to each of the checkboxes I need to render the Price input, which would display after clicking on the checkbox. The Price is in the Courses Entity and this is Admin For LunchMenuEntity. So The stuff i need is, In the LunchMenu Admin, Have All the choices from Course Entity, grouped by Course Category and have Course.price next to each of them when checkbox clicked (the course.price input should have the price in DB pre-setted if not null) and then click save and Save the Chechkboxes into Entity LunchMenu Which contains field courses that is many-to-many relation and price into Courses for each Course

**Comment by pulzarraider** [comment]
Your requirements are quite complex. You can solve your problem with creating [custom form field type](http://symfony.com/doc/current/cookbook/form/create_custom_field_type.html) or by storing your fields manually [using the saving hooks](https://sonata-project.org/bundles/admin/master/doc/reference/saving_hooks.html#saving-hooks).
