### ISSUE TITLE
How to Remove pagination

### ISSUE THREAD

**Issue by blackstarek** [sonata-project/SonataAdminBundle#3180]
I want to have Full list of records in every list action. 

Is there a simple way to have full list auto appear or do I have to override DataGrid Pager.php? 

UPDATE: Tried to add this into my admin class:

    protected $datagridValues = array(
        '_sort_order' => 'ASC', // reverse order (default = 'ASC')
        '_sort_by' => 'category',  // name of the ordered field
        '_per_page' => 200
    );

    // Fields to be shown on filter forms
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        
        $datagridMapper
            ->add('name',null,array('label' => 'Název'))
            ->add('category', null, array('label' => 'Druh Jídla'))

        ;
    }

    protected $datagridValues = array(
        '_sort_order' => 'ASC', // reverse order (default = 'ASC')
        '_sort_by' => 'category',  // name of the ordered field
        '_per_page' => 200
    );

    // Fields to be shown on filter forms
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        
        $datagridMapper
            ->add('name',null,array('label' => 'Název'))
            ->add('category', null, array('label' => 'Druh Jídla'))

        ;
    }

But it's not working and it doesnt even sort by category :/

**Comment by pulzarraider** [comment]
Setting '`_per_page`' will not work because [it's reset with $maxPerPage in the __construct](https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Admin.php#L604). Please try to set the $maxPerPage property in your admin class (or call the `setMaxPerPage`).

**Comment by blackstarek** [comment]
And why does the sort by not work? Is it possible to have contact info on you, since you are from SK, it will be much easier for me to ask questions in Czech than in eng.

**Comment by pulzarraider** [comment]
If your field `category` contains the `Category` entity (foreign key), the sorting is not enabled by default. You have to activate it manually and specify the field from Category entity on which the sorting should be done (e.g. category's title).

E.g.:
```
$listMapper->add('category', null, array(
    'sortable' => true, 
     'label' => $this->trans('food_type'),
     'sort_field_mapping'=> array('fieldName'=>'title'), // title is available in the Category entity
      'sort_parent_association_mappings' => array(array('fieldName'=>'category')),
));
```

**Comment by pulzarraider** [comment]
I like writing about the problems in english so if someone else will have the same problem, he will find the answer much easier :)

**Comment by blackstarek** [comment]
Sure, but I dont want to create thousand threads on git cause I'm trying to get this stuff done but im kinda new in symfony & Sonata

**Comment by blackstarek** [comment]
BTW thank you, works like a charm :] I would like to have more questions :D Maybe some more detailed

**Comment by pulzarraider** [comment]
I am glad I helped you. Feel free to ask more questions, but I think you should try to use the [Google Groups](https://github.com/sonata-project/SonataAdminBundle#documentation) first. Github issues are here for reporting bugs and requesting new features.

**Comment by stefanbranic** [comment]
If anyone encounters this problem in sonata 3.x and wants to have full list try with this:

protected $maxPerPage = 'All';

**Comment by hefbs** [comment]
If anyone encounters this problem in sonata 3.x and wants to have full list try with this:

protected $maxPerPage = 'All';
