### ISSUE TITLE
AutoCheck Checkboxes in List

### ISSUE THREAD

**Issue by blackstarek** [sonata-project/SonataAdminBundle#3181]
How can I set some checkboxes in List to be checked based on Another Entity Type?

E.g. I have a batch action addSelectedToMenu , which adds Selected Records into another Entity. How do I make theese ones checked everytime I visit the list? 

I'm new to Sonata so I would probably need more detailed answer.

**Comment by pulzarraider** [comment]
The checkboxes in the list are here for batch actions. It's up to the user to select which items he need to delete or run on them another selected batch action.

To select some of the checkboxes, you can create your own javascript function, that will do the job for you.
