### ISSUE TITLE
Issue with sonata_type_collection

### ISSUE THREAD

**Issue by marvoh** [sonata-project/SonataAdminBundle#3185]
I have included a related model in my admin as follows

    ->add('parameters', 'sonata_type_collection', array(
                'type_options' => array(
                    // Prevents the "Delete" option from being displayed
                    'delete' => false,
                     )
            ), array(
                'edit' => 'inline',
                'inline' => 'table',
                'sortable' => 'position',
            ))

The child admin is included and I can add a new row. However, when I try to add a second child, I get the following error:

    PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "NULL" while trying to traverse path "parameters[0]" at property "0". 

I cannot explain what is happening, I am using symfony 2.7.3 and using dev-master branch of Admin bundle.
I don't know whether this has been reported, I have tried to check in the issues list but haven't seen it

**Comment by marvoh** [comment]
This has been solved by an update

**Comment by OskarStark** [comment]
@marvoh can you please close this issue then?
