### ISSUE TITLE
Sonata reload Controller another logic in action

### ISSUE THREAD

**Issue by shubaivan** [sonata-project/SonataAdminBundle#3188]
I install Sonata admin Bundle, create controller extends Admin. In another controller for image I use 

            $url = sprintf(
            '%s%s',
            $this->container->getParameter('acme_storage.amazon_s3.base_url'),
            $this->getPhotoUploader()->upload($request->files->get('file'))
        );

        $user->setImage($url);
 But in Sonta I can do create service and controller with configureFormFields, configureDatagridFilters,configureListFields
Early I crate form and after form if form is valid in action I use my custom loagic, how in controller extends Admin and use configureFormFields, I can do use my custom service for download Image for Amazon S3?
this is my controller extends Admin where action for download image and set in Entity ?? I want another logic but dont know how do this ( Help

    class DeveloperAdmin extends Admin
    {
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper

            ->add('firstName', null, array('label' => 'Developer\'s First Name', 'max_length' => 255))
            ->add('lastName', null, array('label' => 'Developer\'s Last Name', 'max_length' => 255))
            ->add('qualification', 'choice', array('label' => 'Speciality',
                'choices' => array('Frontend' => 'Frontend', 'Backend' => 'Backend', 'Full stack' => 'Full stack'),'attr'=> array('class'=>'qualif'), 'required' => false))
            ->add('level', 'choice', array('label' => 'Professional Level', 'max_length' => 255,
                'choices' => array('Junior' => 'Junior', 'Middle' => 'Middle', 'Senior' => 'Senior')))
            ->add('tags', 'tags', array('label' => 'Tags','required' => false))
            ->add('main_skill', 'mainSkill', array('label' => 'Main Skill', 'required' => true, 'mapped' => true, 'attr' => array('placeholder' => 'Select your skills ...', 'class'=>'main_skill') ))
            ->add('skills', 'skills', array('label' => 'Skills','required' => false))
            ->add('english', 'choice', array('label' => 'English Level', 'max_length' => 255,
                'choices' => array('Basic' => 'Basic', 'Intermediate' => 'Intermediate', 'Advanced' => 'Advanced')))
            ->add('rate', null, array('label' => 'Rate $/h', 'max_length' => 255));
            ->add('image', 'file')
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('username')
            ->add('firstName')
            ->add('lastName')
            ->add('main_skill')
            ->add('skills', 'skills', array('label' => 'Skills','required' => false))
            ->add('level')
            ->add('rate')
            ->add('english')
            ->add('email')
            ->add('location')
            ->add('country')
            ->add('image')
            ->add('tags')
            ->add('created', 'doctrine_orm_date_range', array('field_type'=>'sonata_type_date_range_picker',))
        ;
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('id')
            ->add('username')
            ->add('firstName')
            ->add('lastName')
            ->add('main_skill')
            ->add('skills')
            ->add('level')
            ->add('rate')
            ->add('english')
            ->add('email')
            ->add('location')
            ->add('country')
            ->add('created')
            ->add('image', 'string', array('template' => 'SonataMediaBundle:MediaAdmin:list_image.html.twig'))

            ->add('_action', 'actions', array(
                'actions' => array(
                    'show' => array(),
                    'edit' => array(),
                )
            ))
        ;
    }

}

**Comment by pulzarraider** [comment]
You can use  every Symfony form field type in `configureFormFields`.
If you want to improve the `file` field type, try to serach for already existed form field types in [Symfony's bundles](http://knpbundles.com/) or create your own [form field type](http://symfony.com/doc/current/cookbook/form/create_custom_field_type.html).

**Comment by shubaivan** [comment]
I use SonataAdmin bundle for admin panel and knp-gaufrette-bundle and I want if I upload file in sonata form add, file upload for amazon, thats all, how to reload sonata action and add in this action my logic??
