### ISSUE TITLE
Sonata use custom service in form

### ISSUE THREAD

**Issue by shubaivan** [sonata-project/SonataAdminBundle#3189]
I install Sonata admin Bundle, create controller extends Admin and in configureFormFields I use service tags, skills, choice and this is good and work, but in configureListFields this is not work and I have 

    [0 => web design] [1 => Java] [2 => Eclipse] [3 => Backbone.js] [4 => Nginx] [5 => F#] [6 => Apache] [7 => CoffeeScript] [8 => Cocoa] 
this is not good
In filter I want find developer more one skill how can do this ? Because I try use 

     ->add('skills', 'skills', array('label' => 'Skills','required' => false))
and I have error

    No attached service to type named `skills` 
how fix this and maybe another way

 - in controller I have:

        class DeveloperAdmin extends Admin
        {
        protected function configureFormFields(FormMapper $formMapper)
        {
        $formMapper

            ->add('firstName', null, array('label' => 'Developer\'s First Name', 'max_length' => 255))
            ->add('lastName', null, array('label' => 'Developer\'s Last Name', 'max_length' => 255))
            ->add('qualification', 'choice', array('label' => 'Speciality',
                'choices' => array('Frontend' => 'Frontend', 'Backend' => 'Backend', 'Full stack' => 'Full stack'),'attr'=> array('class'=>'qualif'), 'required' => false))
            ->add('level', 'choice', array('label' => 'Professional Level', 'max_length' => 255,
                'choices' => array('Junior' => 'Junior', 'Middle' => 'Middle', 'Senior' => 'Senior')))
            ->add('tags', 'tags', array('label' => 'Tags','required' => false))
            ->add('main_skill', 'mainSkill', array('label' => 'Main Skill', 'required' => true, 'mapped' => true, 'attr' => array('placeholder' => 'Select your skills ...', 'class'=>'main_skill') ))
            ->add('skills', 'skills', array('label' => 'Skills','required' => false))
            ->add('english', 'choice', array('label' => 'English Level', 'max_length' => 255,
                'choices' => array('Basic' => 'Basic', 'Intermediate' => 'Intermediate', 'Advanced' => 'Advanced')))
            ->add('rate', null, array('label' => 'Rate $/h', 'max_length' => 255));

          }
        protected function configureDatagridFilters(DatagridMapper $datagridMapper)
          {
        $datagridMapper
            ->add('username')
            ->add('firstName')
            ->add('lastName')
            ->add('main_skill')
            ->add('skills', 'skills', array('label' => 'Skills','required' => false))
            ->add('level')
            ->add('rate')
            ->add('english')
            ->add('email')
            ->add('location')
            ->add('country')
            ->add('image')
            ->add('tags')
            ->add('created', 'doctrine_orm_date_range', array('field_type'=>'sonata_type_date_range_picker',))
        ;
          }

    
          protected function configureListFields(ListMapper $listMapper)
         { 
        $listMapper
            ->addIdentifier('id')
            ->add('username')
            ->add('firstName')
            ->add('lastName')
            ->add('main_skill')
            ->add('skills')
            ->add('level')
            ->add('rate')
            ->add('english')
            ->add('email')
            ->add('location')
            ->add('country')
            ->add('created')
            ->add('image', 'string', array('template' => 'SonataMediaBundle:MediaAdmin:list_image.html.twig'))
            ->add('_action', 'actions', array(
                'actions' => array(
                    'show' => array(),
                    'edit' => array(),
                )
              ))
             ;
            }

           }

**Comment by pulzarraider** [comment]
You have probably created the form type `skills`. That's ok for the edit form, but not enough for the datagrid. I don't know how you store the skills - it's many to many relation or some serialized field?

To use your form field as a datagrid filter, you have to create new datagrid filter service. You can look in the [DoctrineORMAdminBundle](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/tree/master/Filter) for inspiration.

If the skills are managed as many-to-many relation. Everything should work without your custom field types.

**Comment by pulzarraider** [comment]
Closing as there is no more feedback. @shubaivan If you will provide more informations for your problem, I will reopen the issue.
