### ISSUE TITLE
Sonata Admin, dependant child fields

### ISSUE THREAD

**Issue by robhunt3r** [sonata-project/SonataAdminBundle#3195]
I have three classes,

`OrderAdmin`,  `ProductAdmin`, `OrderHasEquipmentAdmin`.

`Order` needs to add a `Product` and `Equipment` related to that product into an intermediate table `OrderHasEquipment`.

I can add a new Product, but when I try to add an OrderHasEquipment, it shows every Equipment I have in my DB, I only want to show the equipment available for that product and append to that Order.

Relations are

**Order -> manyToOne  -> Product**

**Order -> oneToMany -> OrderHasEquipment** _(because I need an intermediate Entity to work with sonata admin `sonata_type_collection` and `sonata_type_model_list`)_

**Product -> manyToMany -> Equipment**

So, when creating/editing an `Order`, it shows up a choice list with `Product`s, I need a behaviour that when a `Product` is selected, `OrderHasEquipment` (that is a `sonata_type_collection` field with `sonata_type_model_list` inside because the intermediate entity), allow me to only add an `Equipment` item related to that `Product` selected.

Any way of doing this?

(StackOverflow related question) http://stackoverflow.com/questions/32222664/sonata-admin-dependant-child-fields

**Comment by jordisala1991** [comment]
To me it seems related to #3808 . Im trying to unify issues, and the other one has more comments.

Closing for now. If you think this is not related, please ping me to reopen.

**Comment by rollsappletree** [comment]
guys it would be a very must-have...

**Comment by core23** [comment]
If it's a must-have for you. Please create an updated issue and provide a PR :+1:
