### ISSUE TITLE
show boolean field template

### ISSUE THREAD

**Issue by gnorby88** [sonata-project/SonataAdminBundle#3202]
https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/show_boolean.html.twig#L17
https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/show_boolean.html.twig#L20
These classes does not exist in the Font Awesome 4.3. Replace with:
```
<i class="fa fa-check-circle-o"></i>
<i class="fa fa-ban"></i>
```

**Comment by OskarStark** [comment]
can you provide a PR?

**Comment by OskarStark** [comment]
@issue: this is correct!

**Comment by gnorby88** [comment]
Yet i don't know how to..
