### ISSUE TITLE
Field options for start and end on sonata_type_date_range_picker not working

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3205]
I try to set default dates in my start and end option with type `sonata_type_date_range_picker` with `dev-master`.

Looking at the `DateRangeType` class I started with setting the `field_options_start` directly. But it seems that the options have to included in the `field_options` array like this:
```php
        $dateStart = new \DateTime('now');
        $dateEnd   = clone $dateStart;

        $datagridMapper
            ->add('date', 'doctrine_orm_date_range', array(
                    'show_filter' => true,
                    #'field_type' => 'sonata_type_date_range_picker',
                    'field_type' => 'sonata_type_date_range',
                    'field_options' => array(
                        'field_options_start' => array(
                            'dp_default_date' => $dateStart
                        ),
                        'field_options_end' => array(
                            'dp_use_current' => true,
                            'dp_show_today' => true,
                            'dp_default_date' => $dateEnd->modify('+6 days')
                        )
                    )
                ))
```
https://github.com/sonata-project/SonataCoreBundle/blob/master/Form/Type/DateRangeType.php#L38-L50

But none of these settings have effect.

The following example is mentioned for *2.4.*:
* http://stackoverflow.com/questions/28688368/date-ranger-picker-in-sonata-admin-filters#29300385
which is also used in 
* https://github.com/sonata-project/SonataAdminBundle/issues/2863#issue-64759610
but corrected to my example here:
* https://github.com/sonata-project/SonataAdminBundle/issues/2863#issuecomment-98975565

What is the correct approach?

Related:
* https://github.com/sonata-project/SonataAdminBundle/issues/2148

**Comment by DevMaster112** [comment]
By adding `format('d.m.Y')` to `dp_default_date' => $dateStart` is working for me to set a default value to field_type `sonata_type_date_range_picker`:

```php
$datagridMapper
            ->add('date', 'doctrine_orm_date_range', array(
                    'show_filter' => true,
                    'field_type' => 'sonata_type_date_range_picker',
                    'field_options' => array(
                        'field_options_start' => array(
                            'dp_default_date' => $dateStart->format('d.m.Y')
                        ),
                        'field_options_end' => array(
                            'dp_use_current' => true,
                            'dp_show_today' => true,
                            'dp_default_date' => $dateEnd->modify('+6 days')->format('d.m.Y')
                        )
                    )
                ))
```

**Comment by webdevilopers** [comment]
Closing as this seems to be the official approach.
