### ISSUE TITLE
sonata_type_model_autocomplete no longer populated with current label

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3206]
In current `dev-master` the `sonata_type_model_autocomplete` no longer gets populated with the current value.

**The DB Queries are fired.**

Though the `hidden' input holds the ID. But with an empty`span` ang `html5validate` you can't re-send the form. You have to re-select the correct value.

Empty line *3*:
```html
<div id="s2id_s55e4152d16323_branch_autocomplete_input" class="select2-container form-control">
<a class="select2-choice" tabindex="-1" href="javascript:void(0)">
<span id="select2-chosen-1" class="select2-chosen"> </span>
<abbr class="select2-search-choice-close"></abbr>
<span class="select2-arrow" role="presentation">
<b role="presentation"></b>
</span>
</a>
<label class="select2-offscreen" for="s2id_autogen1"></label>
<input id="s2id_autogen1" class="select2-focusser select2-offscreen" type="text" role="button" aria-haspopup="true" aria-labelledby="select2-chosen-1">
<div class="select2-drop select2-display-none select2-with-searchbox">
<div class="select2-search">
<label class="select2-offscreen" for="s2id_autogen1_search"></label>
<input id="s2id_autogen1_search" class="select2-input" type="text" aria-autocomplete="list" aria-expanded="true" role="combobox" spellcheck="false" autocapitalize="off" autocorrect="off" autocomplete="off" aria-owns="select2-results-1" placeholder="">
</div>
<ul id="select2-results-1" class="select2-results" role="listbox"> </ul>
</div>
</div>
<input id="s55e4152d16323_branch_autocomplete_input" type="text" required="required" value="" tabindex="-1" title="" style="display: none;">
<div id="s55e4152d16323_branch_hidden_inputs_wrap">
<input type="hidden" value="35" name="s55e4152d16323[branch]">
</div>
```

Possibly related to changes in https://github.com/sonata-project/SonataAdminBundle/pull/2898 @pulzarraider  ?

**Comment by webdevilopers** [comment]
The PR `sergbass:autocomplete-customization` by @sergbass seems not to be merged yet.
I guess somebody else changed something. Can we get the latest working commit somehow @pulzarraider ?

**Comment by webdevilopers** [comment]
Do you remember any change to the `sonata_type_model_autocomplete` @Soullivaneuh ? I can at least tell that it used to work in my dev 14 days ago.

**Comment by webdevilopers** [comment]
I seem to get a similar JS error btw like @Skunkz in #3227  :
**ReferenceError: opts is not defined
...getPlaceholderOption();this.opts.element.val(e?e.val():""),this.selection.find("...**

![bildschirmfoto vom 2015-09-10 08 16 41](https://cloud.githubusercontent.com/assets/3479626/9781375/e23cbfa4-5793-11e5-8c5f-b039c847b548.png)

**Comment by webdevilopers** [comment]
Some changes were at least made to the twig templates by @Soullivaneuh and @Koc 13 days ago:
https://github.com/sonata-project/SonataAdminBundle/commits/master/Resources/views/Form/form_admin_fields.html.twig

Maybe they know more.

**Comment by Soullivaneuh** [comment]
@pulzarraider Did you find anything about it? We need to fix it before 2.4 stable.

**Comment by webdevilopers** [comment]
I wonder that nobody else recognized this issue though some people seem to test the autocompleter currently.

Can you confirm this issue, guys?
* https://github.com/sonata-project/SonataAdminBundle/issues/3230 @javiereguiluz 
* https://github.com/sonata-project/SonataAdminBundle/issues/3227 @Skunkz 
* https://github.com/sonata-project/SonataAdminBundle/issues/3164 @MM-Psiiirus 
* https://github.com/sonata-project/SonataAdminBundle/issues/3131 @nixoschu

**Comment by javiereguiluz** [comment]
@webdevilopers I confirm that I don't have the issue you mentioned, but the autocomplete doesn't work for me because of the other reported error.

**Comment by MM-Psiiirus** [comment]
I've dropped the usage because I already wasted to much time to get it work properly :/ 
Will have a look again if a new stable is out.

**Comment by Skunkz** [comment]
Hi,
Didn't check the component in a few days, but it seems to work fine now, wihtout any changes from my side.
Thanks !

**Comment by webdevilopers** [comment]
That means if you re-load your form with the autocompleter and try to edit the field the label / value is displayes and not missing @Skunkz ? Can you check that with current `dev-master`?

**Comment by joshlopes** [comment]
@webdevilopers well it still happens - i just updated my projects. The bug is still there.

**Comment by joshlopes** [comment]
In git history i can tell you that name was removed for no reason -- removing it will prompt this:

076d8cc	10/04/15 16:26	Chabot Vincent	Remove mal-formatted name for autocomplete type
before the commit:
![screen shot 2015-09-17 at 15 17 58](https://cloud.githubusercontent.com/assets/3440849/9935572/4afa750c-5d4f-11e5-8ce7-42f00d11aab8.png)
after the commit:
![screen shot 2015-09-17 at 15 18 42](https://cloud.githubusercontent.com/assets/3440849/9935591/6b0de824-5d4f-11e5-87fd-45795f7392f8.png)

Ofc this doesnt solve the problem but doesnt help either -- why it got removed anyway.

**Comment by joshlopes** [comment]
Update:

Change:
````
<input type="text" id="{{ id }}_autocomplete_input" value=""
        {%- if read_only %} readonly="readonly"{% endif -%}
        {%- if disabled %} disabled="disabled"{% endif -%}
        {%- if required %} required="required"{% endif %}
    />
````

To:
````
<select type="text" id="{{ id }}_autocomplete_input" name="{{ full_name }}_autocomplete_input"
            {%- if read_only %} readonly="readonly"{% endif -%}
            {%- if disabled %} disabled="disabled"{% endif -%}
            {%- if required %} required="required"{% endif %}
            />
            {% if value is not empty %}
                <option value="{{ value[0] }}">{{ value['_labels'][0] }}</option>
            {% endif %}
    </select>
````

and there you have -- its working again , for me at least.

**Comment by webdevilopers** [comment]
Thanks for confirming the bug and providing the solution:
* https://github.com/sonata-project/SonataAdminBundle/pull/3261

Really happy about this and just wanna say thank you guys for the awesome work!

**Comment by joshlopes** [comment]
I am sorry @webdevilopers i made a mistake, if you use selectbox you cant use multiple nor ajax which is what we use on Sonata, on a second look i realize that what was breaking was some select2 opts var not being init. I set a global one on windows and that solved the issue. 

PR has also been updated. I removed my last solution! Please use this one instead, rollback to the old version if you already made the changes.

Thanks

**Comment by pulzarraider** [comment]
Fixed with sonata-project/SonataCoreBundle#189. Thank you for reporting the problem.

**Comment by Soullivaneuh** [comment]
@pulzarraider A new fix tag should be out with a minimum requirement on admin-bundle.

**Comment by pulzarraider** [comment]
@Soullivaneuh can you take care of it?

**Comment by Soullivaneuh** [comment]
I'll take a look.

**Comment by pulzarraider** [comment]
Thank you.

**Comment by Soullivaneuh** [comment]
@pulzarraider done https://github.com/sonata-project/SonataAdminBundle/commit/5039c70e2b524deb69c8c8d3cf153105e5ff6813.
