### ISSUE TITLE
User right MASTER can't give VIEW right

### ISSUE THREAD

**Issue by samuel4x4** [sonata-project/SonataAdminBundle#3209]
Hello,

I'm using ACL with Sonata Admin 2.3.5. I'm logged in with an user that have MASTER right on an object. I open the ACL editor and I check VIEW right for another user. When I save I receive this:

Attempted to call an undefined method named "getOwnerPermissions" of class "Sonata\AdminBundle\Util\AdminObjectAclData".
Did you mean to call e.g. "getPermissions" or "getUserPermissions"?

https://github.com/sonata-project/SonataAdminBundle/blob/2.3.5/Util/AdminObjectAclManipulator.php line 119

If the MASTER user is OWNER, there's no problem but I want for him to stay MASTER not OWNER in order to not be allowed to see other OWNER users. By the way, what officially MASTER can do?

Thanks a lot!

**Comment by ipalo** [comment]
+1
Same problem here: https://github.com/sonata-project/SonataAdminBundle/issues/2349
