### ISSUE TITLE
Adding symfony 'button' form type to FormMapper raises Exception

### ISSUE THREAD

**Issue by ghost** [sonata-project/SonataAdminBundle#3217]
The following code in an Admin class

```
protected function configureFormFields(FormMapper $formMapper)
{
    $formMapper->add('myButton', 'button');
}
```

throws this error:

```
The options "label_render", "sonata_field_description" do not exist. Defined options are: "attr", "auto_initialize", "block_name", "disabled", "label", "label_format", "translation_domain".
```

Doesn't seem to matter what options you specify

**Comment by core23** [comment]
What should this button do?

**Comment by aaronkmiller** [comment]
I would expect it to create a [ButtonType field](http://symfony.com/doc/current/reference/forms/types/button.html)

**Comment by ejkun** [comment]
Same error with Sonata 3.23.0
I'm trying to create a ButtonType field and I'm getting this

The options "label_render", "property_path", "sonata_field_description" do not exist. Defined options are: "attr", "auto_initialize", "block_name", "disabled", "label", "label_format", "translation_domain"

**Comment by core23** [comment]
AFAIK we don't support unmapped form fields. Maybe someone could create a PR with this feature?

**Comment by lopezator** [comment]
It would be nice to support this feature. It's confusing that you can use some Symfony FormTypes and some not, mapped or not.
