### ISSUE TITLE
Undefined variable: subject

### ISSUE THREAD

**Issue by morgangiraud** [sonata-project/SonataAdminBundle#3220]
Hello @Soullivaneuh ,

Here is my error : 
`Undefined variable: subject in admin-bundle/Form/Type/AdminType.php line 74`

Here is the merged the P.R. which created it:
#3128 

I've been trying to understand if it comes from my code or yours but i seriously have no real clues on this.  Here is what i know : 
 - php 5.4.44
 - symfony 2.3.30
 - sonate-core 2.3.8

If i set the subject in all case like this : 
```php
Form\Type\AdminType:64
if ($subjectCollection instanceof Collection) {
       $subject = $subjectCollection->get(trim($options['property_path'], '[]'));
} else {
      $subject = $subjectCollection;
}
```
everything works like a charm again.

Finally, here is the P.R. i made : #3219

P.S. The P.R. 3128 actually fix an other bug i had in some other depedencies which is really welcome.

**Comment by Soullivaneuh** [comment]
What is the type of `$subject` in your case?

**Comment by morgangiraud** [comment]
For example : 
```php
* @var ...Model\FirstViewInterface
     *
     * @ORM\OneToOne(targetEntity="...Model\FirstViewInterface", inversedBy="offer", cascade={"all"})
     *
     * @Assert\Valid()
     */
    protected $firstView;
```

But it happens on a every other OneToOne relation of this entity.

**Comment by greg0ire** [comment]
Please reopen if still relevant for Sonata 3.
