### ISSUE TITLE
How can i create a custom breadcrumb

### ISSUE THREAD

**Issue by torst** [sonata-project/SonataAdminBundle#3221]
my current breadcrumb for exemple is Dashboard / Company / Departments.

and i want to add something to be like this 

Dashboard / Company / My /Departments
-----------------------

second problem that i want to render a custom navbar title if is empty

Best regards

**Comment by ejkun** [comment]
As far as I know, you will have to rewrite the buildBreadcrumbs function. You can find it in the Admin class.

**Comment by greg0ire** [comment]
It's now a separate service, you may inject another one in the admin class if needed.

**Comment by zhil** [comment]
@greg0ire not any more, it would be nice to have ablitity to customize breadcrumbs
