### ISSUE TITLE
ListMapper should throw an error when trying to access a non-existing template

### ISSUE THREAD

**Issue by michaelkonecny** [sonata-project/SonataAdminBundle#3222]
If I do this:

    // Fields to be shown on lists
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('property', null, array(
                'template' => 'MyBundle:Admin:template_which_wont_be_found.hmtl.twig',
            ))
        ;
    }

the ListMapper doesn't throw an error, but instead uses the default template for this property type.

This can really complicate debugging, because if one makes a typo in the template name (like 'hmtl' instead of 'html'), it's very hard to understand why there are errors coming from 'base_list_field.html.twig' template instead of the one they intended to include.

ListMapper should instead throw something like: 

    Error: The template MyBundle:Admin:template_which_wont_be_found.hmtl.twig couldn't be found.

**Comment by OskarStark** [comment]
:+1:  great idea

**Comment by torst** [comment]
i think that you should specify type to throw an exception.
not sure :p

**Comment by greg0ire** [comment]
I think I fixed exactly this recently, see #3704
