### ISSUE TITLE
Objects of EmbedMany get deleted

### ISSUE THREAD

**Issue by MHaendel** [sonata-project/SonataAdminBundle#3224]
Hi,

if I do EmbedMany instead of ReferenceMany with mongodb odm, "old" items of the collection get's deleted. In the log panel of the profiler, I can see the pushAll command, after this query, there comes the delete query.

I use sonata_type_model formtype. The first time I add items to the collection, everything works fine. The second time I add items, the old ones get deleted and just the new one is in the collection.

**Comment by core23** [comment]
This issue should be opened in https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle
