### ISSUE TITLE
Flash message does not render the name of handled entity

### ISSUE THREAD

**Issue by sylzys** [sonata-project/SonataAdminBundle#3228]
First, thanks for the great job !

I use the admin bundle, and followed the docs to create admin classes for my entities, they're now displayed in the dashboard and menu, and I can create / edit them.

I'm facing a slight problem though: when I create an entity, the flash message does not render

> Item "FooBar" has been successfully created.

But 

> Item "CouponsBundle\Entity\Company:000000007851fdde000000010739fe91" has been successfully created. 

Same goes with the breadcrumb, which display for instance

>  Dashboard / Company List / CouponsBundle\Entity\Company:000000007934e1080000000129391fb3 

I really have no idea where to dig... Thanks

**Comment by sylzys** [comment]
The same problem appears when I create an entity.

I got a "Company" entity, which has a OneToOne relationship with a "Contact" entity.
When I create the contact, here's what appears in the form. The same appears when creating and when editing.

Cache has been cleared :/

![capture d ecran 2015-09-08 a 09 51 27](https://cloud.githubusercontent.com/assets/1545358/9729400/750858ce-560f-11e5-9e29-19cd17570a5f.png)

**Comment by rande** [comment]
You need to either overwrite the toString method from the admin class or set a __toString method in your entities.

**Comment by sylzys** [comment]
So obvious now that you say it :'(

Thanks !

**Comment by AlexL5** [comment]
You need to overwrite __toString()  in your entity
