### ISSUE TITLE
Issue with sonata_type_model_autocomplete

### ISSUE THREAD

**Issue by javiereguiluz** [sonata-project/SonataAdminBundle#3230]
I'm trying to use the [sonata_type_model_autocomplete](https://sonata-project.org/bundles/admin/master/doc/reference/form_types.html#sonata-type-model-autocomplete) in a Symfony app which uses SonataAdmin 2.3.5.

I've configured the field as follows:

```php
->add('user', 'sonata_type_model_autocomplete', array(
    'property' => array('name'),
    'attr' => array('style' => 'width: 100%'),
))
```

The autocompleting part works perfectly. I can type anything and the appropriate values appear on the list and I can select them.

However, when I click on the save button, I see the following error:

```
Argument 1 passed to $post->setUser() must be an instance of ...\...\...\User, null given.
```

I think I followed all the steps explained in the documentation, and the `name` property is indeed a text filter of the related UserAdmin class.

**Comment by rande** [comment]
I think @pulzarraider can help you on this. Can you check in the $_POST if the user's id is set ? can be a js issue.

**Comment by rande** [comment]
Also you might try to do ``function setUser(User $user = null)`` as the form can set the user in a second pass with event ...

**Comment by javiereguiluz** [comment]
This is the `$_POST` data sent for the user field:

```
user => [ title => 31828, identifiers => [ 0 => , 1 => 31828 ] ]
```

**Comment by torst** [comment]
hey @javiereguiluz i think that you should use prePersist function to parse User instance to the function $post->setUsser();

there is any relationship between User and Post ?

**Comment by javiereguiluz** [comment]
@torst I have the following relationship configured:

```php
/**
 * @ORM\ManyToOne(targetEntity="...\...\...Bundle\Entity\User")
 */
private $user;
```

> I think that you should use prePersist function to parse User instance to the function $post->setUsser();

Where can I find more information about this? Thanks!

**Comment by torst** [comment]
this how should looks like
in your formmapper add this options
            'minimum_input_length' => 1,
            'multiple' => false,


in your  prePersist function use it like this

 public function prePersist($project)
  {
    $uniqid = $this->getRequest()->query->get('uniqid');
    $formData = $this->getRequest()->request->get($uniqid);
    $userid = $formData['user'];
    $em = $this->getConfigurationPool()->getContainer()->get('doctrine')->getManager();
    $user= $em->getRepository('Compnay_yourBundle:User')->find((int)$userid);
    $project->setUser($user);
  }


like this should be work.

**Comment by javiereguiluz** [comment]
@torst thanks a lot for your help. Your suggestion "almost" worked. First I had to make some changes in the entity code and then, I changed the following line:

```php
$userid = $formData['user'];
```

by the following:

```php
$userId = $formData['user']['identifiers'][0];
```

I know that this is super-weird, but look what I get when I `dump()` the `$formData['user']` in `preUpdate()`:

![sonata_dump](https://cloud.githubusercontent.com/assets/73419/9737470/1bbd861c-5647-11e5-817e-a7760cc69a94.png)

Is this `title` + `identifiers` normal or I'm doing something wrong?

**Comment by pulzarraider** [comment]
@javiereguiluz can you please try the current `master` version of SonataAdmin (with latest SonataDoctrineORMAdmin and SonataCoreBundle)? The `sonata_type_model_autocomplete` were  refactored with some issues fixed and with additional functionality added.

**Comment by javiereguiluz** [comment]
Closing it as fixed. Using the current `master` version fixed the issue. Thank you all for the help!
