### ISSUE TITLE
Improve templates for overriding list_filters

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3232]
I have a custom action in a `CRUDController`. The `url` of the filter form is routing the `list` action by default.
But I need to redirect to my custom action.

Currently you have to override the complete `list_filters` block to achieve this.
https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/base_list.html.twig#L228-L305

Though you only need to change a single line:
```twig
{{ admin.generateUrl('list') }}
```
See: https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/base_list.html.twig#L235

I have found no way to change the action on the form inside my controller. Only some datagrid related methods:
```php
        $datagrid = $this->admin->getDatagrid();
        $formView = $datagrid->getForm()->createView();

        // set the theme for the current Admin Form
        $this->get('twig')->getExtension('form')->renderer->setTheme($formView, $this->admin->getFilterTheme());
```

Maybe some additional blocks or a `getFilterForm()` method would improve overriding?

**Comment by core23** [comment]
Closing this in favor of https://github.com/sonata-project/SonataAdminBundle/issues/4050
