### ISSUE TITLE
Cannot get value from doctrine_orm_time filter with mapped set to false

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3236]
I have a `doctrine_orm_time` filter `night_shift_start` that is not mapped to my `TimekeepingEntry` admin:

``` php
$datagridMapper
            ->add('night_shift_start', 'doctrine_orm_time', array(
                'show_filter' => true,
                'field_options' => array(
                    'hours' => array(20, 22),
                    'with_minutes' => false,
                    'mapped' => false
                )
            ))
```

After setting the filter to a value and submitting I'm getting the following dump on the filter data in my custom CRUDController:

``` php
$datagrid = $this->admin->getDatagrid();
$datagridFilters = $datagrid->getFilters();
dump($datagridFilters);
```

![bildschirmfoto vom 2015-09-09 13 45 28](https://cloud.githubusercontent.com/assets/3479626/9760810/a6ebcc4c-56f8-11e5-9fe8-e913bea97f88.png)

As you can see the `value` index is not set and since then not available with:

``` php
echo $datagridFilters['night_shift_start']->getValue()['value'];
```

This seems to be caused by the `mapped` option. Setting the option to `true` and dumping without(!) submitting will show the expected format:
![bildschirmfoto vom 2015-09-09 13 49 11](https://cloud.githubusercontent.com/assets/3479626/9760876/28ee25c8-56f9-11e5-83ef-12b4ba5a8355.png)

Submitting the filter is not possible:
**TimekeepingEntry has no field or association named night_shift_start**

Any idea how to solve this?

BTW: why does the `mapped` option have to be set on the `field_options` and not the general third parameter array?

**Comment by webdevilopers** [comment]
I tried the following solution as workaround:
```php
$nightShiftStart = $datagrid->getForm()->get('night_shift_start')->getData();
```
Seen on: http://stackoverflow.com/questions/20440836/sonata-admin-how-to-read-not-mapped-field

But the `value` will again be empty.

The only quick workaround I found:
```php
$nightShiftStart = $request->get('filter')['night_shift_start']['value']['hour'];
```

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.

**Comment by webdevilopers** [comment]
Sorry, but I'm no longer working on this project.
