### ISSUE TITLE
remove group does not remove assigned roles

### ISSUE THREAD

**Issue by remoteclient** [sonata-project/SonataAdminBundle#3239]
I use Sonata admin and user bundle in combination with fos user bundle.

For convenience I group different roles to groups and assign them to users. I think sonata just take the roles from the groups and assign them to the users.

When I remove one group from a user the group gets removed but the containing roles are assigned to the user furthermore.

The expected behavior should be that all roles which are in this removed group and are not present in other groups which are assigned to the user are removed from the user.

**Comment by pulzarraider** [comment]
Seems that this issue is related to SonataUserBundle, not the SonataAdminBundle. Please repoort it to the [SonataUserBundle](https://github.com/sonata-project/SonataUserBundle).
