### ISSUE TITLE
Can't set default value / data on doctrine_orm_date_range / sonata_type_date_range_picker

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3245]
I tried `data` and `dp_default_date` without success:

``` php
        $datagridMapper
            ->add('date', 'doctrine_orm_date_range', array(
                    'show_filter' => true,
                    'field_type' => 'sonata_type_date_range_picker',
                    'field_options' => array(
                        'field_options_start' => array(
                            'dp_default_date' => new \DateTime('now'),
                            'data' => new \DateTime('now'),
                        ),
                        'field_options_end' => array(
                            'dp_use_current' => true,
                            'dp_show_today' => true,
                            'dp_default_date' => new \DateTime('now'),
                            'data' => new \DateTime('now'),
                        )
                    )
                ))
```

Related to datepicker options:
- https://github.com/sonata-project/SonataCoreBundle/pull/149 @nlzet 

Came from:
- https://github.com/sonata-project/SonataAdminBundle/pull/842

**Comment by nlzet** [comment]
Note: the WIP of me you referenced is about a whole new version of the eonasdan plugin, and probably behaves differently than the current version.

**Comment by fadoe** [comment]
I have the same problem. Is there any solution after 2 years?

**Comment by webdevilopers** [comment]
Not here, sorry! I must confess I'm no longer using most of these features.

**Comment by webdevilopers** [comment]
@nlzet Do you know if anything happened - did the new version implement it?
Maybe I should close this issue anyway?

**Comment by nlzet** [comment]
@webdevilopers My PR was based on a completely new version of the plugin, and seemed incompatible with the current behaviour.

Unfortunately I do not have an idea how to do this either

**Comment by fadoe** [comment]
Can everyone explain how I can debug this? I have no idea how the configuration came from the Admin class to the form. And where can I fin the place where the form is rendered to the template?

**Comment by Renrhaf** [comment]
Same issue on version 3.35.2

**Comment by webdevilopers** [comment]
I explained to @core23 on Twitter that I no longer maintain the projects that use Sonata.
I will try to comment on the issues anyway. I will close them if nobody else suggested a PR or similar.

There have been some proposals for this issue. From my POV it can be closed.
Please tell me if I have to close it personally.
