### ISSUE TITLE
Symfony 2.8: Use FQCN instead of field names

### ISSUE THREAD

**Issue by WouterJ** [sonata-project/SonataAdminBundle#3248]
Refs https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/485

Field names are deprecated and FQCN has to be used instead, the bundle should at least support FQCN to have 2.8/3.0 support.

**Comment by Soullivaneuh** [comment]
Symfony ref: https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#form

@WouterJ What is the way to support Symfony <2.8 BC?
