### ISSUE TITLE
Notice: Undefined variable: test in "SonataAdminBundle:CRUD:base_edit_form.html.twig"

### ISSUE THREAD

**Issue by baksosapi** [sonata-project/SonataAdminBundle#3249]
When i configure sonataAdminBundle+UserBundle i've got an error:

An exception has been thrown during the compilation of a template ("Notice: Undefined variable: test") in "SonataAdminBundle:CRUD:base_edit_form.html.twig".
500 Internal Server Error - Twig_Error_Syntax
1 linked Exception: ContextErrorException »

**Comment by ThibautAlgrin** [comment]
Can you execute this command:
composer show -i | grep sonata

**Comment by baksosapi** [comment]
this is the output:
sonata-project/admin-bundle              dev-master 1e0750a
sonata-project/block-bundle              2.3.8             
sonata-project/cache                     1.0.6             
sonata-project/cache-bundle              2.2.4             
sonata-project/core-bundle               2.3.8             
sonata-project/datagrid-bundle           dev-master cc42f28
sonata-project/doctrine-extensions       1.0.2             
sonata-project/doctrine-orm-admin-bundle dev-master dbcd559
sonata-project/easy-extends-bundle       2.1.9             
sonata-project/exporter                  1.4.0             
sonata-project/google-authenticator      1.0.2             
sonata-project/user-bundle               dev-master ec09378

**Comment by TransQ** [comment]
I have the same problem.

**Comment by TransQ** [comment]
For me I commented this
```php
if ($function instanceof Twig_SimpleFunction && $function->isDeprecated()) {
            $message = sprintf('Twig Function "%s" is deprecated', $function->getName());
            //if ($test->getAlternative()) {
            //    $message .= sprintf('. Use "%s" instead', $function->getAlternative());
            //}
```
in ExpressionParser.php

**Comment by revollat** [comment]
see https://github.com/symfony/symfony/issues/15732#issuecomment-138828509
you have to upgrade twig to version 1.22.1

**Comment by revollat** [comment]
@TransQ you better not modify this file ... just upgrade twig. that worked for me

**Comment by TransQ** [comment]
sure, its only to localize issue )

**Comment by bezdelnique** [comment]
[composer update] of my Symfony project help's for me! =)
