### ISSUE TITLE
All exceptions hidden in Sonata ?

### ISSUE THREAD

**Issue by matthieuauger** [sonata-project/SonataAdminBundle#3255]
Hi,

Does Sonata hide all exceptions or am I missing something ?

Currently I can write anything, like

```php
    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->add('missingProperty', null, ['unkownOption' => 'foo', 'template' => 'typoInMyTwigPath'])        
        ;
    }
```

And everything is fine for Sonata. Nothing is displayed, but there is no way to debug anything. I lost multiple hours trying to debug my admin class and this was simply a typo in my template path. With the right config otherwise, everything is working.

Is it intentional ? Even in dev environment and debug mode ? I hope it isn't and can work on a PR to solve this if needed

**Comment by rande** [comment]
You should get an error message in the log: https://github.com/sonata-project/SonataAdminBundle/blob/master/Twig/Extension/SonataAdminExtension.php#L103

Maybe this should be adjusted for dev mode

**Comment by Soullivaneuh** [comment]
@rande Maybe invalid options should throw errors. Is `OptionResolver` used for that? Could be a nice addition IMO.

**Comment by greg0ire** [comment]
I fixed the template part in #3704 , it would be great not to sweep things like that under the rug. Please reopen if you still experience this with Sonata 3

**Comment by matthieuauger** [comment]
You rocks 👍

**Comment by greg0ire** [comment]
> You rocks :+1:

lol thanks :blush:
