### ISSUE TITLE
Sonata Admin Bundle Security Configuration Error 

### ISSUE THREAD

**Issue by supdeva** [sonata-project/SonataAdminBundle#326]
I get the following error while trying to access the dashboard.

Fatal error: Call to a member function isGranted() on a non-object in C:\wamp\www\Symfony\vendor\bundles\Sonata\AdminBundle

So I thought its an error with the security configuration and explicitly set the security config to "noop" . Given below is my config.yaml

sonata_admin:
    security_handler: sonata.admin.security.handler.noop
    dashboard_groups:
        publishers:
            label: Publishers
            items: [client.project.sonatatest.admin.publisher]

My service definition is given here
<service id="client.project.sonatatest.admin.publisher" class="Client\Project\SonataTestBundle\Admin\PublisherAdmin">
			<tag name="project.admin" manager_type="orm" group="project_publisher" label="publisher" />
			<argument />
			<argument>Client\Project\SonataTestBundle\Admin\Publisher</argument>
			<argument>SonataTestBundle:PublisherAdmin</argument>
		</service>

However I still get this error. My security config is the default file that comes with the symfony 2 standard edition. Can you please help me resolve this.

**Comment by core23** [comment]
If this is an active issue, please reopen @supdeva @teu

**Comment by rafiqbd** [comment]
I am using symfony 2.8 and FOS User bundle 2.0@dev. Can't integrate with sonata admin bundle with user integration. Using  "sonata-project/admin-bundle": "^3.1", "sonata-project/user-bundle": "^3.0" composer update is fine. But after execute admin, showing "An exception has been thrown during the rendering of a template ("Admin service "sonata.user.admin.user" not found in admin pool.") in SonataAdminBundle:Core:dashboard.html.twig " . Would you kindly help regarding this issue. also, not compatible with doctrine.

**Comment by Soullivaneuh** [comment]
@rafiqbd Sonata user-bundle stable is not compatible with FOSUser 2.0.

**Comment by rafiqbd** [comment]
@Soullivaneuh , Thanks for your reply. Ok, let's back to FOS 1.3 . Then composer update is fine but can't execute acl. showing  [Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]   
  The service "security.access.decision_manager" has a dependency on a non-ex  
  istent service "security.acl.provider".  Would you kindly help me how can integrate FOS+sonata user bundle with acl.

**Comment by Soullivaneuh** [comment]
If your issue is about sonata user-bundle, please open another one on the concerned bundle.
