### ISSUE TITLE
Unable to create the cache directory 

### ISSUE THREAD

**Issue by vamsiikrishna** [sonata-project/SonataAdminBundle#3265]
after deploying new code, we clear the cache using sumfony's console command.
after clearing the cache, I make sure permissions are set up properly again.
( chmod  -R 777 app/cache )
but even after that, I am getting the above error in some cases ( routes ), when I run the chmod -R 777 app/cache after I get an error , the error is generally resolved..

I have tried cache:warmup but even its not having the desired impact..

is there a way I can make sure the sonata admin is able to write to cache dir ?

Thanks

**Comment by OskarStark** [comment]
i'd say this is a symfony, not a sonata problem

**Comment by vamsiikrishna** [comment]
@OskarStark  thanks for the reply..

reason I created in this repo is because I am not facing caching related issues in other parts of my app.

**Comment by Soullivaneuh** [comment]
As @OskarStark says, this is a global cache issue.

As a question without technical detail, I will ask you to make your question on stackoverflow.

If you think you find a bug, feel free to open another ticket to explain it.

Thanks.
