### ISSUE TITLE
The extended type specified for the service "sonata.admin.form.extension.field" does not match the actual extended type. Expected "form", given "field".

### ISSUE THREAD

**Issue by dkorsak** [sonata-project/SonataAdminBundle#3266]
For the master sonata branch and Symfony version 2.8.x I got error as in the subject,

**Comment by OskarStark** [comment]
can you please provide some code and include the stacktrace of the exception?

thank you

**Comment by pulzarraider** [comment]
I think I have found the problem, ser PR #3267

**Comment by jordisala1991** [comment]
Was solved long ago, closing
