### ISSUE TITLE
Download drop-down menu does not work as expected

### ISSUE THREAD

**Issue by DavidGarciaCat** [sonata-project/SonataAdminBundle#3270]
Hey there,

I cannot use the Download menu from an list generated automatically.
It seems all options are hidden (please see attached image).

I am using `Mac OS X "El Capitan"` and latest `Google Chrome` release.

Any idea?

Thanks,

<img width="230" alt="screen shot 2015-09-21 at 15 29 53" src="https://cloud.githubusercontent.com/assets/7809429/9994587/e52fd3a0-6075-11e5-9fec-54329023a764.png">

**Comment by OskarStark** [comment]
which sonata version do you use?

```composer show -i | grep sonata-admin```

in the current master branch this seems to be fixxed, i think you are on 2.3 stable, right?

**Comment by DavidGarciaCat** [comment]
No, it seems I am not using the 2.3:

```
$ composer show -i | grep sonata

sonata-project/admin-bundle              dev-master 987beb7  Symfony SonataAdminBundle
sonata-project/block-bundle              2.2.12              Symfony SonataBlockBundle
sonata-project/cache                     1.0.3               Cache library
sonata-project/core-bundle               2.2.6               Symfony SonataCoreBundle
sonata-project/datagrid-bundle           dev-master dba166c  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2               Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle dev-master 34b8f90  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       dev-master dbc2325  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.3.3               Lightweight Exporter library
sonata-project/google-authenticator      1.0.2               Library to integrate Google Authenticator into a PHP project
sonata-project/user-bundle               2.2.4               Symfony SonataUserBundle
```

**Comment by OskarStark** [comment]
i'm using the ```master``` branch and don't have this bug!

**Comment by OskarStark** [comment]
@DavidGarciaCat feel free to compare the master with the 2.3 branch and provide a PR against the 2.3 branch. please reference this issue in the PR.

thank you
