### ISSUE TITLE
Symfony 2.8: Form 'field' !== 'form' issue

### ISSUE THREAD

**Issue by petforsberg** [sonata-project/SonataAdminBundle#3271]
I upgraded my project to SF 2.8@dev. Everything works... besides of Sonata Admin.

I cannot open now any admin page because of filters form issue:

    "The extended type specified for the service "sonata.admin.form.extension.field" does not match the actual extended type. Expected "form", given "field""

However, replacing a name in this file:

https://github.com/sonata-project/SonataAdminBundle/blob/master/Form/Extension/Field/Type/FormTypeFieldExtension.php#l199

from "field" to "form" does the trick.

Ok I found another issue referring to the same thing:
https://github.com/sonata-project/SonataAdminBundle/issues/3266

Anyway, it's interesting that it's depcrated from SF 2.1, but still in use here in Admin.

**Comment by Soullivaneuh** [comment]
Fixed in #3267.
