### ISSUE TITLE
shall we use the AdminLTE checkbox style which looks better (like the inputs)?

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataAdminBundle#3276]
now:
![bildschirmfoto 2015-09-23 um 11 24 13](https://cloud.githubusercontent.com/assets/995707/10041649/e05d382e-61e5-11e5-856d-8a906c184cd3.png)

possible:
![bildschirmfoto_2015-09-23_um_11_24_47](https://cloud.githubusercontent.com/assets/995707/10041650/e66c73ce-61e5-11e5-9a19-68bc25081e3c.jpg)

**Comment by OskarStark** [comment]
i mean the ```Square skin```
![bildschirmfoto 2015-09-23 um 11 27 37](https://cloud.githubusercontent.com/assets/995707/10041684/285551c0-61e6-11e5-9ee4-f8992daa53b7.png)

**Comment by Soullivaneuh** [comment]
Why not, feel free to propose a PR. :+1:

**Comment by OskarStark** [comment]
sounds great :)
