### ISSUE TITLE
Entity validation annotations are ignored

### ISSUE THREAD

**Issue by dmitry84** [sonata-project/SonataAdminBundle#3280]
Versions I'm using:
        "sonata-project/core-bundle": "2.3.*@stable",
        "sonata-project/admin-bundle": "dev-master#e7aaad9",
        "sonata-project/doctrine-orm-admin-bundle": "dev-master#6299bc8",
        "sonata-project/user-bundle": "2.2.*@stable",
        "sonata-project/easy-extends-bundle": "2.1.*@stable",

My User entity class is extended from FosUser, and when I'm trying to save entity via standard form all validation rules are working. But when I'm trying to do this in admin bundle (extended from Sonata\UserBundle\Admin\Model\UserAdmin) - only email and password works. validate() doesn't call at all.

This is happening only for the user entity, other entities which are extended from Admin works as expected.

I don't want to use inline validation, and would like to have all validation rules in the entity.

I've tried to debug, but can not see where the problem is. Looks like attachInlineValidator is called  but rules are not loaded.

**Comment by greg0ire** [comment]
Please reopen if you still experience this with Sonata 3
