### ISSUE TITLE
ability to customize associationAdmin for sonata_type_collection

### ISSUE THREAD

**Issue by pmurzakov** [sonata-project/SonataAdminBundle#329]
I have entities 
- **Provider**
- **ProviderBrand**
- **Brand**

**ProviderBrand** linked to other entities(**Provider** and **Brand**) as many-to-one.

I want to have ability to edit brands list from **Provider** and providers list from **Brand**.

My **ProviderBrand** entity:

``` php
class ProviderBrand
{
    ///
    /// several not interesting fields here
    ///


    /**
     * @var Brand
     *
     * @ORM\ManyToOne(targetEntity="Brand", inversedBy="providersList")
     */
    private $brand;

    /**
     * @var Provider
     *
     * @ORM\ManyToOne(targetEntity="Provider", inversedBy="brandsList")
     */
    private $provider;
}
```

In **ProviderAdmin** I'd added field

``` php
$formMapper
// ...
// ...
->add('brandsList', 'sonata_type_collection', array(
        'by_reference' => false,
    ), array(
        'edit' => 'inline',
        'inline' => 'table',
        'sortable'  => 'position'
))
```

And in **BrandAdmin**

``` php
$formMapper
// ...
// ...
->add('providersList', 'sonata_type_collection', array(
        'by_reference' => false,
    ), array(
        'edit' => 'inline',
        'inline' => 'table',
        'sortable'  => 'position'
))
```

In **ProviderAdmin** I want to see **ProviderBrand** with brand field (but without provider field (!))
In **BrandAdmin** I want to see **ProviderBrand** with provider field (but without brand field (!))

For this purposes I`d wrote 2 Admin classes for **ProviderBrand**

**ProviderBrandAdmin**

``` php
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('brand')
            ->add('...)
            ->add('...');
    }
```

**ProviderBrandReversedAdmin**

``` php
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('provider')
            ->add('...)
            ->add('...');
    }
```

But field **brandsList** from **ProviderAdmin** and field **providersList** from **BrandAdmin** pick up only one Admin classs(**ProviderBrandAdmin** or **ProviderBrandReversedAdmin**) without ability of selecting it manually. Because in **Admin/Admin.php** we have followed code:

``` php
    /**
     * attach an admin instance to the given FieldDescription
     *
     * @param \Sonata\AdminBundle\Admin\FieldDescriptionInterface $fieldDescription
     */
    public function attachAdminClass(FieldDescriptionInterface $fieldDescription)
    {
        $pool = $this->getConfigurationPool();

        $admin = $pool->getAdminByClass($fieldDescription->getTargetEntity());
        if (!$admin) {
            return;
        }

        $fieldDescription->setAssociationAdmin($admin);
    }
```

I solved my problem with follows way:

1.I'd changed **Admin/Admin.php**

``` php
    /**
     * attach an admin instance to the given FieldDescription
     *
     * @param \Sonata\AdminBundle\Admin\FieldDescriptionInterface $fieldDescription
     */
    public function attachAdminClass(FieldDescriptionInterface $fieldDescription)
    {
        $pool = $this->getConfigurationPool();


        if (null !== ($associationAdmin = $fieldDescription->getOption('association_admin'))) {
            $admin = $pool->getInstance($associationAdmin);
        } else {
            $admin = $pool->getAdminByClass($fieldDescription->getTargetEntity());
        }
        if (!$admin) {
            return;
        }

        $fieldDescription->setAssociationAdmin($admin);
    }
```

2.I'd changed my Admin classes 
a) **ProviderAdmin**

``` php
$formMapper
// ...
// ...
->add('brandsList', 'sonata_type_collection', array(
        'by_reference' => false,
    ), array(
        'edit' => 'inline',
        'inline' => 'table',
        'sortable'  => 'position'
        'association_admin' => 'berg.site.admin.provider_brand'
))
```

b) **BrandAdmin**

``` php
$formMapper
// ...
// ...
->add('brandsList', 'sonata_type_collection', array(
        'by_reference' => false,
    ), array(
        'edit' => 'inline',
        'inline' => 'table',
        'sortable'  => 'position'
        'association_admin' => 'berg.site.admin.provider_brand_reversed'
))
```

Is my changes a right solution?
If no other way to do this, can you include my patch to main branch?

**Comment by Soullivaneuh** [comment]
@lu4e3ar is this issue still relevant with latest sonata-admin version?

If yes, could you make a PR about it?

cc @rande

**Comment by ujhgj** [comment]
I vote for this feature

**Comment by mcwebb** [comment]
@lu4e3ar's solution seems to already be implemented, just as `admin_code` rather than `association_admin` however this doesn't seem to work for `sonata_type_collection`.
The point being that there doesn't seem to be a way to include an unmapped `sonata_type_collection`, which is sometimes quite useful.

**Comment by core23** [comment]
Can you fix this @mcwebb ?

**Comment by mcwebb** [comment]
I don't have time at the moment I'm afraid

**Comment by jordisala1991** [comment]
This can be done using admin_code. But the field needs to be mapped directly. Closing. @mcwebb feel free to open an issue for the other issue. But it think there are already some issues for that matter.

If this is still relevant, ping me to reopen
