### ISSUE TITLE
font-awesome vs. glyphicons

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataAdminBundle#3291]
hi guys

is there a reason, why we use both?

best Oskar

Todo:
- [x] in list actions - #3303
- [x] sonata-project/SonataCoreBundle#194

**Comment by Soullivaneuh** [comment]
I think is just because Bootstrap include glyphicons by default.

But FontAwesome only is used AFAIK.

**Comment by OskarStark** [comment]
ok, but we use font-awesome in the navigation for example, but in the list actions we use glyphicons:

```php
{% if admin.isGranted('EDIT', object) and admin.hasRoute('edit') %}
    <a href="{{ admin.generateObjectUrl('edit', object) }}" class="btn btn-sm btn-default edit_link" title="{{ 'action_edit'|trans({}, 'SonataAdminBundle') }}">
        <i class="glyphicon glyphicon-edit"></i>
        {{ 'action_edit'|trans({}, 'SonataAdminBundle') }}
    </a>
{% endif %}
```

**Comment by Soullivaneuh** [comment]
Certainly historic code. :-)

Feel free to make PR about that. :+1:

**Comment by OskarStark** [comment]
I referenced a PR where i moved the icons to the translations files.

later we can decide if we want to use font-awesome everywhere.

Oskar

**Comment by rande** [comment]
yep. a 5 years old projects might need so spring cleaning ;)

**Comment by OskarStark** [comment]
if you like i'll change the icons this way:

old-glyphicons:
<img width="313" alt="bildschirmfoto 2015-09-28 um 11 33 55" src="https://cloud.githubusercontent.com/assets/995707/10132229/b90dc240-65d5-11e5-881b-1b0169084bd1.png">

old-new side by side (left is glyphicon):
<img width="475" alt="bildschirmfoto 2015-09-28 um 11 39 29" src="https://cloud.githubusercontent.com/assets/995707/10132233/c15349a2-65d5-11e5-84ac-abc9037ada5c.png">

new-font-awesome:
<img width="386" alt="bildschirmfoto 2015-09-28 um 11 39 49" src="https://cloud.githubusercontent.com/assets/995707/10132242/cb8cd0e6-65d5-11e5-979c-17065f386a63.png">

**Comment by Soullivaneuh** [comment]
Looks good.

BTW, bootstrap will drop glyphicons default integration on 4.x.

**Comment by OskarStark** [comment]
good to know

ok i'll create a PR

**Comment by Koc** [comment]
@OskarStark so does we have moved from glyphicons to font-awesome?

**Comment by ju1ius** [comment]
@OskarStark can you also remove the [famfamfam](https://github.com/sonata-project/SonataAdminBundle/tree/master/Resources/public/famfamfam) set ?

**Comment by OskarStark** [comment]
> @OskarStark so does we have moved from glyphicons to font-awesome?

yes we moved

> @OskarStark time to also remove the famfamfam set ? 😉
