### ISSUE TITLE
Custom Javascript listener

### ISSUE THREAD

**Issue by tounarti000** [sonata-project/SonataAdminBundle#3293]
Hi,

I have a custom form template which extends base_template
And I'm trying to modify the form dynamically with some javascript but I just can't get it to work.

here is my template :

``` javascript
{% extends base_template %}

{% block javascripts %}
    {{ parent() }} 

    {% javascripts '@AcmeBundle/Resources/public/js/custom.js'%}
        <script src="{{ asset_url }}"></script>
    {% endjavascripts %}

{% endblock %}
```

And in my custom.js

``` javascript

jQuery(document).ready(function($) {
    jQuery('input[type=checkbox]').each(function(index, element) {  
        if(window.addEventListener) {
            element.addEventListener('change', loadContacts, false);
        } else if (window.attachEvent){
            element.attachEvent("onchange", loadContacts);
        }                   
    });
});
function loadContacts(){
    alert('worked');
     //ajax code etc...
}
```

But the function loadContacts is never called. In my browser i can see that the event is bind to the checkbox but it ain't called.

I tried with unbind(), jquery noConflict()... , the only time it works is when i put my js before the sonata.admin.js... but if I do that, the admin js doesn't work.
Is there a special way to add a listener to a checkbox?

additionally, in my js console I have:

```
sonata_admin_js.js:94 [Sonata.Admin] [core|setup_per_page_switcher] setup page switcher, [object HTMLDocument]
sonata_admin_js.js:94 [Sonata.Admin] [core|shared_setup] Register services on, [object HTMLDocument]
sonata_admin_js.js:94 [Sonata.Admin] [core|setup_collection_buttons] setup collection buttons, [object HTMLDocument]
sonata_admin_js.js:94 [Sonata.Admin] [core|set_object_field_value] set value field on, [object HTMLDocument]
sonata_admin_js.js:94 [Sonata.Admin] [object Object]
sonata_admin_js.js:94 [Sonata.Admin] [core|setup_select2] configure Select2 on, [object HTMLDocument]
sonata_admin_js.js:94 [Sonata.Admin] [core|setup_icheck] configure iCheck on, [object HTMLDocument]
sonata_admin_js.js:94 [Sonata.Admin] [core|add_filters] configure filters on, [object HTMLDocument]
sonata_admin_js.js:94 [Sonata.Admin] [core|setup_xeditable] configure xeditable on, [object HTMLDocument]
sonata_admin_js.js:94 [Sonata.Admin] [core|add_pretty_errors] configure pretty errors on, [object HTMLDocument]
sonata_admin_js.js:94 [Sonata.Admin] [core|setup_form_tabs_for_errors] setup form tab's errors, [object HTMLDocument]
2sonata_admin_js.js:94 [Sonata.Admin] [core|show_form_first_tab_with_errors] show first tab with errors, [object Object]
sonata_admin_js.js:94 [Sonata.Admin] [core|setup_inline_form_errors] show first tab with errors, [object HTMLDocument]
sonata_admin_js.js:94 [Sonata.Admin] [core|setup_tree_view] setup tree view, [object HTMLDocument]
```

Thanks for your help and time ;)

**Comment by Soullivaneuh** [comment]
Please format your code.

**Comment by tounarti000** [comment]
done ;)

**Comment by OskarStark** [comment]
does the ```javascript```-block accepts the script code directly?

i think not

**Comment by tounarti000** [comment]
sorry, I forgot to add it in the issue. I updated it.
But that wasn't the problem. thx anyway

**Comment by OskarStark** [comment]
anyway, i think this has to be in a separate file, as it is used via assetic

**Comment by tounarti000** [comment]
done too but loadContacts is still not called :(

**Comment by tounarti000** [comment]
Based on your answer i guess that it should work and that there is no "special" way to add a listener . 
Am I right?

**Comment by jordisala1991** [comment]
I don't think this is an issue for Sonata but for Stackoverflow.

You should be able to add custom javascript to Sonata, to implement your logic.

I might also recommend this docs, because we are using icheck for radio and checkboxes: http://icheck.fronteed.com/

Closing. If you still having this problem, please provide more information (so we can help you better) and I will reopen
