### ISSUE TITLE
Parametered admin group names

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/SonataAdminBundle#3299]
From sonata-project/SonataNewsBundle#62

Parameterable group names should be consistent across the projects. Repos which need this update will be listed here.

**Bundles**
- [x] SonataNewsBundle - sonata-project/SonataNewsBundle#62

**Comment by OskarStark** [comment]
i updated you initial post @sagikazarmark

**Comment by sagikazarmark** [comment]
:+1:

**Comment by greg0ire** [comment]
So… this is fixed, right? Reopen if it isn't.
