### ISSUE TITLE
Strange behaviour with field type time and select2 for selecting `20` when using tabs not mouse

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3301]
Since the `SonataAdmin` uses `select2` for `time` field types I post this issue here.
At the bottom line I think the behaviour is driven by `select2` itstelf.

I'm tabbing through a form and focusing a time field. I want to enter _20_. When I start typing the following options appear:
![bildschirmfoto vom 2015-09-28 11 10 30](https://cloud.githubusercontent.com/assets/3479626/10131618/e1ca04b8-65d1-11e5-9b02-6b423cfdd2dd.png)

No I type the final _0_ but nothing happens. I have to use the arrow keys or the mouse to select the _20_.

When I focus the field type by clicking on it instead of using tabs I can indeed type _20_:
![bildschirmfoto vom 2015-09-28 11 14 50](https://cloud.githubusercontent.com/assets/3479626/10131639/0d039d56-65d2-11e5-8ec8-7c02b0fb2c36.png)

Should I move this issue to `select2` or is it caused by the way the option labels are rendered?
![bildschirmfoto vom 2015-09-28 11 10 09](https://cloud.githubusercontent.com/assets/3479626/10131680/47b0304a-65d2-11e5-8b6b-ac52a030b26d.png)

**Comment by rewotec** [comment]
:+1:

**Comment by jordisala1991** [comment]
This issue is too old and does not seem related to sonata, but to Select2. I did some testing on this with other values, and the search worked well.

Closing for now. If you still having this issue, please ping me to reopen, and provide more information
