### ISSUE TITLE
listMapper oneToMany link to admin

### ISSUE THREAD

**Issue by robhunt3r** [sonata-project/SonataAdminBundle#3304]
Is there any way to add a oneToMany relation inside listMapper, and instead of rendering the list of items, just render a link to that admin, for example:

`/admin/brands` has two fields:
`Name`, `Products`

Products has a list of products, weird in a list view, we want a link to that brand's products, so link would be:

`/admin/brands/X/products/list` where X is that brand id.

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
