### ISSUE TITLE
Translation inconsistencies

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/SonataAdminBundle#3306]
There are a few issues with translations:
- Dot notation vs underline: In some cases identifiers are separated with dots, in some cases with underlines. What should be the standard?
- ":" in label names: it should not be there, it should be added in the code, by the form builder for example

**Comment by Soullivaneuh** [comment]
> Dot notation vs underline: In some cases identifiers are separated with dots, in some cases with underlines. What should be the standard?

Could you provide some cases? And yes this should be standardized. The issue is changing labels would be BC break.

But yes, we should write something about it on contribution doc (cc @rande).

> ":" in label names: it should not be there, it should be added in the code, by the form builder for example

Not agree. Some languages like french need a space before `:`, some don't. This need to be handled by translations files.

**Comment by sagikazarmark** [comment]
> Could you provide some cases? And yes this should be standardized. The issue is changing labels would be BC break.

Actually, I might made a mistake here. I realized since that dot notation is used for some namespacing. For example: form.label_context vs label_context

> Not agree. Some languages like french need a space before :, some don't. This need to be handled by translations files.

Well, I think it would be better if the form library could handle this internally. What if you want to use a placeholder instead? Add a new string without the colon?

**Comment by Soullivaneuh** [comment]
> What if you want to use a placeholder instead? Add a new string without the colon?

We don't do it AFAIK. :-)

Seriously, I understand your issue, I got the same for project. Actually I make two translations for that (yes, not very nice).

> Well, I think it would be better if the form library could handle this internally.

I'm curious. Feel free to PR. :+1:

**Comment by rande** [comment]
@sagikazarmark dot notation is used by sonata admin using the underscore strategy: https://sonata-project.org/bundles/admin/2-3/doc/reference/translation.html#label-strategies

**Comment by sagikazarmark** [comment]
@rande thanks

**Comment by jvasseur** [comment]
Maybe the ":" could get its own translation, that would be appended to the label.

**Comment by greg0ire** [comment]
Or maybe integrate this : https://github.com/jolicode/JoliTypo ?
