### ISSUE TITLE
Tests are broken on branch 2.3

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataAdminBundle#3320]
See [this build](https://travis-ci.org/sonata-project/SonataAdminBundle/jobs/83453730#L129), for instance.

**Comment by greg0ire** [comment]
Only the 5.6 jobs work now.

**Comment by greg0ire** [comment]
Idea : `composer global require $PHP_PLATFORM $PHP_VERSION` . Are there any built-in variables that might match this ?

**Comment by greg0ire** [comment]
BTW, this looks like a Composer bug. How come it installs something incompatible with the platform in use ? It could detect that php 5.3 is used…

**Comment by greg0ire** [comment]
[Issue reported](https://github.com/composer/composer/issues/4474)

**Comment by greg0ire** [comment]
It appears that [the php version is available](http://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) through `TRAVIS_PHP_VERSION`

**Comment by alcohol** [comment]
`composer require 'phpunit/phpunit:@stable'` will also work just fine. Please see comments I left on your reported issue (composer/composer#4474) for the reasons why `require` works as it does.

**Comment by greg0ire** [comment]
Thanks @alcohol ! @Soullivaneuh How come auto-close did not work on this issue. I'm closing.

**Comment by Soullivaneuh** [comment]
> How come auto-close did not work on this issue

My fault I guess, forgot to specify issue on the PR.

And BTW, auto-closing works only for default branch AFAIK.

**Comment by greg0ire** [comment]
> My fault I guess, forgot to specify issue on the PR.

I specified it on mine, that's what I am surprised about.

> And BTW, auto-closing works only for default branch AFAIK.

Guess this explains that.
