### ISSUE TITLE
Multiple admin classes of one Entity

### ISSUE THREAD

**Issue by Nexotap** [sonata-project/SonataAdminBundle#3325]
Quite some time ago there has been an issue with multiple admin classes of one Entity: https://github.com/sonata-project/SonataAdminBundle/issues/1899

At the end of the conversation cjgordon mentioned that one has to add the admin_code for each field. This works so far, but looks very clumsy to me. Now I modified the FormMapper class. Added a setter function for setting a general admin_class and adapted the add function.

I cant tell if it's a good idea. But imagine having large forms, this looks like a cleaner solution to me.

 Should someone be interested I can provide you with the code.

**Comment by OskarStark** [comment]
:+1: for PR

Thank you @Nexotap

**Comment by Nexotap** [comment]
Please bear with me. Alltought I've worked at home a bit with git, I've never used github for anything else than downloading tarballs. 
I'm willing to try out creating a PR.
Can you give me some hints for doing so?

**Comment by Nexotap** [comment]
I'm still willing to contribute. But I have no clue how this works with PR and such. It would be nice to get some help; at least if you're interested in my PR.

**Comment by reypm** [comment]
@Nexotap it's easy, fork the repo, create a branch for your contributions, make PR and stay sync with upstream. All you have to do is hit the button **Fork** on top of the repo page and Github will do the rest. You should take care of PR and syncing since this are tasks of the developer. Github have pretty good docs about this. Good luck

**Comment by greg0ire** [comment]
Related : #3908

**Comment by Nexotap** [comment]
I think, problem solved now. Will close this.
