### ISSUE TITLE
Search Bar : Unable to find a valid admin 

### ISSUE THREAD

**Issue by bdebon** [sonata-project/SonataAdminBundle#3329]
Hey !

I've recently update all my sonata stuff from `~2.2` up to `dev-master`.
Everything is working great except the search engine. 

When I search something, I get the following exception : 
`An exception has been thrown during the rendering of a template ("Unable to find a valid admin for the class: Application\Sonata\UserBundle\Entity\User, there are too many registered: author.admin,lector.admin") in "SonataAdminBundle:Core:search.html.twig" at line 63.`

I have a User class which has two different admins and it seems to be a problem here (in the last version it was not). 
I have tried to fix the problem by myself but I stopped when I found that the problem is in the call of the twig function `sonata_block_render` that you can find in the file `search.html.twig` 

I think it is not a big deal if you know the bundle but I confess that it is a little bit to hard for me... 

I hope you will find something !

**Comment by DavidG04** [comment]
Hi, 

Please can you post your two admin code (author and lector) and your admin declaration service

Thx.

**Comment by greg0ire** [comment]
You can fix this by using `admin_code` IMO. Closing.
