### ISSUE TITLE
sonata_type_collection with subclasses does not update the view on create

### ISSUE THREAD

**Issue by jbultmann** [sonata-project/SonataAdminBundle#3345]
Hi,
I am using a simple SonataAdmin configuration with
"sonata-project/core-bundle" : "2.3.6" and
"sonata-project/admin-bundle": "2.3.9"

I have the following (shortened) Entities

``` php
class Landingpage {
//... 
    /**
     * @var \Doctrine\Common\Collections\ArrayCollection
     * @ORM\OneToMany(targetEntity="Module", mappedBy="landingpage", cascade={"persist", "remove"}, orphanRemoval=true)
     */
    protected $modules;

    public function addModule(Module $module)
    {
        $this->modules->add($module);
        $module->setLandingpage($this);
    }
    public function removeModule(Module $module)
    {
        $index = $this->modules->indexOf($module);
        $this->modules->remove($index);
        $module->setLandingpage(null);
    }
    ///... 
}

abstract class Module
{
    ///... 
    /**
     * @ORM\ManyToOne(targetEntity="Landingpage", inversedBy="modules", cascade={"persist"})
     * @ORM\JoinColumn(name="langingpage_id", referencedColumnName="id")
     */
    protected $landingpage;

    public function getLandingpage()
    {
        return $this->landingpage;
    }
    public function setLandingpage($landingpage)
    {
        $this->landingpage = $landingpage;
    }
    ///... 
}
```

One Landingpage can have many Modules. 
The Modules are subclassed, so the Module Entity is abstract.
My ModuleAdmin Class is configured with the available subclasses

``` yml
calls:
      - [ setTranslationDomain, [AppBundle]]
      - [ setSubClasses, [{ product_slider : AppBundle\Entity\ProductSliderModule, ... }]]
```

The Landingpage Admin Class is rendering a sonata_type_collection to handle an exclusive Module Collection for the Landingpage

``` php
class LandingpageAdmin extends Admin {
    //...
    protected function configureFormFields(FormMapper $formMapper)
    {
        //...
        $formMapper->add('modules', 'sonata_type_collection', array(
            'type_options' => array(
                'delete' => true
            ),
            'by_reference' => false
        ))
   }
   //...
}
```

I tried different setups including different configurations with and without inline editing.
The Behavior remains nearly the same.

On Configurations without inline editing:
If I click on the add Button I get the Subclass select Modal, following the correct Form of the Subclass.
Once submitted the Module is created correctly but the following get-form-field-element requests returns an unchanged state. The newly created Entity is not added to the List and therefore not associated with the Landingpage.

On Configurations with inline editing:
Without further customizations I will get a new row only including the fields of the abstract Module class.
On save I get an Error because the abstract class cannot be instantiated.
I therefore customized the Rendering of the Add button a little to give me an Add button for each subclass. 
Unfortunately the Form still tries to create an Instance of the abstract Module Class.

Is this feature not implemented or am I doing something wrong?

**Comment by clytemnestra** [comment]
I have the same issue, so I think it's bugged.

**Comment by mpoiriert** [comment]
Did you find any solution ?

**Comment by mcwebb** [comment]
I ended up having to create a custom (rather janky) solution using jQuery. Couldn't figure out a way to fix Sonata's code unfortunately.

**Comment by mpoiriert** [comment]
And wich one did you fix ? With or without the inline edit ?

**Comment by mcwebb** [comment]
The inline table version of `sonata_type_collection`

**Comment by mpoiriert** [comment]
Have you manage to have a way to edit field that are different from the sub class ?

**Comment by mcwebb** [comment]
The issue I solved was when using an inline table type `sonata_type_collection` with an association which has subclasses the "Add New" button was allowing me to select the correct subclass in the modal, but after creation the created entity was not immediately added to the parent collection.
After a refresh the created entity would be there, but obviously that isn't good enough for a client.

@mpoiriert I think you're having a different issue; in order to show different fields in the collection depending on which subclass, you can just do something like:
```php
if ($this->getSubject() instanceof SubclassOne) $formMapper->add('field');
elseif ($this->getSubject() instanceof SubclassTwo) $formMapper->add('other_field');
```

**Comment by mpoiriert** [comment]
No you can't have a different list of fileds in a inline edit...

**Comment by jordisala1991** [comment]
Lets unify discussions in #3538
