### ISSUE TITLE
Disable submit buttons after clicking - multiple entries issue

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3346]
Since the submit buttons come from bootstrap I guess this could end up being a bootstrap issue.

I recently published a new project and users create the strangest issues as we know.
One user is a heavy mouse user and he is clicking quickly.

Suddenly he reported that some of his entries appeared twice.
It's not a display problems - the submitted entity / row was indeed created twice.

**He was even able to click it up to 5 times creating 5 entries!**

It would be nice to disable the submit buttons after clicking.
A lot of sensitive forms today use this feature - guess it would make sense here too?

**Comment by webdevilopers** [comment]
PS.: The user just informed me that this started to happen recently. We recognized the bug **6** days ago.

**Comment by rewotec** [comment]
:+1: 1

**Comment by finchen** [comment]
I am giving a try at that
```javascript
$(document).on('click', 'form [type="submit"]', function(e){
				var $form = $(this).closest('form');
				console.log(e, $form);
				if ($form[0].checkValidity && $form[0].checkValidity()) {
					$(this).button('loading');
				}
			});
```

**Comment by Zuhayer** [comment]
@webdevilopers Having same issue in my project. Did you find a solution?

![untitled](https://cloud.githubusercontent.com/assets/5408155/22201727/b3f4168c-e186-11e6-8d34-0517ca885d1c.png)

**Comment by webdevilopers** [comment]
No longer working on that project, sorry!

**Comment by Zuhayer** [comment]
Kindly let me know if anyone else working on this?

@Bladrak @core23 @dunglas @mremi @nicolasricci @OskarStark @pulzarraider @qsomazzi @rande @Soullivaneuh

@webdevilopers Thanks for the response.

**Comment by core23** [comment]
Not working on this, but please aware that you should find a way to resubmit the form if a connection error occoured. Maybe using a unique form token is a better idea instead of disabling the button.

**Comment by Bladrak** [comment]
Not working on this either

**Comment by ashpumpkin** [comment]
I have a form with 2 submit btns. One for preview and one for export into csv. Export button doesn't reload the page and all buttons get disabled

Maybe a better solution is to disable buttons for 1 or 2 seconds?

**Comment by gototog** [comment]
@ashpumpkin 
You can add the code below in your js file to replace sonata function

```
window.Admin.setup_form_submit= function(subject) {
    jQuery(subject).find('form').on('submit', function() {
        var form = jQuery(this);

        setTimeout(function() {
            form.find('button').prop('disabled', true);
        }, 1);

        setTimeout(function() {
            form.find('button').prop('disabled', false);
        }, 1000); // <---  the button will be re-enabled after 1 sec

        var tabSelected = form.find('.nav-tabs li.active .changer-tab');

        if (tabSelected.length > 0) {
            form.find('input[name="_tab"]').val(tabSelected.attr('aria-controls'));
        }
    });
}
```
