### ISSUE TITLE
Embedded form with sonata_type_choice_field_mask jQuery Error

### ISSUE THREAD

**Issue by fatmah** [sonata-project/SonataAdminBundle#3348]
Hi,
I tried to use sonata_type_choice_field_mask in an embedded Admin form with oneToMany relation
but I get " jQuery is not defined " error !!
 the {% block sonata_type_choice_field_mask_widget %} have a jquery script but it seems that jquery is not loaded there.

Thank you

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
