### ISSUE TITLE
Ability to render blocks in the form view

### ISSUE THREAD

**Issue by ElectricMaxxx** [sonata-project/SonataAdminBundle#3350]
I would like to have the ability on the `FormMapper` to render simple text instead of form fields. The best solution would be to render the sonata blocks, to create customized html blocks inside my form view (between form field, tabs, ...).

The use case is to render custom data beside the mapped properties on the entity like additional information. Atm i show those data in `read_only` text fields, which is a bad solution, i know.

It would be nice to implement that feature on the 2.3 too.

**Comment by OskarStark** [comment]
sound great, would like this feature, too :+1:

**Comment by Soullivaneuh** [comment]
Don't know what to think about it.

> It would be nice to implement that feature on the 2.3 too.

No. All new feature must be on a new minor version, not a patch.

**Comment by ElectricMaxxx** [comment]
yea i know it would be a mixture between content rendering and form
handling. But actually in my current project i would love to use it.

**Comment by Soullivaneuh** [comment]
> But actually in my current project i would love to use it.

I understand but we wont brake semver just because some users want it to them projects. :-)

**Comment by ElectricMaxxx** [comment]
No that wasn't the reason for my last comment, just to support the
feature at all. I understand the semver thing :-)

**Comment by OskarStark** [comment]
The ability to render Blocks with the $formMapper sounds like a mayor feature, so 3.0 IMO

**Comment by Soullivaneuh** [comment]
> The ability to render Blocks with the $formMapper sounds like a mayor feature, so 3.0 IMO

Major version is only for BC breaks. If this feature could be provided with BC, it could be on a new minor.
