### ISSUE TITLE
Get master dependency in composer.json

### ISSUE THREAD

**Issue by Brah0um** [sonata-project/SonataAdminBundle#3351]
I am working with this `composer.json` file:
```json
"require": {
     "sonata-project/admin-bundle": "dev-master",
     "sonata-project/doctrine-orm-admin-bundle": "^2.3",
     "sonata-project/intl-bundle": "^2.2"
}
```

I'm facing an issue. Indeed I'm using Single Table Inheritance and I want to display a dropdown list or showdialog for children.
This feature was added in `master` branch ([PR #2917](https://github.com/sonata-project/SonataAdminBundle/pull/2917)) but it's still not added in `2.3.6` branch.

When I edit the `composer.json` file and set the dependency for admin-bundle to 'dev-master', it fetches the `2.3.6` branch.

What should I said to my `composer.json` to get this feature?

Thanks!

**Comment by pulzarraider** [comment]
If you want to try `dev-master` of `SonataAdminBundle`, you should set also `sonata-project/doctrine-orm-admin-bundle` to `dev-master`.

**Comment by Brah0um** [comment]
It works! Thanks a lot!

**Comment by pulzarraider** [comment]
You're welcome @Brah0um
