### ISSUE TITLE
Form name changed.

### ISSUE THREAD

**Issue by rifeman2007** [sonata-project/SonataAdminBundle#3358]
Hi Guys,

Why is it the form name is changed after the submission?

Before submitting the form

array(1) { ["s561a8ad02ac5f"]=> array(4) { ["note"]=> string(6) "ewrewr" ["_token"]=> string(43) "aExeXfHPi0df4qkd-S3IA1Vr3LoxcI-0WuqvoNSELd4" } }

And after the submission.
s561a8ad79e1ca

Any idea what's wrong with it? I am using a custom controller btw,

Any help is greatly appreciated.

Thanks.

**Comment by pulzarraider** [comment]
Form name is defined by `uniqid` parameter. If this value is not available, it`s [generated](https://github.com/sonata-project/SonataAdminBundle/blob/master/Admin/Admin.php#L2040).

Your target action of your custom form should contain the `uniqid` parameter to make the form name the same, e.g.:  `<form action="/some-custom-form/1/edit?uniqid=s123"  method="POST">`
