### ISSUE TITLE
Wrong value in show template for percent

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3360]
Came from:
https://github.com/sonata-project/SonataAdminBundle/pull/2573

My percent value defined in entity:
```php
    /**
     * @var string
     * @ORM\Column(type="integer", length=3, name="night_surcharge")
     */
    private $nightSurcharge;
```

Which results in an `INT(11)` - should be INT(3) btw.

In my `list` and show `mapper` I use type `percent`.

Then my *30* percent becomes `3.000 %`. German format with `.` as thousands seperator.
Shouldn't it be `30 %` or `30.00 %` depending on precision?

The current template simply multiplies with **100**:
```twig
{% block field %}
    {% set value = value * 100 %}
    {{ value }} %
{% endblock %}
```

https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/CRUD/list_percent.html.twig

**Comment by OskarStark** [comment]
yes it should IMO

**Comment by pulzarraider** [comment]
This template expects number with decimal fraction (float or decimal), e.g. `0.3`, not the integer.

This template is replaced with [the extended version](https://github.com/sonata-project/SonataIntlBundle/blob/master/Resources/views/CRUD/list_percent.html.twig) if you use the [`SonataIntlBundle`](https://github.com/sonata-project/SonataIntlBundle). In that case [PHP NumberFormatter](http://php.net/manual/en/class.numberformatter.php) is used to format the values specified on current user locale.
