### ISSUE TITLE
Lists with big width overflow not showing bottom scrollbar

### ISSUE THREAD

**Issue by clytemnestra** [sonata-project/SonataAdminBundle#3362]
I generated a module for modifying my users. The table is pretty big so it is very long. Currently, there is no way to scroll, except using Shift+mousewheel. There is no scrollbar. The only way to see the rest of the table is to zoom out, but that's not really a good option.

```bash
    "require": {
    "php": ">=5.3.9",
    "symfony/symfony": "2.7.*",
    "doctrine/orm": "~2.2,>=2.2.3,<2.5",
    "doctrine/dbal": "<2.5",
    "doctrine/doctrine-bundle": "~1.4",
    "symfony/assetic-bundle": "~2.3",
    "symfony/swiftmailer-bundle": "~2.3",
    "symfony/monolog-bundle": "~2.4",
    "sensio/distribution-bundle": "~4.0",
    "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
    "incenteev/composer-parameter-handler": "~2.0",
    "doctrine/doctrine-migrations-bundle": "^1.0",
    "friendsofsymfony/user-bundle": "~2.0@dev",
    "cunningsoft/chat-bundle": "^0.4.0",
    "knplabs/knp-time-bundle": "^1.3",
    "knplabs/knp-paginator-bundle": "^2.4",
    "knplabs/knp-menu-bundle": "~2",
    "twig/extensions": "^1.3",

    "sonata-project/core-bundle": "^2.3",
    "sonata-project/block-bundle": "^2.3.8",
    "sonata-project/admin-bundle": "dev-master",
    "sonata-project/doctrine-orm-admin-bundle": "^2.3"
},
```

This is how it looks, as you can see I am lacking a lot of fields, hidden to the right

![image](https://cloud.githubusercontent.com/assets/7060048/10428240/b159c976-70f8-11e5-82b7-9a8ccdfb4ca8.png)

On zooming out...

![image](https://cloud.githubusercontent.com/assets/7060048/10428251/bd96bb7c-70f8-11e5-83d4-e2b8abaa3496.png)

**Comment by greg0ire** [comment]
Hi, sorry but as you may already know, Sonata 2 is no longer supported. Please reopen if you still experience this with Sonata 3.
