### ISSUE TITLE
Display Fields Error Messages

### ISSUE THREAD

**Issue by TaqiOfficial** [sonata-project/SonataAdminBundle#3366]
I have a form configure wiht sonata admin bundle. On the form field field i have done error handling using `assert/regex`. I want to display errors just below the error field. The issue whenever a field has error the error is just shown for a `nano second` and disappers  and rouine errors comes `An error has occurred during update of item "345345".`

Why it is, is there any setting needed to be done to display these error messages?.

**Comment by greg0ire** [comment]
> rouine errors

?

Closing, but feel free to reopen if you still experience this with Sonata 3.
