### ISSUE TITLE
Navbar moving along with sidebar on collapsing the sidebar

### ISSUE THREAD

**Issue by clytemnestra** [sonata-project/SonataAdminBundle#3367]
Collapsing the left sidebar, the navbar containing the filters and the list type collapses at the same time with it, then fits back into place.
![image](https://cloud.githubusercontent.com/assets/7060048/10436652/7c8f6416-7130-11e5-873a-60207b26508e.png)

Here you can see it is getting dragged along with the left menu. You can see on the right side of it that it doesn't occupy that space anymore. It will occupy it after the animation finishes.
![image](https://cloud.githubusercontent.com/assets/7060048/10436656/80e35018-7130-11e5-8b58-9eedb2189f48.png)

Same issue on the sandbox demo website.

Also, if I remember right, the animation used to be different on collapse. It used to bounce towards the end. Where did that go?

```bash
    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.7.*",
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~4.0",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "doctrine/doctrine-migrations-bundle": "^1.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "cunningsoft/chat-bundle": "^0.4.0",
        "knplabs/knp-time-bundle": "^1.3",
        "knplabs/knp-paginator-bundle": "^2.4",
        "knplabs/knp-menu-bundle": "~2",
        "twig/extensions": "^1.3",

        "sonata-project/core-bundle": "^2.3",
        "sonata-project/block-bundle": "^2.3.8",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3"

    },
```

**Comment by greg0ire** [comment]
We do not support Sonata 2 anymore, sorry. Feel free to reopen if you experience this bug with Sonata 3

**Comment by clytemnestra** [comment]
It's an old bug that got solved in the meantime.
