### ISSUE TITLE
Variable "admin" does not exist when not on prod env

### ISSUE THREAD

**Issue by MortisQc** [sonata-project/SonataAdminBundle#3376]
I'm trying to add a custom controller with custom route, action and view to show reports and stats. 
When accessing it in dev env (app_dev.php/admin/report/index) I get this error message:

```html
Variable "admin" does not exist in SonataAdminBundle::standard_layout.html.twig at line 76 
```

But when I access it on prod env (/admin/report/index) then it works perfectly, 
I cleared cache, tried on other work stations, 

I did not see anything about that on cookbooks and tutorials about custom controllers and views in Sonata Admin Bundle. 

Any thoughts / help ? 
Thanks in advance. 

I'm using  
```composer
"name": "sonata-project/admin-bundle",
"version": "2.3.4",
```

The Controller file:
```php
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use AppBundle\Form\FormType;
use Symfony\Component\HttpFoundation\Request;

/**
 * Generic report controller.
 *
 * @Route("/admin/report")
 */
class ReportController extends Controller
{
    /**
     * @Route(path="/index", name="index_report")
     */
    public function indexAction(Request $request){
        $form = $this->createForm(new FormType());
        $data = array();

        if($request->getMethod() == 'GET'){
            $form->handleRequest($request);
            $data = $form->getData();
/*
...
...
*/
        }
$admin_pool =  $this->get('sonata.admin.pool');
        return $this->render('AppBundle:View:index.html.twig', array(
            'action'     => 'view',
            'form' => $form->createView(),
            'data'  => $data,
            'admin_pool' => $admin_pool,
        ));
    }
```

The view that overrides the standard_layout.html.twig
```twig
{% extends "SonataAdminBundle::standard_layout.html.twig" %}

```

**Comment by pulzarraider** [comment]
In dev mode more notices are reported directly to help the developer improve his code.

Your custom controller should extend the Sonata's  `CRUDController` or you should define all variables that are used in the template. 
The `admin` variable is defined in the [`render` method](https://github.com/sonata-project/SonataAdminBundle/blob/2.3/Controller/CRUDController.php#L176).
