### ISSUE TITLE
Autocomplete type as a component

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataAdminBundle#3378]
The auto-complete type is very useful on admin, but could be useful on another sections too.

BTW, some users could get interested by this auto-complete type without admin-bundle.

Would be great to made it as a symfony-form component.

I have the idea for this type, but maybe another could have the same thing.

What do you think?

cc @pulzarraider

**Comment by ElectricMaxxx** [comment]
:+1:

**Comment by mihai-stancu** [comment]
Doesn't an auto-complete type require an action to return the values?

Separating them implies adding some logic regarding the action itself.

**Comment by Soullivaneuh** [comment]
> Doesn't an auto-complete type require an action to return the values?

Yes I think so. We have to check if the logic could be separated or not.

**Comment by jordisala1991** [comment]
This issue is related to #4819 

Closing for now. Im trying to unify issues that are the same. If you still think this is not related, please feel free to reopen it
