### ISSUE TITLE
Issues with the deprecated initRuntime() Twig method

### ISSUE THREAD

**Issue by javiereguiluz** [sonata-project/SonataAdminBundle#3401]
I'm getting this deprecation message while upgrading a Symfony app to 2.8:

```
Defining the initRuntime() method in an extension is deprecated. Use
the `needs_environment` option to get the Twig_Environment instance
in filters, functions, or tests; or explicitly implement
Twig_Extension_InitRuntimeInterface if needed (not recommended)
```

The problem is located here: https://github.com/sonata-project/SonataAdminBundle/blob/master/Twig/Extension/SonataAdminExtension.php#L57

**Comment by Soullivaneuh** [comment]
Not related to Symfony but Twig: https://github.com/twigphp/Twig/blob/fd84403ac725fe1a053a0a109e26ecdb9928c912/CHANGELOG#L5
