### ISSUE TITLE
Global search throws exception on dev

### ISSUE THREAD

**Issue by fenusa0** [sonata-project/SonataAdminBundle#3423]
Hi,
Every time I perform a global search on dev environment throws the exception ' An exception has been thrown during the rendering of a template ("Class does not exists") in SonataAdminBundle:Core:search.html.twig at line 40'.
On prod environment works fine, but keeps breaking on dev.
I'm using the latest version, on top of Symfony 2.7.
Thanks!

**Comment by core23** [comment]
Can you say something more? I think this is a local problem, not related to this bundle.
