### ISSUE TITLE
Is it possible to add a EventListener at a DatagridMapper?

### ISSUE THREAD

**Issue by DevMaster112** [sonata-project/SonataAdminBundle#3427]
I want to build a dynamic filter in configureDatagridFilters.
So if the user select an value in the choice-list of the filter some additional filters should be displayed. 

E.g. 
>The User selects value "Evaluate all Employee in Branch" in "Evaluation"-Filter. Then the filter >"Branch" should be displayed additionally at the 'filterview'. 
>But if the user selects value "Evaluate all Contracts for Employee" in "Evaluation"-Filter then the filter >"Employee" should be displayed additionally.

It's important that the user cannot change the filters so the filter is static to the user.

It is possible to add a form listener event for the formmapper (see: https://gist.github.com/webdevilopers/fef9e296e77bb879d138)

So is it possible for a datagridFilter in configureDatagridFilters? 
How can i do it or is there a workaround? @pulzarraider @OskarStark

**Comment by OskarStark** [comment]
to be honest, i don't know this.. sorry :(

**Comment by DevMaster112** [comment]
I got an little workaround for it:
Doing it by jQuery and change()-Function in the twig-template. (See: https://api.jquery.com/change/)

So if the user will change the choice-value in "evaluation" the div-tags of the filters will get `display: none` style and filter-forms the user should edit will get `display: block` style.

I think its a kind dirty of doing it in twig directly with javascript and jquery. 
Maybe its possible to implement such a function into SonataAdmin to the configureDatagridFilters as i said in my issue above.

```twig
{% block javascripts %}
    {{ parent() }}

    <script>

        function initForm() {
            {% for filter in admin.datagrid.filters %}
                {% if filter.name != 'evaluation' %}
                    $("#filter-{{ filter.name|replace({'.' : '_'}) }}").css('display', 'none');
                {% endif %}
            {% endfor %}
        }

        function handleEvaluationForm() {
            var evaluation = $("#{{ form.evaluation.vars.id }}_value option:selected").val();

            switch(evaluation)
            {
                case '{{ constant('SomeNamespace\\Evaluation::filterTimekeepingEmployeeBranch') }}':
                    $("#filter-date").css('display', 'block');
                    $("#filter-night_shift_start").css('display', 'block');
                    $('#filter-employee_employmentContracts_branch').css('display', 'block');
                    break;
                case '{{ constant('SomeNamespace\\Evaluation::filterJobfunctionBranch') }}':
                    $("#filter-date").css('display', 'none');
                    $("#filter-night_shift_start").css('display', 'none');
                    $('#filter-employee_employmentContracts_branch').css('display', 'none');
                    break;
            }
        }

        $(document).ready(function() {
            $("#{{ form.evaluation.vars.id }}_value").change(handleEvaluationForm)
            initForm();

        });

    </script>
{% endblock %}
```

**Comment by OskarStark** [comment]
what about throwing some events when the filters are changed?
afterwards you can register on these listerns to perform some actions

**Comment by DevMaster112** [comment]
im doing the handling of changes in filters by javascript now in the twig template. 
was the fastest and easiest way to do what i want to have. 

but i didn't found any solution by doing it with the configureDatagridFilters in my admin class.

**Comment by OskarStark** [comment]
Thanks for your feedback @DevMaster112
