### ISSUE TITLE
How to Auto Post on Facebook Page in Admin

### ISSUE THREAD

**Issue by Siddharth22** [sonata-project/SonataAdminBundle#3430]
I am using Symfony2.6 + Sonata Admin in my project. I want to know that How I can auto post my video blogs on facebook page when admin create video blogs in admin ? It's possible with sonata admin ?

**Comment by pulzarraider** [comment]
@Siddharth22 There is no direct support for Facebook API in SonataAdmin. You should use Facebook PHP SDK (or some other library) than can help you communicate with Facebook API.

Inside your Admin you can use the [`postPersist` saving hook](https://sonata-project.org/bundles/admin/master/doc/reference/saving_hooks.html#saving-hooks). In this method you can do anything with the object after it's stored in the database.

Example:

```
<?php

namespace Your\Bundle\AdminBundle\Admin;

use Sonata\AdminBundle\Admin\Admin;

class VideoBlog extends Admin
{    
    private $facebookApi;

    // inject the facebook API service with dependency injection
    public function setFacebookApi($facebookApi)
    {
        $this->facebookApi = $facebookApi;
    }

    public function postPersist($object)
    {
        $title = $object->getTitle();
	$videoUrl = $object->getVideoUrl();

	// use facebook API to post the data to facebook
        $this->facebookApi->...
    }
}
```

**Comment by Siddharth22** [comment]
Thanks for help :+1:
