### ISSUE TITLE
Use Crowdin for translations

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/SonataAdminBundle#3431]
Opening this issue here as this seems to be the main repository:

I mentioned in sonata-project/SonataMediaBundle#891 that we could use Crowdin for translation management.

https://crowdin.com/page/open-source-project-setup-request

**Comment by OskarStark** [comment]
ping @sonata-project/contributors

**Comment by OskarStark** [comment]
i like this idea, but don't know how to implement it in a way that works

**Comment by sagikazarmark** [comment]
Several other projects use it: Akeneo, Cachet.

**Comment by sagikazarmark** [comment]
Any news?

**Comment by sagikazarmark** [comment]
@ping @OskarStark @rande

**Comment by rande** [comment]
@sagikazarmark we are busy on migrating the code base to work on sf2.8 and 3.0. We might look at this solution after this work. 

Thanks.

**Comment by greg0ire** [comment]
Closing in favor of https://github.com/sonata-project/dev-kit/issues/98

**Comment by core23** [comment]
You forgot the "Close" button @greg0ire  ;)

**Comment by greg0ire** [comment]
lol silly me!
