### ISSUE TITLE
Allowing Symfony 3.0

### ISSUE THREAD

**Issue by mihai-stancu** [sonata-project/SonataAdminBundle#3432]
Testing a migration to Symfony 3.0 (BETA) is currently not possible due to the version requirements of sonata-project packages.

I've seen many Symfony related packages requiring symfony packages via  `~2.3|~3.0` in order to cover both the 3.0 migration (ex. in their dev branches).

**Comment by rande** [comment]
Can you create a PR ?

**Comment by mihai-stancu** [comment]
I'm working on one.

**Comment by OskarStark** [comment]
:+1: thank you @mihai-stancu

**Comment by mihai-stancu** [comment]
`knp-menu-bundle` allows Symfony 3.0 in its master but doesn't have a dev branch/tag pointing to master. What should branch should I reference?

**Comment by mihai-stancu** [comment]
Using a fictitious `2.2@dev` branch seems to work.

**Comment by mihai-stancu** [comment]
Wow this is such a house of cards, forking sonata-project/... admin, doctrine-orm, block, core, cache, exporter and still going.

**Comment by mihai-stancu** [comment]
@rande appears to have added support for sf3 across most sonata projects.

I'll close this issue.
