### ISSUE TITLE
[Batch] Provide possibility easy creation of extended confirmation page with form, for example

### ISSUE THREAD

**Issue by Koc** [sonata-project/SonataAdminBundle#3433]
Currently we have page for batch editing of the products with custom form. We should set `ask_confirmation = false` and handle confirmation manually in our action. Also a lot of templates code duplicates. I think, that this part can be improved a lot.

**Comment by amine2z** [comment]
@Koc can you explain more? with some code exemple

**Comment by OskarStark** [comment]
sounds good to me :+1:

**Comment by core23** [comment]
Related to https://github.com/sonata-project/SonataAdminBundle/issues/4069

**Comment by jordisala1991** [comment]
To me it seems the same as #4105 

Closing because I am trying to unify isssues. If you think this is a completely different issue, please ping me to reopen.
