### ISSUE TITLE
"sensio/generator-bundle": "v3.0.0" is not allowed

### ISSUE THREAD

**Issue by tubssp** [sonata-project/SonataAdminBundle#3438]
Problem 1
    - sonata-project/admin-bundle 2.3.7 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.7 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - Installation request for sonata-project/admin-bundle v2.3.7 -> satisfiable by sonata-project/admin-bundle[2.3.7].

if i install "sensio/generator-bundle": "v3.0.0" become i this error.

can you allow version 3.0.0 from sensio/generator-bundle

**Comment by OskarStark** [comment]
can you please provide a PR with this change?

Thank you @tubssp

**Comment by OskarStark** [comment]
close because of:
https://github.com/sonata-project/SonataAdminBundle/pull/3451#issuecomment-161200360
