### ISSUE TITLE
sonata_type_model_autocomplete causing "An invalid form control with name='' is not focusable"

### ISSUE THREAD

**Issue by johnpancoast** [sonata-project/SonataAdminBundle#3446]
I have a category entity with a parent_id field linking child categories to their parents. The entity is setup similar to Doctrine's example here: http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/reference/association-mapping.html#one-to-many-self-referencing

I want the category admin to be able to specify a category's parent *or* its children although the former is irrelevant for now. I'm just focused on the children.

I add the field in admin like this

```php
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('title', 'text')
           ... other stuff ...
            ->add('children', 'sonata_type_model_autocomplete', [
                'property' => 'title',
                'multiple' => true,
                'to_string_callback' => [$this, 'getObjectPropertyValue'],
            ])
        ;
    }

    protected function getObjectPropertyValue($object, $property)
    {
        if (!$this->propertyAccessor) {
            $this->propertyAccessor = PropertyAccess::createPropertyAccessor();
        }

        return $this->propertyAccessor->getValue($object, $property);
    }
```

The 'Children' field works fine in admin. Meaning, i get the autocomplete form for multiple categories and the queries work fine and I can select multiple children by name to go into the field. But when I attempt to save, I receive the following error in chrome console and the form never saves. `An invalid form control with name='' is not focusable`. If I remove this field, all works fine.

Maybe it has to do with field name ambiguity (since they're both "title")? However, the parent field does work fine (which are both also named "title") so.... I do not know.

**Comment by pulzarraider** [comment]
@johnpancoast can you please specify which version of SonataAdmin and SonataDoctrineORMAdmin do you use? And also which browser and version trhrows this js error?

**Comment by johnpancoast** [comment]
This was awhile back. I was in a rush and was unable to provide it at the time, unfortunately and I don't remember versions. Switching to master resolved it so I'm going with that for now (although I locked to a specific commit).
