### ISSUE TITLE
[SF 2.8] Argument 1 passed to Symfony\Component\Form\Extension\Core\Type\ChoiceType::normalizeLegacyChoices() must be of the type array, null given

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataAdminBundle#3452]
On Symfony 2.8 only, with the following form config:

```php
->add('groups', 'sonata_type_model', ['required' => false, 'expanded' => true, 'multiple' => true])
```

I got the following error:

```
Catchable Fatal Error: Argument 1 passed to Symfony\Component\Form\Extension\Core\Type\ChoiceType::normalizeLegacyChoices() must be of the type array, null given, called in /home/projects/project/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php on line 266 and defined
```

Seems to be related to this config line: https://github.com/sonata-project/SonataAdminBundle/blob/09cb3bf45b4c662059c668173f3c85234d825767/Form/Type/ModelType.php#L105

If i replace `null` by `array()`, no error thrown but my choice form is empty.

Don't know wait if it's a Symfony or a Sonata issue, some investigation is needed.

**Comment by Trip09** [comment]
@Soullivaneuh, same here>> (sorry) https://github.com/sonata-project/SonataAdminBundle/issues/3453 PR is open

**Comment by Trip09** [comment]
@Soullivaneuh fix in PR https://github.com/sonata-project/SonataAdminBundle/pull/3455

**Comment by mediamonks-robert** [comment]
Can a new tag be created for this?

**Comment by binarious** [comment]
I'm also waiting for a tag.

**Comment by j0k3r** [comment]
By upgrading to Symfony 2.7.9 or 2.8.2, it should be ok without that change: https://github.com/symfony/symfony/commit/f3c2a9bedaad10633874b6bf89a95d0eb4a0c7fc
