### ISSUE TITLE
sonata_type_model compatible with Symfony 2.8 

### ISSUE THREAD

**Issue by Trip09** [sonata-project/SonataAdminBundle#3453]
normalizeLegacyChoices Forces the use of an array in Defaults 'choices', this will be only supported until version 3.0

**Comment by Trip09** [comment]
normalizeLegacyChoices(array &$choices, $choiceLabels, &$nextKey = 0)
if &$choices == null an error is thrown
PR::
https://github.com/sonata-project/SonataAdminBundle/pull/3454

**Comment by trihtm** [comment]
@Trip09 Hi, you can find the answer here: https://github.com/sonata-project/SonataClassificationBundle/pull/165

**Comment by Trip09** [comment]
@trihtm you can look into the solution on https://github.com/sonata-project/SonataAdminBundle/issues/3455 this PR is close
