### ISSUE TITLE
[BC] KNP Menu Bundle ends up in an uninstallable set of packages

### ISSUE THREAD

**Issue by sagikazarmark** [sonata-project/SonataAdminBundle#3459]
Introduced here:

https://github.com/sonata-project/SonataAdminBundle/commit/d9c85b2a76f72e23b861e33d0f67abdc4ea2c963#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780L40

```
  Problem 1
    - remove sonata-project/admin-bundle 2.4.x-dev|keep sonata-project/admin-bundle dev-master
    - sonata-project/admin-bundle 2.4.x-dev requires knplabs/knp-menu-bundle dev-master -> no matching package found.
    - sonata-project/admin-bundle dev-master requires knplabs/knp-menu-bundle dev-master -> no matching package found.
    - Installation request for sonata-project/admin-bundle ~2.4@dev -> satisfiable by sonata-project/admin-bundle[2.4.x-dev].
```

**Comment by sagikazarmark** [comment]
Solution: `"knplabs/knp-menu-bundle": "^2.1@dev"` in composer.json

**Comment by pulzarraider** [comment]
We are waiting here for releasing stable version of `knplabs/knp-menu-bundle`, that supports Sf 3.0. Until it's done you have to specifiy the `"knplabs/knp-menu-bundle": "dev-master",` in your composer.json.

**Comment by sagikazarmark** [comment]
Yeah, that's OK. Just wanted to report it, so that others find the issue quickly. Also, this is a BC breaking scenario, even if it is only true for a short time.

**Comment by DevMaster112** [comment]
Same issue. Thanks @sagikazarmark for the fast workaround!

**Comment by greg0ire** [comment]
knp menu bundle is now compatible with sf3, it seems. Closing.
