### ISSUE TITLE
sonata_type_admin form type issue

### ISSUE THREAD

**Issue by cosf87** [sonata-project/SonataAdminBundle#3460]
I have an entity 'Employee' and I embed an entity 'User' with 'sonata_type_admin' form type (one to one relation).
```
protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->tab('General')
                ->with('---')
                    ->add('name')
                    ->add('surnames')
                ->end()
            ->end()
            ->tab('Access')
                ->with('---')
                    ->add('user', 'sonata_type_admin')
                ->end()
            ->end()
        ;
    }
```
When I create a new Employee object I want to set default values to User object, but User __construct() or getNewInstance() method is never called.
Maybe it is a bug?

Thanks.

**Comment by DavidG04** [comment]
Hi, can you post your user admin configureFormField method code and  your orm configuration for the oneToOne relation ?

**Comment by cosf87** [comment]
Hi @DavidG04 
I extended my user entity from SonataUserBundle (FOSUserBundle). 
```
//User.orm.xml
...
    <entity name="Application\Sonata\UserBundle\Entity\User" table="fos_user_user">

        <id name="id" column="id" type="integer">
            <generator strategy="AUTO" />
        </id>
        
        <one-to-one field="employee" target-entity="AppBundle\Entity\Employee" mapped-by="user" />
    </entity>

</doctrine-mapping>
```

My Employee entity is in AppBundle.
```
//Employee.php
namespace AppBundle\Entity;

use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Doctrine\ORM\Mapping as ORM;

/**
 * Session
 *
 * @ORM\Table(name="nup_employee")
 * @ORM\Entity(repositoryClass="AppBundle\Entity\EmployeeRepository")
 */
class Employee
{
    const STATUS_INACTIVE = 0;
    const STATUS_ACTIVE = 1;
    
    use TimestampableEntity;
    
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    /**
     * @ORM\OneToOne(
     *  targetEntity="Application\Sonata\UserBundle\Entity\User", 
     *  inversedBy="employee", 
     *  cascade={"persist", "remove"}
     * )
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=true, onDelete="SET NULL")
     */
    private $user;
...
```

```
//UserAdmin.php
...
protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->with('General')
                ->add('username')
                ->add('email')
                ->add('plainPassword', 'text', array(
                    'required' => (!$this->getSubject() || is_null($this->getSubject()->getId()))
                ))
            ->end()
        ;

        $formMapper
            ->with('Security')
                ->add('enabled', null, array('required' => false))
                ->add('locked', null, array('required' => false))
                ->add('token', null, array('required' => false))
                ->add('twoStepVerificationCode', null, array('required' => false))
            ->end()
        ;
    }
...
```

I also noticed that user validation constraints don't work when I edit an Employee (for instance, if I edit an employee and I try to set an username that already exists, validation constraint is not displayed on username field). If I edit an user, __construct(), getNewInstance() and validation constraints works fine.

Thanks for your help.

**Comment by DavidG04** [comment]
Ok, i m sorry but i don t test your code now because i don t have my computer with me. But you can make two simple test :

First, try to invert your bidirectional relashionship (inversedby and mappedby) notre the cascade.

Second: change the type admin by a type collection for test and try to add a new user in your employee (maybe you must change your oneToOne in manytoone for this test)

**Comment by DavidG04** [comment]
Not manytoone sorry onetomany is better in your case

**Comment by cosf87** [comment]
@DavidG04, I was on holidays last days so I couldn't test your tests.
If I change 'sonata_type_admin' field type to 'sonata_type_model_list' or  'sonata_type_model' (I have to change one-to-one relationship to many-to-one), construct and validation work fine when I try to add new object (in a popup which is displayed).
However, I would like to understand why is not working on one-to-one relationship with 'sonata_type_admin' field type, because is the best solution for my issue.
Any ideas about that?
Thanks for your help.

**Comment by DavidG04** [comment]
Ok, no problem, can you post the service declaration for employee admin class. I test your code in my environment and reply to you

**Comment by cosf87** [comment]
Here my service declaration for Employee admin
```
services:
...
    sonata.admin.employee:
        class: AppBundle\Admin\EmployeeAdmin
        arguments: [~, AppBundle\Entity\Employee, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Employee }
```
Thanks.

**Comment by DavidG04** [comment]
Ok, i have test your code in my environment. it's work fine when I create an Employee. I have the same composer.json , but i just declare the admin code in the user field in employee admin

```
protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->tab('General')
            ->with('---')
            ->add('test')
            ->end()
            ->end()
            ->tab('Access')
            ->with('---')
            ->add('user', 'sonata_type_admin', array(),array(
                'admin_code' => 'sonata.user.admin.user',
            ))
            ->end()
            ->end()
        ;
    }
```
Test this

**Comment by cosf87** [comment]
Construct and validation still not working. For instance, if I set default values in User entity construct
```
//Application\Sonata\UserBundle\Entity
...
    public function __construct()
    {
        parent::__construct();
        $this->enabled = true;
    }
```
When I create new Employee object 'enabled' field of user embedded form is set to false, but if I create  new User object 'enabled' field is set to true.
Also, if  I create new Employee object and I don't fill 'username' field a global error is only displayed, but if I do this in new User object error is also displayed on the field

**Comment by DavidG04** [comment]
Ok, For your first problem it's normal. Sonata don't instanciate a new user on employee create because it's don't know if the property is nullable or not (it's different if you create a user because if you create a user the user is required). if you want instanciate a new user on employee create you must push the data on field
```
    protected function configureFormFields(FormMapper $formMapper)
    {
        $data = new User();
        if ($this->getSubject()->getUser()) {
            $data = $this->getSubject()->getUser();
        }

        $formMapper
            ->tab('General')
            ->with('---')
            ->add('test')
            ->end()
            ->end()
            ->tab('Access')
            ->with('---')
            ->add('user', 'sonata_type_admin', array(
                'data' => $data,
            ),array(
                'admin_code' => 'sonata.user.admin.user',
            ))
            ->end()
            ->end()
        ;
    }
```

and for the error bubble i try and i reply to you

**Comment by DavidG04** [comment]
For the error it's normal again, because the subject is not the same and the user admin in employee admin is a clone. In your case the sonata_type_admin is not the best way. you may create a formType for your user and call this form type in user admin and employee admin. After you can manage data and error in the form type

**Comment by cosf87** [comment]
@DavidG04 thanks for your answer for the first problem. 
Finally, I found the answer to solve field validation on embedded User entity. I had to add Valid constraint on user mapping on Employee entity and add validations groups related to FOSUserBundle in EmployeeAdmin.
```
class Employee
{
...    
    /**
     * @ORM\OneToOne(
     *  targetEntity="Application\Sonata\UserBundle\Entity\User", 
     *  inversedBy="employee", 
     *  cascade={"persist", "remove"}
     * )
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id", nullable=true, onDelete="SET NULL")
     * @Assert\Valid
     */
    private $user;
...
}
```

```
class EmployeeAdmin extends Admin
{
    public function getFormBuilder()
    {
        $this->formOptions['data_class'] = $this->getClass();

        $options = $this->formOptions;
        
        $options['validation_groups'] = array('Default');
        array_push($options['validation_groups'], (!$this->getSubject() || is_null($this->getSubject()->getId())) ? 'Registration' : 'Profile');

        $formBuilder = $this->getFormContractor()->getFormBuilder($this->getUniqid(), $options);

        $this->defineFormBuilder($formBuilder);
        
        return $formBuilder;
    }
...
}
```
