### ISSUE TITLE
 Unrecognized option "knp_menu_template" under "sonata_admin.templates"

### ISSUE THREAD

**Issue by marvoh** [sonata-project/SonataAdminBundle#3462]
I just updated my version on sonata-admin and getting the error above.

**Comment by OskarStark** [comment]
can you please post the output of ``composer show -i`` ?

**Comment by marvoh** [comment]
Here it is:

 

cocur/slugify                            v1.4               Converts a string into a slug.

doctrine/annotations                     v1.2.7             Docblock Annotations Parser

doctrine/cache                           v1.5.1             Caching library offering an object-oriented API for ma...

doctrine/collections                     v1.3.0             Collections Abstraction library

doctrine/common                          v2.5.1             Common Library for Doctrine projects

doctrine/dbal                            v2.5.2             Database Abstraction Layer

doctrine/doctrine-bundle                 1.6.1              Symfony DoctrineBundle

doctrine/doctrine-cache-bundle           1.2.2              Symfony Bundle for Doctrine Cache

doctrine/inflector                       v1.1.0             Common String Manipulations with regard to casing and ...

doctrine/instantiator                    1.0.5              A small, lightweight utility to instantiate objects in...

doctrine/lexer                           v1.0.1             Base library for a lexer that can be used in Top-Down,...

doctrine/orm                             v2.5.2             Object-Relational-Mapper for PHP

egeloen/ckeditor-bundle                  3.0.1              Provides a CKEditor integration for your Symfony2 Proj...

egeloen/json-builder                     2.0.0              JSON builder with escaping control for PHP 5.3+

friendsofsymfony/rest-bundle             1.7.2              This Bundle provides various tools to rapidly develop ...

friendsofsymfony/user-bundle             v1.3.6             Symfony FOSUserBundle

incenteev/composer-parameter-handler     v2.1.2             Composer script handling your ignored parameter file

jdorn/sql-formatter                      v1.2.17            a PHP SQL highlighting library

jms/metadata                             1.5.1              Class/method/property metadata management in PHP

jms/parser-lib                           1.0.0              A library for easily creating recursive-descent parsers.

jms/serializer                           1.1.0              Library for (de-)serializing data of any complexity; s...

jms/serializer-bundle                    1.1.0              Allows you to easily serialize, and deserialize data o...

knplabs/knp-menu                         v2.1.0             An object oriented menu library

knplabs/knp-menu-bundle                  v2.1.0             This bundle provides an integration of the KnpMenu lib...

kriswallsmith/assetic                    v1.3.2             Asset Management for PHP

michelf/php-markdown                     1.5.0              PHP Markdown

monolog/monolog                          1.17.2             Sends your logs to files, sockets, inboxes, databases ...

nelmio/api-doc-bundle                    2.10.3             Generates documentation for your REST API from annotat...

phpcollection/phpcollection              0.4.0              General-Purpose Collection Library for PHP

phpoption/phpoption                      1.5.0              Option Type for PHP

psr/log                                  1.0.0              Common interface for logging libraries

sensio/distribution-bundle               v4.0.4             Base bundle for Symfony Distributions

sensio/framework-extra-bundle            v3.0.11            This bundle provides a way to configure your controlle...

sensio/generator-bundle                  v2.5.3             This bundle generates code for you

sensiolabs/security-checker              v3.0.2             A security checker for your composer.lock

sonata-project/admin-bundle              2.3.x-dev c5b0944  Symfony SonataAdminBundle

sonata-project/block-bundle              2.2.13             Symfony SonataBlockBundle

sonata-project/cache                     1.0.7              Cache library

sonata-project/core-bundle               2.3.10             Symfony SonataCoreBundle

sonata-project/datagrid-bundle           dev-master 5f7106a Symfony SonataDatagridBundle

sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions

sonata-project/doctrine-orm-admin-bundle 2.3.3              Symfony Sonata / Integrate Doctrine ORM into the Sonat...

sonata-project/easy-extends-bundle       2.1.10             Symfony SonataEasyExtendsBundle

sonata-project/exporter                  1.4.1              Lightweight Exporter library

sonata-project/google-authenticator      1.0.2              Library to integrate Google Authenticator into a PHP p...

sonata-project/user-bundle               dev-master c6aeda9 Symfony SonataUserBundle

swiftmailer/swiftmailer                  v5.4.1             Swiftmailer, free feature-rich PHP mailer

symfony/assetic-bundle                   v2.7.1             Integrates Assetic into Symfony2

symfony/monolog-bundle                   v2.8.2             Symfony MonologBundle

symfony/swiftmailer-bundle               v2.3.9             Symfony SwiftmailerBundle

symfony/symfony                          v2.7.7             The Symfony PHP framework

twig/extensions                          v1.3.0             Common additional features for Twig that do not direct...

twig/twig                                v1.23.1            Twig, the flexible, fast, and secure template language...

willdurand/jsonp-callback-validator      v1.1.0             JSONP callback validator.

willdurand/negotiation                   1.5.0              Content Negotiation tools for PHP provided as a standa...

**Comment by greg0ire** [comment]
Hi, sorry but as you may already know, Sonata 2 is no longer supported. Please reopen if you still experience this with Sonata 3.
