### ISSUE TITLE
Is not Symfony 2.8 same as 3.0 but with warnings and deprecated? Why SonataAdmin fails with Symfony 2.8 fresh project?

### ISSUE THREAD

**Issue by reypm** [sonata-project/SonataAdminBundle#3468]
I'm trying to install latest SonataAdmin (dev-master) bundle in a Symfony 2.8 project but surprise I can't I don't even be asked about choose a branch or tag as said in [docs][1]. See the output below:

    composer require sonata-project/admin-bundle
    Using version ^2.3 for sonata-project/admin-bundle
    ./composer.json has been updated
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - sonata-project/admin-bundle 2.3.7 requires sensio/generator-bundle ~2.3 -> no matching package found.
        - sonata-project/admin-bundle 2.3.6 requires sensio/generator-bundle ~2.3 -> no matching package found.
        - sonata-project/admin-bundle 2.3.5 requires sensio/generator-bundle ~2.3 -> no matching package found.
        - sonata-project/admin-bundle 2.3.4 requires sensio/generator-bundle ~2.3 -> no matching package found.
        - sonata-project/admin-bundle 2.3.3 requires sensio/generator-bundle ~2.3 -> no matching package found.
        - sonata-project/admin-bundle 2.3.2 requires sensio/generator-bundle ~2.3 -> no matching package found.
        - sonata-project/admin-bundle 2.3.1 requires sensio/generator-bundle ~2.3 -> no matching package found.
        - sonata-project/admin-bundle 2.3.0 requires sensio/generator-bundle ~2.3 -> no matching package found.
        - Installation request for sonata-project/admin-bundle ^2.3 -> satisfiable by sonata-project/admin-bundle[2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7].

    Potential causes:
     - A typo in the package name
     - The package is not available in a stable-enough version according to your minimum-stability setting
       see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

    Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

    Installation failed, reverting ./composer.json to its original content.

Any advice?

 [1]: https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/doc/reference/installation.rst#downloading-the-code

**Comment by rande** [comment]
depends on the dependency tree you might not success to install sonata's bundles with sf2.8. So just wait a bit.

**Comment by ThibautAlgrin** [comment]
It's working for me.
This is my composer.json:

```
"require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "sonata-project/admin-bundle": "^2.3",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3",
        "sonata-project/media-bundle": "^2.3"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "symfony/phpunit-bridge": "~2.7",
	"phpspec/phpspec": "~2.0",
        "phpunit/phpunit": "4.8.*"
    },
```

**Comment by paquitodev** [comment]
@ThibautAlgrin mine looks like below and doesn't work:

    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "symfony/security-acl": "^2.7",
        "knplabs/knp-menu-bundle": "dev-master",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3",
        "sonata-project/block-bundle": "^2.3",
        "sonata-project/easy-extends-bundle": "^2.1",
        "avanzu/admin-theme-bundle": "^1.3",
        "symfony/assetic-bundle": "^2.7",
        "kevintweber/ktw-database-menu-bundle": "~0.5",
        "friendsofsymfony/user-bundle": "~2.0@dev"
    },
    "require-dev": {
        "sensio/generator-bundle": "~3.0",
        "symfony/phpunit-bridge": "~2.7"
    },

Can you try this setup on your side?

**Comment by jvasseur** [comment]
@ThibautAlgrin from your composer logs, the problem is with ``"sensio/generator-bundle": "~3.0"`` composer is trying to install the 2.3 version of the admin bundle that wants the ~2.3 version of the generator bundle.

You can try doing ``composer require sonata-project/admin-bundle:dev-master`` that would make composer try to install the last version of the bundle that is compatible with the new admin bundle.

**Comment by paquitodev** [comment]
@jvasseur lol ;) I think you want to advise me and not @ThibautAlgrin and yes, that's the fix I have found and I am using as you can see on the `composer.json`. @ThibautAlgrin just try my composer config with this line `"sonata-project/admin-bundle": "^2.3",` and you will see errors coming up.

**Comment by jvasseur** [comment]
@paquitodev yes it was you i wanted to mention.

The other solution would be to go back to an older version of the generator bundle (<3).

**Comment by andrewtch** [comment]
@rande , which version if Sonata bundles is expected to work with 3.0? 2.4 or 3.0?

**Comment by rande** [comment]
@andrewtch https://docs.google.com/spreadsheets/d/1fSpS10nzlEj9HE-GdZ-BHcxileEzHwRIzLlNfdNtZ2k/edit?pli=1#gid=0&vpid=C4 some information here

**Comment by andrewtch** [comment]
So, apart from Intl 2.4@dev seems to work fine. Excellent!

**Comment by valerymelou** [comment]
This worked for me:
* Change the required version of  `sensio/generator-bundle` from `~3.0` to `~2.3`
* Run `composer install`
* And finally `composer require sonata-project/admin-bundle`

**Comment by reypm** [comment]
Merry christmas to everyone here, now 

@valerymelou can you share your complete `composer.json`?

@rande can you share with us a properly *working* version of `composer.json`?

**Comment by valerymelou** [comment]
@reypm this is my complete `composer.json` after I installed the `sonata-project/admin-bundle`

```json
{
    "name": "valem/paposy",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "files": [
            "app/AppKernel.php"
        ]
    },
    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "sonata-project/admin-bundle": "^2.3",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3"
    },
    "require-dev": {
        "sensio/generator-bundle": "~2.3",
        "symfony/phpunit-bridge": "~2.7"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}
```

**Comment by reypm** [comment]
@valerymelou and which guide did you follow to setup the bundles? the current online at site or docs from here (the repo)? also did you try any other bundle as EasyExtend or SonataUser?

**Comment by valerymelou** [comment]
@reypm I followed [this guide] (https://sonata-project.org/bundles/admin/2-3/doc/reference/installation.html). I did try EasyExtendBundle and SonataUserBundle + FOSUserBundle but I couldn't get it to work. Actually I'm moving on with my project without the AdminBundle.

**Comment by SkobelevIgor** [comment]
According https://sonata-project.org/bundles/admin/2-3/doc/reference/installation.html you just need to specify "dev-master" version of bundle.

**Comment by ethernal** [comment]
Should SonataAdminBundle still run with deprecation notices? I use @dev-master and after updating Assetic and JMSSerializerBundle I only have FoSUserBundle 1.3 and SonataAdmin deprecation notices:

```bash
10:39:58 	php 	Accessing type "form" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\FormType" instead.

    FormRegistry::getType() (called from FormFactory.php at line 107)
    FormFactory::createNamedBuilder() (called from FormContractor.php at line 79)
    FormContractor::getFormBuilder() (called from classes.php at line 9086)
    Admin::getFormBuilder() (called from classes.php at line 8854)
    Admin::buildForm() (called from classes.php at line 9145)
    Admin::getForm() (called from CRUDController.php at line 403)
    CRUDController::editAction()
    call_user_func_array() (called from HttpKernel.php at line 139)
    HttpKernel::handleRaw() (called from HttpKernel.php at line 62)
    HttpKernel::handle() (called from ContainerAwareHttpKernel.php at line 69)
    ContainerAwareHttpKernel::handle() (called from Kernel.php at line 185)
    Kernel::handle() (called from app_dev.php at line 39)

10:39:59 	php 	Accessing type "choice" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\ChoiceType" instead.
10:39:59 	php 	Accessing type "sonata_type_model" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Sonata\AdminBundle\Form\Type\ModelType" instead. (2 times)
10:39:59 	php 	The value "false" for the "choices_as_values" option of the "choice" form type (Symfony\Component\Form\Extension\Core\Type\ChoiceType) is deprecated since version 2.8 and will not be supported anymore in 3.0. Set this option to "true" and flip the contents of the "choices" option instead. (2 times)
```

How should I change my code? Example generating the deprecations above:

```php
class UserGroupAdmin extends Admin
{
    protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->add('name')
        ;
    }

    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('name',null,array(
                    'label'=>'admin.core.userGroup.name.label',
                    'help'=>'admin.core.userGroup.name.help'
                    )
            )
            ->add('users','sonata_type_model',array(
                    'label'=>'admin.core.userGroup.users.label',
                    'help'=>'admin.core.userGroup.users.help',
                    'expanded'=>false,
                    'by_reference'=>false,
                    'multiple'=>true,
                    'btn_add'=>false,
                    )
            )
            ->end()
            ->with('admin.core.userGroup.tabs.associatedEntities')

                ->add('readRequests','sonata_type_model', array(
                    'label'=>'admin.core.userGroup.readRequest.label',
                    'help'=>'admin.core.userGroup.readRequest.help',
                    'expanded'=>false,
                    'required'=>false,
                    'by_reference'=>false,
                    'multiple'=>true,
                    'btn_add'=>false,
                    'attr'=>array('readonly'=>'readonly'),
                    )
                )
            ->end()
        ;
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('name')
            ->add('users')
        ;
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
                ->addIdentifier('name')
                ->add('users')
        ;
    }

}
```

A Cookbook entry would be more than welcome regarding that topic.

**Comment by greg0ire** [comment]
> Should SonataAdminBundle still run with deprecation notices?

No, it should not. We are trying to reduce them, but since we do not have 100% code coverage, we can't even be sure to detect them all. PRs are welcome to help reducing the notices, BTW.

**Comment by ethernal** [comment]
@greg0ire 
Ok then, as far as I can tell this should not be happening:

```bash
Accessing type "date" by its string name is deprecated since version 2.8 and will be removed in 3.0. Use the fully-qualified type class name "Symfony\Component\Form\Extension\Core\Type\DateType" instead.

    FormRegistry::getType() (called from FormRegistry.php at line 149)
    FormRegistry::resolveAndAddType() (called from FormRegistry.php at line 96)
    FormRegistry::getType() (called from FormFactory.php at line 107)
    FormFactory::createNamedBuilder() (called from FormBuilder.php at line 106)
    FormBuilder::create() (called from FormBuilder.php at line 267)
    FormBuilder::resolveChildren() (called from FormBuilder.php at line 215)
    FormBuilder::getForm() (called from ProtisReportMeanTicketTimeByTypeAdminController.php at line 90)
    ReportMeanTicketTimeByTypeAdminController::listAction()
    call_user_func_array() (called from HttpKernel.php at line 139)
    HttpKernel::handleRaw() (called from HttpKernel.php at line 62)
    HttpKernel::handle() (called from ContainerAwareHttpKernel.php at line 69)
    ContainerAwareHttpKernel::handle() (called from Kernel.php at line 185)
    Kernel::handle() (called from app_dev.php at line 39)
```

This gets invoked by:

```php
->add('dateFrom', DatePickerType::class, array(
                            'label'=>'admin.protis.report.monthly.dateFrom.label',
                            'required'=>true,
                            'input' => 'datetime',
                            'format' => 'yyyy-MM-dd',
                            'dp_default_date' => 'yyyy-MM-dd',
                            'dp_language' => 'pl',
                        
                ))
                ->add('dateTo',  DatePickerType::class,array(
                            'label'=>'admin.protis.report.monthly.dateFrom.label',
                            'required'=>true,
                            'input' => 'datetime',
                            'format' => 'yyyy-MM-dd',
                            'dp_default_date' => 'yyyy-MM-dd',
                            'dp_language' => 'pl',
                            'dp_use_current' => true,
                        
                ))
                ->add('generate', SubmitType::class, array('label'=>'form.admin.generateReport'))
                
                ->getForm()
                ;
```

I am using DatePickerType by it's class name but it seems somewhere along the way it's being changed into 'date' type as string, can you confirm/test?

**Comment by greg0ire** [comment]
Can confirm, see `DatePickerType::getParent()`

**Comment by greg0ire** [comment]
Would you create a PR to solve this ? It is just a matter of doing this in `getParent` I think : 

```
return method_exists('Symfony\Component\Form\FormTypeInterface', 'setDefaultOptions') ?
    'date':
    'Symfony\Component\Form\Extension\Core\Type\DateType';

```

**Comment by ethernal** [comment]
Sure, I'll test and try it out.

**Comment by ethernal** [comment]
I created a PR for SonatacoreBundle#234:  "Fix deprecation notices on getParent"
I'm new to this so I hope all is as it should. I check for the class not for the method as the old one does exist in 2.8 and that way it returns wrong parent.

**Comment by greg0ire** [comment]
@ethernal we want to return one thing in 2.7, and the other thing in 3.0 **and** 2.8 . Please use the test I provided.

**Comment by Soullivaneuh** [comment]
2.x branch of admin-bundle is not maintained anymore. Please upgrade to 3.0 and open another issue if the problem persists.
