### ISSUE TITLE
Filter multiple sub entity properties has errors 

### ISSUE THREAD

**Issue by rafrsr** [sonata-project/SonataAdminBundle#3475]
After update a project (with sonata 2.4@dev) to symfony 2.8 when try to add filters for multiple sub entity properties, only the last property appear in the filter.

eg.
````php
 ->add('address.street')
 ->add('address.ZIPCode')
 ->add('address.town')
````
the filters appears:

- town
- town
- town

and only one field appear in the filter form.

**Comment by rande** [comment]
@rafrsr Can you try to dig into the issue ? this is probably a template issue.

Thanks

**Comment by FrancoisMartin** [comment]
I had the same problem since 5443959ecea1b77fb6b0e053f49a1f657d76c70c.

This pull request solve the issue :
https://github.com/sonata-project/SonataAdminBundle/pull/3481
