### ISSUE TITLE
symfony 2.8.*@dev problem with 'sonata_type_model'

### ISSUE THREAD

**Issue by SkyAgency** [sonata-project/SonataAdminBundle#3477]
$formMapper
...
->add('category', 'sonata_type_model', array('required' => false, 'expanded' => false, 'multiple' => true, 'btn_add' => false))
...

When I use symfony 2.8.*@dev, I have error:

Catchable Fatal Error: Argument 1 passed to Sonata\AdminBundle\Form\DataTransformer\ModelsToArrayTransformer::__construct() must be an instance of Sonata\AdminBundle\Form\ChoiceList\ModelChoiceList, instance of Symfony\Component\Form\ChoiceList\LazyChoiceList given

When I use symfony 2.8.*, I have error:

Catchable Fatal Error: Argument 1 passed to Symfony\Component\Form\Extension\Core\Type\ChoiceType::normalizeLegacyChoices() must be of the type array, null given, called in /var/www/html/sym2_dbh/vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/Type/ChoiceType.php on line 266 and defined

**Comment by SkyAgency** [comment]
In symfony 2.8.*@dev second error fixed: https://github.com/symfony/symfony/issues/16792

**Comment by Trip09** [comment]
this is related to https://github.com/sonata-project/SonataAdminBundle/pull/3455

**Comment by paquitodev** [comment]
@Trip09 is this already merged in `@dev` branch? I am updating constantly my project and still seeing this issue all the time I am on SF 2.8

**Comment by rande** [comment]
should be fixed by https://github.com/sonata-project/SonataAdminBundle/pull/3504
