### ISSUE TITLE
SimpleChoiceList

### ISSUE THREAD

**Issue by lipiluk** [sonata-project/SonataAdminBundle#3492]
class ModelChoiceList extends ArrayChoiceList instead of SimpleChoiceList in ModelChoiceList.php from Symfony 2.8/+ .

**Comment by andrewtch** [comment]
yes, +1 (after installing manual dependency to symfony-acl I see this error)

**Comment by andrewtch** [comment]
Seems like that ```Sonata\AdminBundle\Form\ChoiceList\ModelChoiceList``` should extend now ```Symfony\Component\Form\ChoiceList\ArrayChoiceList```.

@rande , can you confirm?

**Comment by Id4v** [comment]
+1 same problem as @andrewtch 
Created a PR for this. 
Seems to break compatibility with sf2.3 but not sure this is a problem though.

**Comment by rande** [comment]
The ``choice_list`` option should not be used with sf2.7+. You must use the ``choice_loader`` options. See https://github.com/sonata-project/SonataAdminBundle/blob/9e8f0e60c78b6b410ed896079a6f86ecde491e42/Form/Type/ModelType.php#L85-L114

**Comment by andrewtch** [comment]
@rande , it is not about "usage", this error happens just after installing Sonata on 3.0 because of mailformed "Use". Consider reopening.

**Comment by Id4v** [comment]
+1 @andrewtch 
Having the same exception on a fresh Sf3.0 install.

After some investigation. 
`Sonata\AdminBundle\Form\ChoiceList\ModelChoiceList` is being listed in `./var/cache/classes.map`
Don't know why though, but it's clearly not linked with a misuse of `choice_list` option in custom code.

Anyway, with the use case that @rande described, making `Sonata\AdminBundle\Form\ChoiceList\ModelChoiceList` extends `Symfony\Component\Form\ChoiceList\ArrayChoiceList` doesn't seem the correct answer and #3499 seems irrelevant.

Main problem is more to find why `ModelChoiceList` is being loaded when it shouldn't with Sf2.7+.

**Comment by rande** [comment]
@ld4v ok got it. I need to alter the SonataAdminExtension.

**Comment by rande** [comment]
done!

**Comment by rande** [comment]
For reference: https://github.com/sonata-project/SonataAdminBundle/commit/d499812e8fe7c33cd322addd35d6b669fe00d4b5

**Comment by Id4v** [comment]
:+1:  Thanks @rande

**Comment by andrewtch** [comment]
Checked, works fine. Thank you!

**Comment by rande** [comment]
@Id4v please note, 3.0 support has not been properly tested. Unit test are ok, but it might have some issues.

**Comment by Id4v** [comment]
@rande Yes I know, I am just trying it on a test project. 
If I can help reporting/correcting some bugs in the process, it's a plus.
