### ISSUE TITLE
Wrong naming for Pager methods

### ISSUE THREAD

**Issue by imilyukov** [sonata-project/SonataAdminBundle#3494]
Please, look at this:
https://github.com/sonata-project/SonataAdminBundle/blob/master/Datagrid/Pager.php#L254
https://github.com/sonata-project/SonataAdminBundle/blob/master/Datagrid/Pager.php#L268

Is it correct?? 
Maybe there: Pager::getFirstIndex() and Pager::getLastIndex()??

Thanks.

**Comment by OskarStark** [comment]
changing this name would be a BC break..., but we can schedule this for the next major.

Are you willing to provide a PR?

**Comment by imilyukov** [comment]
PR?

**Comment by OskarStark** [comment]
Pull Request

**Comment by greg0ire** [comment]
ping @imilyukov

**Comment by greg0ire** [comment]
Reopen if you want to fix it @imilyukov

**Comment by greg0ire** [comment]
Actually it's an easy pick so I guess anyone could fix it. Let's tag it.
