### ISSUE TITLE
chrome broken caracters

### ISSUE THREAD

**Issue by ibasaw** [sonata-project/SonataAdminBundle#3497]
since few days, i got this in sonata admin and chrome

![bug sonata chrome](https://cloud.githubusercontent.com/assets/313704/11840673/00e516b4-a3ce-11e5-89e2-69dd16bd1c2a.jpg)

sf2.8.1 dev

**Comment by ibasaw** [comment]
this is very strange, got it only on one of my computers

**Comment by ibasaw** [comment]
i uninstall chrome, clean and re install it, and problem disapear

**Comment by rande** [comment]
@ibasaw you had probably change characters encoding in your browser.

**Comment by ibasaw** [comment]
@rande : i had verified, and no, i had changed nothing ;) i got an os updated and my chrome installation was old. problem solved

**Comment by OskarStark** [comment]
which OS?

**Comment by ibasaw** [comment]
win 10 64
