### ISSUE TITLE
2.4 Release

### ISSUE THREAD

**Issue by Enleur** [sonata-project/SonataAdminBundle#3509]
Any plans of a new stable release?

**Comment by Th3Mouk** [comment]
https://github.com/sonata-project/SonataAdminBundle/issues?q=is%3Aopen+is%3Aissue+milestone%3A2.4

**Comment by Enleur** [comment]
@Th3Mouk thanks, i saw it. Most of the milestone's issues have been stuck since the end of 2014 and 2.3.x versions don't provide support for symfony 3.0 and contain a lot of deprecated usages, meanwhile sonata's master branch already have support for such things

**Comment by Th3Mouk** [comment]
All my productions are on 2.3, and i can't move to 2.4 that IMO is more a 3.0 version.
This is a link for the current dependences issues : https://docs.google.com/spreadsheets/d/1fSpS10nzlEj9HE-GdZ-BHcxileEzHwRIzLlNfdNtZ2k/edit?pli=1#gid=0
The main problem is about the symfony form component.
