### ISSUE TITLE
Filtering data by string that ends on underscore does not work

### ISSUE THREAD

**Issue by IwfY** [sonata-project/SonataAdminBundle#3520]
I have a data set that contains string values which use underscores as separators.

That is why I want to filter by strings like 'A_'. When I do so all entities are returned that contain 'A' (also e.g. 'AB'). To get the filters to show what I want I have to insert 'A_'.

Filtering by e.g. 'A_B' works as expected.

Is this wanted behaviour? Can this be configured somehow?

**Comment by pulzarraider** [comment]
@IwfY thank you for reporting the problem.

In MySQL underscore `_` with ``LIKE` operator searchs for any single character. We have to escape `%` and `_` in [StringFilter.php](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Filter/StringFilter.php).

**Comment by jordisala1991** [comment]
Duplicated of https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/138

Closing this one as the bug appears on the other bundle, and has to be fixed there.
