### ISSUE TITLE
Get exception when try to export a list to csv, xml file

### ISSUE THREAD

**Issue by Hoannv** [sonata-project/SonataAdminBundle#3522]
I'm using SF2.3, Sonata Admin 2.2.*. I update dependencies today and getting this exception when try to export a list to csv, xml file

Fatal error: Class 'Symfony\Component\Form\Util\PropertyPath' not found in /vendor/sonata-project/exporter/lib/Exporter/Source/DoctrineORMQuerySourceIterator.php on line 47

**Comment by pulzarraider** [comment]
Sonata Admin 2.2 is not supported. Can you please try Sonata Admin 2.3?

**Comment by Hoannv** [comment]
thanks @pulzarraider
