### ISSUE TITLE
SonataAdmin and Symfony 2.8.x|3.0.x current status

### ISSUE THREAD

**Issue by reypm** [sonata-project/SonataAdminBundle#3545]
I know the team or the people behind Sonata has been working hard to get this done, I know there is a [document][1] talking about it (which I think it's outdated since has been a lot of PR on these past days) but, what's is the real status of the bundle on this moment? It's recommended for a new fresh backend project where I need to use FOSUserBundle and ACLs? Which is the status of the other Sonata Bundles? I think will be good if someone take care of this kind of info and put at README so there is not duplicates. At least I am following this bundle because I need it and will be good if we can keep informed about the status.

 [1]: https://docs.google.com/spreadsheets/d/1fSpS10nzlEj9HE-GdZ-BHcxileEzHwRIzLlNfdNtZ2k/edit#gid=0

**Comment by sc0rp10** [comment]
+1

**Comment by Icewild** [comment]
+1

**Comment by tape88** [comment]
+1

**Comment by sylvaindeloux** [comment]
+1

**Comment by Allchi** [comment]
+1

**Comment by redactuk** [comment]
+1

**Comment by dmitry-php** [comment]
+1

**Comment by reypm** [comment]
@core23 @rande guys any advice on this *"issue"*?

**Comment by core23** [comment]
As far as I know... There will be a Symfony 2.8+ support in the next 2.4 release, but there are some open issues https://github.com/sonata-project/SonataAdminBundle/milestones/2.4

@rande Can give you more informations, because he is the owner of this project ;)

**Comment by OskarStark** [comment]
One big problem is, that we don't have a stable FOSUserBundle which works with 2.8/3.0 ... :(

**Comment by redactuk** [comment]
@OskarStark Has anyone had any private communication with lead developer for FOSUserBundle? A stable v2 was promised in December but still nothing. Perhaps lead developers are having issues or need some help? Getting a stable FOSUSerbundle really needs to happen soon.

**Comment by OskarStark** [comment]
@redactuk the have a milestone for the 2.0 but IMO not all of the things are really needed.

no direct contact from my side, maybe @rande, but i don't know

**Comment by acrobat** [comment]
Yeah someone [is asking](https://github.com/FriendsOfSymfony/FOSUserBundle/issues/1951#issuecomment-173972645) for a 2.0 beta milestone. So hopefully they get that milestone setup soon, so we can help getting things done for a 2.0 release!

@OskarStark are there any other deps you know which block us from having 2.8/3.0 support? If we have a list of blocking deps we can create issues for it in their repo's or even try to fix it

**Comment by OskarStark** [comment]
yes we have:
https://docs.google.com/spreadsheets/d/1fSpS10nzlEj9HE-GdZ-BHcxileEzHwRIzLlNfdNtZ2k/edit?pli=1#gid=0

but i don't know WHAT is the exact problem of the nelmio stuff...

**Comment by acrobat** [comment]
Ok, geat! Is that spreadsheet still up to date?

**Comment by sylvaindeloux** [comment]
But FosUserBundle is not required by AdminBundle

**Comment by OskarStark** [comment]
No but an admin bundle without the possibility so secure it via the SonataUserBundle...

**Comment by sylvaindeloux** [comment]
Are [these issues](https://github.com/sonata-project/SonataAdminBundle/milestones/2.4) really needed by the next stable release?

It blocks the compatibility with Symfony 2.8/3.0, and I think this is more urgent (last tag was on october 2015…)

Ping @rande :)

**Comment by reypm** [comment]
@OskarStark and why we're waiting on a stable release? Could not the team work based on the alpha and then move things if needed on the stable? They are working on this from September, 2015 and we're on February, 2016, if we still waiting on this we will never get out a stable release of Sonata and it's bundles, don't you think?

Also will be nice if someone can share a kind of *"working"* sandbox or at least its `composer.json` file with the current bundle so we can test because I would like to test and report issues. Any advice on this?

**Comment by OskarStark** [comment]
@reypm we are working on it here:
https://github.com/sonata-project/SonataUserBundle/tree/add_support_for_fos_user2

depending on ` "friendsofsymfony/user-bundle": "~2.0@dev",`

would be glad if you could help to get this working, testing and reporting bugs would be great too.
We are accepting PR's on this Branch :exclamation: 

Thank you (all) very much!

**Comment by tim96** [comment]
> depending on "friendsofsymfony/user-bundle": "~2.0@dev",
would be glad if you could help to get this working, testing and reporting bugs would be great too.
We are accepting PR's on this Branch :exclamation: 

@OskarStark do you have list tasks, issues or PR where you heed help?

**Comment by OskarStark** [comment]
not yet, but you can please use this branch, try it out please and give us feedback

thank you :+1:

**Comment by reypm** [comment]
@OskarStark I would be glad to help but I am still looking for the right `composer.json` dependencies for current Sonata WIP version and also the rest of the bundles so if any can share this, will be very helpful, anyone?

**Comment by OskarStark** [comment]
ping @rande can you help?

**Comment by zajca** [comment]
I'm actually using current master with 3.0 and mongo driver, it's working with some issues, only bigger problem that I run to is this: https://github.com/sonata-project/SonataAdminBundle/issues/3529
but I'm not using FOSUserBundle

**Comment by reypm** [comment]
@rande any advice for a *working* `composer.json` file in order to test?

**Comment by reypm** [comment]
@OskarStark could you or any other ( @core23 ) provide a *functional* `composer.json` file? I have a project stopped waiting on this so I want to help as much as I can but again docs are outdated so I don't know where to go. Here is my `composer.json` file:

    "require": {
        "php": ">=5.3.9",
        "symfony/symfony": "2.8.*",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",

        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3",
        "sonata-project/easy-extends-bundle": "^2.1.10",

        "kevintweber/ktw-database-menu-bundle": "~0.5",
    }

What do you think?

**Comment by OskarStark** [comment]
@core23 can you help, i am using dev-master

**Comment by core23** [comment]
Sorry, I'm using dev-master too

**Comment by reypm** [comment]
@OskarStark @core23 has been a while since I asked this but any advice regarding this topic? I have been involve in other project and leave this for a while

**Comment by core23** [comment]
Please be patient. The new minor releases should come soon which.

**Comment by Soullivaneuh** [comment]
3.x is now stable and allow SF 3.0. If you have specific issues with SF 3.0 and our bundle, please open issues or propose PR.
