### ISSUE TITLE
Tag 2.4 status (stable for Symfony 2.8/3.0)

### ISSUE THREAD

**Issue by sylvaindeloux** [sonata-project/SonataAdminBundle#3560]
Hi !
I have some issues with Sonata version on a Symfony 2.8 version. I can't use ```dev-master``` because my project only accept stable vendors.
I've found [this file](https://docs.google.com/spreadsheets/d/1fSpS10nzlEj9HE-GdZ-BHcxileEzHwRIzLlNfdNtZ2k/edit#gid=0) but I don't understand the colors (and the 2.4.x does not exist).
Any feedback about the 2.4 release?
Thanks :)
(ping @rande)

**Comment by nickpro** [comment]
+1, cant setup with symfony3

**Comment by peter-gribanov** [comment]
+1, we want use Symfony 3

**Comment by whitewhidow** [comment]
+1

**Comment by sylvaindeloux** [comment]
The 2.4 is coming : https://github.com/sonata-project/SonataAdminBundle/milestones/2.4 but missing some PR

**Comment by aistis-** [comment]
Also waiting for 2.4! :)

**Comment by edrush** [comment]
+1

**Comment by GyniO** [comment]
+1

**Comment by haivala** [comment]
+1

**Comment by greg0ire** [comment]
There is a +1 button now, you know.

**Comment by mvhirsch** [comment]
What's missing to get 2.4 released?

**Comment by greg0ire** [comment]
We would like to get [this list](https://github.com/sonata-project/SonataAdminBundle/milestones/2.4) to zero items

**Comment by Soullivaneuh** [comment]
@mvhirsch That @greg0ire says. When it will be OK, I'll release a 2.4.0 and start the new [sonata version managment](https://github.com/sonata-project/SonataAdminBundle/issues/3053) for this bundle.

**Comment by Soullivaneuh** [comment]
Please see #3731.
