### ISSUE TITLE
Impossible filter a list by empty value

### ISSUE THREAD

**Issue by peter-gribanov** [sonata-project/SonataAdminBundle#3569]
For example:
- I want to find all users who do not have group
- I want to find all users who have not specified a surname

Now, if you leave the filter empty, it does not apply. If you search for a null value via callback, it always applies, even if i did not choose filters.

**Comment by danielsippel** [comment]
+1

**Comment by muspelheim** [comment]
+1

**Comment by core23** [comment]
Please stop spamming `+1` comments. Somebody need to start a PR for this.

Maybe @danielsippel or @muspelheim ?

**Comment by gam6itko** [comment]
To reach this behavior we should refactor this 

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/39cf5c594d4c4aacff9cf3e6085f391341718e09/src/Filter/ChoiceFilter.php#L48

**Comment by OskarStark** [comment]
Can you provide a PR with the proposed change? Thanks

**Comment by VincentLanglet** [comment]
Hi, as asked here https://github.com/sonata-project/SonataDoctrineORMAdminBundle/issues/991#issuecomment-595868272, can you be more precise with the needs ?
What is an empty value ?

If not we could consider this issue as resolved since 

> * I want to find all users who do not have group
> * I want to find all users who have not specified a surname

`Where group.id IS NULL`
`Where surname IS NULL`

Can be both made by the ChoiceFilter now.

For what I know, you now only miss the filter `Where surname = ''`, isn't it ?

**Comment by peter-gribanov** [comment]
> * I want to find all users who have not specified a surname
> 
> `Where surname IS NULL`

NULL is not a valid value for a string column.

> For what I know, you now only miss the filter Where surname = '', isn't it ?

Yes. This is the main case.

This issue was created more than 4 years ago.  Now for me this is not so relevant.

> Can be both made by the ChoiceFilter now.

I can't check now, but is this relevant for?

* `NumberFilter`
* `StringFilter`
* `DateTimeFilter`
* `DateFilter`
* `TimeFilter`
* `DateTimeRangeFilter`
* `DateRangeFilter`
* `ModelAutocompleteFilter`

**Comment by peter-gribanov** [comment]
This issue has not been resolved yet

**Comment by VincentLanglet** [comment]
Do you want to work on a PR @peter-gribanov ?

**Comment by peter-gribanov** [comment]
@VincentLanglet I see only one way to solve this problem. Filter by empty value only if the filtering type is explicitly specified (not specified by default).

**Comment by VincentLanglet** [comment]
I think there is a big reflexion needed about the UX of this kind of filters.
Also this is maybe not a behavior that everybody's looking for.

This could be solved by
- An option
- Specific filters
- Some UX changements.

**Comment by peter-gribanov** [comment]
> Specific filters

Any filter will not be applied if the filter value is empty. For more details see here #6402
I see no reason to create a new filter if it can be done within the existing one.

> I think there is a big reflexion needed about the UX of this kind of filters.

Let me explain how i see it.

This is how the filter string looks when we decide to filter the data. In this form, the filter will not be applied.
![image](https://user-images.githubusercontent.com/1954436/93871212-f0b7ce00-fcd6-11ea-91cb-a93f97e1b68a.png)

We can enable advanced filtering mode, but this filter will still not be applied.
![image](https://user-images.githubusercontent.com/1954436/93871361-32487900-fcd7-11ea-8fac-4930998537a0.png)

If we explicitly indicate the typhus of filtering, then we let the system know that we want to search for an empty string. And we don't want the system to ignore this filter.
![image](https://user-images.githubusercontent.com/1954436/93871491-6328ae00-fcd7-11ea-877b-e85ee3523b02.png)

**Comment by VincentLanglet** [comment]
> > Specific filters
> 
> Any filter will not be applied if the filter value is empty. For more details see here #6402

That's a good point.

> 
> > I think there is a big reflexion needed about the UX of this kind of filters.
> 
> Let me explain how i see it.
> 
> This is how the filter string looks when we decide to filter the data. In this form, the filter will not be applied.
> ![image](https://user-images.githubusercontent.com/1954436/93871212-f0b7ce00-fcd6-11ea-91cb-a93f97e1b68a.png)
> 
> We can enable advanced filtering mode, but this filter will still not be applied.
> ![image](https://user-images.githubusercontent.com/1954436/93871361-32487900-fcd7-11ea-8fac-4930998537a0.png)
> 
> If we explicitly indicate the typhus of filtering, then we let the system know that we want to search for an empty string. And we don't want the system to ignore this filter.
> ![image](https://user-images.githubusercontent.com/1954436/93871491-6328ae00-fcd7-11ea-877b-e85ee3523b02.png)

If after your third step you disable again the advanced filtering mode, you'll get
![image](https://user-images.githubusercontent.com/1954436/93871212-f0b7ce00-fcd6-11ea-91cb-a93f97e1b68a.png)

You won't be able to know if this filter will be applied or not. That's my only concern.

**Comment by peter-gribanov** [comment]
We can define through JS that a search will be performed on an empty string and add help text in these cases.

![image](https://user-images.githubusercontent.com/1954436/93899592-240d5380-fcfd-11ea-9a8d-0028dbbb7949.png)
![image](https://user-images.githubusercontent.com/1954436/93899521-1526a100-fcfd-11ea-81fa-24bf5be95113.png)

**Comment by peter-gribanov** [comment]
@VincentLanglet this is just a suggestion for improving UI. I do not understand your JS and i cannot do it.

**Comment by VincentLanglet** [comment]
> @VincentLanglet this is just a suggestion for improving UI. I do not understand your JS and i cannot do it.

This is clearly not **my** JS 😄

But I think it could be a good suggestion to highlight active filter. This could lead to a new feature-request.

**Comment by VincentLanglet** [comment]
Solved by https://github.com/sonata-project/SonataAdminBundle/pull/6402

Now, filters can handle empty value like https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1120
