### ISSUE TITLE
The option "property" does not exist.

### ISSUE THREAD

**Issue by aglemakinafr** [sonata-project/SonataAdminBundle#3575]
Hello,

I am following the documentation for sonataadminbundle, and I am at this point : https://sonata-project.org/bundles/admin/2-3/doc/getting_started/the_list_view.html

Trying to do the last change to my code, I have the exception : The option "property" does not exist.

Is there an error in the documentation ? How can I fix this ?

Thank you for reading.

**Comment by snroki** [comment]
Hi, 

I assume you're using symfony 3, got the same error. 
It's because the entity field doesn't use the option "property" anymore (cf http://symfony.com/doc/current/reference/forms/types/entity.html) you should use the option "choice_label" instead.

**Comment by aglemakinafr** [comment]
Thank you very much.
This was exactly my problem. I suspected some changes due to v3, but I could not find which option replaced property.

**Comment by muspelheim** [comment]
@aglemakinafr, why you don't close issue?

**Comment by aglemakinafr** [comment]
Just because I forgot. Sorry, done now ;)
