### ISSUE TITLE
sonata_top_nav_menu contents are always visible

### ISSUE THREAD

**Issue by dlondero** [sonata-project/SonataAdminBundle#3579]
Am I missing something or shouldn't `sonata_top_nav_menu` contents be visible only when there's an `app.user` available?

**Comment by greg0ire** [comment]
Can you link to the code on github?

**Comment by dlondero** [comment]
@greg0ire here you go https://github.com/sonata-project/SonataAdminBundle/blob/d5f8d0b0058cc3ab88d75eda9982820a4c6b2c2b/Resources/views/standard_layout.html.twig#L164-L187

**Comment by greg0ire** [comment]
Oh my god you're right, I checked it on a Sonata 2 site and… it's there, completely useless.
@sonata-project/contributors : does anyone know if this happens also in Sonata 3. @dlondero , do you? If yes, would you kindly provide a PR to fix this?

**Comment by dlondero** [comment]
@greg0ire looking at the code of the layout this should happen in Sonata 3 as well. As a fix I'd wrap the content of the block with a `{% if app.user and is_granted('ROLE_SONATA_ADMIN') %}` check. Which branch should I target?

**Comment by greg0ire** [comment]
3.x, there is no bc break imo
