### ISSUE TITLE
Custom default CRUDController?

### ISSUE THREAD

**Issue by edrush** [sonata-project/SonataAdminBundle#3581]
I want so specify a custom default CRUDController for all my admins. Admins are to use this Controller unless another one is specified in the service. I did not find an issue or documentation on that? Is it possible?

**Comment by OskarStark** [comment]
when you generate an admin class, the wizard asks you wheather you want to use the default or a custom controller

**Comment by edrush** [comment]
Right, but what if I want to change it afterwards, for all my admins?

Am 10.02.16 um 09:34 schrieb Oskar Stark:

**Comment by OskarStark** [comment]
manually :smile:

**Comment by edrush** [comment]
@OskarStark Ok, that's what I thought. Thank you!

Would be a new nice feature though...
