### ISSUE TITLE
Question about related fields

### ISSUE THREAD

**Issue by muspelheim** [sonata-project/SonataAdminBundle#3594]
Hello, I have form for entity1, this form contains 2 related fields (Device and DeviceContacts), how i can make in form, so when selecting Device automatically loads the value of DeviceContacts in form for entity1

i find in FormTypes ModelReferenceType and ModelAutocompleteType but in my case it's doesn't work.

**Comment by anacona16** [comment]
You can use https://github.com/shtumi/ShtumiUsefulBundle

**Comment by muspelheim** [comment]
@anacona16, Thank you, that works!
