### ISSUE TITLE
Using sonata with Symfony 2.8 and 3 ?

### ISSUE THREAD

**Issue by ychoucha** [sonata-project/SonataAdminBundle#3596]
hello, 

well i can't install sonata on my frech install of symfony2 can explain me what is wrong please ?

```
root [/var/www/html_prod/CMS-Demo] > symfony new my_project_demoSonata 2.8

 Downloading Symfony...

    5.17 MB/5.17 MB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

 Preparing project...

 ✕  Symfony 2.8.2 was successfully installed but your system doesn't meet its
     technical requirements! Fix the following issues before executing
     your Symfony application:

 * date.timezone setting must be set
   > Set the "date.timezone" setting in php.ini* (like Europe/Paris).

 After fixing these issues, re-check Symfony requirements executing this command:

   php my_project_demoSonata/app/check.php

 Then, you can:

    * Change your current directory to /var/www/html_prod/CMS-Demo/my_project_demoSonata

    * Configure your application in app/config/parameters.yml file.

    * Run your application:
        1. Execute the php app/console server:run command.
        2. Browse to the http://localhost:8000 URL.

    * Read the documentation at http://symfony.com/doc
```

and : 

```
root [/var/www/html_prod/CMS-Demo/my_project_demoSonata] > php  composer.phar require sonata-project/admin-bundle "2.3.*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonata-project/admin-bundle 2.3.7 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.6 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.5 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.4 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.3 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.2 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.1 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.0 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - Installation request for sonata-project/admin-bundle 2.3.* -> satisfiable by sonata-project/admin-bundle[2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

```

**Comment by greg0ire** [comment]
Sonata 2.3 is not compatible with symfony 3.0. Sonata 2.4 might be.

**Comment by nlzet** [comment]
@greg0ire the issue mensions Symfony 2.8

@ychoucha
The error occurs because symfony 2.8 by default requires (dev) : `sensio/generator-bundle": "~3.0"`

I'm not sure if this minimum requirement is correct, you can fix this by first executing:
`composer require sensio/generator-bundle "~2.3" --dev`

And then you can install the admin bundle with:
`composer require sonata-project/admin-bundle "2.3.*"`

But you should search if the 2.3 generator bundle is compatible with symfony 2.8

**Comment by greg0ire** [comment]
Oh my bad, the dependency is correct, the ~3.0 version is marked as compatible with symfony "~2.7". I think sonata should allow it.

**Comment by ychoucha** [comment]
ok so sonata is not compatible with stable release of symfony 2.8 with  end of support Nov. 2018 ??

so we have to use Sonata with a old symfony framwork version ? like the 2.4 but we can't install it : 


```
root [/var/www/html_prod/CMS-Demo] > symfony new my_project_demoSonata 2.4
  [RuntimeException]
  The selected version (2.4.10) cannot be installed because it belongs
  to an unmaintained Symfony branch which is not compatible with this installer.
  To solve this issue install Symfony manually executing the following command:
  composer create-project symfony/framework-standard-edition /var/www/html_prod/CMS-Demo/my_project_demoSonata 2.4
  .10
```

so so so how use sonota please ?

**Comment by greg0ire** [comment]
I was speaking about sonata 2.4 . Not symfony 2.4 ;)

**Comment by ychoucha** [comment]
ok so what symfonyé version we need to instal to play with sonata

**Comment by greg0ire** [comment]
You can use sf 3.0 and sonata 2.4@dev I guess, but there are more stable choices like sf 2.7, sonata 2.3

**Comment by ychoucha** [comment]
well thanks,

that's not cool to start a project with no sf stable version ?

**Comment by greg0ire** [comment]
sf 3.0 is stable, but sonata 2.4 is not stable yet. Starting a project with any dependency unstable is risky (you must be ready to change your code as soon as you upgrade the dependency). I would advise to start with sf 2.8 and sonata 2.3, and then upgrade sf and sonata when sonata 2.4 is ready.

**Comment by ychoucha** [comment]
ok so i try the install with sf 2.8 and sonata 2.3 : 
i do this terminal video --> https://asciinema.org/a/cm5035hej5u0565b3wvb73c2w

and no way to install it :/


```

root [/var/www/html_prod/CMS-Demo/my_project_demoSonata] > php composer.phar require sonata-project/admin-bundle "2.3.*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonata-project/admin-bundle 2.3.7 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.6 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.5 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.4 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.3 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.2 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.1 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.0 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - Installation request for sonata-project/admin-bundle 2.3.* -> satisfiable by sonata-project/admin-bundle[2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

```

**Comment by greg0ire** [comment]
The generator bundle requirement should probably be changed to `~2.3|~3.0` on the 2.3 branch of Sonata. @sonata-project/contributors ? What do you think?

**Comment by ychoucha** [comment]
Si i have to found sf 2.4 with so 2.3

**Comment by greg0ire** [comment]
> Si i have to found sf 2.4 with so 2.3

What?

**Comment by Soullivaneuh** [comment]
> The generator bundle requirement should probably be changed to `~2.3|~3.0` on the 2.3 branch of Sonata. @sonata-project/contributors ? What do you think?

It's already the case for 2.4.x.

I'm not sure we can easily change this on 2.3 without breaking anything... cc @rande

**Comment by greg0ire** [comment]
The generator bundle does not have an upgrade file :(

**Comment by dbu** [comment]
does sonata admin actually need the generator bundle? i thought that is about creating bundles in a command and similar things...

**Comment by jvasseur** [comment]
Sonata admin use it for the generate:admin command.

**Comment by greg0ire** [comment]
Looks like there is a test for it. We should just make a P.R. and let the tests run.

**Comment by greg0ire** [comment]
Looks like tests are passing.

**Comment by ychoucha** [comment]
ok so i have try to install sonata and i m stuck :/


I have triend with symfony 2.8 and sonata 2.3 : 

```
root [/var/www/sonata-demo] > php composer.phar require sonata-project/admin-bundle
Using version ^2.3 for sonata-project/admin-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonata-project/admin-bundle 2.3.7 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.6 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.5 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.4 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.3 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.2 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.1 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - sonata-project/admin-bundle 2.3.0 requires sensio/generator-bundle ~2.3 -> no matching package found.
    - Installation request for sonata-project/admin-bundle ^2.3 -> satisfiable by sonata-project/admin-bundle[2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by ychoucha** [comment]
and on the web site of symfony i can"t get a old symfony version :!

https://symfony.com/roadmap?version=2.4#checker

**Comment by dbu** [comment]
well, 2.4 was not a long term support version, so its not maintained
anymore. afaik 2.3 is about to end, but 2.7 will be maintained for a
while still.

**Comment by ychoucha** [comment]
im sorry, but even the 2.7 not working with symfony : 

show what i do : 

https://asciinema.org/a/3uslv0wktz9cr2b2g1o5vs789


i finish with the error : 

> 

Your requirements could not be resolved to an installable set of packages.

**Comment by greg0ire** [comment]
Try again after running what @nlzet recommended : `composer require sensio/generator-bundle "~2.3" --dev`. Alternatively, you 

And please stop using asciinema, it is very pretty, but brings nothing to the table and prevents at least me to see what exactly you used when requiring `sensio/generator-bundle`. Use it if you really need to show us color or progress bars.

**Comment by greg0ire** [comment]
#3604 has been fixed, which means you should be also be able to install the 2.3@dev version of the admin bundle without changing the generator requirements.

**Comment by ychoucha** [comment]
ok cool works with :+1: 

> symfony new my_project_demoSonata 2.7
> php composer.phar require "sensio/generator-bundle"
> php composer.phar require sonata-project/admin-bundle "2.3" --dev
> php composer.phar require sonata-project/doctrine-orm-admin-bundle --prefer-dist


ok i will never use again asciinema (but he looking cool :/)

**Comment by greg0ire** [comment]
> ok i will never use again asciinema (but he looking cool :/)

I know, it's really nice, but should not be overused :) 

>  php composer.phar require sonata-project/admin-bundle "2.3" --dev

This does not do what you think it does, it adds `sonata-project/admin-bundle` 2.3 to your dev requirements (have a look at your composer.json), you'll see what I mean

> php composer.phar require "sensio/generator-bundle"

Shoud be `php composer require sensio/generator-bundle "~2.3" --dev`

I don't know what you have now, but if it works, guess you can play with Sonata and sort that out later.

**Comment by ychoucha** [comment]
well well well i talk to fast : 

this i do to install symfony 2.7 an sonata 2.3 : 

```
symfony new my_project_demoSonata 2.7
cp composer.phar my_project_demoSonata/
cd my_project_demoSonata/
php composer.phar require "sensio/generator-bundle"  "~2.3" --dev
php composer.phar require sonata-project/admin-bundle "2.3" --dev
php composer.phar require sonata-project/doctrine-orm-admin-bundle --prefer-dist
php app/console cache:clear
chmod 777 -R app/cache
chmod 777 -R app/logs
cd ..
chown ayoub:www-data -R  my_project_demoSonata/
```


and i have this error when i logging : 


`FatalErrorException in AdminListBlockService.php line 0: Compile Error: Declaration of Sonata\AdminBundle\Block\AdminListBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block)`

**Comment by ychoucha** [comment]
ok works with that : 

```
symfony new my_project_demoSonata 2.7
cp composer.phar my_project_demoSonata/
cd my_project_demoSonata/
pwd
php composer.phar require "sensio/generator-bundle"   "~2.3" --dev
pwd
php composer.phar require sonata-project/admin-bundle
pwd
php composer.phar require sonata-project/doctrine-orm-admin-bundle --prefer-dist
pwd
php app/console cache:clear
chmod 777 -R app/cache
chmod 777 -R app/logs
cd ..
chown ayoub:www-data -R  my_project_demoSonata/
```

**Comment by greg0ire** [comment]
Great! I'm sure the `pwd`s helped a lot :stuck_out_tongue_winking_eye:

**Comment by ychoucha** [comment]
well i m hope sonata will be more stable

**Comment by ychoucha** [comment]
ok  i m trying the first sonata exemple ---> https://sonata-project.org/bundles/admin/master/doc/getting_started/creating_an_admin.html


i have this error : 

`
An exception has been thrown during the rendering of a template ("Unable to generate a URL for the named route "admin_app_category_create" as such route does not exist.") in SonataAdminBundle:Block:block_admin_list.html.twig at line 39. 
`
i do exactly what the example 



create an entity ; 

`<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Category
 *
 * @ORM\Table()
 * @ORM\Entity
 */
class Category
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Category
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }
}
`


create an Admin files : 

`<?php 

// src/AppBundle/Admin/CategoryAdmin.php
namespace AppBundle\Admin;

use Sonata\AdminBundle\Admin\Admin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;

class CategoryAdmin extends Admin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper->add('name', 'text');
    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper->add('name');
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper->addIdentifier('name');
    }
}`

`# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category }`


what is wrong now ??

**Comment by greg0ire** [comment]
Everyone does, @ychoucha , everyone does…

**Comment by brave44** [comment]
How to istall sonata-project/admin-bundle with Symfony3? Still can not do it.

` - sonata-project/admin-bundle 2.3.7 requires sensio/generator-bundle ~2.3 -> no matching package found.`

**Comment by Mangetsu** [comment]
if you still have issues with SF3 and Sonata install, please refere to my composer requirement bellow, i managed to get Sf3, Sonata and FOSUser to work perfectly (dispite some minor fixes to avoid deprecated/removed services)

`"require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.0.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "symfony/security-acl": "^3.0",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "^2.1",
        "sonata-project/doctrine-orm-admin-bundle": "dev-master",
        "friendsofsymfony/user-bundle": "dev-master",
        "sonata-project/user-bundle": "dev-add_support_for_fos_user2@dev",
        "sensio/generator-bundle": "^3.0"
    },`

FOSUser removed services fix : 
`services:
   
    # Fix FOSUserBundle issue
    fos_user.doctrine_registry:
        alias: doctrine

    fos_user.entity_manager:
        alias: fos_user.object_manager`

**Comment by lacpandore** [comment]
Hello, I've tryed what you gave Mangetsu, 
but i still have a problem  to install sonata-project/user-bundle

it seems the corebundle of sonata is not compatible, do u know wich is?
![capture](https://cloud.githubusercontent.com/assets/20201470/16909917/bb63dc9a-4cd5-11e6-8844-4fac203b4058.PNG)


`		"php": ">=5.5.9",
        "symfony/symfony": "3.0.*",
		"doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
		"stof/doctrine-extensions-bundle": "~1.1",
		"doctrine/doctrine-fixtures-bundle": "~2.2",
		"twig/extensions": "~1.0",
        "symfony/assetic-bundle": "^2.8",
        "symfony/options-resolver": "~2.3",
		"symfony/form": "~2.3",
		"symfony/yaml": "~2.3",
        "symfony/security-bundle": "~2.3",
		"kriswallsmith/buzz": "~0.13",
		"coresphere/console-bundle": "dev-master",
        "pugx/autocompleter-bundle": "^1.2",
        "stof/doctrine-extensions-bundle": "~1.1",
        "sonata-project/doctrine-orm-admin-bundle": "dev-master",
 
        "sonata-project/core-bundle": "^2.3",
        "sonata-project/block-bundle": "^3.1",
        "knplabs/knp-menu-bundle": "^2.0",
        "sonata-project/easy-extends-bundle": "^2.1",
        "sonata-project/cache-bundle": "^2.2",
		
		"symfony/security-acl": "^3.0",
		"sonata-project/admin-bundle": "dev-master",
		"friendsofsymfony/user-bundle": "dev-master",
		"sonata-project/user-bundle": "dev-add_support_for_fos_user2@dev"
		`

**Comment by Soullivaneuh** [comment]
you need to add `sonata-project/core-bundle` `^3.0`.

**Comment by lacpandore** [comment]
yes i did this, but i got this error, i don't know how to solve this

 sonata-project/user bundle dev-add_support_for_fos_user2 requires sonata-project/core-bundle "2.3,>=2.3.10

**Comment by Soullivaneuh** [comment]
Please note that `user bundle dev-add_support_for_fos_user2` is an experimental and unstable branch.

If you really want to use it, you might have to use composer version aliases.

https://getcomposer.org/doc/articles/aliases.md#require-inline-alias

**Comment by lacpandore** [comment]
Okay, thank you
Are there maybe another way to install sonata user?

**Comment by Soullivaneuh** [comment]
Yes, using stable version. But this will not be compatible with FOSUser 2.x.

**Comment by lacpandore** [comment]
I've found a version wich is working, but now i've a problem with mediabundle on a service:

`"require": {
		"php": ">=5.5.9",
        "symfony/symfony": "3.0.*",
		"doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
		"stof/doctrine-extensions-bundle": "~1.1",
		"doctrine/doctrine-fixtures-bundle": "~2.2",
		"friendsofsymfony/user-bundle": "dev-master",
		"twig/extensions": "~1.0",
        "symfony/assetic-bundle": "^2.8",
        "symfony/options-resolver": "~2.3",
		"symfony/form": "~2.3",
		"symfony/yaml": "~2.3",
        "symfony/security-bundle": "~2.3",
		"kriswallsmith/buzz": "~0.13",
		"coresphere/console-bundle": "dev-master",
        "pugx/autocompleter-bundle": "^1.2",
        "stof/doctrine-extensions-bundle": "~1.1",
        
		"sonata-project/doctrine-orm-admin-bundle": "^3.0",
        "sonata-project/admin-bundle": "^3.4",
        "sonata-project/core-bundle": "^3.0",
        "sonata-project/block-bundle": "^3.1",
        "knplabs/knp-menu-bundle": "^2.0",
        "sonata-project/easy-extends-bundle": "^2.1",
        "sonata-project/cache-bundle": "^2.2",
        "sonata-project/media-bundle": "^3.0",
        "sonata-project/seo-bundle": "^2.0",
        "sonata-project/classification-bundle": "^3.1",
        "jms/serializer-bundle": "^1.1"    
    },
    "require-dev": {
		"sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^2.7"
    },`

So I did the installation with mediabundle and then classificationbundle, and it works, I updated my db, 

but i have an new error on sonata/media/media/create: 
`You have requested a non-existent service "request". Did you mean one of these: "request_stack", "router.request_context", "monolog.logger.request", "assetic.request_listener", "validate_request_listener", "data_collector.request"? `

and on admin/sonata/media/media/list
`Notice: Undefined index: entity `

Does anybody have an idea where i have to search or maybe an answer?
Thank you

**Comment by Soullivaneuh** [comment]
@lacpandore Not related to this issue.

1. Read and re-read carefully the documentation
1. Ask your question on SO
1. If you think it's a bug, try to find the related GitHub issue on the right repository
1. If no issue related to this bug, feel free to create one respecting the bug report template

**Comment by nikunjkabariya** [comment]
Hello,

How to use sonata admin project with symfony 3.2.* having translation features (Multilingual support - form labels, messages, validators and doctrine ORM translatable support - <what should be database structure?>).
Can anybody have  example which i can use?
OR Can anybody guide me how to implement it?

Thanks

**Comment by Soullivaneuh** [comment]
@nikunjkabariya This is **not** related to the issue and not an issue anymore.

Please ask your question on SO.

Locking this thread.
