### ISSUE TITLE
Unable to find a valid admin for the class

### ISSUE THREAD

**Issue by napestershine** [sonata-project/SonataAdminBundle#3602]
I am getting following error:

Unable to find a valid admin for the class: AdminBundle\Entity\Category, there are too many registered: admin.category,admin.admin.category

Any solution? TIA

**Comment by greg0ire** [comment]
I think you can specify the admin code, have a look at the code. If it is the case, can you please make a P.R. to improve the error message?

**Comment by napestershine** [comment]
@greg0ire  What is admin_code?

**Comment by greg0ire** [comment]
`grep -rn admin_code vendo/sonata-project/admin-bundle` shoud answer your question ;)

**Comment by napestershine** [comment]
How will I run it in windows?

**Comment by greg0ire** [comment]
grep is a search tool. Do you know how to search for code in a directory under Windows? I don't.

**Comment by napestershine** [comment]
Problem solved, thanks :)

**Comment by greg0ire** [comment]
Can you post your solution for others? And perhaps make the PR I asked for?

**Comment by greg0ire** [comment]
Please @napestershine . Think of the children…

**Comment by napestershine** [comment]
HI @greg0ire 

Sorry, The problem was I was using sonata.admin.generate command from console. And at same time I was following the sonata project documentation.
 

So problem was in services.yml. According to documentation I should put services in app/config/services.yml

But common put them into src/bundle/resources/config/services.yml

This was creating a conflict. Also Need to use __toString() in parent category.

Thanks.

**Comment by greg0ire** [comment]
Thanks @napestershine !
