### ISSUE TITLE
How can i get who created entity?

### ISSUE THREAD

**Issue by nkl90** [sonata-project/SonataAdminBundle#3608]
Hellow. In my SonataAdmin install ACL security and FOSUserBundle. How can i get in list of entities who create this entity? I dont understand, what be kept in this table:
`acl_classes`, `acl_entries`, `acl_object_identities`, `acl_object_identity_ancestors`, `acl_security_identities`
How can i use this data to get what I need?

**Comment by greg0ire** [comment]
The ACLs are not part of Sonata, but of Symfony, read the Symfony docs, and make sure you really need the ACLs, because they are quite painful to manage.
