### ISSUE TITLE
List embedded fields

### ISSUE THREAD

**Issue by Spomsoree** [sonata-project/SonataAdminBundle#3614]
I'm trying to display the embedded geoLocations of my class Review like this:

```php
    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('geoLocation.latitude')
            ->add('geoLocation.longitude')
        ;
    }
```

This works fine with the FormMapper

If I try to do this with the ShowMapper or ListMapper, all I get is a empty field.

**Comment by greg0ire** [comment]
You could try to find the template that is in use and debug it.

**Comment by mlang38** [comment]
Lol. I've just spent an hour to jump from classes to classes to debug, to finally see that it seems it has been [fixed](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3ba04959270c44596e72ccff0adb7ba5cc02cbe2/Admin/FieldDescription.php#L102) 7 hours ago :smile:.

**Comment by greg0ire** [comment]
Well then it's one less issue, thanks for pointing that out @mlang38 , it will help the next poor guy ;)
