### ISSUE TITLE
Autocomplete - error when trying mapped = false

### ISSUE THREAD

**Issue by rapemer** [sonata-project/SonataAdminBundle#3615]
It's not possible to create autocomplete type where `mapped = false` and filled `admin_code`

``` php
    public function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('page', 'sonata_type_model_autocomplete', [
                'class' => 'Application\AppBundle\Entity\Page',
                'label' => 'app.label.menu.page.name',
                'help' => 'app.help.menu.page.name',
                'mapped' => false,
            ], [
                'admin_code' => 'app.admin.page',
            ])
        ;
    }
```

Giving error:
`The current field`page`is not linked to an admin. Please create one for the target entity:`

**Comment by greg0ire** [comment]
Shouldn't an autocomplete field have a source (the database), and thus, be mapped to a field of the entity?

**Comment by rapemer** [comment]
If I use @ManyToMany or some mapping metadata, autocomplete is ok. But if I want use `mapped` => false, then autocomplete don't work :-)

**Comment by greg0ire** [comment]
Why isn't `app.admin.page` associated with the `Application\AppBundle\Entity\Page` entity ?

**Comment by rapemer** [comment]
It is associated ;-) that's the problem ...

**Comment by greg0ire** [comment]
Oh ok. Can you provide a stack trace?

**Comment by ju1ius** [comment]
Doesn't [this line](https://github.com/sonata-project/SonataAdminBundle/blob/master/Controller/HelperController.php#L373) imply that the field must be mapped ?

**Comment by ju1ius** [comment]
Okay, I found a way, but it's quite tedious.
The idea is to overwrite the field description generated by the FormMapper with a custom one with fake association mapping metadata.

```php
<?php
/**
 * @param FormMapper $formMapper
 */
protected function configureFormFields(FormMapper $formMapper)
{
    // simulate an association ...
    $pageAdmin = $this->configurationPool->getAdminByClass('Application\AppBundle\Entity\Page');
    $fieldDescription = $this->getModelManager()->getNewFieldDescriptionInstance($this->getClass(), 'page', [
        'translation_domain' => 'AppBundle',
    ]);
    $fieldDescription->setAssociationAdmin($pageAdmin);
    $fieldDescription->setAdmin($this);
    $fieldDescription->setAssociationMapping([
        'fieldName' => 'page',
        'type' => ClassMetadataInfo::MANY_TO_ONE,
        'targetEntity' => 'Application\AppBundle\Entity\Page'
    ]);
    // create a child builder
    $builder = $formMapper->create('page', 'sonata_type_model_autocomplete', [
        'property' => 'name',
        'sonata_field_description' => $fieldDescription,
        'class' => $pageAdmin,
        'model_manager' => $pageAdmin->getModelManager(),
        'label' => 'app.label.menu.page.name',
        'admin_code' => $pageAdmin->getCode()
    ]);

    $formMapper->add($builder, 'sonata_type_model_autocomplete');
    // overwrite the generated field description, again...  ¯(°_o)/¯
    $this->addFormFieldDescription('field', $fieldDescription);
}
```

**Comment by ju1ius** [comment]
@rapemer Out of curiosity, why don't you just map your Page entity ?

**Comment by Saint-Cyr** [comment]
Please I coudn't make the SONATA_TYPE_AUTOCOMPLET work for the basic setup show in the documentation for I still get the error: `Notice: Undefined index: read_only`. for information, my relationship is ManyToOne and in Many side, I've over 40000 items (the reason why I wanted use the type in order to limit the number of item return by the server so that performance will be ok)

**Comment by greg0ire** [comment]
@Saint-Cyr : does this have anything to do with the issue at hand?

**Comment by dexterionut** [comment]
@ju1ius can this be extended for filters as well?
