### ISSUE TITLE
Symony3 sonata.admin.doctrine_phpcr.form.collection_type_extension service issue

### ISSUE THREAD

**Issue by billsworld** [sonata-project/SonataAdminBundle#3618]
Trying to update to Symfony3 so using the master version of SonataAdminBundle and I am getting the following error. Still need to do some digging but wanted to see if anyone had an idea.

```
Tagged form type extension must have the extended type configured using the extended_type/extended-type attribute, none was configured for the "sonata.admin.doctrine_phpcr.form.collection_type_extension" service.
```

**Comment by ychoucha** [comment]
well, like i see sonata is not yet compatible with sf3

**Comment by billsworld** [comment]
Sorry fogot to mention that I am running the master version

**Comment by greg0ire** [comment]
Shouldn't you report that bug to the phpcr bundle?

**Comment by jordisala1991** [comment]
This doesnt belong here
