### ISSUE TITLE
Transform phone number in ListMapper

### ISSUE THREAD

**Issue by SukachVitally** [sonata-project/SonataAdminBundle#3629]
I  use misd-service-development/phone-number-bundle for phone number in my application. Phone number persist in model as object.
In FormMapper it's okay. I just set field type. 
`$formMapper->add('cell', PhoneNumberType::class, ['required' => false])`
And get normal text 

> +380 93 708 6736

But in list I have some problem. My field doesn't converted.
`$listMapper->add('cell', PhoneNumberType::class) `

> Country Code: 380 National Number: 937086736 Country Code Source:	

How can I format this field?

**Comment by greg0ire** [comment]
`$listMapper->r->add('cell', PhoneNumberType::class)`

I don't get what the `r` part is about.

About your problem, this is not a support forum, so if you want it to be taken into account, you must show us there is a bug and what you expect. I guess your package has some sort of transformer you would expect to be called when displaying a list element, why not talk directly about that?

**Comment by tim96** [comment]
> I don't get what the r part is about.

@greg0ire maybe it is only mistake when @SukachVitally create a new issue?

>But in list I have some problem. My field doesn't converted.
$listMapper->r->add('cell', PhoneNumberType::class)

@SukachVitally I'm not sure, but in ListMapper I use _template_ option to change format field.
`$listMapper->add('status', null, array('template' => 'MyCoolBundle:Status:status_list.html.twig'))`

**Comment by SukachVitally** [comment]
Sorry. I update my question.

**Comment by tim96** [comment]
@SukachVitally sorry, but I don't find information about how to using custom class type for list field type. 
https://sonata-project.org/bundles/admin/master/doc/reference/action_list.html#available-types-and-associated-options
https://sonata-project.org/bundles/doctrine-orm-admin/master/doc/reference/list_field_definition.html#types-available

**Comment by greg0ire** [comment]
Right, but it looks like it works anyway… hidden feature?

**Comment by greg0ire** [comment]
Seems that this is used by the ORM bundle to choose a template matching the type of relation, see https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3751e894e658ca9c6b59deda696019840494de15/Builder/ListBuilder.php#L134

**Comment by greg0ire** [comment]
After the right relation is done, this is executed : `$admin->attachAdminClass($fieldDescription);`. It finds PhoneNumberAdmin if it exists, and attaches it to the field description. This is probably used later for display…

**Comment by greg0ire** [comment]
My bad, it is used for linking : https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3751e894e658ca9c6b59deda696019840494de15/Resources/views/CRUD/list_orm_many_to_one.html.twig#L18

**Comment by tim96** [comment]
> Right, but it looks like it works anyway… hidden feature?

@greg0ire can you explain how it works? @SukachVitally say that it doesn't work.

**Comment by greg0ire** [comment]
> @greg0ire can you explain how it works? @SukachVitally say that it doesn't work.

Hardly. By "it works", I just mean that obviously, @SukachVitally is not getting a 500. It does not work as expected, but it "works" in the sense that the phone number is displayed.

**Comment by greg0ire** [comment]
Closing due to lack of response.

**Comment by florentdestremau** [comment]
Still looking for an anwser, this is pretty annoying by sonata not to basically display an actual phone number... :(

**Comment by covex-nn** [comment]
@SukachVitally @florentdestremau phone number is instance of `libphonenumber\PhoneNumber`. This class has `__toString` method, which returns not formated debug information about object's properties

* https://github.com/giggsey/libphonenumber-for-php/blob/master/src/PhoneNumber.php

I have formated phone number with `temlate`:

```php
$listMapper
    ->add('phoneNumber', PhoneNumberType::class, [
        'template' => ':CRUD:phoneNumber_list_field.html.twig'
    ]);
```

Template `:CRUD:phoneNumber_list_field.html.twig` contents:

```twig
{% extends 'SonataAdminBundle:CRUD:base_list_field.html.twig' %}

{% block field %}
    {% if object.phoneNumber is null %}
        -
    {% else %}
        {{ object.phoneNumber|phone_number_format(2) }}
    {% endif %}
{% endblock %}
```

Here argument `2` for twig filter is `\libphonenumber\PhoneNumberFormat::NATIONAL`

* https://github.com/giggsey/libphonenumber-for-php/blob/master/src/PhoneNumberFormat.php
