### ISSUE TITLE
Twig Cache file generates Parse Error: syntax error

### ISSUE THREAD

**Issue by webdevilopers** [sonata-project/SonataAdminBundle#3633]
I get a strange debug error for some days now with `dev-master`. When trying to access a sonata admin list view I get:
**request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Parse Error: syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE)" at /app/cache/prod/twig/a7/a7a9af7119e75eb8391ea0c72b3b43e98ddf88c723e92565488abffefeb9c3fe.php line 253**

Looking at the cache file:
```php
    // line 3
    public function getattributes($__attributes__ = null, ...$__varargs__)
    {
        $context = $this->env->mergeGlobals(array(
            "attributes" => $__attributes__,
            "varargs" => $__varargs__,
        ));

        $blocks = array();

        ob_start();
```

I'm not sure if this is Sonata Admin related or if it is a pure twig issue, @twigphp?

As soon as I remove the cache files manually and reload the page - not clearing cache via command - everything is fine.

The lines now look like this:
```php
    // line 3
    public function getattributes($__attributes__ = null)
    {
        $context = $this->env->mergeGlobals(array(
            "attributes" => $__attributes__,
            "varargs" => func_num_args() > 1 ? array_slice(func_get_args(), 1) $
        ));
            
        $blocks = array();

        ob_start();
```

Any idea?

**Comment by greg0ire** [comment]
Apparently, twig generate php that is not compatible with your version of php (namely, the variadic parameters). I would says it is purely a twig issue. When you installed / updated `twig/twig`, were you using the same version of php as when you are executing this piece of code?

**Comment by webdevilopers** [comment]
Good catch, @greg0ire ! Indeed there are different versions. My DEV is more uptodate.

DEV:
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 

PROD:
PHP 5.5.30 (cli) (built: Dec 16 2015 06:09:55) 

Still strange because when deploying the command is executed on the server:
```
SYMFONY_ENV=prod /usr/bin/env php app/console cache:warmup  --no-debug )
```

When I remove the cache manually and simply reloading the page - no command - shouldn't the generated cache files be the same? At least regarding the PHP version?
But wait! I will compare my CLI and APACHE versions of PHP. Maybe our provider didn't update CLI.

**Comment by webdevilopers** [comment]
Nope, both version are PHP Version *5.5.30*.

Is there anything else that could be different when using the warmup command or removing the files manually and generate them by the "apache" "www-data / web" user?

Anyways I should update to *5.6* on the server too.

**Comment by nlzet** [comment]
Do you have a php versioned defined in composer.json by using https://getcomposer.org/doc/06-config.md#platform ?

I believe this overrides your php version to force the behaviour of using the same minimal PHP version.

**Comment by webdevilopers** [comment]
My `composer.json` requires:
```javascript
    "require": {
        "php": ">=5.3.3",
```

My `composer.lock` for `twig`:
```javascript
            "require": {
                "php": ">=5.2.7"
            },
```

Anywhere else I should look @nlzet?

When were the `the variadic parameters` introduced, @greg0ire - > php *5.5.30*?

**Comment by greg0ire** [comment]
It wouldn't make sense to introduce a feature like that and not bump the middle number.

**Comment by greg0ire** [comment]
What version of twig are you using ? `composer show --installed|grep twig`

**Comment by webdevilopers** [comment]
```
twig/extensions                              v1.3.0             Common additional features for Twig that do not directly belong in core
twig/twig                                    v1.24.0            Twig, the flexible, fast, and secure template language for PHP
```

**Comment by greg0ire** [comment]
It requires php >= 5.2.7, that's strange. Look for variadic params in the code source.

**Comment by greg0ire** [comment]
Do you have the name of the twig template?

**Comment by greg0ire** [comment]
What do you have when printing `PHP_VERSION_ID`

**Comment by greg0ire** [comment]
Maybe you should debug [this line](https://github.com/twigphp/Twig/blob/v1.24.0/lib/Twig/Node/Macro.php#L57)

**Comment by webdevilopers** [comment]
Looks like the `knp_menu.html.twig`:
https://gist.github.com/webdevilopers/3029aaccf1b7ddbac48f#file-a9f4d476b68d309ff919ce927ebe438582abbff7232497b2079d47159e04d5d4-php

**Comment by webdevilopers** [comment]
I debugged the line inside the `vendor` file but it is not called at call when warming up cache on the server. Neither when reloading page.

**Comment by greg0ire** [comment]
[The corresponding line](https://github.com/KnpLabs/KnpMenu/blob/master/src/Knp/Menu/Resources/views/knp_menu.html.twig#L3) ?

**Comment by greg0ire** [comment]
> What do you have when printing PHP_VERSION_ID ?

**Comment by greg0ire** [comment]
> I debugged the line inside the vendor file but it is not called at call when warming up cache on the server. Neither when reloading page.

Maybe you're debugging the wrong file ? Can you grep `varargs` in the whole project?

**Comment by webdevilopers** [comment]
Since the `twig` cache is not created in `dev` I checked the `prod` version and found 4 files:

```
grep -rnw './' -e "varargs"
./e9/e9dfd81bf031ea85d9804ab7e838d1af6b7fa916a0b91de557440f88f38459a1.php:257:            "varargs" => $__varargs__,
./0a/0a1080967eab56170116d855cfe10ff35194d7f9a36aa8bb796854fdd145c756.php:33:            "varargs" => $__varargs__,
./a6/a67c84c9107a2fe98c2901150c872d4ff3dd2849e91ee2260ecf12b19d0437db.php:28:            "varargs" => $__varargs__,
./b6/b6be8a423f90509e4a9ee55d7f8f59329105088448720a1789ccddc553b6362c.php:115:            "varargs" => $__varargs__,
```

The related templates are:
* knp_menu_base.html.twig
* SonataAdminBundle:CRUD:base_acl_macro.html.twig
* SonataAdminBundle:CRUD:base_edit_form_macro.html.twig
* SonataAdminBundle:CRUD:tree.html.twig

Looks like this could be Sonata Admin related. I've updated the complete files to the gist:
https://gist.github.com/webdevilopers/3029aaccf1b7ddbac48f

**Comment by webdevilopers** [comment]
Maybe something went wrong here @OskarStark ? 3 days ago would fit.
https://github.com/sonata-project/SonataAdminBundle/pull/3621/files

**Comment by greg0ire** [comment]
Well you can use git bisect if you suspect the admin bundle, but frankly, I don't see how this can be a Sonata issue.

Also : 

> Maybe you're debugging the wrong file ? Can you grep varargs in the whole project (including app, I'm thinking class cache, etc…)?

Can you please grep the whole project, not just the production cache ?

**Comment by webdevilopers** [comment]
Missed that, sorry. Result:

```
grep -rnw './' -e "varargs"
Passwort: 
Das hat nicht funktioniert, bitte nochmal probieren.
Passwort: 
./app/cache/prod/twig/e9/e9dfd81bf031ea85d9804ab7e838d1af6b7fa916a0b91de557440f88f38459a1.php:257:            "varargs" => $__varargs__,
./app/cache/prod/twig/0a/0a1080967eab56170116d855cfe10ff35194d7f9a36aa8bb796854fdd145c756.php:33:            "varargs" => $__varargs__,
./app/cache/prod/twig/a6/a67c84c9107a2fe98c2901150c872d4ff3dd2849e91ee2260ecf12b19d0437db.php:28:            "varargs" => $__varargs__,
./app/cache/prod/twig/b6/b6be8a423f90509e4a9ee55d7f8f59329105088448720a1789ccddc553b6362c.php:115:            "varargs" => $__varargs__,
./vendor/twig/twig/doc/tags/macro.rst:24:  special ``varargs`` variable as a list of values.
./vendor/twig/twig/doc/templates.rst:548:special ``varargs`` variable as a list of values.
./vendor/twig/twig/lib/Twig/Node/Macro.php:19:    const VARARGS_NAME = 'varargs';
./vendor/twig/twig/test/Twig/Tests/Fixtures/macros/varargs.test:7:    {{- var }}: {{ varargs|join(", ") }}
./vendor/twig/twig/test/Twig/Tests/Fixtures/macros/varargs.test:11:    {{- varargs|join(", ") }}
./vendor/twig/twig/test/Twig/Tests/Fixtures/macros/varargs_argument.test:2:macro with varargs argument
./vendor/twig/twig/test/Twig/Tests/Fixtures/macros/varargs_argument.test:4:{% macro test(varargs) %}
./vendor/twig/twig/test/Twig/Tests/Fixtures/macros/varargs_argument.test:7:Twig_Error_Syntax: The argument "varargs" in macro "test" cannot be defined because the variable "varargs" is reserved for arbitrary arguments in "index.twig" at line 2.
./vendor/twig/twig/test/Twig/Tests/Node/MacroTest.php:36:            $varargs = '$__varargs__';
./vendor/twig/twig/test/Twig/Tests/Node/MacroTest.php:39:            $varargs = 'func_num_args() > 2 ? array_slice(func_get_args(), 2) : array()';
./vendor/twig/twig/test/Twig/Tests/Node/MacroTest.php:50:        "varargs" => $varargs,
```

**Comment by greg0ire** [comment]
Just wanted to make sure there were no other possibility than ./vendor/twig/twig/lib/Twig/Node/Macro.php in your project. Can you slightly change line 57 (change the number of dots for instance), just to see what happens?

**Comment by webdevilopers** [comment]
Removing the dots in line **257** immediately fixes the issue.

**Comment by greg0ire** [comment]
I was talking about line 57 of vendor/twig/twig/lib/Twig/Node/Macro.php , not line 257 of the generated file.

**Comment by greg0ire** [comment]
The goal is to see if both file have anything to do with each other.

**Comment by greg0ire** [comment]
Remove one dot (not all dots) line 57, and see if your error message has one or two dots. If it has 2, you'll know you are looking at the right file.

**Comment by webdevilopers** [comment]
Removing a dot doesn't change the error, it is still line *253*:
`/app/cache/prod/twig/3c/3c517fe0d83ac6b34f22fb34cd3fa5c8398007ea0caed7a6156abdd9d881cdb1.php line 253`

**Comment by webdevilopers** [comment]
Instead of removing the cache folder manually I know used the cli and look what happens:
```
SYMFONY_ENV=prod php app/console cache:clear
Clearing the cache for the prod environment with debug false
PHP Parse error:  syntax error, unexpected '.', expecting variable (T_VARIABLE) in /usr/local/www/apache24/noexec/spspartnerstage/releases/20160305174613/vendor/twig/twig/lib/Twig/Environment.php(403) : eval()'d code on line 253
PHP Fatal error:  Class '__TwigTemplate_07018bd0b907061e6219ae248210dfe0eb5e25a4dc1f85b1b16e9161cd566426' not found in /usr/local/www/apache24/noexec/spspartnerstage/releases/20160305174613/vendor/twig/twig/lib/Twig/Environment.php on line 411

                                                                                                                                        
  [Symfony\Component\Debug\Exception\ClassNotFoundException]                                                                            
  Attempted to load class "__TwigTemplate_07018bd0b907061e6219ae248210dfe0eb5e25a4dc1f85b1b16e9161cd566426" from the global namespace.  
  Did you forget a "use" statement?                                                                                                     
```

Now what is this about?

**Comment by greg0ire** [comment]
> Removing a dot doesn't change the error, it is still line 253:
/app/cache/prod/twig/3c/3c517fe0d83ac6b34f22fb34cd3fa5c8398007ea0caed7a6156abdd9d881cdb1.php line 253

So, even after removing the cache ?

The error you're getting is probably about the two dots when warming up the cache.

I guess you no longer have the 3 dots line 253 after trying to remove the cache folder with the cli, do you?

**Comment by greg0ire** [comment]
You could try doing a syntactically valid change, like changing the variable name instead of removing a dot.

**Comment by webdevilopers** [comment]
* Deploy app that updates vendor and warms up cache
* Removedone dot from the Macro.php
* Error remains the same in twig template at line 253 in cache folder

A:
* Remove the cache folder
* Clear cache
* Three dots are gone - fixed

B:
* Clear cache
* Additional Twig Environment error

**Comment by greg0ire** [comment]
A: Three dots ? When you removed one?!?
B: To clear the cache, the current cache is used, hence the error you get probably.

**Comment by greg0ire** [comment]
Maybe you should stop deploying and try to reproduce this locally (with ca:cl --env=prod , and by using app.php instead of app_dev.php).

**Comment by webdevilopers** [comment]
Checked PROD on my machine now and there are no problems and no `...` anywhere! ;)
Corrected my list above.

**Comment by greg0ire** [comment]
@hason can you help ? I'm out of ideas. Can you for example tell us if you think this is a sonata or twig bug?

**Comment by webdevilopers** [comment]
A PHP Update on our server will still take some weeks. But maybe our provider can update the CLI version to **5.5.9**. Then we can see if the problem is the PHP version.

**Comment by greg0ire** [comment]
> PROD:
PHP 5.5.30 (cli) (built: Dec 16 2015 06:09:55) 

> But maybe our provider can update the CLI version to 5.5.9.

**Comment by webdevilopers** [comment]
Sorry?

**Comment by greg0ire** [comment]
You said production was using 5.5.30, and no you talk about upgrading it to 5.5.9 ???

**Comment by webdevilopers** [comment]
Stupid me, mixed up the version. Read **5.5.3**. I will update `dev` and check for the issue.

**Comment by webdevilopers** [comment]
I'm now using `PHP 5.5.32-1+deb.sury.org~trusty+1 (cli)` in `dev`, still **5.5.30** in `PROD`.
No issue w/ warming up or clearing cache.

My `dev` runs on Ubuntu and the `prod` on FreeBSD. Had several issues on FreeBSD w/ deployment tools and cli commands. But can't imagine anything related to php.

**Comment by greg0ire** [comment]
> still 5.5.30 in PROD

Really?

**Comment by greg0ire** [comment]
> > What do you have when printing PHP_VERSION_ID ?

> What do you have when printing PHP_VERSION_ID ?

What do you have when printing PHP_VERSION_ID ?

**Comment by webdevilopers** [comment]
Where should I echo it? CLI or app*.php?

**Comment by greg0ire** [comment]
Both I guess, unless you figured out if you have the problem only with CLI or web?

**Comment by webdevilopers** [comment]
Sorry for the late answer, we are experiencing serious problems with our server and provider now.
I can't even really deploy or PUSH to our git.

All I could find out for PHP_VERSION_ID so far is:
* PROD: web = 50530, cli = 50606
* DEV: web + cli = 50618 after update

Our provider agrees that it shouldn't be the php version. Maybe a permission problem with the cache files.

**Comment by greg0ire** [comment]
Ha!!!! 50606!!! For PROD cli! There's your bug!

**Comment by greg0ire** [comment]
```php
<?php
        if (PHP_VERSION_ID >= 50600) {
            if ($count) {
                $compiler->raw(', ');
            }
            $compiler->raw('...$__varargs__');
        }
```

**Comment by webdevilopers** [comment]
I'm totally confused because there is a lot going on in this project.

Is it just the PHP Version conflict that causes the issue?

Since our provider won't downgrade everything should work fine if CLI and WEB are upgraded to **5.6**?

**Comment by greg0ire** [comment]
> I'm totally confused because there is a lot going on in this project.

Breathe :)

The PHP version conflict causes the issue for sure and BTW, it isn't a Sonata problem, nor is it a Twig problem.

Things you need to get straight : 

- is your PROD CLI version really 5.3.30 ?
- if yes, is your PROD CLI `PHP_VERSION_ID` really 50606 ?
- if yes, ask your provider why the f*** .

Good luck :)

**Comment by webdevilopers** [comment]
Thanks for all the help @greg0ire ! I will close this issue and check it as soon as the server was updated.
But our provider still wants to wait some weeks because they regard **5.6** as "stable" enough. Ouch!

**Comment by webdevilopers** [comment]
FYI: We totally switched to a new provider with CentOS running php **5.6** and **7** anytime we want - none of the issues mentioned here ever appeared with our code again. :+1:
