### ISSUE TITLE
Fatal Error installing stable packages using composer

### ISSUE THREAD

**Issue by DavidGarciaCat** [sonata-project/SonataAdminBundle#3635]
Hey there,

I am trying to update my packages (from previous/old `dev-master` to the latest stable versions) and I am getting an error. Composer is installing all packages without any problem but looks like there is an issue between `AdminBundle` and `BlockBundle`.

These are the packages that I have on my project:

```
        ...
        "sonata-project/admin-bundle": "^2.3",
        "sonata-project/block-bundle": "^2.3",
        "sonata-project/cache": "^1.0",
        "sonata-project/core-bundle": "^2.3",
        "sonata-project/datagrid-bundle": "^2.2",
        "sonata-project/doctrine-extensions": "^1.0",
        "sonata-project/doctrine-orm-admin-bundle": "^2.3",
        "sonata-project/easy-extends-bundle": "^2.1",
        "sonata-project/exporter": "^1.4",
        "sonata-project/google-authenticator": "^1.0",
        "sonata-project/user-bundle": "^2.2",
        ...
```

Please have a look to the error message:

```
Fatal error: Declaration of Sonata\AdminBundle\Block\AdminListBlockService::validateBlock() must be compatible with Sonata\BlockBundle\Block\BlockAdminServiceInterface::validateBlock(Sonata\CoreBundle\Validator\ErrorElement $errorElement, Sonata\BlockBundle\Model\BlockInterface $block) in vendor/sonata-project/admin-bundle/Block/AdminListBlockService.php on line 108

Call Stack:
    0.0005     233320   1. {main}() app/console:0
    0.0282    4129432   2. Symfony\Component\Console\Application->run() app/console:27
    0.0307    4353456   3. Symfony\Bundle\FrameworkBundle\Console\Application->doRun() vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:123
    0.0307    4353680   4. Symfony\Component\HttpKernel\Kernel->boot() vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:70
    0.0536    5412232   5. Symfony\Component\HttpKernel\Kernel->initializeContainer() app/bootstrap.php.cache:2475
    0.2594   12573952   6. Symfony\Component\DependencyInjection\ContainerBuilder->compile() app/bootstrap.php.cache:2697
    0.2622   12624624   7. Symfony\Component\DependencyInjection\Compiler\Compiler->compile() vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:593
    4.4320   30458000   8. JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass->process() vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:107
    4.9348   48918592   9. JMS\AopBundle\DependencyInjection\Compiler\PointcutMatchingPass->processDefinition() vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php:64
    4.9348   48922304  10. class_exists() vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php:110
    4.9348   48922696  11. spl_autoload_call() vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php:110
    4.9348   48922760  12. Symfony\Component\Debug\DebugClassLoader->loadClass() vendor/jms/aop-bundle/JMS/AopBundle/DependencyInjection/Compiler/PointcutMatchingPass.php:110
```

Given security reasons, all stable projects should use stable versions, but we cannot update our packages if we are giving errors like this one. Any idea about how to fix this, or how long will take an update to prevent this error?

Cheers,

**Comment by greg0ire** [comment]
I have no time for this right now, but maybe you can help ?

Can you : 

- look at the block bundle issue tracker to make sure the bug isn't already reported?
- look at both signatures and tells us in which way they are incompatible ?
- tell us when they ceased to be compatible with each other, provided they ever were?
- tell us which versions of both bundles can work together when it comes to this signature?

I'll probably have a look at all this later, but if you can do this in the meantime, it will be quicker.

**Comment by greg0ire** [comment]
Wow, thanks for the help!

1. Nothing found
2. I think what differs is the namespace of `ErrorElement`
3. They ceased to be compatible with each other since [this commit](https://github.com/sonata-project/SonataBlockBundle/commit/06fac2531ac872ea94a650a345331e14c4da9eb0), and were compatible again since [this commit](https://github.com/sonata-project/SonataAdminBundle/commit/0c9439f01e85842f267cdd91ee0a93b05f09d3dd)
4. SonataAdminBundle can work with BlockBundle if block version < 2.3.0 or if AdminBundle is master.

**Comment by greg0ire** [comment]
I think the best solution for you is to use block bundle  ~2.3.9

**Comment by DavidGarciaCat** [comment]
@greg0ire sorry for the delay, but that was an issue related to the company, and I was out.

Looks like if I use the last releases of those bundles (`admin-bundle 2.3.7` and `block-bundle 2.3.9`) I get the error. However if I use the `admin-bundle 2.3.7` and `block-bundle 2.2.7` it works as expected.

I hope this can help.

**Comment by greg0ire** [comment]
The last releases of the bundles are not supposed to work together. Can you please close this issue?

**Comment by DavidGarciaCat** [comment]
:+1:
