### ISSUE TITLE
Support for multiple entitymanagers / admin's

### ISSUE THREAD

**Issue by kciredor** [sonata-project/SonataAdminBundle#364]
Wouldn't it be great if Sonata's AdminBundle supports multiple entitymanagers?

For example, I've created two applications: CompanyWebsiteBundle and CompanyCrmBundle. The CompanyCrmBundle has a SonataAdmin implementation and the admin can perform crud operations on CrmBundle's tables. If you would be able to use two entitymanagers in 1 admin setup, it's possible for a single CMS to administrate both the WebsiteBundle -and- CrmBundle! (They use two different databases).

Would make my life (and many others) a lot easier. One admin instead of two, is awesome!

**Comment by chakib-lah** [comment]
Hello how can I create a new service for inject setModelManager method??
