### ISSUE TITLE
[standard_layout] Moment.js and select2 translation files not referenced correctly

### ISSUE THREAD

**Issue by calinpristavu** [sonata-project/SonataAdminBundle#3642]
Hi guys,
This is addressed to dev-master

In [standard_layout.html.twig#L65-L76](https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/standard_layout.html.twig#L65-L76), we load the moment and select2 vendor locale files. 
The thing is that they have a different file name that the one we're looking for.
here's a `ls` from the moment locale folder:

> af.js     ar.js  bn.js  ca.js  da.js     en-au.js  es.js  fi.js     fy.js  hr.js     is.js  ka.js  lt.js  ml.js     my.js  nn.js     ro.js  sl.js       sv.js     tr.js        uk.js     zh-tw.js
> ar-ma.js  az.js  bo.js  cs.js  de-at.js  en-ca.js  et.js  fo.js     gl.js  hu.js     it.js  km.js  lv.js  mr.js     nb.js  pl.js     ru.js  sq.js       ta.js     tzl.js       uz.js
> ar-sa.js  be.js  br.js  cv.js  de.js     en-gb.js  eu.js  fr-ca.js  he.js  hy-am.js  ja.js  ko.js  me.js  ms-my.js  ne.js  pt-br.js  si.js  sr-cyrl.js  th.js     tzm-latn.js  vi.js
> ar-tn.js  bg.js  bs.js  cy.js  el.js     eo.js     fa.js  fr.js     hi.js  id.js     jv.js  lb.js  mk.js  ms.js     nl.js  pt.js     sk.js  sr.js       tl-ph.js  tzm.js       zh-cn.js

And we're assuming all files are of the format `a-b.js`
for example, if the locale is `ro_RO`, the asset will not be found (it looks for `ro-ro.js` instead of `ro.js`).

there are two options here:
1. we duplicate the locale name in the locale file names for the ones that don't respect the format `xx-yy.js`
2. using a custom twig function that wraps the asset function, which checks using the filesystem that the asset exists, and if not, tries the alternative format.

Any ideas? I'd be happy to submit a PR with any of the solutions.
(btw this is quite critical, as it messes up the remaining js)

**Comment by greg0ire** [comment]
What about the case when the locale doesn't even exist? There should be a fallback system IMO. Implementing 2. seems the way to go, but I think maybe we are not the first to have the problem? Could you look at [the Moment.js issue tracker](https://github.com/moment/moment/search?utf8=%E2%9C%93&q=locale+fallback&type=Issues) to see if this problem has been encountered and if yes, how it was solved?

**Comment by calinpristavu** [comment]
The thing is, it's not quite their responsibility. They provide some translations, and it's up to us if we use them or not.

However i'll check if some encountered this in their issues.

As a side note, even though option 2 is the professional way to go, it solves a problem that should not exist in the first place (names should always be normalized).
Therefore I would go with solution 1 as a temporary alternative to when they provide a normalized format to their file names.

**Comment by greg0ire** [comment]
What about the locale existence problem? Shouldn't it exist? Plus, just like fr is a valid locale, just like fr_FR . See http://symfony.com/doc/current/reference/constraints/Locale.html

**Comment by calinpristavu** [comment]
1.The existence problem should indeed be solved by a twig function which first checks if the file exists.

2. That's exactly my point. sf standard supports both the 2 char and the 5 char locale. BUT our filesystem should be decoupled to the locale format. It should pick one of the two ISOs for the file names. [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) only is out of the question, because it doesn't cover cases like en + gb and en + UK, plus both vendors "support" [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes) also.

Therefore, the suggestion is: 
1. normalize all file names according to [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1#Current_codes)
2. implement an "assetFetcher" twig function which accepts 3 args: 1 the directory containing the locales, 2 the locale(whatever format) 3 the asset extension(limited to css/js, so that we don't mess around with images and wild html attributes)

asset fetcher should:
- normalize the locale format (ro => ro-ro, en_GB => en-gb)
- using the `filesystem` component, find the first file containing the normalized locale in its name + extension
- silent fail in prod if no file found.
- call the `asset` function on the normalized asset path
- wrap the asset response in an "script src" or "link ref" depending on the extension

However this breaks BC in so many ways :(
What do you say?

**Comment by greg0ire** [comment]
I think maybe we should have a look at how symfony does things? There is a translation component that 
supports all formats, maybe it could be reused for this purpose?
I'm reluctant with the normalize filenames solution, because I don't like touching files that shouldn't even be check in in revision control (they are an external dependency).

**Comment by greg0ire** [comment]
Also, [the doc](http://momentjs.com/docs/#/i18n/loading-into-browser/) says there is a file with all locales minified into one. Maybe we should use that instead if it is not too heavy.

**Comment by greg0ire** [comment]
[The locales min file](https://raw.githubusercontent.com/moment/moment/develop/min/locales.min.js) weights 151 Ko

**Comment by calinpristavu** [comment]
:+1: This is the optimal solution for momentjs. Also, for BC reasons, we could also keep the current locale files.

the same must be achieved with select2. Unfortunately, in their repo, there is no translation file which contains all locales. Furthermore, our version of select2 is quite old, and has a totally different folder structure to what [their repo](https://github.com/select2/select2/tree/master/src/js/select2) has...
So how should we approach this one?
Unfortunately google or [select2 docs](https://select2.github.io/options.html) didn't help much with regards to translation files. I'm not a js person, but [this function](https://github.com/select2/select2/blob/master/src/js/select2/defaults.js#L248) seems to load translations on demand from their filesystem without having to manualy include it.
What do you think? Is an upgrade a viable option?

**Comment by greg0ire** [comment]
> So how should we approach this one?

I think we should recommend the use a package manager instead of bundling js libs with sonata.

>  I'm not a js person

I'm not either, so let's call for help to someone who is. @ju1ius , can you give us your thoughts on these problems?

**Comment by calinpristavu** [comment]
We could also make use of their [new Translation object](https://github.com/select2/select2/blob/master/src/js/select2/translation.js) to load translations in a script tag in our Admin.js maybe?

**Comment by greg0ire** [comment]
Yes, maybe this is the way to go. I think select2 is not supposed to be tweaked that much by users, so upgrading it can be considered an acceptable BC-break

**Comment by ju1ius** [comment]
> Also, the doc says there is a file with all locales minified into one. The locales min file weights 151 Ko

Maybe for a temporary solution... AFAICT, Sonata already does this for jquery-ui.
But that's ~140Ko wasted on each request...

Concerning the normalization problem: these language files are static and almost never change. Why perform filesystem checks on every request ? Furthermore, each plugin will likely have it's own custom i18n system, requiring to handle the special cases.

IMO, these checks should happen at build time, not runtime.
So there would be a solution n°3:
  - Write a build task that walks your javascript dependencies searching for i18n files.
  - From that information, build a mapping between locales and translation files (normalizing the locale names as needed)
  - Dump that mapping to a JSON file.
  - Load that file once per request.
  - Use this info in your twig function to perform the path resolution logic in-memory.


> We could also make use of their new Translation object to load translations in a script tag in our Admin.js maybe?

@calinpristavu yes they seem to have implemented a way to lazy-load i18n files.
However select2 in Sonata is still at version 3 (not 4) and upgrading requires changing the `Sonata\AdminBundle\Form\TypeModelAutocompleteType` class. I'm currently in the process of refactoring the AdminBundle JS to address #3173, so I'll try to have a look at it.

**Comment by cassianotartari** [comment]
I'm here to confirm the bug with locales and moment.

My locale is set to ``pt_BR`` and ``SonataAdminBundle::standard_layout.html.twig`` translate my locale to the follow js ``/bundles/sonatacore/vendor/moment/locale/pt-BR.js`` but there is no ``pt-BR.js`` file only ``pt-br.js`` so a possible solution would be add ``lower`` filter under the template:
```twig
<script src="{{ asset('bundles/sonatacore/vendor/moment/locale/' ~ locale|replace({'_':'-'})|lower ~ '.js') }}"></script>
```

I'm running:

```
$ composer show sonata-project/*
sonata-project/admin-bundle              3.3.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.0.1 Symfony SonataBlockBundle
sonata-project/cache                     1.0.7 Cache library
sonata-project/core-bundle               3.0.3 Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.0.4 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.5.0 Lightweight Exporter library
```

```
$ composer show symfony/*
symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2
symfony/monolog-bundle     2.11.1  Symfony MonologBundle
symfony/phpunit-bridge     v3.1.1  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v3.1.1  The Symfony PHP framework
```

```
$ php -v
PHP 7.0.5-2+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
    with blackfire v1.10.4, https://blackfire.io, by Blackfireio Inc.
```
