### ISSUE TITLE
Twig related unit tests should compare DOM documents, not strings.

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/SonataAdminBundle#3646]
Hi,
While working on #3173, I changed the way xeditable data is passed to the widget.
The old way was writing json strings in twig:

``` twig
data-source="[{value: 0, text: '{%- trans from 'SonataAdminBundle' %}label_type_no{% endtrans -%}'},{value: 1, text: '{%- trans from 'SonataAdminBundle' %}label_type_yes{% endtrans -%}'}]"
```

I changed this to use the twig `json_encode` filter,:

``` twig
data-source="{{ [
  {value: 0, text: 'label_type_no'|trans({}, 'SonataAdminBundle')},
  {value: 1, text: 'label_type_yes'|trans({}, 'SonataAdminBundle')},
]|json_encode|e('html_attr') }}"
```

However, this broke a few unit tests (notably [testRenderListElement](https://github.com/sonata-project/SonataAdminBundle/blob/master/Tests/Twig/Extension/SonataAdminExtensionTest.php#L191)), because we are testing twig's string output. Which is a shame, since now I have to use twig_escape_filter all over the place in phpunit `@dataProvider` methods (which doesn't work in PHPUnit 4 btw because dataProviders are loaded before bootstrap.php).

In 90% of the cases what we want to test is the correctness of the **DOM structure**. We don't care how Twig escape things as long as the DOM contains the right data. We don't care if an attribute comes before of after another, but we do care about it's presence/absence and it's value. And element/attribute names are case-insensitive in HTML.
We should really compare DOMDocuments here, not strings.

**Comment by jordisala1991** [comment]
2 years without a lof of interest on an issue about tests. I guess Im closing it for now, since it does not affect the end user. Cant consider it a bug

If you want to reopen, please ping me
