### ISSUE TITLE
sonata_type_model_autocomplete: strange name of entity

### ISSUE THREAD

**Issue by navalex** [sonata-project/SonataAdminBundle#3654]
Hello,

I'm trying to create my own news bundle. I have an entity post, in which I made a connection with a Tag entity, it has the title field.

In PostAdmin form, I put the following code:

```
$formMapper
            ->add('tags', 'sonata_type_model_autocomplete', array(
                'property' => 'title',
                'multiple' => true,
                'minimum_input_length' => 1,
            ))
        ;
```

It works well at the search etc .. but instead of show me the title tag, it displays things like 

> Navalex\NewsBundle\Entity\Tag:00000000402b668400007fdc919d4ba6

I do not really understand how to fix it ...

**Comment by ju1ius** [comment]
@navalex You need to either implement `Tag::__toString() ` or `TagAdmin::toString($tag)`. 
```php
class TagAdmin extends Admin {
  public funtion toString($tag) {
    return $tag->getTitle();
  }
}
```

**Comment by pulzarraider** [comment]
Thank you @ju1ius for answer.
