### ISSUE TITLE
LoggerInterface error using jms/translation-bundle 

### ISSUE THREAD

**Issue by ScherlOMatic** [sonata-project/SonataAdminBundle#3658]
Info:
This error occurs after upgrading to symfony 3.0.3 and fixing the translation-bundle with the PR from NobletSolutions/JMSTranslationBundle.

Solution:
Replace following line:
- use Symfony\Component\HttpKernel\Log\LoggerInterface;
+ use Psr\Log\LoggerInterface;

Error:
> [Symfony\Component\Debug\Exception\FatalThrowableError]
  Type error: Argument 2 passed to Sonata\AdminBundle\Translator\Extractor\JM
  STranslatorBundle\AdminExtractor::__construct() must be an instance of Symf
  ony\Component\HttpKernel\Log\LoggerInterface, instance of Symfony\Bridge\Mo
  nolog\Logger given, called in ...

**Comment by greg0ire** [comment]
Hey! That's something I fixed in 91f3c5e165e8e077cc952bd6181b16d6a53c3c75 :)
