### ISSUE TITLE
Available support channels on IRC

### ISSUE THREAD

**Issue by iltar** [sonata-project/SonataAdminBundle#3664]
I'm usually online on freenode#symfony. Being an op on this channel, I try to help a lot of people daily. Sadly I cannot answer a lot of questions about Sonata other than to look elsewhere. Usually I see several Sonata questions come by that all go unanswered.

According to https://sonata-project.org/contributing people can find help when contributing to sonata on #symfony. I cannot find any references for people that seek help though. Is there an IRC channel or something similar I can redirect people to that seek help but cannot find it here?

I've tried contacting this message via contact at sonata-project dot org, but that didn't give any replies

**Comment by greg0ire** [comment]
@rande , can you answer this ?

**Comment by rccc** [comment]
Hello,

I think sonata deserves a dedicated irc channel.  I noticed that only #Symfony channel

**Comment by tim96** [comment]
@iltar Hi. What about stackoverflow? It is a good place to ask guestion if you can't find the answer in documentation, and developers who have the same problems as you, can read your answer there. IRC doesn't save history, but I'm not sure about it.

**Comment by iltar** [comment]
@tim96 I don't really mind where people can go for help as long as they have a place to go to. I just see too many sonata questions coming by and going unanswered on IRC.

**Comment by tim96** [comment]
@iltar I don't really think what it is a good idea. Can you show example of unanswered questions? I am sure sonata contributors don't sit where, sometimes they don't have time to answer here. I'm sure that developers who will using #sonata channel will using #symfony channel too.

**Comment by javiereguiluz** [comment]
@iltar I think IRC is the worst possible way of asking for help. It has the advantage of "live discussions", but it has lots of drawbacks:

  * If the person who can help you is not online, you won't get help. That doesn't happen with StackOverflow.
  * Maybe you are asking the same question which has been solved a million times ... but you don't know that and you can't look for previous questions. That can be solved with StackOverflow.
  * Live questions distract (and can even bother) people connected to IRC. That can be solved with StackOverflow.

So I always recommend using StackOverflow, because it's way better for people asking and answering questions.

**Comment by tim96** [comment]
@javiereguiluz Thank you. I try explain the same things, but you did it better.

**Comment by iltar** [comment]
Alright, so the best solution would be to redirect people to SO, got it!

**Comment by javiereguiluz** [comment]
@iltar but not only for Sonata, for Symfony too. A question answered on IRC is lost forever. All that effort is wasted. StackOverflow makes support remain forever.

**Comment by iltar** [comment]
@javiereguiluz I know, I'm also trying to fill in answers on SO every once in a while, it's just easier for me to help people 1 on 1 via IRC because I don't have time to browse. The advantage of IRC is that discussions arise why something is better, which I find a lot harder to do on SO. 

Either way, my question got answered, thanks

**Comment by greg0ire** [comment]
See https://github.com/sonata-project/SonataAdminBundle/pull/3683/commits/da8d662b1efd6161d2fd2f5734fb4a8307120541
