### ISSUE TITLE
Initialise sonata type collection with object collection

### ISSUE THREAD

**Issue by locs31** [sonata-project/SonataAdminBundle#3666]
Hi, is there a way to initialise a sonata type collection with a collection of object in configureformsfield or other?
Thanks

**Comment by greg0ire** [comment]
I think using `getNewInstance` would be the way to go.

**Comment by locs31** [comment]
I've try to use getNewInstance In the target entity mapped with the type collection field, but it's never call?

**Comment by greg0ire** [comment]
It's not in the entity, it's in the admin. You wouldn't get a new instance from an instance, would you ?

**Comment by greg0ire** [comment]
Also, please read the doc and make a PR if it is unclear.

**Comment by locs31** [comment]
Sorry in the Admin of course. I've read the doc, but the sonata admin is not well documented i found...

**Comment by locs31** [comment]
So i need to call the getNewInstance in the parent Admin not child admin?

**Comment by greg0ire** [comment]
> So i need to call the getNewInstance in the parent Admin not child admin?

You mean define, not call, don't you ?
I don't think `getNewInstance` is called recursively, so yes.


> the sonata admin is not well documented i found...

If this turns out to work, would you make a PR to improve this?

**Comment by locs31** [comment]
I'm don't know how PR work, and in fact you see i'm not a good level with sonata to make documentation I think, no?

**Comment by greg0ire** [comment]
> I'm don't know how PR work

Not a problem, I can help you.

> I'm not a good level with sonata to make documentation I think, no?

Now you understand why sonata admin is not well documented?

**Comment by locs31** [comment]
Why there is no people with good level in sonata admin?

**Comment by greg0ire** [comment]
> Why there is no people with good level in sonata admin?

Lol, wrong conclusion, smartass ;) They think they're not good enough to contribute. It's just documentation, and if what you document is wrong, we will help you make it right. First step if you want to understand how this works is to search `getNewInstance` in `vendor/sonata-project`

**Comment by locs31** [comment]
i've already use getNewInstance method, but never to initialize a sonata type collection !!

**Comment by greg0ire** [comment]
Well it is not different, you have your class A, that has an ArrayCollection property, so you create just that, an object A with a property initialized just like you want.

**Comment by greg0ire** [comment]
Looks like getNewInstance is not documented at all, so you would really do us a real favor by documenting that. Plus, you would know how to do a PR after that. Please consider it.

**Comment by locs31** [comment]
I consider ;). I will try to make that work for my sonata type collection and when it's good for me i'll try to make a PR. Is there any doc about how to make a PR?

**Comment by greg0ire** [comment]
Yes there is : https://github.com/sonata-project/SonataAdminBundle/blob/master/CONTRIBUTING.md#pull-requests

**Comment by locs31** [comment]
Thanks i will take a look. I will try making work my type collection and form step (my other issue) and i will be back next to try making a PR, perhaps begining of next week. Also other question, is there any date fixe for next release of sonata?

**Comment by greg0ire** [comment]
> Also other question, is there any date fixe for next release of sonata?

I don't know that, sorry.

**Comment by locs31** [comment]
You work for sonata?

**Comment by greg0ire** [comment]
You will too soon ;) I have this "Sonata Project member" because I have access rights to another sonata repository, but that's all.

**Comment by locs31** [comment]
Lool perhaps ;). Thanks for your help :)

**Comment by greg0ire** [comment]
No follow-up? Closing.
