### ISSUE TITLE
SonataAdminBundle - category/create issue

### ISSUE THREAD

**Issue by Billybroksen** [sonata-project/SonataAdminBundle#3670]
An exception has been thrown during the rendering of a template ("No entity manager defined for class Doctrine\Common\Collections\ArrayCollection") in "SonataAdminBundle:CRUD:base_edit_form.html.twig".

Hello guys, I am having issue while i am trying to access my page category/create while I was following this tutorial : 
https://sonata-project.org/bundles/admin/2-3/doc/getting_started/the_form_view.html

So does anyone know what's problem?

[](http://postimg.org/image/st6300nah/)

**Comment by greg0ire** [comment]
Can you show provide us with a stack trace?
