### ISSUE TITLE
Autocomplete error with the basic setup (ManyToOne): Notice: Undefined index: read_only

### ISSUE THREAD

**Issue by Saint-Cyr** [sonata-project/SonataAdminBundle#3673]
I just setup the basic configuration like show in the documentation in order to make one form field autocomoplete (ManyToOne relationship) but I still get the following error: Notice: Undefined index: read_only.

`/**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->add('figureValue')
            ->add('wordValue')
            ->add('pollingStation', 'sonata_type_model_autocomplete', array('property' => 'name'))
            ->add('prParty')
        ;
    }`

`/**
     * @ORM\ManyToOne(targetEntity="myEntity", inversedBy="prVoteCasts")
     * @ORM\JoinColumn(nullable=false)
     */
    private $pollingStation;`

**Comment by greg0ire** [comment]
Can you provide us with a stack trace?

**Comment by Saint-Cyr** [comment]
> Can you provide us with a stack trace?
Sorrry I don't understand but following is my composer.json:

`{
    "name": "root/vtally",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.0.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "friendsofsymfony/user-bundle": "~2.0@dev",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "^2.1",
        "sonata-project/user-bundle": "^2.2",
        "friendsofsymfony/rest-bundle": "^1.7"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0",
        "doctrine/doctrine-fixtures-bundle": "^2.3",
        "hautelook/alice-bundle": "^1.2",
        "doctrine/data-fixtures": "^1.1"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "platform": {
            "php": "5.5.9"
        }
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}`

**Comment by greg0ire** [comment]
A [stack trace](http://stackoverflow.com/questions/3988788/what-is-a-stack-trace-and-how-can-i-use-it-to-debug-my-application-errors) would be more helpful

**Comment by Saint-Cyr** [comment]
Sorry ! that is it:

`        $builder->setAttribute('minimum_input_length', $options['minimum_input_length']);
        $builder->setAttribute('items_per_page', $options['items_per_page']);
        $builder->setAttribute('req_param_name_page_number',               $options['req_param_name_page_number']);
        $builder->setAttribute('disabled', $options['disabled'] || $options['read_only']);
        $builder->setAttribute('to_string_callback', $options['to_string_callback']);
        if ($options['multiple']) {`

**Comment by ju1ius** [comment]
@Saint-Cyr To find the stack trace:
At the bottom of Symfony's error page, there's a section called «Stack Trace (Plain Text)» with a blue "+" icon. Click on this icon and copy what's in there:

![stack-trace](https://cloud.githubusercontent.com/assets/218404/14038929/1590a772-f257-11e5-94fb-8d4d3917fcfe.png)

Then paste it in a [Gist](https://gist.github.com/) and put the link here.
Thanks.

**Comment by greg0ire** [comment]
@ju1ius thanks for doing what I did not have the strength and patience to do.

**Comment by ju1ius** [comment]
@greg0ire You're welcome!
I think we really [need this](https://github.com/blog/2111-issue-and-pull-request-templates).

**Comment by Saint-Cyr** [comment]
Well one more time I apologize for I didn't understand how to make it easy so fast. Finally I hope you can see it now:
[https://gist.github.com/Saint-Cyr/015b98e359c6da90aabc](url)

**Comment by greg0ire** [comment]
clicking on your link gives a 404

**Comment by greg0ire** [comment]
Ok so that's only one line of the stack trace I think. Can you give us the full stack trace ?

**Comment by Saint-Cyr** [comment]
Yes I just realize it one moment please

**Comment by Saint-Cyr** [comment]
https://gist.githubusercontent.com/Saint-Cyr/015b98e359c6da90aabc/raw/6176162f129cf9769520ae10d8afc44386fcedc6/gistfile1.txt

**Comment by Saint-Cyr** [comment]
I'm still looking better way to publish it like yours please but for now you can see this: https://gist.githubusercontent.com/Saint-Cyr/015b98e359c6da90aabc/raw/6176162f129cf9769520ae10d8afc44386fcedc6/gistfile1.txt

**Comment by greg0ire** [comment]
> vendor/sonata-project/admin-bundle/Form/Type/ModelAutocompleteType.php at line 44

This is just one line in one file. I would like all the line in all the files of the stack please.

**Comment by Saint-Cyr** [comment]
update: https://gist.github.com/Saint-Cyr/4da2cb8dad2d43ec79ae#file-gistfile1-txt

**Comment by greg0ire** [comment]
Wait… IIRC, this was fixed and merged recently.

**Comment by greg0ire** [comment]
see  #3668

**Comment by Saint-Cyr** [comment]
Great job ! I'm doing "composer update" right now

**Comment by greg0ire** [comment]
Well?

**Comment by Saint-Cyr** [comment]
Yes Thank you @greg0ire  ! but after the update I realize 2 others bugs :
1 - When click on "show" action: `Unable to find template "@Admin/CRUD/base_show_macro.html.twig" in SonataAdminBundle:CRUD:base_show.html.twig at line 14.`

**Stack trace**: [stack trace](https://gist.github.com/Saint-Cyr/91a19befd536101ad121#file-gistfile1-txt)

**Comment by greg0ire** [comment]
Bug 1 looks familiar, check the latest issues. I don't understand 2 , proofread your post please

**Comment by greg0ire** [comment]
See #3684

**Comment by Saint-Cyr** [comment]
Thank you and all orther contributors of Sonata - Project for you make our job so easy ! Indeed the bug is fixed some days ago and I just update my vendor : `composer update`
