### ISSUE TITLE
View list translation

### ISSUE THREAD

**Issue by bilougit** [sonata-project/SonataAdminBundle#3674]
I have an entity `Trophy`. View list works fine. This entity is related to the entity `User`. Each trophy is assigned to a user (winner).
I need to display an information of the user in the view list of `Trophy`. Which works fine, but when a trophy is not assigned to any user I need to display `Not assignet yet`. This text lives in my symfony translation files (`messages.fr.yml`). How do I display it?

**Comment by greg0ire** [comment]
Having one big `messages.fr.yml` file is bad, you know. You should try to split your file into smaller files. Plus, how is `Not assignet yet` french? And finally, does the symfony profiler show you any missing translation?

**Comment by ju1ius** [comment]
@bilougit You could just override the label block of your widget
Let's say your admin service id is `acme.admin.trophy`, and you're using a `sonata_type_model_list` to render the related user form field:

```twig
{% block acme_admin_trophy_sonata_type_model_list_label %}
  {{ form_label(form) }}
  {% if value is empty %}
    {{ 'label.trophy.unassigned'|trans({}, 'AcmeTrophyBundle') }}
  {% endif %}
{% endblock %}
```

**Comment by ju1ius** [comment]
@bilougit Maybe once you've done that, you could make a PR to update the documentation :wink:

**Comment by greg0ire** [comment]
No answer… closing
