### ISSUE TITLE
[3.0] Sonata frontend/client-side RFC proposal

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/SonataAdminBundle#3680]
Hi, 

I took some time to write the beginning of a [proto-specification](https://github.com/ju1ius/sonata-frontend-rfc) about what could be done to improve the frontend/client-side part of sonata in the future major version(s).
The idea is to specify what the users should expect regarding dom structure (class names & data-attributes), javascript (events & apis).

Does this make sense ? Shall I continue ? Wanna help ?

**Comment by greg0ire** [comment]
ping @sonata-project/contributors

**Comment by jordisala1991** [comment]
Related to #3972

Closing this one, but Im letting a link on the other issue, so we can access this info if we need to at some point.
