### ISSUE TITLE
Endless 301 redirection when forcing https

### ISSUE THREAD

**Issue by GWillmann** [sonata-project/SonataAdminBundle#3686]
Hi,
​
I'm trying to secure the admin panel of SonataAdminBundle by forcing the https scheme for my App hosted on Heroku with Symfony 2.7.10. 

All routes are in HTTPS except : 

- the query made by the search input in the left panel,
![screen shot 2016-03-29 at 09 48 51 copy](https://cloud.githubusercontent.com/assets/5655900/14101320/0e58c63e-f594-11e5-83ec-437de7ea2d25.png)

- the query to add a new relation to an entity when using sonata_type_collection :
![screen shot 2016-03-29 at 09 49 28 copy](https://cloud.githubusercontent.com/assets/5655900/14101322/1742d33e-f594-11e5-986d-51073511e81d.png)

```php
$formMapper
    ->add(
        ‘reasons’, 'sonata_type_collection', array(
            'required' => false),
            array(
                'edit' => 'inline',
                'inline' => 'table',
                'sortable'  => 'position')
    );
```
​
These two cases lead to an error of "**mixed-content**" (http url being used with https is not secure).

​
There are others issues but the answers were not helpful for me :
https://github.com/sonata-project/SonataAdminBundle/issues/2903
https://github.com/sonata-project/SonataAdminBundle/issues/2483
https://github.com/sonata-project/SonataAdminBundle/issues/2497
​
I tried to forced https URLs with `scheme: [https]` in _routing.yml_ but I have a endless redirection…

**Comment by greg0ire** [comment]
Could you try to pinpoint the piece of code that makes this redirection? I think you can by finding the profile entry for the right url, using the "search" form of the symfony profiler.

**Comment by GWillmann** [comment]
Thank you for your answer @greg0ire.
I think the problem is solved as of this morning.

The problem seemed to come from the fact that I did not configure Symfony to work behind a load balancer/proxy which is mandatory when using Heroku.

See : 

- [Symfony Cookbook](http://symfony.com/doc/current/cookbook/request/load_balancer_reverse_proxy.html)

- [Heroku Best Practices](https://devcenter.heroku.com/articles/getting-started-with-symfony#trusting-the-load-balancer)

**Comment by greg0ire** [comment]
Glad to hear you fixed it.
