### ISSUE TITLE
Something wrong with checkbox on login admin screen

### ISSUE THREAD

**Issue by tim96** [sonata-project/SonataAdminBundle#3689]
Hi, @greg0ire .
I am using this version **"dev-master#a18a2d702240fe966938562c37912ae04ab085aa",** today after update to last version **"sonata-project/admin-bundle": "dev-master",** something wrong with my login screen. Usually I use firefox browser. Do you have this problem or I did something wrong?

![1](https://cloud.githubusercontent.com/assets/12379114/14120875/dece96ba-f605-11e5-871f-0b220eb6294f.png)
![2](https://cloud.githubusercontent.com/assets/12379114/14120876/defe301e-f605-11e5-8ee0-64a5af3d2987.png)

**Comment by greg0ire** [comment]
Hi, here is what you are probably looking for : https://github.com/sonata-project/SonataUserBundle/pull/709

**Comment by tim96** [comment]
@greg0ire yes, you are right. Thank you. I didn't use master branch of SonataUser bundle, so I simple change layout in my project.
