### ISSUE TITLE
Wrong instance parameter on SonataAdminExtension::renderListElement()

### ISSUE THREAD

**Issue by lilocon** [sonata-project/SonataAdminBundle#3694]
Type error: Argument 1 passed to Sonata\AdminBundle\Twig\Extension\SonataAdminExtension::renderListElement() must be an instance of Twig_Environment, instance of AppBundle\Entity\Product given, called in /var/www/vendor/sonata-project/admin-bundle/Controller/HelperController.php on line 309

**Comment by greg0ire** [comment]
What version of Sonata are you using ?

**Comment by lilocon** [comment]
"sonata-project/admin-bundle": "dev-master"

**Comment by greg0ire** [comment]
Can you change HelperController, line 294, to this ? 

`$content = $extension->renderListElement($this->twig, $rootObject, $fieldDescription);`

and report back ?

**Comment by Soullivaneuh** [comment]
After all, please stop copy paste your error on the title.

Next, can you be please more explicit about your error. For example, are you overriding `SonataAdminExtension` class?

Please note you are using a not stable version of sonata project, BC break changes could happen.

**Comment by lilocon** [comment]
`$content = $extension->renderListElement($this->twig, $rootObject, $fieldDescription);`
It is right..

**Comment by lilocon** [comment]
thinks

**Comment by greg0ire** [comment]
Ok, then wait for #3694 to be merged and backported to master.

**Comment by Soullivaneuh** [comment]
> Ok, then wait for #3694 to be merged and backported to master.

Which one? You linked the issue itself.

**Comment by lilocon** [comment]
thanks

**Comment by greg0ire** [comment]
@Soullivaneuh : sorry, fixed

**Comment by greg0ire** [comment]
@lilocon : you can update now

**Comment by lilocon** [comment]
OK， thank you
