### ISSUE TITLE
A form can only be submitted once. Problem with editing in admin.

### ISSUE THREAD

**Issue by bartoszmalec** [sonata-project/SonataAdminBundle#3699]
Hi,

I have problem with Sonata Admin. I can't edit entities on admin panel.

I get error: "A form can only be submitted once".

Create, delete works fine.

![admin_error](https://cloud.githubusercontent.com/assets/13161733/14225598/dea3febc-f8c8-11e5-902d-6330eceb751a.png)

**Comment by tim96** [comment]
Hi, I am not sure, but the problem maybe here:
https://github.com/sonata-project/SonataAdminBundle/commit/66cb40000d66c53aa9f2f4e8de80338e0ada67ef
You can try to update to the latest version or revert to previous commit.

**Comment by bartoszmalec** [comment]
I have just updated from 2.3.9 to 2.3.10 and now works fine. Thank you @Soullivaneuh

**Comment by tim96** [comment]
@bartoszmalec If it solves your problem, can you close issue?
