### ISSUE TITLE
sonata_type_collection with subclasses - on create problem when subclass entry is not valid

### ISSUE THREAD

**Issue by kozltomasz** [sonata-project/SonataAdminBundle#3702]
Hi
I have Product entity with is related to ProductPrice (OneToMany).

``` php
    class Product
    {

    /**
     * @ORM\OneToMany(targetEntity="ProductPrice", mappedBy="product", cascade={"all"})
     */
    protected $prices;

    }
```

The prices field in ProductAdmin is defined like that:

``` php
$formMapper
            ->add('prices', 'sonata_type_collection', [
                'required'     => false,
                'by_reference' => false,
                'type_options' => [
                    'delete' => true
                ],
                'btn_add' => 'Add new pricing scheme'
            ], [
                'edit'   => 'inline',
                'inline' => 'table'
            ])`
```

The problem is when adding new Product, and ProductPrice immediately and the Product price is invalid or some of values missing. 
![2016-04-04_1618](https://cloud.githubusercontent.com/assets/14977487/14251142/de6249f8-fa81-11e5-8c8a-2e923f198eda.png)

Then of course new product is not added, the error message is given, but the form is reloaded too. The new form is update form.
![2016-04-04_1619](https://cloud.githubusercontent.com/assets/14977487/14251157/fb77cad6-fa81-11e5-92a7-13c8a35b1791.png)

After passing correct value to ProductPrice and clicking update we have got 
"unable to find the object with id : 22
404 Not Found - NotFoundHttpException".

Since the Product wasn't added to the database correctly, why update form appeared?
Shouldn't create form be still there?

**Comment by Kreyo** [comment]
I think a possible solution for this case would be this one - [](https://sonata-project.org/bundles/admin/master/doc/cookbook/recipe_row_templates.html) . Instead of handling object field errors in backend, you can add the frontend validation to the Create\Edit form (e.g. "required" attribute).
Would be nice to add some default required fields to sonata_type_collection row based on the model, though.

**Comment by jordisala1991** [comment]
Either related to #5089 or #3728

In any case. you should define your assertions in the entities. Closing for now. If your issue is still happening, and it is not related to any of those, please ping me to reopen.
