### ISSUE TITLE
Passing admin object to sonata_type_model_autocomplete form type

### ISSUE THREAD

**Issue by a1ku** [sonata-project/SonataAdminBundle#3727]
Hi,

SonataAdmin version: `dev-master 44f8162 Symfony SonataAdminBundle` (`"sonata-project/admin-bundle": "2.4.*@dev"`)

In a Admin class I'm trying to define form (in `configureFormFields` method) that has a field being a collection of some simple Symfony (extending `Symfony\Component\Form\AbstractType`) types.

``` php
$form->add('nmRelations', 'sonata_type_native_collection', [
    'type' => new NMRelationType($modelManager, $admin),
    'allow_add' => true,
    'allow_delete' => true,
]);
```

In NMRelationType (that inherits from `Symfony\Component\Form\AbstractType`) there is:

``` php
public function buildForm(FormBuilderInterface $builder, array $options)
{
    $builder->add('m', 'sonata_type_model_autocomplete', [
        'model_manager' => $this->modelManager,
        'sonata_admin' => $this->admin,
        'class' => M::class,
        'property' => 'name',
        'multiple' => false,
    ]);
}
```

With that configuration I keep getting this error:

```
Impossible to access an attribute ("uniqid") on a boolean variable ("") in SonataAdminBundle:Form/Type:sonata_type_model_autocomplete.html.twig at line 63
```

which means that 

```
62: {% if sonata_admin.admin is not null %}
63:    'uniqid': '{{ sonata_admin.admin.uniqid }}',
64:    'admin_code': '{{ sonata_admin.admin.code }}',
65: {% elseif admin_code %}
66:     'admin_code':  '{{ admin_code }}',
67: {% endif %}
```

(`sonata_admin.admin` equals `false`, so yeah, that's not null..)
admin is not passed to the types' Twig template.
Am I using it wrong? I read https://sonata-project.org/bundles/admin/master/doc/reference/form_types.html And haven't seen statement that SonataAdmin form types are only to be used within FormMapper builder.

**Comment by ju1ius** [comment]
@a1ku Hi, can you provide a minimal runnable example (the two entities & the form type) as a gist ?

**Comment by KevinM2k** [comment]
@ju1ius @a1ku are we any further with this, we are getting a similar issue when trying to use autocomplete in blocks (so no related entity) - same error message for us too.

**Comment by mikemix** [comment]
I'm getting same error when trying to use the ModelAutocompleteType inside embedded form, eg:

```php
// an Admin
    ->add('related', RelatedFormType::class, ['model_manager' => $this->modelManager])

// the RelatedFormType
    ->add('entity', ModelAutocompleteType::class, [
        'class' => MyClass::class,
        'model_manager' => $options['model_manager'],
        // …
    ])
```
