### ISSUE TITLE
Validation error on creation of entity with a ID not auto generated cause system to think it's a update after

### ISSUE THREAD

**Issue by mpoiriert** [sonata-project/SonataAdminBundle#3728]
| Question | Answer |
| --- | --- |
| Bundle version | dev-master 139d110 Symfony SonataAdminBundle |
| Symfony version | v2.8.3             The Symfony PHP framework |
| php version | 5.6.20 |

I have a entity that has a Id that is not auto generated.
When submitting a creation form if the validation failed I go back to the form input.
The only problem is that sonata think's I am editing the object since the id value is not null.
If resubmitting the form once the violation have been fix it will failed because sonata is not able to find the object.
# Error message

```
unable to find the object with id : test2
```
# Steps to reproduce

Create a entity that have a ID that is not auto generated (example a string).
Create the admin for it.
Filled the ID input.
Submit.
Make the validation failed for any reason.
Fix the violation on the next page.
Resubmit
# Expected results

Should create the entity
# Actual results

Entity is consider a existing instance so a update flow is choose instead of a creation flow.

The reason behind this is because the check done everywhere is admin.id(object) instead of being something like admin.isNew(object)

I think it's simple to explain but there is probably a lot of place to change this.

**Comment by ju1ius** [comment]
>I think it's simple to explain but there is probably a lot of place to change this.

Yeah, I once tried to use entities with application-generated identifiers and it failed somehow in almost every sonata bundle...

I think this would be something great for 3.0: replace all the
```php
if ($entity->getId()) // and variations thereof
```
By 
```php
if ($entityManager->getUnitOfWork()->contains($entity))
```

**Comment by mpoiriert** [comment]
To be more accurate we should use

```
if ($entityManager->getUnitWork()->getEntityState($entity, UnitOfWork::STATE_NEW))
```

**Comment by greg0ire** [comment]
There are several possible model managers so I guess it would be even more abstract

**Comment by ju1ius** [comment]
I think all doctrine implementations use the unit of work pattern, but yeah the implementation should be the responsability of the various persistence bundles.
