### ISSUE TITLE
Visual regression in show action view

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/SonataAdminBundle#3729]
| Question       | Answer
|----------------|-------------------------------------------------------------
| Bundle version | dev-master
| Symfony version| 2.8.4
| php version    | 5.6.19

# Error message
No error message, this is a HTML/CSS visual bug.

# Steps to reproduce
Build a show view without tabs, but with groups with colum classes, e.g:
```php
    /**
     * @param ShowMapper $showMapper
     */
    protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->with('Person', ['class' => 'col-md-6'])
                ->add('name')
                ->add('age')
                ->add('gender')
            ->end()
            ->with('Contact', ['class' => 'col-md-6'])
                ->add('email', 'email')
                ->add('url', 'url')
                ->add('address', 'text')
            ->end()
            // Note that I do not add a class to this group
            ->with('Social')
                ->add('website', 'url')
                ->add('facebook', 'url')
                ->add('twitter')
            ->end()
        ;
    }
```

# Expected results
I should see 3 boxes.
The first two should be on the same row, 50% width each.
The last one on his own row, 100% width.
# Actual results
I see a blank space in place of the first row. The second row is visible.

# Easy guess
The offending code is in the new [base_show_macro.html.twig](https://github.com/sonata-project/SonataAdminBundle/pull/3657/files#diff-e2db96e003c0ed9f0b32866440121600R15), introduced by PR #3657 in [this commit](https://github.com/sonata-project/SonataAdminBundle/commit/fd1a1596f86bfb4afdafe9767efaa4c787bba6a5).
It doesn't add the default `col-md-12` class to the 3rd group, causing the other two to disappear.

**Comment by ju1ius** [comment]
Also note that this PR removed the `div.sonata-ba-view` wrapper, which is a BC break AFAICT. :confused:

**Comment by OskarStark** [comment]
do you have a screenshot @ju1ius ?

**Comment by ju1ius** [comment]
@OskarStark Here we go!

## The expected result:
![2016-04-20 1461140995_1135x406_scrot-fs8](https://cloud.githubusercontent.com/assets/218404/14668167/1af63cd6-06e3-11e6-8545-2ff0f1a78327.png)

## Showing the dreadful bug
![2016-04-20 1461140895_1041x405_scrot-fs8](https://cloud.githubusercontent.com/assets/218404/14668187/3b82ed96-06e3-11e6-9f3a-a0c130fd7e5c.png)
