### ISSUE TITLE
versioning problem

### ISSUE THREAD

**Issue by josephzhao** [sonata-project/SonataAdminBundle#3735]
I hope for the sonata project can use same version number for all bundle compatible,  some times it difficult to find out all bundles version which compatible with each other, I just download sandbox , and when I use composer.phar to update all bundles, there is still errors.

if we can use 2.3.* or 2.4.* for all Sonata bundles that should be much better for us.

Thanks

**Comment by ju1ius** [comment]
Looks like [this is not going to happen anytime soon](https://github.com/sonata-project/SonataAdminBundle/issues/3053#issuecomment-202874094).

**Comment by Soullivaneuh** [comment]
> I hope for the sonata project can use same version number for all bundle compatible, some times it difficult to find out all bundles version which compatible with each other

We decide starting #3053 to strictly follow [semver](http://semver.org/) and semver is not the way you describe.

I understand your problem that is real for actual versions of sonata project but just tag same version for each project is not the solution.

The solution is to push more releases and be very careful about BC.

Please refer to #3053 and #3731 and also [sonata-project/dev-kit](https://github.com/sonata-project/dev-kit) to see what is going on for the future.

Regards.
