### ISSUE TITLE
Filtering by sub entity properties causes unexpected results in global search

### ISSUE THREAD

**Issue by gprioux** [sonata-project/SonataAdminBundle#3739]
The configureDatagridFilters function of the MembershipAdmin class is configured using fields from a linked entity User (1/n : a Membership belongs to one User, a User may have several memberships) :

```php
$datagridMapper
        ->add('user.username')
        ->add('user.lastname')
        ->add('user.email')
        ->add('category')
        ->add('amount');
```
        
This works fine in the MembershipAdmin filters, and list can be filtered using these fields.

Problem occurs when using the global search feature, which is based on the datagridFilters : when searching for any word, all related entities are queried using this word in the 'where' clause, except Memberhip which is queried without any 'where' clause. Consequently, the 'Search Results' page shows all records of the related Membership table as results.

When commenting out the 3 'user.*' fields, the global search behaviour is as expected and returns only accurate results base on a correct 'where' clause.

traces: 

> [2016-04-22 10:09:23] request.INFO: Matched route "sonata_admin_search". {"route_parameters":{"_controller":"Sonata\\AdminBundle\\Controller\\CoreController::searchAction","_route":"sonata_admin_search"},"request_uri":"https://escmp/admin/search?q=mytest"} []
...
[2016-04-22 10:09:26] doctrine.DEBUG: SELECT count(DISTINCT m0_.id) AS sclr_0 FROM Membership m0_ LEFT JOIN User u1_ ON m0_.Member_id = u1_.id LEFT JOIN MembershipCategory m2_ ON m0_.category_id = m2_.id [] []

Bundle version : 2.3.10
| Symfony version : 2.7.11
| php version : 5.6.2

**Comment by greg0ire** [comment]
I think this could be solved by tweaking [this line](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Search/SearchHandler.php#L56). @gprioux , can you try ?

**Comment by gprioux** [comment]
Hi Gregoire
thanks for your answer! 
What do you suggest to tweak this line ? I tried to comment it out and as a result, the search is done using a query on the simple fields (amount and category) but not on the complexe ones (user.*) 

I tried to go a little bit deeper in the executed code but I couldn't figure out why the query built in the datagrid Pager is empty in the normal case for this admin class

**Comment by greg0ire** [comment]
I would add a condition so that fields are added to the global search only if they are on the simple fields. But maybe you should just use this option in your mapper ? `        ->add('category', null, ['global_search' => true])` ?

**Comment by gprioux** [comment]
ok, that could be a workaround to partially fix the issue : I need the search to work in the 'complexe' fields as well, as soon as it contains user details on which a search is more interesting than in simple fields...

**Comment by greg0ire** [comment]
>  it contains user details 

How would you detect that ?

**Comment by gprioux** [comment]
ie. if I search for 'prioux' in the global search tool, I can find 4 users in the results and I should find 15 results in Membership table. I'm expecting the search query being something like : 

SELECT * FROM Membership m LEFT JOIN User u ON u.id = m.Member_id WHERE (u.lastname LIKE '%prioux%' OR u.firstname LIKE '%prioux%' OR u.email LIKE '%prioux%')

which gives a correct result

**Comment by greg0ire** [comment]
I mean how do you detect that "prioux" is about a user, and thus there is a need for complex search ?

**Comment by gprioux** [comment]
Ok, I gave you a partial view of the expected query, which should be:
`SELECT * FROM Membership m LEFT JOIN User u ON u.id = m.Member_id WHERE (u.lastname LIKE '%prioux%' OR u.firstname LIKE '%prioux%' OR u.email LIKE '%prioux%' OR m.category LIKE '%prioux%' OR m.amount LIKE '%prioux%')`
even if I don't think that searching into 'amount' field is relevant as it's a number type, not a string
In my opinion, the JOIN query should be triggered by the 'user.*' field declaration

**Comment by greg0ire** [comment]
I re-read your question and think I got it wrong from the start… so the problem is, if I get it right, as soon as you add an indirect field to the filters, there is no more filtering? So the bug would be that suddenly, `$filter->getOption('global_search', false)` always returns false, am I right? Can you check that?

**Comment by gprioux** [comment]
you got it right for the problem, as soon as I add an indirect field to the filter, the global search fails as it doesn't apply any filter in the query.
For the root cause, I'm afraid you've got it wrong : the `$filter->getOption('global_search', false)` returns true for the indirect fields, I've checked this in a debug session

**Comment by greg0ire** [comment]
There is a contradiction in what you are saying

> all related entities are queried using this word in the 'where' clause, except Memberhip which is queried without any 'where' clause.

so other tables have a WHERE clause or not ?

> SELECT count(DISTINCT m0.id) AS sclr_0 FROM Membership m0_ LEFT JOIN User u1_ ON m0_.Member_id = u1_.id LEFT JOIN MembershipCategory m2_ ON m0_.category_id = m2_.id [] []

It looks like there is no WHERE clause at all here

>  the global search fails as it doesn't apply any filter in the query.

And you seem to confirm that here…

So what is it?

**Comment by gprioux** [comment]
When I'm talking about other tables (or other entities), I mean the other entities within the system for which the global search is working fine because their datagrid filters are defined only with simple fields : in these cases, there're correct WHERE clauses in Doctrine traces.

For the Membership entity case, the problem I mentionned is that there's no WHERE clause at all when using indirect fields within filter. The WHERE clause (only on simple fields) has only worked once when you've suggested to me to force it on simple fields with the global_search option set to true

**Comment by greg0ire** [comment]
> When I'm talking about other tables (or other entities), I mean the other entities within the system for which the global search is working fine because their datagrid filters are defined only with simple fields : in these cases, there're correct WHERE clauses in Doctrine traces.

Ok so you mean when you query these entities on their dedicated page and not through `Membership`? I think I get it this time :)

**Comment by greg0ire** [comment]
Oh by the way, this version of the bundle is no longer supported, do you reproduce the problem on version 3 ?

**Comment by gprioux** [comment]
No longer supported although version 3 is only few days old ?
I've moved to v3, a little bit painful but somehow, this problem is fixed within this version... Here is the query I now have to get the numbers of results:
`SELECT DISTINCT m0_.id AS id_0 FROM Membership m0_ LEFT JOIN User u1_ ON m0_.Member_id = u1_.id LEFT JOIN MembershipCategory m2_ ON m0_.category_id = m2_.id WHERE u1_.username LIKE ? OR u1_.lastname LIKE ? OR u1_.email LIKE ? ORDER BY m0_.id ASC LIMIT 10 OFFSET 0 ["%prioux%","%prioux%","%prioux%"]`
which is correct !
thanks for your help
-G

**Comment by greg0ire** [comment]
> No longer supported although version 3 is only few days old ?

We know that's bad, and planning to change that.

> I've moved to v3, a little bit painful

And as a result of the new way, we promise future upgrade won't be painful at all ;) and more frequent
