### ISSUE TITLE
Clarify versioning and where the BCs are going to be

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#3740]
I saw today (in #3731) that the plan is to change 2.4 to 3.0 and make it the next major release.

My key questions are:

* What is the current stable version? (I think it's 2.3, but maybe I'm just behind the times!)
* When will the 'new' stable version be released?
* Going forward, how is versioning going to work?
* Where are the BC breaks? (To clarify the comment by @Soullivaneuh on #3731 saying "Even if it's a new major, no BC breaking Pull Request will be merge until 3.0.0 release")

In particular...

* if I currently use ~2.3, are there breaks between this and ~3.0? (I'm guessing there are many!)
* if I currently use 2.4.*@dev, are there breaks between this and ~3.0?
* is there a clear list of the breaks to look out for between ~2.3 and ~3.0? (to help bring those older projects up to speed)
* once 3.0.0 is released, will this be a stable branch? If so, will it be stable without BC breaks until 3.1.0 or 4.0? (or something else)
* is there a roadmap with any suggestion of how long 3.0 is going to be the stable branch?

Very excited to see this tidying up happen, albeit wary of how much work is going to be needed to drag 2.3 projects into the new and shiny world of 3.0!

**Comment by greg0ire** [comment]
> What is the current stable version? (I think it's 2.3, but maybe I'm just behind the times!)

Good guess

> When will the 'new' stable version be released?

Early may ?

> Going forward, how is versioning going to work?

see #3053 

> Where are the BC breaks? (To clarify the comment by @Soullivaneuh on #3731 saying "Even if it's a new major, no BC breaking Pull Request will be merge until 3.0.0 release")

> if I currently use ~2.3, are there breaks between this and ~3.0? (I'm guessing there are many!)

Yes

> if I currently use 2.4.*@dev, are there breaks between this and ~3.0?

Not at all, it is the same thing, it was renamed

> is there a clear list of the breaks to look out for between ~2.3 and ~3.0? (to help bring those older projects up to speed)

Sadly no as far as I know

> once 3.0.0 is released, will this be a stable branch? If so, will it be stable without BC breaks until 3.1.0 or 4.0? (or something else)

We will follow semver, so next BC break will be 4.0, and 4.0 will be the alias of master

 > is there a roadmap with any suggestion of how long 3.0 is going to be the stable branch?

No

> Very excited to see this tidying up happen, albeit wary of how much work is going to be needed to drag 2.3 projects into the new and shiny world of 3.0!

Me too! But I think it will be the last painful migration ;)

**Comment by caponica** [comment]
Great - thanks for the quick replies and link to #3053 (sorry, I hadn't found that before)

**Comment by Soullivaneuh** [comment]
Some additions to @greg0ire:

> if I currently use 2.4.*@dev, are there breaks between this and ~3.0?

It is indeed the same things. But we are some introduced BC break by the past. Release a major instead is a security.

> is there a clear list of the breaks to look out for between ~2.3 and ~3.0? (to help bring those older projects up to speed)

Indeed, sadly. We have to work on a better system for that (see https://github.com/sonata-project/dev-kit/pull/1 if you want to participate).

> is there a roadmap with any suggestion of how long 3.0 is going to be the stable branch?

Let quickly explain why the "No": We are not a big company like SensioLabs or Mozilla fundation. We do not have full team working only on sonata-project. All people here are contributing from them free times (if they have).

So no, it's impossible to promise a precise release date or a roadmap for this. 

> Very excited to see this tidying up happen, albeit wary of how much work is going to be needed to drag 2.3 projects into the new and shiny world of 3.0!

\o/

**Comment by ju1ius** [comment]
@caponica Given the bundle will use semver, even without a pre-defined roadmap, I guess we can expect one major per year, give or take...

**Comment by greg0ire** [comment]
>  one major per year, give or take...

I think it will be a bit more than that. What I really would like is that we release a new major **before** being too afraid to do so.

**Comment by Soullivaneuh** [comment]
> I guess we can expect one major per year, give or take...

This is absolutely wrong. If it was true, then we will be able to create a roadmap. :-)

> I think it will be a bit more than that.

Not really, it's depends. A major could be out when it necessary. E.G. when we have a quite huge BC break modifications on master.

BTW, if we follow the new Symfony technique, that mean a major would be the same as the last minor but without deprecated feature, it will such painless.

And it would be easier to have a sonata-dependencies that can be compatible with two or more majors of other sonata projects IMO.

**Comment by greg0ire** [comment]
> when it feels necessary

+1 on this

To me it would feel necessary if the stable branch and the master branch start differing too much, or simply if we haven't released for a long time (after all, PR authors would like to be able to feel safe on a stable branch, while using the code of their PR).

**Comment by ju1ius** [comment]
> This is absolutely wrong.

It's just a guess, so wait and see :stuck_out_tongue:
