### ISSUE TITLE
[BUG] Double translation: success message flashbag

### ISSUE THREAD

**Issue by bordeux** [sonata-project/SonataAdminBundle#3745]
File: Controler/CRUDController.php

This message is double translated. First time is translated here:
![first](https://cloud.githubusercontent.com/assets/784536/14905500/6b98d264-0db1-11e6-9e1c-422651254c8e.png)

And second time is translated on FlashBag Manager, here:
![first](https://cloud.githubusercontent.com/assets/784536/14905520/a3076e4a-0db1-11e6-9015-f26aa2ec7858.png)

This is annoying, because this create new entry on my DB with translation tokens to translate... :) 

I think, best way is remove translation on flashBag manager.

**Comment by core23** [comment]
Screenshot wouldn't help much when explaining bugs in the code... Please refer the lines in your comment.

Could you create a new PR with a fix @bordeux ?

**Comment by bordeux** [comment]
With pull request: No problem, but PM need define correct way to fix this bug. 

**First way:**
I think the best way (programming standards) is remove translation in flashBagManager service. Everything should be translated before put into flashBag. So after that flashBagManager can be removed.

+
- we can use parameters in translation

−
- hard way
- i need to modify SonataAdminBundle, SonataCore and others bundles

**Second way:**
Remove from [CRUDController.php](https://github.com/sonata-project/SonataAdminBundle/blob/master/Controller/CRUDController.php#L407) in SonataAdminBundle  message with arguments. 

+
- easy way, fast

−
- we cannot use custom translation parameters in flashbag message


**Third way**
- add extra parameter on flasbag()->add($message, $domain, $parameters = [])

+
- easy way, fast

−
- i cant implemenets [FlashBagInterface](https://github.com/symfony/http-foundation/blob/master/Session/Flash/FlashBagInterface.php) from symfony

==============
Lines:
[Screenshot1](https://github.com/sonata-project/SonataAdminBundle/blob/master/Controller/CRUDController.php#L407)
[Screenshot2](https://github.com/sonata-project/SonataCoreBundle/blob/master/FlashMessage/FlashManager.php#L159)

**Comment by greg0ire** [comment]
I think we should go with solution number one.

**Comment by Hanmac** [comment]
i think the problem still exist and creating Translation not found because it is already translated

**Comment by greg0ire** [comment]
@Hanmac why would it no longer exist?

**Comment by Hanmac** [comment]
@greg0ire i mean the problem isn't fixed yet (still exist)
i currently fall into it and wanted to make a new ticket before i found this.

and because the ticket is over a year old i wanted to remind that this problem still exist and isn't fixed yet
(it might not be that critical, but still counts)

**Comment by jlamur** [comment]
@Hanmac That's right, the problem still exists. Thanks for your feedback.

Could you try to provide a PR to help us fix this bug?

**Comment by Hanmac** [comment]
@jlamur the best solution would be the first way, that the Flashbag(Manager) doesn't translate itself anymore, but that might be to complicated for me to fix currently. (and probably to big to fix in one PR because it does affect the other bundles too)

**Comment by jlamur** [comment]
It can be done in the next major with the 1st way that @bordeux proposed, without having to change a lot of thing in other bundles, because most of the flashbag messages are already translated before.

I don't understand the 2nd solution. And the 3rd one is irrelevant because the flashbag interface is simply not meant to translate messages. That's the way Symfony designed it.

**Comment by lukepass** [comment]
It happened to me when saving items in foreign languages. It seems that the flashbang is translataed again after parameters:

![image](https://user-images.githubusercontent.com/6429961/40620626-cc5b7aae-6299-11e8-9518-43b9fca51e21.png)

**Comment by Hanmac** [comment]
Was Fixed at https://github.com/sonata-project/SonataCoreBundle/pull/685 by @core23 

Should this be closed?
