### ISSUE TITLE
Requirements could not be resolved

### ISSUE THREAD

**Issue by philippe-surprizemi** [sonata-project/SonataAdminBundle#3760]
Hi guys,

We are using this awesome bundle on our e-commerce project, but since this morning we have a composer dependency issue:

<pre>
> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sonata-project/admin-bundle dev-master -> satisfiable by sonata-project/admin-bundle[dev-master].
    - sonata-project/admin-bundle dev-master requires sonata-project/block-bundle 3.x-dev@dev -> no matching package found.
  Problem 2
    - sonata-project/admin-bundle 3.x-dev requires sonata-project/block-bundle 3.x-dev@dev -> no matching package found.
    - sonata-project/doctrine-orm-admin-bundle dev-master requires sonata-project/admin-bundle 3.x-dev@dev -> satisfiable by sonata-project/admin-bundle[3.x-dev].
    - Installation request for sonata-project/doctrine-orm-admin-bundle dev-master -> satisfiable by sonata-project/doctrine-orm-admin-bundle[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
</pre>

Here is our complete composer.json:

<pre>
{
    "name": "spz/phoenix",
    "license": "proprietary",
    "type": "symfony-bundle",
    "authors" : [{
        "name" : "SPZ Core Team",
        "email" : "XXXX"
    }],
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "require": {
        "symfony/symfony": "3.0.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "friendsofsymfony/user-bundle": "dev-master",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "dev-master"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "platform": {
            "php": "5.5.9"
        }
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}
</pre>

I assume that there have been some changes during the last week ?

it is very annoying for our dev processes, someone had the same problem ?

PS: adding "minimum-stability": "dev" doesn't work.

Thanks 

Phil

**Comment by greg0ire** [comment]
See https://github.com/sonata-project/SonataAdminBundle/issues/3731

**Comment by philippe-surprizemi** [comment]
Hi @greg0ire 

Thanks for the reply,

I edit my composer.json like that (but still not work) :
<pre>
    "require": {
....
        "sonata-project/core-bundle": "3.x-dev",
        "sonata-project/block-bundle": "3.x-dev",
        "sonata-project/admin-bundle": "3.x-dev",
        "sonata-project/doctrine-orm-admin-bundle": "3.x-dev"
    },
</pre>

I'm not sure that it is the good syntax (not a composer expert)

the error :

<pre>
> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sonata-project/core-bundle 3.x-dev -> satisfiable by sonata-project/core-bundle[3.x-dev].
    - sonata-project/doctrine-orm-admin-bundle 3.x-dev requires sonata-project/core-bundle ^2.3.1 -> satisfiable by sonata-project/core-bundle[2.x-dev].
    - Can only install one of: sonata-project/core-bundle[3.x-dev, 2.x-dev].
    - Installation request for sonata-project/doctrine-orm-admin-bundle 3.x-dev -> satisfiable by sonata-project/doctrine-orm-admin-bundle[3.x-dev].
</pre>

Do you see what's wrong ?

Thanks

Phil.

**Comment by greg0ire** [comment]
I think you are supposed to use inline alias to let other packages think that 3 is in fact 2.4 .

**Comment by philippe-surprizemi** [comment]
Solved:

FYI:

<pre>
    "require": {
        . . .
        "sonata-project/core-bundle" : "3.x-dev as 2.4",
        "sonata-project/block-bundle" : "3.x-dev as 2.4",
        "sonata-project/admin-bundle" : "3.x-dev as 2.4",
        "sonata-project/doctrine-orm-admin-bundle" : "3.x-dev as 2.4"
    },
</pre>

Thanks @greg0ire
