### ISSUE TITLE
GetElementAccessPath in AdminHelper gets confused when using nested properties with underlines

### ISSUE THREAD

**Issue by jordisala1991** [sonata-project/SonataAdminBundle#3763]
| Question       | Answer
|----------------|-------------------------------------------------------------
| Bundle version | dev-master
| Symfony version| 2.8.5
| php version    | 5.5.34

This is my first issue on Sonata so if I am doing something wrong or you need more info I can provide it. I can also provide a PR that fixes this.

# Error message

Could not get element id from s5729b4b1cced5_main_category_current_tags Failing part: tags

# Stack trace

    [1] Exception: Could not get element id from s5729bd3e0bfe6_main_category_current_tags Failing part: tags
    at n/a in /vagrant/app/cache/dev/classes.php line 4358
    at Sonata\AdminBundle\Admin\AdminHelper->getElementAccessPath('s5729bd3e0bfe6_main_category_current_tags', object(Post)) in /vagrant/app/cache/dev/classes.php line 4264
    at Sonata\AdminBundle\Admin\AdminHelper->appendFormFieldElement(object(PostAdmin), object(Post), 's5729bd3e0bfe6_main_category_current_tags') in /vagrant/vendor/sonata-project/admin-bundle/Controller/HelperController.php line 105
    at Sonata\AdminBundle\Controller\HelperController->appendFormFieldElementAction(object(Request)) in  line 
    at call_user_func_array(array(object(HelperController), 'appendFormFieldElementAction'), array(object(Request))) in /vagrant/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 139
    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1') in /vagrant/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php line 62
    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true) in /vagrant/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php line 69
    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Request), '1', true) in /vagrant/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php line 185
    at Symfony\Component\HttpKernel\Kernel->handle(object(Request)) in /vagrant/web/app_dev.php line 30

# Steps to reproduce

Have 3 models: Post, Category, Tag. Post with a one-to-one with Category and Category with a one-to-many with Tag.

In the sonata configuration have 'sonata_type_model' on Category in PostAdmin and 'sonata_type_collection' on Tag in the CategoryAdmin.

Then try to add Tags from the PostAdmin

# Expected results

You should be able to create tags on the category, both from the CategoryAdmin and PostAdmin.

# Actual results

If you are using properties like: main_category and current_tags you can't.

**Comment by Soullivaneuh** [comment]
> Have 3 models: Post, Category, Tag. Post with a one-to-one with Category and Category with a one-to-many with Tag.

@jordisala1991 Could you please copy-paste you entity classes? Especially for the one-to-one relation.

**Comment by jordisala1991** [comment]
Ok, give me time to prepare a gist

**Comment by jordisala1991** [comment]
@Soullivaneuh The names are not the same of the initial issue. Tell me if you need more code. https://gist.github.com/jordisala1991/e372fbc909f9bf6ecc75b336fa381025

**Comment by Soullivaneuh** [comment]
@jordisala1991 I'm sorry but I can't reproduce your error. Could you please paste the code on this issue of:

* Your entity classes 
* Your admin classes
* Your admin service configurations

Thanks.

**Comment by jordisala1991** [comment]
I updated the gist with the admin classes and the admin.yml.

https://gist.github.com/jordisala1991/e372fbc909f9bf6ecc75b336fa381025

@Soullivaneuh with my example you can reproduce the bug by going to Tournament add, and click to Add new (TournamentEventDay). That button should execute an ajax to add an inline form of TournamentEventDay, but instead it will fail.

**Comment by jordisala1991** [comment]
Can we reopen this in order to confirm the bug?

I provide a full working example repository:

https://github.com/jordisala1991/ArchetypeSonata

Steps:

- Go to the branch `issue/underscore-properties`
- Do a `vagrant up`
- Acces to 192.168.33.99
- Login with user: admin, password: admin
- Go to Poker > Tournament > Add new
- Try to use the button Add new on the form
- At this point you get an ajax error (at this moment, packagist is not updated with the latest changes on the github repository)
- Change composer.json > adminBundle to: `dev-master#0b5a38ddd8cf84aeaf075ba30d0a1763e60bbd3e as 2.4` 
- Do a composer update
- Try again
- At this point it works

@Soullivaneuh @OskarStark

**Comment by Soullivaneuh** [comment]
@jordisala1991 Thanks a lot for your time.

I got this error:

```
==> default: TASK [app : Create parameters.yml] *********************************************
==> default: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception OSError: (2, 'No such file or directory', '/vagrant/app/config/.ansible_tmpuw7GEmparameters.yml') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0x7fc2acc9d660>> ignored
==> default: fatal: [192.168.33.99]: FAILED! => {"changed": true, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1463258133.24-244554454910690/copy\", line 2331, in <module>\n    main()\n  File \"/root/.ansible/tmp/ansible-tmp-1463258133.24-244554454910690/copy\", line 328, in main\n    module.atomic_move(src, dest)\n  File \"/root/.ansible/tmp/ansible-tmp-1463258133.24-244554454910690/copy\", line 2087, in atomic_move\n    os.chown(dest, os.getuid(), os.getgid())\nOSError: [Errno 1] Operation not permitted: '/vagrant/app/config/parameters.yml'\nException OSError: (2, 'No such file or directory', '/vagrant/app/config/.ansible_tmpuw7GEmparameters.yml') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0x7fc2acc9d660>> ignored\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
==> default: 
==> default: NO MORE HOSTS LEFT *************************************************************
==> default: 
==> default: RUNNING HANDLER [apache : restart apache] **************************************
==> default: 
==> default: RUNNING HANDLER [php : restart php5-fpm] ***************************************
==> default: 	to retry, use: --limit @/vagrant/ansible/playbook.retry
==> default: 
==> default: PLAY RECAP *********************************************************************
==> default: 192.168.33.99              : ok=48   changed=34   unreachable=0    failed=1   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
sullivan@sweethome:~/tmp/ArchetypeSonata(master)$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: VirtualBox VM is already running.
```

And when I try to access [192.168.33.99](http://192.168.33.99), I got a forbidden error.

I'm not a Vagrant expert, maybe could you give me some clues to solve this?

> at this moment, packagist is not updated with the latest changes on the github repository

Yes, we have an issue with Packagist about that: https://github.com/composer/packagist/issues/674

**Comment by jordisala1991** [comment]
I changed the ansible code.. this is a ansible issue when using template with sudo permissions:

https://github.com/ansible/ansible/issues/7553

Can you pull the changes and try: vagrant provision?

**Comment by Soullivaneuh** [comment]
Now I got this:

```bash
==> default: TASK [composer : Install Composer globals] *************************************
==> default: failed: [192.168.33.99] (item=hirak/prestissimo) => {"failed": true, "item": "hirak/prestissimo", "msg": "[RuntimeException] Invalid working directory specified, /home/vagrant/.config/composer does not exist."}
==> default: 
==> default: NO MORE HOSTS LEFT *************************************************************
==> default: 	to retry, use: --limit @/vagrant/ansible/playbook.retry
==> default: 
==> default: PLAY RECAP *********************************************************************
==> default: 192.168.33.99              : ok=48   changed=5    unreachable=0    failed=1   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by jordisala1991** [comment]
Heh, that's me trying to use new things without proper testing...

I will push a fix in a sec :)

**Comment by jordisala1991** [comment]
Fixed @Soullivaneuh . Pull and provision again

**Comment by Soullivaneuh** [comment]
Well, sorry @jordisala1991. :-)

```bash
==> default: TASK [app : Create .htaccess] **************************************************
==> default: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: Exception OSError: (2, 'No such file or directory', '/vagrant/web/.ansible_tmpof_GF7.htaccess') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0x7ff5aca86660>> ignored
==> default: fatal: [192.168.33.99]: FAILED! => {"changed": true, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1463261027.11-197534486723997/copy\", line 2331, in <module>\n    main()\n  File \"/root/.ansible/tmp/ansible-tmp-1463261027.11-197534486723997/copy\", line 328, in main\n    module.atomic_move(src, dest)\n  File \"/root/.ansible/tmp/ansible-tmp-1463261027.11-197534486723997/copy\", line 2087, in atomic_move\n    os.chown(dest, os.getuid(), os.getgid())\nOSError: [Errno 1] Operation not permitted: '/vagrant/web/.htaccess'\nException OSError: (2, 'No such file or directory', '/vagrant/web/.ansible_tmpof_GF7.htaccess') in <bound method _TemporaryFileWrapper.__del__ of <closed file '<fdopen>', mode 'w+b' at 0x7ff5aca86660>> ignored\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}
==> default: 
==> default: NO MORE HOSTS LEFT *************************************************************
==> default: 	to retry, use: --limit @/vagrant/ansible/playbook.retry
==> default: 
==> default: PLAY RECAP *********************************************************************
==> default: 192.168.33.99              : ok=50   changed=6    unreachable=0    failed=1   
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by jordisala1991** [comment]
Do you have an .htacces on the web directory? I'm not really sure why it's failing on a simple copy task, but while I'm looking at it we can try this the old way..

    vagrant ssh
    cd /vagrant
    cp ansible/roles/app/templates/.htaccess web/.htaccess
    composer install
    php app/console doctrine:migrations:migrate

That's what is missing on your provision

**Comment by Soullivaneuh** [comment]
Now I have:

```
RuntimeException in Imagine.php line 172:
Gd not installed
```

On the web interface.

I tried:

```
vagrant@default:/vagrant$ sudo apt-get install php5-gd
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php5-gd is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
vagrant@default:/vagrant$ logout
Connection to 127.0.0.1 closed.
```

So nothing else happened. Didn't search any longer, will see it again tomorrow evening or monday.

**Comment by jordisala1991** [comment]
Probably you need to restart apache on the vm

**Comment by Soullivaneuh** [comment]
Ok it works. :+1: 

But, maybe I'm too tired but I don't see any "Poker" or "Tournament":

![image](https://cloud.githubusercontent.com/assets/1698357/15271002/0551e2cc-1a34-11e6-843e-3e4b397c381c.png)

**Comment by jordisala1991** [comment]
Are you in the issue/underscore-properties branch?

When you change branch you need to run again:

php app/console doctrine:migrations:migrate

**Comment by Soullivaneuh** [comment]
> Are you in the issue/underscore-properties branch?

Well, definitely I'm tired. ;-)

I just tested your project, this bug is reproduced and indeed fixed.

Thanks again a lot for your time! :+1:
