### ISSUE TITLE
[Question] Show template - hide empty fields

### ISSUE THREAD

**Issue by muspelheim** [sonata-project/SonataAdminBundle#3765]
Hello, how i can hide empty fields on show template without rewrite fields template?

**Comment by cassianotartari** [comment]
One way is get the object in admin show action with: ``$this->getSubject()`` and test is not empty to add the field in ``ShowMapper``

**Comment by muspelheim** [comment]
@cassianotartari most easier extend template, but i thought Sonata have functional for this.
