### ISSUE TITLE
Remove $context from AdminInterface::createQuery

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataAdminBundle#3795]
This variable could not be modified anywhere as specified on https://github.com/sonata-project/SonataAdminBundle/issues/3246.

But @greg0ire detected an OCP violation on my PR. See https://github.com/sonata-project/SonataAdminBundle/pull/3247#issuecomment-172676861

So as he suggested, this parameter should be simply removed.

TODO: See if this could be done on a BC way.

**Comment by greg0ire** [comment]
> TODO: See if this could be done on a BC way.

`func_get_args()` knows if you are using a default argument or not.
