### ISSUE TITLE
How to use the user-bundle after 3.0

### ISSUE THREAD

**Issue by RomainSanchez** [sonata-project/SonataAdminBundle#3796]
The user bundle requires sonata admin 2.2.9 but the doctrineormadmin bundle requires sonata admin 3.0.How am i supposed to get around this?i already have to use aliases on admin and doctrine to make them appear as 2.4.I am completely lost in all the dependency problems 3.0 created.Why evolve to 3.0 for the core bundles before getting all the other bundles ready?(already read #3731 comments).

**Comment by Soullivaneuh** [comment]
Please open an issue on the concerned bundle (e.g. user-bundle).
