### ISSUE TITLE
composer sonata-project/doctrine-orm-admin-bundle does not support admin-bundle:dev-master 

### ISSUE THREAD

**Issue by Saint-Cyr** [sonata-project/SonataAdminBundle#3831]
I just wanted to update my vendor in order to fixe a problem I accounted from one of the bundles I'm using but it looks like sonata-project/doctrine-orm-admin-bundle does exist no more in stable version for admin-bundle:dev-master

Problem 1
    - sonata-project/doctrine-orm-admin-bundle dev-master requires sonata-project/admin-bundle ^3.0 -> satisfiable by sonata-project/admin-bundle[3.x-dev].
    - sonata-project/doctrine-orm-admin-bundle dev-master requires sonata-project/admin-bundle ^3.0 -> satisfiable by sonata-project/admin-bundle[3.x-dev].
    - Conclusion: don't install sonata-project/admin-bundle 3.x-dev
    - Installation request for sonata-project/doctrine-orm-admin-bundle dev-master -> satisfiable by sonata-project/doctrine-orm-admin-bundle[dev-master].

**Comment by Soullivaneuh** [comment]
Please fill github issue format as described when you tried to open the issue.

First, please give your `composer.json` file.

**Comment by Saint-Cyr** [comment]
> Please fill github issue format as described when you tried to open the issue.
Sorry !
this is my composer.json file:

"require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.0.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "friendsofsymfony/user-bundle": "2.0.x-dev",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "^2.1",
        "friendsofsymfony/rest-bundle": "^1.7",
        "ddeboer/data-import-bundle": "~0.1",
        "hautelook/alice-bundle": "1.2.2",
        "knplabs/knp-time-bundle": "dev-master"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0",
        "doctrine/doctrine-fixtures-bundle": "^2.3",
        "doctrine/data-fixtures": "^1.1"
    },

**Comment by Soullivaneuh** [comment]
Please update your comment and use code blocks for better readability.

Also the Packagist repos are update since https://github.com/composer/packagist/issues/674 is resolved.

Could you please try again?

**Comment by Soullivaneuh** [comment]
Replace those lines:

```json
"sonata-project/admin-bundle": "dev-master",
"sonata-project/doctrine-orm-admin-bundle": "dev-master",
```

By this:

```json
"sonata-project/admin-bundle": "^3.0",
"sonata-project/doctrine-orm-admin-bundle": "^3.0",
```

And your problem will be solved.

If you want dev version:

```json
"sonata-project/admin-bundle": "^3.0@dev",
"sonata-project/doctrine-orm-admin-bundle": "^3.0@dev",
```

**Comment by Saint-Cyr** [comment]
Thank you ! sorry for the delay it works

**Comment by senthilkumar3282** [comment]
> ```json
> "sonata-project/admin-bundle": "^3.0",
> "sonata-project/doctrine-orm-admin-bundle": "^3.0",
> ```

"sonata-project/admin-bundle": "^3.0",
"sonata-project/doctrine-orm-admin-bundle": "^3.0",
this one is working for me, thank you.
