### ISSUE TITLE
Decouple the admin and the breadcrumbs builder

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataAdminBundle#3833]
The plan : 
- [x] Move the breadcrumbs building code in a separate class
- [x] Create a breadcrumbs builder service
- [x] Deprecate admin proxy methods in favor of breadcrumbs builder method
- [ ] Determine what exact part of the admin the breadcrumbs builder needs, and see if we can inject them.

~~\- [ ] See if the breadcrumbs builder code can be made simpler by making it stateful (injecting the admin in the constructor)~~

**Comment by Soullivaneuh** [comment]
> by making it stateful

Maybe can you elaborate this part? Some ideas?

**Comment by greg0ire** [comment]
> Maybe can you elaborate this part? Some ideas?

As a first step, the admin object could be injected into the breadcrumbs builder, and there would be no need to give an admin object to each and every method.

**Comment by OskarStark** [comment]
@greg0ire can you create a task list instead in your initial post and mark the parts which are done?

**Comment by greg0ire** [comment]
@OskarStark done.
Injecting the admin in the constructor would create a circular reference, so not sure about this one…

**Comment by greg0ire** [comment]
At the moment, the admin is needed for : 

- the menu factory
- the route generator
- getting a classname to generate a translation string
- checking if a route exists
- checking if access is granted
- doing the translation

I think for instance, the translator could be injected instead, and `AbstractAdmin::trans()` could be bypassed. Also, I think the breadcrumbs simply cannot work well without a translation system, even if the application is not internationalized, because it uses translation strings with underscores…

**Comment by greg0ire** [comment]
Gave it some more though, and I think making the breadcrumbs builder stateful is not a good think, because then it cannot be used as a service and instead, we have to create one breadcrumbs builder per admin instead of using one breadcrumbs builder object. I changed the plan accordingly, and will try to make BC PR about this shortly.

**Comment by zhil** [comment]
@greg0ire do you have any ideas about some way  to customize breadcrumbs for some admin class?

convert something simple, like

Dashboard / Wares / WareTitle 

to more userfriendly, like

Dashboard / Category / Wares / SomeOtherCriteria / WareTitle
?

I used getBreadcrumbs function, but it doesn't work any more

I would like to create PR to implement this feature, would appreciate feedback on possible realisation

1) in default service 'sonata.admin.breadcrumbs_builder' check if admin class have method getBreadcrumbs and call it, if its callable. Super simple, could be BC compatible, a bit ugly though

2) add ability to override service name with custom service? A bit overcomplicated, as for me.

Let me know what do you think, @greg0ire

**Comment by greg0ire** [comment]
I'm AFK right now but you might want to look into service decoration
