### ISSUE TITLE
How to config SonataAdminBundle with Symfony 2.8.3

### ISSUE THREAD

**Issue by anhnt0212** [sonata-project/SonataAdminBundle#3834]
Hi Guys.
I'm junior developer
I have installed symfony 2.8.3 then i  install more SonataAdminBunlde. The installation process ends I have path "/admin".But it straight back in to the dashboard without going through the **login**. How do I make a login before.
Please help me !!!

**Comment by Soullivaneuh** [comment]
First, you got totally rid of the issue template, please dont.

After that, GitHub issue are here for bug report or specific feature request. Not or global installation help.

Please refer to the documentation or ask your question on StackOverflow: http://stackoverflow.com/questions/tagged/sonata
