### ISSUE TITLE
sonata_type_model_list causes error about duplicated namescape 

### ISSUE THREAD

**Issue by machei** [sonata-project/SonataAdminBundle#3847]
Here function is overriding on based framework called by name Sonata which is building admin template :

```
protected function configureFormFields(FormMapper $formMapper){
$formMapper->add('owner', 'sonata_type_model_list',
    array(
        'class' => 'XYZXBundle:ContestUser',
        'btn_add'       => false,      //Specify a custom label
        'btn_list'      => 'Search',     //which will be translated
        'btn_delete'    => false,             //or hide the button.
        'btn_catalogue' => 'SonataNewsBundle', //Custom translation domain for buttons,
        'by_reference' => false
    ), array(
        'placeholder' => 'No owner selected',
        'by_reference' => false
    ))
    }
```
Object structure:
```

/**
 * @ORM\ManyToOne(targetEntity="XYZ\XBundle\Entity\ContestUser")
 * @ORM\JoinColumn(name="owner_id", referencedColumnName="id")
 * @var XYZ\XBundle\Entity\ContestUser
 */
protected $owner;
```
Happens when i tried to insert new row.

Error stacktrace:

> Expected argument of type "XYZ\XBundle\Entity\XYZ\XBundle\Entity\ContestUser", "XYZ\XBundle\Entity\ContestUser" given` in vendor\symfony\symfony\src\Symfony\Component\PropertyAccess\PropertyAccessor.php at line 254
> UPDATE 1

I tried to use like that below, but still causes the same error.

```
 * @ORM\ManyToOne(targetEntity="\XYZ\XBundle\Entity\ContestUser")
 or
 * @ORM\ManyToOne(targetEntity="ContestUser")
UPDATE 2
```

file XYZ\X\Entity\Contest.php

```
<?php

namespace XYZ\XBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Filesystem\Filesystem;

/**
 * XYZ\XBundle\Entity\Contest
 *
 * @ORM\Table(name="contests")
 * @ORM\Entity(repositoryClass="XYZ\XBundle\Entity\ListRepository")
 * @ORM\HasLifecycleCallbacks()
 */
class Contest
```
XYZ\X\Entity\ContestUser.php
```

<?php

namespace XYZ\XBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\ExecutionContext;
use Symfony\Component\Filesystem\Filesystem;

/**
 * @ORM\Entity()
 * @ORM\Table(name="contest_users")
 */
class ContestUser extends BaseUser
{
```
Namespaces are still valid ok, but only with type sonata_type_model_list causes this error.

Link:
http://stackoverflow.com/questions/37311698/symfony-causes-error-expected-argument-of-type-with-using-framework-sonata/37315739?noredirect=1#comment62154102_37315739

PHP : 5.6.8
Symfony: 2.7.13
"sonata-project/admin-bundle": "2.3.10",
"sonata-project/doctrine-orm-admin-bundle": "2.3.*",
"sonata-project/core-bundle": "2.3.*",
"sonata-project/block-bundle": "2.2.13",
"sonata-project/easy-extends-bundle": "2.1.9",
"sonata-project/user-bundle": "2.2.4",

**Comment by machei** [comment]
I found stupid bug and i had:
public function setOwner(XYZ\XBundle\Entity\ContestUser $owner){}

that code works for me:
public function setOwner(\XYZ\XBundle\Entity\ContestUser $owner){}

**Comment by greg0ire** [comment]
You should use imports at the top of your file to avoid this. It will spare you a lot of repetition since you probably also have a `getOwner` method.
