### ISSUE TITLE
Handle filters in tree view

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#3863]
| Question | Answer |
| --- | --- |
| Bundle version | master |
| Symfony version | 2.8.4 |
| php version | 5.5 |
# Steps to reproduce

Show entities in a tree view, click `Filter` and enter some filters.
# Expected results

Display all items in a tree view that match my filter settings.
# Actual results

Result page displays my entities in a list view.
# Possible improvements
- Display all items and highlight matching results
- Display only filtered items. This may be a problem when a parent item is hidden.
- Hide the filters in tree view

**Comment by core23** [comment]
@sonata-project/contributors What behavior would you expect?

👍 highlight matching results
👎 show only filtered items
🎉 hide filters

**Comment by greg0ire** [comment]
What about showing filtered items AND all their ancestors?

**Comment by core23** [comment]
Added a 4. option

**Comment by core23** [comment]
Please leave your opinion how we should handle the filters in the tree view @sonata-project/contributors
