### ISSUE TITLE
Multi-sort 

### ISSUE THREAD

**Issue by alexhub79** [sonata-project/SonataAdminBundle#387]
You can not define several fields  

protected $datagridValues = array(
        '_page'       => 1,
        '_sort_order' => 'DESC', // sort direction
        '_sort_by' => 'root,lft' // field name
    );    

error 

An exception has been thrown during the rendering of a template ("[Semantical Error] line 0, col 29 near 'lft FROM FirstAppli\TestBundle\Entity\Menu': Error: 'lft' is not defined.") in "FirstAppliTestBundle:ADMIN:list.html.twig" at line 30.

**Comment by jordisala1991** [comment]
It is not possible to sort by multiple filters, atleast with the sort options. You can, however, modify the query as some poeple said.

Closing as this is also related to #1548 .

Ping me if this is still relevant, and different from #1548
