### ISSUE TITLE
Adding support for composite primary keys

### ISSUE THREAD

**Issue by javiereguiluz** [sonata-project/SonataAdminBundle#3870]
*Note: this issue replaces #482, which was closed due to inactivity.*

I'd like to ask if SonataAdminBundle will ever support composite keys for Doctrine entities or if it has been decided to not support them. Thank you.

**Comment by greg0ire** [comment]
I don't know, but for the record, I contributed [this change](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/876f09853f3c1ea7699e0e567860d163961932d2), and was not asked to simplified because "we don't support composite primary keys".

**Comment by greg0ire** [comment]
Related : #3873
