### ISSUE TITLE
Type doctrine_orm_model_autocomplete with query_builder

### ISSUE THREAD

**Issue by mistris** [sonata-project/SonataAdminBundle#3896]
Is it possible to use type `doctrine_orm_model_autocomplete` for datagrid filter together with `query_builder`?
I want this autocomplete to search only in query builder results, not in all DB entries.

Tried something like this but `query_builder` didn't work:
```
->add('device', 'doctrine_orm_model_autocomplete', [
                'query_builder' => function (EntityRepository $er) use ($container) {
                    return $er
                        ->createQueryBuilder('d')
                        ->where('d.organization = :organization')
                        ->andWhere('d.type = :type')
                        ->setParameters([
                            'organization' => $container->get('session')->get('organization'),
                            'type'         => 'csc',
                        ]);
                },
            ], null, [
                'property' => 'name',
                'multiple' => true,
            ])
```

I found that it's possible when configuring form fields with type `sonata_type_model_autocomplete` and `callback`. But I need it for filters.

**Comment by mistris** [comment]
Found solution.
Needed to use the same `callback` as for type `sonata_type_model_autocomplete` and put it in $fieldOptions.

**Comment by squizzypouet** [comment]
Thanks for your solution ! 
Could you tell me where `$container` is coming from ?

**Comment by mistris** [comment]
`$container = $this->getConfigurationPool()->getContainer();`
