### ISSUE TITLE
Avoid Sonata to add a column in ajax requests.

### ISSUE THREAD

**Issue by stuzzo** [sonata-project/SonataAdminBundle#3900]
Bundle: v 3.1.0 
source: 53850de35eb88ebadeb21ad09487d9edfcd357ed
Symfony : v 2.8.6
PHP: 5.6.22

Actually my situation is just like [this](http://stackoverflow.com/a/30045479/320318).
So, I use the list action for normal and ajax requests.
Here's an example of normal list.

![normal-request](https://cloud.githubusercontent.com/assets/6000769/15691686/7d8a3f7e-278a-11e6-9d18-267184e693ac.png)

<br>

When I call the list in ajax (for the pagination), I would expect that list updates results, with no more columns, but Sonata add a Select column.

![ajax-request](https://cloud.githubusercontent.com/assets/6000769/15691706/9db52840-278a-11e6-8697-33a814468925.png)

<br>

Moreover I noticed that if I delete the edit route, I receive the error

> An exception has been thrown during the rendering of a template ("unable to find the route `social.admin.twitter.post.pending.edit`") in "SonataAdminBundle:CRUD:list__select.html.twig" at line 15.

<br>

If I don't delete the edit route, the column is added.
I tried to debug and when I'm in ajax, here's the dump of the column added

![dump](https://cloud.githubusercontent.com/assets/6000769/15691881/8fa606ec-278b-11e6-9e23-4a4d0903716d.png)

How I can avoid this situation?

**Comment by terox** [comment]
Hello,

The issue is located here: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/AbstractAdmin.php#L2794-L2810

You can disable it setting the template "select" to empty, but you still having a "blank" column.

```yanl
# ...
calls:
   - [ setTranslationDomain, [ admin ]]
   - [ setTemplate, [ "select", ""]]
# ...
```
