### ISSUE TITLE
[RFC] default admin

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataAdminBundle#3908]
| Question | Answer |
| --- | --- |
| Bundle version | Sonata 3 and above |
| Symfony version | irrelevant |
| php version | irrelevant |

Given an entity (or document ?) for which several admin are defined, when you try to reference an object of this type, sonata will not be able to choose and will prompt the user for an `admin_code` options in most cases.

Being forced to give this option can get tedious, and can also cause regressions : for instance, if you define and admin, develop a lot of things around it, and then define another admin for the same class, you have to carefully check your application for this error and fix it.

I think this problem could be resolved by injecting where needed a service that would be able to make the right choice when asked for the admin to use for a given class.

The interface to implement would be the following :

``` php
<?php
namespace To\Be\Defined\Please\Help;

interface DefaultAdminResolverInterface
{
    /**
     * Decides which admin best fits the required FQCN
     *
     * @param string $fqcn the fully qualified class of a model that has several admins
     *
     * @return AdminInterface the chosen admin
     */
    public function getDefaultAdminForModel($fqcn);
}
```

I think a good implementation would gather the possible admin services, and discard services that are children admin, and if this does not reduces the number of possible admin to exactly one, then use a mapping model => defaultAdmin .

Whether to give this job to `AdminPool` or create a new class just for this is to be discussed, it turns out it is the class that throws the exception about `admin_code` : https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Admin/Pool.php#L186

**Comment by clytemnestra** [comment]
What about check each admin for a boolean $isMainAdmin and then have the default value for admin_code to go with the admin that has $isMainAdmin true, when there are multiple admins for an Entity?

**Comment by greg0ire** [comment]
I must say I thought about it, but discarded the idea: although it seems more simple, I can see two issues. First, the `false` value of the boolean will be useless, and second, what if you define several main admin for a model? I think the right data structure for this is a hash.

**Comment by greg0ire** [comment]
ping @sonata-project/contributors

**Comment by greg0ire** [comment]
ping @sonata-project/contributors , what do you think about this issue?

**Comment by core23** [comment]
Sounds like a good idea 👍

**Comment by greg0ire** [comment]
Cool, but I'm still torn on this issue:

Either this : 

```
# config.yml
sonata_admin:
    default_admin:
        My\Entity: my_entity_main_admin_id
```

Or something like @clytemnestra suggested, but with null instead of a useless boolean : 

```
# admin.yml
services:
    my_entity_main_admin_id:
        tags:
             -
                  is_main: ~ # If I go with this implementation, I must gather tags and check for uniqueness, so more complicated
```

Can I have your view on this in particular?

**Comment by core23** [comment]
Maybe we can use existing key:
```yml
# config.yml
sonata_admin:
	admin_services:
		id.of.admin.service:
			entities:
				Foo\Entity\Bar

```

**Comment by greg0ire** [comment]
Definitely going to do that, I had forgotten about this key!

**Comment by greg0ire** [comment]
… not. This key is meant to configure services that will be injected in all services.

**Comment by DeonKuhn** [comment]
What's the solve for this?
