### ISSUE TITLE
Preview mode - error with a collection 

### ISSUE THREAD

**Issue by CyrilleGuimezanes** [sonata-project/SonataAdminBundle#3912]
| Question | Answer |
| --- | --- |
| Bundle version | 3.2 |
| Symfony version | 2.8.6 |
| php version | 5.5.12 |

In my admin I have a choice field (nammed 'default_weeks')  with options "expanded" & "multiple" activated.

When I dump the request &  I click on "preview" button I have:

```
object(Symfony\Component\HttpFoundation\ParameterBag)#4 (1) { ["parameters":protected]=> array(2) { ["s5753dd38f25aa"]=> array(25) { ... ["default_weeks"]=> array(3) { [0]=> string(1) "5" [1]=> string(1) "6" [2]=> string(1) "7" } ... 
```

==> OK

But when I click on "approve" or "decline" buttons all others fields are present in the request except this one.

==> KO

Field definition if needed:

``` php
->add('default_weeks', 'sonata_type_model',array(
              'class' => 'MyBundle\Entity\Week',
              'required'=> true,
              'multiple' => true,
              'btn_add' => false,
              'expanded'=>true))
```

Is there an issue?

**Comment by OskarStark** [comment]
Can you confirm this bug with the current `3.2` release, because `2.3` isn't supported anymore

**Comment by CyrilleGuimezanes** [comment]
After few hours to update, yes, the bug is still present in 3.2 (First post edited with good version)

**Comment by CyrilleGuimezanes** [comment]
After some test I can confirm that the issue is present only with the 'expanded' option enabled. 

If I disable this option, preview is wroking fine.

Hope this help

**Comment by OskarStark** [comment]
Could you maybe extend the test? Afterwards i could implement a fix, or you can do it by yourself if you liek

**Comment by CyrilleGuimezanes** [comment]
Sadly, I tried to enter into sonata admin and focus on where 'expanded' options is used but without success. 

Actually I think the bug is where the model is populated before or after accept/decline but I can't find where this is done :/

**Comment by Soullivaneuh** [comment]
@OskarStark Did you reproduce the issue? If yes, please remove the label I added.

**Comment by ju1ius** [comment]
@CyrilleGuimezanes When you submit the preview form, does the browser throw an error like `input is not focusable` or sthg like that ?

**Comment by CyrilleGuimezanes** [comment]
@ju1ius No didn't see any error like that
