### ISSUE TITLE
Nested childAdmin and BreadCrumbs

### ISSUE THREAD

**Issue by MendelYev** [sonata-project/SonataAdminBundle#3916]
Hi everyone,
I really enjoy the childAdmin feature of Sonata, but I can't figure how to use it with nested childs. Suppose we have 3 entities : 
- Dictionnary
- Page (child of dictionnary)
- Word (child of page)
With the configureTabMenu() function I can use addChild() to add a link from a Dictionnary to its Pages (breadcrumbs)
And from a Page I can add a link to its Words.
But I can't chain it : if I get to a Dictionnay and then to one of its Pages, the link to Words of this Page isn't displayed.

From url point, I can use : http://domain.ext/admin/dictionnary/1/page/1/edit
or : http://domain.ext/admin/page/1/word/1/edit
but I can use : http://domain.ext/admin/dictionnary/1/page/1/word/1/edit

Is there actually a way to do this (more than 2 admin levels) ?

**Comment by greg0ire** [comment]
> Is there actually a way to do this (more than 2 admin levels) ?

Not sure but IIRC this is not supported :(

**Comment by greg0ire** [comment]
Can you use `debug:router` to see what routes you can actually use instead of trying random urls ?

**Comment by MendelYev** [comment]
No route is created by Sonata to do such thing (nothing corresponding in debug:router), that's the problem. The documentation explains how to ad a one level childAdmin. But if you add a childAdmin to this child, I does not add a route.
I don't know how to code this functionnality.

**Comment by greg0ire** [comment]
You should probably have a look at `AbstractAdmin::buildRoutes`, see how it behaves. Also, take care, I think it is important to clear your cache if you want it to be fired.

**Comment by MendelYev** [comment]
Creating the route is not the problem. A whole system of persisting and breadcrumbs is deployed when you use childAdmin. I'd like to keep this for nested childAdmin.

**Comment by greg0ire** [comment]
> Creating the route is not the problem. A whole system of persisting and breadcrumbs is deployed when you use childAdmin. I'd like to keep this for nested childAdmin.

Well how can you know if it works if you can't route a page showing this grand-children-admin ?

**Comment by MendelYev** [comment]
For 1 level childAdmin I didn't create any route. As explained in documentation you just have to create an EntityAdmin.php and a service with a specific child. The route is then available.
I can't create a route for a service that does not exists. My question is: how can I create a service for a 2 or more levels childAdmin ?

**Comment by greg0ire** [comment]
What prevents you from doing something like this : 
```yml
services:
    parent.service:
        …
        addChild child service

    child.service:
        …
        addChild grandchild service

    grandchild.service:
        …
```

**Comment by MendelYev** [comment]
Well, that's exactly how I thought it should work. But it doesn't. To explain it here is an exemple:
Let's say I have 3 entities:
- Etablissement: has many Services
- Service: has many Postes.
- Poste: child of Service

AddChild parameters are used exactly like you said:

`etablissement.service: addChild service service`
`service.service: addChild poste service`
`poste.service`
(sorry for the "Service service" but that's how it has to be called in my case)

If I try to travel from an Etablissement to a Poste:

1) I open an Etablissement (called "CHRU")
![sonata_1](https://cloud.githubusercontent.com/assets/7216280/15986606/024310f4-300c-11e6-8648-0c142d637dcd.jpg)

2) From this edit panel, I open the Services tab, which gives me all Services from the selected Etablissement. And you can see that the breadcrumbs keep in memory the Etablissement used to access this list
![sonata_2](https://cloud.githubusercontent.com/assets/7216280/15986607/02451188-300c-11e6-8e7d-873a72045d71.jpg)

3) From this list, I open a Service (called "Psychiatrie"). Inside this Service I can't access the Postes tab (the tabs displayed seem to be those from the Etablissement only)
![sonata_3](https://cloud.githubusercontent.com/assets/7216280/15986605/0240e248-300c-11e6-94f5-8683b16a5907.jpg)

4) If I access the same Service directly (take a look at the url, the Etablissement id is not used) it works. But it does not provide a full breadcrumb so you can't navigate up and down trought parents/children.
![sonata_4](https://cloud.githubusercontent.com/assets/7216280/15986603/01d33234-300c-11e6-84cd-4d52121cb6e7.jpg)
![sonata_5](https://cloud.githubusercontent.com/assets/7216280/15986604/02149f26-300c-11e6-817a-891891ae100c.jpg)

So I think that the main problem is that this functionnality is based on service parameters from the first entity accessed. Instead I'd like it to use parameters from the current displayed entity service.

**Comment by greg0ire** [comment]
I've had a look at the main controller, and clearly, 3-level nesting is not supported : there is a `childId`, but no `grandChildId`. Closing, then.

**Comment by ceesvanegmond** [comment]
@greg0ire Any workaround on this?

**Comment by greg0ire** [comment]
No.

**Comment by jlamur** [comment]
@ceesvanegmond I'm currently working on providing a PR for this feature (nested child admins). I already did it for a business project. I only need the agreement of my company to publish the feature and a little bit of time to clean the code and write a PR. Stay tuned!

**Comment by ceesvanegmond** [comment]
@jlamur I'm glad to help out! 👍

**Comment by jlamur** [comment]
PR open here: #4542.
