### ISSUE TITLE
[Question] Change default admin template

### ISSUE THREAD

**Issue by muspelheim** [sonata-project/SonataAdminBundle#3917]
Hi, how i can change default sonata style to another?
is there any way to change the design or layout is very tied to the components?
I mean change the adminLTE to another bootstrap dashboard, for example http://webapplayers.com/inspinia_admin-v2.4/dashboard_2.html

**Comment by Soullivaneuh** [comment]
@muspelheim Please see the documentation about template: https://sonata-project.org/bundles/admin/3-x/doc/reference/templates.html

GitHub issues is for reporting bug of suggesting idea / feature request.

If you have more questions of how to use the package, please ask it on StackOverflow.

See also: https://github.com/sonata-project/SonataAdminBundle#support

If you want to improve the documentation. We will be glad to review a PR of you. :+1:
