### ISSUE TITLE
List action - Scrollbar on number field types

### ISSUE THREAD

**Issue by CyrilleGuimezanes** [sonata-project/SonataAdminBundle#3923]
| Question | Answer |
| --- | --- |
| Bundle version | 3.2 |
| Symfony version | 2.8.6 |
| php version | 5.5.12 |

Hello,

When I add to my list action a field typed `integer`, `double` or `currency` it display a horizontal scrollbar (see below)

![image](https://cloud.githubusercontent.com/assets/5911548/15888000/721ae5f4-2d65-11e6-8e7a-cbd9689eef17.png)

It was not the case in 2.X version.

I think a simple 'overflow: hidden' fix it but there is maybe more complexes scenarios... 
I also think you should trim() displayed values to avoid:

![image](https://cloud.githubusercontent.com/assets/5911548/15888242/6c25baf6-2d66-11e6-898d-e978ddd7d87b.png)

Regards,

**Comment by greg0ire** [comment]
@ju1ius can you help with this ?

**Comment by CyrilleGuimezanes** [comment]
Hello, 

For the moment, I apply a quick fix into sonata layout:

```
<style media="screen">
  table.sonata-ba-list td {
    overflow: hidden;
  }
</style>
```

**Comment by ju1ius** [comment]
@CyrilleGuimezanes I cannot reproduce your issue...
Can you provide a bit more context ?

**Comment by CyrilleGuimezanes** [comment]
> Does this happen in all browsers ?

Oh, it's only on Chrome 51.0 (tested on FF && Edge)

> Does this happen anytime you use this type of field anywhere ? Or just on a particular view ?

Any view but it happen when the data is align to right.......

Screenshot:
![image](https://cloud.githubusercontent.com/assets/5911548/16071072/901bb8ca-32d9-11e6-925c-3e2bce2e30d1.png)

When I change the text alignement via Chrome dev tools => no scroll bar

For the moment I applied an overflow:hidden only on fields typed integer, currency ...

**Comment by ju1ius** [comment]
> it's only on Chrome 51.0

Can you test in a more recent version ?
I can not reproduce with Chrome 53...

**Comment by muspelheim** [comment]
i confirm this bug in 53 chrome

**Comment by CyrilleGuimezanes** [comment]
@ju1ius For the moment I can't move to Chrome dev channel (due to an other project) but @muspelheim comment seems to confirm the bug

**Comment by ju1ius** [comment]
@CyrilleGuimezanes What does the style inspector say ?
