### ISSUE TITLE
Admin creates too many queries

### ISSUE THREAD

**Issue by clytemnestra** [sonata-project/SonataAdminBundle#3924]
Following https://github.com/sonata-project/SonataAdminBundle/issues/3922

[This method](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/Datagrid/ProxyQuery.php#L242) is being called and returns "o" on that line. The function return "s_user"

**Comment by greg0ire** [comment]
So it joins nothing, because there are not filters applied I guess.

**Comment by clytemnestra** [comment]
Well there are no filters applied. Then what's the problem? Shouldn't it join all relationships?

**Comment by greg0ire** [comment]
> Shouldn't it join all relationships?

It would be a plus, yeah. And I think this method could be called by a piece of code that would analyze the list mapper. Let's try to find where this should happen.

**Comment by greg0ire** [comment]
IMO it could happen [here](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/Builder/DatagridBuilder.php#L163)

**Comment by greg0ire** [comment]
I didn't notice that you created the issue on the admin bundle again. This should be reported in the ORM bundle.

**Comment by clytemnestra** [comment]
Oups, relocating it again.
