### ISSUE TITLE
[Bug] RoleSecurityHandler ignores object for Super-Admins

### ISSUE THREAD

**Issue by leberknecht** [sonata-project/SonataAdminBundle#3928]
| Question       | Answer
|----------------|-------------------------------
| Bundle version | <ul><li>sonata-project/block-bundle 3.0.0 Symfony SonataBlockBundle</li><li>sonata-project/cache        1.0.7 Cache library</li><li>sonata-project/core-bundle  3.0.2 Symfony SonataCoreBundle</li><li>sonata-project/exporter     1.4.1 Lightweight Exporter library</li><li>sonata-project/intl-bundle  2.2.4 Symfony SonataIntlBundle</li></ul>
| symfony version| <ul><li>symfony/asset                v3.1.0 Symfony Asset Component</li><li>symfony/cache                v3.1.0 Symfony implementation of PSR-6</li><li>symfony/class-loader         v3.1.0 Symfony ClassLoader Component</li><li>symfony/config               v3.1.0 Symfony Config Component</li><li>symfony/console              v3.1.0 Symfony Console Component</li><li>symfony/debug                v3.1.0 Symfony Debug Component</li><li>symfony/dependency-injection v3.1.0 Symfony DependencyInjection Component</li><li>symfony/event-dispatcher     v3.1.0 Symfony EventDispatcher Component</li><li>symfony/expression-language  v3.1.0 Symfony ExpressionLanguage Component</li><li>symfony/filesystem           v3.1.0 Symfony Filesystem Component</li><li>symfony/finder               v3.1.0 Symfony Finder Component</li><li>symfony/form                 v3.1.0 Symfony Form Component</li><li>symfony/framework-bundle     v3.1.0 Symfony FrameworkBundle</li><li>symfony/http-foundation      v3.1.0 Symfony HttpFoundation Component</li><li>symfony/http-kernel          v3.1.0 Symfony HttpKernel Component</li><li>symfony/inflector            v3.1.0 Symfony Inflector Component</li><li>symfony/intl                 v3.1.0 A PHP replacement layer for the C intl extension that includes additional data from the ICU library.</li><li>symfony/options-resolver     v3.1.0 Symfony OptionsResolver Component</li><li>symfony/phpunit-bridge       v3.1.0 Symfony PHPUnit Bridge</li><li>symfony/polyfill-intl-icu    v1.2.0 Symfony polyfill for intl's ICU-related data and classes</li><li>symfony/polyfill-mbstring    v1.2.0 Symfony polyfill for the Mbstring extension</li><li>symfony/polyfill-php56       v1.2.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions</li><li>symfony/polyfill-php70       v1.2.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions</li><li>symfony/polyfill-util        v1.2.0 Symfony utilities for portability of PHP codes</li><li>symfony/process              v3.1.0 Symfony Process Component</li><li>symfony/property-access      v3.1.0 Symfony PropertyAccess Component</li><li>symfony/routing              v3.1.0 Symfony Routing Component</li><li>symfony/security             v3.1.0 Symfony Security Component</li><li>symfony/security-acl         v3.0.0 Symfony Security Component - ACL (Access Control List)</li><li>symfony/security-bundle      v3.1.0 Symfony SecurityBundle</li><li>symfony/stopwatch            v3.1.0 Symfony Stopwatch Component</li><li>symfony/templating           v3.1.0 Symfony Templating Component</li><li>symfony/translation          v3.1.0 Symfony Translation Component</li><li>symfony/twig-bridge          v3.1.0 Symfony Twig Bridge</li><li>symfony/validator            v3.1.0 Symfony Validator Component</li><li>symfony/yaml                 v3.1.0 Symfony Yaml Componen</li></ul>
| php version    | PHP 7.0.7-2+donate.sury.org~trusty+1 (cli) ( NTS ) Copyright (c) 1997-2016 The PHP Group Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies  with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans

# Error message

```
no error message
```

# Steps to reproduce

Assign a user a super-admin role, login to sonata, edit a user that has no roles and use 
```php
$this->isGranted('ROLE_WHATEVER', $userWithoutAnyRoles)
```

# Expected results

false

# Actual results

true

# more info

In Security/Handler/RoleSecurityHandler.php: 

```php
public function isGranted(AdminInterface $admin, $attributes, $object = null)
{
[...]
try {
        return $this->authorizationChecker->isGranted($this->superAdminRoles)
            || $this->authorizationChecker->isGranted($attributes, $object);
    } catch (AuthenticationCredentialsNotFoundException $e) {
        return false;
    }
[...]
```

This leads to "if sonata-user has super-admin roles, and we ask isGranted for privs of another user-object, we grant all privs to this user as well"

**Comment by greg0ire** [comment]
O_o good catch!

**Comment by Soullivaneuh** [comment]
> This leads to "if sonata-user has super-admin roles, and we ask isGranted for privs of another user-object, we grant all privs to this user as well"

You provided a code sample and an expected result, but I still not understand what is the bug exactly.

Could you provide a step by step use case? I mean on the UI, not the code.

The part I don't really understand:

> and we ask isGranted for privs of another user-object, we grant all privs to this user as well"

**Comment by leberknecht** [comment]
>Could you provide a step by step use case? I mean on the UI, not the code.

might be tricky, as the buggy method/use-case needs code :D I will try. 
- install symfony (i used 3.0, 3.1 seems to have dependency problems with fos-user-bundle and the security component)
- install fos-user bundle
- install sonata-admin-bundle
- setup a user-entity, so we can fetch a user by id from a repository
- create a new user, call it "admin", assign ROLE_SUPER_ADMIN
- create a second user, call it "normalUser", ensure the user only has ROLE_USER
- create UserAdmin, give it a method like this: 
```php
    public function something()
    {
        $userObject = $this->getConfigurationPool()
            ->getContainer()
            ->get('doctrine')
            ->getRepository('MyBundle:User')
            ->find(<normalUsers-ID>);
        $result = $this->isGranted('ROLE_DOESNT_EVEN_EXIST', $userObject);
        var_dump($result);
    }
```
- call that method somewhere in your UserAdmin
- login to sonata as "admin" user
- trigger the method

result will be that `isGranted` claims that "normal" user _does_ have the role "ROLE_DOESNT_EVEN_EXIST", because the admin user (that is triggering the method) has ROLE_SUPER_ADMIN. Because the check for super-admin roles ignores the user-object passed to `isGranted` and therefore fetches the "current user" (= admin) from the security context.

But: i noticed that my patch actually doesnt fix the problem! Sorry for that! It looks to me like the problem also exists (if i see it correctly...maybe i'm missing something?) in `symfony/symfony RoleVoter:vote` => 
```php
public function vote(TokenInterface $token, $subject, array $attributes)
    {
        $result = VoterInterface::ACCESS_ABSTAIN;
        $roles = $this->extractRoles($token);
        foreach ($attributes as $attribute) {
            if (0 !== strpos($attribute, $this->prefix)) {
                continue;
            }
            $result = VoterInterface::ACCESS_DENIED;
            foreach ($roles as $role) {
                if ($attribute === $role->getRole()) {
                    return VoterInterface::ACCESS_GRANTED;
                }
            }
        }
        return $result;
    }
```
so we pass `$subject` but we dont do anything with it..i think we are missing something like `$this->supports($subject, $attributes)` here? At the moment, it looks to me like its saying "gather roles from token (= in my case this results in `RoleHierarchyVoter:getReachableRoles($token->getRoles());` getting called, which returnes all-known-roles ?) and check if the requested role is in there". I'm trying to gather more debugging info. If i'm missing something, please tell me :D

**Comment by Soullivaneuh** [comment]
> result will be that isGranted claims that "normal" user does have the role "ROLE_DOESNT_EVEN_EXIST", because the admin user (that is triggering the method) has ROLE_SUPER_ADMIN. Because the check for super-admin roles ignores the user-object passed to isGranted and therefore fetches the "current user" (= admin) from the security context.

Ok so in a nutshell, the checker totally ignore the passed user on:

```php
$this->isGranted('ROLE_DOESNT_EVEN_EXIST', $userObject);
```

That's right?

And what is the behavior with an existent role?

**Comment by leberknecht** [comment]
As commented on PR: Turns out the second parameter given to isGranted is not the "object that is requesting permission" but the "object we are requesting permission on", so the current logic is totally correct. (as, if we are Super-admin, we dont need to care about "what object" we are dealing with, we are allowed to do everything with anything). Sorry for the confusion!

**Comment by leberknecht** [comment]
Ah, if anyone finds this: Maybe this helps you:
http://stackoverflow.com/questions/24078270/check-if-a-role-is-granted-for-a-specific-user-in-symfony2-acl

**Comment by greg0ire** [comment]
Looks like I read to fast ^^
