### ISSUE TITLE
Where is CSRF protection?

### ISSUE THREAD

**Issue by Romashka** [sonata-project/SonataAdminBundle#3933]
Is there any CSRF protection for editable fields at list view? I haven't found it at `Sonata\AdminBundle\Controller\HelperController::setObjectFieldValueAction`

**Comment by Soullivaneuh** [comment]
Please don't open issue just to push a question like that.

First, issues are for issues. If you are a question about how to do things, you have a StackOverflow channel for that. See: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md#issues

Then, Sonata issues have a template. Please follow it if you have to report a bug.

Regards.
