### ISSUE TITLE
How to manage the entity more convenient in the sonata backend?

### ISSUE THREAD

**Issue by liamyabou** [sonata-project/SonataAdminBundle#3937]
Hi, 

I'm learning symfony2 about sonata-admin-bundle; There are three tables `goods`、`category` and `brand`, I want to show or edit category.name and brand.name in the backend page(goods listView),it will be very convenient for administrator to manage them;

![error_01](https://cloud.githubusercontent.com/assets/17719629/15898814/3b52cf7a-2dcc-11e6-8feb-78233cbfdf7d.jpg)

![error_02](https://cloud.githubusercontent.com/assets/17719629/15898824/422de190-2dcc-11e6-9f84-47028898861f.jpg)

It shows category.name is built with "many-to-one" relation successfuly, and the second relation between 

brand and goods is not work.

I have two questions:

1、Is the "yml" file just can contain one "many-to-one" relationship?

2、If Iwant to manage the goods info in one page,(please refer the picture),what should I do?

Here is some code below:

**brand.orm.yml**

    Application\Sonata\MallBundle\Entity\Brand:
        type: entity
        table: brand
        ...
        oneToMany:
            goods:
                targetEntity: Goods
                mappedBy: brand
        lifecycleCallbacks: {  }

**goods.orm.yml**

    Application\Sonata\MallBundle\Entity\Goods:
        type: entity
        table: goods
        repositoryClass: Application\Sonata\MallBundle\Repository\GoodsRepository
        ...
        manyToOne:
            category:
                targetEntity: Category
                inverseBy: goods
                joinColumn:
                    name: category_id
                    referencedColumnName: id
        manyToOne:
            brand:
                targetEntity: Brand
                inverseBy: goods
                joinColumn:
                    name: brand_id
                    referencedColumnName: id
        lifecycleCallbacks: {  }

**category.orm.yml**

    Application\Sonata\MallBundle\Entity\Category:
        type: entity
        table: category
        repositoryClass: Application\Sonata\MallBundle\Repository\CategoryRepository
        ...
        oneToMany:
            goods:
                targetEntity: Goods
                mappedBy: category
        lifecycleCallbacks: {  }

Someone please help, any help appreciated.

**Comment by core23** [comment]
Please don't open issue just to push a question like that.

First, issues are for issues. If you are a question about how to do things, you have a StackOverflow channel for that. See: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md#issues

Regards.
