### ISSUE TITLE
About symfony 3 support

### ISSUE THREAD

**Issue by sampath92** [sonata-project/SonataAdminBundle#3945]
Hi ,

I'm new to symfony. I started working on a project and it needs a admin panel. then I found this bundle. But I don't know is this support for symfony 3. Can some one help me to find it out. My app based on symfony 3.1.0 version. Thanks.

**Comment by greg0ire** [comment]
We support sf3

**Comment by Soullivaneuh** [comment]
Just read the composer.json file to know it: https://github.com/sonata-project/SonataAdminBundle/blob/3.3.0/composer.json#L27-L41
