### ISSUE TITLE
Make search results more ergonomic 

### ISSUE THREAD

**Issue by Soullivaneuh** [sonata-project/SonataAdminBundle#3946]
I have a project with a **lot** of admin classes.

So when we do a global search, we have this kind of result:

![image](https://cloud.githubusercontent.com/assets/1698357/16036694/575cce28-321d-11e6-83d4-052a36554d58.png)

As you can see (or not), only one box has a result. This is hard to find it.

I'm thinking of two solution:
- [ ] Colorize by default the boxes with results, with `primary` or `info` colors. An option to deactivate it may be added
- [ ] Add a `show_empty_boxes` option for search. If set to `false`, only boxes with results will be shown

Another idea?

**Comment by OskarStark** [comment]
Love your ideas 👍 

maybe ordering them by number of search results?

**Comment by Soullivaneuh** [comment]
> maybe ordering them by number of search results?

Not sure about that. Later, I would like to propose a feature to separate search result by section.

**Comment by ju1ius** [comment]
What's the point of showing empty boxes ?
The should never be shown IMO.

**Comment by ju1ius** [comment]
> a feature to separate search result by section

The ability to **query** only a particular group would be also very nice.

**Comment by Soullivaneuh** [comment]
> The ability to query only a particular group would be also very nice.

Well, this will be a big change, let's start simple. :wink: 

> What's the point of showing empty boxes ?
> The should never be shown IMO.

Empty boxes has link to create and/or go to list.

Plus, this permits to differentiate no-result boxes and not configured for search admins.

**Comment by Soullivaneuh** [comment]
Two proposition for colorized boxes, please vote:

:+1: for this one:

![image](https://cloud.githubusercontent.com/assets/1698357/16043156/a5dc3586-323e-11e6-898b-be322bf1cd72.png)

:-1: for this one:

![image](https://cloud.githubusercontent.com/assets/1698357/16043162/adf727d0-323e-11e6-92b9-78e9d313b6bd.png)

I prefer the first one, the color is more explicit.

**Comment by Soullivaneuh** [comment]
And finally, the "Hide empty boxes" option would render this:

![image](https://cloud.githubusercontent.com/assets/1698357/16043295/3d599ade-323f-11e6-8435-ce633622119a.png)

What do you think?

**Comment by Soullivaneuh** [comment]
Seems you prefer the first result for https://github.com/sonata-project/SonataAdminBundle/issues/3946#issuecomment-225869780.

But maybe `primary` color is to aggressive. I give a try with `info`, it's smoother IMHO. Please vote:

:+1: for this:

![image](https://cloud.githubusercontent.com/assets/1698357/16043503/3b07c854-3240-11e6-89c0-79d44ad5a993.png)

:-1: for this:

![image](https://cloud.githubusercontent.com/assets/1698357/16043515/435acaf6-3240-11e6-8584-6a7e39f2a091.png)

**Comment by ju1ius** [comment]
> Empty boxes has link to create and/or go to list.

Well then you could render boxes with results first, then the empty ones, so that relevant stuff comes first.

**Comment by Soullivaneuh** [comment]
Or just have an option to allow empty box or not.

For my case, links on boxes are pointless. The option permits the users to have the choice.

**Comment by javiereguiluz** [comment]
And what about fading a bit the elements that contain no results?

### Before

![435acaf6-3240-11e6-8584-6a7e39f2a091_original](https://cloud.githubusercontent.com/assets/73419/16077101/15743f16-32f7-11e6-92de-18af83acf53c.png)

### After

![435acaf6-3240-11e6-8584-6a7e39f2a091_proposal](https://cloud.githubusercontent.com/assets/73419/16077103/18456120-32f7-11e6-8840-b5851c0bda80.png)

**Comment by OskarStark** [comment]
this looks awesome @javiereguiluz 👍

**Comment by Soullivaneuh** [comment]
Nice idea @javiereguiluz! :+1: 

Do you have the CSS part of what you did?

**Comment by core23** [comment]
Maybe we can use a library like [Masonry](http://masonry.desandro.com/) to fill the empty spaces too

**Comment by OskarStark** [comment]
> Maybe we can use a library like Masonry to fill the empty spaces too

Would be a cool feature 👍

**Comment by muspelheim** [comment]
@Soullivaneuh @OskarStark @core23 Hello, guys. Any news about this feature?

**Comment by core23** [comment]
Feel free to start @muspelheim 👍

**Comment by muspelheim** [comment]
@core23 ok, I try to implement this

**Comment by muspelheim** [comment]
So, I implement this feature and in bottom you can see the result:

*show option*
![show](https://cloud.githubusercontent.com/assets/1663352/22080347/553075b4-ddd0-11e6-8ac2-a252af5ff674.png)

*fade option*
![fade](https://cloud.githubusercontent.com/assets/1663352/22080346/55267ad2-ddd0-11e6-85f8-72cd3fbb122f.png)

*hide option*
![hide](https://cloud.githubusercontent.com/assets/1663352/22080345/552613b2-ddd0-11e6-8072-8835ac352aa2.png)

what do you think about it? may be need some changes?
