### ISSUE TITLE
expanded entity form are not grouped

### ISSUE THREAD

**Issue by kavillock** [sonata-project/SonataAdminBundle#3950]
| Question | Answer |
| --- | --- |
| Bundle version | 3.3.0 |
| Symfony version | 2.8.7 |
| php version | 5.6.19 |
# Steps to reproduce

``` php
            ->with('Atrybuty', array('class' => 'col-md-8'))
                ->add('attributes', null, array(
                    'label' => false,
                    'required' => false,
                    'class' => 'ProductBundle\Entity\ProductAttributeValue',
                    'property' => 'name',
                    'multiple' => true,
                    'expanded' => true,
                    'query_builder' => function (\Doctrine\ORM\EntityRepository $er) {
                        return $er->createQueryBuilder('u')
                            ->orderBy('u.name', 'ASC');
                    },
                    'group_by' => 'attribute.label'
                ))
            ->end()
```
# Expected results

without  'expanded' => true, i get groups, but in select field, i want with checkboxes

a group1
- [ ] a1
- [ ] a2
- [ ] a3

b group2
- [ ] b1
- [ ] b2
- [ ] b3
# Actual results
- [ ] a1
- [ ] a2
- [ ] a3
- [ ] b1
- [ ] b2
- [ ] b3

**Comment by Soullivaneuh** [comment]
@sonata-project/contributors Anyone can confirm this bug?

**Comment by ju1ius** [comment]
Is it actually supposed to work like that in the first place ?
From what I can see, the expanded choice widget is just a flat list of checkboxes...
This looks more like a feature request.

**Comment by LMSzor** [comment]
@ju1ius Whats the point of having a limited functionality? If we are able to not-expand and group options, we should also be able to expand and group them. I've just encountered this problem and its confusing, that I actually use these options in a combo.
