### ISSUE TITLE
Checkbox and radio rows not aligned with horizontal layout

### ISSUE THREAD

**Issue by EmmanuelVella** [sonata-project/SonataAdminBundle#3951]
| Question       | Answer
|----------------|-------------------------------
| Bundle version | 3.3.0
| Symfony version| 2.8.7
| php version    | 5.5

# Steps to reproduce

Use horizontal layout : 
```
sonata_admin:
    options:
        form_type: horizontal
```

Add a checkbox in a form : 
```
protected function configureFormFields(FormMapper $formMapper)
{
    $formMapper
        ...
        ->add('enabled', 'checkbox')
    ;
}
```

# Expected results

Checkbox should be aligned with other inputs : 
![checkbox-ok](https://cloud.githubusercontent.com/assets/663607/16084647/d81f7d38-3319-11e6-8da8-c05ccd522388.JPG)

# Actual results

Checkbox is aligned on the left of the page.
![checkbox](https://cloud.githubusercontent.com/assets/663607/16083421/33321bb8-3315-11e6-9eb8-6cc397f832d7.JPG)

An offset column (col-md-3) is needed, in order to fill in the left space.

**Comment by Soullivaneuh** [comment]
Please fill the PR template correctly. Especially for step to reproduce.

**Comment by Soullivaneuh** [comment]
Also try with the latest version of admin-bundle (3.3.0).

**Comment by EmmanuelVella** [comment]
@Soullivaneuh I updated my PR and fixed the version number (was a mistake).

**Comment by Soullivaneuh** [comment]
Thanks @EmmanuelVella.

Bug confirmed.

**Comment by Soullivaneuh** [comment]
@EmmanuelVella Do you have a case to reproduce the issue with radio?

**Comment by EmmanuelVella** [comment]
I did not test, give me a few minutes and I tell you if there is a problem with radios too.

**Comment by EmmanuelVella** [comment]
Radio are ok, sorry my title was indeed incorrect ! I updated it.

**Comment by Soullivaneuh** [comment]
They are not: 

![image](https://cloud.githubusercontent.com/assets/1698357/16153405/78334182-34a6-11e6-85f4-1e51c11a86bc.png)

```php
->add('canceled', 'radio', ['required' => false])
```

**Comment by EmmanuelVella** [comment]
Hum ok... I tested too quickly apparently ;) Thank you

**Comment by EmmanuelVella** [comment]
Ok found why, expanded `choices` type is ok, not `radio` type.

```
...
->add('tags', 'choice', [
    'expanded' => true,
    'choices' => range(1, 3),
])
```

![choices](https://cloud.githubusercontent.com/assets/663607/16153518/f41fe1a6-34a6-11e6-83a5-70f240fc4815.JPG)

**Comment by Soullivaneuh** [comment]
PR is coming. :wink:

**Comment by EmmanuelVella** [comment]
Great :+1:  ! Thank you very much.

**Comment by Soullivaneuh** [comment]
@EmmanuelVella => #3962
