### ISSUE TITLE
Filter block design issue

### ISSUE THREAD

**Issue by ArturTovmasyan** [sonata-project/SonataAdminBundle#3954]
After update sonata admin bundle we have a problem on FILTER BLOCK (RIGHT),it is showing incorrect style on all window size, Please help me fix it
![screenshot from 2016-06-16 20 45 20](https://cloud.githubusercontent.com/assets/13746633/16125166/7c01e154-3403-11e6-93fd-fd7123602160.png)

        "sonata-project/admin-bundle": "3.3.*",
        "sonata-project/core-bundle": "3.0.*",
        "sonata-project/doctrine-orm-admin-bundle": "3.0.*",
        "sonata-project/intl-bundle": "2.2.*",
        "sonata-project/easy-extends-bundle" :"2.1.*",

**Comment by core23** [comment]
Please add some more information. We don't see your screen...

**Comment by greg0ire** [comment]
The filter block is no longer right, it is supposed to be on top. Check your project for overrides.

**Comment by ArturTovmasyan** [comment]
How to set it on top?

**Comment by ArturTovmasyan** [comment]
![screenshot from 2016-06-16 20 45 20](https://cloud.githubusercontent.com/assets/13746633/16125145/5ef0df66-3403-11e6-81ca-0e2300c33524.png)

**Comment by ArturTovmasyan** [comment]
How to set it on top?

**Comment by greg0ire** [comment]
You don't have ti do anything, it is the default behavior I think. Check your project for template overrides

**Comment by ArturTovmasyan** [comment]
Thank you! After update override template standard_layout.html.twig it's ok...
![sonata](https://cloud.githubusercontent.com/assets/13746633/16126305/93b00042-3408-11e6-97e7-4eca452c2708.png)

**Comment by Soullivaneuh** [comment]
As @greg0ire said, you are certainly overriding some sonata template.

Some BC break are present on this new major.

Solution:

* Deactivate **all** your overridden
* Watch parent template and fix yours

Please next time you open an issue, follow the added template. Otherwise, we cannot guarantee any answer on it.

**Comment by OlegBabakov** [comment]
Maybe my article will help you:
http://logicm.beget.tech/2016/10/20/sonata-admin-3-filter-panel-right-side/
