### ISSUE TITLE
[RFC] association mapping abstraction methods for FieldDescriptionInterface

### ISSUE THREAD

**Issue by ju1ius** [sonata-project/SonataAdminBundle#3958]
> «Every persistence layer likely has some kind of "related model" concept. At the end of the day, whatever the underlying concepts, the admin interface for a document with some relations always looks very similar, so having the same code for all of that makes sense.» - @dbu

Hi,
I'm finishing moving the CRUD association templates back to the admin bundle. Currently the persistence bundles still have to choose the appropriate block to display depending on the association type. For example, the `sonata_type_admin` widget in SonataDoctrineORMAdminBundle now looks like:

``` twig
{# SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig #}
{% block sonata_type_admin_widget %}
  {% if sonata_admin.field_description.mappingType in [
    constant('Doctrine\\ORM\\Mapping\\ClassMetadataInfo::ONE_TO_ONE'),
    constant('Doctrine\\ORM\\Mapping\\ClassMetadataInfo::MANY_TO_ONE')
  ] %}
    {# This block is defined in the SonataAdminBundle #}
    {{ block('sonata_admin_one_to_one_widget') }}
  {% else %}
    The admin widget only supports single-valued associations.
  {% endif %}
{% endblock %}
```

Which is okay-ish, but still lets a leaky abstraction leak into the view layer. Not kosher.

Therefore I propose that the following methods be added to the `FieldDescriptionInterface`.
# Interface

``` php
namespace Sonata\AdminBundle\Admin;

interface FieldDescriptionInterface
{
  /**
   * Returns whether this object describes an association between two related models.
   *
   * @return boolean
   */
  public function describesAssociation();

  /**
   * Returns whether this object describes a single-valued (N..1) association.
   *
   * @return boolean
   */
  public function describesSingleValuedAssociation();

  /**
   * Returns whether this object describes a collection-valued (N..*) association.
   *
   * @return boolean
   */
  public function describesCollectionValuedAssociation();
}
```

This would completely remove the need for persistence bundles to override the widget blocks. For example the `sonata_type_admin` widget could now be moved to the AdminBundle and would look like this:

``` twig
{# SonataAdminBundle:Form:form_admin_fields.html.twig #}
{% block sonata_type_admin_widget %}
  {% if sonata_admin.field_description.describesSingleValuedAssociation %}
    {{ block('sonata_admin_association_single_widget') }}
  {% else %}
    The admin widget only supports single-valued associations.
  {% endif %}
{% endblock %}
```

Although I haven't thoroughly checked the if and how, it _might_ also enable us to later remove duplicated logic from the various Builder implementations (DatagridBuilder, FormContractor, ListBuilder, ShowBuilder).

Following are the new methods implementations for the four persistence bundles.
# Implementations
## Abstract base class

``` php
namespace Sonata\AdminBundle\Admin;

abstract class BaseFieldDescription implements FieldDescriptionInterface
{
  /**
   * @inheritdoc
   */
  final public function describesAssociation()
  {
    return $this->describesSingleValuedAssociation()
      || $this->describesCollectionValuedAssociation();
  }
}
```
## Doctrine ORM implementation

``` php
namespace Sonata\DoctrineORMAdminBundle\Admin;

use Doctrine\ORM\Mapping\ClassMetadata;
use Sonata\AdminBundle\Admin\BaseFieldDescription;

class FieldDescription extends BaseFieldDescription
{
  /**
   * @inheritdoc
   */
  final public function describesSingleValuedAssociation()
  {
    return $this->mappingType === ($this->mappingType & ClassMetadata::TO_ONE);
  }

  /**
   * @inheritdoc
   */
  final public function describesCollectionValuedAssociation()
  {
    return $this->mappingType === ($this->mappingType & ClassMetadata::TO_MANY);
  }
}
```
## Doctrine MongoDB ODM implementation

``` php
<?php
namespace Sonata\DoctrineMongoDBAdminBundle\Admin;

use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Sonata\AdminBundle\Admin\BaseFieldDescription;

class FieldDescription extends BaseFieldDescription
{
  /**
   * @inheritdoc
   */
  final public function describesSingleValuedAssociation()
  {
    return in_array($this->mappingType, [
      ClassMetadata::ONE,
      ClassMetadata::REFERENCE_ONE,
      ClassMetadata::EMBED_ONE,
    ], true);
  }

  /**
   * @inheritdoc
   */
  final public function describesCollectionValuedAssociation()
  {
    return in_array($this->mappingType, [
      ClassMetadata::MANY,
      ClassMetadata::REFERENCE_MANY,
      ClassMetadata::EMBED_MANY,
    ], true);
  }
}
```
## Doctrine PHPCR ODM implementation

``` php
namespace Sonata\DoctrinePHPCRAdminBundle\Admin;

use Doctrine\ODM\PHPCR\Mapping\ClassMetadata;
use Sonata\AdminBundle\Admin\BaseFieldDescription;

class FieldDescription extends BaseFieldDescription
{
  /**
   * @inheritdoc
   */
  final public function describesSingleValuedAssociation()
  {
    return in_array($this->mappingType, [
      ClassMetadata::MANY_TO_ONE,
      'child',
      'parent'
    ], true);
  }

  /**
   * @inheritdoc
   */
  final public function describesCollectionValuedAssociation()
  {
    return in_array($this->mappingType, [
      ClassMetadata::MANY_TO_MANY,
      'children',
      'referrers',
      'mixedreferrers'
    ], true);
  }
}
```
## Propel ORM implementation

``` php
namespace Sonata\PropelAdminBundle\Admin;

use Propel\Runtime\Map\RelationMap;
use Sonata\AdminBundle\Admin\BaseFieldDescription;

class FieldDescription extends BaseFieldDescription
{
  /**
   * @inheritdoc
   */
  final public function describesSingleValuedAssociation()
  {
    return in_array($this->mappingType, [
      RelationMap::ONE_TO_ONE,
      RelationMap::MANY_TO_ONE,
    ], true);
  }

  /**
   * @inheritdoc
   */
  final public function describesCollectionValuedAssociation()
  {
    return in_array($this->mappingType, [
      RelationMap::ONE_TO_MANY,
      RelationMap::MANY_TO_MANY,
    ], true);
  }
}
```
# Comments ?

This is a RFC, so I'm waiting for your comments, in particular regarding the correctness of implementations, as I'm not familiar with all the persistence layers.

Thanks.

**Comment by greg0ire** [comment]
Great initiative! The MongoDB implementation looks a bit weird though, because I fail to see how `describesOneToOneAssociation` and `describesManyToOneAssociation` would return the same thing…

**Comment by ju1ius** [comment]
@greg0ire In MongoDB a referenceable document can always be referenced by any number of others.

So I guess it's a matter of choosing between:
1. Considering that the left side cardinality is always many, so `describesOneToOneAssociation` and `describesOneToManyAssociation` should always return `false`.
2. Considering that the left side cardinality is not defined, so `describesOneToOneAssociation` and `describesManyToOneAssociation` should return the same thing as `describesToOneAssociation`.

Thinking about it this way, I think you're right and that n°1 is the correct behavior...

**Comment by greg0ire** [comment]
3. `describesOneTo*Association` has no meaning for MongoDb and should be part of a separate interface that MongoDB will not implement.

**Comment by ju1ius** [comment]
> should be part of a separate interface that MongoDB will not implement

OMG, are you sure you want to write
```php
if ($fieldDescription instanceof LeftSideAssociationCardinalityAwareFieldDescriptionInterface) {
  throw new \OutOfBoundsException('Cannot write Java in here.');
}
```
:laughing:

**Comment by ju1ius** [comment]
@greg0ire  Jokes aside, what would it look like ?

**Comment by greg0ire** [comment]
Something shorter maybe, but it's just a thought. Solution 1 is maybe more sensible, because the implementation you are providing still kind of makes sense… it's not like you're writing `throw new NotImplementedException()`, which is a sign of Interface Segregation Principle violation, so go with that I guess…

**Comment by greg0ire** [comment]
ping @sonata-project/contributors

**Comment by ju1ius** [comment]
@greg0ire Been working on it a bit yesterday, and turns out that you're _almost_ right on this one. It's not that we need separate interfaces, but that `describesToOneAssociation` and `describesToManyAssociation` are in fact the only two methods that we actually need ! The left-side cardinality is a persistence layer thing and is irrelevant in an object context.
Which is why Doctrine's common ClassMetadata interface only specifies `isSingleValuedAssociation()` and `isCollectionValuedAssociation()`, I guess.

Which means we can get by with only three methods:

```php
namespace Sonata\AdminBundle\Admin;

interface FieldDescriptionInterface
{
  /**
   * Returns whether this object describes an association between two related models.
   *
   * @return boolean
   */
  public function describesAssociation();
  /**
   * Returns whether this object describes a (N..1) association.
   *
   * @return boolean
   */
  public function describesToOneAssociation();

  /**
   * Returns whether this object describes a (N..*) association.
   *
   * @return boolean
   */
  public function describesToManyAssociation();
}
```

BTW I wonder if we shouldn't just borrow Doctrines names, like `describesSingleValuedAssociation` and `describesCollectionValuedAssociation`, what do you think ?

**Comment by greg0ire** [comment]
> BTW I wonder if we shouldn't just borrow Doctrines names, like describesSingleValuedAssociation and describesCollectionValuedAssociation, what do you think ?

I think if we can sound familiar, let's sound familiar, it makes sense.

> The left-side cardinality is a persistence layer thing and is irrelevant in an object context.

Indeed, it is relevant for persistence because things are going in an n-m table or just in a field depending on if it is one to many or many to many, but for a form, for instance, we don't really care. Glad we end up with a somewhat small interface!

**Comment by ju1ius** [comment]
I just updated the main issue comment.
