### ISSUE TITLE
Deleting ACLs despite error when deleting an object.

### ISSUE THREAD

**Issue by TimoFrenzel** [sonata-project/SonataAdminBundle#3968]
### Environment
all

#### Sonata packages
AdminBundle

```bash
$ composer show sonata-project/*
"sonata-project/admin-bundle": "2.4.*@dev",
        "sonata-project/core-bundle": "2.3.*@dev",
        "sonata-project/easy-extends-bundle": "2.1.*@dev",
        "sonata-project/intl-bundle": "2.2.*@dev",
        "sonata-project/doctrine-orm-admin-bundle": "2.4.*@dev",
        "sonata-project/notification-bundle": "2.3.*@dev",
        "sonata-project/block-bundle": "2.3.*@dev",
        "sonata-project/media-bundle": "2.4.*@dev",
        "sonata-project/user-bundle": "2.3.*@dev",
        "sonata-project/cache-bundle": "2.2.*@dev",
        "sonata-project/page-bundle": "2.3.*@dev",
        "sonata-project/formatter-bundle": "2.4.*@dev",
        "sonata-project/news-bundle": "2.3.*@dev",
        "sonata-project/classification-bundle": "2.3.*@dev",
        "sonata-project/datagrid-bundle": "2.2.*@dev",
"sonata-project/markitup-bundle": "dev-master",
```

#### Symfony packages

```bash
$ composer show symfony/*
"symfony/icu": "~1.0-RC",
"symfony/intl": "2.6.*@dev",
"symfony-cmf/routing-bundle": "1.1.*@dev",
"symfony-cmf/routing": "1.1.*@dev",
"symfony/symfony": "~2.3",
"symfony/assetic-bundle": "~2.3",
"symfony/swiftmailer-bundle": "~2.3",
"symfony/monolog-bundle": "~2.4",
```

#### PHP version

```bash
$ php -v
PHP 5.5.35 (cli) (built: May  2 2016 23:27:49)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

## Subject
Deleting ACLs despite error when deleting an object.

php 5.5.35
OS: CentOS

I also used the ACLs.

When deleting a record, an error is generated.
"Can not delete or update a parent row: a foreign key constraint fails"

This is also correct.

However, it will delete all of the object ACLs.

Debt is the delete function in the \ Sonata \ Admin Bundle \ Admin \ Admin

It will be erased in all ACLs and then the data is trying to delete. Occurring an error, interrupts the script and provides the Acls not restore.

($ This-> getSecurityHandler () -> deleteObjectSecurity ($ this, $ object);)

`

public function delete ($ object)
{
        $ This-> Preremove ($ object);
        foreach ($ this-> extensions as $ extension)  {
            $ Extension-> Preremove ($ this, $ object);
        }
        $ This-> getSecurityHandler () -> deleteObjectSecurity ($ this, $ object);
        $ This-> getModelManager () -> delete ($ object);
        $ This-> postremove ($ object);
        foreach ($ this-> extensions as $ extension) {
            $ Extension-> postremove ($ this, $ object);
        }
}

`

**Comment by greg0ire** [comment]
Hi, sorry to break this news to you, but Sonata 2 is no longer supported. Please reopen if you still experience this with Sonata 3.
