### ISSUE TITLE
Decide what to do with unused id parameter

### ISSUE THREAD

**Issue by greg0ire** [sonata-project/SonataAdminBundle#3970]
Several actions ([CrudController::editAction](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Controller/CRUDController.php#L231), [CRUDController::showAction](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Controller/CRUDController.php#L584)) have an unused id parameter, a legacy kept for BC. We should decide what to do on next major.

Several possibilities : 
- drop the parameter
- introduce a childId parameter and remove the `getIdParameter` method, but then we would have to take `childId` when not null, `id` otherwise to get the current object id, which is not very handy
- @Soullivaneuh talked about `ParamConverter`s, can you please develop ?

**Comment by curry684** [comment]
Given that PHP silently ignores extra parameters and there are no plans to change that during 7.x lifetime keeping them around is far more harmful (it implies it should work, https://github.com/sonata-project/SonataAdminBundle/pull/3961) than removing (everything will keep working yet show IDE warnings to consumers).

**Comment by greg0ire** [comment]
It's indeed worth noting that in this particular case, the parameter can be removed [without causing BC-breaks](https://3v4l.org/0P8o3)

**Comment by greg0ire** [comment]
Thinking more about it, the `getIdParameter` was probably introduced because routes in a child admin use `id` and `childId`, while the could have used `parentId` and `id`.

**Comment by Soullivaneuh** [comment]
> @Soullivaneuh talked about ParamConverters, can you please develop ?

Having directly the object on the action parameters instead of the ID thanks to this:

But this has some inconvenient:

* This seems to require annotations enable. Have to see if we can use it without them.
* Not sure if we can use it for an not determined object type.

**Comment by greg0ire** [comment]
> This seems to require annotations enable. Have to see if we can use it without them
[Could be doable](https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/EventListener/ParamConverterListener.php#L58) by setting the `_converters` attribute of a request, but this feels ugly.

>    Not sure if we can use it for an not determined object type.

The param converter would have to know about the current admin to do that, so… why not.

Anyway, unless you're willing to work on this in the very near future, I propose to get rid of the parameter. It won't prevent you to add ParamConverters later if you want to.

**Comment by VincentLanglet** [comment]
@greg0ire Should we close this, thanks to https://github.com/sonata-project/SonataAdminBundle/pull/5807 ?
