### ISSUE TITLE
how do disabled csrf　for  one bundle not all bundle

### ISSUE THREAD

**Issue by wangpengpeng** [sonata-project/SonataAdminBundle#3987]
Question	  Answer
Bundle    version	sonata-project/admin-bundle 2.3.0
Symfony version	symfony/symfony v2.3.0
php version	PHP 5.6.20-3+donate.sury.org~trusty+1

namespace DWD\AdminBundle\Admin;

use Sonata\AdminBundle\Admin\Admin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;

use Sonata\AdminBundle\Route\RouteCollection;
use Sonata\AdminBundle\Validator\ErrorElement;
use Symfony\Component\Validator\ExecutionContextInterface;

class AppVersionAdmin extends BaseAdmin
{
    protected $classnameLabel = 'App版本';
    protected $baseRouteName = 'appversion';

    // Fields to be shown on create/edit forms
    protected function configureFormFields(FormMapper $formMapper)
    {
        $appversion = $this->getSubject();

        $originurl = $appversion->getUrl();
        if(!empty($originurl) &&  str_split($originurl,4)[0] != 'http'){
            $versionurl = $this->getImageFullUrl($originurl);
        }else{
            $versionurl  = $originurl;
        }

        $formMapper
            ->add('platform', 'choice', array('choices'=>array( 2=>'Android',1=>'iOS')))
            ->add('code')
            ->add('name')
            ->add('title')
            ->add('description')
//            ->add('url')
            ->add('url', 'dwd_admin_form_type_image', [
                'label' => 'appurl',
                'required' => $appversion->getId() ? false : true,
                'dwd_admin_form_type_image_preview_url' => $versionurl,
                'dwd_admin_form_type_image_size_limit' => 51200, //50MB
                'disabled' => false,
                'data_class'=> null,
//                'required' => true,
            ])
            ->add('force_update', 'checkbox', ['required' => false])
            ->add('enabled', 'checkbox', ['required' => false])
            ->setHelps(array(
            ))
        ;
    }

    // 选择图片上传组件
    public function getFormTheme() {
        return [
            'DWDAdminBundle:Form:file_upload.html.twig'
        ];
    }

    // Fields to be shown on filter forms
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('platform', 'doctrine_orm_choice', ['label' => "platform"], 'choice', [
                'choices' => [
                    2 => 'Android',
                    1 => 'iOS',
                ]])
            ->add('code')
            ->add('name')
        ;
    }

    // Fields to be shown on lists
    protected function configureListFields(ListMapper $listMapper)
    {
        $actions = [];

        if ($this->isGranted('EDIT')) {
            $actions += [
                'edit' => [],
            ];
        }

        $listMapper
//            ->addIdentifier('id')
            ->add('id')
            ->add('platform', 'choice', array('choices'=>array(1=>'iOS', 2=>'Android')))
            ->add('code')
            ->add('name')
            ->add('title')
            ->add('url', 'null', [
                'template' => 'DWDAdminBundle:CRUD:list_url.html.twig',
            ])
            ->add('force_update', 'boolean', ['editable' => true])
            ->add('enabled',      'boolean', ['editable' => true])
        ;

        if ($actions) {
            $listMapper->add('_action', 'actions', [
                'actions' => $actions,
            ]);
        }
    }

    public function prePersist($appconfig) {

        $uniqid = $this->getUniqid();
        $request_arr = $this->getRequest()->get($uniqid);

        $this->_prePersist( $appconfig, $request_arr );
    }

    public function _prePersist( $appconfig, $request_arr )
    {

        if (is_object($appconfig->getUrl()) ) {
            $key = $this->uploadFileToQiNiuOrigin($appconfig, $appconfig->getUrl());
            if( $key ) {
                $appconfig->setUrl($key);
            }
        }

    }

    public function preUpdate($object) {

        if (is_object($object->getUrl()) ) {
            $key = $this->uploadFileToQiNiuOrigin($object, $object->getUrl());
            if( $key ) {
                $object->setUrl($key);
            }
        }

        if (!empty($object->getId()) && is_null($object->getUrl()) ) {
            $em = $this->getDoctrine()->getManager();

            $uow = $em->getUnitOfWork();
            $data = $uow->getOriginalEntityData($object);
            $object->setUrl($data['url']);
        }
    }

    //继承的批量删除属性拿掉
    protected function configureRoutes(RouteCollection $collection)
    {
        $collection
            ->add('delete')
            ->add('batch_remove')
        ;
    }
}

namespace DWD\AdminBundle\Admin;

use Sonata\AdminBundle\Admin\Admin;
use Sonata\AdminBundle\Route\RouteCollection;

use DWD\DataBundle\Entity\Role;
use DWD\AdminBundle\Review\Handler as ReviewHandler;
use DWD\DataBundle\Entity\ReviewObject;
use DWD\DataBundle\Entity\ReviewQueue;

class BaseAdmin extends Admin
{
..............
}

**Comment by wangpengpeng** [comment]
i know how do disabled  ｔｈｉｓ csrf

**Comment by Soullivaneuh** [comment]
Open an issue with just bad copy/paste of code won't help at all.

Plus, GitHub is here for issue reporting, not general support. For that, please use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata).

More info: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md#issues

Regards.
