### ISSUE TITLE
Add possibility to create a dynamic action/route for identifiers in grid

### ISSUE THREAD

**Issue by Koc** [sonata-project/SonataAdminBundle#3989]
We have list of entities and some of them should go to edit and some to show (depends on isGranted call). Currently it is impossible because we set route when configuring list fields.

**Comment by Soullivaneuh** [comment]
Actually you can do that:

```php
protected function configureListFields(ListMapper $listMapper)
{
    $listMapper->addIdentifier('id', null, [
        'route_name' => $this->isGranted('YOUR_ROLE') ? 'role_route' : 'another_route',
    ]);
}
```

Is this what you're looking for?

**Comment by OskarStark** [comment]
i changed the issue title 😄

**Comment by Koc** [comment]
@Soullivaneuh I should call `$this->isGranted('YOUR_ROLE', $object)` for each item in grid.

**Comment by Soullivaneuh** [comment]
@Koc I don't think it should be the role of the `ListMapper`.

BTW, we are trying to reduce code size on the admin class and your request will do the reverse IMHO.

cc @greg0ire

**Comment by Soullivaneuh** [comment]
> I should call `$this->isGranted('YOUR_ROLE', $object)` for each item in grid.

BTW, if you have to add this check on multiple field, in this case just store the result on a variable before.

**Comment by greg0ire** [comment]
> BTW, if you have to add this check on multiple field, in this case just store the result on a variable before.

$object won't be the same between 2 iterations, so no.

> BTW, we are trying to reduce code size on the admin class and your request will do the reverse IMHO.

Will it ? @Koc didn't mention the admin class at all for the moment, did he ?

**Comment by Soullivaneuh** [comment]
> $object won't be the same between 2 iterations, so no.

What do you mean? How the object could change on `configureListFields`?

**Comment by Soullivaneuh** [comment]
> Will it ? @Koc didn't mention the admin class at all for the moment, did he ?

Indeed. The admin object is already on the `ListMapper`.

Still think it's not the role of this class IMHO.

**Comment by greg0ire** [comment]
> What do you mean? How the object could change on configureListFields?

IIUC he has a list, and wants to show an edit link for object in iteration 1, and a show link for object in iteration 2, which is not the same, right ?

**Comment by jvasseur** [comment]
@Soullivaneuh it would probably be something like this:
```php
protected function configureListFields(ListMapper $listMapper)
{
    $listMapper->addIdentifier('id', null, [
        'route_name' => function ($object) {
            return $this->isGranted('YOUR_ROLE', $object) ? 'role_route' : 'another_route';
        },
    ]);
}
```
the closure being executed for each row and the return value used as the route name.

**Comment by Soullivaneuh** [comment]
@jvasseur And what is the `$this` placed on the anonymous function?

After that yeah, it's an idea. :wink:

**Comment by Soullivaneuh** [comment]
But we have to be sur it will be useful.

If for most of case it's depends on the `isGranted` method, a ternary could be enough, could not be?

**Comment by greg0ire** [comment]
> IIUC he has a list, and wants to show an edit link for object in iteration 1, and a show link for object in iteration 2, which is not the same, right ?

Oh ok, `$this` can't change, I understand the misunderstanding now.

**Comment by jvasseur** [comment]
@Soullivaneuh `$this` is the admin class.

A closure is the best solution, it allows the most flexibility (you could need to do the check on an a property of object instead of an isGranted call).
