### ISSUE TITLE
Not working "required" attribute in select 2

### ISSUE THREAD

**Issue by nilov** [sonata-project/SonataAdminBundle#3993]
For fix it need update select2 to version 4. 

https://github.com/select2/select2/issues/128
https://github.com/select2/select2/issues/3824

I tried update select 2, but design is crashed. Maybe it's because of the admin LTE.

**Comment by Soullivaneuh** [comment]
> For fix it need update select2 to version 4.

Will not be done until next major. But you can update it manually thanks to #3988.

Please next time start by updating your PR body according to the GitHub template.
