### ISSUE TITLE
How i can cancelled remov object in preRemove?

### ISSUE THREAD

**Issue by nkl90** [sonata-project/SonataAdminBundle#3994]
Hello, when before delete object I check some conditionsns in preRemove hook. And if object can not be removed in preRemove hook, cancelled remove. How I cancelled remove in preRemove hook?

**Comment by nkl90** [comment]
I override delete method in my admin class. 
`public function delete($object) {
		$preRemoveResult = $this->preRemove($object);
		if($preRemoveResult instanceof RedirectResponse){
			return $preRemoveResult;
		}
        parent::delete($object);
	}
	
	public function preRemove($object) {
		/*$pollService = $this->getConfigurationPool()->getContainer()->get('intell.polling');
		foreach($object->getBetLink() as $betLink){
			
		}
		
		die();*/
		//die();
		$this->getRequest()
			->getSession()
			->getFlashBag()
			->add('warning', _('My flashBag!!!'));
		return new RedirectResponse('url');
	}`

Its fine work. But! I dont understand, where does an flash_delete_success message in flashBag array???

**Comment by Soullivaneuh** [comment]
GitHub issue trackers is for bug or feature request. Please use Stack-overflow for questions.

More info: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md#issues

**Comment by panique** [comment]
@nkl90 same problem here, 3 years later :/ PLEASE sonataAdminBundle people, fix this broken piece of software!

**Comment by panique** [comment]
@nkl90 same problem here, 3 years later :/ sonatadminbundle delete-stuff is totally broken and compleltely undocumented :/ what a pity, such a great project but unusable.

**Comment by phansys** [comment]
@panique, if you think there is an issue with some feature exposed by this package, please bring us your support providing the required details, using the issue template. That would be a huge step forward to know the origin of any problem.
Check the related docs for any question: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md#issues.

Thank you in advance!
