### ISSUE TITLE
Display "[Protected]" in configureFormFields for a  parent variable as $email in UserEntity from FosUserBundle 

### ISSUE THREAD

**Issue by delphimat** [sonata-project/SonataAdminBundle#4001]
### Environment

Unbuntu 14 LTS. Nginx

#### Sonata packages
sonata-project/admin-bundle              3.4.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.1.0 Symfony SonataBlockBundle
sonata-project/cache                     1.0.7 Cache library
sonata-project/core-bundle               3.0.3 Symfony SonataCoreBundle
sonata-project/doctrine-extensions       1.0.2 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.0.5 Symfony Sonata / Inte ...to the SonataAdminBundle
sonata-project/exporter                  1.5.0 Lightweight Exporter library

#### Symfony packages

symfony/assetic-bundle     v2.7.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.8.2  Symfony MonologBundle
symfony/polyfill-apcu      v1.2.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.2.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.2.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v2.8.8  The Symfony PHP framework

#### PHP version

php7.0-fpm 

## Subject

Hello the community, i have an issue that i dont success to resolve. ( has been working the whole day).

So  the problem is.

I dont success to display the value "email" of my entity User which extend the Base user of the FosUserBundle but this only in the production server. The problem doest appear on my boths laptop for the developpement
.
Concretely if i want to display the value of the email for the entity User in my method

"configureFormFields" of the OrganisationUserAdmin.php.

```
 protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->with('Donner les droits sur l\'Organisation' , array('class' => 'col-md-12'))
            ->add('user', EntityType::class , array(
                'label'     => "Choisir un utilisateur Gagnao",
                'class'     => 'Gagnao\Bundle\CoreBundle\Entity\GagnaoUser',
                'multiple'  => false,
                'required'  => true,
                'choice_label' => function ($user) {
                    return $user->getIdName();
                }))
            ->end()
        ;
    }
```

IN GagnaoUser {
```
 /**
     * @return string
     */
    public function getIdName()
    {
        return $this->getId().': '.$this->getEmail();
    }
}
```

The page load perfectly without any error.
But the value of the select is wrong. 

It is write that the getEmail() return a Protected, and then some javascript error message.

The result display is the form should be the ID + email and now i get the ID and [PROTECTED email]@
I believe that the  there is a little problem with the extends and sonata admin but i dont know where and how. 
I checked the composer show -i of my both environnement there are similar (the environnement which work perfectly and the production environnement)
![code](https://cloud.githubusercontent.com/assets/1278245/16844074/face2394-49e3-11e6-9aca-ffff2937c860.png)
![email_protected](https://cloud.githubusercontent.com/assets/1278245/16844075/fad1b374-49e3-11e6-9e1f-602bb9609e8e.png)

<span class="select2-chosen" id="select2-chosen-2">

Which normaly should be only 

The problem is this happened only on my production serveur. There is no problem on the 2 other machines use for develop the solution.

I did some screen shot to try to show and explain in a better way what is my problem.

## Steps to reproduce

Try to display the value of an entity User which expend BaseUser from FosUserBundle

## Expected results

```
<span class="select2-chosen" id="select2-chosen-2"> 
204 : toto@gmail.com
</span>

```

## Actual results
```

`204: [email&nbsp;protected]/* &lt;![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&amp;&amp;(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]&gt; */`

</span>
```
```

```

**Comment by greg0ire** [comment]
>  then some javascript error message.

That's not a javascript error message, that's a script! Can you check your database directly, and tell us if the `email` column also has these weird content?

**Comment by delphimat** [comment]
Hello Grégoire  first I need to thank you for your answer.
You give me a hint for solve this problem.
Unfortunately I'm in holidays this week, i will go back next week on the problem 
Then I will let you know if I find the weird content in the database.
And purhaps we will find the solution.
Thanks again .

**Comment by delphimat** [comment]
Hello gregoire.

I did check in the database for the column email, username, email_canonical_ username_canonical.
I dont see anything weird,  with a normal select on the shell from psql.
I see regular information. 
Do you have an other tips purhaps ?

**Comment by greg0ire** [comment]
Can you look at the exact output (view source) ? This output looks a bit like the output of `var_dump`. See for yourself : 

```
Interactive mode enabled

php > class A { protected $email; }
php > var_dump(new A());
object(A)#1 (1) {
  ["email":protected]=>
  NULL
}
```

**Comment by delphimat** [comment]
i'm not sure to have completely understand.

but i got the source of the page html; maybe can help.

`Choisir un utilisateur Gagnao
</label>
<div class="sonata-ba-field sonata-ba-field-standard-natural">
<select id="s57a0600f00fc4_user" name="s57a0600f00fc4[user]" class=" form-control"><option value="222">222: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="5f2a2c383a312b36333326352a3b301f302d3e31383a71392d">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="208">208: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="ccb9bfe2aba9a2b8a5a0a0b58cbbada2ada8a3a3e2aabe">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="210">210: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="87e6f2e3e2a9e3e8f5f3efe8c7e0eae6eeeba9e4e8ea">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="216">216: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="7b19551814031418171a091a3b1c161a121755181416">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="220">220: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="7f15130a1c51180d1e111b151a1e113f18121e1613511c1012">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="206">206: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="4f253a23262a103f203d3b2e230f27203b222e2623612c2022">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="204">204: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="5128303f3822113630363f303e7f3723">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="219">219: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="0a7e7e657e657e654a6d6b6d646b65246c78">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="213">213: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="c3a4a6b0b083a4a2a4ada2acedacb1a4">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="214">214: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="54272031243c353a31143335333a353b7a3b2633">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="215">215: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="dfacbaacbae6e8edecec9fb8b2beb6b3f1bcb0b2">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="202">202: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="791d1c150911105714180d391e14181015571a1614">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="209">209: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="700011040219131b5e12111c1405151e113007111e11141f1f5e1602">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="223">223: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="2d445e594c434f58415e40546d4a404c4441034e4240">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="224">224: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="ea938b848399d3deaa8d8b8d848b85c48c98">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="211">211: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="0661736f6a6a67736b632863757046697467686163286074">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="221">221: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="f5808692909b819c99998c939a9a81b59a87949b9290db9387">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="218">218: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="c6a4b4afa5a3e8b0afa8a5a386a1aba7afaae8a5a9ab">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="217">217: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="e7828bb8838e838eded0d5a78f88938a868e8bc984888a">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="203">203: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="bfd2decbd7d6dacaffd8ded8d1ded091d9cd">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option><option value="225">225: <a class="__cf_email__" href="/cdn-cgi/l/email-protection" data-cfemail="c1a2a4a5b3a8a2ecada4a3a8a9a0af81a5a3aca0a8adefa2aeac">[email&#160;protected]</a><script data-cfhash='f9e31' type="text/javascript">/* <![CDATA[ */!function(t,e,r,n,c,a,p){try{t=document.currentScript||function(){for(t=document.getElementsByTagName('script'),e=t.length;e--;)if(t[e].getAttribute('data-cfhash'))return t[e]}();if(t&&(c=t.previousSibling)){p=t.parentNode;if(a=c.getAttribute('data-cfemail')){for(e='',r='0x'+a.substr(0,2)|0,n=2;a.length-n;n+=2)e+='%'+('0'+('0x'+a.substr(n,2)^r).toString(16)).slice(-2);p.replaceChild(document.createTextNode(decodeURIComponent(e)),c)}p.removeChild(t)}}catch(u){}}()/* ]]> */</script></option></select>


I try to find more information, `

**Comment by delphimat** [comment]
i tried to show the html code, but he has been interpreted by github; even with the  < > "insert code"

**Comment by greg0ire** [comment]
> i tried to show the html code, but he has been interpreted by github; even with the < > "insert code"

I fixed that.

**Comment by delphimat** [comment]
![Uploading source code.png…]()

**Comment by delphimat** [comment]
![source code](https://cloud.githubusercontent.com/assets/1278245/17323069/ba75b3fe-58a0-11e6-8bf6-1d775d913ad8.png)

**Comment by delphimat** [comment]
![source code](https://cloud.githubusercontent.com/assets/1278245/17323104/f1c688a6-58a0-11e6-9f9f-c3d6c4819839.png)

**Comment by greg0ire** [comment]
I think you have some kind of javascript script that "protects" email addresses (so nothing to do with `var_dump`). Nothing to do with Sonata, closing.

**Comment by delphimat** [comment]
ahhh ok thanks

**Comment by delphimat** [comment]
i believe it's cloudflare.
