### ISSUE TITLE
Error in calculating the width of .form-action.well.stuck

### ISSUE THREAD

**Issue by soerenbernstein** [sonata-project/SonataAdminBundle#4009]
As I understand the width for the stuck class is calculated by a script from AdminLTE, but the result - at least for me - is, that the div.form-action.well.stuck will be to wide, so that the right side will be outside the viewport.

Ignoring the calculated width and using css istead solve the problem for me. the following css is what I came up with to get the right width, positioning and transition for the stucked well, although the left: 230px should actually be dependend on the width of the main-sidebar:

```
.sonata-bc .form-actions.well {
    width: 100% !important;
}

.sonata-bc .form-actions.stuck {
    position: fixed;
    left: 230px;
    right: 0;
    bottom: 0;
    width: auto !important;
    margin-left: -5px;
    margin-right: -5px;
    margin-bottom: 0;
    z-index: 5;
    border-radius: 0;
    -webkit-transition: left .3s ease-in-out, width .3s ease-in-out;
    -moz-transition: left .3s ease-in-out, width .3s ease-in-out;
    -o-transition: left .3s ease-in-out, width .3s ease-in-out;
    transition: left .3s ease-in-out, width .3s ease-in-out;
}

@media (min-width: 768px) {
    .sonata-bc.sidebar-collapse .form-actions.stuck {
        left: 0;
    }
}
```

**Comment by core23** [comment]
Please use the issue template. Feel free to create a PR with a fix, if this is a bug.

**Comment by jordisala1991** [comment]
No answer since 2016, hard to know if this is an issue on our side (or an issue at all).

Closing for now. If you still have this issue and want to reopen. Please ping me and fill the issue template properly. Maybe a few screenshots would be nice in this case.
