### ISSUE TITLE
Consider refactoring the registerFormMapping() feature

### ISSUE THREAD

**Issue by javiereguiluz** [sonata-project/SonataAdminBundle#4019]
- The other day I was profiling step-by-step a Symfony application that uses SonataAdmin for the backend.
- That's why I realized that the `boot()` method of SonataAdminBundle ([here](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/SonataAdminBundle.php#L40)), SonataCoreBundle ([here](https://github.com/sonata-project/SonataCoreBundle/blob/3.x/SonataCoreBundle.php#L38)) and SonataBlockBundle ([here](https://github.com/sonata-project/SonataBlockBundle/blob/3.x/SonataBlockBundle.php#L36)) are not empty.
- Adding code to the `boot()` method is extremely discouraged for bundles because it may impact app performance significantly (it's executed for every request!)
- I wonder if you could refactor this feature to not have to execute any code in the `boot()` method.

Thanks!

**Comment by greg0ire** [comment]
Does the git history explain the rationale behind this?

**Comment by greg0ire** [comment]
Btw do you mean "debugging" or really "profiling". If profiling, did you indeed notice significant overhead?

**Comment by greg0ire** [comment]
> Does the git history explain the rationale behind this?

To answer my own question, I think there is an explanation for that right here : https://github.com/sonata-project/SonataCoreBundle/blob/master/Resources/doc/reference/form_types.rst

I think this can safely be removed when dropping support for symfony < 2.8 . What do you think @sonata-project/contributors ?

**Comment by javiereguiluz** [comment]
I'm closing this super old issue because it's probably no longer relevant. New profiling should be done on newer Sonata versions and new issues should be created if needed. Thanks!
