### ISSUE TITLE
Add priority for admin extensions

### ISSUE THREAD

**Issue by hason** [sonata-project/SonataAdminBundle#4036]
I want to register a global admin extension as the last extension.

**Comment by greg0ire** [comment]
Doesn't the order in which you declare the extension services help you do just that?

**Comment by hason** [comment]
No. The problem is in https://github.com/sonata-project/SonataAdminBundle/blob/3.x/DependencyInjection/Compiler/ExtensionCompilerPass.php#L62-L73 The universal extensions are registered as the first, and custom extensions as the second. Furthermore, universal extensions are not sorted. I suggest this enhancement:

```php
$extensions = $universalExtensions; // [ priority1 => [...], priority2 => [...]]
$extensions = merge($extension, $this->getExtensionsForAdmin($id, $admin, $container, $extensionMap);
krsort($extensions);
$extensions = call_user_func_array('array_merge', $extensions);

foreach ($extensions as $extension) {
    $admin->addMethodCall('addExtension', array(new Reference($extension)));
}
```

**Comment by greg0ire** [comment]
Do you really care about the order, or would you rather establish dependencies between extensions (that is, all you want is extension A to be executed before extension B)?

**Comment by greg0ire** [comment]
This could be implemented like [ordered fixtures](https://github.com/doctrine/data-fixtures/blob/11d238580b33a2c9c01d18f22163a7d3d18f4bb0/lib/Doctrine/Common/DataFixtures/Loader.php#L208) are, maybe?

**Comment by OskarStark** [comment]
Sometimes the order is important 

A getOrder() Method could be very helpful

**Comment by hason** [comment]
I prefer set order in DI. This is the standard method - http://symfony.com/doc/current/reference/dic_tags.html. Tags with priority:
- `twig.loader`
- `kernel.cache_warmer`
- `data_collector`
- `serializer`
- ...

We can use a trait https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Compiler/PriorityTaggedServiceTrait.php

**Comment by greg0ire** [comment]
:+1: @hason , that would be mean a lot less code. Less is more. Are you planning on making a PR?

**Comment by OskarStark** [comment]
indeed, great idea @hanson 👍
