### ISSUE TITLE
Tree view?

### ISSUE THREAD

**Issue by Padam87** [sonata-project/SonataAdminBundle#4039]
Hi,

I see some evidence of a tree view in the code and issues, but can't figure out if it is usable, just a remnant, or perhaps a new feature.

What is the status of the tree view? Is it documented?

Thanks,
Adam

**Comment by greg0ire** [comment]
Maybe you can try to find the authors with the git history and ping them? I think I might have used this with the phpcr bundle, a long time ago.

**Comment by OskarStark** [comment]
There is no tree view which can be used by default in all admins, but you can have a look at the PageBundle an implement it for your own needs

**Comment by Padam87** [comment]
For anyone interested in this issue, take a look at this: https://github.com/redco/sonata-admin-tree-bundle

Works with gedmo's nested set, and can be adapted to work with sortable too. It was perfect for my needs, maybe it will help someone else too.
