### ISSUE TITLE
Filter error when adding a manyToOne relation 

### ISSUE THREAD

**Issue by victordevaid** [sonata-project/SonataAdminBundle#4052]
#### Sonata packages

sonata-project/admin-bundle              3.4.0              The missing Symfony Admin Generator
sonata-project/block-bundle              3.1.1              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               3.0.3              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2                Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.x-dev f7e221d    Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10             Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.6.0              Lightweight Exporter library
sonata-project/formatter-bundle          3.x-dev 28c79f0    Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2              Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               dev-master b68df5e Symfony SonataIntlBundle
sonata-project/user-bundle               3.x-dev 7bfbe5e    Symfony SonataUserBundle
#### Symfony packages

symfony/asset                            v3.0.9             Symfony Asset Component
symfony/assetic-bundle                   dev-master aa5b4f8 Integrates Assetic into Symfony2
symfony/class-loader                     v3.0.9             Symfony ClassLoader Component
symfony/config                           v2.8.9             Symfony Config Component
symfony/console                          v2.8.9             Symfony Console Component
symfony/debug                            v2.8.9             Symfony Debug Component
symfony/debug-bundle                     3.1.x-dev 995b9d7  Symfony DebugBundle
symfony/dependency-injection             v2.8.9             Symfony DependencyInjection Component
symfony/doctrine-bridge                  v3.1.3             Symfony Doctrine Bridge
symfony/event-dispatcher                 v3.0.9             Symfony EventDispatcher Component
symfony/expression-language              v3.1.3             Symfony ExpressionLanguage Component
symfony/filesystem                       v3.0.9             Symfony Filesystem Component
symfony/finder                           v3.0.9             Symfony Finder Component
symfony/form                             v2.8.9             Symfony Form Component
symfony/framework-bundle                 v2.8.9             Symfony FrameworkBundle
symfony/http-foundation                  v2.8.9             Symfony HttpFoundation Component
symfony/http-kernel                      v2.8.9             Symfony HttpKernel Component
symfony/intl                             v3.0.9             A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/monolog-bridge                   v3.1.3             Symfony Monolog Bridge
symfony/monolog-bundle                   dev-master 7da68be Symfony MonologBundle
symfony/options-resolver                 v2.8.9             Symfony OptionsResolver Component
symfony/phpunit-bridge                   v3.1.3             Symfony PHPUnit Bridge
symfony/polyfill-intl-icu                v1.2.0             Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring                v1.2.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php54                   v1.2.0             Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55                   v1.2.0             Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56                   v1.2.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70                   v1.2.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                    v1.2.0             Symfony utilities for portability of PHP codes
symfony/process                          v3.1.3             Symfony Process Component
symfony/property-access                  v3.0.9             Symfony PropertyAccess Component
symfony/routing                          v3.0.9             Symfony Routing Component
symfony/security                         v2.8.9             Symfony Security Component
symfony/security-acl                     v3.0.0             Symfony Security Component - ACL (Access Control List)
symfony/security-bundle                  v2.8.9             Symfony SecurityBundle
symfony/stopwatch                        v3.0.9             Symfony Stopwatch Component
symfony/swiftmailer-bundle               dev-master d8d7ca2 Symfony SwiftmailerBundle
symfony/templating                       v3.0.9             Symfony Templating Component
symfony/translation                      v2.8.9             Symfony Translation Component
symfony/twig-bridge                      v3.1.3             Symfony Twig Bridge
symfony/twig-bundle                      3.1.x-dev fb00a91  Symfony TwigBundle
symfony/validator                        v3.1.3             Symfony Validator Component
symfony/var-dumper                       v3.1.3             Symfony mechanism for exploring and dumping PHP variables
symfony/web-profiler-bundle              3.0.x-dev 27f53ac  Symfony WebProfilerBundle
symfony/yaml                             v3.1.3             Symfony Yaml Component
#### PHP version

PHP 5.6.19
## Subject

When I try to use a filter with a ManyToOne relation, it returns an error.
## Steps to reproduce

If I add a filter with a ManyToOne relation and I dont specify the widget type, it returns an error. An example would be the:

protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('company')
        ;
    }

With company being a ManyToOne relation with the admin entity.
## Expected results

The filter working as a selector.
## Actual results

The page return the following error:

Notice: Undefined index: entity
## How to make it work

It works when you put the widget like this:

``` php
protected function configureDatagridFilters(DatagridMapper $datagridMapper)
{
        $datagridMapper
            ->add('company',null,array(),'Symfony\Bridge\Doctrine\Form\Type\EntityType')
        ;
}
```

**Comment by greg0ire** [comment]
Can you provide a stack trace?

**Comment by victordevaid** [comment]
Stack Trace:

    Symfony\Component\Debug\Exception\ContextErrorException:` Notice: Undefined index: entity
    at n/a
        in /var/www/git/contractors/vendor/symfony/form/FormRegistry.php line 103

    at Symfony\Component\Debug\ErrorHandler->handleError('8', 'Undefined index: entity', '/var/www/git/contractors/vendor/symfony/form/FormRegistry.php', '103', array('name' => 'entity', 'type' => object(EntityType), 'extension' => object(DependencyInjectionExtension)))
        in /var/www/git/contractors/vendor/symfony/form/FormRegistry.php line 103

    at Symfony\Component\Form\FormRegistry->getType('entity')
        in /var/www/git/contractors/vendor/symfony/form/FormFactory.php line 107

    at Symfony\Component\Form\FormFactory->createNamedBuilder('value', 'entity', null, array('required' => false, 'class' => 'AppBundle\Entity\Company'))
        in /var/www/git/contractors/vendor/symfony/form/FormBuilder.php line 106

    at Symfony\Component\Form\FormBuilder->create('value', 'entity', array('required' => false, 'class' => 'AppBundle\Entity\Company'))
        in /var/www/git/contractors/vendor/symfony/form/FormBuilder.php line 269

    at Symfony\Component\Form\FormBuilder->resolveChildren()
        in /var/www/git/contractors/vendor/symfony/form/FormBuilder.php line 215

    at Symfony\Component\Form\FormBuilder->getForm()
        in /var/www/git/contractors/vendor/symfony/form/FormBuilder.php line 221

    at Symfony\Component\Form\FormBuilder->getForm()
        in /var/www/git/contractors/var/cache/dev/classes.php line 12158

    at Sonata\AdminBundle\Datagrid\Datagrid->buildPager()
        in /var/www/git/contractors/var/cache/dev/classes.php line 12262

    at Sonata\AdminBundle\Datagrid\Datagrid->getForm()
        in /var/www/git/contractors/vendor/sonata-project/admin-bundle/Controller/CRUDController.php line 105

    at Sonata\AdminBundle\Controller\CRUDController->listAction()
        in  line 

    at call_user_func_array(array(object(CRUDController), 'listAction'), array())
        in /var/www/git/contractors/vendor/symfony/http-kernel/HttpKernel.php line 144

    at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), '1')
        in /var/www/git/contractors/vendor/symfony/http-kernel/HttpKernel.php line 64

    at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), '1', true)
        in /var/www/git/contractors/vendor/symfony/http-kernel/DependencyInjection/ContainerAwareHttpKernel.php line 69

    at Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(object(Request), '1', true)
        in /var/www/git/contractors/vendor/symfony/http-kernel/Kernel.php line 185

    at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
        in /var/www/git/contractors/web/app_dev.php line 30

**Comment by victordevaid** [comment]
The error is that 'entity' is not a valid key for $types array in Symfony\Component\Form\FormRegistry in line 103. When you dump the keys for $types, they all look like 'Symfony\Bridge\Doctrine\Form\Type\EntityType', the full class name of every type. 

On the other side, there is a method called registerFormMapping() in Sonata\CoreBundle\SonataCoreBundle , wich looks like is mapping the widget names like 'entity' to the full qualified name  'Symfony\Bridge\Doctrine\Form\Type\EntityType'. And if you add a 'entity' type to the FormBuilder in the configureFormFields() method, it works allright.

So my guess is that when you add an 'entity' widget to the FormBuildler, it searchs the fully qualified name in this mapping, but in the DatagridMapper it doesnt do the same.

**Comment by victordevaid** [comment]
Here are all the keys for the $types array in FormRegistry Class:

```
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\HiddenType"
"hidden"
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\HiddenType"
"hidden"
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\HiddenType"
"hidden"
"Sonata\AdminBundle\Form\Type\Filter\DefaultType"
"sonata_type_filter_default"
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\HiddenType"
"hidden"
"Sonata\AdminBundle\Form\Type\Filter\DefaultType"
"sonata_type_filter_default"
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\HiddenType"
"hidden"
"Sonata\AdminBundle\Form\Type\Filter\DefaultType"
"sonata_type_filter_default"
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\HiddenType"
"hidden"
"Sonata\AdminBundle\Form\Type\Filter\DefaultType"
"sonata_type_filter_default"
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\HiddenType"
"hidden"
"Sonata\AdminBundle\Form\Type\Filter\DefaultType"
"sonata_type_filter_default"
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\HiddenType"
"hidden"
"Sonata\AdminBundle\Form\Type\Filter\DefaultType"
"sonata_type_filter_default"
"Symfony\Component\Form\Extension\Core\Type\ChoiceType"
"choice"
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\HiddenType"
"hidden"
"Sonata\AdminBundle\Form\Type\Filter\DefaultType"
"sonata_type_filter_default"
"Symfony\Component\Form\Extension\Core\Type\ChoiceType"
"choice"
"Sonata\CoreBundle\Form\Type\EqualType"
"sonata_type_equal"
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\HiddenType"
"hidden"
"Sonata\AdminBundle\Form\Type\Filter\DefaultType"
"sonata_type_filter_default"
"Symfony\Component\Form\Extension\Core\Type\ChoiceType"
"choice"
"Sonata\CoreBundle\Form\Type\EqualType"
"sonata_type_equal"
"Symfony\Component\Form\Extension\Core\Type\FormType"
"form"
"Symfony\Component\Form\Extension\Core\Type\HiddenType"
"hidden"
"Sonata\AdminBundle\Form\Type\Filter\DefaultType"
"sonata_type_filter_default"
"Symfony\Component\Form\Extension\Core\Type\ChoiceType"
"choice"
"Sonata\CoreBundle\Form\Type\EqualType"
"sonata_type_equal"
"Symfony\Bridge\Doctrine\Form\Type\EntityType"
```
Its strage, but all other widgets have both their shortname and full quallyfied name as keys in the array, only 'entity' widget has only the fullname.

**Comment by greg0ire** [comment]
Specifying `entity` is the old way to do things in Symfony. The new way is specifying the FQCN like you did. I think the type guesser resolves to `entity` instead of the FQCN.

**Comment by greg0ire** [comment]
Can you try changing [this line](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/Guesser/FilterTypeGuesser.php#L52)?

**Comment by victordevaid** [comment]
Yeah, that works:

$options['field_type'] = 'Symfony\Bridge\Doctrine\Form\Type\EntityType';

**Comment by greg0ire** [comment]
Glad to read that! Would you kindly submit a pull request to fix this?

**Comment by dmarkowicz** [comment]
Fixed in https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/621

**Comment by greg0ire** [comment]
Thanks @dmarkowicz !
