### ISSUE TITLE
Form LocalStorage with GarlicJS

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#4057]
Ref: http://garlicjs.org/#demonstration

The idea is to use this library to persist form data onto the browser thanks to LocalStorage.

With that, you can refresh the page or go somewhere else without losing anything you typed, even you didn't submit the data.

This should be proposed as an option, activated by default. If activated, the warning message about losing data should be removed.

What do you think?

**Comment by greg0ire** [comment]
I think that the warning message about losing data triggers way more than it should, to the point that my client was overjoyed when I finally took the time to disable it. Using local storage would also prevent data loss, but would be way less obnoxious (not obnoxious at all, in fact)
