### ISSUE TITLE
Find a better way for "actions" menu

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#4066]
Introducing the method `AbstractAdmin::configureActionButtons` was a bad idea, because we have no control what items will be generated in the templates. This should be reverted asap. 

We should use the knp `ItemInterface` instead, because we use this for every dynamic menu (e.g. the tab menu). This would also help to display all actions associated to an admin in the [dynamic dropdown menu](https://github.com/sonata-project/SonataAdminBundle/pull/4020).

``` php
     # CustomAdmin.php

     protected function configureActionMenu(MenuItemInterface $menu, $action)
     {
     //...
     }
```

The big problem is to supply a BC solution without displaying duplicate menu items.

**Comment by VincentLanglet** [comment]
Closing due to lack of interest
