### ISSUE TITLE
Preselect filter operator in list view

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#4068]
### Environment

| Question | Answer |
| --- | --- |
| Bundle version | 3.4.0 |
| Symfony version | 2.8.4 |
| php version | 5.6 |
## Steps to reproduce

Open a list view and click on advanced filters
## Expected results

The operator choice list should show (left input field), which operator is used in the filtered list.

![bildschirmfoto 2016-08-21 um 09 44 02](https://cloud.githubusercontent.com/assets/3440437/17835991/d33c50e0-6783-11e6-9788-0d767455aaad.PNG)
## Actual results

The operator list shows an empty value, but internal uses some default operator.

![bildschirmfoto 2016-08-14 um 13 22 48](https://cloud.githubusercontent.com/assets/3440437/17648792/95210d52-6222-11e6-9124-f3ff7e4b6c94.PNG)

**Comment by jordisala1991** [comment]
This should be easy, we should just put the first option as the selected, or avoid creating empty options
