### ISSUE TITLE
Short breadcrumbs

### ISSUE THREAD

**Issue by zhil** [sonata-project/SonataAdminBundle#407]
Is it possible to make breadcrumbs more short?
I mean, right now it looks like
<pre>
Dashboard / Home Slider Item / Home Slider Item Create 
</pre>

Thats why I need to create tons of the entries in translations. Is it possible to generate simple breadcrumbs like
<pre>
Dashboard / Home Slider Item / Create 
</pre>

**Comment by core23** [comment]
Refs https://github.com/sonata-project/SonataAdminBundle/pull/2286

**Comment by OskarStark** [comment]
@zhil you can control this via the translations
