### ISSUE TITLE
Remove translation from admin class

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#4072]
We should remove the `translator` and all of it's child methods like `AbstractAdmin::trans` from the admin. We should use twig template or the `CRUDController` instead.

This modification should be done with BC for the stable branch and removed with the next major release

Refs https://github.com/sonata-project/SonataAdminBundle/issues/3947

**Comment by greg0ire** [comment]
Big :+1: for this, it will remove one more responsibility from the admin
