### ISSUE TITLE
Image preview on edit form

### ISSUE THREAD

**Issue by zhil** [sonata-project/SonataAdminBundle#408]
I have an entity with screenshotFile field.
How can I configure FormFields, so there will be custom field for current screenshot preview on edit page?

Thanks in advance for help :)

**Comment by blaues0cke** [comment]
Just posted a "clean" solution for symfony3 for this problem: http://stackoverflow.com/questions/11366278/how-to-display-the-current-picture-above-the-upload-field-in-sonataadminbundle/42158303#42158303
