### ISSUE TITLE
Remove form theme from CRUDController / Admin

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#4088]
The form theme is a UI element which should be handled in the twig templates only. 
- [ ] Remove `setFormTheme` and `getFormTheme` from `AbstractAdmin`
- [ ] Remove `setTheme` from `CRUDController`

This modification should be done with BC for the stable branch and removed with the next major release

Refs #3947

**Comment by VincentLanglet** [comment]
What would be the replacement @core23 ?

**Comment by core23** [comment]
As mentioned in this issue, the theme should be set / hardcoded inside the twig templates.

All form theme related methods should be removed from the php classes.

**Comment by VincentLanglet** [comment]
Since the twig option https://symfony.com/doc/current/form/form_themes.html#applying-themes-to-all-forms can still be use (isn't it), it should make sens to ask the developer to use form_theme the same way it use it for his own forms.
