### ISSUE TITLE
Remove security checks from admin

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#4095]
The admin class should be used for admin configuration. All security checks like `hasAccess` or `isGranted` should be moved to the `CRUDController`

This modification should be done with BC for the stable branch and removed with the next major release

Refs #3947

**Comment by greg0ire** [comment]
I think there should be a dedicated, unit-tested service, but the `CRUDController` could proxy to it, so that we keep the controllers skinny.

**Comment by Soullivaneuh** [comment]
Same thing here. This can be done with BC. Deprecation, etc...

**Comment by fbourigault** [comment]
I will have a look at this. Stay tuned ;)
