### ISSUE TITLE
Remove router from admin

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#4096]
A default admin doesn't need any routing information. All routing methods should be moved to a separate RoutingService to reduce the methods in the admin. If a user wants to create some routes (e.g. in the tab or action menu), it should be injected in the constructor or via a setter method.

This modification should be done with BC for the stable branch and removed with the next major release

Refs #3947

**Comment by Soullivaneuh** [comment]
Please don't always target major for moving/removing feature from an admin.

**Comment by Soullivaneuh** [comment]
Please don't always target major for moving/removing feature from an admin.

All modifications should be done with a BC way as possible.
