### ISSUE TITLE
FormMapper used with FormBuilderInterface require type not to be null

### ISSUE THREAD

**Issue by fbourigault** [sonata-project/SonataAdminBundle#4100]
When calling `FormMapper::add()` with a `FormBuilderInterface` as name, underlying `FormContractor` complains about missing type. Should `FormMapper::add` have something like this as the `FormBuilderInterface` holds the type:

```php
if ($name instanceof FormBuilderInterface && $type == null) {
    $fieldDescriptionOptions['type'] = get_class($name->getType()->getInnerType());
}
```

If it's ok, I will do a PR.

**Comment by greg0ire** [comment]
Sure, it would be a sensible thing to do. Please do submit a PR

**Comment by fbourigault** [comment]
Against which branch?

**Comment by greg0ire** [comment]
Always submit PR to 3.x, unless there is a BC-break and the PR has a BC counterpart that prepares for it. This is completely BC IMO : people will no longer be obliged to submit a type but will still be able to.
