### ISSUE TITLE
Create batch edit form

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#4105]
It would be nice if we can find a way to edit multiple items with one edit page. 

For example if you want to change the tags of multiple pages. You have to create a custom batch action with a custom form. This needs to be done for every entity. Instead we should introduce something like `configureBatchFormFields`.

We could implement this after merging https://github.com/sonata-project/SonataAdminBundle/pull/4103 to have a clean starting point.

**Comment by core23** [comment]
I've starting working on something, but it's early WIP at the moment: https://github.com/core23/SonataAdminBundle/commits/feature-batch-edit

**Comment by Koc** [comment]
Relates to #3433

**Comment by grekpg** [comment]
And what about configureBatchFormFields ?

**Comment by core23** [comment]
Sorry, I'm not working on this anymore. Feel free to pickup this feature.

**Comment by VincentLanglet** [comment]
Closing due to lack of interest
