### ISSUE TITLE
The service "sonata.admin.breadcrumbs_builder" has a dependency on a non-existent parameter "sonata.admin.configuration.breadcrumbs"

### ISSUE THREAD

**Issue by locs31** [sonata-project/SonataAdminBundle#4111]
Hi i just update my composer with latest sonata admin bundle release and now i've got this error message. Someone get this also?

```
ParameterNotFoundException in ParameterBag.php line 106: The service "sonata.admin.breadcrumbs_builder" has a dependency on a non-existent parameter "sonata.admin.configuration.breadcrumbs". Did you mean one of these: "sonata.admin.configuration.templates", "sonata.admin.configuration.admin_services", "sonata.admin.configuration.dashboard_groups", "sonata.admin.configuration.sort_admins"?
```

**Comment by greg0ire** [comment]
@locs31 , can you provide a whole stack trace? 
@cassianotartari , can you help?

**Comment by locs31** [comment]
Yes the stack trace is : 
`


    in ParameterBag.php line 106
    at ParameterBag->get('sonata.admin.configuration.breadcrumbs') in ParameterBag.php line 232
    at ParameterBag->resolveString('%sonata.admin.configuration.breadcrumbs%', array()) in ParameterBag.php line 203
    at ParameterBag->resolveValue('%sonata.admin.configuration.breadcrumbs%', array()) in ParameterBag.php line 193
    at ParameterBag->resolveValue(array('%sonata.admin.configuration.breadcrumbs%')) in ResolveParameterPlaceHoldersPass.php line 39
    at ResolveParameterPlaceHoldersPass->process(object(ContainerBuilder)) in Compiler.php line 117
    at Compiler->compile(object(ContainerBuilder)) in ContainerBuilder.php line 614
    at ContainerBuilder->compile() in bootstrap.php.cache line 2594
    at Kernel->initializeContainer() in bootstrap.php.cache line 2373
    at Kernel->boot() in bootstrap.php.cache line 2404
    at Kernel->handle(object(Request)) in app_dev.php line 28


`

**Comment by locs31** [comment]
So how can i rollback the last composer update to use a sonata release working please?

**Comment by greg0ire** [comment]
You can use the `!=3.5.0` version constraint and hope it gets fixed in `3.5.1`

**Comment by locs31** [comment]
I try using the 3.5.0 and i've got the same error.

**Comment by locs31** [comment]
Here is my composer.json for sonata bundle : 
`"sonata-project/easy-extends-bundle": "~2.1@dev",
        "sonata-project/seo-bundle": "2.x-dev",
        "sonata-project/doctrine-extensions": "1.x-dev",
        "sonata-project/intl-bundle": "2.x-dev",
        "sonata-project/admin-bundle": "3.5.0",
        "sonata-project/doctrine-orm-admin-bundle": "3.x-dev",
        "sonata-project/notification-bundle": "3.x-dev",
        "sonata-project/block-bundle": "3.x-dev",
        "sonata-project/media-bundle": "3.x-dev",
        "sonata-project/user-bundle": "3.x-dev",
        "sonata-project/cache-bundle": "~2.1@dev",
        "sonata-project/cache": "~1.0@dev",
        "sonata-project/page-bundle": "3.x-dev",
        "sonata-project/core-bundle": "3.x-dev",
        "sonata-project/formatter-bundle": "3.x-dev",
        "sonata-project/datagrid-bundle": "~2.2@dev",
        "sonata-project/exporter": "1.x-dev",
        "sonata-project/timeline-bundle": "3.x-dev",
        "sonata-project/classification-bundle": "3.x-dev",`

**Comment by greg0ire** [comment]
- `!=3.5.0`
- `!=`
- **not** equals

**Comment by locs31** [comment]
ok i try

**Comment by greg0ire** [comment]
You should avoid dev versions, you know?

**Comment by locs31** [comment]
can you give me a sample for this json composer please?

**Comment by greg0ire** [comment]
No, but I can tell you how to build it : for each package, go on packagist, see what the last stable version is, and if the numbers starts with `42`, use the `^42.0.0` version constraints, and you should be fine.

**Comment by locs31** [comment]
ok i try

**Comment by greg0ire** [comment]
People like are a blessing, because you report the bugs before they occur to others, but you must know that literally what you are doing : taking all the new bugs for the others :wink: Anyway, thanks for reporting this!

**Comment by locs31** [comment]
In packagist if bundle version is 2.2.4 i write ^2.2.4 in my composer.json?

**Comment by greg0ire** [comment]
Yes, that's good!

**Comment by locs31** [comment]
ok thanks :)

**Comment by cassianotartari** [comment]
The ``sonata.admin.configuration.breadcrumbs`` that is used to instantiate ``BreadcrumbsBuilder`` is only available in ``dev-master``. I don't know why under tag ``3.5.0`` [the parameter is being used in ``core.xml``](https://github.com/sonata-project/SonataAdminBundle/blob/3.5.0/Resources/config/core.xml#L28).

**Comment by cassianotartari** [comment]
To fix this issue ``SonataAdminExtension`` should be merged into tag ``3.5.0``. See [#L94](https://github.com/sonata-project/SonataAdminBundle/blob/3.5.0/DependencyInjection/SonataAdminExtension.php#L94)

**Comment by cassianotartari** [comment]
I didn't understand anymore, a minute a go I swear that I didn't see any [``sonata.admin.configuration.breadcrumbs``](https://github.com/sonata-project/SonataAdminBundle/blob/3.5.0/DependencyInjection/SonataAdminExtension.php#L94) mention under ``3.5.0`` in ``SonataAdminExtension``. Nor [``breadcrumbs``](https://github.com/sonata-project/SonataAdminBundle/blob/3.5.0/DependencyInjection/Configuration.php#L76) under ``Configuration``.

``3.5.0`` should not have this bug. After the parameter is used in [``core.xml``](https://github.com/sonata-project/SonataAdminBundle/blob/3.5.0/Resources/config/core.xml#L28) to instantiate [``BreadcrumbsBuilder``](https://github.com/sonata-project/SonataAdminBundle/blob/3.5.0/Admin/BreadcrumbsBuilder.php#L32). Seems to be all right.

**Comment by locs31** [comment]
I don't understand your fix. I try gregoire solution in my composer.json like this : 
`"sonata-project/easy-extends-bundle": "^2.1.10",
        "sonata-project/seo-bundle": "^2.0.2",
        "sonata-project/doctrine-extensions": "^1.0.2",
        "sonata-project/intl-bundle": "^2.2.4",
        "sonata-project/admin-bundle": "^3.5.0",
        "sonata-project/doctrine-orm-admin-bundle": "^3.0.5",
        "sonata-project/notification-bundle": "^3.0.0",
        "sonata-project/block-bundle": "^3.1.1",
        "sonata-project/media-bundle": "^3.2.0",
        "sonata-project/user-bundle": "^3.0.1",
        "sonata-project/cache-bundle": "^2.2.5",
        "sonata-project/cache": "^1.0.7",
        "sonata-project/page-bundle": "^3.1.0",
        "sonata-project/core-bundle": "^3.1.0",
        "sonata-project/formatter-bundle": "^3.0.1",
        "sonata-project/datagrid-bundle": "^2.2.0",
        "sonata-project/exporter": "^1.7.0",
        "sonata-project/timeline-bundle": "^3.0.0",
        "sonata-project/classification-bundle": "^3.1.0",`

It's the latest package stable find on packagist.
But now i've got this error : 
`ClassNotFoundException in SourceManager.php line 23: Attempted to load interface "SourceIteratorInterface" from namespace "Exporter\Source".
Did you forget a "use" statement for another namespace?`

**Comment by locs31** [comment]
I just restart my server and clear all cache it's look like good now. I think it was a bad cache clear.

**Comment by locs31** [comment]
And of course thanks to help improve my composer.json with good and stable release :) :+1:

**Comment by cassianotartari** [comment]
``"sonata-project/exporter": "^1.7.0"`` don't need to be in your ``composer.json`` it's a require on [SonataAdmin](https://github.com/sonata-project/SonataAdminBundle/blob/3.5.0/composer.json#L26)

Same for [``"sonata-project/core-bundle": "^3.1.0"``](https://github.com/sonata-project/SonataAdminBundle/blob/3.5.0/composer.json#L25)

Didn't look close to others requires

**Comment by locs31** [comment]
ok thanks i will delete this in my composer

**Comment by greg0ire** [comment]
`composer update -v` is supposed to clear the cache on post install, so this is strange. Anyway, no bug, that's great to hear!

**Comment by locs31** [comment]
Yes it's look like good for me :) thanks :)
