### ISSUE TITLE
[WorkFlow] Sonata type collection and trigger event

### ISSUE THREAD

**Issue by chadyred** [sonata-project/SonataAdminBundle#4121]
Lots of though about this workflow bundle and its compatibility with doctrine event.

Lots of my sonata admin entity which contain a ```sonata_type_collection```, each time, I have to trigger the prePersist on them manually with the ```prePersist()``` and ```preUpdate()``` method in this bundle like this.

Is their a way to featuring the nice way Doctrine  ```prePersist ``` and  ```preUpdate ``` as it build on original entity ? 

Then, for the Timestampable and other field that change with on Update event, same thing I have to manually use this boring prePersist and preUpdate function to make my whole workflow with the `@ORM\perPersist` made basically...

An extract is like this, I trigger like I said and I even trigger the other ```prePersist()``` and ```preUpdate()``` method on the other side of the collection

```
    public function preUpdate($object)
    {
        $this->runMultiPreAction($object);
    }
    public function prePresist($object)
    {
        $this->runMultiPreAction($object);
    }

    protected function runMultiPreAction($object)
    {

          $security = $this->getContainer()->get('security.token_storage');
            $token = $security->getToken();
        $user = $token->getUser();

        $serviceAdminRecipeWorkflow = $this->getConfigurationPool()->getAdminByAdminCode('me.recipe.admin.recipe_workflow');

        foreach ($this->getFormFieldDescriptions() as $fieldName => $fieldDescription) 
        {
            if($fieldDescription->getType() === 'sonata_type_collection' &&
                ($associationMapping = $fieldDescription->getAssociationMapping()) &&
                ($associationMapping['targetEntity'] === 'Me\RecipeBundle\Entity\RecipeWorkflow'))
             {
                $getter = 'get' . $fieldName;
                $setter = 'add' . $fieldName;

                $recipesWorkflow = $object->$getter();

                if (count($recipesWorkflow) > 0)
                {
                    foreach ($recipesWorkflow as $unRw)
                    {

                        $unRw->setRecipe($object);

                       // Timestampable...boring and verbose code
                        $unRw->setUpdatedBy($user);
                        $unRw->setContentChangedAt(new \DateTime('now'));
                        $unRw->setCreatedAt(new \DateTime('now'));
                        $unRw->setUpdatedAt(new \DateTime('now'));

                        $object->addRecipeWorkflow($unRw);
                       
                          // Trigger this same fonction on the other admin...boring, relly !!
                        $serviceAdminRecipeWorkflow->preUpdate($unRw);
                        $serviceAdminRecipeWorkflow->prePersist($unRw);

                    }
                }
            }
```

Why this prePersist are not trigger directly like in a simple form on Symfony ? Is their a way to achieve that ? I think the DRY made by `prePersist` on `inversedSide` by the setter is really cool, and here, unfortunetly, all that workflow is done manually...`prePersist` by use `prePersist` method is not a good way, maybe I have misunderstood this bundle ;)

Thanks.

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.

**Comment by chadyred** [comment]
Sure ! I'm doing this and show on StackOverflow.
