### ISSUE TITLE
sonata_type_choice_field_mask doesn't work in expanded mode

### ISSUE THREAD

**Issue by verheyenkoen** [sonata-project/SonataAdminBundle#4127]
When you use a sonata_type_choice_field_mask form field with the option `'expanded' => true` (causing it to generate radio buttons instead of a select list), the rendered jQuery code to handle this behaviour doesn't work anymore. It appears to be completely written to work for a select element only.

I guess expanded should be supported as well here.

Not sure if multiple should be supported here, since the field mapping would maybe required a single selection mode.

**Comment by greg0ire** [comment]
> doesn't work anymore

Please develop

> the rendered jQuery code

Please link to the code on github

> I guess expanded should be supported as well here.

I think so too, would you be willing to write a PR for this?

**Comment by verheyenkoen** [comment]
> Please link to the code on github

https://github.com/sonata-project/SonataAdminBundle/blob/master/Resources/views/Form/form_admin_fields.html.twig#L466

**Comment by greg0ire** [comment]
Plus it's js code in a twig template… that would need to be changed in favor of a separate js file looking for data-attributes to do its thing.

**Comment by verheyenkoen** [comment]
@greg0ire I came up with some sort of fix that works in my case (still JS in Twig though). I forked the project and read the contributing guide, but I can't figure out how to set everything up since Sonata Admin is in the root of the project (usually in the vendor dir), there doesn't seem to be a way to install it as a Symfony project.

Anyway, this is what I have overridden in `form_admin_fields.html.twig`.

`````
{% block sonata_type_choice_field_mask_widget %}
    {{ block('choice_widget') }}
    {% set main_form_name = id|slice(0, id|length - name|length) %}
    <script>
        jQuery(document).ready(function() {
            var allFields = {{ all_fields|json_encode|raw }};
            var map = {{ map|json_encode|raw }};

            var showMaskChoiceEl = jQuery('#{{ main_form_name }}{{ name }}');
            var isExpanded = showMaskChoiceEl.has(':radio,:checkbox').length > 0;

            if (isExpanded) {
                showMaskChoiceEl = showMaskChoiceEl.find(':radio,:checkbox');
            }

            // ifChecked is the iCheck library event (change will not fire if iCheck is active)
            showMaskChoiceEl.on('change ifChecked', function () {
                choice_field_mask_show(jQuery(this).val());
            });

            function choice_field_mask_show(val)
            {
                var controlGroupIdFunc = function (field) {
                    return '#sonata-ba-field-container-{{ main_form_name }}' + field;

                };
                if (map[val] == undefined) {
                    jQuery.each(allFields, function (i, field) {
                        jQuery(controlGroupIdFunc(field)).hide();
                    });
                    return;
                }

                jQuery.each(allFields, function (i, field) {
                    jQuery(controlGroupIdFunc(field)).hide();
                });
                jQuery.each(map[val], function (i, field) {
                    jQuery(controlGroupIdFunc(field)).show();
                });
            }

            if (isExpanded) {
                choice_field_mask_show(showMaskChoiceEl.filter(':checked').val());
            } else {
                choice_field_mask_show(showMaskChoiceEl.val());
            }
        });
    </script>
{% endblock %}
`````

Also this is a bug I guess, so a unit test is required, but the fix is purely JS. Usually this cannot be tested with web tests, unless you use some other system.

Btw, running phpunit (`make test`) on a clean checkout throws a fatal error after the 12th test.

````
PHP Fatal error:  Call to undefined method Sonata\AdminBundle\Tests\Admin\AdminTest::prophesize() 
in (...)/SonataAdminBundle/Tests/Admin/AdminTest.php on line 125
````

**Comment by greg0ire** [comment]
> but I can't figure out how to set everything up since Sonata Admin is in the root of the project (usually in the vendor dir), there doesn't seem to be a way to install it as a Symfony project.

You're supposed to install it inside another project, in the vendor dir. You can't install it as a Symfony project because it isn't one.

> Also this is a bug I guess, so a unit test is required, but the fix is purely JS. Usually this cannot be tested with web tests, unless you use some other system.

Sadly we don't unit test js for the moment, so I guess this would be ok.

> Btw, running phpunit (make test) on a clean checkout throws a fatal error after the 12th test.

Your version of phpunit is old.
