### ISSUE TITLE
Registering localised assets via AdminPool

### ISSUE THREAD

**Issue by elHornair** [sonata-project/SonataAdminBundle#4135]
The loading of the localised versions of moment.js and select2 are currently not registered and loaded via the admin pool. Doing so would make the template `standard_layout` simpler. We could then also move the logic of generating the proper localised names to PHP instead of Twig (f.e. for respecting the fact that the portuguese version of select2 is called 'pt_PT' and not 'pt').
The goal of this issue would be to create a service that adds all localised assets to the admin pool so they are automatically rendered in `standard_layout`.

(originally discussed here: https://github.com/sonata-project/SonataAdminBundle/pull/4134)

**Comment by elHornair** [comment]
I can have a look at this, but I'd need a hint on where the "normal" (non-localised) assets are registered

**Comment by OskarStark** [comment]
@ju1ius can you help uns here?
