### ISSUE TITLE
Have you ever thought using SonataAdmin without writing a line of PHP?

### ISSUE THREAD

**Issue by betaglop** [sonata-project/SonataAdminBundle#4140]
The basic idea is: why writing a code that I cannot reuse and extend easily when I'm configuring a SonataAdmin in my bundle ?... Especially if I target an ultra-reusable design, a many years lifespan for my piece of software, an optimized maintainability, etc.

For the moment, AFAIK SonataAdmin cannot go really far in that direction.
That's why we developed a bundle (and a set of bundles actually) for that purpose: the [LibrinfoCoreBundle](https://github.com/libre-informatique/SymfonyLibrinfoCoreBundle).

[This bundle](https://github.com/libre-informatique/SymfonyLibrinfoCoreBundle) is the next step after the SonataAdminBundle:
- Configure an entire back-end bundle filling only YAML files...
- Extend a bundle from the outside making some properties generic and reusable
- Forecast the display of properties and their future uses in other bundles, making them lightweight and easier to maintain...

Try it!
And if the Sonata Project is interested in some collaboration, do not hesitate to propose it!

PS: ok ok, the documentation is still a WIP... it's improving daily, even if the development continues on a daily basis as well.

**Comment by greg0ire** [comment]
> Have you ever thank

This should go to https://www.reddit.com/r/titlegore

> PS: ok ok, the documentation is still a WIP... it's improving daily, even if the development continues on a daily basis as well.

My advice, if you want your project to be better than Sonata : write the documentation before writing the code, and make sure

**Comment by betaglop** [comment]
We are more working in a RAD intention (we do not separate doing and thinking)... We write things as we need them, so we cannot really write the doc before being sure it will be realized as it was designed. But sure: it's a pain, but it's also rewarding to crystallize what you did correctly.

Then the idea is not to do something better than Sonata but more to improve Sonata using it in the better way we can.

> This should go to https://www.reddit.com/r/titlegore

Is this reddit correct?? Maybe I missed something.

**Comment by greg0ire** [comment]
> Is this reddit correct?? Maybe I missed something.

Yes, it's a subreddit dedicated to wrong titles :wink: Look at the title of your issues.

> Then the idea is not to do something better than Sonata but more to improve Sonata using it in the better way we can.

Yeah I understood that a bit late. Cool project!

**Comment by neo-james** [comment]
@betaglop thanks for sharing your efforts.
>We are more than open to contributions, comments, ideas... do not hesitate.
Yes I have some ideas, Can you please look at  #3947

**Comment by jordisala1991** [comment]
This can be closed.
