### ISSUE TITLE
CRUD Controller tries to access private property Symfony\Bridge\Twig\Extension\FormExtension::$renderer

### ISSUE THREAD

**Issue by mdstorage** [sonata-project/SonataAdminBundle#4152]
Environment
Symfony 3.2.0-dev
SonataAdminBundle 3.x-dev
StackTrace
[1] Symfony\Component\Debug\Exception\FatalThrowableError: Cannot access private property Symfony\Bridge\Twig\Extension\FormExtension::$renderer
    at n/a
        in .../vendor/sonata-project/admin-bundle/Controller/CRUDController.php line 108

**Comment by core23** [comment]
Can you supply a PR?

Refs https://github.com/sonata-project/SonataAdminBundle/issues/4088

**Comment by eldiablo62** [comment]
I have the same problem with symfony 3.2 and sonata 3.x dev and 3.10.0 :(

**Comment by greg0ire** [comment]
Well then carry #4216 yourself
