### ISSUE TITLE
How have default value in filter with session

### ISSUE THREAD

**Issue by razbounak** [sonata-project/SonataAdminBundle#4153]
I would like have a dynamic value of session for the default value of filterParameters

This code working : 
`    
    /**
     * Default Datagrid values
     *
     * @var array
     */
    protected $datagridValues = array(
        'applications' => array('value' => 'Sport TV'),
        '_sort_order' => 'ASC'
    );

    // Fields to be shown on filter forms
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('title')
            ->add('applications', null, array('label' => 'Chaîne'), null, array('expanded' => true, 'multiple' => true))
        ;
    }`

But when I add the session, he don't want that I use this outside the function : 
`    public function getApplicationsSession()
    {
        $session = new Session();
        return $session->get('applications');
    }

    /**
     * Default Datagrid values
     *
     * @var array
     */
    protected $datagridValues = array(
        'applications' => array('value' => $this->getApplicationsSession()),
        '_sort_order' => 'ASC'
    );`

Thanks to helping me

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
