### ISSUE TITLE
Deprecations related to AdminBlockServiceInterface

### ISSUE THREAD

**Issue by javiereguiluz** [sonata-project/SonataAdminBundle#4155]
#### Sonata packages

```bash
$ composer show sonata-project/*

sonata-project/admin-bundle              3.8.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0 Symfony SonataBlockBundle
sonata-project/cache                     1.0.7 Cache library
sonata-project/core-bundle               3.1.1 Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.1.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.0 Lightweight Exporter library
```

#### Symfony packages

```bash
$ composer show symfony/*

symfony/assetic-bundle     v2.8.0  Integrates Assetic into Symfony2
symfony/monolog-bundle     2.11.1  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.12 Symfony PHPUnit Bridge
symfony/polyfill-intl-icu  v1.2.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.2.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.2.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.2.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.2.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.3.11 Symfony SwiftmailerBundle
symfony/symfony            v3.1.5  The Symfony PHP framework
```

#### PHP version

```bash
$ php -v

PHP 5.6.19 (cli) (built: Mar 10 2016 14:12:41)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with blackfire v1.11.1, https://blackfire.io, by Blackfireio Inc.
```

## Subject

When using the latest version of Sonata, I see two deprecation messages:

![sonata-deprecations](https://cloud.githubusercontent.com/assets/73419/19068666/c21755d6-8a23-11e6-8399-a20ee4bf93fa.png)

I don't use the block service directly, so this deprecation may be caused by Sonata itself. If I open the code of vendor/sonata-project/admin-bundle/Block/AdminListBlockService, I see this in PHPStorm:

![phpstorm-deprecation](https://cloud.githubusercontent.com/assets/73419/19068733/191aa946-8a24-11e6-8058-6fe80e34dae4.png)

But maybe I'm missing something here and the problem is caused by my application? Thanks for your help!

**Comment by OskarStark** [comment]
Hey @javiereguiluz 

You are right, we need to extend `AbstractBaseBlockService` here and increase the dependency to 3.2 of the block-bundle.

I am working on a PR right know and let you know when its fixed! 👍

**Comment by OskarStark** [comment]
@javiereguiluz we release AdminBundle 3.9.0 -> https://github.com/sonata-project/SonataAdminBundle/releases/tag/3.9.0

**Comment by javiereguiluz** [comment]
@OskarStark I've updated Sonata packages (and Symfony to 3.2-beta1):

```
$ composer show sonata-project/*

sonata-project/admin-bundle              3.9.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0 Symfony SonataBlockBundle
sonata-project/cache                     1.0.7 Cache library
sonata-project/core-bundle               3.1.1 Symfony SonataCoreBundle
sonata-project/doctrine-orm-admin-bundle 3.1.1 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.0 Lightweight Exporter library
```

And I'm still getting deprecation messages like this one:

![deprecated_log_message](https://cloud.githubusercontent.com/assets/73419/19849184/07c8f682-9f52-11e6-9c70-dbbb51fbc960.png)

Should I reopen this issue or create a new issue? Thanks.

**Comment by greg0ire** [comment]
Related PR : https://github.com/sonata-project/SonataBlockBundle/pull/338
