### ISSUE TITLE
 Edit form with nested tabs and groups

### ISSUE THREAD

**Issue by neo-james** [sonata-project/SonataAdminBundle#4171]
For the need for an edit form like following, I suggest to allow for nesting form groups and tabs. So group or tab can contain tabs.

![edit_form](https://cloud.githubusercontent.com/assets/22734109/19373457/ab2e13e0-91cc-11e6-970f-44258429d434.png)

**Comment by OskarStark** [comment]
Sounds great 👍 

And great pictograms btw. 👍

**Comment by neo-james** [comment]
Thanks,
If you agree I suggest (if I'm not wrong) in the the file `Show/ShowMapper.php`

- By default there is a root group within it we can add `field` or `group` or `tabgroup`
- So in `ShowMapper' We add a method `addTabGroup()` that return `TabGroup` class.
- `TabGroup' class has only two methods `addTab`, `removeTab` (or `addGroup` and `removeGroup` as it simplify things )

So based on above we end up with following classes `Group`, `TabGroup` and `Field`
- `Group` is the container for `field`s
- `TabGroup` can has only groups each `group` will be displayed as a tab UI
- `Field` will be rendered as current implementation

This suggestion will also be simple in the template `Resources/views/CRUD/base_edit_form.html.twig`
- As code will only loop inside `root` group for `group`, `filed` or `tabgroup` 
- Inside TabGroups will loop only for `Group`
- A macros can be utilized to render each type

Finally removing a field or group or tabgroup can be done using path like `remove('\tabgroup1\infox')`


One question: 
Why in ShowMapper do we need access to `AdminInterface` as `$admin` ? By mean of 
Why methods like `getShowGroups`, `setShowGroups`, `getShowTabs` and others are in the  `AdminInterface` ?

**Comment by OskarStark** [comment]
> So based on above we end up with following classes Group, TabGroup and Field

Why not just `Group`, `Tab` and `Field` ?

**Comment by neo-james** [comment]
> Why not just Group, Tab and Field ?
I suggest that `Tab` is just a group but nested directly inside a `Tabgroup` this way a group can be moved inside or outside `TabGroup` easily and without change .
Also from code perspective a sample form tree will be like:
```
\
    field1
    field2
    TabGroup1
        group1
            field3
            field4
        group2
            field5
            field6
```
Also what will be the difference between `Tab` and `Group` from code perspective (IMHO both are same). Also a tab is also a group of fields.

**Comment by jordisala1991** [comment]
You already have Tabs and Groups to build form. Closing . Ping me if this should be reopened
