### ISSUE TITLE
Absolute admin routes in menu

### ISSUE THREAD

**Issue by fracsi** [sonata-project/SonataAdminBundle#4175]
Is there a specific reason why the generated routes in the sidemenu are absolute?

In the [`Configuration.php`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/DependencyInjection/Configuration.php#L161) the route_absolute: true is hardcoded when using admin ids as items, thus cannot be changed.

**Comment by OskarStark** [comment]
@rande can you help?

**Comment by greg0ire** [comment]
@fracsi what does the git log say about this?

**Comment by fracsi** [comment]
@greg0ire Not much. I only found this PR: #3578

**Comment by OskarStark** [comment]
@fracsi what is you exact problem?

**Comment by fracsi** [comment]
It is just a question. Why is it needed? Or if it is needed, then why it cannot be configured?

**Comment by OskarStark** [comment]
always +1 for configuration, would you provide a PR?

**Comment by greg0ire** [comment]
Not sure it isn't configurable. The PR you linked to says it is a default value

**Comment by fracsi** [comment]
@OskarStark I think it needs more conversation about how it should be done.

Currently:
1. route_absolute can be configured if using a direct configuration for menu item (not admin), by providing label, route
2. route_absolute is always true if admin is used, only providing admin service id.
3. If both admin and route is defined, admin is ignored. ([`Configuration.php`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/DependencyInjection/Configuration.php#L154))

I don't know what should be the best to make it configurable.

**Comment by fracsi** [comment]
@greg0ire If you check the usage of groupDefaults, it is passed to the Pool (setAdminGroups), and that is it. The only solution to modify it would be to get the adminGroups from Pool, modify them and reset them.

**Comment by fracsi** [comment]
@OskarStark @greg0ire 
One quick solution would be to remove `$items[$key]['admin'] = '';` line from [`Configuration.php`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/DependencyInjection/Configuration.php#L154), this way we can configure the menu item as array with an admin id.
E.g.:
```
sonata_admin:
    dashboard:
        groups:
            test_group:
                items:
                    - { admin: my.admin.service.id, route_absolute: false }
```
Any thougths?

**Comment by greg0ire** [comment]
@amine2z , can you help? Also, can you link your ekino.com email address to your github account?

**Comment by rande** [comment]
I don't see the need of an absolute url... but I don't see the issue with absolute url too. If the url is not correct, it just mean the RequestContext is wrong, and should be correctly set either with settings the correct http headers in your RP or changing the value at the php level.

**Comment by fracsi** [comment]
@rande There is no issue. I just ran across this "feature"/"bug" and found an inconsistency. Because there is a configuration option, but it cannot be configured if using admin service ids. That is it.

**Comment by amine2z** [comment]
as @rande said i dont see what is wrong with this. For the moment route_absolute is not used for admin menu items https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Menu/Provider/GroupMenuProvider.php#L129. 
@greg0ire i don't see why im pinged too, and why you talk about email adresse 😆

**Comment by greg0ire** [comment]
@amine2z : I pinged you because you're the main author of this piece of code, and I had a hard time finding you because you did not link the email address you make your commits with with your github account (and thus, your username).

**Comment by fracsi** [comment]
@amine2z As you can see route_absolute is used for admin: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Menu/Provider/GroupMenuProvider.php#L110

**Comment by ebuildy** [comment]
Hello, as a conclusion, how can I disable this for all groups? thanks you
