### ISSUE TITLE
Printing value only should be possible in specific template

### ISSUE THREAD

**Issue by nykopol** [sonata-project/SonataAdminBundle#4186]
In a custom template, the twig helper `render_view_element` display a field inside a table row. But when we write a custom template we usually want more control.

It's possible to overwrite the template of the field, but it's not the most obvious way to do it in a custom template. The solution of printing the value with something like `{{object.attribut}}` is easy. But you lose the automatic translation, and the others cool stuff of Sonata (boolean to icon, formatted dates, ...)

So I think that Sonata miss two twig helper :
* `render_value_element`: this one print only the value
* `render_name_element`: this one print only the name of the field

Did I miss something that would make this issue useless or did you share my opinion ?

**Comment by greg0ire** [comment]
Isn't there a way to change the value before it is passed to the templates? Custom templates are useful if they contain markup image,  but if it is just values, not so much.

**Comment by nykopol** [comment]
The `render_view_element` take as parameters the `FieldDescription` and the object. The only way to change the way it's displayed is by changing the template defined in the FieldDescription. But so, you must define a template for this specific attribute.

For example ,if you want a custom `show` template to display you beautiful blog post, a raw table listing the attributes of you entity is not so sexy. On this template, if you want to display the publication date in a pinky fashioned div, either you define a template for this attribute, or you print `{{object.publicationDate}}`.

On the fist case, creating a specific template when you already are in a specific template is not developer friendly. Especially if you not plan to reuse this fashioned picky div.

On the second case, printing `{{object.publicationDate}}` will require you to add the twig filters to print it with the good format, witch is already done by Sonata.

The helper that I think would print only the value with the good formatting : 
```xml
<div class="pinky-fashioned">{{ elements['publication_date']|render_view_element(object)}}</div>
```
would print : 
```xml
<div class="pinky-fashioned">1 oct. 2016</div>
```
With the date already formatted like usual.

**Comment by greg0ire** [comment]
I think it's a great idea. Maybe these helpers could rely on a new valueformatter or nameformatter class that could be associated with a field type, and overriden for a specific field?
