### ISSUE TITLE
Is the suffix "id : (%s)" in ModelChoiceLoader a really good choice ?

### ISSUE THREAD

**Issue by jlamur** [sonata-project/SonataAdminBundle#4194]
A screenshot explains better than my words, so : 
![capture du 2016-11-06 19-49-03](https://cloud.githubusercontent.com/assets/7054317/20040603/8fdc28e8-a45a-11e6-81a4-f70495567264.png)

The code that cause this behavior is here : https://github.com/sonata-project/SonataAdminBundle/blob/5745cdbfe377761caa0277ff2a5ed98772199c96/Form/ChoiceList/ModelChoiceLoader.php#L124

It is obvious in my opinion that someone should remove this horrible suffix. But maybe I'm missing something...

What do you think ?

**Comment by greg0ire** [comment]
> What do you think ?

That if you do that, there is no way to tell both items apart. So why do it?

**Comment by jlamur** [comment]
@greg0ire because it's ugly, and you should let the developer choose if he want to display an unique identifier for its entities. This is not about if it's technically or not doable.

With this approach, there's no choice. In my case, the **__toString()** function will return a string which is always unique. So there is absolutely no need to display an id.

**Comment by greg0ire** [comment]
> In my case, the __toString() function will return a string which is always unique. So there is absolutely no need to display an id.

But if it is really unique, the id does not get displayed, right?

**Comment by jlamur** [comment]
@greg0ire Well... You're absolutely right ! 
I only tested with identical values and I had not understood right the code that I mentioned...
Sorry for the waste of time.

**Comment by greg0ire** [comment]
Haha no biggie
