### ISSUE TITLE
updating jquery and jqueryui

### ISSUE THREAD

**Issue by caponica** [sonata-project/SonataAdminBundle#4195]
Hi,

what are the plans relating to upgrading the jquery/jqueryui libraries?

jquery is now on 3.1.1 but I think SonataAdmin uses 2.1.4, and jqueryui is on 1.12.1 but SonataAdmin uses 1.10.4, both of which I think are from 2014?

In particular:

 - Are there any known Sonata issues with upgrading these to the latest versions?
 - How will any future library upgrade be managed? (since some people will want to keep the old versions to prevent BCs in their current code... so I can understand why they haven't been updated for a long time - it's going to be a big can of worms!)

**Comment by greg0ire** [comment]
If jQuery UI uses semver, I think we can upgrade it just fine. jQuery itself however should have to be upgraded on the next major version (so the master branch), and since we have no tests manual check should be done :/

**Comment by caponica** [comment]
That's what I thought... scary!

P.S. I don't think jqueryui uses semver... there are breaking changes betweeen 1.11 and 1.12 and methods deprecated in 1.10 were removed in 1.11.

**Comment by phansys** [comment]
I'm closing this issue since we will use Webpack Encore for asset management.
Please see #5454.
