### ISSUE TITLE
How do I know what options are available as 3rd argument of ListMapper->add() in SonataAdminBundle

### ISSUE THREAD

**Issue by sruj** [sonata-project/SonataAdminBundle#4198]
for 3 days nobody answer at [stack ](http://stackoverflow.com/questions/40421034/how-do-i-know-what-options-are-available-as-3rd-argument-of-listmapper-add-in)so I put it here 

How do I know what options are available as 3rd argument of ListMapper->add() in SonataAdminBundle

You says there is a link with options http://symfony.com/doc/current/bundles/SonataAdminBundle/reference/action_list.html#options

but there are also a few here http://symfony.com/doc/current/bundles/SonataAdminBundle/reference/action_list.html#visual-configuration

How do I know if there are more options available? Perfectly if someone point how to discover that from Sonata code (maybe ListMapper class).

Because f.e. I want to reduce size of text in cell if it's too large, and I don't know if I can use some 3rd argument option or I need to override template.

**Comment by greg0ire** [comment]
Hi, we try to keep Github issues for bug reports and feature requests only. 

I don't have time to look into this, so I'll just add a bounty on your SO question.

**Comment by sruj** [comment]
thank You.
