### ISSUE TITLE
FormMapper->add with 'sonata_type_model_autocomplete' uses ACL, while 'sonata_type_model' doesn't

### ISSUE THREAD

**Issue by sr972** [sonata-project/SonataAdminBundle#4203]
Hi,

i've found an interesting behaviour on using ACL in the Admin Bundle and when ACL seems to be respected and when not.

Info on versions:

- Symfony 2.8
- AdminBundle 3.8
- FOS UserBundle 1.3.6
- Using sonata.admin.security.handler.acl (in combination with CoopTilleulsAclSonataAdminExtensionBundle)

Situation:
You have 2 entities, lets call them `Users` and `Groups`. There is a OneToMany (Groups) and ManyToOne (Users) relation between them both. I have 2 separated admins for this 2 entities. 

Problem:
User A logs into AdminBundle and creates a `Group` named "UsergroupA". User B logs into AdminBundle and creates a `Group` named "UsergroupB". Thanks to CoopTilleulsAclSonataAdminExtensionBundle the list option is already prefiltered and user A only sees his things, B only things from B.

Now user B wants to create an `User`. The `configureFormFields` looks like:
```php
protected function configureFormFields(FormMapper $formMapper)
{
    $formMapper
        ->with('Userdetails')
        ->add('Name', 'text')
        ->add('group') // which will call the other admin
        // or ->add('group', 'sonata_type_model')
        ->end();
}
````

But now in the dropdown both groups appear, the "UsergroupA" and "UsergroupB". What is wrong when it would respect the ACL.

If i change the `configureFormFields` to
```php
protected function configureFormFields(FormMapper $formMapper)
{
    $formMapper
        ->with('Userdetails')
        ->add('Name', 'text')
        ->add('group', 'sonata_type_model_autocomplete', array('property' => 'name', 'minimum_input_length' => 0))
        ->end();
}
````
the ACL is respected and user A sees just "UsergroupA" and B just "UsergroupB", what is (IMO) correct.

The question is:
Is acting `sonata_type_model` or `sonata_type_model_autocomplete` wrong? 
As i wrote, i think `sonata_type_model` is the one. Or could this be fixed in any other way?

**Comment by mba242** [comment]
Just confirm, i think not so many uses CoopTilleulsAclSonataAdminExtensionBundle.
sonata_type_model_list have same behavior like sonata_type_model_autocomplete.

**Comment by lukepass** [comment]
Same problem here, sonata_type_model_list and sonata_type_model_autocomplete respect acl, sonata_type_model doesn't. Any solutions?
