### ISSUE TITLE
What I need to do?

### ISSUE THREAD

**Issue by Lednick** [sonata-project/SonataAdminBundle#4217]
Remaining deprecation notices (4)
The Sonata\AdminBundle\Admin\AbstractAdmin::setTranslator method is deprecated since version 3.9 and will be removed in 4.0: 4x
    4x in DefaultControllerTest::testIndexAction from Tests\AppBundle\Controller

I have symfony 3.1.7 and SonataAdminBundle 3.10

**Comment by core23** [comment]
Please use the issue template!
