### ISSUE TITLE
File upload in collection

### ISSUE THREAD

**Issue by QuentinPolantis** [sonata-project/SonataAdminBundle#4227]
Hi all,

I'm facing a weird issue. I'm trying to have a file upload in sonata_type_collection field.
For this i've to perform an upload method for each item of the collection. 

The issue looks like a front-end issue.

<img width="1235" alt="capture d ecran 2016-12-12 a 10 41 06" src="https://cloud.githubusercontent.com/assets/14995853/21094528/a8407290-c057-11e6-815b-f893c2d5e4ad.png">

At the very moment i click "Add new", all my uploaded file fields are reseted and no files are selected anymore.

<img width="1181" alt="capture d ecran 2016-12-12 a 10 44 21" src="https://cloud.githubusercontent.com/assets/14995853/21094599/fabfac3e-c057-11e6-8a6a-3958e4c7b3ca.png">
 

In order to avoid the issue, i've to select all my uploaded files after typing every row. Did someone ever noticed that behavior (that i think is not the intended one)? 

Thanks by advance,

Quentin

**Comment by jordisala1991** [comment]
Yes, someone tried to solve it for the SonataDoctrineOrmAdminBundle here: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/590

It is working that way to ensure that the new row added is on the right position (depending on the order by it may not be the last one), but the files and some other behavior: https://github.com/sonata-project/SonataAdminBundle/issues/2383 is not mantain when recreating all the rows.

**Comment by sujayjaju** [comment]
Above 3 PRs should resolve the issue for Doctrine, PHPCR and MongoDB.
