### ISSUE TITLE
How do I remove translations from admin class?

### ISSUE THREAD

**Issue by GCalmels** [sonata-project/SonataAdminBundle#4229]
Hi,

Since v3.9, translations no longer have to be managed by the class admin but is it possible to have examples of how to do it via the controller or via the template?

It is understandable that you want to decrease the dependency of the admin class but it does not complicate things to quickly have a functional bundle for a dev?

Before it was possible to add only one admin class and everything worked while now it will be necessary to add templates or controllers each time?

Thank you!

**Comment by greg0ire** [comment]
You mean things are no longer translated when you add a new admin? I doubt that… have you checked the Symfony profiler? It shows what the translator tries to translate.

**Comment by GCalmels** [comment]
No no sorry, there are just deprecated notices! And I tried to remove them

**Comment by greg0ire** [comment]
What kind of deprecation notice do you get? Can you give an example?

**Comment by GCalmels** [comment]
Yes of course :
The Sonata\AdminBundle\Admin\AbstractAdmin::setTranslator method is deprecated since version 3.9 and will be removed in 4.0.

**Comment by greg0ire** [comment]
Not sure if this answers your question, but I think that to translate things, you will have to create translation files, like before… and that's all.

**Comment by GCalmels** [comment]
In fact, everything works fine but I have some deprecated notices. For example :
```php
protected function configureShowFields(ShowMapper $showMapper)
{
    $showMapper
        ->with('Product')
          ->add('product.category','trans', array(
                    'code' => 'getCategoryTranslationKey', 'catalogue' => 'AppBundle'))
         ->end()
         ->add('status', 'trans', array(
                'code' => 'getStatusTranslationKey', 'catalogue' => 'AppBundle'));
}
```

If I understood correctly: "trans" will be deleted so I wanted to know how to correct it

**Comment by greg0ire** [comment]
Not sure why `setTranslator` is called at all… Can you edit this method , throw an `\Exception` in it, and post the resulting stack trace?

**Comment by greg0ire** [comment]
[Here is the related PR](https://github.com/sonata-project/SonataAdminBundle/pull/4124/files) if you're interested.

**Comment by GCalmels** [comment]
Ok, I will take a look!
I have this notice too : The Sonata\AdminBundle\Admin\AbstractAdmin::trans method is deprecated since version 3.9 and will be removed in 4.0

**Comment by GCalmels** [comment]
When I clear the cache, I have 0 deprecated notice but if I change one thing in my admin class, all notices returns!

Normally the notice should only appear if I call setTranslator, trans ... in php in the Admin class?

**Comment by greg0ire** [comment]
> Normally the notice should only appear if I call setTranslator, trans ... in php in the Admin class?

No, it doesn't matter if you call it directly or indirectly, through Sonata. Did you try getting a stack trace?

**Comment by GCalmels** [comment]
<img width="985" alt="capture d ecran 2016-12-12 a 17 58 31" src="https://cloud.githubusercontent.com/assets/5655839/21108195/a2060d30-c094-11e6-88aa-7998cc7130d9.png">

**Comment by greg0ire** [comment]
Are you sure you're not calling `setTranslator` yourself, in `ClassifiedAdmin` line 227? Or is it where you are throwing the exception? Or did you override `setTranslator` there? Also, please note that there is a text version of the stack trace below, no need for a screenshot next time.

**Comment by GCalmels** [comment]
Ok, sorry! 
No, I'm throwing the exception l.227. I never call setTranslator anywhere...
And my class has configureShowFields with $showMapper :
```php
protected function configureShowFields(ShowMapper $showMapper)
{
        $showMapper
            ->with('Product')
                ->add('product.category','trans', array(
                    'code' => 'getCategoryTranslationKey', 'catalogue' => 'AppBundle'))
                ->add('product.number')
            ->end();
}
```

**Comment by greg0ire** [comment]
What I'm asking is "where is setTranslator called?". To answer that, edit the `SonataAdminBundle\Admin\AbstractAdmin::setTranslator` method, and throw an exception in it. This should provide you with a stack trace showing where it is called

**Comment by bgaleotti** [comment]
Could it be this lines (deleting them seems to remove the deprecation)?

[Translation1](https://github.com/sonata-project/SonataAdminBundle/blob/d8fc2edae14bc22d32e7d99990bcea54b626d01a/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L211)
[Translation2](https://github.com/sonata-project/SonataAdminBundle/blob/d8fc2edae14bc22d32e7d99990bcea54b626d01a/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L261)

**Comment by greg0ire** [comment]
Yes! The fact that they are dynamic explains that they were missed during the refactoring. Good catch! Not sure what the right thing to do is though… @core23? Help?

**Comment by greg0ire** [comment]
If it still works after removing the lines, maybe we should introduce a config none to enable the translator injection, set to true by default, and let people set it to false if the think they are ready for the migration? Feels a bit cumbersome though.

**Comment by GCalmels** [comment]
If I delete this 2 lines : I have the error "Call to a member function trans() on null"
because of AbstractAdmin ->trans ('Product', array(), 'RMOAdminBundle') 
and it is the "Product" in `->with('Product')`
Maybe it is why I have these deprecated notice but I can not remove this!

**Comment by greg0ire** [comment]
Ok so the bundle is not ready yet it seems. Would be great to have a full stack trace if you can provide it.

**Comment by bgaleotti** [comment]
There are some templates that are still using the deprecated Admin::trans method.

These are the ones I could find:

[SonataAdminBundle](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/CRUD/base_show.html.twig#L86)
[SonataDoctrineORMAdminBundle](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/46fbc45fbdeab4fac88041db94cacb3e8f9d3c67/Resources/views/CRUD/edit_orm_one_to_many_inline_table.html.twig#L26)
[SonataMediaBundle](https://github.com/sonata-project/SonataMediaBundle/blob/8f8b2195e0ba26592f1d3b927c2cd964c2945c85/Resources/views/MediaAdmin/list.html.twig#L18)

**Comment by greg0ire** [comment]
Would you guys like to make PRs for that?

**Comment by greg0ire** [comment]
Reopening since this is not really fixed. But it will be soon, see #4235
