### ISSUE TITLE
Sonata Media Bundle

### ISSUE THREAD

**Issue by ahbaqdadi** [sonata-project/SonataAdminBundle#4242]
### Environment
mac os

#### Sonata packages
sonata-project/admin-bundle              3.10.2          
sonata-project/block-bundle              3.2.0           
sonata-project/cache                     1.0.7           
sonata-project/classification-bundle     3.x-dev 
sonata-project/core-bundle               3.1.2          
sonata-project/datagrid-bundle           2.2          
sonata-project/doctrine-extensions       1.0.2     
sonata-project/doctrine-orm-admin-bundle 3.1.2
sonata-project/easy-extends-bundle       2.1.10   
sonata-project/exporter                  1.7.0           
sonata-project/formatter-bundle          3.1.0    
sonata-project/google-authenticator      1.0.2 
sonata-project/intl-bundle               2.2.4         
sonata-project/media-bundle              3.3.0     
sonata-project/news-bundle               3.0.0     
sonata-project/notification-bundle       3.0.0   
sonata-project/user-bundle               3.2.0       

#### Symfony packages
symfony/monolog-bundle     2.11.3 
symfony/phpunit-bridge     v2.8.15 
symfony/polyfill-apcu      v1.3.0 
symfony/polyfill-intl-icu  v1.3.0 
symfony/polyfill-mbstring  v1.3.0
symfony/polyfill-php54     v1.3.0 
symfony/polyfill-php55     v1.3.0 
symfony/polyfill-php56     v1.3.0 
symfony/polyfill-php70     v1.3.0 
symfony/polyfill-util      v1.3.0  
symfony/security-acl       v3.0.0
symfony/swiftmailer-bundle v2.4.2
symfony/symfony            v2.8.15 

#### PHP version
PHP 5.6.10

## Subject
sonata media bundle 3

I've uploaded image

but when i want to use this ( {% path image.image, 'small' %} ) helper i got nothing ,

try to change permission with chmod 777 -R in web/uploads , but still not working ,

it just can handle this helper  {% path image.image, 'reference' %} , because already exist on upload directory , but can't generate

**Comment by greg0ire** [comment]
There's a template for issues, why did you ignore it?

**Comment by ahbaqdadi** [comment]
is it OK  now ?

**Comment by greg0ire** [comment]
Yes it is. But now, if your issue is with the media bundle, why do you report it on the admin repository?
