### ISSUE TITLE
[RFC] FormMapper : decouple display logic from building logic

### ISSUE THREAD

**Issue by fbourigault** [sonata-project/SonataAdminBundle#4243]
In symfony-cmf, the plan is to provide alongside each Model a FormType which would be reused by anybody building an user interface for those model edition.

A reusable FormType was built few month ago for the StaticContent model but, using this FormType within sonata was a little bit painful because of the coupling between form building logic and form display logic (tabs/groups) in sonata's FormMapper.

What was done in the StaticContentAdmin class is to build the FormType using the FormFactory and then steal each children to use them in the FormMapper.

```php
    protected function configureFormFields(FormMapper $formMapper)
    {
        $builder = $formMapper->getFormBuilder()->getFormFactory()->createBuilder(StaticContentType::class, null, [
            'readonly_parent_document' => (bool) $this->id($this->getSubject()),
        ]);
        $formMapper
            ->with('form.group_general')
                ->add($builder->get('parentDocument'))
                ->add($builder->get('name'))
                ->add($builder->get('title'))
                ->add($builder->get('body'))
            ->end()
        ;
    }
```

This approach looks very hacky and disallow the use of events on the FormType.

As you can see, the problem is that we are controlling fields ordering/grouping/tabbing while building the form. A developer displaying this FormType without any admin bundle would simply control ordering/grouping/tabbing within twig views.

This is an open discussion on how we can decouple form display logic and form building logic.

**Comment by greg0ire** [comment]
I think there should be a new method in [the `BaseGroupedMapper` class](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Mapper/BaseGroupedMapper.php) for this use case, allowing to redefine the groups from a simple hash associating a group label with field names.

**Comment by fbourigault** [comment]
More or less something like making `BaseGroupedMapper::setTabs` public?

IIRC, there is an other problem: you can't add a single FormType without calling first `FormMapper::with`.

**Comment by greg0ire** [comment]
> IIRC, there is an other problem: you can't add a single FormType without calling first FormMapper::with.

Are you sure?

What about [this line](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Mapper/BaseGroupedMapper.php#L286) then ?

**Comment by greg0ire** [comment]
> More or less something like making BaseGroupedMapper::setTabs public?

I don't think you have to, because you're inheriting from this class when you are in an admin…

**Comment by fbourigault** [comment]
I think we must have a look at `Sonata\AdminBundle\Admin\AbstractAdmin::setFormTabs()`, `Sonata\AdminBundle\Admin\AbstractAdmin::setFormGroups()`

**Comment by greg0ire** [comment]
Might be a solution indeed, but I don't know if the usage is as simple as you wish.

**Comment by fbourigault** [comment]
I looked at what can be done to achieve this and sadly I think we can't do anything as the added FormType is seen as a whole by the FormMapper. Allowing a such case would be a lot of work, but in an architectural point of view, I don't know if it's a best practice to use FormTypes bound to a top level entity.
