### ISSUE TITLE
Template not found list_outer_rows_tree.html.twig

### ISSUE THREAD

**Issue by vmtzkr** [sonata-project/SonataAdminBundle#4266]
### Environment
MacOS Sierra / XAMPP

#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.10.3 The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/classification-bundle     3.2.0  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.1.2  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0  Lightweight Exporter library
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.2.4  Symfony SonataIntlBundle
sonata-project/media-bundle              3.3.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0  Symfony SonataNotificationBundle
sonata-project/user-bundle               3.2.0  Symfony SonataUserBundle
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v2.8.15 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.15 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 5.6.27 (cli) (built: Oct 23 2016 11:47:58) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

## Steps to reproduce
Download the 3.x branch and try to find the template under the defined location. This location is specified in the config yaml (https://sonata-project.org/bundles/admin/master/doc/reference/configuration.html).

## Expected results
The template should be there.

## Actual results
Unable to find template "SonataAdminBundle:CRUD:list_outer_rows_tree.html.twig" (looked into: /Users/***/***/***/app/Resources/views, /Users/***/***/***/vendor/symfony/symfony/src/Symfony/Bridge/Twig/Resources/views/Form, /Users/***/***/***/vendor/knplabs/knp-menu/src/Knp/Menu/Resources/views) in SonataAdminBundle:CRUD:base_list.html.twig at line 76.

**Comment by greg0ire** [comment]
You should format that properly.

**Comment by borjadinamic** [comment]
Any fix for this issue? The bug stills there.

**Comment by greg0ire** [comment]
@borjadinamic can you have a look into it?

**Comment by RedPaes** [comment]
Run into the same Issue. 
I don't found this file on searching for it in the sonata-admin Repo. 
Where should it come from?

**Comment by greg0ire** [comment]
@RedPaes I think it's an empty variable which causes that: 

```
locate list_outer_rows     
/home/gparis/dev/SonataAdminBundle/Resources/views/CRUD/list_outer_rows_list.html.twig
/home/gparis/dev/SonataAdminBundle/Resources/views/CRUD/list_outer_rows_mosaic.html.twig

```

**Comment by RedPaes** [comment]
Yes this is the problem. Found the solution i use the sonata-admin-tree-bundle there i forgot to add the AdminController to the service: 
`  admin.category:
      class: TopangeboteBundle\Admin\CategoryAdmin
      arguments: [~, TopangeboteBundle\Entity\Category,TopangeboteBundle:Admin\CategoryAdmin, 'name' ]
 `
( I know is not a problem from sonata-admin but maybe usefull for somewhere else.)

But as i understand the sonata admin bundle does not provide any tree functionality. Only through other bundles?
So should this list_outer_rows_tree.html.twig life in the admin bundle or third part software? 
So is a issue of documentation of sonata-admin or is the plan to implement somthing like   https://github.com/redco/sonata-admin-tree-bundle does?
@greg0ire : Thank you for your fast reply.

**Comment by greg0ire** [comment]
Not sure. Please have a look at the history to see who introduced the tree feature and ping that person

**Comment by Ragash** [comment]
The bug is still here. i have the exact same problem

**Comment by greg0ire** [comment]
> Please have a look at the history to see who introduced the tree feature and ping that person

**Comment by greg0ire** [comment]
Why not?

**Comment by Ragash** [comment]
Still learning how using github effectively, in anycases i searched even into the 2.x to go even more back to the history, but it seems that twig file is missing from the 2012

**Comment by greg0ire** [comment]
You could use git, the cli tool, with the `--follow` in case the files was renamed `git log --follow -p path`

**Comment by jordisala1991** [comment]
It was added here: https://github.com/sonata-project/SonataAdminBundle/commit/7d0322b53622ac506ec876a1bb19019ec58d3d99

Seems like it was half implemented. But the template was never put in place.

**Comment by boogiewoogieman** [comment]
Has anyone found the missing file yet?

**Comment by greg0ire** [comment]
@boogiewoogieman there is nothing to find, it never existed, as said before.

**Comment by phso** [comment]
im having the same exact problem with the missing template: 
`Unable to find template "@SonataAdmin/CRUD/list_outer_rows_tree.html.twig" (looked into: /var/www/vendor/sonata-project/admin-bundle/src/Resources/views) in @SonataAdmin/CRUD/base_list.html.twig at line 94.`
what is the best way to fix that issue?  i tried just to create the template within the given path but that does somehow not resolve the problem.
