### ISSUE TITLE
Triggering a JQuery event in Admin.setup_list_modal in Admin.js

### ISSUE THREAD

**Issue by RomainSanchez** [sonata-project/SonataAdminBundle#4270]
## Subject

It would be usefull (at least to me) to trigger a jquery event (something like 'sonata-admin-setup-list-modal') in the `Admin.setup_list_modal()` function of Admin.js.

It makes sense as such an event ('sonata-admin-append-form-element') is triggered when `sonata_type_model` adds a children form 'inline' so this new event would correspond to when `sonata_type_model` sets up the children form as modal

I already have a PR (one liner) ready  if needed

**Comment by greg0ire** [comment]
Please do submit a PR (with docs please).
