### ISSUE TITLE
sonata_type_admin form type does not fire getNewInstance()

### ISSUE THREAD

**Issue by c0ntax** [sonata-project/SonataAdminBundle#4275]
#### Sonata packages

```bash
$ composer show sonata-project/*

sonata-project/admin-bundle              3.10.3 The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.1.2  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.0.1  Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/user-bundle               3.2.0  Symfony SonataUserBundle
```

#### Symfony packages

```bash
$ composer show symfony/*

symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v2.8.16 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v2.8.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.16 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v

PHP 5.5.9-1ubuntu4.20 (cli) (built: Oct  3 2016 13:00:37) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with blackfire v1.14.1~linux-x64-non_zts55, https://blackfire.io, by Blackfireio Inc.
```

## Subject

When using the sonata_type_admin form type to embed an entity into a parent entity, the getNewInstance() method of the child entity is never executed, thus if you're using it to create consistent default values for an entity both embeded as a child or in its own admin page, you can't.

## Steps to reproduce

1.  Create two entities and associated admins with the parent/child relationship
2. Ensure that the child entity has at least one settable property (let's call it 'thing')
3. In the child Admin entity, add:
```php
    public function getNewInstance()
    {
        $entity = parent::getNewInstance();
        $entity->setThing('default value');
    }
```
4. In the parent admin entity, add the child in:
```php
    protected function configureFormFields(FormMapper $form)
    {
        $form
            ->add('child', 'sonata_type_admin')
        ;
    }
```
5. View the parent admin entity in your browser

## Expected results

The child admin entity should be displayed inside it's parent and there should be a prefilled ```thing``` field with the data ```default value``` displayed within in.

## Actual results

The ```thing``` field is present, but the default value is not.

## Other info

Although it's possible to set defaults in several other ways to set default values, using getNewInstance() and setting the defaults in there seems to be the 'cleanest' way to me. The other alternatives (and why I don't like using them are):

1. The most 'Doctrine' way of doing this is to define the value of the default in the entity's property definition:
```php
class Entity
{
    private $thing = 'default value';
}
```
That's fine for 90% of all cases, but where Doctrine gets a little vague on defaults is, what if the property that you want to set a default to is another entity that needs to be loaded from the database? Putting an entity manager inside a Doctrine entity so that you can populate this value is a bit no-no, so you have to populate these values externally
2. Use the ```data``` option to set the value in the child entity's ```configureFormFields```.
```php
    protected function configureFormFields(FormMapper $form)
    {
        $form
            ->add('thing', null, ['data' => 'default value'])
        ;
    }
```
Sadly, although Symfony's Form handling is really good, populating a pre-filled default value is still a bone of contention for developers. Setting ```data``` stamps over any pre-existing value and ```empty_data``` only sets the data on the way in, thus not displaying it. Thus you need to check for an existing value first and use that in ```data``` (or not use ```data``` at all) or set your default.
3. Use the ```data``` option to set the child in the parent entity's ```configureFormFields```.
```php
    protected function configureFormFields(FormMapper $form)
    {
        $child = null;
        if ($this->getSubject()->getChild() === null) {
            $child = new Child();
            $child->setThing('default value');
        } else {
            $child = $this->getSubject()->getChild();
        }
        $form
            ->add('child', 'sonata_type_admin', ['data' => $child])
        ;
    }
```
That logic will always stamp over any data that already exists, so you then have to come up with a nice way of checking for pre-existing values in ```$this->getSubject()``` which when submitting inline admins seems to not be populated. Also, with this method, I have to set my default value on two different places if I'm allowing the Admin to be embedded in the parent and also be a free standing Admin (unless I make factory methods obviously)

Can has fix please? ;-)

**Comment by c0ntax** [comment]
On further investigation of this issue, it seems that the limiting factor of getNewInstance() being called or not appears to be the number of Admins called in to the parent Admin.

For example, if I have the following entity Admin structure:

- Parent
  - Child A
    - Child B
  - Child C

getNewInstance() is called on Parent and Child A but not Child B, C or any other ones that are rendered *after* Child A.

**Comment by c0ntax** [comment]
And more mysteriously than this, any default values that are defined in Child B and Child C's class definition, e.g.

```php
class ChildB
{
    private $var = 'default value';
    private $otherVar;
    public function __construct()
    {
        $this->otherVar = 'something else';
    }
}
```

also do not show up. The objects appear completed nulled out.

**Comment by tobemedia** [comment]
Same problem. getNewInstance() is called in GET requests but not in POST requests (which are used in embedded Admins to do calls like  */core/append-form-field-element?code=*&elementId=s58f702ca5bc85_addresses&objectId=3&uniqid=s58f702ca5bc85

**Comment by greg0ire** [comment]
Can any of you try to see if [this line](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Form/Extension/Field/Type/FormTypeFieldExtension.php#L220) and the code block around are executed, or should be?

**Comment by vyshkant** [comment]
@greg0ire in my case the method `FormTypeFieldExtension::getValueFromFieldDescription` is not invoked so  the [line](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Form/Extension/Field/Type/FormTypeFieldExtension.php#L220)  is not executed.

**Comment by greg0ire** [comment]
The only call is [here](https://github.com/sonata-project/SonataAdminBundle/blob/master/Twig/Extension/SonataAdminExtension.php#L147), which means there seems to be no call to achieve what you are expecting... I think. If I were you, I would debug [this line](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Form/Type/AdminType.php#L55). Maybe this is where this should be implemented.

**Comment by Jeace** [comment]
same problem here !

**Comment by c0ntax** [comment]
I can confirm that this has been fixed (in my codebase at least) by https://github.com/sonata-project/SonataAdminBundle/pull/4571

**Comment by LewisW** [comment]
The same thing seems to happen with `sonata_type_collection`. I'll investigate further when I have more time but until then this seems to be a workaround for anyone with the same issue:

```php
'type_options' => [
    'empty_data' => function() {
        return $this->getConfigurationPool()->getAdminByAdminCode('mycode')->getNewInstance();
    }
]
```
