### ISSUE TITLE
I need to add or create a new button  

### ISSUE THREAD

**Issue by dhafer1** [sonata-project/SonataAdminBundle#4279]
#### Sonata packages

```bash
$ composer show sonata-project/*
# Put the result here.
```

#### Symfony packages

```bash
$ composer show symfony/*
# Put the result here.
```

#### PHP version

```bash
$ php -v
# Put the result here.
```

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
