### ISSUE TITLE
Unused $choiceList property in ModelsToArrayTransformer

### ISSUE THREAD

**Issue by RomainSanchez** [sonata-project/SonataAdminBundle#4283]
## Subject

In `ModelstoArrayTransformer` there is a `ChoiceList` protected property and constructor argument that are not used anywhere in the class.It looks like it was a copy paste mistake from `LegacyModelsToArrayTransformer`.
https://github.com/sonata-project/SonataAdminBundle/blob/master/Form/DataTransformer/ModelsToArrayTransformer.php

I was about to make a PR but i have two questions: 

Should this choiceList be handled (being chosen over the `$collection` argument of `transform` maybe) and replaced by a `ChoiceLoader` or removed?

If it is removed is it a BC break as `ModelType` instanciates a `ModelsToArrayTransformer` with this
constructor?

**Comment by greg0ire** [comment]
The property is protected, so removing it would be a BC-break.
Changing the constructor would be a BC-break too.
The usefulness of this has been removed in 3e7ad359411a5f4ae119d9dc3ef26b3e44716fd1

If you want to contribute something switch to 3.x and:

1. implement a magic getter that triggers a deprecation notice whenever the property is accessed
2. remove the type hinting on the second parameter on the constructor, make the third parameters, and then simulate the old signature and the new signature with `func_get_args()` / `func_num_args()`
3. add instructions for next major (remove the property, use a signature with 2 arguments, type hinting, and make the second argument mandatory).

**Comment by RomainSanchez** [comment]
> implement a magic getter that triggers a deprecation notice whenever the property is accessed

Have an example somewhere ?

**Comment by RomainSanchez** [comment]
What i have so far

```php
/**
     * @var ModelChoiceList
     * @deprecated
     */
    protected $choiceList;

    /**
     * ModelsToArrayTransformer constructor.
     *
     * @param ModelChoiceList|LazyChoiceList|ModelChoiceLoader $choiceList
     * @param ModelManagerInterface                            $modelManager
     * @param $class
     *
     * @throws RuntimeException
     */
    public function __construct($choiceList, $modelManager, $class)
    {   
        /*
        NEXT MAJOR: Remove constructor() and legacyConstructor() methods, $choiceList property and argument
        __construct signature should be : public function construct(ModelManager $modelManager, $class)
         */
        if(func_num_args(__FUNCTION__) == 3) {
            $this->constructor(func_get_args(__FUNCTION__));
        }else {
            $this->legacyConstructor(func_get_args(__FUNCTION__));
        }
    }

/**
     * Simulates the old constructor
     * 
     * @param array $args
     * @throws RuntimeException
     */
    private function legacyConstructor($args)
    {
        $choiceList = $args[0];
        
        if (!$choiceList instanceof ModelChoiceList
            && !$choiceList instanceof ModelChoiceLoader
            && !$choiceList instanceof LazyChoiceList) {
            throw new RuntimeException('First param passed to ModelsToArrayTransformer should be instance of
                ModelChoiceLoader or ModelChoiceList or LazyChoiceList');
        }

        $this->choiceList = $choiceList;
        $this->modelManager = $args[1];
        $this->class = $args[2];
    }
    
    /**
     * Simulates the new constructor
     * 
     * @param array $args
     */
    private function constructor($args)
    {
        $this->modelManager = $args[0];
        $this->class = $args[1];
    }
```

**Comment by greg0ire** [comment]
[here is an example](https://github.com/symfony/symfony/commit/f2691d5ed5d6717e2d43452196841c7db8fc9455#diff-20cf558e59446c9795003885bd09e1a3R108)

**Comment by greg0ire** [comment]
Looks good! I think you can move `constructor` to `__construct`, but keep `legacyConstructor`, it will make the diff to next major smaller. Please make a PR, it will be easier to discuss this piece of code, but you got it right :)

**Comment by RomainSanchez** [comment]
should i implement __get __set __isset and __unset or just __get ?

**Comment by greg0ire** [comment]
All of them, if you feel up to it.

**Comment by RomainSanchez** [comment]
I don't see anything regarding data transformers in the docs.Also `ModelsToArrayTransformer` is the only data transformer in AdminBundle not having a test class.

**Comment by greg0ire** [comment]
I think it's not meant to be used directly, but when using `ModelType`, which would explain the lack of code. Writing tests would be the easiest way for you to test your changes though, I think. Don't hesitate to ask if you need help writing them. Also, please make sure to update the instantiation inside `ModelType`.
