### ISSUE TITLE
Warning: get_class() expects parameter 1 to be object, string given

### ISSUE THREAD

**Issue by xmon** [sonata-project/SonataAdminBundle#4299]
#### Sonata packages

sonata-project/admin-bundle              2.3.10             Symfony SonataAdminBundle
sonata-project/block-bundle              2.2.15             Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               2.3.11             Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2                Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 2.3.4              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10             Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0              Lightweight Exporter library
sonata-project/formatter-bundle          2.3.4              Symfony SonataFormatterBundle
sonata-project/google-authenticator      1.0.2              Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.3.0              Symfony SonataIntlBundle
sonata-project/media-bundle              2.3.4              Symfony SonataMediaBundle
sonata-project/notification-bundle       2.3.4              Symfony SonataNotificationBundle
sonata-project/seo-bundle                1.1.10             Symfony SonataSeoBundle
sonata-project/user-bundle               2.2.5              Symfony SonataUserBundle

#### Symfony packages

symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v2.8.16 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v2.8.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.16 The Symfony PHP framework

#### PHP version

PHP 5.4.45-0+deb7u2 (cli) (built: Oct 17 2015 08:26:31) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies

## Subject

I follow tutorial [SORTABLE BEHAVIOR IN ADMIN LISTING](https://sonata-project.org/bundles/admin/3-x/doc/cookbook/recipe_sortable_listing.html) but after Symfony update stopped working and throws an error.

## Steps to reproduce
To follow tutorial [SORTABLE BEHAVIOR IN ADMIN LISTING](https://sonata-project.org/bundles/admin/3-x/doc/cookbook/recipe_sortable_listing.html)

## Expected results
Order in admin list.

## Actual results
```php
Warning: get_class() expects parameter 1 to be object, string given
500 Internal Server Error - ContextErrorException
```

1. in app/cache/dev/classes.php at line 6835
```php
}
public static function getClass($object)
{
return self::getRealClass(get_class($object));
}
public static function getParentClass($className)
{
```

2. at ErrorHandler ->handleError ('2', 'get_class() expects parameter 1 to be object, string given', '/var/www/virtual/domain.es/dev/htdocs/app/cache/dev/classes.php', '6835', array('object' => 'AppBundle\Entity\RedesSociales')) 
3. at get_class ('AppBundle\Entity\RedesSociales') in app/cache/dev/classes.php at line 6835   + 
4. at ClassUtils ::getClass ('AppBundle\Entity\RedesSociales') in vendor/pixassociates/sortable-behavior-bundle/Pix/SortableBehaviorBundle/Services/PositionORMHandler.php at line 48   + 
5. at PositionORMHandler ->getLastPosition ('AppBundle\Entity\RedesSociales')  in src/AppBundle/Admin/RedesSocialesAdmin.php at line 79   + 
6. at RedesSocialesAdmin ->configureListFields (object(ListMapper)) in app/cache/dev/classes.php at line 9832   + 
7. at Admin ->buildList () in app/cache/dev/classes.php at line 10420   + 
8. at Admin ->hasListFieldDescription ('sort') in app/cache/dev/classes.php at line 9878   + 
9. at Admin ->buildDatagrid () in app/cache/dev/classes.php at line 10201   + 
10. at Admin ->getDatagrid () in vendor/sonata-project/admin-bundle/Controller/CRUDController.php at line 216   + 
11. at CRUDController ->listAction () 
12. at call_user_func_array (array(object(SortableAdminController), 'listAction'), array()) in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 144   + 
13. at HttpKernel ->handleRaw (object(Request), '1') in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 64   + 
14. at HttpKernel ->handle (object(Request), '1', true) in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/DependencyInjection/ContainerAwareHttpKernel.php at line 69   + 
15. at ContainerAwareHttpKernel ->handle (object(Request), '1', true) in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 185   + 
16. at Kernel ->handle (object(Request)) in web/app_dev.php at line 30

**Comment by LaurentFl** [comment]
Same problem since last composer update...

**Comment by xmon** [comment]
Hi solve downgrade pixSortableBehaviorBundle, [here](https://github.com/pix-digital/pixSortableBehaviorBundle/issues/57) more details

**Comment by LaurentFl** [comment]
I've found a solution better than downgrading.
We can see in this [commit](https://github.com/pix-digital/pixSortableBehaviorBundle/commit/5c3d1a122f8d177e817c19e2fe637bbe9847bde8) that the $last_position is not needed anymore (in v1.1).
So simply remove from your code the variable $last_position and the line $this->last_position = $this->positionService->getLastPosition($this->getRoot()->getClass());
You can also remove the $positionService variable, the setPositionService method and the call in the "services.yml" file.

If you have a custom template, don't forget to adapt it with the new twig variables, like in [pixSortableBehaviorBundle/Resources/views/Default/_sort.html.twig](https://github.com/pix-digital/pixSortableBehaviorBundle/blob/v1.1/Resources/views/Default/_sort.html.twig)

It's easier now but the doc is not up to date...

**Comment by xmon** [comment]
hi man, great!!

**Comment by Yessine-abid** [comment]
Error symfony 2.8 page_bundle in sonata bundle 
when i execute this command the created site functions normally php app/console sonata:page:create-site but when i create it with the graphical interface it shows me this error

> Warning: get_class() expects parameter 1 to be object, integer given

Stack Trace in vendor/doctrine/common/lib/Doctrine/Common/Util/ClassUtils.php at line 58 -

```
public static function getClass($object)
{
    return self::getRealClass(get_class($object));
}
```

https://github.com/sonata-project/SonataPageBundle/issues/847
