### ISSUE TITLE
Remove famfam icons

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataAdminBundle#4314]
We moved from glyphicons to font-awesome, but still have the famfam icons in our project:

https://github.com/sonata-project/SonataAdminBundle/tree/master/Resources/public/famfamfam

Based on comment https://github.com/sonata-project/SonataAdminBundle/issues/3291#issuecomment-278282385, the should be removed.

Should this be done against `master`?

**Comment by jordisala1991** [comment]
This was fixed on #4315
