### ISSUE TITLE
Entering a date like "01/23/20017" causes a Doctrine exception even with @Assert\Date

### ISSUE THREAD

**Issue by gnutix** [sonata-project/SonataAdminBundle#4318]
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              2.2.11 Symfony SonataAdminBundle
sonata-project/block-bundle              2.2.11 Symfony SonataBlockBundle
sonata-project/cache                     1.0.6  Cache library
sonata-project/cache-bundle              2.1.6  This bundle provides caching services
sonata-project/core-bundle               2.2.5  Symfony SonataCoreBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 2.2.7  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.6  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.4.0  Lightweight Exporter library
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/jquery-bundle             1.8.3  Symfony SonatajQueryBundle
sonata-project/user-bundle               2.2.4  Symfony SonataUserBundle
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.7.0  Integrates Assetic into Symfony2
symfony/monolog-bundle     2.8.1   Symfony MonologBundle
symfony/swiftmailer-bundle v2.3.8  Symfony SwiftmailerBundle
symfony/symfony            v2.3.37 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 5.6.29-0+deb8u1 (cli) (built: Dec 13 2016 16:02:08) 
```

## Steps to reproduce

1. Create an Entity with a `type="date"` field.
2. Add a `\Symfony\Component\Validator\Constraints\Date` validation on the field.
3. Create an Admin class for this Entity.
4. Edit the Entity in Sonata Admin and enter a date with 5 characters for the year (like 20017).
5. Submit, **the data is saved into the database**, and then you get an Exception from Doctrine when it tries to display the page again.
6. Try to access any edit form for this Entity, same Exception (so it's not only when displaying the page for the Entity with the wrong data, but any edit page for that Entity).

## Expected results

A validation message should be displayed on the form to prevent this kind of input, I guess. At the same time, it is a valid date (according to PHP at least)... just far away in the future (and probably computers as we know them won't exist anymore).

## Actual results

Doctrine throws an Exception because the format doesn't respect `YYYY-mm-dd`.

**Comment by greg0ire** [comment]
Did you call `setValidator`? IIRC it's necessary.

**Comment by greg0ire** [comment]
> At the same time, it is a valid date (according to PHP at least)... just far away in the future (and probably computers as we know them won't exist anymore).

Good point lol! What if you try something invalid like `32/32/2017`?

**Comment by gnutix** [comment]
I did not call setValidator in the Admin class service configuration. I can't even enter `32/32/2017` because the HTML `date` input type prevents any number above 31 for day and month. However, it allows up to `999999` as a year.

**Comment by greg0ire** [comment]
Change `date` to `text` with your browser inspector and try again. And call `setValidator` in `admin.yml` IIRC, it's the way to go. And I even think it's documented. Did you check the docs?

**Comment by gnutix** [comment]
I don't know, it's a 4+ years old project with deprecated vendors. I fixed it manually using a custom validator. Opening the issue for me was more a way to point out that PHP thinks 20017 is a valid date, and I'm wondering if Sonata/Symfony/Doctrine should as well. So it's more a question for debate than a technical issue.

**Comment by greg0ire** [comment]
Oh right, your vendors are very out of date… sorry, but we don't offer support for that. If you want to chat about that head to https://symfony-devs.slack.com/messages/sonata/ … this is an issue tracker.

**Comment by gnutix** [comment]
Thanks for the link, will do ASAP.
