### ISSUE TITLE
Update Cookbook recipe for Sortable behaviour

### ISSUE THREAD

**Issue by mvhirsch** [sonata-project/SonataAdminBundle#4326]
### Environment

* PHP 7.0.14
* Sonata-Admin 3.13.0
* pixassociates/sortable-behavior-bundle 1.2

## Subject

Using Sonata/Admin with Sortable-Behaviour as described in [Cookbook "Sortable behaviour" ](https://sonata-project.org/bundles/admin/3-x/doc/cookbook/recipe_sortable_listing.html) will lead to an exception, since pixassociates/sortable-behavior-bundle v1.1.

This is due of the fact the author of this package silently removed the "$last_position" handling, which is not needed anymore. See commit https://github.com/pix-digital/pixSortableBehaviorBundle/commit/5c3d1a122f8d177e817c19e2fe637bbe9847bde8

This was already discussed https://github.com/sonata-project/SonataAdminBundle/issues/4299#issuecomment-276642050 and https://github.com/pix-digital/pixSortableBehaviorBundle/issues/57.

As I'm not familiar in how to upgrade the docs, I'll ask you for help.
Should I make a PR with "since Version v1.1 it's no longer necessary to handle "$last_position" [...]" or remove the paragraph entirely?

## Steps to reproduce

* Install latest sonata-project/admin-bundle
* Install pixassociates/sortable-behavior-bundle at least v1.1
* Follow [Cookbook "Sortable behaviour" ](https://sonata-project.org/bundles/admin/3-x/doc/cookbook/recipe_sortable_listing.html)
* Open the Admin's list view

## Expected results

A list view to work with.

## Actual results

An exception.

**Comment by greg0ire** [comment]
I'd remove the last §, but ask people to install a version >= 1.1
