### ISSUE TITLE
'list' action hardcoded in base_list and base_links

### ISSUE THREAD

**Issue by wodka** [sonata-project/SonataAdminBundle#4338]
## Subject

I wanted to add "tabs" for different lists on the same admin. This works ok but I needed to copy some templates just to get it to work. Awesome would be if the links would actually use the action property if they refer to the same page.

## Workaround

the files contain hardcoded **'list'** references, I changed them to **action**:

- CRUD/base_list.html.twig
- Pager/base_links.html.twig

## How did I add the lists?

The admin class got 2 separate routes:

```php
    public function configureRoutes(RouteCollection $collection)
    {
        parent::configureRoutes($collection);

        $collection->add('listRequest');
        $collection->add('listOrder');
    }
```

and the controller 2 separate methods:
```php
// fancyListAction uses the given action for the list
    public function listRequestAction()
    {
        return $this->fancyListAction('listRequest');
    }

    public function listOrderAction()
    {
        return $this->fancyListAction('listOrder');
    }
```

(I removed the additional filtering for results)

**Comment by OskarStark** [comment]
sounds interesting to have an option to overwrite the default list route and add some tabs for different lists with (different filters and/or queries) ?
