### ISSUE TITLE
VIEW vs SHOW

### ISSUE THREAD

**Issue by axzx** [sonata-project/SonataAdminBundle#4359]
What is the difference between a VIEW and a SHOW?
Is used in `isGranted` in views.

**Comment by greg0ire** [comment]
On is a permission, the other an action. Both shouldn't be used with `isGranted`. If they are, you found a bug.

**Comment by axzx** [comment]
thanks.

only here:

https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/CRUD/list_outer_rows_mosaic.html.twig#L63

https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/doc/cookbook/recipe_customizing_a_mosaic_list.rst

**Comment by greg0ire** [comment]
I think you definitely found a bug :) Can you please fix it?
