### ISSUE TITLE
Best place for access conditions

### ISSUE THREAD

**Issue by axzx** [sonata-project/SonataAdminBundle#4364]
Where is the best place to save access conditions? I need to: block the action function and also to hide the buttons.
I have role `ROLE_USER_ADMIN_USER_VIEW_OWN` and I use handler `sonata.admin.security.handler.role`.
I want to give access to action `show` for users who have this role.

**Comment by jordisala1991** [comment]
For general support and questions, please use http://stackoverflow.com/questions/tagged/sonata

Closing as this is not an issue with Sonata or a feature request. If you think this is question could be converted into a new feature for Sonata, feel free to open a new issue with your proposal.

(I would probably try to block access to all show routes unless you have that role, and use a custom button that only appears if you have that role, without giving too much thought to it)
