### ISSUE TITLE
Incorrect handling of boolean types in HelperController

### ISSUE THREAD

**Issue by gremo** [sonata-project/SonataAdminBundle#4368]
#### Sonata packages

```bash
$ composer show sonata-project/*

sonata-project/admin-bundle              3.13.0
sonata-project/block-bundle              3.3.1
sonata-project/cache                     1.0.7
sonata-project/cache-bundle              2.3.1
sonata-project/classification-bundle     3.2.1
sonata-project/core-bundle               3.2.0
sonata-project/datagrid-bundle           2.2.1
sonata-project/doctrine-extensions       1.0.2
sonata-project/doctrine-orm-admin-bundle 3.1.3
sonata-project/easy-extends-bundle       2.1.10
sonata-project/exporter                  1.7.1
sonata-project/formatter-bundle          3.2.0
sonata-project/google-authenticator      1.0.2
sonata-project/intl-bundle               2.3.0
sonata-project/media-bundle              3.4.0
sonata-project/notification-bundle       3.1.0
sonata-project/page-bundle               3.3.0
sonata-project/seo-bundle                2.1.0
sonata-project/user-bundle               3.2.1

```

#### Symfony packages

```bash
$ composer show symfony/*

symfony/assetic-bundle     v2.8.1
symfony/monolog-bundle     v3.0.3
symfony/phpunit-bridge     v2.8.18
symfony/polyfill-apcu      v1.3.0
symfony/polyfill-intl-icu  v1.3.0
symfony/polyfill-mbstring  v1.3.0
symfony/polyfill-php54     v1.3.0
symfony/polyfill-php55     v1.3.0
symfony/polyfill-php56     v1.3.0
symfony/polyfill-php70     v1.3.0
symfony/polyfill-util      v1.3.0
symfony/security-acl       v2.8.0
symfony/swiftmailer-bundle v2.5.3
symfony/symfony            v2.8.18
```

#### PHP version

```bash
$ php -v

PHP 5.5.31 (cli) (built: Jan  6 2016 12:57:50)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

## Subject

The `HelperController `is unable to handle boolean values.

## Steps to reproduce

Using the SonataPageBundle which sends a POST XMLHttpRequest (with form data: `value=false`) request to the following URL:

`/admin/core/set-object-field-value?objectId=21&context=list&field=enabled&code=sonata.page.admin.block`

.. in order to update the block with `id `21 and set the field `enabled `to `false`.

## Expected results

Block is update and a status code of 200 is returned.

## Actual results

Status code 500 along with the following exception (note that false is actually a string, not the boolean false):

> [3/4] DriverException: An exception occurred while executing 'UPDATE block SET enabled = ?, updated_at = ? WHERE id = ?' with params ["false", "2017-03-08 01:06:54", 21]:
> 
> SQLSTATE[HY000]: General error: 1366 Incorrect integer value: 'false' for column 'enabled' at row 1

**Comment by greg0ire** [comment]
"integer"?!?

**Comment by gremo** [comment]
@greg0ire Yes, boolean types in Doctrine are actually TINYINT in MySQL. But Doctrine can't convert it to an integer because is `false` as string, not as `boolean`.
