### ISSUE TITLE
Dot-notation is always TextType in create/edit view.

### ISSUE THREAD

**Issue by jlamur** [sonata-project/SonataAdminBundle#4380]
#### Sonata packages

```bash
sonata-project/admin-bundle              3.13.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.1  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.2.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/intl-bundle               2.3.0  Symfony SonataIntlBundle
```

#### Symfony packages

```bash
symfony/symfony            v2.8.18 The Symfony PHP framework
```

#### PHP version

```bash
PHP 7.1.1
```

## Subject

Fields declared in `FormMapper` with a dot-notation are always rendered as basic text fields (ignoring the `FieldDescription`).

I'm not sure if this is a real bug, or if it have never worked this way because I never used the dot-notation before.

\* *dot-notation*: Accessing a field under a one to one / many to one relation, e.g. `user.email`.

N.B.: fields are well rendered within list/show views.

## Steps to reproduce

1. *For the purpose of keeping the snippet simple, I omitted `namespace`s, `use`s, and it's assumed that the `CommentAdmin` class is a well declared admin:*

```php
// src/AcmeBundle/Entity/Comment.php
/** @ORM\Entity */
class Comment {
    /** @ORM\Id @ORM\Column(type="integer") */
    public $id;

    /** @ORM\ManyToOne(targetEntity="User") */
    public $user; 

    public function __construct() {
        $this->user = new User;
    }
}

// src/AcmeBundle/Entity/User.php
/** @ORM\Entity */
class User {
    /** @ORM\Id @ORM\Column(type="integer") */
    public $id;

    /** @ORM\Column(type="boolean") */
    public $enabled;
}

// src/AcmeBundle/Admin/CommentAdmin.php
class CommentAdmin extends AbstractAdmin {
    public function configureFormFields(FormMapper $mapper) {
        $mapper->add('user.enabled');
    }
}
```

2. Go to the `CommentAdmin` create/edit route.

## Expected results

A nice checkbox.

## Actual results

An ugly text field.

# Current investigations

It seems that the `FieldDescription` is well set in the `FormMapper` (a `dump($formMapper)` asserts it).
So I guess that the `FieldDescription` is completly ignored.

# Questions

* Is it a bug or a missing feature?
* Would a PR to implement it be welcome?

**Comment by greg0ire** [comment]
It it's not documented, I'd say it's a missing feature, a bug otherwise.
A PR to implent it would be very welcome 👍

**Comment by jlamur** [comment]
After digging a lot into this issue, I found that it's the responsibility of the class `Symfony/Component/Form/FormFactory` to get the good type (depending on the `property_path` type option). **But this feature has never been implemented.**

I will open a PR for this on the Symfony repository, and hopefully Sonata will be able to profit from it without any change :)

I'm closing this issue.

**Comment by jlamur** [comment]
For traceability: I created a PR for this feature: [[Form] Fix FormFactory guesses with property_path option. (symfony/symfony#22469)](https://github.com/symfony/symfony/pull/22469).
