### ISSUE TITLE
Select just the given Discriminator Map type

### ISSUE THREAD

**Issue by DavidGarciaCat** [sonata-project/SonataAdminBundle#4382]
Hello,

## Subject

When I have a set of entities with a Doctrine Discriminator Map then I cannot add a filter to get just one type of all mapped entities, due SonataAdmin and SonataDoctrineORMAdminBundle are throwing an error.

## Example:

Entities with a Doctrine Discriminator Map

```php
/**
 * @ORM\Table(name="activities")
 * @ORM\Entity()
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *     "joined" = "...\JoinedActivity",
 *     "other" = "...\OtherActivity"
 * })
 */
abstract class Activity()
{
    abstract public function getType();
}

/**
 * @ORM\Entity()
 */
class JoinActivity extends Activity()
{
    const TYPE = 'joined';

    public function getType()
    {
        return self::type;
    }
}


/**
 * @ORM\Entity()
 */
class OtherActivity extends Activity()
{
    const TYPE = 'other';

    public function getType()
    {
        return self::type;
    }
}
```

Then I add the Sonata Admin filter:

```php
protected function configureDatagridFilters(DatagridMapper $filter)
{
    $filter->add(
        'type',
        null,
        [
            'label' => 'Activity Type',
        ],
        'choice',
        [
            'choices' => [
                JoinActivity::TYPE => ucfirst(JoinActivity::TYPE),
                OtherActivity::TYPE => ucfirst(OtherActivity::TYPE),
            ],
        ]
    );
}
```

## Expected results

Get a new filter to select just `joined` or `other` activities.

## Actual results

```
Notice: Undefined index: type
500 Internal Server Error - ContextErrorException
```

Any idea how I can fix it?

Thanks,

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.

**Comment by DavidGarciaCat** [comment]
Hi @core23 

I though this issue could track a bug due Sonata thrown an error reporting an existing column does not exist, but based on your comment I am wrong? Anyway, I will do that you say, and will follow those 2 links.

Cheers,
