### ISSUE TITLE
Default page sizes are confusing

### ISSUE THREAD

**Issue by Kolyunya** [sonata-project/SonataAdminBundle#4391]
### Environment
Not relevant.

#### Sonata packages

```bash
# not relevant
```

#### Symfony packages

```bash
# not relevant
```

#### PHP version

```bash
# not relevant
```

## Subject
**Disclamer**: yes, I do know that this property is easily configurable and I can override it. My point is that the default distribution must be as user-friendly as possible.

[Default page sizes](https://github.com/sonata-project/SonataAdminBundle/blob/f880155d92450a874bbdcad952c486cef882270e/Admin/AbstractAdmin.php#L169) are confusing. Admin panels are meant to be designed for non-technical staff. Non-technical staff is used to counting things in multiples of tens not twos. E.g. 10, 20, 50, 100, 500.

If you decide to stick to binary-based page sizes then what is the rationale behind having the last item equal to `192`? Why not `256` which would be consistent to the previous sequence elements?

## Steps to reproduce
Open any admin panel.

## Expected results
Expect to see decimal-based page sizes.

## Actual results
Page sizes are binary-based.

**Comment by greg0ire** [comment]
Never noticed it, but indeed, that's quite weird. No idea about `192`, which is even weirder. Can you have a look at the history?

**Comment by Kolyunya** [comment]
@greg0ire I did look up the history and it's there since forever.

**Comment by greg0ire** [comment]
With no explanation in the commit message or docs I guess? Then it's ok to change. That wouldn't even be a bc-break IMO

**Comment by Kolyunya** [comment]
@greg0ire I was able that it was decimal-based [in the past](https://github.com/sonata-project/SonataAdminBundle/commit/582c90af652a059b8a1a06ae6890ef1d0dc348ed#diff-81cd2da3c7ffebe278779869361e685aR199) but I wasn't able to actually find what happend next yet.

**Comment by greg0ire** [comment]
`git log -G perPageOptions -p` ?

**Comment by greg0ire** [comment]
Yields 5e9ce9f86897a06361c64300c46209bb114fce96

**Comment by greg0ire** [comment]
I guess it has to do with mozaic mode needing to display nicely.

**Comment by greg0ire** [comment]
I think you could either make a PR to add a comment explaining these slightly WTF values, or one that would introduce separate options depending on the current mode.

**Comment by Kolyunya** [comment]
Seems like `256` will fit nicely with `32` items per page.

B.t.w. `git log -G perPageOptions -p` returned other commit to me. Should I have activated some specific branch beforehand?

**Comment by greg0ire** [comment]
> Should I have activated some specific branch beforehand?

No, it's normal, it show all the commits that have a change that contains this. I hand picked this one after a cursory glance at this output.

**Comment by Kolyunya** [comment]
@greg0ire thanks for help!

**Comment by greg0ire** [comment]
My pleasure, thanks for caring :)

**Comment by jordisala1991** [comment]
Could be solved by changing 192 by 256
