### ISSUE TITLE
sonata_type_choice_field_mask empty_value throw exception

### ISSUE THREAD

**Issue by lalop** [sonata-project/SonataAdminBundle#4397]
Trying to use `sonata_type_choice_field_mask` as define in the documentation https://sonata-project.org/bundles/admin/3-x/doc/reference/form_types.html

The property `empty_value` seems to not be surported anymore, I get this error.

> The option "empty_value" does not exist. Defined options are: "action", "allow_extra_fields", "attr", "auto_initialize", "block_name", "by_reference", "choice_attr", "choice_label", "choice_loader", "choice_name", "choice_translation_domain", "choice_value", "choices", "choices_as_values", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "disabled", "empty_data", "error_bubbling", "error_mapping", "expanded", "extra_fields_message", "group_by", "horizontal_input_wrapper_class", "horizontal_label_class", "horizontal_label_offset_class", "inherit_data", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_format", "label_render", "map", "mapped", "method", "multiple", "placeholder", "post_max_size_message", "preferred_choices", "property_path", "required", "sonata_admin", "sonata_field_description", "sonata_help", "sortable", "translation_domain", "trim", "upload_max_size_message", "validation_groups".

**Comment by greg0ire** [comment]
Maybe it should be `placeholder` ? http://symfony.com/doc/current/reference/forms/types/choice.html#placeholder

**Comment by lalop** [comment]
This add a new choice :(

**Comment by greg0ire** [comment]
What about `empty_data` Not sure what you are trying to do btw…

**Comment by lalop** [comment]
In fact I wanted to add a kind of placeholder and I assume this is what `empty_value` was for.
Anyway if I opened this issue it's more to notice this error from the doc more than get a solution :)

**Comment by greg0ire** [comment]
So… `placeholder` doesn't do just that? If it does, can you make a PR to fix the docs?

**Comment by lalop** [comment]
I can just delete the `empty_value` reference since I don't know what it did

**Comment by greg0ire** [comment]
let me `cd ~/dev/symfony-docs` and do `git log -S empty_value`

**Comment by greg0ire** [comment]
> The ``placeholder`` option was introduced in Symfony 2.6 and replaces ``empty_value``, which is available prior to 2.6.

**Comment by greg0ire** [comment]
So you can purely and simply replace `empty_value` with placeholder, and if you do, please `grep` for it in the entire repo.

**Comment by lalop** [comment]
ok I will

**Comment by greg0ire** [comment]
Thanks a lot for contributing!

**Comment by lalop** [comment]
Should I migrate this too https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/Form/form_admin_fields.html.twig#L195 ?

**Comment by greg0ire** [comment]
I don't think so, b/c it will break projects of sf 2.3 users. Should be done on master though.
