### ISSUE TITLE
Batch action "stack" feature

### ISSUE THREAD

**Issue by symball** [sonata-project/SonataAdminBundle#4442]
## Make batch actions more flexible with a stack features

In a recent project I worked on, I added the ability to add many items to a "stack" prior to running a batch action. This meant that across a very large dataset, many searches could be made and then a batch action run once.

It was necessary because people would often want to combine a series of search results and then run a single action as opposed to the single action many times, an example being the generation of newsletter recipients prior to Campaign Monitor submission. Business found it very useful and, I'm wondering whether to try and move it upstream.

### It works as follows:
To build the stack, there is an extra batch action called "add to stack". Upon using the action, first the stack type would be checked (and emptied) if objects are of different type, the selected entries would then be added (or merged to avoid duplicates) to session variables.

### These session variables track the stack:
stackType: The name of the objects being added to the stack so that, UI can tell user what is in stack and also if a person were to try adding a different type, it would clear
stackCount: A simple counter of stack size so that the whole thing didn't need to be read just to get a count
stackValues: A simple associative array using the ID and __toString value

### In terms of user interface:
There is an area in the navbar which shows a button with stack type and size. Clicking it, makes a request to the server returning the full set in a modal window. Entries in the stack can be removed by simply here at the same time.

### In terms of using the stack:
When it comes time to using the stack, either at the last selection list proceed to select the desired batch action as normal.
Behind the scenes at this moment, preBatchAction was modified so that it would integrate the stack with the batch action.

### Guidance requested for feature if moving forward

- When creating this feature, the UI part was defined in base_list.html.twig list_filters_actions area. Do you consider this the correct place? If not, please state where
- The URL calls (addToStack, getStack, removeStackItem, clearStack) were all defined in the CRUDController. I believe this is the correct place for it but, again, please confirm

Please let me know your thoughts on the matter

**Comment by greg0ire** [comment]
> When creating this feature, the UI part was defined in base_list.html.twig list_filters_actions area. Do you consider this the correct place?

Link for the lazy : https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/CRUD/base_list.html.twig#L228

IMO, a brand new block would be the best place. Also, can you upload a screenshot of the stack?

> The URL calls (addToStack, getStack, removeStackItem, clearStack) were all defined in the CRUDController. I believe this is the correct place for it but, again, please confirm

Same here, a brand new controller would be best IMO

**Comment by symball** [comment]
Here's a screenshot taken of the feature after moving it from the header area to a new block within the batch action area.
In terms of experience, clicking on "View Stack" and removing individual item (using the cross button) are carried out by simple AJAX requests.
"Add to Stack" and "Clear stack" are carried out using page refreshes.

![batch-action-ui](https://cloud.githubusercontent.com/assets/10624537/24732965/020e483e-1aa7-11e7-8b5a-596963ee0a94.png)

**Comment by greg0ire** [comment]
There's one thing I don't understand yet : how do you choose to run a batch action on the stack or on the selected elements?

**Comment by symball** [comment]
A fair question and there are three situations:

1 - If you have a stack present, you can run the batch action without selecting any elements and it gets run on the stack.
2 - If you have a stack present and you select some elements prior to running the batch action, an array merge is performed (the selection is just a bunch of IDs anyway) and then the batch action is run
3 - If the stack is empty and you select some elements prior to running the batch action, only that selection will be used.

The priority is to try and use the stack, merging it with the "current selection" whether empty or not.

In the case where you have a stack and then try running a batch action using a different type of options, the stack is emptied prior to running the action because it would be "incompatible" with the operation.

**Comment by greg0ire** [comment]
I'm 👍 with this feature, it could be quite nice indeed, but if you want to contribute it, keep it mind that it should be fully documented and tested (so please write the docs, the tests and the code, in that order). I also think it should be introduced in 3.x in an opt-in way to maintain BC. @sonata-project/contributors ,WDYT? Should @symball go ahead and write a PR?

**Comment by OskarStark** [comment]
Sounds great, I like the Feature

**Comment by core23** [comment]
Looks like an interesting feature, but not sure how we should handle adding `All elements`. Which elements are visible if we've added 20 items+?

**Comment by symball** [comment]
I've been very busy, sorry for delay in getting back here with a response. With a thumbs up, I'll set myself to the task after finishing up something I'm working on at the moment. As prescribed above, I'll write some documentation first in order to solidify the idea before touching the actual code.
@core23 - In the case of All elements, keeping it simple, the stack would combine with whatever is sent to the batch task. If all elements, so be it.

**Comment by core23** [comment]
But what if you add 1000+ elements? This would take a massive amount of memory

**Comment by symball** [comment]
@core23 - Each array entry is simply the ID and __toString() value, not the full object so memory usage isn't too much of a concern. When using this feature in a project, it was used with stack sizes of roughly 12,000 and ran fine on a micro AWS instance.

You should take in to account that, in a typical environment, there won't be too many administrators on at the same time making use of the stack feature. As developers who actually implement the solution, if the situation does require so many people using huge stacks at the same time, there is probably something wrong with the design itself and a better solution should be considered.

I just did a quick test of stack size using the following:

```
$array = [];
for($i = 100000; $i < 106000; $i++)
{
    $array[$i] = '12345678901234567890';
}
$this->get('session')->set('array', $array);
```
In this example, 6000 entries are made with keys that could represent database IDs and 20 characters in every value. Even in the development environment, memory usage peaked at 17MB, up from 9MB without it; 8MB for a 6000 element array. Increasing the size of the array to 60,000 entries and value length to 60, it's up to 40MB which is still not world ending stuff.

I honestly don't think the extra overhead is a concern; in situations where it genuinely is people would be using other supporting technologies such as redis to keep things simpler.

**Comment by muspelheim** [comment]
@symball Hi, how it will be work with ajax loaded pages?
