### ISSUE TITLE
Unable to create entities that implement __toString() the false way

### ISSUE THREAD

**Issue by eschultz-magix** [sonata-project/SonataAdminBundle#4446]
#### Sonata packages

```bash
sonata-project/admin-bundle              3.16.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.3.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.4  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
```

#### Symfony packages

```bash
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v2.8.19 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.4  Symfony SwiftmailerBundle
symfony/symfony            v2.8.19 The Symfony PHP framework
```

#### PHP version

```bash
PHP 5.6.17 (cli) (built: Jan  6 2016 13:28:21)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
```

## Subject

Unfortuately, I have to report another issue introduced with Twig 1.33.0: https://github.com/twigphp/Twig/commit/f5193e92c50c89f19121771ca800aad55b97aff7. You cannot create entities anymore because ```getActionButtons()``` will throw an exception.

Internally, ```action_buttons.html.twig``` will call ```admin.getActionButtons(action, object|default(null))``` and the default filter now uses ```__toString()``` internally, which is implemented by all of my entities.

But if you implement ```__toString()``` on new entities where most properties of the class are null, you cannot return any property with ```NULL``` as value.

Maybe a simple null / isset check may help to avoid triggering the ```__toString()``` method on new entities.

## Steps to reproduce
Create a form for a new entity that has some default actions. The entity must implement the ```__toString()``` method and return a property that is NULL initially. Note: Returning ```NULL``` is forbidden as ```__toString()``` has to return a string value: http://php.net/manual/en/language.oop5.magic.php#object.tostring

## Expected results
The form is shown.

## Actual results

```php
An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Method AppBundle\Entity\TestEntity::__toString() must return a string value").

[2/2] Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Method AppBundle\Entity\TestEntity::__toString() must return a string value").

CRITICAL - Uncaught PHP Exception Twig_Error_Runtime: "An exception has been thrown during the rendering of a template ("Catchable Fatal Error: Method AppBundle\Entity\TestEntity::__toString() must return a string value")." at C:\Projects\php\mmj-test\vendor\sonata-project\admin-bundle/Resources/views/CRUD/action_buttons.html.twig line 12 
```

**Comment by eschultz-magix** [comment]
I think, the error itself is on twig side. I had a look at their code:

```
function _twig_default_filter($value, $default = '')
{
    if (twig_test_empty($value)) {
        return $default;
    }

    return $value;
}

function twig_test_empty($value)
{
    if ($value instanceof Countable) {
        return 0 == count($value);
    }

    if (method_exists($value, '__toString')) {
        return '' === (string) $value;
    }

    return '' === $value || false === $value || null === $value || array() === $value;
}
```

the check ```method_exists($value, '__toString')``` is safe, but validating ```'' === $value``` first will cast _every_ object to string.

**Comment by greg0ire** [comment]
I don't think there is anything to fix besides your entity.

```php
<?php
// wrong
public function __toString()
{
    return $this->myProperty;
}

// right
public function __toString()
{
    return (string) $this->myProperty;
}
```

It's just basic php, you're not supposed to be able to return anything else than a string there. Nothing to do with Sonata.

> Note: Returning NULL is forbidden as __toString() has to return a string value: http://php.net/manual/en/language.oop5.magic.php#object.tostring

You seem to have perfectly understood this by yourself, so, what's the actual issue?

**Comment by eschultz-magix** [comment]
@greg0ire Yes I understand what I did wrong on my side. But it did work before because the ```object|default(null)``` did not trigger the ```__toString()``` method. The error didn't occure before because every created entity had a non-nullable value.

Yes, it may be enough to fix the ```__toString()``` return value, but it would be better to avoid triggering this method by using a simple null check in twig instead of the default filter.

**Comment by greg0ire** [comment]
> Yes, it may be enough to fix the __toString() return value, but it would be better to avoid triggering this method by using a simple null check in twig instead of the default filter.

That's the part I don't understand. What would that check check? Because if it checks the return value of `__toString`, it's already too late.

**Comment by eschultz-magix** [comment]
```object|default(null)``` should check whether the object variable is set and not null, otherwise null is used, right? So in simple PHP code this would be:

```php
return isset($object) ? $object : $default;
```

But now ```__toString()``` and some other internal checks are called in default filter, which is not necessary. Also if you pass an object instance which __toString() method returns an empty string (most common case for new entities), the default value is used because ```'' === ''```.

If someone overrides ```configureActionButtons``` in his Admin class, the new entity won't be passed as argument anymore. Anyway, this seems to be very uncommon, but it may be an unwanted behaviour.

**Comment by greg0ire** [comment]
Oh now I recall seeing this lately, which was discussed as being kinda BC-breaky. My opinion is that relying on to `__toString()` being called only when the returned property is not null is really really wrong, and we shouldn't encourage it by being lenient and cluttering our codebase with extra code to support this.
Every php developer should now how `__toString` works and be able to implement it so that it handles all possible situations.

I'm closing this, but thank you for your bug report, it was very clear and complete! Keep them coming :)
