### ISSUE TITLE
Symfony 3.3 compatibility

### ISSUE THREAD

**Issue by yann-eugone** [sonata-project/SonataAdminBundle#4447]
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.16.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.3.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.4  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/monolog-bundle     v3.1.0             Symfony MonologBundle
symfony/phpunit-bridge     v3.2.7             Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0             Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0             Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0             Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0             Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.4             Symfony SwiftmailerBundle
symfony/symfony            dev-master 549af73 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.10 (cli) (built: Sep  6 2016 16:44:10) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10, Copyright (c) 1999-2016, by Zend Technologies
```

## Subject

Application won't start. Due to some errors.

## Steps to reproduce

- install a brand new Symfony 3.3@dev project
- install sonata admin
- clear the cache.

## Expected results

My application should start.

## Actual results

```bash
$ bin/console cache:clear
                                                                          
  [Symfony\Component\DependencyInjection\Exception\OutOfBoundsException]  
  The argument "3" doesn't exist.                                         
                                                                          
```

### Problems found

In `Sonata\CoreBundle\DependencyInjection\Compiler\FormFactoryCompilerPass` : 

```php
        // get factories
        $original = $container->getDefinition('form.extension');

        $factory = $container->getDefinition('sonata.core.form.extension.dependency');
        $factory->replaceArgument(1, $original->getArgument(1));
        $factory->replaceArgument(2, $original->getArgument(2));
        $factory->replaceArgument(3, $original->getArgument(3));

        $container->removeDefinition('form.extension');
        $container->removeDefinition('sonata.core.form.extension.dependency');

        $container->setDefinition('form.extension', $factory);
```

Symfony `form.extension` service has no more argument number `3`

**Comment by greg0ire** [comment]
This looks like a BC-break. Can you find the commit where the argument was removed?

**Comment by yann-eugone** [comment]
Looks like [this one](https://github.com/symfony/symfony/commit/600e75ce8894f5d18f1726d9d45241f83074de44) could be a good start point

**Comment by greg0ire** [comment]
Let's follow this lead a bit deeper : https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Form/Extension/DependencyInjection/DependencyInjectionExtension.php#L41

**Comment by greg0ire** [comment]
Can you make a PR that adds the argument iff sf/framework-bundle < 3.3 ?

**Comment by yann-eugone** [comment]
Do you think this is enough ?

**Comment by greg0ire** [comment]
I think `sonata.core.form.extension.dependency` might have to be changed too.

**Comment by yann-eugone** [comment]
ok, i tried to, but i got many more errors than just this, i will push the result, but there is more work to do

**Comment by greg0ire** [comment]
Please do push something, I'll help you go through it :)

**Comment by yann-eugone** [comment]
see : https://github.com/sonata-project/SonataCoreBundle/pull/396

- had to try/catch the getArgument(3) and fallback to empty array in FormFactoryCompilerPass
- has to remove array typehinting in DependencyInjectionExtension constructor

now i'm stuck with : 

> Container->get(object(RewindableGenerator))
> in vendor/sonata-project/core-bundle/Form/Extension/DependencyInjectionExtension.php (line 129)

**Comment by greg0ire** [comment]
So `$this->typeServiceIds[$name]` is a Generator?

**Comment by yann-eugone** [comment]
yes, it's a new symfony internal class

**Comment by greg0ire** [comment]
I'll try to have an in-depth look this WE, this looks complicated. Maybe if you get a Generator here you need to go one level deeper? Try to do a foreach on it, see what it contains?

**Comment by greg0ire** [comment]
@yann-eugone I think there are indeed two levels now: each key in `typeExtensionServices` is a hash that associates a serviceId to a service. That's the new content of the 2nd argument. Before, it used to be a simple hash of service ids => service. To get a service, you are now supposed to use the first argument I think : `$this->typeContainer->get($this->typeServiceIds[$name])`

**Comment by gnutix** [comment]
Any news on this one ? Does Sonata work well with Symfony 3.3.0-BETA1 ?

**Comment by greg0ire** [comment]
This is supposed to be fixed by https://github.com/sonata-project/SonataCoreBundle/pull/399

**Comment by yann-eugone** [comment]
Didn't had time to test by now. But I will give feedback has soon has I can : May 9th
