### ISSUE TITLE
Call to private method Exporter\Exporter::addWriter() from context 'appDevDebugProjectContainer'

### ISSUE THREAD

**Issue by samanmohamadi** [sonata-project/SonataAdminBundle#4468]
Registerring SonataExporterBundle in AppKernel.php throws this Error when trying to access admin:
`
Call to private method Exporter\Exporter::addWriter() from context 'appDevDebugProjectContainer'`

**Comment by core23** [comment]
Please use the issue template when reporting bugs!

**Comment by greg0ire** [comment]
IIRC this method has been made public ages ago Had you filled the issue template, we would have known whether your setup is up to date or not. You can complete it and ping us to reopen this.
