### ISSUE TITLE
delete batch option no call preRemove in admin class

### ISSUE THREAD

**Issue by jxamorro** [sonata-project/SonataAdminBundle#4485]
#### Sonata packages
sonata-project/admin-bundle              3.18.2 The missing Symfony Admin ...
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.3.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral exten...
sonata-project/doctrine-orm-admin-bundle 3.1.4  Symfony Sonata / Integrate...
sonata-project/easy-extends-bundle       2.2.0  Symfony SonataEasyExtendsB...
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/google-authenticator      1.1.0  Library to integrate Googl...
sonata-project/intl-bundle               2.3.0  Symfony SonataIntlBundle
sonata-project/user-bundle               3.2.3  Symfony SonataUserBundle

#### Symfony packages
symfony/monolog-bundle     v3.1.0  Symfony MonologBundle
symfony/phpunit-bridge     v3.2.8  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* fun...
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related...
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring exten...
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5...
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5...
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5...
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7...
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PH...
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Acces...
symfony/swiftmailer-bundle v2.5.4  Symfony SwiftmailerBundle
symfony/symfony            v2.8.20 The Symfony PHP framework
#### PHP version
PHP 5.6.15 (cli) (built: Oct 29 2015 12:39:50)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
## Subject
When I delete a entity from batch option de preRemove method of de admin class is not called, if I delete
from inside the entity the method is called

**Comment by jxamorro** [comment]
I am watching the flow and I can see:

in CRUDController:

` public function batchActionDelete(ProxyQueryInterface $query)    {

        $this->admin->checkAccess('batchDelete');
        $modelManager = $this->admin->getModelManager();

        try {
            $modelManager->batchDelete($this->admin->getClass(), $query);
            $this->addFlash('sonata_flash_success', 'flash_batch_delete_success');
        } catch (ModelManagerException $e) {
            $this->handleModelManagerException($e);
            $this->addFlash('sonata_flash_error', 'flash_batch_delete_error');
        }

        return new RedirectResponse($this->admin->generateUrl(
            'list',
            array('filter' => $this->admin->getFilterParameters())
        ));
    }`

and in Sonata\DoctrineORMAdminBundle\Model\ModelManager: 

`public function batchDelete($class, ProxyQueryInterface $queryProxy) {

        $queryProxy->select('DISTINCT '.$queryProxy->getRootAlias());

        try {
            $entityManager = $this->getEntityManager($class);

            $i = 0;
            foreach ($queryProxy->getQuery()->iterate() as $pos => $object) {
                $entityManager->remove($object[0]);

                if ((++$i % 20) == 0) {
                    $entityManager->flush();
                    $entityManager->clear();
                }
            }

            $entityManager->flush();
            $entityManager->clear();
        } catch (\PDOException $e) {
            throw new ModelManagerException('', 0, $e);
        } catch (DBALException $e) {
            throw new ModelManagerException('', 0, $e);
        }
    }`

Prevalidator is not called in anyplace. Anyone have any idea of how to solution it?

Thanks!

**Comment by jlamur** [comment]
Hello @jxamorro.

This problem has been reported many times.
There was an interresting discussion about it on this PR: https://github.com/sonata-project/SonataAdminBundle/pull/1318.

**Comment by jxamorro** [comment]
thanks @jlamur  I didn't know this discussion.

**Comment by AndoniLarz** [comment]
Hello, had the same issue here. Deleting from the entity itself works fine, but deleting it with batch action triggers an exception because the preRemove method is not called.
