### ISSUE TITLE
sonata_type_model_autocomplete causes 'An invalid form control with name='' is not focusable.' JavaScript error 

### ISSUE THREAD

**Issue by VoyteckLenartovich** [sonata-project/SonataAdminBundle#4486]
#### Sonata packages

sonata-project/admin-bundle              3.18.2             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               3.4.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.4              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              Lightweight Exporter library

#### Symfony packages

symfony/assetic-bundle                   v2.8.1             Integrates Assetic into Symfony2
symfony/monolog-bundle                   v3.1.0             Symfony MonologBundle
symfony/phpunit-bridge                   v3.2.8             Symfony PHPUnit Bridge
symfony/polyfill-apcu                    v1.3.0             Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu                v1.3.0             Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring                v1.3.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php56                   v1.3.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70                   v1.3.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util                    v1.3.0             Symfony utilities for portability of PHP codes
symfony/security-acl                     v3.0.0             Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle               v2.5.4             Symfony SwiftmailerBundle
symfony/symfony                          v3.2.8             The Symfony PHP framework

#### PHP version

PHP 7.1.5-1+deb.sury.org~xenial+1 (cli) (built: May 11 2017 14:07:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.5-1+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans

## Subject

Using `'sonata_type_model_autocomplete'` in `configureFormFields` causes `'An invalid form control with name='' is not focusable.'` JavaScript error in browser's console when clicking any of the Create buttons while trying to create a new item.

This problem doesn't occur in version 3.17.0.

**Comment by stiffroy** [comment]
I am having the same problem after composer update. Any news on it?

**Comment by greg0ire** [comment]
Can you find said form control in the HTML of the page?

**Comment by stiffroy** [comment]
For me, it shows no direct error on the view but this error message is present in the console. But when I revert back to Sonata Admin Bundle 3.16.x (which I had before), it works perfectly as it was working before the composer update.

**Comment by VoyteckLenartovich** [comment]
Additionally, you can still submit the form without errors by running command `$(form).submit();` in the browser's console.

**Comment by greg0ire** [comment]
> it shows no direct error on the view

I'm confused. Did you look for an error in the view? Or did you look for a form control with an empty name?

**Comment by stiffroy** [comment]
I am talking about form error bag. When there is any issues or event the success msg, it is shown just above the form in the view. I am talking about this message.

**Comment by fracsi** [comment]
I just ran into the same issue. With using a required attribute on an autocomplete field, select2 generates 2 fields: a hidden input with a correct name, and a select input without name (and with a required attribute), which causes the error, and the form cannot be submitted.
![image](https://cloud.githubusercontent.com/assets/690307/26339315/6d30cbdc-3f87-11e7-80da-9741f4a391c8.png)

**Comment by greg0ire** [comment]
Can any of you use `git bisect` to find the offending commit?

**Comment by fracsi** [comment]
@greg0ire As far as I can tell this #4480 introduced the select field.

**Comment by greg0ire** [comment]
@Soullivaneuh please have a look at this

**Comment by fracsi** [comment]
I found a quick workaround. In the javascript for the autocomplete field, the changed code removes the unused input field instead of hiding it.

Current:[`$(unusedInputRef).hide();`](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig#L46)
Updated: `$(unusedInputRef).remove();`

**Comment by OskarStark** [comment]
@fracsi I updated your comment and used `diff` markup
