### ISSUE TITLE
Minor spelling issue "existance" --> "existence"

### ISSUE THREAD

**Issue by dreftymac** [sonata-project/SonataAdminBundle#4489]
### Environment

* All

#### Sonata packages

* All (including documentation and front-matter)

#### Symfony packages

* All (including documentation and front-matter)

#### PHP version

* All

## Existance should be spelled "Existence"

* Throughout the source code and public-facing documentation and front-matter, the word "existance" should be replaced with "existence".
* This appears to be consistent throughout all elements of the sonata-project, including the home page at https://sonata-project.org/

**Comment by core23** [comment]
Can you provide a PR with a fix please @dreftymac
