### ISSUE TITLE
Get data from the form in create/update actions of CrudController

### ISSUE THREAD

**Issue by ozanichkovsky** [sonata-project/SonataAdminBundle#4494]
## Subject

On the project I'm working on immutable entities are used. DataMapper solves the problem with creating new Entity instance based on Form data. But $object is never got from the form in CRUDController::createAction() and CRUDController::editAction(). If new object is not created then nothing will change as the same instance will be returned. But this patch can be easily adopted and provide others working with DDD entities with a solution.

I provided sample DataMapper that creates new entity from Form data.

## DataMapper

```php
class SampleEntityDataMapper implements DataMapperInterface
{
    /**
     * @param SampleEntity $data
     * @param FormInterface[]|\Traversable $forms
     */
    public function mapDataToForms($data, $forms)
    {
        if (null !== $data) {
            $forms = iterator_to_array($forms);
            $forms['name']->setData($data->getName());
            $forms['description']->setData($data->getDescription());
        }
    }

    /**
     * @param FormInterface[]|\Traversable $forms
     * @param SampleEntity $data
     */
    public function mapFormsToData($forms, &$data)
    {
        $forms = iterator_to_array($forms);

        if (null === $data->getId()) {
            $name = $forms['name']->getData();
            $description = $forms['description']->getData();

            // New entity is created
            $data = new SampleEntity(
                $name,
                $description
            );
        } else {
            $data->update(
                $forms['description']->getData()
            );
        }
    }
```

## CRUDController:createAction()

See comments here. Some code was removed to make my example more readable.

```php
    /**
     * Create action.
     *
     * @return Response
     *
     * @throws AccessDeniedException If access is not granted
     */
    public function createAction()
    {
        // some code is removed

        $object = $this->admin->getNewInstance();

        $this->admin->setSubject($object);

        /** @var $form \Symfony\Component\Form\Form */
        $form = $this->admin->getForm();
        $form->setData($object);
        $form->handleRequest($request);

        if ($form->isSubmitted()) {
            //TODO: remove this check for 4.0
            if (method_exists($this->admin, 'preValidate')) {
                $this->admin->preValidate($object);
            }
            $isFormValid = $form->isValid();

            // persist if the form was valid and if in preview mode the preview was approved
            if ($isFormValid && (!$this->isInPreviewMode() || $this->isPreviewApproved())) {
                $this->admin->checkAccess('create', $object);

                try {
                    // Old object is passed to be created. One that is newly created in the form is never got back
                    // For example:
                    $object = $form->getData();
                    $object = $this->admin->create($object);

                    // some code removed
                } catch (ModelManagerException $e) {
                   // some code removed
                }
            }
         // some code removed
    }
```

**Comment by greg0ire** [comment]
Would you like to provide that as a PR?

**Comment by ozanichkovsky** [comment]
yes, I've forked a repository, committed a fix and am creating a PR now

**Comment by ozanichkovsky** [comment]
PR request has passed all checks.

**Comment by denbad** [comment]
Still Sonata Admin forces data_class option to Entity's classname, leading to unnecessary Entity::__construct calls, that behavior is unwanted in DDD. For quick hack override _getNewInstance_ to return null  and _getFormBuilder_ to set data_class as null. Not sure about side effects.

**Comment by kunicmarko20** [comment]
@denbad check https://symfony.com/doc/master/bundles/SonataAdminBundle/cookbook/recipe_data_mapper.html

**Comment by denbad** [comment]
@kunicmarko20 Exactly, checked it first, somehow _getNewInstance_ along with _data_class_ option are unaware of DataMapper's _mapDataToForms and mapFormsToData_ methods, maybe it's specific to installed versions of mine. _CRUDController::createAction_ calls _getNewInstance_ - this leads to "Too few arguments exception", as well as _data_class_ autoresolve:

<img width="945" alt="1" src="https://user-images.githubusercontent.com/2112361/56303211-1afd7780-6144-11e9-8924-0845107167b5.png">
<img width="840" alt="2" src="https://user-images.githubusercontent.com/2112361/56303216-1df86800-6144-11e9-87e7-d7e0f7aa63ab.png">
