### ISSUE TITLE
After setting filters with configureDefaultFilterValues, they do not show as removable

### ISSUE THREAD

**Issue by mmucklo** [sonata-project/SonataAdminBundle#4497]
#### Sonata packages

```bash
$ composer show sonata-project/*
# Put the result here.
sonata-project/admin-bundle              3.18.2             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.0              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               3.2.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       dev-master aec01f1 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle dev-master ab4ba73 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       dev-master 36bac7e Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              Lightweight Exporter library
```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle          dev-master 0241b13 Integrates Assetic into Symfony2
symfony/monolog-bundle          v3.0.3             Symfony MonologBundle
symfony/phpunit-bridge          v3.2.4             Symfony PHPUnit Bridge
symfony/polyfill-intl-icu       v1.3.0             Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring       v1.3.0             Symfony polyfill for the Mbstring extension
symfony/polyfill-php54          v1.3.0             Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55          v1.3.0             Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56          v1.3.0             Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70          v1.3.0             Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util           v1.3.0             Symfony utilities for portability of PHP codes
symfony/psr-http-message-bridge v0.3               PSR HTTP message bridge
symfony/security-acl            v3.0.0             Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle      v2.4.2             Symfony SwiftmailerBundle
symfony/symfony                 v3.2.4             The Symfony PHP framework```

#### PHP version

```bash
$ php -v
PHP 7.0.18 (cli) (built: Apr 18 2017 12:04:39) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
    with Zend OPcache v7.0.18, Copyright (c) 1999-2017, by Zend Technologies```
```
## Subject

A Default filter is not easily removable.

1) Overrode configureDefaultFilterValues(...) in an Admin class.
2) Added a default filter with ChoiceType::TYPE_NOT_CONTAINS

Documentation says class is ChoiceFilter::TYPE_.... but there's no constant in that class
https://sonata-project.org/bundles/admin/master/doc/reference/action_list.html

3) Filter works as expected, however, I'm unable to easily remove it as all I see is a blank filter section when loaded (see screen capture)

## Steps to reproduce

See above

## Expected results

A way to remove the filter

## Actual results

No apparent way to remove the filter

<img width="1060" alt="screen shot 2017-05-26 at 5 57 29 pm" src="https://cloud.githubusercontent.com/assets/245122/26516562/23051bf4-423d-11e7-8c34-6f05dfc4019d.png">

**Comment by mmucklo** [comment]
<img width="1060" alt="screen shot 2017-05-26 at 5 57 29 pm" src="https://cloud.githubusercontent.com/assets/245122/26516565/2a63c7f6-423d-11e7-9500-79a0e934618e.png">

**Comment by core23** [comment]
Can you provide a PR with a fix @mmucklo ?

**Comment by mmucklo** [comment]
@core23 any clue where I should begin looking?

**Comment by core23** [comment]
Maybe have a look at this PR where the feature was introduced https://github.com/sonata-project/SonataAdminBundle/pull/4059

**Comment by Kalyse** [comment]
@mmucklo  https://github.com/sonata-project/SonataAdminBundle/pull/4059/files#r133965341

**Comment by Kalyse** [comment]
I just added the following:

On Load
![vr_332](https://user-images.githubusercontent.com/199760/29463082-51d5727a-8429-11e7-971d-9a76ce7b6172.png)


![vr_331](https://user-images.githubusercontent.com/199760/29463085-54a61d7e-8429-11e7-9bd0-69cda841ad42.png)


```
 {%  if admin.isDefaultFilter(filter.formName) %}
                                        <div class="panel panel-default">
                                        <div class="panel-body">
                                            <b>Default filter</b> {{ filter.options.placeholder }}
                                            - <a href="#" class="sonata-toggle-filter sonata-ba-action" filter-target="filter-{{ admin.uniqid }}-{{ filter.name }}" filter-container="filter-container-{{ admin.uniqid() }}">
                                                <i class="fa {{ (filter.isActive() or filter.options['show_filter']) ? 'fa-check-square-o' : 'fa-square-o' }}"></i>{{ filter.label|trans({}, filter.translationDomain ?: admin.translationDomain) }}
                                            </a> <span class="text-muted">(edit)</span>
                                        </div></div>
                                    {% endif %}```

**Comment by core23** [comment]
Can you provide a PR if you find a solution @Kalyse

**Comment by tknuppe** [comment]
Hi @mmucklo 
Just in case you haven't found a solution yet. I had the same problem and just added the filter values directly inside the $datagridValues variable instead of set them inside configureDefaultFilterValues method. Then the filters will show up in the filters section and can be removed.

Note: This is a workaround. I don't know if this will work in the future but for now it seems to help a lot.

Example:

>     protected $datagridValues = array(
>         'name' => array ('type' => EqualType::TYPE_IS_EQUAL, 'value' => 'ipsum lorem'),
>         'is_verified' => array ('type' => EqualType::TYPE_IS_EQUAL, 'value' => true),
>         'is_locked' => array ('type' => EqualType::TYPE_IS_EQUAL, 'value' => false),
>         'is_active' => array ('type' => EqualType::TYPE_IS_EQUAL, 'value' => true),
>         '_page' => 1,
>         '_sort_order' => 'ASC',
>         '_sort_by' => 'another_nr',
>     );
>
