### ISSUE TITLE
configureDatagridFilters doesn't recognize fields from a trait

### ISSUE THREAD

**Issue by blixit** [sonata-project/SonataAdminBundle#4524]
### Environment
Linux
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.19.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.1.5  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
```

#### Symfony packages

```bash
$ composer show symfony/*
 symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.2 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.4.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.4.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.4.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.4.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.4.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.4.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2 Symfony SwiftmailerBundle
symfony/symfony            v3.3.2 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 7.0.18-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

## Subject

I have an entity 'Examen' which use a trait with 2 fields (costHt and costTtc).  
These fields work fine in the methods (configureListFields, configureFormFields, configureShowFields) of ExamenAdmin but raise an error while used in configureDatagridFilters().

```php
protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper
            ->add('id')->add('value')->add('certificated')
            ->add('costHt')->add('costTtc');    // <-- raises error
    }
protected function configureShowFields(ShowMapper $showMapper)
    {
        $showMapper
            ->add('id')->add('parameter')->add('value')->add('certificated')
            ->add('costHt')->add('costTtc')  // <-- works fine
        ;
    }
```

## Steps to reproduce

Create an entity 'Entity'
Create a trait 'Able' with doctrine fields
Use the trait 'Able' in the entity 'Entity'
Create EntityAdmin class
Configure DatagridFilters with 'Able' fields

## Expected results

I expect required fields added to filter

## Actual results

**Notice: Undefined index: costHt**
Here is the stacktrace after error detection.
```
-in vendor/sonata-project/doctrine-orm-admin-bundle/Guesser/FilterTypeGuesser.php (line 69)
FilterTypeGuesser->guessType('AppBundle\\Entity\\Examen', 'costHt', object(ModelManager))
-in vendor/sonata-project/admin-bundle/Guesser/TypeGuesserChain.php (line 55)
TypeGuesserChain->Sonata\AdminBundle\Guesser\{closure}(object(FilterTypeGuesser))
-in vendor/sonata-project/admin-bundle/Guesser/TypeGuesserChain.php (line 73)
TypeGuesserChain->guess(object(Closure))
-in vendor/sonata-project/admin-bundle/Guesser/TypeGuesserChain.php (line 56)
TypeGuesserChain->guessType('AppBundle\\Entity\\Examen', 'costHt', object(ModelManager))
-in vendor/sonata-project/doctrine-orm-admin-bundle/Builder/DatagridBuilder.php (line 105)
DatagridBuilder->addFilter(object(Datagrid), null, object(FieldDescription), object(ExamenAdmin))
-in vendor/sonata-project/admin-bundle/Datagrid/DatagridMapper.php (line 89)
DatagridMapper->add('costHt')
-in src/AdminBundle/Admin/ExamenAdmin.php (line 23)
```

**Comment by blixit** [comment]
Actually, I can overcome the problem above by adding the field type like that : 
```
$datagridMapper 
            ->add('costHt',NumberFilter::class)
```
But if I try to submit the search in the filter input, I get a semantical error : 
```
[Semantical Error] line 0, col 74 near 'costHt >= :c': Error: Class AppBundle\Entity\Examen has no field or association named costHt
```
Now I don't know anymore if the problem is from doctrine or sonata.

**Comment by blixit** [comment]
The 'error' was from doctrine and was mine. The field name was converted from costHt to cost_ht. It seems that configureDatagridFilters() method work with database name while configureListFields, configureFormFields, configureShowFields accept real field names.

**Comment by jlamur** [comment]
Well, I think there is two problems that have to be fixed here:

- The exception must be more verbose (something like `No mapping found for field 'costHt'`,
- The DatagridMapper/Builder should be consistent with other Builders by accepting entity fields name (and not column names).

BTW, this issue belongs to `SonataDoctrineORMBundle` repository.

**Comment by blixit** [comment]
Thank you for your quick response. 

I agree with the verbose mode. It should be clearer.
Since the issue belongs to SonataDoctrineORMAdminBundle and not Doctrine, should I reopen the issue or just let it closed ?

**Comment by jlamur** [comment]
Yes, I think it would be a good idea to reopen the issue on the SonataDoctrineORMAdminBundle repository. You could even propose a fix in a pull request if you want to help make Sonata better :smiley:

**Comment by blixit** [comment]
Ok. I will reopen it. 
Actually, I would have been able to propose a fix if I had a bigger understanding of the whole bundle source code. Right now it's not the case. 
If you tell me what files are directly concerned by the matter, i can start to have a look because I'm also looking for a source project to contribute to.
