### ISSUE TITLE
#4028 introduced bug in base_show.html.twig

### ISSUE THREAD

**Issue by fracsi** [sonata-project/SonataAdminBundle#4525]
#### Sonata packages

```bash
sonata-project/admin-bundle              3.20.0 The missing Symfony Admin Generator
```

## Subject

Undefined variable (`view_group`) in [`base_show.html.twig`](https://github.com/sonata-project/SonataAdminBundle/blob/3.20.0/Resources/views/CRUD/base_show.html.twig#L47)
Introduced in: #4028

## Steps to reproduce
Configure a ShowMapper with tabs.

## Actual results

500 Internal server error:

```
Variable "view_group" does not exist.
```

**Comment by TimoBakx** [comment]
I think view_group.label should be show_tab.label in base_show.html.twig, line 47.

**Comment by OskarStark** [comment]
@TimoBakx are you willing to provide a PR?

**Comment by TimoBakx** [comment]
@OskarStark I'm working on it. It'll be my first PR, so I hope I'm doing this correctly.

**Comment by OskarStark** [comment]
> @OskarStark I'm working on it. It'll be my first PR, so I hope I'm doing this correctly.

Glad to hear that, we will support you getting it merged 👍

**Comment by EmmanuelVella** [comment]
Hey, thank you for the bug report, I just tested and fixed it here : https://github.com/sonata-project/SonataAdminBundle/pull/4526

@OskarStark Feel free to merge or close it if another PR is opened !

**Comment by jlamur** [comment]
Maybe it's time to add some functional tests?

**Comment by TimoBakx** [comment]
Just added PR #4527. I wasn't sure if the tasks are needed.

**Comment by OskarStark** [comment]
> @OskarStark Feel free to merge or close it if another PR is opened !

I will keep the one of @TimoBakx open, as it is his first contribution and maybe he will keep supporting us in the future, too 😃 

> Maybe it's time to add some functional tests?

Yes I think so

> Just added PR #4527. I wasn't sure if the tasks are needed.

I removed the todo section for you, the PR itself looks good to me 👍

**Comment by TimoBakx** [comment]
@OskarStark Thank you.

**Comment by EmmanuelVella** [comment]
> I will keep the one of @TimoBakx open, as it is his first contribution and maybe he will keep supporting us in the future, too 😃

@OskarStark Sure ! 👍
