### ISSUE TITLE
Properly override template

### ISSUE THREAD

**Issue by QuentinPolantis** [sonata-project/SonataAdminBundle#4528]
Hello,

First, i would like to mention that i'm using sonata admin bundle for 2 years now; and i'm very satisfied with. 

In order to make it fit to some specific needs, i have overrided some templates. 
For this i had to completely copy and paste the code of the sonata widget template name (template X), and replace the part which i want to be different.
If Sonata release new feature or new design on that template X; i remain with my old code and do not take advantages of these new benefits. 

That is exactly what i'm currently facing and i would like to know if overriding an entire template or widget is the best practice. How can i handle specific case and call a specific widget in my Formmapper?

Otherwise (but linked to my question), do you plan to provide more way to customize or add class to input? At this very moment, i'm overriding form_row to get col-md-3 form-group for an exemple.

Thanks by advance,

Quentin

**Comment by greg0ire** [comment]
> That is exactly what i'm currently facing and i would like to know if overriding an entire template or widget is the best practice. How can i handle specific case and call a specific widget in my Formmapper?

Overriding is what you do when Sonata is not flexible enough. The best practice is to report this lack of flexibility, and contribute something to fix it.

> Otherwise (but linked to my question), do you plan to provide more way to customize or add class to input? At this very moment, i'm overriding form_row to get col-md-3 form-group for an exemple.

We are a small team, and our plans are not that detailed, sorry. Right now we are more concerned with getting next major versions out. If you want to contribute something to fix your issue, feel free to.
