### ISSUE TITLE
after update to 3.20.1 no work CKEditor

### ISSUE THREAD

**Issue by jxamorro** [sonata-project/SonataAdminBundle#4537]
#### Sonata packages
sonata-project/admin-bundle              3.20.1 The missing Symfony Admin ...
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral exten...
sonata-project/doctrine-orm-admin-bundle 3.1.5  Symfony Sonata / Integrate...
sonata-project/easy-extends-bundle       2.2.0  Symfony SonataEasyExtendsB...
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/google-authenticator      1.1.0  Library to integrate Googl...
sonata-project/intl-bundle               2.3.1  Symfony SonataIntlBundle
sonata-project/user-bundle               3.2.4  Symfony SonataUserBundle

#### Symfony packages
symfony/monolog-bundle     v3.1.0  Symfony MonologBundle
symfony/phpunit-bridge     v3.3.2  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.4.0  Symfony polyfill backporting apcu_* fun...
symfony/polyfill-intl-icu  v1.4.0  Symfony polyfill for intl's ICU-related...
symfony/polyfill-mbstring  v1.4.0  Symfony polyfill for the Mbstring exten...
symfony/polyfill-php54     v1.4.0  Symfony polyfill backporting some PHP 5...
symfony/polyfill-php55     v1.4.0  Symfony polyfill backporting some PHP 5...
symfony/polyfill-php56     v1.4.0  Symfony polyfill backporting some PHP 5...
symfony/polyfill-php70     v1.4.0  Symfony polyfill backporting some PHP 7...
symfony/polyfill-util      v1.4.0  Symfony utilities for portability of PH...
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Acces...
symfony/swiftmailer-bundle v2.6.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.22 The Symfony PHP framework

#### PHP version
PHP 5.6.15 (cli) (built: Oct 29 2015 12:39:50)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans

## Subject
In admin class the code: 
->add('text', CKEditorType::class)
In the screen no show ckeditor, no show textarea

## Actual results
only show the label of the field

**Comment by greg0ire** [comment]
Do you have any js errors?

**Comment by jxamorro** [comment]
yes
i have this js error:
Error: [CKEDITOR.resourceManager.load] Resource name "default" was not found at "http://myurl/bundles/ivoryckeditor/styles.js?t=G87E".  ckeditor.js:236:80

**Comment by greg0ire** [comment]
And do you have any 404 in the network tab?

**Comment by jxamorro** [comment]
i have downgraded and i have updated again and it works well now.
i suppose that the before update had errors in assets install.
i close the issue.
thanks greg0ire for help!
