### ISSUE TITLE
Child admins entities are accessible from any parent admin entities.

### ISSUE THREAD

**Issue by jlamur** [sonata-project/SonataAdminBundle#4556]
## Subject

When editing a child (or on any other child route) if you change the parent id there's no error.

In fact, there have never been any check that the child belong to the parent.

My first thought was this is a security issue due to the scope of this bug. I discussed with @greg0ire about it and we finally agreed that it is not.

**Comment by greg0ire** [comment]
Still, getting a 404 for that would be nice.
