### ISSUE TITLE
Menu with option on_top no add the css class active never.

### ISSUE THREAD

**Issue by jxamorro** [sonata-project/SonataAdminBundle#4565]
#### Sonata packages

sonata-project/admin-bundle              3.20.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/core-bundle               3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.6  Symfony Sonata / Integrate Doctrine ORM into ...
sonata-project/easy-extends-bundle       2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  Lightweight Exporter library
sonata-project/google-authenticator      1.1.0  Library to integrate Google Authenticator int...
sonata-project/intl-bundle               2.3.1  Symfony SonataIntlBundle
sonata-project/user-bundle               3.2.4  Symfony SonataUserBundle

#### Symfony packages

symfony/monolog-bundle     v3.1.0  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.25 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.4.0  Symfony polyfill backporting apcu_* functions to lower PHP...
symfony/polyfill-intl-icu  v1.4.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.4.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.4.0  Symfony polyfill backporting some PHP 5.4+ features to low...
symfony/polyfill-php55     v1.4.0  Symfony polyfill backporting some PHP 5.5+ features to low...
symfony/polyfill-php56     v1.4.0  Symfony polyfill backporting some PHP 5.6+ features to low...
symfony/polyfill-php70     v1.4.0  Symfony polyfill backporting some PHP 7.0+ features to low...
symfony/polyfill-util      v1.4.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.25 The Symfony PHP framework

#### PHP version

PHP 5.6.31-1~ubuntu16.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

## Subject

When you have a menu in sonata with option "on_top: true" if you select it, the css class no change.

it shoud add the css class active to the html element li

**Comment by pulzarraider** [comment]
@jxamorro can you please add exmaple code so we can reproduce the issue?

**Comment by OskarStark** [comment]
I can confirm, that it gets never "active"

**Comment by jxamorro** [comment]
hi  @pulzarraider 
I put the code of my config.yml that don't work for me, the problem I think is that my route no is associated to an admin class:

```
dashboard:
    groups:
      Home:
        on_top: true
        icon: <i class="fa fa-calendar"></i>
        items:
          - route: sonata_admin_dashboard
            label: Home
```
thanks
