### ISSUE TITLE
Select filter attribute impossible if you have many attributes in datagrid filter

### ISSUE THREAD

**Issue by crifi** [sonata-project/SonataAdminBundle#4575]
#### Sonata packages
sonata-project/admin-bundle              3.20.1                                The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2                                 Symfony SonataBlockBundle
sonata-project/cache                     1.0.7                                 Cache library
sonata-project/core-bundle               3.4.0                                 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1                                 Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2                                 Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.6                                 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0                                 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1                                 Lightweight Exporter library
sonata-project/google-authenticator      1.1.0                                 Library to integrate Google Authenticator into a PHP project
sonata-project/user-bundle               dev-add_support_for_fos_user2 99be909 Symfony SonataUserBundle

#### Symfony packages
symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.5 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.4.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.4.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.4.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.4.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.4.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.4.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.3 Symfony SwiftmailerBundle
symfony/symfony            v3.3.5 The Symfony PHP framework

#### PHP version
PHP: 7.1.4

## Subject
Select a filter attribute in data grid is impossible if the attribute is at the bottom of a long filter list. On mobile devices the responsive layout is okay.

## Steps to reproduce
1. Define many filter attributes in configureDatagridFilters method of your admin class.
2. Try to select a attribute which is at the bottom of the list.

## Expected results
A scrollbar for the list should be shown.

**Comment by pulzarraider** [comment]
@crifi can you please add screenshot and the browser with version where it occurs?

**Comment by crifi** [comment]
The filter list in the following screenshot is to short, there are more attributes, but the list is not scrollable:

<img width="304" alt="2018-08-27-screenshot-issue-sonata-admin-datagrid-filter" src="https://user-images.githubusercontent.com/608768/29747612-8c85c28e-8b00-11e7-86af-bd021cdda421.png">

This occurs in Chrome, Firefox and Safari (all latest version).

**Comment by core23** [comment]
Are you sure that this whole filter list is even useful?

**Comment by OskarStark** [comment]
I have the same issue in one of my projects
