### ISSUE TITLE
Framework form themes should not be used as default

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#4611]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.22.0 3.22.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2  3.3.2  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  1.0.7  Cache library
sonata-project/core-bundle               3.4.0  3.4.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1  2.2.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.6  3.1.6  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0  2.2.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1  1.7.1  Lightweight Exporter library
sonata-project/intl-bundle               2.3.1  2.3.1  Symfony SonataIntlBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle     v2.8.2  v2.8.2 Integrates Assetic into Symfony2          
symfony/monolog-bundle     v3.1.0  v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.5  v3.3.6 Symfony PHPUnit Bridge
symfony/polyfill-intl-icu  v1.4.0  v1.5.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.4.0  v1.5.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.4.0  v1.5.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.4.0  v1.5.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.4.0  v1.5.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.3  v3.0.3 Symfony SwiftmailerBundle
symfony/symfony            v3.2.12 v3.3.6 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.0.22 (cli) (built: Aug  3 2017 22:16:07) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
```

## Subject

If you use and define custom form fields for your front app, admin bundle will also use it.

It should not, or at least, should be deactivated by default.

## Steps to reproduce

Use some custom form themes:

```yaml
# config.yml
twig:
    debug:            '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - 'form_generic_fields.html.twig'
        - 'form_fields.html.twig'
        - 'jquery.collection.html.twig'
```

## Expected results

Should not be used and gives a normal form:

![image](https://user-images.githubusercontent.com/1698357/29488327-bf1ea038-8508-11e7-9e23-9be670085e92.png)

## Actual results

Uses the framework form theme and can give ugly results like this:

![image](https://user-images.githubusercontent.com/1698357/29488334-e035f956-8508-11e7-90a2-237f7d063e28.png)

**Comment by greg0ire** [comment]
Not a bug I'm afraid...

**Comment by jvasseur** [comment]
This is currently impossible to do in symfony, the only solution is to redefine blocks in the sonata form theme to prevent the form rendering to use the ones defined globally.

What we need is https://github.com/symfony/symfony/pull/22610, but it's not merged yet.

**Comment by Soullivaneuh** [comment]
This is still a bug as Sonata admin is strongly independent according to theme templating.

Let's keep it opened waiting symfony/symfony#22610.

Thanks @jvasseur for the link.

What are the possible options waiting that?

**Comment by greg0ire** [comment]
`form_themes` are meant to do application-wide customizations, so no, this is not a bug since people might want to use just that to customize forms that are part of the admin.

**Comment by Soullivaneuh** [comment]
This is why I said "at least, it should be optional".

Currently, if a developper use custom form theme for, by example, materialize-css and then want to integrate admin-bundle, he would have to review all the application.

We can't say that sonata-admin is a simple bundle, it's near a full app itself.

BTW, we can specify form themes with sonata config. So why we can't make it exclusive? In this case, we still be able to add the same form theme trough this config part.

**Comment by Soullivaneuh** [comment]
Waiting the proper way, I found an ugly but not that much workaround.

Create your own `TwigRendererEngine` extending the base one, and permit to change the `defaultThemes` property with a setter:

```php
namespace AppBundle\Form;

use Symfony\Bridge\Twig\Form\TwigRendererEngine as BaseEngine;

final class TwigRendererEngine extends BaseEngine
{
    /**
     * @param array $defaultThemes
     */
    public function setDefaultThemes(array $defaultThemes)
    {
        $this->defaultThemes = $defaultThemes;
    }
}
```

Replace the service class by your own using compiler pass:

```php
namespace AppBundle\DependencyInjection\Compiler;

use AppBundle\Form\TwigRendererEngine;
use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;

final class TwigRendererEngineCompilerPass implements CompilerPassInterface
{
    /**
     * {@inheritdoc}
     */
    public function process(ContainerBuilder $container)
    {
        $container->getDefinition('twig.form.engine')
            ->setClass(TwigRendererEngine::class);
    }
}
```

Finally, create a service listener or subscriber binding the request and set only the base form theme if the route is matching sonata ones:

```php
namespace AppBundle\Listener;

use AppBundle\Form\TwigRendererEngine;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;

final class FormThemeSubscriber implements EventSubscriberInterface
{
    /**
     * @var TwigRendererEngine
     */
    private $twigFormRenderer;

    /**
     * @param TwigRendererEngine $twigFormRenderer
     */
    public function __construct(TwigRendererEngine $twigFormRenderer)
    {
        $this->twigFormRenderer = $twigFormRenderer;
    }

    /**
     * {@inheritdoc}
     */
    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::REQUEST => [
                ['onKernelRequest', 0],
            ],
        ];
    }

    /**
     * @param GetResponseEvent $event
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        if (!$event->isMasterRequest()) {
            return;
        }

        if (
            strncmp($event->getRequest()->get('_route'), 'admin_', strlen('admin_')) === 0
            || strncmp($event->getRequest()->get('_route'), 'sonata_admin_', strlen('sonata_admin_')) === 0
        ) {
            $this->twigFormRenderer->setDefaultThemes(['form_div_layout.html.twig']);
        }
    }
}
```

Declare the subscriber service:

```yaml
    subscriber.form_theme:
        class: AppBundle\Listener\FormThemeSubscriber
        tags:
            - { name: kernel.event_subscriber }
        arguments: [ '@twig.form.engine' ]
```

And voilà ! No more need to review hundred of template file to set your own theme for your app without destroying sonata rendering.

This is quite overkill according to the need, but this is the best workaround I found so far.

If you know better, please tell me here!

**Comment by jvasseur** [comment]
@Soullivaneuh I was thinking of a similar solution, with 2 differences :
 - Use reflexion (or a Closure) to modify the `defaultThemes` property instead of redefining the service (it's a hack anyway, why not hacking our way into the service).
 - Reset the `defaultThemes` inside the [setFormTheme](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/Controller/CRUDController.php#L1395) method instead of a listener.

Another way would have been to create our own form extension to define some `somata_form_*` functions that use a different form renderer with our form themes as a default. But that would require a lot more code to work.

**Comment by Soullivaneuh** [comment]
Why a major feature @jordisala1991 ? :thinking:

**Comment by Soullivaneuh** [comment]
@kunicmarko20 What? It's an issue, not a PR.

I opened it as a bug and then this was changed to major feature like that without explanation. :-)

@jvasseur The `sonata_form_*` would be indeed very overkill indeed.

The other hacks are possible, as mine BTW. If we can't make it proper, we should integrate one on this bundle.

**Comment by Soullivaneuh** [comment]
@kunicmarko20 Read it to fast.

Well it depends. It's indee the default behavior, but this was never normal AFAIK.

**Comment by jordisala1991** [comment]
I thought that this will imply BC breaks, and tagged as major. If it can be done without BC breaks, then its not major

**Comment by jordisala1991** [comment]
There could be a lot of people relying on form themes to change the behavior of the admin-bundle (me included).

If we change it without an opt-in, how is that not a BC break?

**Comment by jvasseur** [comment]
I agree it's a bug but I think the BC break is to big to do this outside of a major (there is probably a lot of projects using this bug as a feature).

Since symfony/symfony#22610 is merged in symfony 3.4 we could restrict our dependencies to symfony >= 3.4 in the next major and use it, this would remove the need to use a hack to solve it.

**Comment by Soullivaneuh** [comment]
> we could restrict our dependencies to symfony >= 3.4

Dependency upgrade is not BC break.

I am not as sure as you about the BC break impact. I mean, when you built a web app, you will maybe customize the form fields, but not touch the BO one.

I don't know, maybe a poll would be interesting just to know the opinion.

Anyway, for now, just mark this issue as a bug.

**Comment by jordisala1991** [comment]
How do you customize the form fields on the backoffice if you are not using form_themes?

**Comment by jvasseur** [comment]
I agree updating dependencies is not a BC break but IMO changing the behavior here is to big of a BC break to go in a minor or a patch.

The biggest BC break will be when using form types from bundles that comes with their own themes (like VichUploaderBundle : https://github.com/dustin10/VichUploaderBundle/blob/master/DependencyInjection/VichUploaderExtension.php#L227, or IvoryCKEditorBundle : https://github.com/egeloen/IvoryCKEditorBundle/blob/master/DependencyInjection/Compiler/ResourceCompilerPass.php#L41) if you start ignoring the `twig.form_themes` node they will stop working "out of the box".

Outside of the BC break element, this is a case we have to solve if we start ignoring global form themes (https://github.com/symfony/symfony/pull/23990 would probably help).

**Comment by Soullivaneuh** [comment]
So now we can adapt sonata to use the `only` option: https://github.com/symfony/symfony/pull/22610
