### ISSUE TITLE
The field labels in list is broken

### ISSUE THREAD

**Issue by peter-gribanov** [sonata-project/SonataAdminBundle#4615]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.22.0          3.22.0
sonata-project/block-bundle              3.3.2           3.3.2
sonata-project/cache                     1.0.7           1.0.7
sonata-project/core-bundle               3.4.0           3.4.0
sonata-project/datagrid-bundle           2.x-dev 80692d9 2.x-dev 80692d9
sonata-project/doctrine-extensions       1.0.2           1.0.2
sonata-project/doctrine-orm-admin-bundle 3.1.6           3.1.6
sonata-project/easy-extends-bundle       2.2.0           2.2.0
sonata-project/exporter                  1.7.1           1.7.1
sonata-project/google-authenticator      1.1.0           1.1.0
sonata-project/user-bundle               3.2.4           3.2.4
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle     v2.8.2  v2.8.2 Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 v3.1.0 Symfony MonologBundle
symfony/polyfill-apcu      v1.5.0  v1.5.0 Symfony polyfill backporting apcu...
symfony/polyfill-intl-icu  v1.5.0  v1.5.0 Symfony polyfill for intl's ICU-r...
symfony/polyfill-mbstring  v1.5.0  v1.5.0 Symfony polyfill for the Mbstring...
symfony/polyfill-php54     v1.5.0  v1.5.0 Symfony polyfill backporting some...
symfony/polyfill-php55     v1.5.0  v1.5.0 Symfony polyfill backporting some...
symfony/polyfill-php56     v1.5.0  v1.5.0 Symfony polyfill backporting some...
symfony/polyfill-php70     v1.5.0  v1.5.0 Symfony polyfill backporting some...
symfony/polyfill-php72     v1.5.0  v1.5.0 Symfony polyfill backporting some...
symfony/polyfill-util      v1.5.0  v1.5.0 Symfony utilities for portability...
symfony/security-acl       v3.0.0  v3.0.0 Symfony Security Component - ACL ...
symfony/swiftmailer-bundle v2.6.3  v3.0.3 Symfony SwiftmailerBundle
symfony/symfony            v2.8.26 v3.3.6 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 5.6.24 (cli) (built: Jul 20 2016 21:19:29)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

## Subject

After updating to the latest version i found that the field labels in list are broken.

## Steps to reproduce

Example admin class

```php
class BroadcastAdmin extends BaseAdmin
{

    // ...

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('id')
            ->addIdentifier('title', null, ['label' => 'Заголовок'])
            ->add('type', null, ['label' => 'Тип'])
            ->add('enabled', null, ['label' => 'Включена', 'editable' => true])
        ;
    }
}
```

## Expected results

In `sonata-project/admin-bundle 3.20.0`

![image](https://user-images.githubusercontent.com/1954436/29513924-6507a47e-866f-11e7-9f8b-08681a90126f.png)

## Actual results

What i saw after the update:

In `sonata-project/admin-bundle 3.21.0`

![image](https://user-images.githubusercontent.com/1954436/29514256-93dd1602-8670-11e7-9d09-f29dbe7e5c08.png)

In `sonata-project/admin-bundle 3.22.0`

![image](https://user-images.githubusercontent.com/1954436/29514105-01405138-8670-11e7-98d1-0a8c2527ebf6.png)

**Comment by peter-gribanov** [comment]
@axzx the problem not in a encoding.
1. I use UTF8.
2. Result is broken only if i change a version of `SonataAdminBundle`.

This code worked for 2 years until your update came out.

**Comment by peter-gribanov** [comment]
![image](https://user-images.githubusercontent.com/1954436/29522989-04c63664-8694-11e7-9116-0bfe78772ce2.png)

If i change labels

```php
class BroadcastAdmin extends BaseAdmin
{

    // ...

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('id')
            ->add('type', null, ['label' => 'Что-то'])
            ->add('enabled', null, ['label' => 'Еще что-то', 'editable' => true])
        ;
    }
}
```

then i see this

![image](https://user-images.githubusercontent.com/1954436/29523240-0bd9f804-8695-11e7-879d-5653cd5f4f81.png)

If i move labels to translation file

```php
class BroadcastAdmin extends BaseAdmin
{

    // ...

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
            ->addIdentifier('id')
            ->add('type', null, ['label' => 'something'])
            ->add('enabled', null, ['label' => 'something_else', 'editable' => true])
        ;
    }
}
```

```yml
# messages.ru.yml
something: 'Что-то'
something_else: 'Еще что-то'
```

```yml
# config.yml
framework:
    translator: { fallbacks: [ 'ru' ] }
```

I see this:

![image](https://user-images.githubusercontent.com/1954436/29523408-9f338494-8695-11e7-8139-bc7fc6eb2c01.png)

This problem not in my code.

**Comment by axzx** [comment]
I have tested your configuration and it works fine for me. 

![bez nazwy](https://user-images.githubusercontent.com/1436016/29537102-b3a56fb6-86c0-11e7-8914-096661f9280e.png)

**Comment by axzx** [comment]
In `messages.ru.yml` should be:

```
# messages.ru.yml
Something: 'Что-то'
Something Else: 'Еще что-то'
```

**Comment by peter-gribanov** [comment]
No. In `messages.ru.yml` should be:

```yml
# messages.ru.yml
app:
    broadcast:
        fields:
            something: 'Что-то'
            something_else: 'Еще что-то'
```

**Comment by jlamur** [comment]
@peter-gribanov Could you please check if this PR https://github.com/sonata-project/SonataAdminBundle/pull/4617 fixes your issue?

**Comment by peter-gribanov** [comment]
@jlamur Unfortunately this did not fix the problem. Label breaks somewhere before.

![image](https://user-images.githubusercontent.com/1954436/29553865-c34e80a0-8725-11e7-8bad-453bd7d6d7c6.png)

**Comment by OskarStark** [comment]
@peter-gribanov do you use a different naming strategy than the default one?

can you check if it works fine with the default naming strategy?

**Comment by peter-gribanov** [comment]
The problem in `LabelTranslatorStrategy`:

```php
var_dump($fieldDescription->getLabel());
var_dump($this->admin->getLabelTranslatorStrategy()->getLabel($fieldDescription->getLabel(), 'list', 'label'));
```
![image](https://user-images.githubusercontent.com/1954436/29554848-5a910cc8-8729-11e7-9404-c8463338f3c1.png)

@OskarStark I did not change the naming strategy.

**Comment by peter-gribanov** [comment]
@OskarStark

```php
$this->admin->getLabelTranslatorStrategy() instanceof \Sonata\AdminBundle\Translator\NativeLabelTranslatorStrategy // true
```

**Comment by peter-gribanov** [comment]
@OskarStark It looks like it's still something on my side

```php
public function getLabel($label, $context = '', $type = '')
{
    ob_clean();
    var_dump($label);
    $label = str_replace(array('_', '.'), ' ', $label);
    $label = preg_replace('/(?<=\\w)([A-Z])/', '_$1', $label);
    var_dump($label);
    var_dump(strtolower($label));
    var_dump(mb_strtolower($label));

    return trim(ucwords(str_replace('_', ' ', $label)));
}
```

![image](https://user-images.githubusercontent.com/1954436/29555501-88009078-872b-11e7-8a5d-272c8358fcb4.png)

**Comment by OskarStark** [comment]
Sounds interesting 🤔

**Comment by peter-gribanov** [comment]
I think that the problem with the locale.

```php
var_dump(setlocale(LC_ALL, 0));
mb_detect_order('UTF8,CP1251,ASCII');
var_dump(mb_detect_encoding($label));
var_dump(mb_detect_encoding(strtolower($label)));
```

```
string(78) "LC_COLLATE=C;LC_CTYPE=Russian_Russia.1251;LC_MONETARY=C;LC_NUMERIC=C;LC_TIME=C"
string(5) "UTF-8"
string(12) "Windows-1251"
```

But it's strange, because in `sonata-project/admin-bundle 3.20.0` everything is fine.

@OskarStark did you change the default naming strategy?

**Comment by OskarStark** [comment]
No we didn't change anything related to the naming strategy.

We name everything here: https://github.com/sonata-project/SonataAdminBundle/releases

**Comment by peter-gribanov** [comment]
I see this change https://github.com/sonata-project/SonataAdminBundle/commit/1b1d4b47d95daec7b4ebe8675cf6befce1d496ac
If you specify a label, it is always transformed.

**Comment by peter-gribanov** [comment]
It broke BC. And now i'm forced to redefine the default transformer to `NoopLabelTranslatorStrategy` to be sure that everything works as before.

**Comment by OskarStark** [comment]
Could you add a failing test here with your configuration, so that we can fix it?

**Comment by axzx** [comment]
@peter-gribanov 
https://github.com/sonata-project/SonataAdminBundle/pull/4621
could you check it?

**Comment by peter-gribanov** [comment]
@axzx Yes. But your change does not make sense in this way.

**Comment by peter-gribanov** [comment]
I do not really understand that you tried to achieve changes like this #4602.
Perhaps this is the right change.
Just need to warn users that you are breaking BC.

**Comment by peter-gribanov** [comment]
By the way, what am I doing wrong?

I change configuration:

```yml
sonata_admin:
    admin_services:
        label_translator_strategy: 'sonata.admin.label.strategy.native'
```

and cache error

```
Invalid type for path "sonata_admin.admin_services.label_translator_strategy". Expected array, but got string
```

If i change it to array

```yml
sonata_admin:
    admin_services:
        label_translator_strategy: [ 'sonata.admin.label.strategy.native' ]
```

I see this:

```
Unrecognized option "0" under "sonata_admin.admin_services.label_translator_strategy"
```

**Comment by axzx** [comment]
Why do you set it? 
`'sonata.admin.label.strategy.native'` is a default value

**Comment by peter-gribanov** [comment]
Excuse me. Of course, `sonata.admin.label.strategy.noop`

```yml
sonata_admin:
    admin_services:
        label_translator_strategy: [ 'sonata.admin.label.strategy.noop' ]
```

**Comment by axzx** [comment]
```
sonata_admin:
    admin_services:
        <service id>:
            label_translator_strategy: 'sonata.admin.label.strategy.noop'
```

**Comment by peter-gribanov** [comment]
@axzx that is, is it the same that i will specify the service tag attribute?

```yml
admin.broadcast:
    class: BroadcastAdmin
    arguments: [ ~, Broadcast, ~ ]
    tags:
        - { name: sonata.admin, manager_type: orm, label: 'admin.menu.broadcast.broadcast', label_translator_strategy: 'sonata.admin.label.strategy.noop'}
```

Apparently the documentation lagged behind reality.
https://sonata-project.org/bundles/admin/3-x/doc/reference/configuration.html

**Comment by axzx** [comment]
yes, the same solution

**Comment by jxamorro** [comment]
the problem is in the last two updated version.

The field 'label' in list not should have translator strategy, because the user must put what he wants, for example

with this implementation the spanish accents no works.

The code is in the file listmapper.php on line 120:

if ($fieldDescription->getLabel() === null) {
	$fieldDescription->setOption(
        	'label',
                $this->admin->getLabelTranslatorStrategy()->getLabel($fieldDescription->getName(), 'list', 'label')
        );
} elseif ($fieldDescription->getLabel() !== false) {
        $fieldDescription->setOption(
                'label',
                $this->admin->getLabelTranslatorStrategy()->getLabel($fieldDescription->getLabel(), 'list', 'label')
        );
}

i propose change the code before for the next solution:

if (($label = $fieldDescription->getLabel()) !== false && !$label) {
    $fieldDescription->setOption(
        'label', 
        $this->admin->getLabelTranslatorStrategy()->getLabel($fieldDescription->getName(), 'list', 'label')
    );
}

regards

**Comment by axzx** [comment]
@peter-gribanov @jxamorro 

https://github.com/sonata-project/SonataAdminBundle/pull/4621/files
could you check it now?

**Comment by peter-gribanov** [comment]
@axzx yes. that's better

**Comment by OskarStark** [comment]
I asked for a release, stay tuned 👍
