### ISSUE TITLE
Sonata Admin listMapper

### ISSUE THREAD

**Issue by Siddharth22** [sonata-project/SonataAdminBundle#4622]
I am using Symfony2.6 with Sonata Admin.In my Entity "Order", i have an array column named "Products". this is "ArrayCollection" type and ManyToMany relation with Product Table

How I can show this field in Sonata Admin listMapper.

      protected function configureListFields(ListMapper $listMapper)
     {
          $listMapper
           ->addIdentifier('id')
           ->add('products')
      }

Right now in list It's showing Blank. So How I can show all Products in List Mapper in Order list.

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.
