### ISSUE TITLE
How useful would be to have a sonata_type_admin for the Show Action

### ISSUE THREAD

**Issue by ejkun** [sonata-project/SonataAdminBundle#4625]
I had this idea after seeing #4593 

I want some opinions on this (and maybe some tips). If this is helpful, I will gladly work on it.

**Comment by greg0ire** [comment]
How would you do it? Would you flatten things in one table, or would you have some kind of sub table in a cell?

**Comment by ejkun** [comment]
A sub table in a cell
The design wouldn't be the most beautiful of all, but if you put the field in a separeted group with label => false or something, it will work perfectly. 
As soon as I get sometime I will start working on this. Any tips, recommendations or rules that I must follow?

**Comment by greg0ire** [comment]
Reading CONTRIBUTING.MD in its entirety would be a good start
