### ISSUE TITLE
Autowiring does not work with Sonata Admin

### ISSUE THREAD

**Issue by spacetraveller** [sonata-project/SonataAdminBundle#4646]
If you have autowiring turned on, there are failures in the Abstract Admin class.

Cannot autowire service "AppBundle\Admin\SomeAdmin": argument "$code" of method "Sonata\AdminBundle\Admin\AbstractAdmin::__construct()" must have a type-hint or be given a value explicitly.

Is there any way around this, if autowiring is being used?

**Comment by jlamur** [comment]
Hello @spacetraveller.

Did you managed to find a solution for your problem?
If not, please post the full stacktrace of your error, and the config related.

**Comment by acrobat** [comment]
I think the original problem with autowiring an admin class is that the arguments are all string arguments and autowiring is not able to resolve the constructor arguments.

**Comment by Soullivaneuh** [comment]
@spacetraveller Please next time follow the issue template. Right now we don't have any information for your issue and can't help you at all.

This kind of issue are generaly closed if not updated.

For this one, please follow #4710

**Comment by otjutt** [comment]
How I solved it: 

I had:

```
_defaults:
  public:true
```
I had to change it to:
```
_defaults:
  public:false
```
and then make each the required service `public:true` individually.
