### ISSUE TITLE
Plan for BS4 (Bootstrap 4)

### ISSUE THREAD

**Issue by binhle410** [sonata-project/SonataAdminBundle#4651]
Do we have any plan for BS4 support, maybe in SonataAdminBundle 4.x ?

**Comment by OskarStark** [comment]
Not yet

**Comment by jvasseur** [comment]
This will probably depend a lot on AdminLTE support for Bootstrap 4.

**Comment by Soullivaneuh** [comment]
@jvasseur answer is right. We depend to AdminLTE, not Bootstrap 4.

BTW, bootstrap 4 is not stable while I'm writing this comment.

Please open an issue on the AdminLTE repository.

Regards.

**Comment by memboc** [comment]
Bootstrap4 is stable now. [Here issue](https://github.com/almasaeed2010/AdminLTE/issues/1819) in AdminLTE repository. 
The dev version already available now.

**Comment by kunicmarko20** [comment]
This is a lot of work and my guess some BC breaks, especially since it needs to be done for all sonata bundles that have templates.

**Comment by haivala** [comment]
Have anyone even tried this
https://github.com/ColorlibHQ/AdminLTE/releases/tag/v3.0.1

**Comment by osavchenko** [comment]
This issue is almost the same as #5597, but no work here. I think we can close it.

**Comment by wbloszyk** [comment]
I should finish it in this week. I am waiting for #5461, but adminlte 3 can be done first.

**Comment by osavchenko** [comment]
Sorry, I thought that AdminLTE will be upgraded with bootstrap in one go and one PR

**Comment by wbloszyk** [comment]
AdminLTE RP will upgrade AdminLTE 2(based on bootstrap 3) to 3(based on bootstrap 4) . Webpack RP will change assets managing.

**Comment by core23** [comment]
We rely heavily on Admin LTE and it's bootstrap version. So we can't do this without upgrading Admin LTE. Closing this in favor of #5597
