### ISSUE TITLE
Error 500 : Cannot use object of type Symfony\Component\Form\FormRenderer as array

### ISSUE THREAD

**Issue by amdiakhate** [sonata-project/SonataAdminBundle#4652]
### Environment

Php 7.0, Mysql

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
```

sonata-project/admin-bundle              3.x-dev 51387ad    dev-master cd61e55
sonata-project/block-bundle              3.x-dev 033f4e1    dev-master 64a897b
sonata-project/cache                     1.x-dev adb8f3e    1.x-dev adb8f3e   
sonata-project/core-bundle               3.x-dev 16c7611    dev-master 3ac1797
sonata-project/datagrid-bundle           2.x-dev 66dcb36    2.x-dev 66dcb36   
sonata-project/doctrine-extensions       1.x-dev b07f636    dev-master b969484
sonata-project/doctrine-orm-admin-bundle 3.x-dev b06d010    dev-master 66219fe
sonata-project/easy-extends-bundle       2.x-dev 60edcd3    2.x-dev 60edcd3   
sonata-project/exporter                  1.x-dev 2aa197e    1.x-dev 2aa197e   
sonata-project/media-bundle              dev-master 504b500 dev-master 504b500
sonata-project/notification-bundle       3.x-dev e27bbc2    dev-master 84e6c0b

#### Symfony packages

```
$ composer show --latest 'symfony/*'
```
symfony/monolog-bundle     dev-master c9fb33a dev-master c9fb33a
symfony/phpunit-bridge     3.4.x-dev 5ddca7a  dev-master 9c5da0f
symfony/polyfill-apcu      dev-master cec3239 dev-master cec3239
symfony/polyfill-intl-icu  dev-master 4aa0b65 dev-master 4aa0b65
symfony/polyfill-mbstring  dev-master 7c8fae0 dev-master 7c8fae0
symfony/polyfill-php56     dev-master e85ebde dev-master e85ebde
symfony/polyfill-php70     dev-master b6482e6 dev-master b6482e6
symfony/polyfill-util      dev-master 67925d1 dev-master 67925d1
symfony/security-acl       dev-master ab4dfe2 dev-master ab4dfe2
symfony/swiftmailer-bundle 2.6.x-dev 11555c3  dev-master d31de92
symfony/symfony            3.4.x-dev 30e3b6d  3.4.x-dev 30e3b6d 

#### PHP version

```
$ php -v
# Put the result here.
```
PHP 7.0.23-1+0~20170902060934.6+stretch~1.gbpa985da (cli) (built: Sep  2 2017 06:09:36) ( NTS )

## Subject

Hello, I get the error  "Cannot use object of type Symfony\Component\Form\FormRenderer as array" when I try to create a new entity in my admin. I didn't have that issue before and I haven't changed anything in the Admin file.

Here's what my Admin file looks like : 

```

use Doctrine\ORM\EntityRepository;
use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Datagrid\ListMapper;
use Sonata\AdminBundle\Datagrid\DatagridMapper;
use Sonata\AdminBundle\Form\FormMapper;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class TeamAdmin extends AbstractAdmin
{
    protected function configureFormFields(FormMapper $formMapper)
    {
        $formMapper
            ->with('Infos')
            ->add('name', 'text');
        $formMapper->add('manager', 'sonata_type_model_list', array(
            'class' => 'UserBundle:User',
            'required' => true,
            'by_reference' => false,
            'required' => false
        ), array(
            'edit' => 'inline',
            'inline' => 'table',
        ))
            ->end()
            ->with('General')
            ->add('members', 'sonata_type_collection', array(
                'required'=> false
            ), array(
                'edit' => 'inline',
                'inline' => 'table',
                'sortable' => 'position'

            ))
            ->add('comexAdmins',
                null,
                array(
                    'label' => 'Admin Comex',
                    'expanded' => true,
                    'by_reference' => false,
                    'multiple' => true,
                    'query_builder' => function(EntityRepository $er)
                    {
                        return $er->createQueryBuilder('u')
                            ->where('u.level = 3');
                    }
                ))
            //            ->add('title')
//            ->add('abstract')
//            ->add('content')
            ->end();

    }

    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper->add('name');
    }

    protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper->addIdentifier('name');
        $listMapper->add('manager');
        $listMapper->add('comexAdmins');

        $listMapper->add('_action', null, array(
            'actions' => array(
                'show' => array(),
                'edit' => array()
            )
        ));
    }


    public function prePersist($team)
    {
        $this->preUpdate($team);
    }

    public function preUpdate($team)
    {
        $team->getManager();
    }
}

```
 
 

Thank you

**Comment by core23** [comment]
We try to keep github issues for feature requests and bugs only. 

Please have a look at the [docs](https://sonata-project.org/bundles/) or use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and questions.

**Comment by dmaicher** [comment]
@core23 I actually think this is a bug. Not sure if its here or on Symfony 3.4.

This also happens to one of my projects when trying the upcoming `3.4.x-dev` version.
