### ISSUE TITLE
Sonata produces missing favicon error

### ISSUE THREAD

**Issue by kosmodisk** [sonata-project/SonataAdminBundle#4673]
A smallish problem :)

Sonata does not have a decent way to override html head section other tags (standard_layout.html.twig allows to override only meta, stylesheets and javascripts), so I cannot define my own favicon so they generate error into logs. Perhaps a new block, e.g 'head_tags' could be introduced?

**Comment by core23** [comment]
You can still override any template with symfony basic features: https://symfony.com/doc/current/templating.html#template-inheritance-and-layouts

**Comment by kosmodisk** [comment]
I am aware of that. But there is no other way than to duplicate whole layout. Seems kinda overreacting. Moreover, the fix is relatively simple.

**Comment by greg0ire** [comment]
> Moreover, the fix is relatively simple

Probably. Can you make a PR? Also what other tags should / could this block contain?

**Comment by kosmodisk** [comment]
> Also what other tags should / could this block contain?
Cant think of anything else but those favicon/icon directives but basically everything else that doesn't go into meta, js and stylesheet. By default it could be empty.

> Can you make a PR
Maybe :)
