### ISSUE TITLE
[RFC] Create new ActionMapper for batch action

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#4677]
Today we have several methods in the `AbstractAdmin` to configure something (e.g. a ListMapper for `configureListFields`, or a `ShowMapper` for `configureShowFields`).

Some configuration methods do still rely on fragile arrays, like `configureBatchActions`. This makes it very hard do change order or remove items on the list.

Refs https://github.com/sonata-project/SonataAdminBundle/pull/4259

**Comment by VincentLanglet** [comment]
Will close in favor of the discussion https://github.com/sonata-project/SonataAdminBundle/issues/6826
