### ISSUE TITLE
Menu badges

### ISSUE THREAD

**Issue by jlamur** [sonata-project/SonataAdminBundle#4682]
An interresting feature that I would :heart: to see on Sonata is what I would call *menu badges* (the colored bubbles at the right of menu labels):

![menu-badges](https://user-images.githubusercontent.com/7054317/31176142-16201ec0-a912-11e7-8466-a0481dff73f4.png)

Ideally, we should be able to define the badge class, text and title attribute simply.

**Comment by nerdyninja** [comment]
I think no one is assigned, can I take this issue?

**Comment by jlamur** [comment]
Of course you can :)

**Comment by jlamur** [comment]
Please come to #sonata on https://symfony.com/slack-invite if you want to discuss about it or if you need help :)

**Comment by osavchenko** [comment]
Looks like it's stuck. @jlamur could explain a little bit more how do you see this feature? What do that numbers mean and how to configure it or so?

**Comment by jlamur** [comment]
This feature could be anything you want it to be, I opened this issue as a suggestion. Besides, I'm no longer helping Sonata development, so feel free to propose anything and start to code it if you want such a feature.
