### ISSUE TITLE
Not implementing reset() from DataCollectorInterface is deprecated in Symfony 3.4

### ISSUE THREAD

**Issue by javiereguiluz** [sonata-project/SonataAdminBundle#4699]
I'm upgrading a Symfony app to 3.4 and I found this deprecation related to your `BlockDataCollector`:

```
User Deprecated: Implementing
"Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the
"reset()" method is deprecated since version 3.4 and will be unsupported in 4.0
for class "Sonata\BlockBundle\Profiler\DataCollector\BlockDataCollector".
```

**Comment by mzstic** [comment]
Seems like nobody started to work on this one yet. I'd be happy to take this one :)
I'm just not sure what's the correct way to persuade composer to install symfony 3.4. If you could give me some directions I'd be glad.

**Comment by greg0ire** [comment]
@mzstic I think you can try `composer require symfony/symfony ^3.4@dev`

**Comment by mzstic** [comment]
One more question this issue is written under SonataAdminBundle but the place that needs to be fixed is within SonataBlockBundle. So I should make PR for this issue into another project, right? I'm kinda confused by it :)

**Comment by greg0ire** [comment]
Indeed, I think @javiereguiluz wanted to centralize issues. You have no choice but to do it in the SonataBlockBundle then :)

**Comment by OskarStark** [comment]
any news on this @mzstic ?

**Comment by Fenozo** [comment]
I have a trouble with this code error in symfony 3.4.6, I don't konw how to resolve it.
Please give me the right answer, thank you.
User Deprecated: Implementing "Symfony\Component\HttpKernel\DataCollector\DataCollectorInterface" without the "reset()" method is deprecated since Symfony 3.4 and will be unsupported in 4.0 for class "CoreSphere\ConsoleBundle\DataCollector\DataCollector".

**Comment by greg0ire** [comment]
That's an issue you need to report to whoever wrote `CoreSphere\ConsoleBundle\DataCollector\DataCollector`
