### ISSUE TITLE
Warning: array_merge() expects at least 1 parameter, 0 given

### ISSUE THREAD

**Issue by featuriz** [sonata-project/SonataAdminBundle#4717]
https://github.com/sonata-project/SonataAdminBundle/blob/caab4a84a2146c0109de7f22550a41af0be72706/Form/Type/ChoiceFieldMaskType.php#L38

If the second is null something like this: call_user_func_array('array_merge', array())
Next action is : array_merge()
Error: So this throws error

**Comment by greg0ire** [comment]
Can you please make a PR to fix this?

**Comment by featuriz** [comment]
My SonataAdminCode is this:
`->add('isActive', 'sonata_type_choice_field_mask', ['label' => 'Active?', 'choices' => FZ::activeChoice(), 'expanded' => TRUE, 'multiple' => FALSE, 'required' => TRUE, 'attr' => ['class' => 'list-inline']])`
I commit these two lines and added one
```
  //      $allFieldNames = call_user_func_array('array_merge', $sanitizedMap);
  //      $allFieldNames = array_unique($allFieldNames);
       $allFieldNames = array_values($sanitizedMap);
```
**I think the error at my admin code!**

**Comment by TimoBakx** [comment]
This happens when the 'map' option of a `ChoiceFieldMaskType` field is not set or an empty array.
Also, when the 'map' option is anything but an array, it will issue a `Warning: Invalid argument supplied for foreach()`.
