### ISSUE TITLE
jQuery.ui still relevant?

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#4725]
I wanted to ask the question if we still need jquery.ui, because it nearly looks dead. The last release was a [year ago](http://blog.jqueryui.com/).

Refs: https://github.com/sonata-project/SonataAdminBundle/tree/3.x/Resources/public/vendor/jqueryui

Anybody knows why we added it as a dependency?

**Comment by Soullivaneuh** [comment]
Sonata admin is based on AdminLTE theme that currently requires jquery-ui: https://github.com/almasaeed2010/AdminLTE/blob/f0421f5b364d61809563bc971eef51fd510ac0ef/package.json#L52

I think the issue should be opened on this project.

If it's removed from AdminLTE, then we should check if we use it for custom code, then remove it.

**Comment by core23** [comment]
Thanks for the information.

Closing this for now
