### ISSUE TITLE
Allow to generate url in url field type with another parameter than `identifier`

### ISSUE THREAD

**Issue by julienfastre** [sonata-project/SonataAdminBundle#4733]
I am currently trying to generate an url column in a list, but the identifier should not be the id parameter.

This is my url: `/profile/{{ username }}`

The entity in the admin is a `Profile` class, with a One-to-One relationship with the `User` entity (`$profile->getUser()` returns a `User` instance).

This seems to be impossible to generate currently from SonataAdmin.

## The way I tryed:

(according to https://sonata-project.org/bundles/admin/master/doc/reference/field_types.html#url)

```
            ->add('user.username', 'url', [
                'route' => [ 
                    'name' => 'comedien_cv_view',
                    'parameters' => [
                        'username' => 'user.username'
                    ]
                ]
            ])
```

Return something like `/profile/user.username`.

```
            ->add('user.username', 'url', [
                'route' => [ 
                    'name' => 'comedien_cv_view',
                    'identifier_parameter_name' => 'profile_slug',
                ]
            ])
```

return something like `/profile/1` where `1` is the id of the profile.

## I would like to use something like:

```
            ->add('user.username', 'url', [
                'route' => [ 
                    'name' => 'comedien_cv_view',
                    'identifier_parameter_name' => 'profile_slug',
                    'identifier_parameter' => 'user.username'
                ]
            ])
```

Which should return an url like `/profile/user123`, `/profile/user456`, etc. (where `user123` and `user456` are the usernames).

I could not find the class generating the url to check if this is possible.

## Questions

Does this feature exists in SonataAdmin ?

If yes, does someone can give me a clue to search where is the code generating the url to improve documentation.

If not, is this something useful ? Can I do a PR ? (and does someone can help me to find faster the code which generate the url).

**Comment by jlamur** [comment]
Hi @julienfastre,

A similar feature was added in this PR https://github.com/sonata-project/SonataAdminBundle/pull/4591, but was then reverted because the implementation was a little bit overlooked.

Maybe you can help @catharsisjelly to rewrite a new one.

**Comment by julienfastre** [comment]
@jlamur : Hum, I am not sure that this is the same feature. From this PR: 

> Now your routes will change from ``/product/1/edit`` to
``/product/af5/edit``

Here, I simply want to add an url in a column in the list view, using the `url` filter. Basically, the sample above should come in `configureListField` function of a `ProfileAdmin` in my example:

```
public function configureListField(ListMapper $listmapper) 
{
    $listMapper
            ->add('user.username', 'url', [
                'route' => [ 
                    'name' => 'comedien_cv_view',
                    'identifier_parameter_name' => 'profile_slug',
                    'identifier_parameter' => 'user.username'
                ]
            ])
    ;
}
```

**Comment by catharsisjelly** [comment]
I see a similarity, whereas I was wanting to encode the ID that gets passed you want to use a totally different property for the ID. I can certainly see how a version of my solution would work where you create a RouteIdHandler that takes your ID parameter and instead of using the ID to get the object it uses the slug. Not 100% convinced it's the same but I can certainly see why the comparison was made

**Comment by greg0ire** [comment]
We need a service that, given an url, can provide the corresponding object identifier. This sounds a bit stupid though because that would probably mean 2 SQL (or whatever) requests.

**Comment by lainosantos** [comment]
Hello.

Any fix for this???

**Comment by mikemix** [comment]
Still can't be done :(

**Comment by core23** [comment]
> Still can't be done :(

That's right
