### ISSUE TITLE
'View more...' or link to filtered list in global search results blocks

### ISSUE THREAD

**Issue by mlang38** [sonata-project/SonataAdminBundle#4750]
As it seems that the global search only shows at max 10 results per Entity/Admin, it would be great to have a link to go to the full filtered list, keeping the global search filters parameters, for each Admin.

It could be a 'View more...' link at the end of the `<ul>` when there is more than 10 results.
And/or just customize the url of the little _list_ box tool link in each block header, next to the results count, so it keeps the global_search filters parameters.

**Comment by core23** [comment]
Can you provide a PR? @mlang38

**Comment by mlang38** [comment]
Don't have much time for now, and I don't really have ideas on how to do it. By reading Sonata guts every day, I have to say it is quite complicated (hairy/messy?).
