### ISSUE TITLE
[RFC] Twig namespaced paths

### ISSUE THREAD

**Issue by fracsi** [sonata-project/SonataAdminBundle#4761]
In `symfony-flex` the directory structure is a little different than the normal symfony skeleton.

It uses the `templates` folder in the root directory for the twig templates. You can override third-party bundle templates in `templates/bundles/[BUNDLENAME]/`, but twig can only find templates if they are referenced with the new namespaced paths. (https://symfony.com/doc/2.8/templating/namespaced_paths.html)

The old syntax that is used by SonataAdmin (e.g.: `SonataAdmin::standard_layout`), is resolved by the symfony/framework-bundle.

The ideal solution would be to use the new namespace syntax everywhere.

**Comment by OskarStark** [comment]
Would you like to create a PR?

**Comment by fracsi** [comment]
@OskarStark I just wanted to start a conversation about it first. Also it affects all Sonata Bundles as well.

**Comment by OskarStark** [comment]
> Also it affects all Sonata Bundles as well.

yes I know, maybe should move the discussion to the centralized [dev-kit](https://github.com/sonata-project/dev-kit) repo and create a todo list with all affected bundles to get a clearer view.

WDYT @greg0ire ?

**Comment by greg0ire** [comment]
I think it's ok to do that since 2.8 is our lowest supported version now. A centralized issue would be great, a bash script to help finding occurences, and perhaps replacing them would be great too.

**Comment by greg0ire** [comment]
See https://github.com/sonata-project/SonataCoreBundle/pull/469

**Comment by fracsi** [comment]
@greg0ire The PR you linked is not related to namespaced paths in twig.

**Comment by greg0ire** [comment]
Oh right it's something else completely 😅

**Comment by fracsi** [comment]
@greg0ire @OskarStark I have added an issue in the dev-kit repo. Please help to create a to-do list.

**Comment by OskarStark** [comment]
Thank you @fracsi, I close this issue here.
