### ISSUE TITLE
"The options "choice_translation_domain", "choices" do not exist." after upgrade from 3.24.0 to 3.25.0

### ISSUE THREAD

**Issue by OskarStark** [sonata-project/SonataAdminBundle#4769]
The options "choice_translation_domain", "choices" do not exist.

I think this was introduced by: #4670

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.25.0             3.25.0             The missing Symfony Admin Generator
sonata-project/block-bundle              3.5.0              3.5.0              Symfony SonataBlockBundle
sonata-project/cache                     2.0.0              2.0.0              Cache library
sonata-project/core-bundle               3.7.0              3.7.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.7              3.1.7              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0              2.2.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              1.7.1              Lightweight Exporter library
sonata-project/user-bundle               dev-master ff710b8 dev-master ff710b8 Symfony SonataUserBundle
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/monolog-bundle     v3.1.2  v3.1.2  Symfony MonologBundle
symfony/phpunit-bridge     v3.3.13 v3.3.13 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.6.0  v1.6.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.6.0  v1.6.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.6.0  v1.6.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.6.0  v1.6.0  Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.6.0  v1.6.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7  v3.1.6  Symfony SwiftmailerBundle
symfony/symfony            v3.3.13 v3.3.13 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.1.9 (cli) (built: Sep  8 2017 03:07:13) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.9, Copyright (c) 1999-2017, by Zend Technologies
```

## Subject

After upgrading von admin bundle `3.24.0` to `3.25.0` the following error occured.

## Error

`The options "choice_translation_domain", "choices" do not exist. Defined options are: "action", "allow_extra_fields", "attr", "auto_initialize", "block_name", "by_reference", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "description", "disabled", "empty_data", "error_bubbling", "error_mapping", "extra_fields_message", "field_options", "field_type", "horizontal_input_wrapper_class", "horizontal_label_class", "horizontal_label_offset_class", "inherit_data", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_format", "label_render", "mapped", "method", "operator_options", "operator_type", "post_max_size_message", "property_path", "required", "sonata_admin", "sonata_field_description", "sonata_help", "translation_domain", "trim", "upload_max_size_message", "validation_groups".
`

## Stacktrace
<details>
Symfony\Component\OptionsResolver\Exception\UndefinedOptionsException:
The options "choice_translation_domain", "choices" do not exist. Defined options are: "action", "allow_extra_fields", "attr", "auto_initialize", "block_name", "by_reference", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "description", "disabled", "empty_data", "error_bubbling", "error_mapping", "extra_fields_message", "field_options", "field_type", "horizontal_input_wrapper_class", "horizontal_label_class", "horizontal_label_offset_class", "inherit_data", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_format", "label_render", "mapped", "method", "operator_options", "operator_type", "post_max_size_message", "property_path", "required", "sonata_admin", "sonata_field_description", "sonata_help", "translation_domain", "trim", "upload_max_size_message", "validation_groups".

  at vendor/symfony/symfony/src/Symfony/Component/OptionsResolver/OptionsResolver.php:667
  at Symfony\Component\OptionsResolver\OptionsResolver->resolve(array('required' => false, 'choice_translation_domain' => 'SonataAdminBundle', 'choices' => array('label_date_type_equal' => 3, 'label_date_type_greater_equal' => 1, 'label_date_type_greater_than' => 2, 'label_date_type_less_equal' => 4, 'label_date_type_less_than' => 5, 'label_date_type_null' => 6, 'label_date_type_not_null' => 7)))
     (vendor/symfony/symfony/src/Symfony/Component/Form/ResolvedFormType.php:95)
  at Symfony\Component\Form\ResolvedFormType->createBuilder(object(FormFactory), 'type', array('required' => false, 'choice_translation_domain' => 'SonataAdminBundle', 'choices' => array('label_date_type_equal' => 3, 'label_date_type_greater_equal' => 1, 'label_date_type_greater_than' => 2, 'label_date_type_less_equal' => 4, 'label_date_type_less_than' => 5, 'label_date_type_null' => 6, 'label_date_type_not_null' => 7)))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Extension/DataCollector/Proxy/ResolvedTypeDataCollectorProxy.php:74)
  at Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeDataCollectorProxy->createBuilder(object(FormFactory), 'type', array('required' => false, 'choice_translation_domain' => 'SonataAdminBundle', 'choices' => array('label_date_type_equal' => 3, 'label_date_type_greater_equal' => 1, 'label_date_type_greater_than' => 2, 'label_date_type_less_equal' => 4, 'label_date_type_less_than' => 5, 'label_date_type_null' => 6, 'label_date_type_not_null' => 7)))
     (vendor/symfony/symfony/src/Symfony/Component/Form/FormFactory.php:76)
  at Symfony\Component\Form\FormFactory->createNamedBuilder('type', object(ResolvedTypeDataCollectorProxy), null, array('required' => false, 'choice_translation_domain' => 'SonataAdminBundle', 'choices' => array('label_date_type_equal' => 3, 'label_date_type_greater_equal' => 1, 'label_date_type_greater_than' => 2, 'label_date_type_less_equal' => 4, 'label_date_type_less_than' => 5, 'label_date_type_null' => 6, 'label_date_type_not_null' => 7)))
     (vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:106)
  at Symfony\Component\Form\FormBuilder->create('type', 'Sonata\\AdminBundle\\Form\\Type\\Filter\\ChoiceType', array('required' => false, 'choice_translation_domain' => 'SonataAdminBundle', 'choices' => array('label_date_type_equal' => 3, 'label_date_type_greater_equal' => 1, 'label_date_type_greater_than' => 2, 'label_date_type_less_equal' => 4, 'label_date_type_less_than' => 5, 'label_date_type_null' => 6, 'label_date_type_not_null' => 7)))
     (vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:269)
  at Symfony\Component\Form\FormBuilder->resolveChildren()
     (vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:215)
  at Symfony\Component\Form\FormBuilder->getForm()
     (vendor/symfony/symfony/src/Symfony/Component/Form/FormBuilder.php:221)
  at Symfony\Component\Form\FormBuilder->getForm()
     (vendor/sonata-project/admin-bundle/src/Datagrid/Datagrid.php:146)
  at Sonata\AdminBundle\Datagrid\Datagrid->buildPager()
     (vendor/sonata-project/admin-bundle/src/Datagrid/Datagrid.php:317)
  at Sonata\AdminBundle\Datagrid\Datagrid->getForm()
     (vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php:108)
  at Sonata\AdminBundle\Controller\CRUDController->listAction()
  at call_user_func_array(array(object(PurchaseOpenOrderItemAdminController), 'listAction'), array())
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:169)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:30)
</details>

cc @Hanmac

**Comment by Hanmac** [comment]
Hm I thought that it wasn't merged yet into the sonata user bundle yet or did a release happen?
I will try to fix it as soon I am on a pc

**Comment by Hanmac** [comment]
@OskarStark what kind of Form type did you try to create? If it was the Security Type, the change is in 3.* but not in Master for User Bundle yet

**Comment by OskarStark** [comment]
ah you mean this one https://github.com/sonata-project/SonataUserBundle/pull/951 is causing the issue?

Yes I am using dev-master of user bundle for now

@greg0ire could you perform a manual merge in UserBundle from `3.x` ➡️  `master` ❓

**Comment by Hanmac** [comment]
Yeah that's what I am thinking
I might do an extra pull request for Master for this change if you guys arent faster than lazy me

But I still might add a change for this That prevents this thing from crashing in case something happen

**Comment by jordisala1991** [comment]
Manual merge for UserBundle is a bit hard (because of the folder refactor), I am handling it, but it won't be done until tonight (it might take some more time)

@OskarStark what kind of field are you using?

**Comment by OskarStark** [comment]
1.  I tried to move core-bundle from 3.7 to 3.6 (like @jordisala1991 said), but this does not fix the issue.
2. I uncomment the security roles type in UserAdmin, to see if this is causing the error, but still the same error.

I updated the PR header with the stack trace

**Comment by jordisala1991** [comment]
Here is the problem (I think): https://github.com/sonata-project/SonataAdminBundle/pull/4727/files#diff-87a2ac19b26e59d370fce2df773ae451R110

**Comment by jordisala1991** [comment]
Can you check before this commit @OskarStark ?

**Comment by OskarStark** [comment]
really, but why? I am using Sf 3.3

**Comment by jordisala1991** [comment]
https://github.com/sonata-project/SonataAdminBundle/pull/4770

**Comment by elliotbouvier** [comment]
Same issue here with `"sonata-project/user-bundle": "dev-master"` but don't know if it's related tho...

**Comment by Hanmac** [comment]
thanks guys! i thought i broke something

hm whould it be a good idea to use `choice_translation_domain | default(translation_domain)` to prevent maybe other bugs?

@elliotbouvier what stacktrace do you get?
is it related to security type?

**Comment by OskarStark** [comment]
New release is out: https://github.com/sonata-project/SonataAdminBundle/releases/tag/3.25.1

**Comment by elliotbouvier** [comment]
@OskarStark looks like it fixed the issue

**Comment by elliotbouvier** [comment]
Edit: not fixed

**Comment by elliotbouvier** [comment]
Edit2: fixed, ty
