### ISSUE TITLE
Automatically add new media to the field after create with 'btn_add' of 'sonata_type_model_autocomplete'

### ISSUE THREAD

**Issue by gagaXD** [sonata-project/SonataAdminBundle#4802]
Hi,

I just updated to `v3.27`, in order to have the "btn_add" feature on `sonata_type_model_autocomplete` (nice work btw @psyray !)

So, my configuration look like this 
```php
->add('downloads', 'sonata_type_model_autocomplete', array(
                        'multiple' => true,
                        'required' => false,
                        'label' => 'Downloads',
                        'property' => 'name',
                        'minimum_input_length' =>0,
                        'btn_add' => 'Add',
                        'callback' => function ($admin, $property, $value) {
                            $datagrid = $admin->getDatagrid();
                            $queryBuilder = $datagrid->getQuery();
                            $queryBuilder
                                ->andWhere($queryBuilder->getRootAlias() . '.context=:context')
                                ->setParameter('context', 'service_downloads')
                            ;
                            $datagrid->setValue($property, null, $value);
                        },
                    ),
                        array('link_parameters' => array(
                            'context' => 'service_downloads'
                        ))
                    )
```
The add button is displayed correctly.

![image](https://user-images.githubusercontent.com/7262437/33332374-6abef44c-d464-11e7-80b0-f714afd70f4d.png)

But, after adding a media with this button, the media is not automatically bind to the field, and the user have to select it in the form.

Is there any way to automatically add the media to the field with some configuration, or did I miss something on the documentation ?

Regards,

Gaetan

**Comment by jlamur** [comment]
Hello @gagaXD,
Thank you for your feedback about the feature.

It looks like this behaviour was overlooked and should be the "default" behaviour.
@psyray can you give us more details about it?

You can still help by providing a fix if you can.

I link the PR for information: https://github.com/sonata-project/SonataAdminBundle/pull/4753.

**Comment by Ousret** [comment]
Hi,

Still no news about this ? Has someone managed to automatically add the entity to the field after create ?

**Comment by BrianWalters** [comment]
I've had clients and UX people ask me for this feature as well. Looking at the code, it looks pretty hard to extend the widget/modal to do this. I think the best way to add another configuration option like `"add_new"` => true` or something. Anyway, I'm interested in helping with this, let me know where I should start.

**Comment by psyray** [comment]
Sorry for the looooooong delay.
PR created and issue fixed
Enjoy ;)
