### ISSUE TITLE
We should depend upon sonata-exporter ^1.7.1 because 1.7 is broken

### ISSUE THREAD

**Issue by gremo** [sonata-project/SonataAdminBundle#4841]
## Subject
We should depend upon sonata-exporter ^1.7.1. Prior to that release, the bundle compiler pass add a call to [addWriter](https://github.com/sonata-project/exporter/blob/1.7.0/src/Bridge/Symfony/DependencyInjection/Compiler/ExporterCompilerPass.php#L36) which is [still private](https://github.com/sonata-project/exporter/blob/1.7.0/src/Exporter.php#L89).

**Comment by greg0ire** [comment]
:+1: Can you please make a PR?
