### ISSUE TITLE
Navbar moves when in mobile view with new refreshNavbarStuckClass function

### ISSUE THREAD

**Issue by Yippy** [sonata-project/SonataAdminBundle#4850]
In mobile view the navbar overlaps the top table when scrolling, due to new refresh function that does not take in account non sticky nav bar mode.

Example
![sticky nav bar refresh issue](https://user-images.githubusercontent.com/6518915/34065093-99d45d5e-e1f6-11e7-9e85-ada884d7ab0e.png)

Referring to #4678 
@EmmanuelVella 

Workaround is to remove calling Admin.refreshNavbarStuckClass(topNavbar) on line 539 and 549

**Comment by EmmanuelVella** [comment]
Hello, I should be fixed by https://github.com/sonata-project/SonataAdminBundle/pull/4809 right ?

**Comment by Yippy** [comment]
Just checked, #4809 does not fix this issue
