### ISSUE TITLE
Can't override list field template

### ISSUE THREAD

**Issue by lomlom10** [sonata-project/SonataAdminBundle#4860]
## Subject

I'm trying to add a column for the user's image in a UserAdmin's list view but I'm unable to change the default 'base_list_field.html.twig' template 

this is my UserAdmin's list configuration :

` protected function configureListFields(ListMapper $listMapper)
    {
        $listMapper
	        ->add('id')
	        ->add('infos.photo', null, array(
	        	'template' => 'UserBundle:Admin:Photos:list.html.twig'
	        ))
	        ->add('username')
	        ->add('email')
	        ->add('password')
	        ->add('lastLogin')
	        ->add('roles')
            ->add('_action', null, array(
                'actions' => array(
                    'show' => array(),
                    'edit' => array(),
                    'delete' => array(),
                ),
            ))
        ;
    }`

## Actual results
the 'UserBundle:Admin:Photos' template is not being rendered.

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
