### ISSUE TITLE
Question: Is there any reason to make admin services non-shared?

### ISSUE THREAD

**Issue by ossinkine** [sonata-project/SonataAdminBundle#4863]
A long time ago admin services became non-shared. It means the same admin object is created several times per request.
Sometimes this is inconvinient if admin keeps some calculated data.
In my environment making admin services shared is working fine.
Could we make it shared or I lose sight of something?

**Comment by greg0ire** [comment]
> A long time ago admin services became non-shared. 

Can you find the commit when or better, the reason why this happened?

**Comment by ossinkine** [comment]
See https://github.com/sonata-project/SonataAdminBundle/commit/a17cae03413a25af3dcb34b09127e14d0cea51af

**Comment by greg0ire** [comment]
Ok so… there is no reason. Here is what we could do:

1. change that and make a PR, see if the tests pass. If they don't we might have a reason, and we should document it.
2. If they pass, we might release it and brace ourselves for bug reports, then revert the PR and document the reason
3. If no one complains, cool.

In the meantime, I think you should inject a service that would hold your data in those admins.

**Comment by ossinkine** [comment]
I'll make the PR
