### ISSUE TITLE
[SF4] ModelHiddenType has visible label

### ISSUE THREAD

**Issue by jgrygierek** [sonata-project/SonataAdminBundle#4886]
Hi, if I render a `Sonata\CoreBundle\Form\Type\CollectionType` with:

```php
    'edit' => 'inline',
    'inline' => 'table',
```

label of `ModelHiddenType` field will be visible. Even I set label to false, empty table cell still is visible too.

**Comment by OskarStark** [comment]
Hey @jgrygierek, thank you for pointing this out.

Could you find out why and if yes, provide a PR?

**Comment by jgrygierek** [comment]
Created new PR: #4888
