### ISSUE TITLE
[Nested admins]Filtering is always visible, even if empty

### ISSUE THREAD

**Issue by jgrygierek** [sonata-project/SonataAdminBundle#4889]
Hi, probably is a bug with filtering. If child admin is used, even I do not have any filters defined, filters menu is still visible.

Probably connected with:
#4542

**Comment by core23** [comment]
Please use the issue tempate when reporting bugs @jgrygierek

**Comment by jordisala1991** [comment]
There is a PR opened for this, and probably an issue also, please search for them and continue discussion there. If you dont find them, comment here and fill the issue template correctly and we will reopen
