### ISSUE TITLE
side menu option

### ISSUE THREAD

**Issue by Sgnx** [sonata-project/SonataAdminBundle#490]
hi,

documentation says that there is a side menu option ? Do i have to configure it in config.yml ?

If anyone have a simple example it will work for me.

**Comment by webdevilopers** [comment]
@Sgnx @pmartelletti Can we close this issue?

**Comment by pmartelletti** [comment]
@webdevilopers feel free to do so. :)

**Comment by webdevilopers** [comment]
I can't, but @rande can! ;)

**Comment by webdevilopers** [comment]
Please close @Sgnx, @rande .
