### ISSUE TITLE
"Form should not contain extra field" for entity with oneToMany nested in oneToMany

### ISSUE THREAD

**Issue by floriancourgey** [sonata-project/SonataAdminBundle#4904]
## Environment
php 7.2 - symfony 3.4 - sonata admin 3.28 - sonata core 3.7

## Subject

Hi, I'm using Sonata to manage my Sylius entities. Here, 1 taxon has N products, and each product has M attributes.

1 taxon -> N products -> M attributes (Sylius ProductAttributeValue)

I'm trying to get an Admin Class for the taxon, that can add/remove products and for each product, and edit product's attribute, like below:
![image 5](https://user-images.githubusercontent.com/9380369/35296676-ce4eef0a-004a-11e8-9781-ae4e89b0450e.png)
In orange, products ; in green, attributes

Each time I add a product, I only want a limited set of attributes, we don't want to add/remove attributes, there's always the 3 attributes as shown above.

At the moment, the javascript "Add" is working, I can add as many product that I want, always with 3 attributes. But when I submit my form, it says it should not contain extra fields.

## Steps to reproduce

Create TaxonAdmin, ProductAdmin and Attribute Admin
Add a product
Submit the form

## Expected results
Form is validated, Taxon is created with 1 product, which has 3 attributes

## Actual results
Form has errors because it contains extra fields (the attributes fields).
Attributes have been lost.

Here's a screenshot of the submitted form:
![image 7](https://user-images.githubusercontent.com/9380369/35297131-1aa00578-004c-11e8-9998-141c16e4951b.png)
(I slightly changed products' code between the 2 screenshots, don't mind)

Here's a preview of the profiler:
![image 8](https://user-images.githubusercontent.com/9380369/35297271-7f725924-004c-11e8-89ab-35db14d88521.png)

Do you know how it happens? How come I can append field to form with JS, but once submitted, it doesn't work?

Thanks
Florian

**Comment by Yippy** [comment]
@floriancourgey I've witness this issue, you need to restore the products in your controller, creating the empty products would be repopulate within submit. For example

```
$newObject = $this->admin->getNewInstance();

$preResponse = $this->preCreate($request, $newObject);
if ($preResponse !== null) {
    return $preResponse;
}

$params = $request->query->all();
if (array_key_exists('uniqid', $params)) {
    $data = $request->request->all();
    $uniqId = $params['uniqid'];

    if (array_key_exists ($uniqId, $data)) {
        $taxon = $data[$uniqId];
        if (array_key_exists('products', $taxon)) {
            foreach ($taxon['products'] as $value) {
                if (array_key_exists ('id',$value) && empty($value['id'])) {
                    // Add empty entity for the form to pre populate in edit/submit, otherwise error complains there is extra fields
                   $product = new Product();
                   $newObject->addProduct($product);
                }
            }
        }
    }
}
$this->admin->setSubject($newObject);
```

Without putting empty "product" object into your "taxon" the submit form does not know what to do with the extra fields from submit data.

**Comment by floriancourgey** [comment]
Hi Yippy, thanks!

I finally managed to resolve this issue using below code:

Taxon
```php
use Sonata\CoreBundle\Form\Type\CollectionType;

class TaxonAdmin extends AbstractAdmin {
 function configureFormFields() {
       $formMapper->add('products', CollectionType::class, [ // 'products' is a Collection of products
          'by_reference' => false,
          'label' => false,
          'type_options' => [
              'delete' => false,
          ],
        ],
        [
          'edit' => 'inline',
          'inline' => 'table',
        ]);
  }
}
```
Product
```php
class ProductAdmin {
  function configureFormFields() {
    $formMapper->add('attributes', CollectionType::class, [ // Collection of ProductAttribute
      'btn_add' => false,
      'type_options' => [
          'delete' => false,
      ],
      'required' => false,
      'by_reference' => false,
      'label' => 'Caractéristiques',
    ])
    ;
    // adding attributes that are always present 
    // using a function that will be fired in PRE_SET_DATA and POST_SUBMIT
    $repo = $this->em->getRepository(ProductAttribute::class);
    $formModifier = function (FormInterface $form, Product $product) use($repo) {
        $attributesCodes = [
          'duree_nombre',
          'reference',
          'ordre',
          'misEnAvant',
        ];
        foreach ($attributesCodes as $code) {
          $typeAttr = $repo->findOneBy(['code'=>$code]);
           // already existing ?
          $attrDejaExistant = false;
          foreach($product->getAttributes() as $attributeValue){
            if($attributeValue->getAttribute() == $typeAttr){
              $attrDejaExistant = true;
              break;
            }
          }
          if($attrDejaExistant){
            continue;
          }
          $typeVal = $this->repoAttributeValue->createNew();
          $typeVal->setAttribute($typeAttr);
          $typeVal->setProduct($product);
          $typeVal->setLocaleCode('fr');
          $product->addAttribute($typeVal);
      }
    };

    $formMapper->getFormBuilder()->addEventListener(FormEvents::PRE_SET_DATA,
    function(FormEvent $event) use ($formModifier) {
      $form = $event->getForm();
      $product = $event->getData();
      if(!$product){
        return;
      }
      $formModifier($form, $product); // fired
    });

    $formMapper->getFormBuilder()->addEventListener(FormEvents::POST_SUBMIT,
    function(FormEvent $event) use ($formModifier) {
      $form = $event->getForm();
      $data = $event->getData();
      $product = $form->getData();
      if(!$data){
        return;
      }
      $formModifier($event->getForm()->getParent(), $product); // fired
    });

  }
}
```
Product Attribute // TODO
