### ISSUE TITLE
Shouldn't $filter->apply only be called if the filter is "active"

### ISSUE THREAD

**Issue by mmucklo** [sonata-project/SonataAdminBundle#4906]
https://github.com/sonata-project/SonataAdminBundle/blob/499d7d20bdca9a1571ad323fec7b330ad5140aee/src/Datagrid/Datagrid.php#L138-L141 (from your 3.x branch)

Shouldn't this be instead:

```php
        foreach ($this->getFilters() as $name => $filter) {
            $this->values[$name] = isset($this->values[$name]) ? $this->values[$name] : null;
            if ($filter->isActive()) {
                $filter->apply($this->query, $data[$filter->getFormName()]);
            }
        }
```

Why?

If you have filters that are associations (e.g. say you're viewing a "users" table which has an associated "posts" table, and you have a filter that is "users.posts.title" in the users admin), and you are using the Sonata Doctrine ORM bundle, it seems to cause a LEFT JOIN to happen even if you haven't activated the filter, as the ->apply causes the association to be created, causing a 'join' clause to be added to the query even if you're just viewing the grid with no filters selected at all...

Although this may be a bug in the implementation of Filter.php in the doctrine-orm-admin-bundle (sonata-project/doctrine-orm-admin-bundle/src/Filter/Filter.php), I still seem to think that you shouldn't be "applying" inactive filters, but I may be wrong, which is why I'm asking...

**Comment by jordisala1991** [comment]
That could be true, and probably related to other issues about performance with large tables. Can you provide a PR to see if your change is viable? WDYT @greg0ire?

**Comment by greg0ire** [comment]
I don't a see a reason not to do this either, so please try, and if it fails, we'll add a comment.

**Comment by marliotto** [comment]
That patch breaks filters from SonataDoctrineORMAdminBundle.
Because filters from SonataDoctrineORMAdminBundle can be true only after applying.
The class Sonata\DoctrineORMAdminBundle\Filter\Filter has overidden method "isActive".

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/5fd6342333ad4383c5365e1d658df992b1bc37b8/src/Filter/Filter.php#L35-L38
```php 
     public function isActive()
     {
         return $this->active;
     }
```

And can be set in true after using method "applyWhere"
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/5fd6342333ad4383c5365e1d658df992b1bc37b8/src/Filter/Filter.php#L60
```php
    protected function applyWhere(ProxyQueryInterface $queryBuilder, $parameter)
    {
        if (self::CONDITION_OR == $this->getCondition()) {
            $queryBuilder->orWhere($parameter);
        } else {
            $queryBuilder->andWhere($parameter);
        }
        // filter is active since it's added to the queryBuilder
        $this->active = true;
    }
```

**Comment by greg0ire** [comment]
Here @mmucklo

**Comment by mmucklo** [comment]
@greg0ire, @marliotto - What's the fix then?

If you don't have that check then extra queries are being added to the QueryBuilder even when the filter is not active (such as when you first load the page before even filtering anything).

**Comment by greg0ire** [comment]
I don't know. Please revert your PR with a comment explaining what @marliotto said if no one finds a solution quickly.

**Comment by jordisala1991** [comment]
IMO we should revert ASAP and them find a solution

**Comment by mmucklo** [comment]
@jordisala1991, @greg0ire - taking a look now if I can come up with a better fix.

**Comment by mmucklo** [comment]
@jordisala1991, @greg0ire - what do you think of #4913?
