### ISSUE TITLE
sonata-admin  DatagridFilters  entity use "doctrine_orm_model_autocomplete" will be very slow  when in  Large Datasets

### ISSUE THREAD

**Issue by askuiop** [sonata-project/SonataAdminBundle#4908]
sonata-admin  DatagridFilters  entity use "doctrine_orm_model_autocomplete" will be very slow  when in  Large Datasets:

The problem SQL is :

309.11 ms    
 SELECT DISTINCT p0_.id AS id_0, p0_.id AS id_1 
    FROM project p0_ 
    LEFT JOIN company c1_ 
    ON p0_.company_id = c1_.id 
    ORDER BY p0_.id DESC LIMIT 11 OFFSET 0

**Comment by greg0ire** [comment]
1. You're not reporting this on the right repository (sould be doctrine ORM admin bundle)
2. This is probably a duplicate
3. You are no longer supposed to reference forms by that kind of name, use the FQCN instead, and please make a PR to fix the docs you followed if any.
