### ISSUE TITLE
Export will fail if entity contains `point` field

### ISSUE THREAD

**Issue by indapublic** [sonata-project/SonataAdminBundle#4953]
### Environment

OSX 10.12.6
Postgres 9.6

#### Sonata packages

```
sonata-project/admin-bundle              3.30.0 3.31.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.9.0  3.12.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.8.0  3.9.0  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.3.0  3.4.2  Symfony Sonata / Integrate Doctrine O...
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter library
```

#### Symfony packages

```
symfony/monolog-bundle     v3.1.2 v3.1.2 Symfony MonologBundle
symfony/phpunit-bridge     v3.4.2 v4.0.4 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.6.0 v1.7.0 Symfony polyfill backporting apcu_* functions to lo...
symfony/polyfill-intl-icu  v1.6.0 v1.7.0 Symfony polyfill for intl's ICU-related data and cl...
symfony/polyfill-mbstring  v1.6.0 v1.7.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.6.0 v1.7.0 Symfony polyfill backporting some PHP 5.6+ features...
symfony/polyfill-php70     v1.6.0 v1.7.0 Symfony polyfill backporting some PHP 7.0+ features...
symfony/polyfill-util      v1.6.0 v1.7.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7 v3.1.6 Symfony SwiftmailerBundle
symfony/symfony            v3.4.2 v4.0.4 The Symfony PHP framework
```

#### PHP version

```
PHP 7.2.2 (cli) (built: Feb  1 2018 11:47:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```

## Subject

Export will fail if entity contains `point` field

## Steps to reproduce

```
/**
 * @var Point
 *
 * @ORM\Column(name="coordinates", type="point")
 */
private $coordinates;
```

And try to export entity

## Expected results

Export is successfull

## Actual results

Export failed. 

```
[2018-02-16 05:05:34] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\DriverException: "An exception occurred while executing 'SELECT DISTINCT c0_.id AS id_0 FROM client_objects c0_' with params [7]:  SQLSTATE[42883]: Undefined function: 7 ERROR:  could not identify an equality operator for type point LINE 1: ...LECT 
```

If I remove `point` field from export fields, anyway export will fail.

How I can remove `DISTINCT` instruction from select?

**Comment by jordisala1991** [comment]
`point` is a custom type? It seems like it is missing the equal function so it cannot be compared to another points?

**Comment by indapublic** [comment]
@jordisala1991 `point` is reserved type for Postgres https://www.postgresql.org/docs/9.4/static/datatype-geometric.html

**Comment by indapublic** [comment]
Or you mean `Point`?

**Comment by jordisala1991** [comment]
No, I was talking about `type=point`. As far as I know, doctrine has to know about that type. Either because it exists on doctrine directly or someone is adding it

**Comment by indapublic** [comment]
Oh, you are right. Missed it.

```
doctrine:
    dbal:
        types:
            point:  AppBundle\ORM\Type\PointType

        mapping_types:
            point: point

```

So I should to realise `equals` method for `PointType`? 
But I cannot find any method like this inside `Doctrine\DBAL\Types\Type`

**Comment by jordisala1991** [comment]
Did you follow something like this to create it?

**Comment by jordisala1991** [comment]
Well it might be related to postgres not having equality for points ? https://www.postgresql.org/message-id/9419BBB1-4858-4DC0-9FD8-733BAC99CF03%40excoventures.com

**Comment by indapublic** [comment]
Yes, I believe it's related. So my first question was `How I can remove DISTINCT instruction from select?`

**Comment by indapublic** [comment]
Or remove `coordinates` field from export query

**Comment by jordisala1991** [comment]
There is a method to manipulate which fields get exported. For the distinct issue there is already some issues created here and on other sonata repositories: https://github.com/sonata-project/SonataAdminBundle/issues/3147

Since we dont need a new one, and its preferable to centralize the conversation on one `point` I am closing this one.

**Comment by indapublic** [comment]
> There is a method to manipulate which fields get exported

I passed exported fields with `getExportFields` method where I removed `coordinates` field, but query still contains this field.
