### ISSUE TITLE
Automatic fields

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#4960]
The idea is simple: Auto configure fields for form, show, list and data-grid.

Sonata admin goal is to allow highly configurable admin sections, but for most of our entities, we may not need to define anything special than all the fields.

Another suggestions:

- Keep the fields auto-configured even if the class contains a configuration. However, provide a `clearAll` method.
- Possibility to only remove the field we don't want on the configuration method. Same for extensions.
- Another?

**Comment by greg0ire** [comment]
Isn't that already the case?

**Comment by Soullivaneuh** [comment]
Do you have a sample? If I remove all the logic of `configureListFields` of an admin, the only fields I have is the fields from my custom admin extensions.

**Comment by Soullivaneuh** [comment]
The idea is an inspiration form easy-admin. If you don't provide anything on the configuration, it will just guess the field and show them on list, show, form...

But if you configure just one field, all the automatic configuration disappeared. It should be choosable.

**Comment by greg0ire** [comment]
I don't have a sample, sorry. But I think this might be the default behavior for show.

**Comment by Soullivaneuh** [comment]
If it's the case, the same might be done for list, datagrid and form. :+1:
