### ISSUE TITLE
Possibility to add booleans to batch actions

### ISSUE THREAD

**Issue by Quberik** [sonata-project/SonataAdminBundle#4964]
Would be great to easily add booleans to batch actions something like this:

```php
protected function configureBatchActions($actions)
{
    $actions
        ->add('enable', 'boolean')
        ->add('soft_deleted', 'boolean', [
            'no_action' => false
        ])
    ;
}
```

![2018-02-21_10-42-32](https://user-images.githubusercontent.com/3033524/36457119-19501e60-16f4-11e8-9495-ebb849cadb9e.png)

Defining new custom actions for booleans in controller isn't great idea I think.

**Comment by Soullivaneuh** [comment]
Your feature request looks more like batch entity modification and does not apply only for booleans.

See also #4105
