### ISSUE TITLE
Auto-wiring and configuration for Admin Classes

### ISSUE THREAD

**Issue by binhle410** [sonata-project/SonataAdminBundle#4973]
Now that Symfony 4 is out and autowiring and auto-configuration has been made default in their skeleton distro. I would like to suggest we incorporate and implment this concept for Admin Classes.

# New Folder Structure:
I have been using SonataAdminBundle in many of my projects and I have come to realise that the AdminController class should reside in the same folder as the Admin class. Let's face it, this is just like a React or Angular Component where the Controller logic comes hand in hand with the Data Model provided by the Admin class. So, I would have something like:

```
src/
Admin/
    SubPackage A
         A1Admin
         A1AdminController
         A2Admin
         * A2Admin does not have a custom Controller.
```

But this is optional, we don't need this to enable auto-config

# New const in AbstractAdmin to facilitate service autowiring 
```
AbstractAdmin
    const AUTO_CONFIG_ENABLED = null;
    const ENTITY = null;
    const CONTROLLER = null;
```
so in DependencyInjection, we will auto configure all subclasses of AbstractAdmin;
- with AUTO_CONFIG_ENABLED === true
or
- with AUTO_CONFIG_ENABLED === null but having in their services.yaml
```
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
```
Then we look for const ENTITY, if it is null, we will derive the Entity class from the Admin class.
Likewise for CONTROLLER, if it is null, we will automaticlly look for the Controller class in the same folder as the Admin Class, if it does not exist, we will use the default CRUDController.

**Comment by osavchenko** [comment]
Sounds good, but I have suggestions:
* `const CONTROLLER = 'SonataAdminBundle\Controller\CRUDController'` by default
* Controllers should take place in `Controller` folder or it should be independent at all

**Comment by binhle410** [comment]
@osavchenko 
Can we leave it (const CONTROLLER) default to null, and it will automatically look for ```'SonataAdminBundle\Controller\CRUDController'``` when the Controller does not exist in the same folder as the Admin Class, by doing this, we only give more flexibility and sacrifice nothing indeed.

**Comment by jordisala1991** [comment]
Can this be unified with https://github.com/sonata-project/SonataAdminBundle/issues/4710

It would be nice to unify discussions. If this is completely different, ping me to reopen
