### ISSUE TITLE
Get rid of container usage from FilterFactory

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#4982]
Ref: https://github.com/sonata-project/SonataAdminBundle/blob/405c5b2e0fb49d070b73783631352bf57f5ae5fa/src/Filter/FilterFactory.php

Why? Because it's ugly. That's why.

Deprecate it on 3.x, remove it on master.

**Comment by VincentLanglet** [comment]
Close by https://github.com/sonata-project/SonataAdminBundle/issues/6963, I think (cc @franmomu)
