### ISSUE TITLE
Admin create fails to handle object that self-generate their PK in __construct()

### ISSUE THREAD

**Issue by Xymanek** [sonata-project/SonataAdminBundle#5007]
### Environment
Win 10 x64, PHP 7.2 x64 TS, Symfony 4.0.4 flex

#### Sonata packages

```
sonata-project/admin-bundle              3.31.1 ! 3.32.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.0 = 3.12.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  = 2.0.1  Cache library
sonata-project/core-bundle               3.9.1  = 3.9.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  = 2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.4.2  = 3.4.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.8.0  = 1.8.0  Lightweight Exporter library
```

## Subject

Here is a simple entity that showcases this problem:

```php
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;

/**
 * @ORM\Entity()
 */
class Article
{
    /**
     * @var UuidInterface
     *
     * @ORM\Id()
     * @ORM\Column(type="uuid_binary")
     */
    private $uuid;

    /**
     * @var string|null
     *
     * @ORM\Column(type="string")
     */
    private $title;

    public function __construct ()
    {
        $this->uuid = Uuid::uuid4();
    }

    public function getUuid (): UuidInterface
    {
        return $this->uuid;
    }

    public function getTitle (): ?string
    {
        return $this->title;
    }

    public function setTitle (?string $title): Article
    {
        $this->title = $title;
        return $this;
    }
}
```

As you can see, the PK field of the entity is generated when the entity is instantiated, not before/after persist. And here is the admin (`getNormalizedIdentifier ` and `getUrlsafeIdentifier` methods are needed as binary field is used in database):

```php
class ArticleAdmin extends AbstractAdmin
{
    /**
     * @param Article $entity
     * @return string
     */
    public function getNormalizedIdentifier ($entity): string
    {
        return $entity->getUuid()->toString();
    }

    public function getUrlsafeIdentifier ($entity): string
    {
        return $this->getNormalizedIdentifier($entity);
    }

    protected function configureListFields (ListMapper $list)
    {
        $list
            ->add('uuid')
            ->addIdentifier('title');
    }

    protected function configureFormFields (FormMapper $form)
    {
        $form
            ->add('title');
    }
}
```

And here is what I get when going to the create action:

![as](https://user-images.githubusercontent.com/2865341/37206815-d8df2360-23a2-11e8-8c19-ca6d848359e1.png)

As you can see the edit behaviour is used instead of create. Furthermore, pressing the update buttons leads to `/admin/app/article/fbbc88ce-ea6f-40e7-871d-e8209bd7e9c0/edit?uniqid=s5aa275247d772 ` which obviously fails as the entity hasn't been persisted yet.

Small note: delaying the UUID generation to before persisting fixes the problem:

```
     * @ORM\Id
     * @ORM\Column(type="uuid_binary")
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
```

**Comment by jordisala1991** [comment]
Maybe because somewhere, instead of checking correctly for object in the database using the manager, we are just checking if the id is set.

There are many places with conditions like this:

https://github.com/sonata-project/SonataAdminBundle/blob/8088e9384c85689d016dcc587f724a653388a290/src/Resources/views/CRUD/base_edit_form.html.twig#L89

Probably this is the problem

**Comment by Xymanek** [comment]
Actually the problem wasn't the bundle - it was my code. This fixes the behavior:

```php
    public function getNormalizedIdentifier ($entity): ?string
    {
        $parent = parent::getNormalizedIdentifier($entity);

        if ($parent === null) {
            return null;
        }

        return $entity->getUuid()->toString();
    }
```

However I think some things need to be improved for cases when users need to override how object IDs are retrieved. First, the docblock on interface has no mention that `null` should be returned when entity isn't persisted yet: 

https://github.com/sonata-project/SonataAdminBundle/blob/8088e9384c85689d016dcc587f724a653388a290/src/Admin/AdminInterface.php#L241-L246

Second, there is no mention of this situation anywhere in docs. @kunicmarko20 you said you are going to refactor admin docs - probably should add how to deal with cases when the PK is an object (as by default it's converted to database value) or tell me where to put it and I'll do it.

Lastly. maybe it makes sense to add ability to query the `ModelManager` about the state of object? It has that info internally but there is no implementation-agnostic way to access it:

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/af162590f204fd94ac0a6e05150cbc1940470ef5/src/Model/ModelManager.php#L386-L391

**Comment by kunicmarko20** [comment]
As it makes no sense to add this to my PR and this needs a new one, would you be able to create new PR and add this to the docs? @Xymanek

**Comment by Xymanek** [comment]
Yeah, sure. I wrote this before I saw your PR and I was thinking that you were moving stuff around...

Where should I put this? [Here](https://sonata-project.org/bundles/admin/3-x/doc/reference/advanced_configuration.html) at the bottom?

**Comment by kunicmarko20** [comment]
Makes sense or maybe custom page in reference part? wdyt @jordisala1991?

**Comment by jordisala1991** [comment]
Imo a new entry on cookbook section.

But I also think that this should be fixable somehow to not have to add any trick. But maybe we can first document how to do it now, and then think if it can be improved
