### ISSUE TITLE
Admin - form type - FormHelper -  string form 

### ISSUE THREAD

**Issue by michalwroblewski** [sonata-project/SonataAdminBundle#5012]
### Environment
MySQL, iOS.

#### Sonata packages
sonata-project/admin-bundle              3.33.0 3.33.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     1.1.1  2.0.1  Cache library
sonata-project/cache-bundle              2.4.2  2.4.2  This bundle provides caching services
sonata-project/core-bundle               3.9.1  3.9.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.4.2  3.4.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter library
sonata-project/google-authenticator      1.1.0  2.0.0  Library to integrate Google Authenticator into a PHP project
sonata-project/notification-bundle       3.4.0  3.4.0  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.8.0  3.8.0  This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.5.1  2.5.1  Symfony SonataSeoBundle
sonata-project/user-bundle               4.1.1  4.1.1  Symfony SonataUserBundle

#### Symfony packages
symfony/monolog-bundle     v3.2.0 v3.2.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.4.6 v4.0.6 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.7.0 v1.7.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.7.0 v1.7.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.7.0 v1.7.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.7.0 v1.7.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.7.0 v1.7.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.7.0 v1.7.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1 v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7 v3.2.1 Symfony SwiftmailerBundle
symfony/symfony            v3.4.6 v3.4.6 The Symfony PHP framework

#### PHP version
PHP 7.1.1 (cli) (built: Jan 23 2017 15:09:57) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
## Subject
Sonata admin form not support "string" definition of type. For example error message: "Could not load type "choice": class does not exist.". Many of type, mappings is add to FormHellper class but never not use. If I setup sonata_core: form: mapping: enabled: false for true FromHellper is used. I read similar topics but don't give concret answer. Symfony from version 3 remove support for string definition of type. Maybe is some problem in proper configuration, maybe version?

## Steps to reproduce
Login to admin. Go to sample page. Click block list. Click on one of blocks.

## Expected results
Edit block.

## Actual results
Could not load type "choice": class does not exist.

**Comment by jordisala1991** [comment]
You have to use FQCNs for formTypes.

ChoiceType::class
TextType::class

etc...

There are some examples in docs.

**Comment by michalwroblewski** [comment]
Thank You for your answer. It is true for new block, forms etc. 

 But the problem occur because in the class Sonata\BlockBundle\Block\Service\ContainerBlockService in line 59 $formMapper->add('children', 'sonata_type_collection' .... is not use FQCNS. It generate Exception:  Could not load type "sonata_type_collection": class does not exist. I use sonata-project/block-bundle 3.12.1 3.12.1 Symfony SonataBlockBundle.

**Comment by michalwroblewski** [comment]
It is resolved by commit: 
https://github.com/sonata-project/SonataBlockBundle/commit/479f72f512b4da2e7452c15bee653647ea1bf43c ten days ago :) What will it be in use, which version?

**Comment by jordisala1991** [comment]
It was released 16hours ago: https://github.com/sonata-project/SonataBlockBundle/releases/tag/3.12.1

Closing.
