### ISSUE TITLE
List inline forms does not respond to form validations nor transformers

### ISSUE THREAD

**Issue by vytsci** [sonata-project/SonataAdminBundle#5026]
Hello, my first attempt to merge into sonata project community. Ive encountered issue when list inline forms does not respond to any validations nor transformers.

This line should be replaces with something like
https://github.com/sonata-project/SonataAdminBundle/blob/74de207a48abc2d58233d66deb2392cb58c3e95b/src/Controller/HelperController.php#L312
`$form = $admin->getForm();
        $form->setData($object);
        $form->submit([$field => $value], false);`

and this line
https://github.com/sonata-project/SonataAdminBundle/blob/74de207a48abc2d58233d66deb2392cb58c3e95b/src/Controller/HelperController.php#L314

should be replaced with

`$violations = $form->getErrors(true);`

What are your thoughts? Have not tested it properly, but if you approve it is a good idea I will make proper PR.

**Comment by greg0ire** [comment]
I had a quick look at the code, and couldn't find a reason to not to do as you said. Maybe there is a reason, but I don't know, so I'd be ok with your PR. If it causes issues, we will simply revert it, and add a comment to explain why it is like this this time.

**Comment by jordisala1991** [comment]
This needs a little bit of testing. When doing #4992 I tried your solution and got csrf token problems and missing fields when validating form.

Ok to do it, but it will need proper testing on real apps :)

**Comment by vytsci** [comment]
Problem with this thing is that it depends on Admin Form and not Entity form. What Ive tried to say is that injecting data directly into object is bad. You miss every data transformer and validation attached to that field. I do not say my solution is good or best, but I see a problem. Ofc it needs testing and Im currently working on a project with my solution attached, so I will update this thing  as I encouter any issues. Currently if I follow Admin Form created on configureFormFields everything works. Ill test this on a bigger scale soon and will add PR if everything turns out OK.

**Comment by Devristo** [comment]
I seem to hit this issue. If the approach @vytsci is considered correct I could write up a PR.
