### ISSUE TITLE
[Feature] [Proposal] Symfony Workflow component integration

### ISSUE THREAD

**Issue by yann-eugone** [sonata-project/SonataAdminBundle#5028]
This is a feature proposal.

I've been working with Symfony workflow component.
I've tried (and succeed) to integrate a workflow process within a Sonata application.

I wonder if such an integration can be added to the bundle.

### Specifications

My app got a workflow configured for a model for which there is an Admin.

In this situation, I can expect that some action buttons are displayed on the detail page of each model, for each enabled transition.

Each button is pointing to an URI, on which the transition is applied.

As a developer, I should be able to hook into the process and display an intermediate page on which the user is asked for more information to allow applying the transition (an additional form for instance).

On a technical side, I also expects that the every new instance are initialized to the Workflow initial place (if configured).

### Implementation

Regarding the specifications, we see that we need two things : a way to add links to an admin & a way to handle these link actions.

I think that creating a dedicated `AdminExtension` is a good way to :

- add the routes that will cover the transition apply process
- add the buttons (probably in a dropdown) to the side menu
- alter new instances to initialize the initial place

Then we only need a controller action to handle my request. We can easily add this action to the `CRUDController`.

### Proposition

I already wrote some code that do the job in my app.

If you are interested in that feature, I'll open a pull request.

**Comment by Soullivaneuh** [comment]
I personally don't use workflow yet, but why not.

But this must be optional. Maybe it's the place for a dedicated bundle? cc @sonata-project/contributors

**Comment by yann-eugone** [comment]
I totally agree to the fact that this is totally optional.

I believe that this is prety the same as ACL, I'm (almost) never using it, but still, I have the code shipped with the bundle.

The hard part is : where to place the controller action ?

**Comment by greg0ire** [comment]
A separate controller with just one action __invoke?, and all its deps in the constructor would be best IMO

**Comment by greg0ire** [comment]
Also, how about a separate bundle under your name, added to the suggest section, and then moved under the Sonata umbrella when stable and downloaded many times?

**Comment by OskarStark** [comment]
> The hard part is : where to place the controller action ?

what about using traits instead of controllers? So we can implement the trait in the custom admin controller

**Comment by yann-eugone** [comment]
Using a trait is possible but still introduce problems.
If I want to write Sonata like code, I need CRUDController methods and properties : a lot of methods (about 10).

This is always the problem when you write a trait : you expect that it will be used in certain context.

**Comment by slootjes** [comment]
I'm very interested in workflow support for Sonata and maybe it's offtopic for this issue but how would you handle different revisions then? If user A has created some entity and it's published by user B, then user A wants to make changes. What happens to the entity, will it be unpublished? Will the changes be stored temporary? I haven't found a solution with Sonata for this or Doctrine ORM in general. Would be nice if you could share how you want to implement this, maybe I can help you with it at some point.

**Comment by yann-eugone** [comment]
I understand your point, but this is really offtopic. There is nothing to do with Workflows (even if you can bind your publish action to a workflow transition). You should look over something related to versionable entities.

See https://github.com/Atlantic18/DoctrineExtensions/blob/v2.4.x/doc/loggable.md

**Comment by yann-eugone** [comment]
Just created the repository with some doc inside : https://github.com/yokai-php/sonata-workflow

Please let me know if you want me to open a pull request to amend the docs with a link to it.

**Comment by greg0ire** [comment]
Looks great, please do!
