### ISSUE TITLE
Forced nullable type declarations (Type error: Return value of Foo::getBar() must be of the type string, null returned)

### ISSUE THREAD

**Issue by vyshkant** [sonata-project/SonataAdminBundle#5034]
### Environment

<details>
<summary>Sonata packages</summary>

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.33.0 3.33.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.9.1  3.9.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.4.2  3.4.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.4.1  3.4.1  Symfony SonataFormatterBundle
sonata-project/media-bundle              3.11.0 3.11.0 Symfony SonataMediaBundle
sonata-project/notification-bundle       3.4.0  3.4.0  Symfony SonataNotificationBundle
sonata-project/user-bundle               4.1.1  4.1.1  Symfony SonataUserBundle
```
</details>

<details>
<summary>Symfony packages</summary>

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle     v2.8.2 v2.8.2 Integrates Assetic into Symfony2
symfony/monolog-bundle     v3.2.0 v3.2.0 Symfony MonologBundle
symfony/phpunit-bridge     v4.0.6 v4.0.6 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.7.0 v1.7.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.7.0 v1.7.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.7.0 v1.7.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.7.0 v1.7.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.7.0 v1.7.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.7.0 v1.7.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.7.0 v1.7.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1 v3.0.1 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v3.2.1 v3.2.1 Symfony SwiftmailerBundle
symfony/symfony            v3.4.6 v4.0.6 The Symfony PHP framework
```
</details>

<details>
<summary>PHP version</summary>

```
$ php -v
PHP 7.2.3-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  6 2018 11:18:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```
</details>

## Subject

The problem is that SonataAdminBundle forces me to make nullable type declaration on non-nullable value getter.

## Steps to reproduce

Suppose I have doctrine entity called `Foo`. It has one non-nullable string property `$bar`.

To implement such an entity, I create a class of the following kind:

<details>
<summary>MyAwesomeBundle/Entity/Foo.php</summary>

```php
<?php

declare(strict_types=1);

namespace MyAwesomeBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table
 * @ORM\Entity
 */
class Foo
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string")
     */
    private $name;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * @param string $name
     *
     * @return Foo
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string
     */
    public function getName(): string
    {
        return $this->name;
    }
}
```
</details><br>

I use php7, so knowing that the `$bar` property cannot be null, I can determine the type declaration `: string` for its getter as it is shown above.

Then I create admin class for this entity:

<details>
<summary>MyAwesomeBundle/Admin/FooAdmin.php</summary>

```php
<?php

declare(strict_types=1);

namespace MyAwesomeBundle\Admin;

use Sonata\AdminBundle\Admin\AbstractAdmin;
use Sonata\AdminBundle\Form\FormMapper;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class FooAdmin extends AbstractAdmin
{
    /**
     * @param FormMapper $formMapper
     */
    protected function configureFormFields(FormMapper $formMapper): void
    {
        $formMapper
            ->add('name', TextType::class, [
                'label' => 'foo.name',
            ])
        ;
    }
}
```
</details><br>

The next step I configure the service for this admin class:
<details>
<summary>MyAwesomeBundle/Resources/config/services.yml</summary>

```yml
    MyAwesomeBundle\Admin\FooAdmin:
        arguments: [~, MyAwesomeBundle\Entity\Foo, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
```
</details><br>

Then I go to SonataAdmin and try to create new entity (URL ~ http://mysite.local/app_dev.php/admin/myawesome/foo/create)

## Expected results

A form to create new entity instance.

## Actual results

```
Symfony\Component\Debug\Exception\FatalThrowableError:
Type error: Return value of MyAwesomeBundle\Entity\Foo::getBar() must be of the type string, null returned

  at src/MyAwesomeBundle/Entity/Foo.php:100
  at MyAwesomeBundle\Entity\Foo->getBar()
     (vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:473)
  at Symfony\Component\PropertyAccess\PropertyAccessor->readProperty(array(object(Foo)), 'bar')
     (vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:396)
  at Symfony\Component\PropertyAccess\PropertyAccessor->readPropertiesUntil(array(object(Foo)), object(PropertyPath), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/PropertyAccess/PropertyAccessor.php:165)
  at Symfony\Component\PropertyAccess\PropertyAccessor->getValue(object(Foo), object(PropertyPath))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Extension/Core/DataMapper/PropertyPathMapper.php:49)
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(object(Foo), object(RecursiveIteratorIterator))
     (vendor/symfony/symfony/src/Symfony/Component/Form/Form.php:383)
  at Symfony\Component\Form\Form->setData(object(Foo))
     (vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php:559)
  at Sonata\AdminBundle\Controller\CRUDController->createAction()
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:29)
```

## My suggestion

My suggestion is to make the SonataAdminBundle does not force me to violate my business logic for the sake of the SonataAdminBundle's internal reasons.

I think we can try to use some features of `Reflection` to make all the properties we are trying to access nullable.

**Comment by kunicmarko20** [comment]
This is not Sonata issue, this is how Symfony forms work. They first get all the properties and fill the object so your getters need to be nullable. I am going to close this if you think this is a problem on our side I will reopen.

**Comment by jordisala1991** [comment]
I was about to answer too:

IMO your entity allows to create it without defining any field, so I could do like this:

$foo = new Foo();
$foo->getName();

and it will fail because your type hint says only string but it is returning null. Not sure if this is a problem on Sonata, but looks like the getter should be ?string unless you define a default value for the field

**Comment by vyshkant** [comment]
> IMO your entity allows to create it without defining any field, so I could do like this:

Yes, but we are not talking about creating an object of **any class**, we're talking about creating **doctrine entity**. And I think that the creation of a `integral entity` is not confined to the constructor call.

For example, when defining symfony service, we can specify the "calls" values that must be called before the service is considered to be created. IMO same here.

**Comment by vyshkant** [comment]
> This is not Sonata issue, this is how Symfony forms work. They first get all the properties and fill the object so your getters need to be nullable. I am going to close this if you think this is a problem on our side I will reopen.

I don't see any **logical** reason why I have to keep my type declaration nullable while an **integral entity** does not allow this property to be null.

I do understand that there are "technical" reasons like SF forms behavior, etc.

So my question is: if I found the way how to make sure that the user is not forced to make **all the getters** nullable, — would take a look at it? I mean, do you agree that it would be better not to force the user to do all the getters nulable?

**Comment by jordisala1991** [comment]
It is a doctrine entity, yes. But without the nullable type, you are not able to use the entity if it is not recovered from the database or created by a form? I does not make a lot of sense to me.

If symfony forms have that limitation (I dont know if they do), my opinion would be not to hack them to avoid putting a ? on a return type.

**Comment by jordisala1991** [comment]
IMO the same with getId, you are forcing it to be int, but doctrine entities have null id until you save them. And that’s a doctrine behavior.

**Comment by vyshkant** [comment]
Yes, but from the user's point of view, it looks like, "Damn, I'm using the SonataAdminBundle, so I need to make two hundreds of getters nullable against my business logic".

Yes, there is an internal need for a SonataAdminBundle, but IMO, the user does not need to know about the limitations of SF forms (because he uses not SF forms, but Sonata). And of course, if these limitations can be lowered, I believe that they should be lowered.

> But without the nullable type, you are not able to use the entity if it is not recovered from the database or created by a form?

I think this can be a part of business logic. Personal I avoid to use "raw" entities, someone else doesn't. And in my business logic a call to `getBar()` while non-nullable `bar` is null, is a logic error, which need to be fixed. But SonataAdminBundle (because of SF forms) doesn't allow me to keep my business logic.
