### ISSUE TITLE
Typehint actions with Request instead of getCurrentRequest()

### ISSUE THREAD

**Issue by slootjes** [sonata-project/SonataAdminBundle#5036]
When trying to extend the _dashboardAction_ I found out that it's currently not possible to get the request object in a proper way. As far as I know it's preferred by Symfony that the Request object is type hinted in the controller but since the CoreController does not do this I also can't do it (at least not in PHP 7.0). getCurrentRequest() is private so not accessible and getRequest() is accessible but deprecated. My proposal would be to either type hint the Request object in the actions or make getCurrentRequest() protected so it can be accessed the proper way from overridden controllers. While looking at the tests it noticed the dashboardAction does receive a request object so the test is currently mismatching (but not breaking) with the code.

**Comment by jordisala1991** [comment]
This can't be done on 3.x without breaking BC. This needs to be done on master

**Comment by slootjes** [comment]
So what would be the preference, type hint Request everywhere or make getCurrentRequest() protected? I would opt for the first option personally.

**Comment by jordisala1991** [comment]
First option seems better
