### ISSUE TITLE
Make form css classes more accessible

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#5043]
## Subject

Currently, we have some attributes like that:

```
id="sonata-ba-field-container-s5abb5e07dd797_title"
class="sonata-ba-td-s5abb5dca1144d_changelogs-content"
...
```

I supposed those attributes are here for CSS and JS tricks, but it's currently hard to handle them for CSS customization because of the dynamic form name.

I propose to remove the dynamic part for attributes, at least for classes.

Something like this: `class="sonata-ba-td-_changelogs-content"`

Or: `id="sonata-ba-field-container-s5abb5e07dd797_title" class="sonata-ba-field-container-_title"`

To keep BC, we may keep both class generation and remove the current one on next major, because I don't see the interest to keep it.

What do you think?

**Comment by greg0ire** [comment]
I'm not sure if you can safely remove it (why are they there in the first place). Until we agree on a solution, I think you can still match those with css thanks to tricks like this one: https://stackoverflow.com/questions/8903313/using-regular-expression-in-css#8903451

**Comment by greg0ire** [comment]
Ah right, that should be ok :+1:
