### ISSUE TITLE
No validation?

### ISSUE THREAD

**Issue by goyote** [sonata-project/SonataAdminBundle#505]
Other than the client side HTML5 validation, is there no validation done on the server? I thought the validation constraints were read form the entity annotations, but `if ($form->isValid()) {` fails to read them, how does one apply validation on the server side?

**Comment by Renrhaf** [comment]
Hi, thanks for SonataAdminBundle which is very useful. Can someone tell me how to change validation groups based on submitted data (like in the official documentation: https://symfony.com/doc/current/form/data_based_validation.html) ?
