### ISSUE TITLE
Small correction in documentation

### ISSUE THREAD

**Issue by lukepass** [sonata-project/SonataAdminBundle#5056]
Hello, where can I edit the online documentation to fix small things?

https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/action_list.html

```
->add('description', TextType::class, [
    'header_style' => 'width: 35%',
    'collapse' => [
        'height' => 40, // height in px
        'read_more' => 'I want to see the full description', // content of the "read more" link
        'read_less' => 'This text is too long, reduce the size' // content of the "read less" link
    ]
])
```

^ This is wrong, the parameters are called `more` and `less` (looked into source).

Thanks.

**Comment by kunicmarko20** [comment]
You edit https://github.com/sonata-project/SonataAdminBundle/blob/3.x/docs/reference/action_list.rst

**Comment by lukepass** [comment]
Ok I did it and made a pull request.

**Comment by kunicmarko20** [comment]
Did you submit PR? because I do not see it here.

**Comment by lukepass** [comment]
Yes, I edited here:
https://github.com/sonata-project/SonataAdminBundle/edit/3.x/docs/reference/action_list.rst

Clicked here:
![image](https://user-images.githubusercontent.com/6429961/38361803-e9e5a9d6-38ce-11e8-887d-cddf7a105a21.png)

And this should be the change:
https://github.com/sonata-project/SonataAdminBundle/compare/3.x...lukepass:patch-1

**Comment by jordisala1991** [comment]
You need to create the PR: https://github.com/sonata-project/SonataAdminBundle/compare/3.x...lukepass:patch-1

**Comment by lukepass** [comment]
Ok, I think I did it :)
https://github.com/sonata-project/SonataAdminBundle/pull/5057
