### ISSUE TITLE
Sidebar toggle buttion is not working with AdminLTE 2.4

### ISSUE THREAD

**Issue by soullivaneuh** [sonata-project/SonataAdminBundle#5066]
## Subject

Because of a missing attribute. I'm working on it.

**Comment by Soullivaneuh** [comment]
Well, we can't currently fix it because it's introduce a BC break.

In 2.3:

```html
<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button"></a>
```

In 2.4:

```html
<a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button"></a>
```

As we currently use 2.3, I can't change it. I leave the issue opened for the time we will upgrade.

A tiny hack is possible if you still want to upgrade AdminLTE yourself:

```javascript
jQuery(document).ready(() => {
  $('a.sidebar-toggle[data-toggle="offcanvas"]').attr('data-toggle', 'push-menu');
});
```

**Comment by jordisala1991** [comment]
Tagged as major enhancement, since we use 2.3 and it is not a bug.

**Comment by Soullivaneuh** [comment]
@jordisala1991 The issue itself is not a major. I don't see why we can't allow upgrade for JS package.

The other issue that will be major is the migration to a yarn/npm package. :+1:
