### ISSUE TITLE
Required fields not showing the required class in label using sonata_type_collection

### ISSUE THREAD

**Issue by simonbertonsugasti** [sonata-project/SonataAdminBundle#5089]
Environment: 3.10.*

Sonata packages
Sonata\CoreBundle\SonataCoreBundle()
Sonata\BlockBundle\SonataBlockBundle()
Sonata\DoctrineORMAdminBundle\SonataDoctrineORMAdminBundle()
Sonata\AdminBundle\SonataAdminBundle()

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.5.0  3.35.1 The missing Symfony A...     
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBu...
sonata-project/cache                     1.0.7  1.0.7  Cache library
sonata-project/core-bundle               3.6.0  3.9.1  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagri...
sonata-project/doctrine-orm-admin-bundle 3.0.5  3.6.0  Symfony Sonata / Inte...
sonata-project/exporter                  1.8.0  1.8.0  Lightweight Exporter ...
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/assetic-bundle       v2.8.2 v2.8.2 Integrates Assetic into Symfony2         
symfony/monolog-bundle       v3.2.0 v3.2.0 Symfony MonologBundle
symfony/polyfill-apcu        v1.7.0 v1.7.0 Symfony polyfill backporting apcu...
symfony/polyfill-intl-icu    v1.7.0 v1.7.0 Symfony polyfill for intl's ICU-r...
symfony/polyfill-mbstring    v1.7.0 v1.7.0 Symfony polyfill for the Mbstring...
symfony/polyfill-php56       v1.7.0 v1.7.0 Symfony polyfill backporting some...
symfony/polyfill-php70       v1.7.0 v1.7.0 Symfony polyfill backporting some...
symfony/polyfill-util        v1.7.0 v1.7.0 Symfony utilities for portability...
symfony/proxy-manager-bridge v4.0.8 v3.4.8 Symfony ProxyManager Bridge
symfony/security-acl         v3.0.1 v3.0.1 Symfony Security Component - ACL ...
symfony/swiftmailer-bundle   v2.6.7 v3.2.2 Symfony SwiftmailerBundle
symfony/symfony              v3.4.8 v3.4.8 The Symfony PHP framework
symfony/web-server-bundle    v4.0.8 v3.4.8 Symfony WebServerBundle
```

#### PHP version

```
$ php -v
PHP 7.0.28-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.28-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies
```

## Steps to reproduce
Class ONE
OneToMany relation to Class TWO.

on the AdminClass of the Class ONE
configureFormFields
 $mapper->add('classTwo', 'sonata_type_collection', array(
                        'required' => false,
                        'by_reference' => true,
                        'constraints' => new \Symfony\Component\Validator\Constraints\Valid(),
                    ), array(
                        'edit' => 'inline',
                        'inline' => 'standard',
                        'sortable' => 'position',
                    ))
classTwo has multiple parameters that on the mapper I put required->true.

Validation works when form is POSTED but no label *
## Expected results
label should have class required
## Actual results
label of field does not have required

**Comment by kunicmarko20** [comment]
You added `'required' => false,`?

**Comment by simonbertonsugasti** [comment]
required -> false for the sonata_type_collection classTwo

All the fields in classTwo have required -> true on the mapper.

**Comment by jordisala1991** [comment]
Hmm I remember a issue about this same thing.

**Comment by jordisala1991** [comment]
Why do you use required false in the collection. That does not check that you need to add atleast one item, but it affects the inner required fields

**Comment by simonbertonsugasti** [comment]
I use the required false because the second class is an item that is not required, but when I introduce one I want it to check the required fields of that class.

**Comment by jordisala1991** [comment]
Have you tried simply not adding anything? Try without required attribute on the collection

**Comment by simonbertonsugasti** [comment]
So for the required check on the embedded class, it needs to have required true on the sonata_type_collection?
Thanks

**Comment by jordisala1991** [comment]
Yes

**Comment by kunicmarko20** [comment]
Can we close this?

**Comment by jordisala1991** [comment]
It is explained on the docs too: https://sonata-project.org/bundles/admin/3-x/doc/reference/form_types.html

```
TIP: Setting the ‘required’ option to true does not cause a requirement of ‘at least one’ child entity. Setting the ‘required’ option to false causes all nested form fields to become not required as well.
```

Closing

**Comment by simonbertonsugasti** [comment]
Thanks !!!
