### ISSUE TITLE
Using configureDefaultFilterValues opens the filter does not show values in the list

### ISSUE THREAD

**Issue by 5zymon** [sonata-project/SonataAdminBundle#5092]
sonata-project/admin-bundle              3.35.1
symfony/symfony                          v2.8.38

Add default filter values in the LIST view by using  configureDefaultFilterValues method for example:

        $filterValues['someFilter'] = [
            'type' => ChoiceType::TYPE_CONTAINS,
            'value' => array(
                'SomeValue in the filter'
            ),
        ];

Results that I expected:

List filtered
filter uncompressed showing value selected above
filter counter showing 1 instead of 0.

Actual results:
List IS filtered (that is correct)
Filter is opened but nothing is visible inside except buttons "filter" and "reset".
Filter counter showing 0.

To get expected results you need to use drop down filter and click the same filter option again.

**Comment by jordisala1991** [comment]
Duplicated of #4497 

Closing
