### ISSUE TITLE
i have these problem, help me please

### ISSUE THREAD

**Issue by rifanajah** [sonata-project/SonataAdminBundle#5106]
C:\xampp2\htdocs>laravel new kameraku
Crafting application...
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - This package requires php ^7.1.3 but your PHP version (5.6.3) does not satisfy that requirement.
  Problem 2
    - laravel/framework v5.6.9 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.8 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.7 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.6 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.5 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.4 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.3 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.23 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.22 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.21 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.20 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.2 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.19 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.18 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.17 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.16 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.15 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.14 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.13 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.12 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.11 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.10 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.1 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework v5.6.0 requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - laravel/framework 5.6.x-dev requires php ^7.1.3 -> your PHP version (5.6.3) does not satisfy that requirement.
    - Installation request for laravel/framework 5.6.* -> satisfiable by laravel/framework[5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17, v5.6.18, v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.3, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].

Application ready! Build something amazing.

**Comment by FireLizard** [comment]
> This package requires php ^7.1.3 but your PHP version (5.6.3) does not satisfy that requirement.

Try to upgrade your PHP to at least 7.1.3

**Comment by greg0ire** [comment]
That's so cute lol
