### ISSUE TITLE
sensio/generator-bundle for Symfony 4

### ISSUE THREAD

**Issue by andreybolonin** [sonata-project/SonataAdminBundle#5108]
## Feature Request
https://symfony.com/blog/introducing-the-symfony-maker-bundle

<img width="596" alt="screen shot 2018-05-28 at 3 42 45 pm" src="https://user-images.githubusercontent.com/2576509/40615041-ce23f8f4-628d-11e8-8a11-72bda78a83dd.png">

`sensio/generator-bundle` is not supported with Symfony 4.

How to use `sonata:admin:generate` in Symfony 4 ?

**Comment by kunicmarko20** [comment]
Sensio generator does not work with symfony4, @indiancomet is working on it https://github.com/sonata-project/SonataAdminBundle/pull/5093
