### ISSUE TITLE
checkParentChildAssociation  function should be protected

### ISSUE THREAD

**Issue by gomcodoctor** [sonata-project/SonataAdminBundle#5119]
## Feature Request

`Sonata\AdminBundle\Controller\CRUDController` has `private function checkParentChildAssociation`

it should be protected for reusing it in extended controller

**Comment by greg0ire** [comment]
If you want you can make a pull request to make it `final protected`

**Comment by kunicmarko20** [comment]
But if it is final protected, they still can’t overwrite it?

**Comment by gomcodoctor** [comment]
same apply to other `function setFormTheme` in same `Sonata\AdminBundle\Controller\CRUDController`

**Comment by greg0ire** [comment]
> it should be protected for reusing it in extended controller

It says "reusing", not overwrite.

@gomcodoctor if you make a PR, please explain why you need to reuse this function so that we can see if there is really no better solution than opening access.

**Comment by gomcodoctor** [comment]
@greg0ire yaa I wanted to reuse it in extended controller.
but if we allow overwrite then it will add more flexibility.

so `final protected ` is must if not `protected`  , `private` is not good choice

**Comment by greg0ire** [comment]
>  but if we allow overwrite then it will add more flexibility.

It also means you add more constraints on changes to the signature of the function.

> private is not good choice

`private` is an excellent choice until proven otherwise on a method per method basis. If proven otherwise, then we make it `final protected`, and if this is proven to be not enough, then we make it just `protected`. Please show us your code and we'll see what level is needed, and if any alternatives are possible to avoid opening our API.

**Comment by gomcodoctor** [comment]
I have to add this function in extended controller

`public function closeAction($id)
    {
        $request = $this->getRequest();
        $id = $request->get($this->admin->getIdParameter());
        $object = $this->admin->getObject($id);

        if (!$object) {
            throw $this->createNotFoundException(sprintf('unable to find the object with id: %s', $id));
        }

        $this->checkParentChildAssociation($request, $object);

        $this->admin->checkAccess('close', $object);

        if ('CLOSE' == $this->getRestMethod()) {
            // check the csrf token
            $this->validateCsrfToken('sonata.close');

            $objectName = $this->admin->toString($object);

            try {
                $this->admin->close($object);

                if ($this->isXmlHttpRequest()) {
                    return $this->renderJson(['result' => 'ok'], 200, []);
                }

                $this->addFlash(
                    'sonata_flash_success',
                    $this->trans(
                        'flash_close_success',
                        ['%name%' => $this->escapeHtml($objectName)],
                        'SonataAdminBundle'
                    )
                );
            } catch (ModelManagerException $e) {
                $this->handleModelManagerException($e);

                if ($this->isXmlHttpRequest()) {
                    return $this->renderJson(['result' => 'error'], 200, []);
                }

                $this->addFlash(
                    'sonata_flash_error',
                    $this->trans(
                        'flash_close_error',
                        ['%name%' => $this->escapeHtml($objectName)],
                        'SonataAdminBundle'
                    )
                );
            }

            return $this->redirectToList();
        }

        // NEXT_MAJOR: Remove this line and use commented line below it instead
        $template = $this->admin->getTemplate('close');
        // $template = $this->templateRegistry->getTemplate('delete');

        return $this->renderWithExtraParams($template, [
            'object' => $object,
            'action' => 'close',
            'csrf_token' => $this->getCsrfToken('sonata.close'),
        ], null);
    }`

this function is using checkParentChildAssociation like deleteAction function in parent class

**Comment by greg0ire** [comment]
Ok, I think it makes sense to make it `final protected`

**Comment by gomcodoctor** [comment]
@greg0ire  thanks 😄 
this is where I stuck always when PR is requested 😞 
Can you please send me some link to guide me how to create a PR on bundle, last time I tried to create PR, some permission issue occurred

**Comment by greg0ire** [comment]
Here is our guide: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/CONTRIBUTING.md#pull-requests

If you need more help, we are on #sonata on [the symfony-devs slack](https://symfony.com/slack-invite).
