### ISSUE TITLE
Content Format field does not change from default value when created  or updated

### ISSUE THREAD

**Issue by BigShanJohn** [sonata-project/SonataAdminBundle#5121]
sonata-project/admin-bundle              3.35.0             3.35.2
sonata-project/block-bundle              3.12.1             3.12.1
sonata-project/cache                     2.0.1              2.0.1
sonata-project/classification-bundle     3.6.1              3.7.0
sonata-project/core-bundle               3.9.1              3.9.1
sonata-project/datagrid-bundle           2.3.1              2.3.1
sonata-project/doctrine-extensions       1.0.2              1.0.2
sonata-project/doctrine-orm-admin-bundle 3.5.1              3.6.1
sonata-project/easy-extends-bundle       2.5.0              2.5.0
sonata-project/exporter                  1.8.0              1.9.0
sonata-project/formatter-bundle          3.4.1              3.5.0
sonata-project/intl-bundle               2.4.0              2.4.1
sonata-project/media-bundle              3.12.0             3.13.1
sonata-project/news-bundle               dev-master 3c8367f dev-master 37876c0
sonata-project/user-bundle               4.1.1              4.2.2

**Comment by core23** [comment]
Can you please say a little bit more... And use the issue template please

**Comment by BigShanJohn** [comment]
Thanks for you quick response.   sonata formatter select field  always  set itself to default even if you update the post
