### ISSUE TITLE
Replace custom attributes with valid w3c attributes

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#5132]
According to w3c custom attributes should start with `data-*`

- [ ] Update https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle
- [ ] Update https://github.com/sonata-project/SonataDoctrineORMAdminBundle
- [x] Update https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle
- [x] Update https://github.com/sonata-project/SonataPropelAdminBundle

Refs #3312

**Comment by VincentLanglet** [comment]
Closing due to lack of interest
