### ISSUE TITLE
getListParameters() like getFilterParameters(), for default list view

### ISSUE THREAD

**Issue by MyTheValentinus** [sonata-project/SonataAdminBundle#5143]
## Feature Request
Hello !
My idea is to add the possibility to make default list view for users. Add optional fields in the list admin.
Like `getFiilterParameters()` but for list fields. Add method for default view or add another option in `->add()` method of `ListMapper`:

```php
protected function configureListFields(ListMapper $list)
{
    $list
    ->add('name', null, [
        'label' => 'label.name',
        'default_selected' => false
    ])
}
```

In admin:

![https://i.imgur.com/iliVd6P.png](https://i.imgur.com/iliVd6P.png)

**Comment by MyTheValentinus** [comment]
Any news ? Thanks

**Comment by kunicmarko20** [comment]
I don't understand why can you explain a bit why would someone need this?

I currently understand that this would allow users to select which fields they want to see in the list view, I just don't get why would anyone want that?

**Comment by MyTheValentinus** [comment]
In my case, users request to have possibility to add additional input hidden by default for small screens. Or where column does not serve all the time, but at specific time user need to see one information.

**Comment by OskarStark** [comment]
We have the same use case an implemented something with JS were we render all columns and only display some of the configured, and a user can persist his selection
