### ISSUE TITLE
Unable to define timezone for datetime in show field

### ISSUE THREAD

**Issue by Awkan** [sonata-project/SonataAdminBundle#5156]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.35.2 3.36.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.9.1  3.11.2 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.3.1  2.3.1  Symfony SonataDatagridBundle
sonata-project/doctrine-orm-admin-bundle 3.6.1  3.6.1  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.9.0  1.9.1  Lightweight Exporter library
```

#### Symfony packages
Symfony 3.4 Flex

#### PHP version
PHP 7.1

## Subject

As we can see in the [following PR](https://github.com/sonata-project/SonataAdminBundle/pull/3257), timezone option is used for `list__datetime` field. However the modification wasn't provided for `show__datetime`. Same problem with `show__time` & `list__time`.

This mean these tests are wrong : https://github.com/sonata-project/SonataAdminBundle/blob/3.x/tests/Twig/Extension/SonataAdminExtensionTest.php#L1458
You are testing that datetime with UTC+0 is same ... This should be updated with a non UTC timezone

## Steps to reproduce

- Create a DateTime field
- Display it in your show action by setting the option `'timezone' => 'Europe/Paris'` for example

## Expected results

- Display date with `Europe/Paris` timezone

## Actual results

- The DateTime is displayed with UTC timezone

## Solution

- Make the show template similar to list one. If you're ok with that, I can make a PR 😉

**Comment by OskarStark** [comment]
A PR would be great 👍🏻
