### ISSUE TITLE
Reduce page size on forms using multiple select2 widgets

### ISSUE THREAD

**Issue by djpretzel** [sonata-project/SonataAdminBundle#5184]
## Feature Request

 
- The current implementation of autocompletes injects a heavy amount of inline JavaScript for each field (https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/Form/Type/sonata_type_model_autocomplete.html.twig)
- On a form with 30+ lookups, this can result in 3MB  & 70,000+ lines of HTML, once variables have been substituted in
- Given that autocompletes are intended to reduce the burden of page/server load for fields with many relations, this doesn't seem scalable
- If the javascript could be modularized/parameterized into a plugin, or set of methods, that are defined only once and then called by each field instance, page size would be decreased considerably

**Comment by OskarStark** [comment]
Would you like to provide a PR?

Feel free to discuss your idea how to solve it (if any) in this issue.

Thank you
