### ISSUE TITLE
CKEditor EndOfLife Issue

### ISSUE THREAD

**Issue by fafiebig** [sonata-project/SonataAdminBundle#5222]
## Feature Request

Due to the fact that CKEditor is no longer maintained, is there any chance to switch to let's say FOSCKEditorBundle or similar?

The CKEditor has several JS vulnerabilities and should be replaced anytime soon.

**Comment by kunicmarko20** [comment]
Switch is already documented in the SonataFormatter documentation. Regarding those js vulnerabilities, can you please open issues on FOSCke repo (since it is the same ckeditor) or find me on symfony slack on #fosckeditorbundle channel.

**Comment by OskarStark** [comment]
Any progress here guys?

**Comment by kunicmarko20** [comment]
Formater 4.x was released which uses fos cke, this can be closed.
