### ISSUE TITLE
Controllers Should Not Be Referenced With Single Colon Syntax

### ISSUE THREAD

**Issue by kiler129** [sonata-project/SonataAdminBundle#5227]
## Feature Request
Symfony 4.1 deprecates bundle notation (e.g. `SonataAdminBundle:CRUS:export`) - https://symfony.com/blog/new-in-symfony-4-1-deprecated-the-bundle-notation. The change causes a lot of `E_USER_DEPRECATED`:
![image](https://user-images.githubusercontent.com/1227834/45323561-27b45000-b511-11e8-949a-8bc3acfe93e8.png)

While it doesn't break anything it will be good to fix this by simply replacing `:` with `::` when controllers are references.
This is a similar issue to e.g. https://github.com/FriendsOfSymfony/FOSRestBundle/issues/1897

I'm not that famillar with Sonata codebase, but I see this syntax is really only used in https://github.com/sonata-project/SonataAdminBundle/blob/312593909ca0b21cf723e07660b966a15a385916/src/DependencyInjection/Compiler/AddDependencyCallsCompilerPass.php#L63-L65

**Comment by greg0ire** [comment]
Can you try changing it directly in your vendor files and running the command again, to confirm your hypothesis?

**Comment by kiler129** [comment]
@greg0ire Yes, in terms of AdminBundle it fixes the problem, now we need a separate issue for MediaBundle:

![image](https://user-images.githubusercontent.com/1227834/45324562-1751a480-b514-11e8-8158-f718aa610249.png)

**Comment by DanieleGBX** [comment]
I'm all about those easy picks.
