### ISSUE TITLE
Deprecate annotations

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#5272]
## Feature Request

We should deprecate `Sonata\AdminBundle\Annotation\Admin`, because it relys on the outdated DiExtraBundle.

We could recommend https://github.com/kunicmarko20/SonataAnnotationBundle instead

**Comment by kunicmarko20** [comment]
So you suggest to deprecate the Admin annotation but to add #5271 ? :joy:

**Comment by core23** [comment]
Oh, your right 😅

Mayve you should add it to your repository 😁

**Comment by core23** [comment]
@kunicmarko20 Is there a reason why you switched from annotations on the admin class to the entity class?

**Comment by kunicmarko20** [comment]
Because in most cases the admin class is redundant, I didn't see a point in having an empty admin class.

**Comment by core23** [comment]
In that case we should keep the annotations inside the sonata bundle and recommend your bundle

**Comment by kunicmarko20** [comment]
There is already a page in a cookbook about my bundle. I just wonder how many people are still using JmsDI. I am fine with any choice.

**Comment by core23** [comment]
Closing this, because this are different solutions for autowiring

**Comment by core23** [comment]
We should get rid of JmsDI and use Doctrine Annotations instead
