### ISSUE TITLE
Remove preliminary permissions checks from RetrieveAutocompleteItemsAction

### ISSUE THREAD

**Issue by warslett** [sonata-project/SonataAdminBundle#5282]
## Bug Report
On line 47 of Sonata\AdminBundle\Action\RetrieveAutocompleteItemsAction is the following code

```php
if ('filter' === $context) {
    $admin->checkAccess('list');
} elseif (!$admin->hasAccess('create') && !$admin->hasAccess('edit')) {
    throw new AccessDeniedException();
}
```
The code is checking that the user has permission to either list (if they are using the field in the context of a filter on the list page OR to either create or edit if they are using it in the context of a form field). This is presumably because we consider that if a user is accessing the autocomplete without any of these permissions they might be up to no good.

This approach is problematic in a few different situations:
1. A user may be granted edit access on specific objects by way of a voter or an overridden hasAccess method on their admin, but not granted edit access in general. This means they will be editing a record they are allowed to edit and the autocomplete function won't work (this is the scenario that has stumped me)
2. The developer may have created custom actions on the admin that use their own admin access mapping. In which case they can't use these form fields in their own custom actions because it has been hard coded to only allow users with create and edit permissions.

These checks are not really necessary because even if a user is accessing this action and doesn't have create or edit permissions, the action will not allow them create or edit anything they shouldn't be able to. It will only allow them to query a list of options available for a particular field. Access to this is checked separately on the target admin and can be configured in the options. I think it should be removed or at least made configurable.

**Comment by greg0ire** [comment]
Could a solution be to check access on the current object if there is one? This should trigger the voter you are talking about, shouldn't it?

**Comment by warslett** [comment]
@greg0ire yes that would solve my problem. But in general I think this is a crude way of checking permissions because it is making a presumption that a user only has permission to retrieve auto complete items if they have either permission to create or edit (see point 2). Personally I think it should be removed altogether and permissions for this action should be determined only by the configurable target_admin_access_action option (which checks list access by default) see https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Action/RetrieveAutocompleteItemsAction.php#L95 This gives us all the security we need and is entirely configurable.

**Comment by greg0ire** [comment]
Indeed, it's like that since #4448 … @pulzarraider , maybe you can help with this?
