### ISSUE TITLE
Bug on multiple level modal inheritance model

### ISSUE THREAD

**Issue by apsylone** [sonata-project/SonataAdminBundle#5283]
#### Sonata packages

```
sonata-project/admin-bundle              3.40.2 3.40.2 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.12.1 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.11.2 3.11.2 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.0  1.1.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.3  3.6.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.9.1  1.9.1  Lightweight Exporter library
sonata-project/media-bundle              3.16.2 3.16.2 Symfony SonataMediaBundle
sonata-project/user-bundle               4.2.3  4.2.3  Symfony SonataUserBundle
```

#### Symfony packages

```
symfony/maker-bundle       v1.8.0  v1.8.0  Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/monolog-bundle     v3.3.0  v3.3.0  Symfony MonologBundle
symfony/phpunit-bridge     v3.4.17 v4.1.6  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.9.0  v1.10.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.9.0  v1.10.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu  v1.9.0  v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.9.0  v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.9.0  v1.10.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.9.0  v1.10.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.9.0  v1.10.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.7  v3.2.4  Symfony SwiftmailerBundle
symfony/symfony            v3.4.17 v4.1.6  The Symfony PHP framework
```

#### PHP version

```
PHP 7.1.19 (cli) (built: Aug 17 2018 18:03:17) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

## Subject

When using multiple inheritance like : 
Quizz - has - Questions - has - Answers

And creating each entities through modal windows, the second level modal windows (adding answers) gives us some problems.  It seems like the JS getting the modal don't refresh correctly the dom ID. Because we have two times the same ID.

## Steps to reproduce

1.  Create a Quizz  and 
![capture d ecran 2018-11-02 a 17 49 22](https://user-images.githubusercontent.com/2072877/47928861-b5843a00-dec7-11e8-9c85-3447ba75a4e7.png)

2. Create a Question 
![capture d ecran 2018-11-02 a 17 49 35](https://user-images.githubusercontent.com/2072877/47928870-bcab4800-dec7-11e8-8ca1-c51af9be0f6d.png)

3. Create a Answer and validate form
![capture d ecran 2018-11-02 a 17 49 40](https://user-images.githubusercontent.com/2072877/47928899-ce8ceb00-dec7-11e8-8926-2daeef279186.png)

4. Validate Question Form
5. Add a new Question
6. Try to add a new Answer

The modal don't show up !

## Expected results

Modal for adding answers should show once again.

## Solution to the problem

Each modal after creation (and form submit) should be destroyed in the dom. We've added a little patch in our "head" html section for doing it : 

```
jQuery(function() {
                jQuery(document).on('hidden.bs.modal', '.modal', function () {
                    console.log("hidden.bs.modal");
                    jQuery(this).remove();
                });
            });
```

**Comment by kunicmarko20** [comment]
Would you be able to provide a PR?

**Comment by kwinne** [comment]
The same issue exists with embedded list modal (ModelListType). 
The first time you open the modal the filters will show (when you click to toggle) but when you reopen the list modal, filters will not respond anymore (clicking has no effect) (due to the same dom ID existing twice problem). 

This problem is also fixed by using the solution of this issue.

**Comment by apsylone** [comment]
@kunicmarko20 : our patch is not the most optimized I think. We just listen to the "hidden modal" event from bootstrap to destroy the modal in the DOM. I think it should be right after the method which closes it. But I dont know less Sonata code to do it. But I would love to investigate if someone could help me a little bit.

**Comment by kwinne** [comment]
The problem with the solution of @apsylone is that every modal gets removed when closing, so when you have selfmade modals (in DOM) they will also get removed when closing. This solution only delete's modals of Sonata because it attaches a listener on creating.

When you add a modified version of the event listener of @apsylone in the setup_list_modal function (Admin.js), only the sonata modals will get removed from the DOM. Not a 100% sure if this counts for ALL modals but it seems to work fine in my project.
`
modal.on('hidden.bs.modal', function () {
        jQuery(this).remove();
    });
`

But as @apsylone said, this works with the event listener of bootstrap, there might be a better approach.
