### ISSUE TITLE
Sonata type model - hide/delete the "create" button

### ISSUE THREAD

**Issue by IgorN** [sonata-project/SonataAdminBundle#530]
Hello!
http://clip2net.com/s/1xx2h
How, I can hide or delete the "create" button?

**Comment by Adwitiya012** [comment]
Thanks!!!!
It Works..

**Comment by Mentos93** [comment]
How can I remove a route depending on the user who's logged in. I want to remove the create route from my userAdmin so that people can't add users. Only the super admin should be able to add users.

If tried this;

```
protected function configureRoutes(RouteCollection $collection)
    {
        $securityContext = $this->getConfigurationPool()->getContainer()->get('security.authorization_checker');

        if (!$securityContext->isGranted('ROLE_SUPER_ADMIN')) {
            $collection->remove('create');
            $collection->remove('edit');
        }
    }
```

But I get an error;

> The token storage contains no authentication token. One possible reason may be that there is no firewall configured for this URL.

I can't think that there is no firewall configured.

Because this works to hide specific fields from my forms for only super admins.

**Comment by caponica** [comment]
@Mentos93 - I think you're coming from the wrong angle. You don't remove the route for different users, just set the user permissions sensibly. E.g. if your general users do not have "CREATE" permissions on this object then they will not see any links to add/create and if they guess the URL they will be bounced.

See: https://sonata-project.org/bundles/admin/3-x/doc/reference/security.html

**Comment by Mentos93** [comment]
@caponica I am completely aware of that, but I don't use the SonataUserBundle. I only use FOSUserBundle directly with SonataAdminBundle with Symfony 3. So I don't know another way.

**Comment by caponica** [comment]
@Mentos93 - however your users are being authenticated, they will have some kind of permissions. If they have ROLE_SONATA_ADMIN_YOURADMIN_CREATE then they will see the add/create links and be able to access the route. If they do not have this persmission then they will not.

However, I suggest you open a ticket on stackoverflow and post a link to it here. The git tickets are not really the place for individual questions like this.

**Comment by Mentos93** [comment]
@caponica OK, will do, thanks.

**Comment by bhaktaraz** [comment]
@ghost I'm facing same issue as you mentioned. Have you solved it?
