### ISSUE TITLE
Sorting in collection type is not working

### ISSUE THREAD

**Issue by emr** [sonata-project/SonataAdminBundle#5303]
#### Packages
```
symfony/framework-bundle                 v4.1.7
sonata-project/admin-bundle              3.40.3
sonata-project/core-bundle               3.11.2
```

## Subject

I try to make a sortable collection type with example in following list, but drag and drop sorting is not working. Sortable field "position" comes as a text input.

https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/form_types.html#sonata-corebundle-form-type-collectiontype

```php
$formMapper
    // ...
    ->add(
        'discounts',
        \Sonata\CoreBundle\Form\Type\CollectionType::class,
        [
            'btn_catalogue' => 'messages',
            'btn_add' => 'Add Discount',
        ],
        [
            'edit' => 'inline',
            'inline' => 'table',
            'sortable' => 'position',
        ]
    )
    // ...
```

Screenshot:
<img width="1194" alt="screen shot 2018-11-19 at 16 22 27" src="https://user-images.githubusercontent.com/7689512/48709758-78ce7780-ec17-11e8-9c15-e183b906ffc7.png">

**Comment by emr** [comment]
All javascript files are seems loaded. No any 404 error in browser console.

Here is the loaded javascript files:
![screen shot 2018-11-19 at 16 27 07](https://user-images.githubusercontent.com/7689512/48710010-36f20100-ec18-11e8-81ca-eab24c5e2729.png)

**Comment by emr** [comment]
Is there an idea?

**Comment by byhaskell** [comment]
Hello. Is there a method to fix this?
