### ISSUE TITLE
Page number filter does not get reset when filters are updated

### ISSUE THREAD

**Issue by haggertypat** [sonata-project/SonataAdminBundle#536]
When filters on the list page are updated, the `filter[_page]=` param is not reset to 1.

This is a problem if you are on any page other than page 1 and change your filters so that your new results are only 1 page.

To re-create:
1. Visit page 2 of any admin list
2. Enter filters that will result in only one page of results
3. no results found!
4. remove "filter[_page]=2" from the url to see your first page of results

OR 

visit this example from the sonata-project demo site:
http://demo.sonata-project.org/admin/sonata/news/comment/list?filter[name][type]=&filter[name][value]=Junius&filter[email][type]=&filter[email][value]=&filter[message][type]=&filter[message][value]=&filter[_sort_by]=id&filter[_sort_order]=ASC&filter[_page]=2

**Comment by RenatoAlmeidaPTC** [comment]
I know it's a long time from now, but again with the filters problem/bug.

Everytime I have a custom filter that is added through "getFilterParameters" method i got a little problem, this is, everytime this same page has a pagination included and I reset the filters, whenever I change the page it will add the default filter again, making it useless the reset button. How can I make a workaround this little problem?
