### ISSUE TITLE
getUniqid implementation change since version 3.38.0 create same ids on composer page.

### ISSUE THREAD

**Issue by vlaurier** [sonata-project/SonataAdminBundle#5398]
#### Sonata packages

sonata-project/admin-bundle              3.40.3 3.43.0 The missing Symfony Admin Generator
sonata-project/article-bundle            1.0.0  1.1.0  Advanced article management
sonata-project/block-bundle              3.12.1 3.13.0 Symfony SonataBlockBundle
sonata-project/cache                     1.1.1  2.0.1  Cache library
sonata-project/cache-bundle              2.4.2  3.0.1  This bundle provides caching services
sonata-project/classification-bundle     3.7.1  3.7.1  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.11.2 3.13.7 Symfony SonataCoreBundle
sonata-project/dashboard-bundle          0.3.0  0.3.0  Provides a Dashboard management through container and block services
sonata-project/datagrid-bundle           2.4.0  2.4.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.0  1.1.3  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.6.3  3.7.0  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.9.1  2.0.0  Lightweight Exporter library
sonata-project/formatter-bundle          3.5.0  4.1.2  Symfony SonataFormatterBundle
sonata-project/intl-bundle               2.5.0  2.5.0  Symfony SonataIntlBundle
sonata-project/media-bundle              3.16.3 3.16.3 Symfony SonataMediaBundle
sonata-project/notification-bundle       3.5.1  3.5.1  Symfony SonataNotificationBundle
sonata-project/page-bundle               3.9.1  3.9.1  This bundle provides a Site and Page management through container and block services
sonata-project/seo-bundle                2.6.2  2.6.2  Symfony SonataSeoBundle
sonata-project/user-bundle               4.2.3  4.2.3  Symfony SonataUserBundle

#### Symfony packages

$ composer show --latest 'symfony/*'
symfony/monolog-bundle     v3.3.1  v3.3.1  Symfony MonologBundle
symfony/phpunit-bridge     v4.1.7  v4.2.1  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.10.0 v1.10.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.10.0 v1.10.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-icu  v1.10.0 v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.10.0 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.10.0 v1.10.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.10.0 v1.10.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v3.2.4  v3.2.4  Symfony SwiftmailerBundle
symfony/symfony            v3.4.20 v4.2.1  The Symfony PHP framework

#### PHP version

$ php -v
PHP 7.2.6 (cli) (built: May 25 2018 21:37:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.6, Copyright (c) 1999-2018, by Zend Technologies

## Subject

In the AbstractAdmin class of the SonataAdminBundle, the implementation for the method getUniqid() has been changed since version 3.38.0. When using SonataPageBundle along with sonata admin, the "compose" webpage displays some different blocks for your page.
By clicking to configure a block, an ajax call is made to display a form, and to set the settings of your block. 
As you can open several blocks to configure them (and then make several ajax calls) you can end up with the same id repeated at different places on the webpage.
In my case, it creates troubles when having several blocks whose form contains ChoiceFieldMaskType element.

## Steps to reproduce

Having a sonata admin working project using Sonata Page.
Having a block whose form containing ChoiceFieldMaskType element.

Then create two blocks of the same type.
Open the first.  Then open the second.
The switch system of the choiceFieldMask element doesn't work anymore for the second block.

To test, replace the getUniqid() implementation of the AbstractAdmin to how it was in version 3.37.0.
It should work.

    public function getUniqid()
    {
        if (!$this->uniqid) {
            $this->uniqid = 's'.uniqid();
        }

        return $this->uniqid;
    }

## Expected results

Not having the same ids at different location of the page.

## Actual results

Some form elements of different blocks have the same id.

**Comment by kavalanche** [comment]
Any news on this issue?

**Comment by core23** [comment]
No, but you can try to fix this @kavalanche

**Comment by greg0ire** [comment]
> In the AbstractAdmin class of the SonataAdminBundle, the implementation for the method getUniqid() has been changed since version 3.38.0

Finding the author of the change and discussing the issue with them would be the next thing to do.

**Comment by Leobaillard** [comment]
I can confirm this problem as well. This is very problematic when using the Sonata as a CMS as it renders the composer page useless.

**Comment by EmmanuelVella** [comment]
Hello, I'm sorry to hear this. I'm currently very busy, but I will try to have a look if I find some time.

**Comment by bmaziere** [comment]
@EmmanuelVella, could you tell us at least what was the purpose about #5176? As @vlaurier said, it breaks the compose feature when you have 2 blocks of same type (ChoiceFieldMaskType but also EntityType, actually every types where uniq id is used).

**Comment by EmmanuelVella** [comment]
@bmaziere Hi, I was trying to add form data persistence on page change, but I finally didn't add it. I don't know if reverting this change would break something now !

**Comment by bmaziere** [comment]
@EmmanuelVella think it would break some feature for people who would have implement some javascript based on those id and then on baseCodeRoute. However, something bigger to me is already broken so IMO it should be reverted
