### ISSUE TITLE
[RFC] Use Webpack for asset management

### ISSUE THREAD

**Issue by silasjoisten** [sonata-project/SonataAdminBundle#5454]
## Feature Request

I would like to provide a PR which implement the usage [webpack encore](https://symfony.com/doc/current/frontend.html)

- [x] Setup webpack encore
- [x] install vendors via yarn (remove from `Resources/public/vendor`)
- [x] use custom stylesheets, javascript files also via webpack
- [x] remove bower

#### Vendors
- AdminLTE2
- famfamfam  (still needed?)
- jQuery
- jQuery form
- jQuery scrollTo
- jQuery UI
- mansonry
- readmoreJS
- slimScroll
- waypoints
- xEditable
- iCheck
- Bootstrap (corebundle)
- fontawesome (corebundle)
- ionicons (corebundle)
- datetimepicker (corebundle)
- select2 (corebundle)
- momentjs (corebundle)

#### Custom 
- colors.css
- layout.css
- styles.css
- tree.css
- jquery.confirmExit.js
- Admin.js
- sidebar.js
- treeview.js

### Benefits
- only one css, javascript file
- easier adding styles, javascripts
- usage of sass or less
- easy update of dependencies for example jQuery

### Questions
- which branch i should use master, 4.x, 3.x?

What would you say?

**Comment by kunicmarko20** [comment]
@core23 had a similar idea if I am not mistaken https://github.com/sonata-project/SonataAdminBundle/pull/5299

**Comment by core23** [comment]
If you have an idea how to do it. Feel free 👍

**Comment by silasjoisten** [comment]
Yea i would have an idea. Shall i open an PR? and from which branch? master or 3.x or 4.x?

**Comment by core23** [comment]
Because it will be a BC break => `master`

**Comment by VincentLanglet** [comment]
Closing in favor of https://github.com/sonata-project/SonataAdminBundle/issues/7049
