### ISSUE TITLE
Custom redirect after CreateAction, EditAction, DeleteAction, BatchAction, etc.

### ISSUE THREAD

**Issue by Baltazar5000** [sonata-project/SonataAdminBundle#5471]
## Feature Request

Hello.

Can you add a custom redirect Feature after Create/Edit and other actions? It's easy and useful. You can use Events or admin class. 

What do you think?

**Comment by OskarStark** [comment]
Sounds like a cool idea to solve this with events 🧐

**Comment by VincentLanglet** [comment]
Can you explain the feature ?

In our team we're overriding the `redirectTo` function when we want a special redirect after the `create` or `edit` action.

**Comment by maMykola** [comment]
I want to have a redirect to a show page after editing an object, but leave all other behaviour untouched. But now I need to replicate all the logic of `redirectTo` method and change only one line. This can be a BC during upgrading sonata from 3.x to 4.x as the definition of this method is different.
<img width="938" alt="image" src="https://user-images.githubusercontent.com/3263273/227500072-06747771-ae04-436c-b180-b19eaebee419.png">
<img width="1024" alt="image" src="https://user-images.githubusercontent.com/3263273/227500135-f760d825-4265-45ab-b619-c60c8f0d08f2.png">
It's not possible to change this behaviour with configuration, only overwrite the method in ugly way.

P.S. The easiest way to change this is to create a property with this list `['edit', 'show']` which can be changed in custom CRUD controller
