### ISSUE TITLE
Filter and field_options "required"

### ISSUE THREAD

**Issue by dsoriano** [sonata-project/SonataAdminBundle#5478]
## Feature Request

Hello,
I have a case where I need to implement a listing with a required filter, but the field_options "required" is disabled :

```
        protected function configureDatagridFilters(DatagridMapper $datagridMapper)
	{
		$datagridMapper
			->add('name')
			->add('brand', null, [
				'show_filter' => true,
			], null, [
				'choice_label' => 'name',
				'required' => true,
			])
		;
	}
```

Actually the "required" option is overrided in Sonata\AdminBundle\Filter\Filter :

```
    public function getFieldOptions()
    {
        return $this->getOption('field_options', ['required' => false]);
    }
```
Is it possible to remove this limitation ?

Thank you

**Comment by phansys** [comment]
AFAIK, this limitation is not in this bundle; but in the `DatagridBuilderInterface::addFilter()` implementations, which call `FieldDescriptionInterface::mergeOption('field_options', ['required' => false])`. By instance: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.9.0/src/Builder/DatagridBuilder.php#L157

@sonata-project/contributors, do you know why is the "required" option forced to `false` here?
https://github.com/sonata-project/SonataAdminBundle/blob/64b83e290566dc609a7a30d6a419c1359430dfc9/src/Admin/BaseFieldDescription.php#L329-L340
