### ISSUE TITLE
Bad display select2 in 'entity type'

### ISSUE THREAD

**Issue by axzx** [sonata-project/SonataAdminBundle#5488]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.46.0 3.46.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.15.0 3.15.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.16.1 3.16.1 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  2.5.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.1.5  1.1.5  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.8.3  3.8.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter library

```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/4.2.4
```

#### PHP version

```
$ php -v
PHP 7.2.15-0ubuntu0.18.10.1 (cli) (built: Feb  8 2019 14:54:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.15-0ubuntu0.18.10.1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

```

## Subject
In the filters and the forms I noticed that in the field's type 'entity type' area is too tight.
I think that it may be connected with select2 configuration.

In ModelAutocompleteType is OK.
In the 3.45.2 version this area was OK (wide).

## Steps to reproduce
Open filters, select field with select2 (entitytype).

## Expected results
wide select2 field

## Actual results

![obraz](https://user-images.githubusercontent.com/1436016/53983852-64f04800-4118-11e9-8ae1-94292a621cd6.png)

**Comment by todwardus** [comment]
Same:  Bad select2 <select> dropdown fields.
3.45.2 -> Works.
3.46.0 -> Ugly as f.

3.45.2
![good](https://user-images.githubusercontent.com/25172311/54024424-0b2f6280-4198-11e9-8014-c35aeeb37672.jpg)
![good2](https://user-images.githubusercontent.com/25172311/54024425-0bc7f900-4198-11e9-8e94-18758bcecc05.jpg)

3.46.0
![bad](https://user-images.githubusercontent.com/25172311/54024422-0b2f6280-4198-11e9-8ecc-f125bc13d4af.jpg)
![bad2](https://user-images.githubusercontent.com/25172311/54024423-0b2f6280-4198-11e9-82c1-a6cb49e7d806.jpg)

**Comment by kunicmarko20** [comment]
cc @silasjoisten could you take a look? or can someone do git bisect

**Comment by silasjoisten** [comment]
Yea i will take a look

**Comment by SirKnightDragoon** [comment]
Same bug here with 3.46.0 ;)

**Comment by silasjoisten** [comment]
I figured out why => select2 got initialized 2 times. The first time was from AdminBundle then the CoreBundle override it.
