### ISSUE TITLE
jQuery issue on sonata list page

### ISSUE THREAD

**Issue by vikashdragongo** [sonata-project/SonataAdminBundle#5493]
Hello,

I am using `"sonata-project/admin-bundle": "^3.38"`

I am having a issue when I try to update inline field (e.g: `title`) from list page then it removes the field box (`td`) and the design of the row looks untidy.

It was working fine when I was using it in `"sonata-project/admin-bundle": "~2.4"`

This issue is rising on all `editable` fields in Sonata CMS.

Please check more on screenshots:

before edit :
![before inline edit](https://user-images.githubusercontent.com/20084848/54129236-d2abb500-4433-11e9-98b0-5789910db6ec.png)

after edit : 
![before inline edit](https://user-images.githubusercontent.com/20084848/54129164-a98b2480-4433-11e9-956b-553b8faeafc1.png)

**Comment by phansys** [comment]
@vikashdragongo, are you yet experiencing the issue? Could you please confirm if there is some issue with the javascript behavior (checking the developer's console in your browser) when the action takes place? Regardless the visual problem, is the change persisted?

If you can, please update the report using the issue template.

Thank you in advance.
