### ISSUE TITLE
Use events instead of class methods

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#5494]
## Feature Request

Today we have many extensions points in our classes, e.g. `CRUDController::preEdit` or `AbstractAdmin::preValidate`. This is really bad. My idea is to replace all this classes with well defined events (e.g `Event\PreValidateObject` or `PreEditObject`), so it is easier to add custom code without using class inheritance to the max.

cc @sonata-project/contributors

**Comment by kunicmarko20** [comment]
https://github.com/sonata-project/SonataAdminBundle/pull/5199 something similar to this?

**Comment by VincentLanglet** [comment]
@core23 There are checks like
```
$preResponse = $this->preEdit($request, $existingObject);
if (null !== $preResponse) {
    return $preResponse;
}
```

If you want to return a custom response in some situation instead of the classic edit logic, what would be the solution with events ?

**Comment by core23** [comment]
Back in 2019, I thought it would be a better idea to remove the whole `AbstractAdmin` class and replace everything with events, because we have two components where you can define admin logic: `CrudController` and `AbstractAdmin`.

Doing this will require a huge refactoring which requires a lot of time. When looking at the current core maintainer situation, we should close this issue.
