### ISSUE TITLE
An exception has been thrown during the rendering of a template ("The Request object has not been set").

### ISSUE THREAD

**Issue by GCalmels** [sonata-project/SonataAdminBundle#5500]
#### Sonata packages
```
sonata-project/admin-bundle              3.47.0 3.47.0 The missing Symfony A...
sonata-project/block-bundle              3.15.0 3.15.0 Symfony SonataBlockBu...
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.16.2 3.16.2 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  3.0.0  Symfony SonataDatagri...
sonata-project/doctrine-extensions       1.2.0  1.2.0  Doctrine2 behavioral ...
sonata-project/doctrine-orm-admin-bundle 3.8.3  3.8.3  Symfony Sonata / Inte...
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter ...
sonata-project/intl-bundle               2.5.0  2.5.0  Symfony SonataIntlBundle
```

#### PHP version

```
7.2.14
```
Since the version 3.46.0, I have the error : `An exception has been thrown during the rendering of a template ("The Request object has not been set").` but this error came from `vendor/sonata-project/admin-bundle/src/Resources/views/Core/dashboard.html.twig (line 60)`

This is not related to old bugs with search...

After some tests, I found this addition : `!$this->getRequest()->isXmlHttpRequest()` in `AbstractAdmin l.2917`.
Without this code : no error

**Comment by kunicmarko20** [comment]
it should have called `hasRequest` before `get`
