### ISSUE TITLE
Tab menu url issue

### ISSUE THREAD

**Issue by quisse** [sonata-project/SonataAdminBundle#5505]
### Environment
macOS 10.14.1

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.47.1 3.47.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.15.0 3.15.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.16.2 3.16.2 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  2.5.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.2.0  1.2.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.8.3  3.8.3  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  1.11.0 1.11.0 Lightweight Exporter library
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/asset                v4.2.4  v4.2.4  Symfony Asset Component
symfony/cache                v4.2.4  v4.2.4  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config               v4.2.4  v4.2.4  Symfony Config Component
symfony/console              v4.2.4  v4.2.4  Symfony Console Component
symfony/contracts            v1.0.2  v1.0.2  A set of abstractions extracted out of the Symfony components
symfony/debug                v4.2.4  v4.2.4  Symfony Debug Component
symfony/dependency-injection v4.2.4  v4.2.4  Symfony DependencyInjection Component
symfony/doctrine-bridge      v4.2.4  v4.2.4  Symfony Doctrine Bridge
symfony/dotenv               v4.2.4  v4.2.4  Registers environment variables from a .env file
symfony/event-dispatcher     v4.2.4  v4.2.4  Symfony EventDispatcher Component
symfony/expression-language  v4.2.4  v4.2.4  Symfony ExpressionLanguage Component
symfony/filesystem           v4.2.4  v4.2.4  Symfony Filesystem Component
symfony/finder               v4.2.4  v4.2.4  Symfony Finder Component
symfony/flex                 v1.2.0  v1.2.0  Composer plugin for Symfony
symfony/form                 v4.2.4  v4.2.4  Symfony Form Component
symfony/framework-bundle     v4.2.4  v4.2.4  Symfony FrameworkBundle
symfony/http-foundation      v4.2.4  v4.2.4  Symfony HttpFoundation Component
symfony/http-kernel          v4.2.4  v4.2.4  Symfony HttpKernel Component
symfony/inflector            v4.2.4  v4.2.4  Symfony Inflector Component
symfony/intl                 v4.2.4  v4.2.4  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle         v1.11.5 v1.11.5 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/options-resolver     v4.2.4  v4.2.4  Symfony OptionsResolver Component
symfony/polyfill-intl-icu    v1.10.0 v1.10.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring    v1.10.0 v1.10.0 Symfony polyfill for the Mbstring extension
symfony/property-access      v4.2.4  v4.2.4  Symfony PropertyAccess Component
symfony/routing              v4.2.4  v4.2.4  Symfony Routing Component
symfony/security-acl         v3.0.1  v3.0.1  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle      v4.2.4  v4.2.4  Symfony SecurityBundle
symfony/security-core        v4.2.4  v4.2.4  Symfony Security Component - Core Library
symfony/security-csrf        v4.2.4  v4.2.4  Symfony Security Component - CSRF Library
symfony/security-guard       v4.2.4  v4.2.4  Symfony Security Component - Guard
symfony/security-http        v4.2.4  v4.2.4  Symfony Security Component - HTTP Integration
symfony/templating           v4.2.4  v4.2.4  Symfony Templating Component
symfony/translation          v4.2.4  v4.2.4  Symfony Translation Component
symfony/twig-bridge          v4.2.4  v4.2.4  Symfony Twig Bridge
symfony/twig-bundle          v4.2.4  v4.2.4  Symfony TwigBundle
symfony/validator            v4.2.4  v4.2.4  Symfony Validator Component
symfony/var-exporter         v4.2.4  v4.2.4  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/yaml                 v4.2.4  v4.2.4  Symfony Yaml Component
```

#### PHP version

```
$ php -v
PHP 7.1.25 (cli) (built: Dec  7 2018 08:20:45) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.25, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethan
```

## Subject

When combining an admin in a tabmenu and using that same admin in a `ModelListType` field of the form of a child admin, the url in the tabmenu turns to /admin/sonata/customer/address/list?id=3 instead of /admin/sonata/customer/customer/3/address/list.
Created a reproducer on https://github.com/storefront-bvba/tabmenu-bug

## Steps to reproduce

1. Clone https://github.com/storefront-bvba/tabmenu-bug
2. Install and configure the project.
1. Create a Customer.
4. Make sure you're on the customer edit page
3. Click on `customer.sidemenu.link_address_list`

## Expected results
Navigate to /admin/sonata/customer/customer/3/address/list
## Actual results
Navigate to /admin/sonata/customer/address/list?id=3

**Comment by franmomu** [comment]
Taking a look at your code, it looks like [here](https://github.com/storefront-bvba/tabmenu-bug/blob/master/src/Admin/BasketAdmin.php#L38) should be `admin.customer`.

**Comment by quisse** [comment]
@franmomu YES! That solved it! 😄
A bit weird, guess I do not completely get [following](https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/form_types.html#fielddescription-options) right?

> 13.1.9. FieldDescription options
The fourth parameter to FormMapper::add() allows you to pass in FieldDescription options as an array. The most useful of these is **admin_code**, which allows you to specify which admin to use for managing this relationship. It is most useful for inline editing in conjunction with the Sonata\AdminBundle\Form\Type\AdminType form type.
The value used should be the admin service name, not the class name. If you do not specify an admin_code in this way, the default admin class for the field's model type will be used.

The admin_code should be the code of the most parent admin instead of the admin which is used to edit the linked entity?

**Comment by franmomu** [comment]
You're welcome! The `admin_code` should be the one managing that property, so if the property is a customer, you need the customer admin service. By the way, I guess it would also work without specifying the `admin_code`, I've only have used it when I have some Admin services for the same Entity, so you have to specify which one to use.

**Comment by quisse** [comment]
Oh okay, clear! Thanks!

**Comment by quisse** [comment]
Sorry, the issue isn't solved. My example wasn't 100% correct. Updated my question.

**Comment by quisse** [comment]
More explicit setting the route fixes the issue:

Not working:
```
$menu->addChild(
            'customer.sidemenu.link_address_list',
            $admin->generateMenuUrl('admin.address.list', ['id' => $id])
        );
```

Working:
```
$menu->addChild(
            'customer.sidemenu.link_address_list',
            $admin->generateMenuUrl('admin.customer|admin.address.list', ['id' => $id])
        );
```

**Comment by franmomu** [comment]
mmm I've tried and just changing the `admin_code` to `admin.customer` in `BasketAdmin` has worked for me. I'll take a look later if I can.

**Comment by quisse** [comment]
The basket admin was a bad example, removed it. Try the customer admin. I've included my solution in the reproducer.

**Comment by quisse** [comment]
I think the issue still exists but the workaround noted previously solved my problem. Due to change of priorities I won't be able to dig in this more thoroughly. Thanks @franmomu for your time & help!

**Comment by kirya-dev** [comment]
How let changeable parameter(ex counter) into translate lable?
Its a problem, Because profiler shows missing tranlsate if im pass allready translated label

**Comment by VincentLanglet** [comment]
> How let changeable parameter(ex counter) into translate lable?
> Its a problem, Because profiler shows missing tranlsate if im pass allready translated label

I don't fully understand your issue, and how it's related to the original issue.
I would recommend to open a new one, since this one is very old.
