### ISSUE TITLE
user block is not displayed on the top right

### ISSUE THREAD

**Issue by SlimenTN** [sonata-project/SonataAdminBundle#5521]
I followed the configuration described here https://sonata-project.org/bundles/admin/3-x/doc/reference/templates.html but still not displaying the user_block.
**config.yml**:
```
sonata_admin:
    templates:
        user_block: ApplicationSonataUserBundle:Default:user_block.html.twig
```
versions I'm using:
```
"require": {
        "php": ">=5.5.9",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "incenteev/composer-parameter-handler": "^2.0",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^5.0.0",
        "sonata-project/admin-bundle": "^3.43",
        "sonata-project/doctrine-orm-admin-bundle": "^3.7",
        "sonata-project/user-bundle": "4.0.0",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.6.4",
        "symfony/symfony": "3.4.*",
        "twig/twig": "^1.0||^2.0"
    },
```
this is where I have placed my **user_block.html.twig** file:

![image](https://user-images.githubusercontent.com/17424180/55719856-34414e00-59f7-11e9-85e5-9cf25c5751b5.png)

I get no error however the user icon on the top right is not displayed !

![image](https://user-images.githubusercontent.com/17424180/55719968-82eee800-59f7-11e9-80f7-1471beb8799c.png)

**Comment by franmomu** [comment]
The `user_block` is displayed [here](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/standard_layout.html.twig#L211) and some lines up, there is this condition:
`{% if app.user and is_granted(sonata_admin.adminPool.getOption('role_admin')) %}`
 could it be possible that you are not logged in or don't have that role?

**Comment by SlimenTN** [comment]
@franmomu I'm connected with role `ROLE_SUPER_ADMIN ` does this make a difference ?

**Comment by SlimenTN** [comment]
@franmomu ok thanks to your hint I found that I need to add this to the configuration:
```
sonata_admin:
    security:
        role_admin: ROLE_USER #since all users has this role they will be able to see the user block
```
we just need to tell sonata which role presents to `role_admin `
now this condition will return true:
`{% if app.user and is_granted(sonata_admin.adminPool.getOption('role_admin')) %}`
