### ISSUE TITLE
Change 'catalogue' key to 'translation_domain' for the choice list field type

### ISSUE THREAD

**Issue by quisse** [sonata-project/SonataAdminBundle#5525]
## Feature Request

When adding a `choice` field to a list, the translation domain has to be configured via `catalogue` key. Not sure why this is, but for a form field the domain is configured via `translation_domain`.

Can i create a PR to change this to `translation_domain`? (or keep `catalogue` but also add `translation_domain`?)

**Comment by phansys** [comment]
Hi @quisse!
Thank you for pointing this. I think we could deprecate the "catalogue" option, indicating that the accepted option is "translation_domain". Please, be free to propose a PR with this change.

**Comment by quisse** [comment]
Will do a PR some day.

**Comment by VincentLanglet** [comment]
Hi @quisse. Do you still want to do a PR to add the support of `translation_domain` and deprecate the `catalogue` option ?

**Comment by quisse** [comment]
Currently I’m not working on projects with Sonata so it isn’t on top of my priority list. If you feel like doing so, be my guest 🙂

**Comment by VincentLanglet** [comment]
Ok. I'm gonna close this issue in favor of https://github.com/sonata-project/SonataAdminBundle/issues/6116

I'll try to do it when I'll find time.
