### ISSUE TITLE
[RFC] Decouple request from admin filter responsibilities

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataAdminBundle#5547]
## Feature Request

Provide a way to configure admin's filter parameters dynamically without a hard dependency against a `Request`:
https://github.com/sonata-project/SonataAdminBundle/blob/b2d0f4846c8752ee3f3db1a86dff6ae7a847857a/src/Admin/AbstractAdmin.php#L761

I think the request object still provide the default implementation, but IMO this must be decoupled from the filter responsibility.

**Some context**: I found this problem while trying to use an admin inside a block (see #5530), which based on my proposal, should not be tied to the master request since it is just part of an embedded block.

**Comment by kunicmarko20** [comment]
We could have like a `FilterBag` and fill it up if the request is there, and dispatch events that would allow people to add their own filters.

**Comment by phansys** [comment]
In order to start working on this, I'd like to know where this filter bag should be filled with the default values from request. The possible options I can imagine are these:
* a dedicated listener based on `kernel.request` or similar event;
* some admin "hook" method (`getDatagrid()`, `buildDatagrid()`, `getFilterParameters()`, etc);
* a controller method, like `CRUDController::preList()`.

**Comment by phansys** [comment]
I've started #5549 in order to address this task. Please, let me know if the approach is something like you've proposed.
BTW, with these changes I'm still not able to set custom filters with the PR #5530.
Thank you.

**Comment by VincentLanglet** [comment]
Should we keep this @phansys ?

https://github.com/sonata-project/SonataAdminBundle/pull/6162 is enough ?

**Comment by phansys** [comment]
> Should we keep this @phansys ?
> 
> #6162 is enough ?

I don't know, but given the title in that PR, I think the goal of this issue is not yet reached. The proposal here is to be able to set admin filters on demand, regardless their default values. By instance `$admin->setFilters([...])`.

**Comment by VincentLanglet** [comment]
Closing due to lack of interest
