### ISSUE TITLE
Add a way to translate exported value

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#5548]
## Feature Request

When I wanted to translate a column in my admin export, I used
```
public function getDataSourceIterator()
    {
        ...
        return new SourceIterator($query, $fields, [
            'translator' => $this->translator,
        ]);
    }
```
And I created my own SourceIterator to translate the column I wanted.

But I discover here PR: https://github.com/sonata-project/SonataAdminBundle/pull/4124 that the translator will be removed.

Then I need another solution. 

`configureExportField` working the same way than `configureDatagridFilters`, `configureListFields`, ... would be great, instead of `getExportFields`.

**Comment by core23** [comment]
You could define the iterator as a service or create a factory for this.

**Comment by VincentLanglet** [comment]
> You could define the iterator as a service or create a factory for this.

Thanks for your quick answer @core23. Can you elaborate a little bit ?

Do you mean injecting the dataSourceIterator this way https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/advanced_configuration.html#service-configuration, with something like a SetIterator ?

And what do you mean by creating a factory for this ? 

Thanks you.

**Comment by phansys** [comment]
The injection can be done using a [call to a setter](https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/advanced_configuration.html#with-a-method-call-more-verbose) in your admin definition, something like:
```yaml
calls:
    - [setDataSourceIterator, ['@your_service']]
```
The other proposed option is to use a call to a factory method directly in your admin class (using the [factory pattern](https://phptherightway.com/pages/Design-Patterns.html)), `YourDataSourceIterator::create()` or so.
