### ISSUE TITLE
[Docs] User should implement Equatable interface in 23. SonataAdmin without FOSUserBundle/SonataUserBundle

### ISSUE THREAD

**Issue by Clindbergh** [sonata-project/SonataAdminBundle#5550]
When following [SonataAdmin without FOSUserBundle/SonataUserBundle](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/docs/cookbook/recipe_sonata_admin_without_user_bundle.rst), I observed the following behavior:

https://stackoverflow.com/questions/47675301/token-was-deauthenticated-after-trying-to-refresh-it

The User class should implement the Equatable interface in order to have a functional login.

**Comment by VincentLanglet** [comment]
I personally use my own User class which implement UserInterface without implementing EquatableInterface, and it works fine.
