### ISSUE TITLE
[Docs] has_role() is deprecate

### ISSUE THREAD

**Issue by minolone** [sonata-project/SonataAdminBundle#5562]
https://symfony.com/doc/current/bundles/SonataAdminBundle/cookbook/recipe_sonata_admin_without_user_bundle.html#adminloginauthenticator

    public function checkCredentials($credentials, UserInterface $user): bool
    {
        if (!$this->passwordEncoder->isPasswordValid($user, $credentials['password'])) {
            return false;
        }

        if (!$user->hasRole('ROLE_ADMIN')) {
            throw new CustomUserMessageAuthenticationException("You don't have permission to access that page.");
        }
        return true;
    }

**Comment by phansys** [comment]
Hi @minolone. Thank you for your first report!
Could you please elaborate what you are describing using the issue template?
