### ISSUE TITLE
[RFC] Bump "twig/twig" in order to avoid deprecations

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataAdminBundle#5573]
## Feature Request

Bump Twig to version `^2.9` in order to use [`apply spaceless`](https://twig.symfony.com/doc/2.x/filters/spaceless.html) filter instead of the deprecated [`spaceless`](https://twig.symfony.com/doc/2.x/tags/spaceless.html) tag.

https://github.com/sonata-project/SonataAdminBundle/blob/a2524e7a6f03de2f8b8e84203088f6e57b209a30/composer.json#L55

**Comment by greg0ire** [comment]
Will that mean dropping the `^1.34` part, or bumping it too?

**Comment by Hanmac** [comment]
@greg0ire 

The spaceless filter was added in Twig 1.38.
The apply tag was added in Twig 2.9. (we might not want that yet)

so if we would use just the spaceless filter, we could just use it as filer

or we could just add our own apply tag in case the one from twig is not defined?

**Comment by phansys** [comment]
The "problem" with using just the filter without the `apply` tag is that the syntax which are covered by the filter must be basically a string, and we are wrapping complex structures now:
https://github.com/sonata-project/SonataAdminBundle/blob/64b83e290566dc609a7a30d6a419c1359430dfc9/src/Resources/views/CRUD/action_buttons.html.twig#L11-L17

**Comment by greg0ire** [comment]
How about just dropping Twig 1? Twig 2 is one year old now, I think people have had plenty of time to migrate.

**Comment by phansys** [comment]
Yes, that is what I'm proposing. But we need the constraint `^2.9` instead `^2.0` if we want to just replace `{% spaceless %}` with `{% apply spaceless %}`. Otherwise, we need to find an alternative solution for the complex syntaxes (writing our own `apply` bridge tag or restructuring the templates).

**Comment by greg0ire** [comment]
Sounds acceptable to me.

**Comment by OskarStark** [comment]
Let’s drop Twig 1

**Comment by phansys** [comment]
Could we also update the constraint `"^1.34 || ^2.0"` to `"^1.41 || ^2.0"` at `3.x` branch in order to have the `filter` filter available? This is required to fix #5575.

**Comment by greg0ire** [comment]
Oh I thought you were actually targetting 3.x in your PR, didn't check that.

**Comment by phansys** [comment]
I think dropping the support for Twig 1.x is a BC break for users which are using that version by their own requirements, since it will make SonataAdmin not installable for them.

**Comment by greg0ire** [comment]
> it will make SonataAdmin not installable for them.

It will make SonataAdmin not upgradable for them. They will still be able to install older versions.

**Comment by phansys** [comment]
Of course. If that is not a problem, I'll change the target.

**Comment by greg0ire** [comment]
That's something we avoid to do with Symfony or Php, but I think for Twig it might be OK.
