### ISSUE TITLE
Autowire for custom CRUDController

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#5586]
## Feature/Documentation Request

When I extend CRUDController, I can inject services as argument for my customAction, but I cannot (obviously ?) add argument in function defined in the parent class CRUDController.

```php
class MyCRUDController extends CRUDController
{
    // Custom action, I can inject service as argument
    public function myCustomAction(MyService $myService, ...)
    {
        // code here
    }

    // Override CRUDController function, I can't inject service as argument since I have to be compatible with the parent function
    public function redirectTo($object)
    {
        // code here
        // I'd like to inject a customService
    }
}
```

In my dream world, there would be a way to inject services in the function from the parent CRUDController like redirectTo. But it's just a dream.
Since `$this->get()` is deprecated by Symfony. Shouldn't Sonata at least write some words about the best way to inject services in the documentation ? I'm new with autowire, but I think in that case I have to use the `__construct` or a `setService` call with the `@required` annotation.

**Comment by core23** [comment]
This is not possible due PHP restrictions if you override a method

**Comment by VincentLanglet** [comment]
> This is not possible due PHP restrictions if you override a method

@core23 Yes, that's why I said it was a dream. But what is the recommended way according to Symfony/Sonata ? I asked for more Sonata documentation.

**Comment by core23** [comment]
There is no specific Sonata way for dependencies, you should try the symfony way, which is constructor injection.

**Comment by VincentLanglet** [comment]
Ok thanks
