### ISSUE TITLE
sonata export : DoctrineODMQuerySourceIterator is not well included

### ISSUE THREAD

**Issue by sabinecimaponti** [sonata-project/SonataAdminBundle#5612]
### Environment
prod

#### Sonata packages
sonata-project/admin-bundle                  3.49.1 3.51.0 The missing Symfony Admin Generator
sonata-project/block-bundle                  3.15.0 3.15.0 Symfony SonataBlockBundle
sonata-project/cache                         2.0.1  2.0.1  Cache library
sonata-project/core-bundle                   3.17.0 3.17.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle               2.5.0  3.0.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions           1.3.0  1.3.0  Doctrine2 behavioral extensions
sonata-project/doctrine-mongodb-admin-bundle 3.2.0  3.2.0  Symfony Sonata / Integrate Doctrine MongoDB ODM into the SonataAdminBundle
sonata-project/easy-extends-bundle           2.5.0  2.5.0  Symfony SonataEasyExtendsBundle
sonata-project/exporter                      2.0.1  2.0.1  Lightweight Exporter library
sonata-project/formatter-bundle              3.5.0  4.1.3  Symfony SonataFormatterBundle
sonata-project/user-bundle                   4.4.0  4.4.0  Symfony SonataUserBundle

#### Symfony packages
symfony/monolog-bundle     v3.4.0  v3.4.0  Symfony MonologBundle
symfony/phpunit-bridge     v3.1.5  v4.3.2  Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.11.0 v1.11.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.11.0 v1.11.0 Symfony polyfill for ctype functions
symfony/polyfill-iconv     v1.11.0 v1.11.0 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-icu  v1.11.0 v1.11.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn  v1.11.0 v1.11.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring  v1.11.0 v1.11.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.11.0 v1.11.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.11.0 v1.11.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.2  v3.0.2  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v3.2.8  v3.2.8  Symfony SwiftmailerBundle
symfony/symfony            v3.4.28 v4.3.2  The Symfony PHP framework

#### PHP version
PHP 7.3.3-1+0~20190307202445.32+jessie~1.gbp32ebb2

## Subject
sonata export : DoctrineODMQuerySourceIterator is not well included

## Steps to reproduce
Connect to Sonata, view a list, choose to export the list

## Expected results
The export is downloaded

## Actual results
Attempted to load class "DoctrineODMQuerySourceIterator" from namespace "Exporter\Source".
Did you forget a "use" statement for "Sonata\Exporter\Source\DoctrineODMQuerySourceIterator"?

This comes from the used, modifying it with use Sonata \ Exporter \ Source \ DoctrineODMQuerySourceIterator; it works

**Comment by phansys** [comment]
@sabinecimaponti, could you please try to update the dependency and share the stack trace for the exception if it already persists? The class `DoctrineODMQuerySourceIterator` seems to be not used in this bundle, at least in the last stable release.

**Comment by sabinecimaponti** [comment]
Hello,

Thanks for the reply. 
I try to update but that seems not work.

In the file vendor/sonata-project/doctrine-mongodb-admin-bundle/src/Model/ModelManager.php, the exception is thrown on the function getDataSourceIterator. If I change the "`use Exporter\Source\DoctrineODMQuerySourceIterator;`" by "`use Sonata\Exporter\Source\DoctrineODMQuerySourceIterator;`" that works

**Comment by phansys** [comment]
Then, the issue you are reporting doesn't belong to this library, but to [sonata-project/doctrine-mongodb-admin-bundle](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle).
Please, take a look at [this PR](https://github.com/sonata-project/SonataDoctrineMongoDBAdminBundle/pull/313); it seems to fix the problem you're exposing here.

I'm closing this issue based on the explained reasons.
Thank you so much!
