### ISSUE TITLE
How to provide access to particular tabs in Sonata admin

### ISSUE THREAD

**Issue by rahulspnd** [sonata-project/SonataAdminBundle#5647]
Hi ,

I am struggling to give access to particular tab to particular user, Is there a way of adding the permission in Sonata Admin? 
Thanks in advance

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
