### ISSUE TITLE
filter[_per_page] still not working

### ISSUE THREAD

**Issue by farshidalavim** [sonata-project/SonataAdminBundle#5651]
Sonata Admin Bundle Version 3.51.0
Sumfony 3.4

Not working for me still, updated to the most stable version.

I found the issue, it is around determinedPerPageValue and it checks the value against list of available pagination options and also checks against the data type. so I think we need to add the following setting on `vendor/sonata-project/admin-bundle/src/Admin/AbstractAdmin.php` on l`ine 786 before` `if (!$this->determinedPerPageValue($parameters['_per_page'])) {` and it will work.

```
if (isset($parameters['_per_page'])) {
    $parameters['_per_page'] = (int) $parameters['_per_page'];
}
```

Reason being the `$parameters['_per_page']` is string while `determinedPerPageValue` expecting it to be integer. Or, otherwise on `determinedPerPageValue` function code sniff we should remove the data type check setting and only check the values.

**Comment by core23** [comment]
When you found a solution for this bug, can you please provide a PR with this fix @farshidalavim ?

**Comment by farshidalavim** [comment]
> When you found a solution for this bug, can you please provide a PR with this fix @farshidalavim ?

PR created, thanks

**Comment by farshidalavim** [comment]
https://github.com/sonata-project/SonataAdminBundle/pull/5653

**Comment by VincentLanglet** [comment]
> Reason being the `$parameters['_per_page']` is string while `determinedPerPageValue` expecting it to be integer. Or, otherwise on `determinedPerPageValue` function code sniff we should remove the data type check setting and only check the values.


When you look at the defaultDatagridValues, the `per_page` is a int.
```
protected $datagridValues = [
    '_page' => 1,
    '_per_page' => 32,
];
```

How did you manage to get a string ? I think that's the real issue.

**Comment by VincentLanglet** [comment]
Plus, the `_per_page` filter is already casted to int
![image](https://user-images.githubusercontent.com/9052536/77272264-15dc6d00-6cb1-11ea-951d-88f5d4a22045.png)

So it's seems to come from your code @farshidalavim
