### ISSUE TITLE
How to overwrite base_show_field.html.twig ?

### ISSUE THREAD

**Issue by askuiop** [sonata-project/SonataAdminBundle#5655]
How to overwrite base_show_field.html.twig ?   

I do not want to use th, td layout !

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
