### ISSUE TITLE
Multiple Entity Managers crash DatagridFilter

### ISSUE THREAD

**Issue by vlabmichl** [sonata-project/SonataAdminBundle#567]
In my app I use 2 entity managers which work fine even with the SonataAdminBundle.
Only when I try to use a relation as a filter criteria in the "list view" I'm get always the following error:

```
Class Enetz\ModelBundle\Entity\Transformer is not a valid entity or mapped super class.
```

I could isolate this error to the fact that it doesn't occur if I use only 1 entity manager.
Interesting that the AdminBundle resolves the relationship correctly in the new/edit forms.

Probably this issue is related to Ticket 36 in the SonataAdminBundle (https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/36) ?

My Symfony Version is 2.0.10 and the AdminBundle's version is from yesterday (2012-02-21).

**Comment by core23** [comment]
@vlabmichl Please check

**Comment by greg0ire** [comment]
Hi, sorry but as you may already know, Sonata 2 is no longer supported. Please reopen if you still experience this with Sonata 3.
