### ISSUE TITLE
Use generic annotations

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#5670]
## Feature Request

We could add `@template` annotations to our interfaces to provide more specific metadata. 

Here's an example from doctrine: https://github.com/doctrine/collections/blob/master/lib/Doctrine/Common/Collections/Collection.php#L29-L32

The following classes could benefit from this:
- Admin/AdminInterface.php
- Admin/AdminInterface.php
- AdminExtensionInterface.php
...

**Comment by VincentLanglet** [comment]
@core23 It's already done to 
- AccessRegistryInterface
- AdminInterface
- LifecycleHookProviderInterface
- UrlGeneratorInterface

And some other others methods. 
Should we close this or continue with some others Interface ? Could you list them ?
