### ISSUE TITLE
Support entities with constructor arguments

### ISSUE THREAD

**Issue by jaikdean** [sonata-project/SonataAdminBundle#5679]
## Feature Request

It's hard work and a little hacky to work with entities with constructor arguments. We have a number of entities with immutable values which we pass in constructors. In these cases, we override `getNewInstance()` in our admin class as follows:

```php
    public function getNewInstance()
    {
        return null;
    }
```

With some other work like a callback for the form's `empty_data` option, this works.

With the latest release, `getNewInstance()` is correctly documented as returning an `object`, which is causing our static analysis to flag our workaround as a problem.

If there are better recommended way to handle this, or is it on the roadmap to be implemented?

**Comment by core23** [comment]
You can do this with PHP 7.4: https://wiki.php.net/rfc/covariant-returns-and-contravariant-parameters

Or you could add some PHPDoc which will return the correct type.

Or you could help with this issue: https://github.com/sonata-project/SonataAdminBundle/issues/5670

**Comment by jaikdean** [comment]
`AdminInterface::getNewInstance()` is documented as returning an `object`. We can make this more specific in our implementations, but expanding it to `object|null` isn't allowed. That means either I need to implement our admin classes differently (which I'm not sure how to do with entities which require constructors), or the documentation of `AdminInterface::getNewInstance()` is incorrect and should allow `null` to be returned.

I'm happy to help out with generic annotations and suchlike where I can, I'm just not sure what the expected/correct behaviour is here.
