### ISSUE TITLE
Replacing `transchoice` tags with `trans` breaks BC

### ISSUE THREAD

**Issue by ossinkine** [sonata-project/SonataAdminBundle#5686]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.53.0 = 3.53.0 The missing Symfony...
sonata-project/block-bundle              3.17.0 = 3.17.0 Symfony SonataBlock...
sonata-project/cache                     2.0.1  = 2.0.1  Cache library
sonata-project/core-bundle               3.17.0 = 3.17.0 Symfony SonataCoreB...
sonata-project/datagrid-bundle           2.5.0  ~ 3.0.0  Symfony SonataDatag...
sonata-project/doctrine-extensions       1.3.0  = 1.3.0  Doctrine2 behaviora...
sonata-project/doctrine-orm-admin-bundle 3.10.0 = 3.10.0 Symfony Sonata / In...
sonata-project/exporter                  2.0.1  = 2.0.1  Lightweight Exporte...
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/http-client           v4.3.4  = v4.3.4 Symfony HttpClient component
symfony/http-client-contracts v1.1.6  = v1.1.6 Generic abstractions related ...
symfony/mime                  v4.3.4  = v4.3.4 A library to manipulate MIME ...
symfony/monolog-bundle        v3.4.0  = v3.4.0 Symfony MonologBundle
symfony/phpunit-bridge        v4.3.4  = v4.3.4 Symfony PHPUnit Bridge
symfony/security-acl          v3.0.2  = v3.0.2 Symfony Security Component - ...
symfony/swiftmailer-bundle    v3.2.8  = v3.2.8 Symfony SwiftmailerBundle
symfony/symfony               v3.4.31 ~ v4.3.4 The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.3.8 (cli) (built: Aug 20 2019 23:03:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.8, Copyright (c) 1999-2018, by Zend Technologies
```

## Subject

Replacing `transchoice` tags with` trans` in #5669 should be accompanied by changing corresponding translations. Just replacing one tag with another changes the output.

New message format is decribed here https://symfony.com/doc/current/translation/message_format.html

## Steps to reproduce
Open not empty admin list and look at results count.

## Expected results
For example, `@SonataAdmin/Pager/results.html.twig` should return `5 results`...

## Actual results
... but returns `1 result|5 results`.

**Comment by phansys** [comment]
Hi @ossinkine, thank you so much for the report!
I'm not able to reproduce what are you exposing here. Could you please complete the description using the issue template?
BTW, the [documentation](https://symfony.com/doc/current/translation/templates.html#using-twig-tags) also states the following:
>The %var% notation of placeholders is required when translating in Twig templates using the tag.

and the referenced PR is only adding usages for the `{% trans % }` tag.

**Comment by ossinkine** [comment]
@phansys The referenced PR does not adding but replacing usages `transchoice` tags with `trans`.
`transchoice` tag assumes to use special formed translation string which describes pluralization forms.
https://github.com/sonata-project/SonataAdminBundle/blob/60a8c4346148335024ae27e420819a098ce4167e/src/Resources/translations/SonataAdminBundle.en.xliff#L363
So this string `1 result|%count% results` with `transchoice` tag returns `5 results` but with `trans` tag returns `1 result|5 results`.

**Comment by ossinkine** [comment]
I've updated issue description according to template.

**Comment by jvasseur** [comment]
This is a BC break if you are using Symfony < 4.2.

Starting from Symfony 4.2 the translator treat the presence of the `%count%` parameter as being a plural translation making this change work, but if you use an older version of Symfony it leads to the problem @ossinkine is describing.

**Comment by phansys** [comment]
I'll try to check this ASAP. Thank you for the feedback.
