### ISSUE TITLE
List fields editable required value

### ISSUE THREAD

**Issue by peter-gribanov** [sonata-project/SonataAdminBundle#5691]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.52.0 3.53.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.12.1 3.18.0 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.17.0 3.17.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  3.0.0  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.3.0  1.3.0  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.9.0  3.10.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter library
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
symfony/monolog-bundle     v3.4.0  v3.4.0  Symfony MonologBundle
symfony/polyfill-apcu      v1.12.0 v1.12.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-ctype     v1.12.0 v1.12.0 Symfony polyfill for ctype functions
symfony/polyfill-iconv     v1.12.0 v1.12.0 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-icu  v1.12.0 v1.12.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn  v1.12.0 v1.12.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring  v1.12.0 v1.12.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.12.0 v1.12.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.12.0 v1.12.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-php72     v1.12.0 v1.12.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-util      v1.12.0 v1.12.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.2  v3.0.2  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v3.2.8  v3.2.8  Symfony SwiftmailerBundle
symfony/symfony            v3.4.31 v4.3.4  The Symfony PHP framework
```

#### PHP version

```
$ php -v
PHP 7.3.9 (cli) (built: Sep  3 2019 06:20:48) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.9, Copyright (c) 1999-2018, by Zend Technologies
```

## Subject

Need add a [required](https://symfony.com/doc/current/reference/forms/types/choice.html#required) option to oblige to select a value from the list of valid values.
Perhaps a related issue #5693.

## Steps to reproduce

Make entity

```php
class ContestantAdminView
{
    // ...

    public function setPermission(string $permission): void
    {
        $this->permission = $permission;
    }
}
```

Configure field as editable in admin service

```php
class TestimonialAdmin extends BaseAdmin
{
    // ...

    protected function configureListFields(ListMapper $list_mapper): void
    {
        $list_mapper
            ->add('permission', 'choice', [
                'label' => 'Permission',
                'editable' => true,
                'required' => true,
                'choices' => Permission::change(),
                'template' => '@Frontend/Testimonial/admin/list_permission.html.twig',
                'catalogue' => 'messages',
            ])
        ;
    }
```
Go to admin. Change the permission, but do not select a value

![image](https://user-images.githubusercontent.com/1954436/65029637-c7879380-d946-11e9-8fef-0d50767e2918.png)

## Expected results

It is necessary to separate the case when we can use `NULL` as a value, and when not. In my case, `NULL` is not a valid value.

## Actual results

Click submit and get 500 error because `NULL` comes

![image](https://user-images.githubusercontent.com/1954436/65032435-d45ab600-d94b-11e9-8dd7-9aa278a84359.png)

**Comment by peter-gribanov** [comment]
Yes. This issue is still relevant. I still haven’t received any feedback.

**Comment by greg0ire** [comment]
I think using `'choice'` is deprecated. Please use the type name like you would on a regular Symfony. That will help us understand what type you are actually using and debug further (I never remember what `'choice'` translates to in the end)

**Comment by peter-gribanov** [comment]
@greg0ire see your documentation
https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/action_list.html#available-types-and-associated-options

**Comment by peter-gribanov** [comment]
@greg0ire using `Symfony\Component\Form\Extension\Core\Type\ChoiceType` does not affect the result

```php
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class TestimonialAdmin extends BaseAdmin
{
    // ...

    protected function configureListFields(ListMapper $list_mapper): void
    {
        $list_mapper
            ->add('permission', ChoiceType::class, [
                'label' => 'Permission',
                'editable' => true,
                'required' => true,
                'choices' => Permission::change(),
                'template' => '@Frontend/Testimonial/admin/list_permission.html.twig',
                'catalogue' => 'messages',
            ])
        ;
    }
}
```

**Comment by greg0ire** [comment]
:thinking: We should probably update the docs, using the name is deprecated.

> @greg0ire using Symfony\Component\Form\Extension\Core\Type\ChoiceType does not affect the result

But it does affect my understanding… I thought you were using a Sonata type, but this is a native form type. Is the bug that the native HTML5 required attribute is not rendered?

And why do you say

> Need add a required option to oblige to select a value from the list of valid values.

You are using that option in your example

**Comment by franmomu** [comment]
I have taken a look at this and I think we are mixing things. This example is talking about the **list**, as @peter-gribanov said, [the types available are in the docs](https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/action_list.html#available-types-and-associated-options). This has nothing to do with Symfony Type forms, but because this issue is about `editable` is a little bit confusing.

> @greg0ire using `Symfony\Component\Form\Extension\Core\Type\ChoiceType` does not affect the result

I think this won't work because as I said this is about the **list** and `editable` uses [this mapping](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/config/twig.xml#L4).

That being said, the permission you already have in you entity is also one of the `Permission::change()` returns? maybe this is because it is not in that list and it does not select any.

**Comment by peter-gribanov** [comment]
All is well. I understood. The problem is on my side. Sorry.

The problem is that i use ValueObject and when [casting object to a string](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/base_list_field.html.twig#L69), the label is returned, not the value.

Solution for me:

```twig
{# @Frontend/Testimonial/admin/list_permission.html.twig #}
{% extends admin.getTemplate('base_list_field') %}

{% set is_editable =
    field_description.options.editable is defined and
    field_description.options.editable and
    admin.hasAccess('edit', object)
%}
{% set x_editable_type = field_description.type | sonata_xeditable_type %}

{% block field_span_attributes %}
    {%- if is_editable and x_editable_type %}
        class="x-editable"
        data-type="{{ xEditableType }}"
        data-title="{{ field_description.label|trans({}, field_description.translationDomain) }}"
        data-pk="{{ admin.id(object) }}"
        data-url="{{ url }}"
        data-source="{{ field_description | sonata_xeditable_choices | json_encode }}"
        {# correct resolve value for x-editable #}
        data-value="{% if data_value.isAwaiting %}approved{% else %}{{ data_value.value }}{% endif %}"
    {%- endif -%}
{% endblock %}

{% block field -%}
    {%- set bem_modifier %}
        {%- if data_value.isAwaiting -%}
            label-danger
        {%- elseif data_value.isApproved -%}
            label-success
        {%- else -%}
            label-warning
        {%- endif -%}
    {%- endset -%}
    <span class="label {{ bem_modifier }}">{{ value | trans({}, field_description.options.catalogue) }}</span>
{%- endblock %}
```

Sorry again.
