### ISSUE TITLE
Translation issue Symfony 4.2+

### ISSUE THREAD

**Issue by Cedric-Lefebvre** [sonata-project/SonataAdminBundle#5704]
Hi,

I'm getting an issue with the translation on Sonata with the latest Symfony versions (4.2+).
The issue is coming from `\vendor\sonata-project\admin-bundle\src\Resources\views\Block\block_stats.html.twig` where he is calling the `transchoice` at line 23 instead of `trans`, I already see a comment there that it needs to be changed in future versions.

So I was thinking about overriding `vendor/sonata-project/admin-bundle/src/Block/AdminStatsBlockService.php` => `configureSettings`, and use my own template, but I cannot get the configuration right for that.

Or if there is a proper way to do it without having to override it.

Thanks for your help.

**Comment by phansys** [comment]
@Cedric-Lefebvre, could you please explain the issue using the provided [template](https://github.com/sonata-project/SonataAdminBundle/blob/6b8ae974c0ed334b6995b17b0c0ec6b20ca01dcd/.github/ISSUE_TEMPLATE.md)?
BTW, you can check if #5702 is related to what you're reporting.

Thank you!
