### ISSUE TITLE
Custom behavior when creating an admin entity

### ISSUE THREAD

**Issue by Minirock** [sonata-project/SonataAdminBundle#5707]
## Feature Request

I'm not sure if this is already possible or not, but actually I can't find anything in the documentation on how to do that. So I come here to suggest this feature in the future. 
May be I just missed it, in this case tell me.

I think it would be nice to be able to **customize the behavior when we are creating/updating an item**. Let's say you have a calculated field wich is related with one of the user input, you can only make this operation when the object is created. 

So I think we should somehow be able to extends the item creation / update.

Apologies if the is already possible.

**Comment by jeroendk** [comment]
You can use the prePersist & preUpdate functions in de admin class to alter fields before the save action, is this what you need?

**Comment by Minirock** [comment]
> You can use the prePersist & preUpdate functions in de admin class to alter fields before the save action, is this what you need?

Indeed this was exactly what I was looking for, sorry about the wrong issue :( 

Thanks for your fast response.
