### ISSUE TITLE
Allow custom css/js per admin

### ISSUE THREAD

**Issue by oleg-andreyev** [sonata-project/SonataAdminBundle#5708]
## Feature Request

Right now there are two options to add custom css/js:
- override whole configuration `stylesheets`
- add extra with `extra_stylesheets`

I propose to move this a bit further and allow customization from Admin/CRUD/DI.

Idea:
- Create `getStylesheets`/`getJavascript` methods in AdminPool (basically it will a wrapped around `getOption('stylesheets')` and `getOption('javascripts)`
- Create `addStylesheet`/`addJavascript` methods in AdminPool

**Comment by OskarStark** [comment]
@silasjoisten is working on a PR to integrate Webpack

**Comment by OskarStark** [comment]
#5461

**Comment by oleg-andreyev** [comment]
Still relevant but it's better to wait for #5461

**Comment by OskarStark** [comment]
FYI @silasjoisten
