### ISSUE TITLE
symfony 4.3 Custom CollectionType using Transform,  Got "This value is not valid"

### ISSUE THREAD

**Issue by Pasuvan** [sonata-project/SonataAdminBundle#5717]
Hi,
I upgrade symfony 3.4 to  symfony 4.3 , Also I update the sonata-project/adminBundle .
Before Symfony 3.4 Custom ColletionType working fine once i update latest version symfony 4.3 i got issue, Please refer the below link
https://github.com/sonata-project/SonataCoreBundle/issues/696
Please Help me.

**Comment by phansys** [comment]
Thank you for the report @Pasuvan.
Could you please update the description using the [issue template](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/.github/ISSUE_TEMPLATE.md)?

**Comment by Pasuvan** [comment]
> Thank you for the report @Pasuvan.
> Could you please update the description using the [issue template](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/.github/ISSUE_TEMPLATE.md)?

Hi @phansys ,
I already put my question in the issue template. please check my issue in below link.
https://github.com/sonata-project/SonataCoreBundle/issues/696 
I hope this is enough for you.
Thanks
