### ISSUE TITLE
Return value of App\Entity\Category::getName() must be of the type string, null returned

### ISSUE THREAD

**Issue by valentindragan** [sonata-project/SonataAdminBundle#5732]
### Environment
symfony 4.3
on laravel/homestead, apache2

#### Sonata packages
```
        "sonata-project/admin-bundle": "^3.54",
        "sonata-project/doctrine-orm-admin-bundle": "^3.10",

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.54.1 3.54.1 The missing Symfony Admin Generator
sonata-project/block-bundle              3.18.1 3.18.1 Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.17.0 3.17.0 Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.5.0  3.0.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.3.1  1.3.1  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.10.0 3.10.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.0.1  2.0.1  Lightweight Exporter library

#### Symfony packages

symfony/apache-pack                v1.0.1  v1.0.1  A pack for Apache support in Symfony
symfony/asset                      v4.3.5  v4.3.6  Symfony Asset Component
symfony/browser-kit                v4.3.5  v4.3.6  Symfony BrowserKit Component
symfony/cache                      v4.3.5  v4.3.6  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/cache-contracts            v1.1.7  v1.1.7  Generic abstractions related to caching
symfony/config                     v4.3.5  v4.3.6  Symfony Config Component
symfony/console                    v4.3.5  v4.3.6  Symfony Console Component
symfony/css-selector               v4.3.5  v4.3.6  Symfony CssSelector Component
symfony/debug                      v4.3.5  v4.3.6  Symfony Debug Component
symfony/debug-bundle               v4.3.5  v4.3.6  Symfony DebugBundle
symfony/debug-pack                 v1.0.7  v1.0.7  A debug pack for Symfony projects
symfony/dependency-injection       v4.3.5  v4.3.6  Symfony DependencyInjection Component
symfony/doctrine-bridge            v4.3.5  v4.3.6  Symfony Doctrine Bridge
symfony/dom-crawler                v4.3.5  v4.3.6  Symfony DomCrawler Component
symfony/dotenv                     v4.3.5  v4.3.6  Registers environment variables from a .env file
symfony/event-dispatcher           v4.3.5  v4.3.6  Symfony EventDispatcher Component
symfony/event-dispatcher-contracts v1.1.7  v1.1.7  Generic abstractions related to dispatching event
symfony/expression-language        v4.3.5  v4.3.6  Symfony ExpressionLanguage Component
symfony/filesystem                 v4.3.5  v4.3.6  Symfony Filesystem Component
symfony/finder                     v4.3.5  v4.3.6  Symfony Finder Component
symfony/flex                       v1.4.6  v1.4.6  Composer plugin for Symfony
symfony/form                       v4.3.5  v4.3.6  Symfony Form Component
symfony/framework-bundle           v4.3.5  v4.3.6  Symfony FrameworkBundle
symfony/http-client                v4.3.5  v4.3.6  Symfony HttpClient component
symfony/http-client-contracts      v1.1.7  v1.1.7  Generic abstractions related to HTTP clients
symfony/http-foundation            v4.3.5  v4.3.6  Symfony HttpFoundation Component
symfony/http-kernel                v4.3.5  v4.3.6  Symfony HttpKernel Component
symfony/inflector                  v4.3.5  v4.3.6  Symfony Inflector Component
symfony/intl                       v4.3.5  v4.3.6  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/maker-bundle               v1.14.0 v1.14.1 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                       v4.3.5  v4.3.6  A library to manipulate MIME messages
symfony/monolog-bridge             v4.3.5  v4.3.6  Symfony Monolog Bridge
symfony/monolog-bundle             v3.4.0  v3.4.0  Symfony MonologBundle
symfony/options-resolver           v4.3.5  v4.3.6  Symfony OptionsResolver Component
symfony/orm-pack                   v1.0.7  v1.0.7  A pack for the Doctrine ORM
symfony/phpunit-bridge             v4.3.5  v4.3.6  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu          v1.12.0 v1.12.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.12.0 v1.12.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-mbstring          v1.12.0 v1.12.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72             v1.12.0 v1.12.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73             v1.12.0 v1.12.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/process                    v4.3.5  v4.3.6  Symfony Process Component
symfony/profiler-pack              v1.0.4  v1.0.4  A pack for the Symfony web profiler
symfony/property-access            v4.3.5  v4.3.6  Symfony PropertyAccess Component
symfony/property-info              v4.3.5  v4.3.6  Symfony Property Info Component
symfony/routing                    v4.3.5  v4.3.6  Symfony Routing Component
symfony/security-acl               v3.0.2  v3.0.2  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v4.3.5  v4.3.6  Symfony SecurityBundle
symfony/security-core              v4.3.5  v4.3.6  Symfony Security Component - Core Library
symfony/security-csrf              v4.3.5  v4.3.6  Symfony Security Component - CSRF Library
symfony/security-guard             v4.3.5  v4.3.6  Symfony Security Component - Guard
symfony/security-http              v4.3.5  v4.3.6  Symfony Security Component - HTTP Integration
symfony/serializer                 v4.3.5  v4.3.6  Symfony Serializer Component
symfony/serializer-pack            v1.0.2  v1.0.2  A pack for the Symfony serializer
symfony/service-contracts          v1.1.7  v1.1.7  Generic abstractions related to writing services
symfony/stopwatch                  v4.3.5  v4.3.6  Symfony Stopwatch Component
symfony/swiftmailer-bundle         v3.3.0  v3.3.0  Symfony SwiftmailerBundle
symfony/templating                 v4.3.5  v4.3.6  Symfony Templating Component
symfony/test-pack                  v1.0.6  v1.0.6  A pack for functional and end-to-end testing within a Symfony app
symfony/translation                v4.3.5  v4.3.6  Symfony Translation Component
symfony/translation-contracts      v1.1.7  v1.1.7  Generic abstractions related to translation
symfony/twig-bridge                v4.3.5  v4.3.6  Symfony Twig Bridge
symfony/twig-bundle                v4.3.5  v4.3.6  Symfony TwigBundle
symfony/validator                  v4.3.5  v4.3.6  Symfony Validator Component
symfony/var-dumper                 v4.3.5  v4.3.6  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter               v4.3.5  v4.3.6  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-link                   v4.3.5  v4.3.6  Symfony WebLink Component
symfony/web-profiler-bundle        v4.3.5  v4.3.6  Symfony WebProfilerBundle
symfony/web-server-bundle          v4.3.5  v4.3.6  Symfony WebServerBundle
symfony/yaml                       v4.3.5  v4.3.6  Symfony Yaml Component

#### PHP version

PHP 7.3.11-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Oct 24 2019 18:23:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-1+ubuntu18.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies

## Subject

I folowed all the steps on
https://symfony.com/doc/master/bundles/SonataAdminBundle/getting_started/installation.html

When clicking on Category Create, i get error
Return value of App\Entity\Category::getName() must be of the type string, null returned
When clicking on Blog Create, I get errors
Return value of App\Entity\BlogPost::getTitle() must be of the type string, null returned

I do not understand why it checks for null on create when it is supposed to be null.

I managed to make my dashboard work by adding the folowing for Category->getName(), BlogPost->getTitle(), BlogPost->getBody() get methods
```
 if($this->title === null)
        {
            $this->title = '';
  }
```

## Expected results
Create new form should be displayed

## Actual results
Error shown

```
TypeError:
Return value of App\Entity\Category::getName() must be of the type string, null returned

  at src/Entity/Category.php:57
  at App\Entity\Category->getName()
     (vendor/symfony/property-access/PropertyAccessor.php:397)
  at Symfony\Component\PropertyAccess\PropertyAccessor->readProperty(array(object(Category)), object(PropertyPath), false)
     (vendor/symfony/property-access/PropertyAccessor.php:93)
  at Symfony\Component\PropertyAccess\PropertyAccessor->getValue(object(Category), object(PropertyPath))
     (vendor/symfony/form/Extension/Core/DataMapper/PropertyPathMapper.php:49)
  at Symfony\Component\Form\Extension\Core\DataMapper\PropertyPathMapper->mapDataToForms(object(Category), object(RecursiveIteratorIterator))
     (vendor/symfony/form/Form.php:378)
  at Symfony\Component\Form\Form->setData(object(Category))
     (vendor/sonata-project/admin-bundle/src/Controller/CRUDController.php:606)
  at Sonata\AdminBundle\Controller\CRUDController->createAction()
     (vendor/symfony/http-kernel/HttpKernel.php:151)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:198)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:25)
```

**Comment by greg0ire** [comment]
Sonata uses Symfony forms bound to entities directly, even for the create form, that means that every field in your entity has to have a nullable getter, or a default value that is not null. How did you create your entities?

**Comment by valentindragan** [comment]
I copied the code samples from the symfony website which seem to mirror the content sonata installation page. 
I added the question mark to make the getters nullable and it works.
`?string`

**Comment by greg0ire** [comment]
The docs talk at no point of category or blog.

**Comment by valentindragan** [comment]
> The docs talk at no point of category or blog.

https://symfony.com/doc/master/bundles/SonataAdminBundle/getting_started/creating_an_admin.html

https://sonata-project.org/bundles/admin/3-x/doc/getting_started/creating_an_admin.html
