### ISSUE TITLE
[Next Major] Drop old symfony deps

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#5761]

**Comment by franmomu** [comment]
After merging https://github.com/sonata-project/SonataAdminBundle/issues/5762 I think we can just use `^4.4 || ^5.0`

**Comment by OskarStark** [comment]
#5762 is an issue not a PR 🧐

**Comment by franmomu** [comment]
oops I meant https://github.com/sonata-project/SonataAdminBundle/pull/5787 🤦‍♂

**Comment by VincentLanglet** [comment]
> After merging ~#5762~ #5787 I think we can just use `^4.4 || ^5.0` and get rid of a bunch of deprecations.

https://github.com/sonata-project/SonataAdminBundle/pull/5787 is merged 🎉 
Should/can we bump the symfony version ?

**Comment by greg0ire** [comment]
We can't we are supposed to support `4.3` (it's an LTS). Is there a reason for which 4.4 is required for that?

**Comment by VincentLanglet** [comment]
Yeah, I was meaning adding ^5.0

**Comment by core23** [comment]
> We can't we are supposed to support `4.3` (it's an LTS). Is there a reason for which 4.4 is required for that?

4.4 is an LTS, so we can drop 4.3

**Comment by greg0ire** [comment]
Oh right, my bad!

**Comment by franmomu** [comment]
So I guess that this can be closed after https://github.com/sonata-project/SonataAdminBundle/pull/5843 was merged
