### ISSUE TITLE
[Next Major] Remove deprecated code

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#5763]

**Comment by VincentLanglet** [comment]
@core23 It's been years since the last major and I feel like the next major is really big with:
- Deprecated code removed
- Some BC-break added
- Some other BC-break wanted but not implemented
- Some dependency update
- Support for Symfony 5 asked
- Support for Twig 3 asked

What about splitting/prioritizing the needs of the milestone ?
What about planning both a 4.0 milestone and a 5.0 milestone ?

For example:
4.0
- Everything already added
- Dependency update
- Support for Symfony 5
- Support for Twig 3

5.0
- Deprecated code removed
- Some other BC-break wanted but not implemented

The fact that sonata does not support the latest versions of Symfony will impact its popularity.

**Comment by greg0ire** [comment]
Support for Symfony 5 and Twig 3 can and should go in Sonata 3 I think. Is there anything preventing that?

**Comment by VincentLanglet** [comment]
> Support for Symfony 5 and Twig 3 can and should go in Sonata 3 I think

That would be great.

I misunderstood the following comment https://github.com/sonata-project/SonataAdminBundle/issues/5761#issuecomment-570788139 and thought it was only possible on master.

**Comment by greg0ire** [comment]
> But making smaller major release can still be a good idea. :)

I'm not sure it's worth it actually, I think we were quite careful to add deprecations for most things we removed, and to ask people to add things to 3.x directly, so that releasing 4.0 is a non-event. Maybe it wouldn't be a bad idea to release 4.0 very very soon, after doing everything we can do and 5.0 once we have solved all the issues related to releasing dependencies (which turns out to be a bit painful/longer than expected). @core23 WDYT? Asking you since I think you have a good estimate of where we are at, especially regarding core bundle and block bundle.

**Comment by core23** [comment]
> > But making smaller major release can still be a good idea. :)
> 
> I'm not sure it's worth it actually, I think we were quite careful to add deprecations for most things we removed, and to ask people to add things to 3.x directly, so that releasing 4.0 is a non-event. Maybe it wouldn't be a bad idea to release 4.0 very very soon, after doing everything we can do and 5.0 once we have solved all the issues related to releasing dependencies (which turns out to be a bit painful/longer than expected). @core23 WDYT? Asking you since I think you have a good estimate of where we are at, especially regarding core bundle and block bundle.

I created a new milestone for the next next release: https://github.com/sonata-project/SonataAdminBundle/milestone/7

Doing all the remaining stuff that I just moved for the 4.0 release would consume too much time. We need a new major release soonish to get rid of the introduced deprecations.

The good news: We are nearly there. Only 3 (4 with rector) tasks need to be done.

**Comment by VincentLanglet** [comment]
Why isn't there a wip 4.0 Changelog file ?
When removing some deprecated code or adding some BC-break to master, we should add a line to the 4.0 changelog or the update will be hard for the users. Am I wrong ?

**Comment by greg0ire** [comment]
CONTRIBUTING.md says we are supposed to do this on release:

Also, the following files must be created/updated on the new stable branch:

 - `UPGRADE-43.x.md`, containing only the main title
 - `UPGRADE-43.0.md`, containing the upgrade notes fetched from the major PRs.
 - `CHANGELOG.md`, containing the changelog of the major PRs.
 - `composer.json`, the `branch-alias` MUST be changed to `43.x-dev`

**Comment by wbloszyk** [comment]
I'm working on #5597. I made example project for testing. After update SonataAdminBundle to master i had to update DoctrineORMAdminBundles too. So i have some questions:

1. Do you wanna release major version for all storege-AdminBundle before AdminBundle? There are templates to update too.
1. What with SonataBlockBundle? Major version is 4.0 but it is not used in AdminBundle. Should we add support for it? Should we drop support for 3.x? For me 

For me:
1. I think major version should be the same for admin and storage admin bundles(becouse it is extension).
1. we should try make "^3.18.4 || ^4.0". It is nice way to upgrade. Update dependencies, remove deprecations and upgrade AdminBundle. Also it is nice way to update PageBundle.

**Comment by VincentLanglet** [comment]
> 1. Do you wanna release major version for all storege-AdminBundle before AdminBundle? There are templates to update too.

I would say yes

> 2. What with SonataBlockBundle? Major version is 4.0 but it is not used in AdminBundle. Should we add support for it?

Yes we want to support 4.0 SonataBlockBundle.

**Comment by wbloszyk** [comment]
One more thing. What with webpack? It look like @silasjoisten havent time to end it. Should I check it?

**Comment by VincentLanglet** [comment]
> One more thing. What with webpack? It look like @silasjoisten havent time to end it. Should I check it?

Last news seems to be https://github.com/sonata-project/SonataAdminBundle/issues/5863#issuecomment-597458072

You can see with him if you can help if you want.
Adding webpack would be great !

**Comment by wbloszyk** [comment]
Next Major will be replace CoreBundle for other package which will be in conflict with CoreBundle. It is mean bundles with CoreBundle dependencies must have own major realase too. Second support for BlockBundle 3.x must be drop becouse there are CoreBundle dependencies too. 

Can we do in all sonata-project bundles in master branch:
1. Replace CoreBundle by new packages (in more bundles it is done)
1. Drop support for BlockBundle 3.x and set ^4.0 where CoreBundle is dropped
1. Update composer.json (php version ..., packages)
1. Remove CORE from travis and remove unsupported php

Then working on all all bundles will be easy.

Also can you merge #5834 ? It will keep admin working well until webpack release. It is only one directory to delete. I think better keep issues and RP as clear as possible.

**Comment by VincentLanglet** [comment]
Now we removed CoreBundle, what is currently delaying the 4.0 release @sonata-project/contributors @wbloszyk ?

IMHO webpack is not mandatory an could wait for 5.0.

The 4.0 release is already big, we could work on it now and try to make smaller release 5, 6, ...

**Comment by jordisala1991** [comment]
IMO having symfony 5 on Sonata4 could delay the release because if we dont do the BC breaks before release we will not have the chance after release

**Comment by VincentLanglet** [comment]
Yes, indeed.
We also started to add typehint everywhere so we could also finish this.

Last things to do could be
- Remove `NEXT_MAJOR`
- Add missing typehint
- Add support for SF5 and Twig 3

What do you think about starting to release some 4.0-alpha version and for example using them in storage-bundle master branch ?

And maybe the sandbox could use the master branch.
Currently there is no way to know if the code is still working on this branch.

**Comment by wbloszyk** [comment]
@VincentLanglet I working on webpack becouse i need it in my project. Before 4.0 release we should do something with BlockBundle. I mean we should support both version for some time (3.x and 4.x) of all Sonata bundles. This allow upgrade one by one bundle and check it is project working. I see two options:
1. Add support for BlockBundle 4.x in sonata 3, remove support for 3.x in sonata 4
1. Keep support for BlokBundle 3.x in sonata 4, bump it some time later

**Comment by VincentLanglet** [comment]
How do you want to support both version of BlockBundle ? @wbloszyk

The only usage is `AbstractBlockService` but the constructor changed and the return typehint were added.
I thought about it yesterday but I didn't find any solution to stay BC.

The fact that SonataAdmin v3 use Block v3 and SonataAdmin v4 use Block v4 seems ok to me.
In the same way, SonataDoctrineORM v3 use SonataAdmin v3 and the SonataDoctrineORM v4 will use SonataAdmin v4.

**Comment by jordisala1991** [comment]
To test sonata 4, we should update all sonata master branches to use 4.0@dev, otherwise it is impossible to install it and make it work.

We can create another branch on sandbox after that to see how Sonata 4 works. (or move master to 3.x and use master for 4.x)

**Comment by wbloszyk** [comment]
@VincentLanglet 
Look at whole Sonata bundles. It is good idea to force user to upgrade whole bundle (from Sonata3 to Sonata4) at one time?  I think we can keep support for BlockBundle3 in Sonata4, becouse:
- BlockBundle3 allow use BlockBundle4 constructor
- return type hint can be add when parent haven't it
- type hint can be drop if parent have it

Some things like extends final block in BlockBundle4 (like `MenuBlockService`) and is not final in BlockBundle3 can be decorete. API between both version should allow for it. It mean BlockBundle will be the last bundle update in upgrade prccess.

@core23 You also work on Block. WDYT?

**Comment by wbloszyk** [comment]
@jordisala1991 Better option is add support for `4.x-dev` in Sonata3. I will check it tommorow and create TODO list. It is possible.

**Comment by wbloszyk** [comment]
I run master admin in sandbox by `"sonata-project/admin-bundle": "prepare_to_major_master-dev as 3.71.1",`. In here issue you can find some information about it and TODO list:
https://github.com/sonata-project/dev-kit/issues/780

**Comment by core23** [comment]
> Some things like extends final block in BlockBundle4 (like `MenuBlockService`) and is not final in BlockBundle3 can be decorete. API between both version should allow for it. It mean BlockBundle will be the last bundle update in upgrade prccess.

I've a little lost the track of the recent sonata 4 development. If it is possible to support block 3/4, we should do it. We can remove support for the older version later.

Please keep an eye on the [4.0 milestone](https://github.com/sonata-project/SonataAdminBundle/milestone/6). This should help to focus.

**Comment by VincentLanglet** [comment]
Closing since there is no deprecated code anymore.
