### ISSUE TITLE
[Next Major] Use latest sonata deps

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#5764]

**Comment by VincentLanglet** [comment]
Is there any target release date for the new major ?

**Comment by core23** [comment]
> Is there any target release date for the new major ?

When it's done. We are just a small team that is working on our free time for this project. 

You can help us with the labeled topics which are a must do before the next major release.

**Comment by core23** [comment]
Can we close this @franmomu ?

https://github.com/sonata-project/SonataAdminBundle/pull/5833/files is merged

**Comment by franmomu** [comment]
Yes!
