### ISSUE TITLE
Do not use private functions 

### ISSUE THREAD

**Issue by grekpg** [sonata-project/SonataAdminBundle#5765]
## Feature Request

Example class CRUDController

 /**
     * Sets the admin form theme to form view. Used for compatibility between Symfony versions.
     */
    private function setFormTheme(FormView $formView, array $theme = null): void
    

Why this and many other metod is private - im offen extends many classes and this class. so need copy methods. 

Please use Protected nor private

**Comment by core23** [comment]
This is intended to reduce BC breaks for us. We expose some public endpoints which you can extend. If you want one specific, please create an issue with an example why you need this.
