### ISSUE TITLE
Allow IfTrue, IfFalse, IfEnd for conditional tab/with

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#5775]
## Feature Request

I would like this syntax
```
$formMapper
  ->ifTrue(false)
  ->tab('label_contract_status')
  ->with('label_contract_status')
  ->add('contractStatus')
  ->end()
  ->end()
  ->ifEnd();
```
To not show an empty tab.

And
```
$formMapper
  ->tab('label_contract_status')
  ->ifTrue(false)
  ->with('label_contract_status')
  ->add('contractStatus')
  ->end()
  ->ifEnd()
  ->end();
```
To not show an empty group

Actually they both do the same than
```
$formMapper
  ->tab('label_contract_status')
  ->with('label_contract_status')
  ->ifTrue(false)
  ->add('contractStatus')
  ->ifEnd()
  ->end()
  ->end();
```

**Comment by phansys** [comment]
I've tried to provide this feature before (https://github.com/sonata-project/SonataAdminBundle/pull/5585#issuecomment-501839586), but the time spent has forced me to omit this behavior.
Please, be free to propose a PR with this great addition! :+1:

**Comment by core23** [comment]
Is there a reason why you can't use a normal if statement? 

IMHO we should remove these methods completely as they don't provide any additional stuff.

**Comment by VincentLanglet** [comment]
> Is there a reason why you can't use a normal if statement?

Why I can't ? No there is no reason.
Why I don't want to ? Yes, I don't want to mix `Iftrue` and if (true)` in my code, and I liked these methods for conditional add.
 
> IMHO we should remove these methods completely as they don't provide any additional stuff.

Chaining methods is nice

**Comment by VincentLanglet** [comment]
> Please, be free to propose a PR with this great addition! 👍

@phansys https://github.com/sonata-project/SonataAdminBundle/pull/5779 ;)
