### ISSUE TITLE
Deprecate IfTrue, IfFalse, IfEnd

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#5778]
I would like to deprecate the following methods, because they don't provide anything special logic in comparison to normal if statements. They just accept a boolean parameter. Also you can only use them with `::add`.

-  `BaseGroupedMapper::ifTrue`
-  `BaseGroupedMapper::ifFalse`
-  `BaseGroupedMapper::ifEnd`

WDYT @sonata-project/contributors 

Removing this would close https://github.com/sonata-project/SonataAdminBundle/issues/5775

**Comment by greg0ire** [comment]
I think it's nice syntactic sugar to keep the interface fluent… @VincentLanglet what's your opinion on this?

**Comment by phansys** [comment]
IMO, these methods are intended to avoid polluting the fluent interface with breaking `if`s that tends to make harder to keep the indentation clean:
```php
$mapper
    ->with('...')
        ->ifTrue(true)
            ->add('...')
        ->ifEnd()
        ->add('...')
        ->ifTrue(true)
            ->add('...')
        ->ifEnd()
    ->end();
```

**Comment by VincentLanglet** [comment]
I agree with @greg0ire and @phansys. This is a nice syntactic sugar to keep chaining method.
