### ISSUE TITLE
Auto quess filter type broken in sonata-project/admin-bundle 3.56.0

### ISSUE THREAD

**Issue by grekpg** [sonata-project/SonataAdminBundle#5781]
After update 

`- Updating sonata-project/admin-bundle (3.55.0 => 3.56.0): Loading from cache`

all filters with null type throw error

`No attached service to type named `doctrine_orm_number``

here is line 
`$datagridMapper->add('id')`

id definition 

```
  /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

```

Rolling back to 3.55.0 fix errors

**Comment by scuben** [comment]
I just ran into the same issue.

**Comment by jaxel87** [comment]
[These aliases are used as filter names](https://github.com/sonata-project/SonataAdminBundle/commit/51201320bbb53431acc4b303b1735ee1474ea3c5#diff-e7680a7f9961b136663cf182b119e0c5L38)

```
            // NEXT_MAJOR: Remove the alias when dropping support for symfony 2.x
            foreach ($attributes as $eachTag) {
                $types[$eachTag['alias']] = $id;
            }
```

**Comment by core23** [comment]
Did you use `doctrine_orm_number` somewhere in your code?

**Comment by core23** [comment]
I think we need to change this one: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Guesser/FilterTypeGuesser.php#L73

@franmomu

**Comment by franmomu** [comment]
I'll take a look later, I'm away of my laptop right now.

**Comment by 7ochem** [comment]
We just encountered the same issue here:

In an Admin:
```
protected function configureDatagridFilters(DatagridMapper $filter) {
    parent::configureDatagridFilters($filter);
    $filter->add('language');
}
```
In the entity:
```
    /**
     * @ORM\Column(type="string", nullable=false)
     */
    private $language = 'en';
```
Error:
```No attached service to type named `doctrine_orm_string` ```
In: vendor/sonata-project/admin-bundle/src/Filter/FilterFactory.php (line 57)

But I guess the type has been 'guessed' somewhere else before it reaches that piece of code.
That guesser should also set the FQCNs instead of the old name strings.

**Comment by core23** [comment]
> I think we need to change this one: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Guesser/FilterTypeGuesser.php#L73
> 
> @franmomu

Same for the phpcr admin:
https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/blob/2.x/src/Guesser/FilterTypeGuesser.php#L82

**Comment by ibasaw** [comment]
same here since last composer update
