### ISSUE TITLE
composer require sonata-project/admin-bundle don't work with symfony 5

### ISSUE THREAD

**Issue by mouad-mahfoud** [sonata-project/SonataAdminBundle#5786]
please help me i m traying to install sonata admin bundle in a fresh symfony installation but i get this error 
Problem 1
    - Installation request for sonata-project/admin-bundle 3 -> satisfiable by sonata-project/admin-bundle[3.0.0].
    - sonata-project/admin-bundle 3.0.0 requires symfony/http-foundation ^2.3 || ^3.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help

**Comment by Bodarev** [comment]
I have the following problem 
![composer json - ecars - Visual Studio Code](https://user-images.githubusercontent.com/18719739/71259344-ec721500-2340-11ea-9abc-aca73e286428.png)
after trying to install : 
$ composer require sonata-project/admin-bundle

I'm trying to install symfony/asset :
$ composer require symfony/asset:4.2.12
![Articles php - ecars - Visual Studio Code](https://user-images.githubusercontent.com/18719739/71259984-6bb41880-2342-11ea-8d26-ff703371a010.png)

help solve the problem, the project is new on symfony 5
