### ISSUE TITLE
[Next Major] Close API

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#5791]
- [ ] Add `final` modifier
- [ ] Reduce visiblity to `private`
- [ ] Add type hints

**Comment by greg0ire** [comment]
Now that 7.1 is EOL (https://secure.php.net/supported-versions.php), maybe we should bump to 7.2 add _parameter_ type declarations in a new minor? If we consider current docblocks as a contract?

**Comment by core23** [comment]
👎 For adding parameter types. There is a reason why symfony won't do this in a major release...

👍 For adding return types

**Comment by greg0ire** [comment]
Adding return types to final classes, but not otherwise, and not to interfaces either: https://3v4l.org/KLvG9

**Comment by core23** [comment]
> 👍 for adding return types to final classes, but not otherwise, and not to interfaces either: https://3v4l.org/KLvG9

👍 for full return / parameter types to final classes

> You mean a minor release, and what's the reason?

If we add a parameter type and someone uses an other type hint, it would break:
https://3v4l.org/XBfik

**Comment by greg0ire** [comment]
But… they can't use another type hint, that would break the LSP, and php rightfully forbids that: https://3v4l.org/eiigE

**Comment by greg0ire** [comment]
Also, we can add type declarations to private methods.

**Comment by VincentLanglet** [comment]
I saw you add final to lot of classes @franmomu https://github.com/sonata-project/SonataAdminBundle/pull/6819
The last one is `AdminHelper`. Declaring this class as final had complexity to our unit tests since we can't mock it anymore.
What is your opinion about this class ?

AdminHelper::getChildFormView and getChildFormBuilder seems better in another service IMHO

The AdminHelper::appendFormFieldElement is only used by AppendFormFieldElementAction maybe an service is not worth it and we should prefer move the method from the AdminHelper to the AppendFormFIeldElementAction.

**Comment by vladyslavstartsev** [comment]
> since we can't mock it anymore

you can do
https://github.com/dg/bypass-finals

**Comment by franmomu** [comment]
I haven't checked that class too much, I'll try (when I can) to see if I can instantiate it, another solution could be to make it `@internal` as looks like internal to us. It is used as dependency in `AppendFormFieldElementAction` and `RetrieveFormFieldElementAction`, but IMO these actions are meant to be called through request, not manually instantiating them.

**Comment by VincentLanglet** [comment]
> another solution could be to make it `@internal` as looks like internal to us. It is used as dependency in `AppendFormFieldElementAction` and `RetrieveFormFieldElementAction`, but IMO these actions are meant to be called through request, not manually instantiating them.

I agree. I thought about this too.

**Comment by dmaicher** [comment]
I had a look and its indeed not simple to use a "real" instance of `AdminHelper`. Involves fiddling around with `FormFactory`, `FormBuilder`, ...

I vote for making it `@internal`

**Comment by dmaicher** [comment]
Is there anything else to do for this issue?

The `AdminHelper` class is `@internal` now. See https://github.com/sonata-project/SonataAdminBundle/pull/6842

**Comment by VincentLanglet** [comment]
I think there is some minor changes possible:
- AdminHelper::$propertyAccessor can be private
- AdminHelper::getModelClassName() too

But that's all I see.

**Comment by VincentLanglet** [comment]
@dmaicher I started https://github.com/sonata-project/SonataAdminBundle/pull/6848

We can add final to a lot of method.
