### ISSUE TITLE
deleteAction has unused param $id

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#5805]
There is something weird in the deleteAction code:
```
/**
     * Delete action.
     *
     * @param int|string|null $id
     *
     * @throws NotFoundHttpException If the object does not exist
     * @throws AccessDeniedException If access is not granted
     *
     * @return Response|RedirectResponse
     */
    public function deleteAction($id)
    {
        $request = $this->getRequest();
        $id = $request->get($this->admin->getIdParameter());
        $object = $this->admin->getObject($id);

...
```

The `$id` param is unused  since we get it in the request:
```
$id = $request->get($this->admin->getIdParameter());
```

In our project, we override the function this way because we had an error (I don't remember in which situation).
```
    /**
     * Fix deleteAction
     *
     * @param $id
     *
     * @return RedirectResponse|Response
     */
    public function deleteAction($id = null)
    {
        return parent::deleteAction($id);
    }
```

Shouldn't the `$id` param be removed of the action ?

**Comment by core23** [comment]
I think that's a legacy thing for the `CRUDController`. AFAIK there's a bug inside the routing which caused this strange hack. 

Can you provide a PR @VincentLanglet

**Comment by franmomu** [comment]
I guess the only thing you can do is to make it `null` by default. Removing it wouldn't be BC. There are other actions related to an object (edit, show, history, etc) that also have that legacy parameter and could be removed in `master`.

**Comment by VincentLanglet** [comment]
Done https://github.com/sonata-project/SonataAdminBundle/pull/5807

Should we add a "Next_Major: Remove the $id param" for all the method with an unused $id param or the hack is still needed ?

**Comment by greg0ire** [comment]
See also: #3970
