### ISSUE TITLE
Trigger warning / error when FormMapper::ifEnd is missing

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#5806]
Follows #5779 

When creating a form definition using `ifTrue` and `ifFalse` and you forget an `ifEnd` statement, I would expect a warning or an error.

This could result in some unexpected behavior, e.g. if you create an admin extensions which adds other fields.

**Comment by VincentLanglet** [comment]
@core23 I added an exception if there is too much ifEnd used here https://github.com/sonata-project/SonataAdminBundle/pull/5808

The PR should be merged quickly (before the next release) or we will have to wait the next major to avoid a BC-break.

For the "missing ifEnd case", I actually don't know how to do it.

**Comment by core23** [comment]
>  I added an exception if there is too much ifEnd used here #5808

:+1: 

> For the "missing ifEnd case", I actually don't know how to do it.

We should check if there are unclosed groups/tabs here:

https://github.com/sonata-project/SonataAdminBundle/blob/9af6ac5aaae40e2bf96c7c37255303b87fbe631d/src/Mapper/BaseGroupedMapper.php#L251-L259

**Comment by VincentLanglet** [comment]
See https://github.com/sonata-project/SonataAdminBundle/pull/5808#issuecomment-573473439

I think the first exception should be merged before the next release ; but the second exception can't be added before the 4.0 release because it's a BC-break.

**Comment by VincentLanglet** [comment]
@greg0ire I think this issue should still be open.

There is two exception to add
- To Many ifEnd (#5808)
- Missing ifEnd (not implemented)

**Comment by VincentLanglet** [comment]
This is not easily do-able, what you want is to throw an exception if you forgot to call an `ifEnd` in `configureShowFields`.
To do this we have to check after this call is the formMapper has no condition left, with an empty `apply` property.

I'm not sure it's worth to add a method to all mappers just for this...
