### ISSUE TITLE
Use constant when available

### ISSUE THREAD

**Issue by JohJohan** [sonata-project/SonataAdminBundle#5826]
## Feature Request
I think its a good practise to use [constant ](https://www.php.net/manual/en/function.constant.php)when available.

Example: [CRUDControllerTest.php](https://github.com/sonata-project/SonataAdminBundle/blob/44503963371ec36ec6d19ce9a61f6c07150ef47c/tests/Functional/Controller/CRUDControllerTest.php)

We have tests that  has a ``GET'` request and return a http code `200`.

Symfony has constants for this see [Response.php](https://github.com/symfony/http-foundation/blob/master/Response.php) and [Request.php](https://github.com/symfony/http-foundation/blob/master/Request.php).

If you think its a good idea let me know i would like to implement this.

**Comment by core23** [comment]
Feel free to improve our tests @JohJohan 👍

**Comment by JohJohan** [comment]
Finished see https://github.com/sonata-project/SonataAdminBundle/pull/5827

I also applied it the the rest of the project to keep it consistent. Let me know what you think
