### ISSUE TITLE
[Major] Create rector set for major upgrade

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#5837]
## Feature Request

We could create a [rector]( https://github.com/rectorphp/rector) set to make the migration to the next major release less painful for the user. The set would do <strike>all</strike> the most manual steps on the user code base to migrate old code fragements.

This is just an idea. I'm not sure how complicated this could be.

**Comment by core23** [comment]
There is a short guide which can generate recipes for us:
https://github.com/rectorphp/rector/blob/master/docs/RectorRecipe.md

**Comment by VincentLanglet** [comment]
I'm removing the 4.0 milestone since this step is optional for the release.
