### ISSUE TITLE
[Feature Request] Way to do both PrePersist and PreUpdate.

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#5845]
### Context
I used a lot the `PreUpdate` function of the Admin.
Recently I notice a bug in my project, and found it was because the `PreUpdate` is not called after during creation, only edition.

This is kinda my fault, I should have checked.
And it's the same behaviour than the doctrine `PreUpdate`.

I recently fixed this by adding a `PrePersist` with the same code than the `PreUpdate` everywhere.

### Idea
With Doctrine Annotation, I can easily write 
```php
/**
 * @ORM\PrePersist
 * @ORM\PreUpdate
 **/
public function foo()
{
  // do something
}
```

But in Sonata I have to write
```php
public function PrePersist()
{
  // do something
}

public function PreUpdate()
{
  // do the same thing
}
```

What about something like a function called by both PrePersist and PreUpdate ? (same for Post)
Something else ?

**Comment by core23** [comment]
This is a special use case that especially easy to fix. Either you create a custom admin extension or call a separate method in both methods

**Comment by wbloszyk** [comment]
It is really nessesery when you can do something like this?:
```php
public function PrePersist()
{
    // do something 1
    $this->preDoSomethingForBoth();
    // do something 2
}

public function PreUpdate()
{
  // do the same thing
    $this->preDoSomethingForBoth();
}

private function preDoSomethingForBoth()
{
  // do something for both
  // for example update field `updateAt'
}
``` 

Then you decide when  `doSomethingForBoth` should be called. New function should called before or afer PreXXXXX() function? prePreDoSomethingForBoth() and postPreDoSomethingForBoth()?

**Comment by VincentLanglet** [comment]
@core23 @wbloszyk I agree this can fix with a custom admin extension or calling a separate method in both methods.

I just wanted to know if this is something useful to add to Sonata (and I could make a PR) or if it's something I should just make in my project.

**Comment by core23** [comment]
> I just wanted to know if this is something useful to add to Sonata (and I could make a PR) or if it's something I should just make in my project.

In the past, we've added too many extension points that are hard to maintain for us. I would like to keep the API simple, especially if this is easy to fix for custom code.

**Comment by VincentLanglet** [comment]
Ok
