### ISSUE TITLE
Pre-filter the list view

### ISSUE THREAD

**Issue by Minirock** [sonata-project/SonataAdminBundle#5859]
## Feature Request

Hi, first of all, let me tell you I don't know if this is already possible or not (but I can't find it on the documentations, so I guess it's not)

When you have an a `ForumAdmin` class you can define which fields can be printed and filtered in the list view.

```
protected function configureListFields(ListMapper $listMapper)
{
    $listMapper->addIdentifier('name');
    $listMapper->addIdentifier('description');
    $listMapper->addIdentifier('owner');
}
```

```
    protected function configureDatagridFilters(DatagridMapper $datagridMapper)
    {
        $datagridMapper->add('name');
    }
```

This is great, but sometimes we dont want to retrieve all the datas. You may want to filter the shown result already when loading the page.

To be more specific, you may want to get only the list of forum where you are the owner which means later the filtering method will only work hover the pre-filtered data

It could be nice to have something like that

```
    protected function preConfigureDatagridData(DatagridMapper $datagridMapper)
    {
        $datagridMapper->filter('owner',$possible_users);
    }
```
It would be nice to provide a field and a set of 'pre-filter' values for this field.

Exemple : 

List of Forum entities

`1,Forum 1,Description forum 1, Marc`
`2,Forum 2,Description forum 2, Paul`
`3,Forum 3,Description forum 3, Marc`
`4,Forum 4,Description forum 4, Lea`

```
    protected function preConfigureDatagridData(DatagridMapper $datagridMapper)
    {
        $datagridMapper->filter('owner',['Paul','Lea']);
    }
```

Then in the list view you will only getting the entities 1,3,4 and the number 2 will never be shown whatever filter we are using later considering he isn't on the possible values since the start.

**Comment by haivala** [comment]
This should work
https://sonata-project.org/bundles/doctrine-orm-admin/master/doc/reference/filter_field_definition.html#callback

**Comment by Minirock** [comment]
Oh I see yes it looks like this is doing it, I will try it. Thanks.

Still a little verbose for what it is I think but if it works no big deal :)

**Comment by VincentLanglet** [comment]
@Minirock Does this issue can be closed ?
