### ISSUE TITLE
problem with install

### ISSUE THREAD

**Issue by AntonVLA** [sonata-project/SonataAdminBundle#5892]
when i try
composer require sonata-project/admin-bundle
 it dont work, write

Problem 1
    - Installation request for sonata-project/admin-bundle ^3.59 -> satisfiable by sonata-project/admin-bundle[3.59.0].
    - sonata-project/admin-bundle 3.59.0 requires symfony/asset ^4.3 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
