### ISSUE TITLE
 SonataCoreBundle is deprecated

### ISSUE THREAD

**Issue by garak** [sonata-project/SonataAdminBundle#5906]
As stated on [its README](https://github.com/sonata-project/SonataCoreBundle/blob/3.x/README.md), SonataCoreBundle is deprecated.

This bundle should not rely on SonataCoreBundle anymore

**Comment by VincentLanglet** [comment]
I working on it https://github.com/sonata-project/SonataAdminBundle/pull/5936

**Comment by wbloszyk** [comment]
Should be close in favor for https://github.com/sonata-project/dev-kit/issues/697
