### ISSUE TITLE
configureListFields and configureShowFields should return an exception for non-found fields

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#5907]
## Feature Request

In configureFormFields, 
```
$formMapper->add('nonExistingField', TextType::class)
```

Throw an exception
```
Neither the property "nonExistingField" nor one of the methods "getNonExistingField()", "nonExistingField()", "isNonExistingField()", "hasNonExistingField()", "__get()" exist and have public access
```

There is an exception too for filters.

But there is no error in configureListFields or configureShowFields.
I expect an exception too.

**Comment by BrianWalters** [comment]
I think this would be a nice improvement.

@VincentLanglet  @core23 I can make a PR for this if no one else has started it.

**Comment by VincentLanglet** [comment]
> I think this would be a nice improvement.
> 
> @VincentLanglet @core23 I can make a PR for this if no one else has started it.

I didn't heard about someone working on it, so feel free to make a PR ! :)

**Comment by VincentLanglet** [comment]
@BrianWalters Did you start something ? Do you need help ?
