### ISSUE TITLE
Improve render of array values (and Array Collection)

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#5908]
## Feature Request

Actually, in the `configureShow`, the following code `$showMapper->add('investedProduct')` is rendering:
![image](https://user-images.githubusercontent.com/9052536/74923824-c107b700-53d1-11ea-9360-e20b60a31bd1.png)

I was expecting something more like the template used by OneToMany field:
![image](https://user-images.githubusercontent.com/9052536/74928515-f0222680-53d9-11ea-9917-8548e9652c96.png)

And in a dream world, every type would be applied on every value of the array.
For example `$showMapper->add('investedProduct', 'trans')` would work, by calling `trans` on every values.

In a similar way, when used on an ArrayCollection field (wich is not a OneToMany field), the value displayed is
```
Doctrine\Common\Collections\ArrayCollection@0000000043b0ee94000000006896675c
```
It should have the same behaviour than OneToMany field

**Comment by osavchenko** [comment]
I suppose that you have implemented `__toString()` on `investedProduct` class, right? What if we create some kind of interface like:

```php
interface SonataTranslatableInterface
{
    public function getTransLabel(): string;

    public function getTransOptions(): array;

    public function getTransDomain(): ?string;
}
```

and use it instead of `__toString()` where it makes sense: show and list actions, titles, etc? This interface should be applicable to models used in admins.

**Comment by VincentLanglet** [comment]
> I suppose that you have implemented `__toString()` on `investedProduct` class, right? What if we create some kind of interface like:

Unfortunaly, `investedProduct` is an array field in my entity 😅

> ```
> interface SonataTranslatableInterface
> {
>     public function getTransLabel(): string;
> 
>     public function getTransOptions(): array;
> 
>     public function getTransDomain(): ?string; // or we can rely on translation domain from an admin  
> }
> ```

This seems to be a nice feature for Entities. Do you want to try to make a PR ?
The default SonataTranslatable could call `__toString` in `getTransLabel`.

But I don't think it will helps when you render an array of values or an arrayCollection of values.

**Comment by osavchenko** [comment]
Ah, got it. I thought about OneToMany relation and that's why I came with an interface.

> Do you want to try to make a PR ?
Yes, will do.

What do you mean "array of values"? An array of primitive types? What about new method like `addTranslatable($arg)` to the `ShowMapper` (like `addIdentifier()` on `ListMapper`) which will check is argument is iterable and if yes -> iterate throw elements and cast them to strings and translate elements.

**Comment by VincentLanglet** [comment]
> What do you mean "array of values"? An array of primitive types?

Yes, sometimes I have array of string in database.

> What about new method like `addTranslatable($arg)` to the `ShowMapper` (like `addIdentifier()` on `ListMapper`) which will check is argument is iterable and if yes -> iterate throw elements and cast them to strings and translate elements.

I was more thinking about modifying `show_array.html.twig` and `list_array.html.twig`.
Both use
![image](https://user-images.githubusercontent.com/9052536/78567909-a8d4e580-7821-11ea-8743-6fa5e4db0d59.png)

I would have taken the design of the OneToMany with ul and li
![image](https://user-images.githubusercontent.com/9052536/78568119-ecc7ea80-7821-11ea-9b48-7093ece7db2c.png)

I would have added an option `with_keys` or `values_only` or something like this in order to decide if the `keys` of the array should be displayed.

And I would have added an option `value_type`, which could be `int`, `boolean`, `trans`, ... and depending of the value of the option I would have called the code of the `show_int`, `show_boolean`, `show_trans`, ...

**Comment by osavchenko** [comment]
Got your point, thank you!

**Comment by osavchenko** [comment]
I thought about [this solution](https://github.com/sonata-project/SonataAdminBundle/issues/5908#issuecomment-609772010) and this is overengineering. Will provide another solution after current PR.
