### ISSUE TITLE
twig/extensions is abandoned and should be removed.

### ISSUE THREAD

**Issue by jaikdean** [sonata-project/SonataAdminBundle#5909]
## Feature Request

The `twig/extensions` package is abandoned and should be removed. Keeping it will stop us updating to Twig 3 and Symfony 5.

See https://github.com/twigphp/Twig-extensions#twig-extensions-repository

**Comment by VincentLanglet** [comment]
See https://github.com/sonata-project/SonataAdminBundle/pull/5865

**Comment by VincentLanglet** [comment]
Fixed by https://github.com/sonata-project/SonataAdminBundle/pull/6132
