### ISSUE TITLE
configureFormField is called when doing a batchAction. Result in an error because getSubject is null.

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#5915]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
symfony/asset                    v4.4.4  v5.0.4  Symfony Asset Component
symfony/browser-kit              v4.4.4  v5.0.4  Symfony BrowserKit Component
symfony/cache                    v4.4.4  v5.0.4  Symfony Cache component with PSR-6, PSR-16, and tags
symfony/config                   v4.4.4  v5.0.4  Symfony Config Component
symfony/console                  v4.4.4  v5.0.4  Symfony Console Component
symfony/contracts                v1.1.8  v2.0.1  A set of abstractions extracted out of the Symfony components
symfony/css-selector             v4.4.4  v5.0.4  Symfony CssSelector Component
symfony/debug                    v4.4.4  v4.4.4  Symfony Debug Component
symfony/debug-bundle             v4.4.4  v5.0.4  Symfony DebugBundle
symfony/dependency-injection     v4.4.4  v5.0.4  Symfony DependencyInjection Component
symfony/doctrine-bridge          v4.4.4  v5.0.4  Symfony Doctrine Bridge
symfony/dom-crawler              v5.0.4  v5.0.4  Symfony DomCrawler Component
symfony/dotenv                   v4.4.4  v5.0.4  Registers environment variables from a .env file
symfony/error-handler            v4.4.4  v5.0.4  Symfony ErrorHandler Component
symfony/event-dispatcher         v4.4.4  v5.0.4  Symfony EventDispatcher Component
symfony/expression-language      v4.4.4  v5.0.4  Symfony ExpressionLanguage Component
symfony/filesystem               v4.4.4  v5.0.4  Symfony Filesystem Component
symfony/finder                   v4.4.4  v5.0.4  Symfony Finder Component
symfony/flex                     v1.6.2  v1.6.2  Composer plugin for Symfony
symfony/form                     v4.4.4  v5.0.4  Symfony Form Component
symfony/framework-bundle         v4.4.4  v5.0.4  Symfony FrameworkBundle
symfony/http-foundation          v4.4.4  v5.0.4  Symfony HttpFoundation Component
symfony/http-kernel              v4.4.4  v5.0.4  Symfony HttpKernel Component
symfony/inflector                v5.0.4  v5.0.4  Symfony Inflector Component
symfony/intl                     v4.4.4  v5.0.4  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/mime                     v5.0.4  v5.0.4  A library to manipulate MIME messages
symfony/monolog-bridge           v5.0.4  v5.0.4  Symfony Monolog Bridge
symfony/monolog-bundle           v3.5.0  v3.5.0  Symfony MonologBundle
symfony/options-resolver         v4.4.4  v5.0.4  Symfony OptionsResolver Component
symfony/phpunit-bridge           v4.4.4  v5.0.4  Symfony PHPUnit Bridge
symfony/polyfill-ctype           v1.14.0 v1.14.0 Symfony polyfill for ctype functions
symfony/polyfill-iconv           v1.14.0 v1.14.0 Symfony polyfill for the Iconv extension
symfony/polyfill-intl-grapheme   v1.14.0 v1.14.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu        v1.14.0 v1.14.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn        v1.14.0 v1.14.0 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer v1.14.0 v1.14.0 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring        v1.14.0 v1.14.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php72           v1.14.0 v1.14.0 Symfony polyfill backporting some PHP 7.2+ features to lower PHP versions
symfony/polyfill-php73           v1.14.0 v1.14.0 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-uuid            v1.14.0 v1.14.0 Symfony polyfill for uuid functions
symfony/process                  v4.4.4  v5.0.4  Symfony Process Component
symfony/property-access          v4.4.4  v5.0.4  Symfony PropertyAccess Component
symfony/routing                  v4.4.4  v5.0.4  Symfony Routing Component
symfony/security-acl             v3.0.4  v3.0.4  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle          v4.4.4  v5.0.4  Symfony SecurityBundle
symfony/security-core            v4.4.4  v5.0.4  Symfony Security Component - Core Library
symfony/security-csrf            v4.4.4  v5.0.4  Symfony Security Component - CSRF Library
symfony/security-guard           v4.4.4  v5.0.4  Symfony Security Component - Guard
symfony/security-http            v4.4.4  v5.0.4  Symfony Security Component - HTTP Integration
symfony/serializer               v4.4.4  v5.0.4  Symfony Serializer Component
symfony/stopwatch                v4.4.4  v5.0.4  Symfony Stopwatch Component
symfony/string                   v5.0.4  v5.0.4  Symfony String component
symfony/swiftmailer-bundle       v3.4.0  v3.4.0  Symfony SwiftmailerBundle
symfony/templating               v4.4.4  v5.0.4  Symfony Templating Component
symfony/translation              v4.4.4  v5.0.4  Symfony Translation Component
symfony/twig-bridge              v4.4.4  v5.0.4  Symfony Twig Bridge
symfony/twig-bundle              v4.4.4  v5.0.4  Symfony TwigBundle
symfony/validator                v4.4.4  v5.0.4  Symfony Validator Component
symfony/var-dumper               v4.4.4  v5.0.4  Symfony mechanism for exploring and dumping PHP variables
symfony/var-exporter             v5.0.4  v5.0.4  A blend of var_export() + serialize() to turn any serializable data structure to plain PHP code
symfony/web-profiler-bundle      v4.4.4  v5.0.4  Symfony WebProfilerBundle
symfony/yaml                     v4.4.4  v5.0.4  Symfony Yaml Component
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
sonata-project/admin-bundle              3.61.0 3.61.0 The missing Symfony Admin Generator
sonata-project/block-bundle              3.18.4 4.1.0  Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/core-bundle               3.18.0 3.18.0 Symfony SonataCoreBundle (abandoned)
sonata-project/datagrid-bundle           2.5.0  3.1.1  Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.5.1  1.5.1  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.14.0 3.14.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.1.0  2.1.0  Lightweight Exporter library
```

#### PHP version

```
$ php -v
PHP 7.4.2 (cli) (built: Feb  2 2020 07:56:32) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies
```

## Subject

When clicking on a batch action
![image](https://user-images.githubusercontent.com/9052536/75249611-dcf6c880-57d6-11ea-8744-b8c2d7e390e2.png)

I get an error `calling foo() on $this->getSubject()`.
But the only place I use `$this->getSubject()->foo()` is in configureFormField().

Why the configureFormField() is called in the route: `myAdmin/batch` ?
This seems weird for me.
I need to investigate this issue, but If you have any idea, I take it.

## Expected results

No error.

**Comment by VincentLanglet** [comment]
I used `git bisect` on my project and found that the issue came up when I bump the version of SonataAdmin from `3.54.1` (the batch action worked) to `3.55.0` (the batch action doesn't worked anymore).

**Comment by oleg-andreyev** [comment]
@VincentLanglet `AdminInterface` does not guarantee  that `getSubject` will be a valid `object` it could be `NULL`
https://github.com/sonata-project/SonataAdminBundle/blob/467a14341ef36641a5859364aba21d824cef9123/src/Admin/AdminInterface.php#L353-L356, so you need to check `hasSubject` before performing any actions.

**Comment by VincentLanglet** [comment]
@oleg-andreyev The `AdminInterface` does not guarantee that `getSubject` will be a valid `object` because this function can be used in any context.

For example I don't expect `getSubject` to return something if I use it in `configureListFields`. But it should always return an `object` in a show/create/edit context.
And if you look at the comment of the AbstractAdmin, it seems to agree with me.
![image](https://user-images.githubusercontent.com/9052536/75716395-645ca400-5ccf-11ea-9108-36bba3eb2efa.png)

So I don't see the point in calling `configureFormField` without an object to edit. And I don't think building a full form, with nothing to edit, just to get the `csrf_option` is a good idea. 
There could be so much logic in the `configureFormFields` with database impact, or slow queries. And now, this code is executed when someone use the `deleteAction` or any custom `batchAction`.

Isn't possible to get the option value without building everything and calling all theses functions ?

I personally don't even think this should rely on the formOption. In your PR you wanted to introduced the feature for the `deleteAction` but it has the same impact in the `batchAction` which has nothing in common with a form. 
Different actions, different behaviour, so it should be different options.

**Comment by VincentLanglet** [comment]
@core23 I saw you were pretty active today. Do you have any opinion about this ?

**Comment by greg0ire** [comment]
>  Since you approved the PR @greg0ire @phansys @OskarStark, what's your opinion about this ?

I agree with you, that flaw wasn't obvious to me just from reading the PR.

**Comment by VincentLanglet** [comment]
> > Since you approved the PR @greg0ire @phansys @OskarStark, what's your opinion about this ?
> 
> I agree with you, that flaw wasn't obvious to me just from reading the PR.

Should I revert the PR as a quick fix then, waiting for finding a better way ?

**Comment by phansys** [comment]
Maybe we should deprecate `AdminInterface::getSubject()` and move this responsibility to the form and the show mappers.

**Comment by VincentLanglet** [comment]
> Maybe we should deprecate `AdminInterface::getSubject()` and move this responsibility to the form and the show mappers.

I didn't look how to implement this but this could be a great way to guarantee a non nullable object.

**Comment by phansys** [comment]
I think it can be nullable even on these classes, but at least the scope of the method can be kept in a narrower context.

**Comment by VincentLanglet** [comment]
I just looked at the code and `getSubject` is also used in `attachInlineValidator` and `getFormFieldDescriptions` and `getClass` is using `$this->subject`;

The first one, is called in `defineFormBuilder` so we could pass the `formMapper`. But not for the other method... 

> I think it can be nullable even on these classes, but at least the scope of the method can be kept in a narrower context.

What would be the situation where the `subject` could be null ?

I see the `getSubject` function like the `$form->getData()` of symfony.
Since the form configuration could depend on the data/subject, it shouldn't be nullable.

**Comment by VincentLanglet** [comment]
> I agree with you, that flaw wasn't obvious to me just from reading the PR.

@greg0ire @phansys As a quick fix, Can I revert the PR who introduced the bug ?

**Comment by phansys** [comment]
If there is no easy way to fix the issue, I think we should go ahead with the revert.
@oleg-andreyev, do you have any concern about this?

**Comment by oleg-andreyev** [comment]
I'm okay with reverting it if it's causing too many problems, but could you please create a follow-up task to ensure that this problem is not forgotten and we are aware about it.

**Comment by VincentLanglet** [comment]
The PR is created https://github.com/sonata-project/SonataAdminBundle/pull/5941

**Comment by VincentLanglet** [comment]
I want also to try to avoid any null subject when building a Form
https://github.com/sonata-project/SonataAdminBundle/pull/5942
