### ISSUE TITLE
Sort list by multiple fields.

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#5929]
## Feature Request

Actually in order to sort a list, you have to override the $datagridValues:
```
protected $datagridValues = [
    '_sort_order' => 'ASC',
    '_sort_by'    => 'lastname',
];
```
The syntax does not allow multiple sorting.

Maybe multi-sorting is not a good idea for UI reason: https://github.com/sonata-project/SonataAdminBundle/issues/1548.

What about something like persistent/hidden orderBy ?

If I add
```
$query->addOrderBy('o.usagename', 'ASC');
$query->addOrderBy('o.firstname', 'ASC');
```
And click on the column 'id'. I get the order by `id` AFTER the order by usagename/firstname.

The behaviour I'm looking for is
```
query->orderBy('columnClicked')
$query->addOrderBy('o.usagename', 'ASC');
$query->addOrderBy('o.firstname', 'ASC');
```

Either there should be an option to do this or this should be the default behaviour when you add order by in the create query.

**Comment by VincentLanglet** [comment]
A solution can be build by using some `addOrderBy` in the `createQuery` function.

It would need
- This PR to fix the behaviour of `_sort_by` VS custom `orderBy` https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/997
- To allow having no `_sort_by` value by default. (*)

(*) When creating the datagrid, there is the following line
```
$parameters = array_merge(
    $this->getModelManager()->getDefaultSortValues($this->getClass()),
    $this->datagridValues,
    $this->getDefaultFilterValues(),
    $filters
);
```

First, I don't see why there is a `$this->getDefaultFilterValues()` function since the developer can override the `$this->datagridValues` value. Should `$this->datagridValues` be private in next major 4.0 ?

Second, I disagree with the use of `$this->getModelManager()->getDefaultSortValues($this->getClass())`.
```
public function getDefaultSortValues($class)
    {
        return [
            '_sort_order' => 'ASC',
            '_sort_by' => implode(',', $this->getModelIdentifier($class)),
            '_page' => 1,
            '_per_page' => 25,
        ];
    }
```
By default there should be no `sort_by` value if the developper didn't add a default one and the user didn't clicked on a column.

This function is also weird because some of the parameters are overriden by the default admin values.
```
protected $datagridValues = [
   '_page' => 1,
   '_per_page' => 32,
];
```
Is overriden

I recommend
- Deprecate `getDefaultSortValues` and remove it in next MAJOR
- Make `getSortParameters` and `getPaginationParameters` functions compatible with the case with no `_sort_by` value

Optional
- do something about datagridValues VS getDefaultFilterValues.

**Comment by greg0ire** [comment]
> Should $this->datagridValues be private in next major 4.0 ?

Yes.

> By default there should be no sort_by value if the developper didn't add a default one and the user didn't clicked on a column.

Not sure why it bothers you exactly, and you know my stance on this (better be on the safe side).

**Comment by VincentLanglet** [comment]
I 
> > By default there should be no sort_by value if the developper didn't add a default one and the user didn't clicked on a column.
> 
> Not sure why it bothers you exactly, and you know my stance on this (better be on the safe side).

In https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/997, we updated the behaviour of custom sortBy vs `_sort_by` in a more natural way: 
- First, apply the column clicked `_sort_by`
- Then, apply the custom orderBy added in the createQuery

Since `_sort_by` does not handle multiple value (which is kinda normal since it would be a complicated UX for the table), when you want to order by multiple column (let's say lastname and firstname), you have to use it in the createQuery.

But since I have always a default `_sort_by`, my list will be ordered by
- Default sortby = id
- Lastname
- Firstname
This will be kinda useless for me.

With no default `_sort_by`, my list will be ordered by 
- Lastname
- Firstname
And if, and only if, I click on `id`, it will be ordered by 
- Id
- Lastname
- Firstname

But, what if there is no `orderBy` in the query and no `_sort_by` ?
We saw together that there is already a safety check when creating the query.
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/998#issuecomment-596005114

**Comment by VincentLanglet** [comment]
> > Should $this->datagridValues be private in next major 4.0 ?
> 
> Yes.

@greg0ire 

Actually, since the `modelManager->getDefaultSortValues`
```
[
   '_page' => 1,
   '_per_page' => 25,
]
```
is overriden by the `datagridValues`,
```
[
   '_page' => 1,
   '_per_page' => 32,
]
```
 the `getDefaultSortValues` is kinda useless.

Stop to use the `datagridValues` seems to be a good idea. But then, we need to do something for 
```
protected $maxPerPage = 32;
protected $perPageOptions = [16, 32, 64, 128, 256];
```
Because there is some functions checking that `_per_page` is in `perPageOptions`, etc...

Any advice about what to do with these value if I want to migrate them from the Admin too ?

**Comment by greg0ire** [comment]
In my opinion:

1. If you do nothing, it should be sorted by primary key(s)
2. If you define a default sort of last name then first name, then it should be sorted by last name, the first name, _and then by primary key(s)_
3. Finally, if the user clicks the `email` column, they should see a listing sorted by `email`, then last name, then first name, then primary key(s)

from what I understand, the `then primary keys(s)` is achieved by the safety check you speak of, correct, If yes, we can indeed remove the mechanism that also adds it at the beginning of the sort (the default `_sort_by`, correct?)

> But then, we need to do something for
> protected $maxPerPage = 32;
> protected $perPageOptions = [16, 32, 64, 128, 256];
> Because there is some functions checking that _per_page is in perPageOptions, etc...

I don't understand, please elaborate

**Comment by VincentLanglet** [comment]
> In my opinion:
> 
> 1. If you do nothing, it should be sorted by primary key(s)
> 2. If you define a default sort of last name then first name, then it should be sorted by last name, the first name, _and then by primary key(s)_
> 3. Finally, if the user clicks the `email` column, they should see a listing sorted by `email`, then last name, then first name, then primary key(s)

I agree with you
And actually we have 
 1. If you do nothing, it is sorted by primary key(s)
 2. If you define a default sort of last name then first name, then it is sorted by primary key(s) and then last name and the first name.
 3. Finally, if the user clicks the `email` column, they see a listing sorted by `email`, then last name, then first name, then primary key(s)

> from what I understand, the `then primary keys(s)` is achieved by the safety check you speak of, correct,

Yes

> If yes, we can indeed remove the mechanism that also adds it at the beginning of the sort (the default `_sort_by`, correct?)

Yes

> > But then, we need to do something for
> > protected $maxPerPage = 32;
> > protected $perPageOptions = [16, 32, 64, 128, 256];
> > Because there is some functions checking that _per_page is in perPageOptions, etc...
> 
> I don't understand, please elaborate

Let's say we're trying to remove the `datagridValue` property because we recommend to use the defaultSortValue from the manager.

First, there is a `maxPerPage` property which seems to override the `_per_page` value.
```php
public function __construct()
{
    $this->predefinePerPageOptions();
    $this->datagridValues['_per_page'] = $this->maxPerPage;
}

protected function predefinePerPageOptions()
{
   array_unshift($this->perPageOptions, $this->maxPerPage);
   $this->perPageOptions = array_unique($this->perPageOptions);
   sort($this->perPageOptions);
}
```
I don't know why there is this property. I think it should be better to remove it.

Then, there is the following check
```php
$parameters = array_merge(
    $this->getModelManager()->getDefaultSortValues($this->getClass()),
    $this->datagridValues,
    $this->getDefaultFilterValues(),
    $filters
);

if (!$this->determinedPerPageValue($parameters['_per_page'])) {
    $parameters['_per_page'] = $this->maxPerPage;
}

public function determinedPerPageValue($perPage)
{
    return \in_array($perPage, $this->perPageOptions, true);
}
```

If my AbstractAdmin has
```
protected $perPageOptions = [16, 32, 64, 128, 256];
```
And I try to override the `getDefaultSortValues`, to return
```
['_per_page' => 25]
```
Since 25 is not in `perPageOptions`, it will always be overriden.
So I have to change the `perPageOptions` of the admin (or all the admin) when I want to update the `_per_page` default value of the `ModelManager`. I think it's a wrong pattern.

There is something to do, like removing the check or moving this option in the ModelManager too.

I would like to clean all this @greg0ire.

**Comment by greg0ire** [comment]
I think there should be a check somewhere, you don't want your end users to be able to get 50000 items at a time, potentially locking too many db rows for sorting. Maybe the best would be to always merge whatever value is set by the developer (25 in your case) into the list of options? And sort the resulting array? `[16, 25, 32, 64, 128, 256];` ? I don't remember the Sonata UI, are there somewhere buttons you can click to switch from 16 to 32 and so on?

**Comment by VincentLanglet** [comment]
> I think there should be a check somewhere, you don't want your end users to be able to get 50000 items at a time, potentially locking too many db rows for sorting. 

Ok, so but this maxPerPage should apply after all the others configuration.
And this could come from the ModelManager instead being set in the AbstractAdmin.

> Maybe the best would be to always merge whatever value is set by the developer (25 in your case) into the list of options? And sort the resulting array? `[16, 25, 32, 64, 128, 256];` ?

This is what is done by `predefinePerPageOptions` for the `maxPerPage`.

But when building the list, there is a check `determinedPerPageValue` which fallback to `maxPerPage` if the value set by the developer is not into the list of options. I don't know why this is done that way, and it should be better to do it your way.

And again, the perPageOptions could come from the ModelManager.

> I don't remember the Sonata UI, are there somewhere buttons you can click to switch from 16 to 32 and so on?

All I know is this
![image](https://user-images.githubusercontent.com/9052536/76896144-99512500-6891-11ea-943e-ac33dfd93c22.png)

What I would like to do is something like
- Adding a `getMaxPerPage` and `getPerPageOptions` in the modelInterface https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Model/ModelManagerInterface.php
- Using all the value from the ModelManager instead of `datagridValues`, `maxPerPage` and `perPageOptions` from the AbstractAdmin.

This would be a step in the AbstractAdmin splitting.

**Comment by greg0ire** [comment]
> This is what is done by predefinePerPageOptions for the maxPerPage.

Oh right, I read a bit fast I guess :sweat_smile: 

> Adding a getMaxPerPage and getPerPageOptions in the modelInterface https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Model/ModelManagerInterface.php

That interface is already quite long… I think there could be a separate object/interface to be extracted from the admin, that would deal with pagination, without necessarily putting that responsability in the ModelManager scope. Hint: if it is called manager, it probably does too much already.

**Comment by VincentLanglet** [comment]
> > Adding a getMaxPerPage and getPerPageOptions in the modelInterface https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Model/ModelManagerInterface.php
> 
> That interface is already quite long… I think there could be a separate object/interface to be extracted from the admin, that would deal with pagination, without necessarily putting that responsability in the ModelManager scope. Hint: if it is called manager, it probably does too much already.

I agree. But it seems to be a lot more of work.

Would it be acceptable to
- First, in one PR, add the two functions to the ModelManagerInterface in order to make all the pagination changes.
- Second, in another PR, split it the ModelManagerInterface

**Comment by greg0ire** [comment]
It would be better than what we have now I guess…

**Comment by brunodim** [comment]
Hello @VincentLanglet @greg0ire ,

Here is how i deal with the multiple field orders in sonata admin list:

- Firstly i used the datagridValues parameters to set the first field i want to order with:

```
    _protected $datagridValues = [
        '_sort_order' => 'ASC',
        '_sort_by' => 'interventionStructure.name',
    ];
```
   
- Then i use the PHP binding closure behaviour to access to the query builder in the configureQuery method, because the createQuery method will become final and should not be overriden anymore:


```
   _protected function configureQuery(ProxyQueryInterface $query): ProxyQueryInterface
    {
        $query = parent::configureQuery($query);
        $cl = function() use ($query) {
            $this->queryBuilder->addOrderBy($query->getRootAliases()[0] . '.position', 'ASC');
        };
        $bcl = \Closure::bind($cl, $query, get_class($query));
        $bcl();

        return $query;
    };
```
