### ISSUE TITLE
PHP versions mismatch between admin bundle and core bundle

### ISSUE THREAD

**Issue by fnowacki** [sonata-project/SonataAdminBundle#5976]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
Empty list
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
No matters.
```

#### PHP version

```
$ php -v
PHP 7.1.33-12+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Feb 23 2020 07:22:16) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

## Steps to reproduce

- On PHP 7.1 version try to install Sonata Admin Bundle:

```
composer require sonata-project/admin-bundle
```

## Expected results

Sonata Admin will install properly.

## Actual results

Result from composer:
```
 Problem 1
    - sonata-project/admin-bundle 3.62.0 requires sonata-project/core-bundle ^3.18.0 -> satisfiable by sonata-project/core-bundle[3.18.0].
    - sonata-project/admin-bundle 3.62.1 requires sonata-project/core-bundle ^3.18.0 -> satisfiable by sonata-project/core-bundle[3.18.0].
    - sonata-project/core-bundle 3.18.0 requires php ^7.2 -> your PHP version (7.1.33) does not satisfy that requirement.
    - Installation request for sonata-project/admin-bundle ^3.62 -> satisfiable by sonata-project/admin-bundle[3.62.0, 3.62.1].
```

In: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/composer.json is php 7.1
In: https://github.com/sonata-project/SonataCoreBundle/blob/3.x/composer.json is php 7.2

**Comment by phansys** [comment]
This is not an issue actually. It's about different requirements of each package (see sonata-project/SonataCoreBundle#729).
"sonata-project/admin-bundle" 3.x is still requiring "sonata-project/core-bundle" because BC reasons, but in version 4.x it will be completely removed (although PHP 7.3 will be the minimum version there).

**Comment by fnowacki** [comment]
Okay, sounds good.
