### ISSUE TITLE
service SonataAdminBundle:CRUD

### ISSUE THREAD

**Issue by gekomod** [sonata-project/SonataAdminBundle#5991]
Symfony 5

#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```

#### Symfony packages

```
$ composer show --latest 'symfony/*'
# Put the result here.
```

#### PHP version
PHP 7.4.4 (cli) (built: Mar 20 2020 18:13:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.4, Copyright (c), by Zend Technologies
```
$ php -v

```

## Expected results
The controller for URI "/admin/app/menutype/list" is not callable. Controller "SonataAdminBundle:CRUD"

**Comment by VincentLanglet** [comment]
With no information about the package installed and the step to reproduce.

Please fill correctly the issue template or this issue will certainly be closed. @gekomod
