### ISSUE TITLE
Association Mapping Breaks Due to Recent Update if entity has custom __call method

### ISSUE THREAD

**Issue by daum** [sonata-project/SonataAdminBundle#6008]
Since the introduction of https://github.com/sonata-project/SonataAdminBundle/commit/894c260dd247ca69e894f052863b471d5cdd400d#diff-97179c4fc4120f802148ade89fc48508R251 The association checking uses is_callable versus method_exists.  The issue with this is for any entity that implements a __call function will return callable.

We discovered this in a recent upgrade because our DoctrineBehaviors translatable entities which were one to many relations had SonataAdmin errors.  Part of the official documentation is to override the call for proxying translations: https://github.com/KnpLabs/DoctrineBehaviors/blob/master/docs/translatable.md#proxy-translations .  

An example is the following A -> has many Bs.  Embedded this looks like `->add('bs'.....)`.  The behavior before was it'd notice that `$a->addBs` doesn't exist but `$a->addB` does exist.  Now it tries to call `$a->addBs` as it returns as callable due to the override.

Is there a specific final reason the logic was switch from method_exists to callable?  Wanted to see if this may be something which could be reverted so that we don't need to go back and add the plural aliases for all the relations add functions.

**Comment by VincentLanglet** [comment]
Hi @daum.

When I did this, there was no special reason, that wasn't the main goal of the PR.
Just a review from @phansys.

At first sight, `is_callable` seems to be a better check, because `method_exist` return `true` even if the function is `protected` or `private`. And this will lead to an error.
Maybe the best would be `method_exists($object, $method) && \is_callable([$object, $method])` ?

Do you want to start a PR ?

**Comment by daum** [comment]
The PR would be reverting back to method_exists.  As for supporting both, we could do the following:
* Use method exist checks first
* If they fail then try the is_callable methods 

This should then support both, what do you think?

**Comment by phansys** [comment]
If you want to exclude the behavior between `is_callable()` and `__call()`, the only solution I can imagine is based on the reflection API.

**Comment by VincentLanglet** [comment]
> If you want to exclude the behavior between `is_callable()` and `__call()`, the only solution I can imagine is based on the reflection API.

Changing
```
if (!\is_callable([$object, $method])
```
to 
```
if (!(\is_callable([$object, $method] && \method_exist($object, $method)))
```
wouldn't be enough ?

**Comment by daum** [comment]
I understand the exclusion of the behavior, just I think the testing with method exists to try to "depluralize" it is a better approach.  Will work on a PR with the update.

**Comment by phansys** [comment]
Yes, I think the requirement is about to know if a public method exists, so I think your first proposal (`\method_exist($object, $method) && \is_callable([$object, $method])`) will be enough for this case.

**Comment by daum** [comment]
Wouldn't that still be returning false on method_exists for a __call based one?

**Comment by VincentLanglet** [comment]
> Wouldn't that still be returning false on method_exists for a __call based one? Also I think the logic for the "callable" checks can be simplified into a single one, the object either has a customized __call function if the methods don't exist or it doesn't. Regardless of what the string of the method is, the is_callable is going to return true, right?

It's because you think only about your special case with __call method.
If I don't use `__call` and use `public/protected/private` methods, you have to check for `is_callable` every time you use `method_exists`.

**Comment by daum** [comment]
Ahhh I understand, made that update.  FYI for some reason PHP CS fixer really does not like the \method_exists and keeps requiring it to be simply method_exists.  I pushed that up.

I'd note that this will NOT support the `__call` method, but it never did before either.  This at least gets it back to being BC compatible.

**Comment by phansys** [comment]
>FYI for some reason PHP CS fixer really does not like the \method_exists and keeps requiring it to be simply method_exists.

That's because the configuration of the rule ["native_function_invocation"](https://github.com/FriendsOfPHP/PHP-CS-Fixer/tree/v2.16.1#usage), which is using
`@compiler_optimized` (functions that are specially optimized by Zend).
