### ISSUE TITLE
Next Major upgrade process for all bundles - propose

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataAdminBundle#6016]
## What next major change:
- close api
- add return type hints
- drop CoreBundle
- upgrade BlockBundle 3 => 4
- drop/update/add dependencies 
- add features

## For me we should try make major upgrade process stepable:
- upgrade project to the newest minor version
- drop dependencies
- upgrade BlockBundle and add return hints for own blocks
- upgrade one by one others sonata bundle 

#### Drop CoreBundle conflict - prepare extensions
- add conflict in form/twig-extensions `"sonata-project/core-bundle": ">=3.13 || <=3.18"`
- clone extensions to new branch - and remove return type hints
- release new extensions versions like 0.3 and 1,3
- i think recipe is requre here to add bride bundle
 
#### Drop CoreBundle conflict - prepare CoreBundle
- drop Sonata/ -form/ -twig in CoreBundle 
- and extensions in 0.x version
- release CoreBundle minor version 3.19, 

#### Drop CoreBundle conflict - update bundles
- allow use `^0.3 || ^1,3` extensions if they are use in any project also with major x.0 version
- drop support for ^0.3 version in major x.0.1 patch

#### Upgrade 3 => 4 changes
- change in API
- add return type hints

#### Upgrade option 1 - [example](https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1023)
- remove AbstractAdminBlockService and AdminBlockServiceInterface
- copy all blocks to block4, upgrade it to BlockBundle 4 

#### Upgrade option 2 - for me we should use it
- in BlockBundle replace tag 4.0.0 for BlockBundle 4 code without return type hints
- upgrade blocks like in [this commit](https://github.com/sonata-project/SonataClassificationBundle/commit/72cff95e75b0b89e3c693deb2a87bffa704d8f2a)
- allow use only BlockBundle 4.0.0 in current bundles

## Conclusion
Return type hints is the most BC-break thing in next upgrade.

**Comment by VincentLanglet** [comment]
I thought the type hints would be in the 5.0 release. The 4.0 is already pretty big.

**Comment by wbloszyk** [comment]
@VincentLanglet sorry, my bad. I talking about all project. Anyway it is better think about it now.

**Comment by core23** [comment]
Thanks for your listing @wbloszy ❤️ 

We already have an internal road map and a [road to sonata 4 issue on our dev-kit](https://github.com/sonata-project/dev-kit/issues/216). The steps your are mentioning are exactly our steps. Our main problem is time. We all want to release new major versions, but we have not enough time to finish this steps soon.

IMHO we made a mistake when we moved the core bundle to the new extensions repos. We should have made a 1:1 made a copy & paste of the original sources. But we added type hints and made some API changes. The only way to solve this issue is to backport the code to the extensions repo and release them as 0.x versions.

Btw. there is a milestone with the (last) steps we need for the admin bundle: https://github.com/sonata-project/SonataAdminBundle/milestone/6

**Comment by wbloszyk** [comment]
Thanks for informations. I don't know AdminBundle code very well. I will cofus to end AdminLTE upgrade and webpack. Then I will check what must be do to prepare extensions in 0.x version.

**Comment by wbloszyk** [comment]
@core23 I almost done #5989. I can not finish it on dependencies part like UserBundle. I check diff CoreBundle with extensions. It is possibile to create backport from 1.2 versions. Bundle config must stay in Core, so 0.x extensions must required Core. This will resolve composer version, but make another one. 0.x should be equal to 1.x but without return Types hints and bridge. Are you agree? I will work on it. I will finish it on jest week, becouse need free weekend.

**Comment by greg0ire** [comment]
I just realised this morning that removing a return type declaration is not a BC-break. How about we remove them (or at least, the ones that prevent us from upgrading) in 1.x, and then add them back in 2.x?

**Comment by wbloszyk** [comment]
There are also other change in API, like add support for contracts, drop support for some parameters. Remove return Types hints is not bc-break becouse user can add, but cant delete them. So we have 2 options:
1. Relase 0.x version
    - merge Core code with 1.x
    - next relases must based on 1.x version
    - 1.x update can be done in 0.x, then merge and add return Types hints
    - i have done it on own repository, todo is merge tests only
1. Remove return Types hints
    - less work, but what with API change
    - we have to add it back in 2.x 

Also remember 1.x is relased and someone can use it now. Add support for older version is strange thing. Also 0.x should be support as long as Sonata3 is - i think not long. 

For me: option 1

**Comment by greg0ire** [comment]
Ok for option 1 too,  I did not have the API changes in mind.

**Comment by wbloszyk** [comment]
Can you create 0.x branch from 1.2 tag for form and twig extensions? I will try finish it in Tuesday. I will also use it in #5989 demo, so i will check on practice how this upgrage process work.

**Comment by greg0ire** [comment]
Done.

**Comment by wbloszyk** [comment]
WDYT should we release CoreBundle 4.0 for use 0.x extensions? Remove extensions from Core required drop some service and is bc-break so i think it good way to force user to drop it. 4.0 can be used like check is bundle "ready for sonata 4". Also this will be good "first step" in sonata upgrade process.

**Comment by greg0ire** [comment]
It might make sense yeah :)
So IIUC, core bundle 4 would be an empty shell requiring 0.x extensions, correct?

**Comment by wbloszyk** [comment]
At first Core must drop all duplicated code (which is move to extensions). Later all other code must be mark as deprecated but mast stay in bundle to keep BC. After upgrade all bundles (ALL!!!) to `Sonata 4` user should drop it. So:
Add CoreBundle 4 - to start upgrade.
Remove CoreBundle 4 - all code is upgraded.

BTW I finish work on 0.x extensions and Core 4. Now I am working on deprecations notice and tests.

**Comment by wbloszyk** [comment]
@greg0ire @core23 and other @sonata-project/contributors WDYT?

I just relized something. I chek it and it is work. We can resolve upgrade problems by `SonataCoreBundle 4`.

##### sonata-project/core-bundle 3.13+ contains:
- Sonata\CoreBundle\*
- Sonata\Form\* - form-extensions legacy
- Sonata\Serializer\* - move to form-extensions
- Sonata\Twig\* - twig-extensions legacy

##### sonata-project/core-bundle 4.x should:
- contains only Sonata\CoreBundle
- required form-extensions 1.3 (with serializer)
- required twig-extensions 1.2
- drop all service whitch was moved to extensions, 
- drop all deprecated code which is not required to Sonata 3 work,

##### sonata-project/block-bundle 3.x and 4.x diff:
- change AbstractAdminBlockService  it to EditableBlockService
- drop AbstractAdminBlockService and AdminBlockServiceInterface
- close API
- add return type hints

## Conclusion:
1. block-bundle 4.x is "Sonata 4" and should not be install in any "Sonata 3" package 
1. block-bundle 3.x should be allow install in "Sonata 4"
1. block-bundle 3.x should required `core-bundle 3.x || 4.x`  to resolve extensions conflict
1. core-bundle 4.x should required extensions 1.x
1. core-bundle 4.x and block-bundle 4 should be in conflict 
1. backport extensions is propably not required

#### becouse
1. Return type hints make BC-break
1. This will allow use old block (cross install between Sonata 3 and 4 will be allow)
1. Using core-bundle 4 will allow install some Sonata 4 bundles
1. Using core-bundle 4 will allow install some Sonata 4 bundles
1. We can force user to fix own code in core-bundle MAJOR upgrade

summary:
- core-bundle 3.x - use only Sonata 3
- core-bundle 4.x - use Sonata 3 or Sonata 4
- drop core-bundle use only Sonata 4

**Comment by core23** [comment]
I'm okay with this, except some cases:

> sonata-project/core-bundle 4.x should:

* not be released

IMHO we could resolve the return type conflict by removing all return types in our *-extensions repos. And add them back with the next major version of the extensions.

**Comment by wbloszyk** [comment]
> I'm okay with this, except some cases:
> 
> > sonata-project/core-bundle 4.x should:
> 
> * not be released
> 
> IMHO we could resolve the return type conflict by removing all return types in our *-extensions repos. And add them back with the next major version of the extensions.

After remove extensions from Core and delete legacy/deprecated code only FormHelper will stay. 

WDYT about: 
- move FormHelper to form-extensions and remove it in 2.0?
- drop required core-bundle in Sonata 3 bundles and force user to install core-bundle 3 or extensions by add checking this bundles in DI

Then we dont have to resolve conflict and dont have to drop return type hints and revert API close.

**Comment by wbloszyk** [comment]
@core23 @greg0ire @VincentLanglet @phansys @javiereguiluz @franmomu @soullivaneuh 

Next proposition - change for https://github.com/sonata-project/SonataAdminBundle/issues/6016#issuecomment-612378919:

1. make core-bundle equal to to doctrine, form and twig -extensions
    - move `Sonata\CoreBundle\Form\FormHelper` to `Sonata\Form\FormHelper`
    - add aliases to service to look like service from *-extensions
1. *-extensions 1.x should be treated as "core-bundle 4.x
    - core-bundle 3.x should be equal to *-extensions 0.x
1. installing
    - naming is diffrence so we should check bundle in DI
    -  error should be throw when bundle is not installed   
1. upgrade notes in:
    - UPGRADE 1.0 in extensions
    - UPGRADE 4.0 in core-bundle
    - special upgrade notes for Sonata 3 to Sonata 4

**Comment by wbloszyk** [comment]
@core23 

Next and probably last proposition:

Relase "sonata-project/core-bundle": "allow_cross_sonata_3_and_4".
- version 4.0 will not be released
- user must upgrade own core-bundle version (simmilar to MAJOR)
- upgrade note force user to use *-extensions 1.x, not core-bundle
- hack by checking bundles in DI will not be required
- change in only one bundle is required

**Comment by wbloszyk** [comment]
@core23 I add two issues which you should see and check. This will resolve some upgrade problems.

https://github.com/sonata-project/SonataCoreBundle/issues/739 
and 
https://github.com/sonata-project/SonataBlockBundle/issues/700
