### ISSUE TITLE
Direct chat

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataAdminBundle#6022]
## Feature Request

What do You think about add direct chat? 
Storage layer should have own inteface to allow use diffrence storage type like session, file, database. It can be done by AJAX or websocket. For now I have one solution in one of my private project(base od CommentBundle). I can improve it and share.

[Some example](https://sharecodex.com/php-websocket/)

**Comment by core23** [comment]
I am a little confused. What does this have to do inside an admin backend?

**Comment by VincentLanglet** [comment]
> What does this have to do inside an admin backend?

I agree. I see no reason to add this.
And if someone does, it would be better with another repository.

**Comment by wbloszyk** [comment]
Not much but some things should be add like template support. For now user must override layout. We should allow add chat by seperate template and add it to templates config. It will not required atention on feature and allow add chat in easy way. By default this options should be empty or include only demo template.
