### ISSUE TITLE
Method getSubject, getChild, getParent, getShowFieldDescription, getFormFieldDescription, getListFieldDescription, ... should return an exception instead of null

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6035]
## Feature Request

Let's take the case of `getSubject`.

Actually the method `hasSubject` is useless because in
```
if ($this->hasSubject())) {
   $foo = $this->getSubject()
}
```
$foo is considered as `object|null` by static analysis and you have to do
```
$foo = $this->getSubject()
if (null !== foo) {
   ...
}
```

IMHO, we should always returning an object in the method `getSubject`  and throwing an exception if it's not set. Then
```
if ($this->hasSubject())) {
   $foo = $this->getSubject()
}
```
Will be the right way to do.

Same for every getter with a `has` method.

**Comment by phansys** [comment]
I agree :+1: 
We should elaborate a list with all methods that are currently in the same situation.

**Comment by VincentLanglet** [comment]
> We should elaborate a list with all methods that are currently in the same situation.

If I search for `hasFoo` method, there is

AbstractAdmin 
- hasChildren => maybe getCurrentChildAdmin ?
- ~~hasAccess => nothing to do~~

AdminInterface + AbstractAdmin
- ~~hasRoute => There is no getter~~
- ~~hasRequest => getRequest already throw an exception~~
- hasParentFieldDescription => getParentFieldDescription 
- hasListFieldDescription => getListFieldDescription
- ~~hasSubClass => getSubClass already throw an exception~~
- ~~hasActiveSubClass => getActiveSubClass will be good in next major~~
- hasSubject => getSubject ; Careful, `hasSubject` actually use `getSubject`.

FieldDescriptionRegistryInterface + AbstractAdmin
- hasFormFieldDescription => getFormFieldDescription
- hasShowFieldDescription => getShowFieldDescription
- hasFilterFieldDescription => getFilterFieldDescription

ParentInterface + AbstractAdmin
- hasChild => getChild
- Maybe adding hasChildren/getCurrentChildAdmin in the interface ?

BaseFieldDescription
- hasAssociationAdmin => getAssociationAdmin
- hasCachedFieldGetter => don't know

Pool 
- ~~hasGroup => getAdminsByGroup throw already an exception~~ => Maybe we should rename hasGroup to hasAdminByGroup.
- hasAdminByClass => getAdminByClass
- hasAdminByAdminCode => getAdminByAdminCode

DatagridInterface/Datagrid
- ~~hasFilter => getFilter will be ok in next major~~
- ~~hasActiveFilters/hasDisplayableFilters => nothing to do~~

BaseGroupMapper
- ~~hasOpenTab => has no getter related~~

AuditManager/AuditManagerInterface
- ~~hasReader => getReader throw already an exception~~

DefaultRouteGenerator
- ~~hasAdminRoute => no getter related~~

TemplateRegistry
- ~~hasTemplate => getTemplate will be ok in next major~~

**Comment by phansys** [comment]
Related to #4905.

**Comment by VincentLanglet** [comment]
@phansys Currently it's already implemented for some functions, but I'm not fully satisfy: let's take `request` as example.

The following code should be correct.
```
if ($this->hasRequest) {
    $r = $this->getRequest();
}
```

In this example $this->getRequest throw an exception if there is no $request or return the $request. So static analysis know that `$r !== null`.

But when you're using static analysis which are checking you're catching every possible exception, the tool is asking to catch the `RuntimeException` thrown. But there won't be an exception thrown in this case...

In general, there is a configuration in order to ignore some exceptions, most of the time people are ignoring `LogicException` or some custom exceptions. So IMHO, we should
- 1) either throw a `LogicException` 
- 2) either throw a custom exception extending `LogicException`
- 3) either throw a custom exception extending `RuntimeException`.

WDYT ? I would say choice 3 but i'm not sure ^^'

**Comment by phansys** [comment]
IMO, this exception should not be considered a "runtime" exception, but a "logic" exception like you're proposing. 
Conceptually speaking, I think runtime exceptions should be built on top of these (bubbling up) exceptions, and they should be thrown when we are sure about the scenario was reached by an unexpected usage (mean, the interaction with application or its configuration or input parameters in general).
About a native or a domain exception, I haven't a strong position, but I think we could start by a native approach in order to make the process easier. Then, if we identify the need for a domain exception, we could create our own exception set.

**Comment by phansys** [comment]
We should add `hasParent()` (see #6007).

**Comment by VincentLanglet** [comment]
> IMO, this exception should not be considered a "runtime" exception, but a "logic" exception like you're proposing.

Indeed, I searched for similar pattern in symfony, and they usually throw a `LogicException` or a an exception extending the `LogicException`, like `BadMethodCallException`.

I can't  be without a BC-break for method which already throw an exception then.

**Comment by VincentLanglet** [comment]
> We should add `hasParent()` (see #6007).

There is a method `isChild()`

**Comment by VincentLanglet** [comment]
> If I search for `hasFoo` method, there is
> 
> AbstractAdmin
> 
> * hasChildren => maybe getCurrentChildAdmin ?
> * ~hasAccess => nothing to do~
> 
> AdminInterface + AbstractAdmin
> 
> * ~isChild => getParent~
> * ~hasRoute => There is no getter~
> * ~hasRequest => getRequest already throw an exception but it's a Runtime~
> * ~hasParentFieldDescription => getParentFieldDescription~
> * ~hasListFieldDescription => getListFieldDescription~ 
> * ~hasSubClass => getSubClass already throw an exception~
> * ~hasActiveSubClass => getActiveSubClass will be good in next major~
> * ~hasSubject => getSubject ; Careful, `hasSubject` actually use `getSubject`.~
> 
> FieldDescriptionRegistryInterface + AbstractAdmin
> 
> * hasFormFieldDescription => getFormFieldDescription
> * hasShowFieldDescription => getShowFieldDescription
> * hasFilterFieldDescription => getFilterFieldDescription
> 
> ParentInterface + AbstractAdmin
> 
> * hasChild => getChild
> * Maybe adding hasChildren/getCurrentChildAdmin in the interface ?
> 
> BaseFieldDescription
> 
> * hasAssociationAdmin => getAssociationAdmin
> * hasCachedFieldGetter => don't know
> 
> Pool
> 
> * ~hasGroup => getAdminsByGroup throw already an exception~ => Maybe we should rename hasGroup to hasAdminByGroup.
> * hasAdminByClass => getAdminByClass
> * hasAdminByAdminCode => getAdminByAdminCode
> 
> DatagridInterface/Datagrid
> 
> * ~hasFilter => getFilter will be ok in next major~
> * ~hasActiveFilters/hasDisplayableFilters => nothing to do~
> 
> BaseGroupMapper
> 
> * ~hasOpenTab => has no getter related~
> 
> AuditManager/AuditManagerInterface
> 
> * ~hasReader => getReader throw already an exception~
> 
> DefaultRouteGenerator
> 
> * ~hasAdminRoute => no getter related~
> 
> TemplateRegistry
> 
> * ~hasTemplate => getTemplate will be ok in next major~

Update since https://github.com/sonata-project/SonataAdminBundle/pull/6050
