### ISSUE TITLE
resetDQLPart('orderBy') in ProxyQuery prevent sorting using orderBy in queryBuilder custom queries

### ISSUE THREAD

**Issue by JSSOLDIER** [sonata-project/SonataAdminBundle#6065]
If we try to sort using the QueryBuilder "orderBy" function, the sorting will not pass and the orderBy DQL section will be removed in the ProxyQuery "execute" function in line 134. 
I suggest adding a function to "Lock" the DQL parts so that the $queryBuilder->resetDQLPart('orderBy'); will not be executed if the orderBy part is locked.

**Comment by VincentLanglet** [comment]
Please respect the ISSUE_TEMPLATE.

Which SonataAdmin version ? Which Sonata package ?
The ProxyQuery is an Interface: `ProxyQueryInterface`.
There is no ProxyQuery, no line 134.

This not a SonataAdminBundle issue.
And for exemple this ProxyQuery https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Datagrid/ProxyQuery.php#L169 works correctly.

You dont give any example to reproduce the error.

Without any correct information about this possible bug, the issue will certainly be close.
