### ISSUE TITLE
Test AdminMakerTest broken

### ISSUE THREAD

**Issue by peter-gribanov** [sonata-project/SonataAdminBundle#6084]
After update `symfony/maker-bundle` v1.14.6 to v1.16.0 the [test](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/tests/Maker/AdminMakerTest.php#L93) of `AdminMaker` was broken because changed [API](https://github.com/sonata-project/SonataAdminBundle/blob/3.x/tests/Maker/AdminMakerTest.php#L126) of `Symfony\Bundle\MakerBundle\FileManager` in https://github.com/symfony/maker-bundle/pull/559.

Failed build:
https://travis-ci.org/github/sonata-project/SonataAdminBundle/jobs/683856722

**Comment by phansys** [comment]
I confirm the issue @peter-gribanov.
Even, the dependency isn't part of the common requirements (it's listed in `require-dev`).
The API change is expected since that class is marked as internal.

**Comment by franmomu** [comment]
I remember giving it a try using [MakerTestCase](https://github.com/symfony/maker-bundle/blob/master/src/Test/MakerTestCase.php), [here](https://github.com/symfony/maker-bundle/tree/master/tests/Maker) are some examples if someone wants to try.

**Comment by VincentLanglet** [comment]
I made a quick fix here: https://github.com/sonata-project/SonataAdminBundle/pull/6087

But re-writing the test without using internal classes could be great.
