### ISSUE TITLE
Improve make:sonata:admin command with model class autocomplete.

### ISSUE THREAD

**Issue by osavchenko** [sonata-project/SonataAdminBundle#6091]
## Feature Request

I think that it will be helpful to build autocomplete for a model class name like for command `make:entity`.

I plan to implement it soon. Maybe someone have ideas how to improve this autocomplete?

**Comment by VincentLanglet** [comment]
Hi @osavchenko, you said you plan to implement it. Did you start something ? :)

**Comment by osavchenko** [comment]
@VincentLanglet yes, I have stared, but I think that I overthink this feature :D
If we check any file of the project to build autocomplete it can decrease performance and it would be good to restrict folders to search. It can be `Entity`, `Document`, `Model`, for example, but will it be enough?

**Comment by VincentLanglet** [comment]
Technically, entities could be created anywhere isn't it ?
And for instance, I have classes in my Entity folder which are not real entities and shouldn't be in the autocomplete.
Finding the entities of the project seems to be something persistence-bundle-specific.

Not sure there is an easy way to do this.

**Comment by osavchenko** [comment]
Out of the box SonataAdmin uses `orm` and `odm` `manager_type` for admins. And, as far as I know, it can't be used without manager, right?
We can create list of entities/documents based on [this implementation](https://github.com/symfony/maker-bundle/blob/main/src/Doctrine/DoctrineHelper.php) and it should cover a lot of usecases and at least it's more than nothing. But in this case we shold put question "The model manager type" before "The fully qualified model class".

Scan all project files (include vendor directory) and extract all PHP classes from them (with tokens or regular expressions) takes a lot of time and depends on the developer hardware a lot. On my laptop with docker on pure symfony installation it took ~10 seconds just to scan all files and extract PHP files. It's too much time on my optinion.

**Comment by VincentLanglet** [comment]
Seems nice

**Comment by VincentLanglet** [comment]
> Out of the box SonataAdmin uses `orm` and `odm` `manager_type` for admins. And, as far as I know, it can't be used without manager, right?
> We can create list of entities/documents based on [this implementation](https://github.com/symfony/maker-bundle/blob/main/src/Doctrine/DoctrineHelper.php) and it should cover a lot of usecases and at least it's more than nothing. But in this case we shold put question "The model manager type" before "The fully qualified model class".

Did you have time to make a try ?

**Comment by osavchenko** [comment]
Yes, but didn't finish it yet. I tried to reuse that class as it is and it works well for `orm` but needs additional work for `odm`.

**Comment by VincentLanglet** [comment]
> Yes, but didn't finish it yet. I tried to reuse that class as it is and it works well for `orm` but needs additional work for `odm`.

You can open a draft PR if you want some help ;)
