### ISSUE TITLE
Ckeditor doesnt render inside CollectionType in sonata admin

### ISSUE THREAD

**Issue by SylvanoTombo** [sonata-project/SonataAdminBundle#6101]
Ckeditor doesn't render when inside CollectionType and 'edit' => 'inline' but when make 'inline' => 'table' it appear in sonata admin.

No js error seen in the console.

**Comment by VincentLanglet** [comment]
Please fill the template when opening an issue.
Libraries ? Version used ?
Code ? Minimal repository with the bug ?

The best you explain the issue and you give a way to reproduce it, the more chance you have that someone gonna fix it.

**Comment by SylvanoTombo** [comment]
### Environment
Symfony version: 4.4

#### Sonata packages
"sonata-project/admin-bundle": "^3.61"

#### PHP version
7.2.28

## Subject
Ckeditor doesn't render when inside CollectionType and 'edit' => 'inline' but when make 'inline' => 'table' it appear in sonata admin.

No js error seen in the console.

## Steps to reproduce
I have a ParentEntity with ParentEntityAdmin who embed a ChildEntityAdmin,
In ChildEntityAdmin, i have a field description with type of CKEditorType..
In ParentEntityAdmin i have a CollectionType who embed ChildEntityAdmin..

In ChildEntityAdmin, the ckeditorType work, but in ParentEntityAdmin inside CollectionType the ckeditor doesnt render and not focusable.

Thanks

**Comment by VincentLanglet** [comment]
I would say that it half-works 😅

I tried 
```
->add('children', CollectionType::class, ['by_reference' => false], [
   'edit'   => 'inline',
])
```

And the CKEditor field is like this
![image](https://user-images.githubusercontent.com/9052536/82727720-82450e00-9cec-11ea-914f-a96a1ce3fe02.png)

But when I click on it, I get
![image](https://user-images.githubusercontent.com/9052536/82727691-59247d80-9cec-11ea-970c-e8da7df8e8a1.png)

Do you have the same thing ?

**Comment by VincentLanglet** [comment]
Removing this line
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/Association/edit_one_to_many_inline_tabs.html.twig#L42

Give the following render
![image](https://user-images.githubusercontent.com/9052536/82728062-66db0280-9cee-11ea-805c-0a3bd8632e4f.png)

But I don't know if there is others impacts.

If this is the right fix, it has to be done here too
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/Association/edit_many_to_many.html.twig#L68

**Comment by SylvanoTombo** [comment]
Thanks for your response.. how i can override the template?

**Comment by SylvanoTombo** [comment]
Another issue, when you sort the collection the ckeditor is no longer editable. Do you have similar issue?

**Comment by VincentLanglet** [comment]
> Thanks for your response.. how i can override the template?

By following the documentation.

> Another issue, when you sort the collection the ckeditor is no longer editable. Do you have similar issue?

Yes I can reproduce the issue.
I would recommend to create one issue for each problem. 

And when you'll open it, be more explicit when you describe the problem, with bundle versions and code to reproduce the issue.

You can even debug the issue. Open your vendor, edit some files and see what happens. This is how I did for fixing this issue. You should look into the JS of Sonata and CKeditor. Maybe some of CKeditor JS should be executed again when you sort. Or maybe The sonata JS isn't rebuilding the field correctly.

**Comment by SylvanoTombo** [comment]
Ok..Thank you
