### ISSUE TITLE
Overriding AbstractAdmin

### ISSUE THREAD

**Issue by grekpg** [sonata-project/SonataAdminBundle#6105]
## Feature Request

I'm trying to override AbstractAdmin method buildList 

- id add if $this->getRequest()->isXmlHttpRequest()) {

field select  I don't want it - I'm using ajax loading panels so ajax != select mode. 

1 Please don't use private vars like private $list; 

2 I think is good add list mode (dialog select) not switch list mode if it's ajax request.

**Comment by VincentLanglet** [comment]
> I'm trying to override AbstractAdmin method buildList
> 
> * id add if $this->getRequest()->isXmlHttpRequest()) {
> 
> field select I don't want it - I'm using ajax loading panels so ajax != select mode.
>
> I think is good add list mode (dialog select) not switch list mode if it's ajax request.

Please give more explanation about the code/behaviour you want to changes.
I understood nothing.

> 1 Please don't use private vars like private $list;

There will be more private vars and final method in next major.
This allow the library to add feature and change behaviour more easily without breaking changes.

A good reason is needed for not using private vars or final methods.

Protected method can be added to override some specific behaviour or check.
If you want to change something like 
```
if ($this->hasRequest() && $this->getRequest()->isXmlHttpRequest()) {
```
It could be refactor to
```
if ($this->shouldDoSomething()) {
```

**Comment by grekpg** [comment]
Other example I try to add second form - totally different of edit , (but want use sonata form inputs)
I duplicate editAction I admin CrudController 
everything will be easy I can use helpers like 

 $this->handleXmlHttpRequestErrorResponse
this->handleXmlHttpRequestSuccessResponse and many more - but it is private why ?

I know what I'm doing but have unnecessary difficulties like private methods.

**Comment by wbloszyk** [comment]
Simmilar or mybe even this probem was discouse in some issue, probably in dev-kit. AbstactAdmin and CRUDController should be split to more atomic service. At first close API and add type hints must be add, than work on this will be start. It is milestone on Sonata 5, but work on this will start in 4.

For now you can copy private properties and methods or write own code.

**Comment by grekpg** [comment]
Ok, thanks

**Comment by VincentLanglet** [comment]
> I know what I'm doing 

We know what we're doing too.

> but have unnecessary difficulties like private methods. I think private change nothing in "more easily without breaking changes".

We have unnecessary difficulties to add feature/bugfix/release new version because everything is theorically overridable by user but most of the time nobody override it. That's why we'll work with private property and final class/method. If some override is needed, we can still expose some protected methods.

> You can break compatibility but allow us override methods - private is unnecessary problem for us.

As I already said, if you really need to override something, make a PR to expose a new protected method.

If you want to change something like 
```
if ($this->hasRequest() && $this->getRequest()->isXmlHttpRequest()) {
```
 
It could be refactor to
```
if ($this->shouldDoSomething()) {
```

PR are always available.
