### ISSUE TITLE
side_bar_before_nav and side_bar_after_nav

### ISSUE THREAD

**Issue by brunovila** [sonata-project/SonataAdminBundle#6107]
I can override sonata admin dashboard.html to show something in the top or/and bottom of sidebar.
I did it overriding _side_bar_before_nav_ and _side_bar_after_nav_ blocks, and it work fine in the main page of dashboard (when the dashboard route appears in the URL of my browser)

But, for example, when I am editing a product, that content is not shown.  How can I shot those blocks allways?

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
