### ISSUE TITLE
Support doctrine/common 3

### ISSUE THREAD

**Issue by jaikdean** [sonata-project/SonataAdminBundle#6121]
## Feature Request

`doctrine/common` 3.0.0 has been released with a sensible upgrade path. The [release notes](https://github.com/doctrine/common/releases/tag/3.0.0) suggest it's easy to support both 2.x and 3.0.

**Comment by greg0ire** [comment]
Looks like we depend on it for 3 packages: https://packagist.org/packages/doctrine/common/dependents?order_by=name&page=77

**Comment by core23** [comment]
Can you try to make a PR @jaikdean ?
