### ISSUE TITLE
Can not install on fresh Symfony 4.4.99

### ISSUE THREAD

**Issue by Helrunar** [sonata-project/SonataAdminBundle#6122]
### Environment
Win10, WSL, PHP 7.4 fpm

## Subject

Try to install Sonata Admin Bundle on a fresh Symfony 4.4.99

## Steps to reproduce
composer create-project symfony/website-skeleton:4.4.* 
composer require sonata-project/admin-bundle

## Actual results
![image](https://user-images.githubusercontent.com/428549/83246157-02162100-a1a2-11ea-98e7-3e26122f68bd.png)

**Comment by wbloszyk** [comment]
@Helrunar  `sonata-project/admin-bundle` do not support `twig/twig 3.x`.

To resolve this make this commands:
```
composer create-project symfony/website-skeleton:4.4.*
composer require sonata-project/admin-bundle --no-update
composer update
```

**Comment by Helrunar** [comment]
Thanks, working fine
