### ISSUE TITLE
[Doc] - Example on sort by mulitple fields

### ISSUE THREAD

**Issue by manu-sparheld** [sonata-project/SonataAdminBundle#6129]
Hi

Here : https://sonata-project.org/bundles/admin/master/doc/reference/action_list.html#customizing-the-query-used-to-generate-the-list

it says: `Note TODO: how to sort by multiple fields (this might be a separate recipe?)`

Is it possible to get a sample code in documentation about it? or may be just a link there if it exists in documentation already.

Thanks

**Comment by VincentLanglet** [comment]
Sure ! I will.
We also need to update the doc in favor of getDefaultSortValues() methods instead of $datagridValues.

**Comment by manu-sparheld** [comment]
@VincentLanglet Thanks so much.

**Comment by VincentLanglet** [comment]
@manu-sparheld I you want look at https://github.com/sonata-project/SonataAdminBundle/pull/6131
