### ISSUE TITLE
Default filter "hidden by default" are not UI friendly and are currently buggy.

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6137]
Currently, when we use `configureDefaultFilterValues` this way
```
protected function configureDefaultFilterValues(array &$filterValues)
{
    $filterValues['foo'] = [
        'type'  => EqualType::TYPE_IS_EQUAL,
        'value' => 1,
    ];
}
```

- The list is filtered with `foo = 1`, but the filter is not displayed.
- The checkbox is checked because of https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/base_list.html.twig#L251 (this is a bug which can be easily fixed).

But:
- If I filter with `foo = 2`, the filter is now displayed.
- If I filter again with `foo = 1` the filter is not displayed anymore.
- If I reset the filter, the filter won't be applied and is not displayed.

When the filter is not displayed I can't know if the filter is not applied or if it's applied with the default value !

And if I set the option `show_filter => true` to my filter, it's still not displayed because of the default value !

IMHO something like an hidden filter is a bad idea. Mainly for UI reason.
A feature for adding default filters is nice, but every applied filters should be displayed to the user.

Plus it add consistency with others methods.
For example, when I used `configureSortDefaultValue`, the sort_by and the sort_order are displayed in the datagrid, they are not hidden.

IMHO The method `isDefaultFilter` should be deprecated and not be used in the template to hide the filters.

Related to https://github.com/sonata-project/SonataAdminBundle/pull/5745 

CC @core23 @sonata-project/contributors

**Comment by jorrit** [comment]
I think there should be a tri-state value for the active property of a filter: inactive, active, default.

Effects:

* inactive: no check and no form
* active: check and form
* default: check and no form

Logic:

* inactive: not present in query string, no default value
* active: present in query string (even when same as default value)
* default: not present in query string, has default value

This logic must be programmed in both JS and PHP.

An enhancement to the filter system would be a 'Reset to defaults' button on the bottom or top of the checkboxes dropdown menu.
