### ISSUE TITLE
X-editable vendor is not maintained 

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6147]
The live-edit function is based on the `x-editable` vendor 
https://github.com/sonata-project/SonataAdminBundle/tree/3.x/src/Resources/public/vendor/x-editable

This library is not maintained anymore, the last commit was made in march 2019.
https://github.com/vitalets/x-editable#project-status

Moreover this library seems to not support bootstrap 4.
https://github.com/vitalets/x-editable/issues/1159

We will maybe have to deprecate the live-edit function and remove it.

WDYT @sonata-project/contributors ?

**Comment by core23** [comment]
Is there any alternative / fork of lib? 

👎 for removing this feature.

**Comment by jordisala1991** [comment]
I did a search and there was not an obvious alternative, we might need to take a deeper look, -1 to remove this feature too.

**Comment by VincentLanglet** [comment]
There is no vote.
Nobody will vote +1 to remove a feature.

The real question is do we have an alternative if nobody maintained the project ?
https://github.com/vitalets/x-editable/issues/610

**Comment by wbloszyk** [comment]
We have alternative!!!

For now SonataAdminBundle is administration panel. Mybe we should start thinking diffrence? For me it is powerfull tools for generating CRUD. AbstractAdmin is big monolit what do not allow use this tools as much as they can be. 

Back to subject. SonataAdminBundle have modal form (for create or edit object by AdminModelType). Create something simmilar is possible.

**Comment by VincentLanglet** [comment]
Closing in favor of https://github.com/sonata-project/SonataAdminBundle/issues/7156
