### ISSUE TITLE
Add BackwardCompatibilityCheck to CI

### ISSUE THREAD

**Issue by vladyslavstartsev** [sonata-project/SonataAdminBundle#6164]
## Feature Request
During discussion of following PR
https://github.com/sonata-project/SonataAdminBundle/pull/6161#discussion_r443845687
We have noticed that it will be useful to check for BC on CI level

https://github.com/Roave/BackwardCompatibilityCheck

**Comment by core23** [comment]
Can you provide a PR @vladyslavstartsev ?

**Comment by vladyslavstartsev** [comment]
No, too much work before new year. Only after it.
