### ISSUE TITLE
Add child object

### ISSUE THREAD

**Issue by kirya-dev** [sonata-project/SonataAdminBundle#6181]
Hello!
Im using AdminBundle 3.49 and im get error when AbsractAdmin set parent association for new child object.

Bug accures when getter of parent object defenied as

```PHP
/**
* @ORM\Entity()
*/
class Item {
    /** @var Order */
    private $order;

    public function getOrder(): Order
    {
        return $this->order;
    }
}
```
Get error that getOrder must return not null object

Im found that breaks in source code of **\Sonata\AdminBundle\Admin\AbstractAdmin::buildForm**
This code not modified 4 years. Also exists following todos in this method:
_todo : clean the way the Admin class can retrieve set the object_

PS. im confused

PS PS
my suggest replace:
```PHP
            $value = $propertyAccessor->getValue($object, $propertyPath);

            if (\is_array($value) || $value instanceof \ArrayAccess) {
                $value[] = $parent;
                $propertyAccessor->setValue($object, $propertyPath, $value);
            } else {
                $propertyAccessor->setValue($object, $propertyPath, $parent);
            }
```
by this:
```PHP
            $propertyAccessor->setValue($object, $propertyPath, $parent);
```
Im understand that lose case `\is_array($value) || $value instanceof \ArrayAccess`. Please explain cases when it must be use?

**Comment by kirya-dev** [comment]
Im assume getValue() need for determine ManyToMany relation?

**Comment by VincentLanglet** [comment]
The issue is in your code.

Does `getOrder` can return `null` ? Yes, since there is no default value provided in the constructor
If in your code you're writing
```
$item = new Item();
$order = $item->getOrder();
```
`$order` will be `null`

So you should update your typehint.
```
/**
* @ORM\Entity()
*/
class Item {
    /** @var Order|null */
    private $order;

    public function getOrder(): ?Order
    {
        return $this->order;
    }
}
```

See, example in symfony/demo: https://github.com/symfony/demo/blob/master/src/Entity/Post.php#L178

**Comment by kirya-dev** [comment]
`$order will be null` why? Entity says that $order not null

**Comment by wbloszyk** [comment]
By default child object should not be created. It is additional data which should not be autogenerated. People should write code for create it by self. Why? Becouse $order could have special fields like number, status etc. You can create this child by override one of methods `getNewInstance`, `prePersist`, preUpdate`.

**Comment by VincentLanglet** [comment]
> `$order will be null` why? Entity says that $order not null

But your entity is wrong. When an entity is created every property is null if you don't set them in the constructor.

Did you try to write the following code ?
```
$item = new Item();
$order = $item->getOrder();
```

**Comment by kirya-dev** [comment]
Ok.
What if pass parent object into constructor of child object automatically?

**Comment by VincentLanglet** [comment]
Currently getNewInstance is written this way.
```
public function getNewInstance()
{
    $object = $this->getModelManager()->getModelInstance($this->getClass());
    foreach ($this->getExtensions() as $extension) {
        $extension->alterNewInstance($this, $object);
    }

    return $object;
}
```
And `getModelInstance` create the instance without calling the constructor if there are required parameters.

So It's currently not fully supported. You'll have to try https://sonata-project.org/bundles/admin/3-x/doc/cookbook/recipe_data_mapper.html.

The easier way would just to update the return type.

**Comment by kirya-dev** [comment]
To many code for simple things :-1:

**Comment by VincentLanglet** [comment]
> To many code for simple things 👎

This is fully related to the fact your entity is wrongly written and typehinted.

Both
```
/**
* @ORM\Entity()
*/
class Item {
    /** @var Order */
    private $order;

    public function __constructor()
    {
        $this->order = new Order();
    }

    public function getOrder(): Order
    {
        return $this->order;
    }
}
```
And
```
/**
* @ORM\Entity()
*/
class Item {
    /** @var Order|null */
    private $order;
    public function getOrder(): ?Order
    {
        return $this->order;
    }
}
```

**Comment by kirya-dev** [comment]
Without setOrder admin crush
