### ISSUE TITLE
[Documentation] Form type in Datepicker

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataAdminBundle#6182]
Hi there,

I was trying to configuration date picker in my project, and always I found stuffs saying to use `SonataCoreBundle` But it's deprecated...

I think this [doc](https://sonata-project.org/bundles/core/3-x/doc/reference/form_types.html#datepickertype-datetimepickertype) need to be changed

from `@SonataCore/Form/datepicker.html.twig` to `@SonataForm/Form/datepicker.html.twig`

But I don't know where I can open a MR to this page.

**Comment by jordisala1991** [comment]
Those docs should be deprecated indeed, and they should be moved to a new place for the SonataFormBundle. This could also apply to SonataTwigBundle and SonataDoctrineExtensions.

All the docs are on the github repositories for each package/ project. 

Do you want to help moving this forward?

**Comment by eerison** [comment]
Yes, I'll do :)

**Comment by eerison** [comment]
Hi @jordisala1991 sorry for don't open PR I forgot this one :( 

But I tried to open this, But it's right in https://github.com/sonata-project/form-extensions/blob/master/docs/reference/form_types.rst#datepickertype--datetimepickertype But why it's different here https://sonata-project.org/bundles/core/3-x/doc/reference/form_types.html#datepickertype-datetimepickertype :confused:

**Comment by VincentLanglet** [comment]
This is not the same thing !

The second url, talk about `core` project
The first one talk about form-extension. 

To see updated information should go to the form-extension website. But it doesn't work currently, see https://github.com/sonata-project/form-extensions/issues/84

So I think we can close this issue.
