### ISSUE TITLE
Remove oppressive words from code

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#6185]
## Feature Request

We should avoid terms like *blacklist*, *whitliste*, *master*, *slave*, ... and use more tech-related words like *blocklist*, *prmary*, *secondary*,...

In this repo, we use the term *whitelist* which could be replaced with *allowlist*:
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/docs/reference/routing.rst#removing-all-routes-except-named-ones

**Comment by tomol1111** [comment]
And we must remeber about remove all white and black colors from CSS ... :facepalm: 
Ohh .. and we can't drink coffee 'cos can be white or black.

**Comment by core23** [comment]
> And we must remeber about remove all white and black colors from CSS ... 🤦
> Ohh .. and we can't drink coffee 'cos can be white or black.

Thank's for your contribution. Feel free to use other projects if you don't like an open world
