### ISSUE TITLE
SonataAdmin: How to customize editable datepicker in List View

### ISSUE THREAD

**Issue by aleksano** [sonata-project/SonataAdminBundle#6188]
Hi!
I looked through the manuals and searched the internet, but I did not find a guide to customize the popuped datepicker window for editable data field in list view.

My questions are:
1) How to set language for popuped datepicker window?
2) How to set a calendar on specific date (not current)?

Details: https://groups.google.com/d/msg/sonata-users/lqaNcqXjPA8/YuAo0FrRAgAJ

Thanks

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
