### ISSUE TITLE
AdminExtractor should set subject

### ISSUE THREAD

**Issue by jorrit** [sonata-project/SonataAdminBundle#6221]
After #6040 was added commands like `php bin/console debug:translation` execute methods on Admin class instances to extract translatable strings.

One of the methods is `getForm`, which calls `configureFormFields`. To tailor my forms I access `$this->getSubject()` in several of these methods. I hope this is not unusual or against best practices.

When the AdminExtractor calls `getForm()` no subject is present.

Perhaps the following can be added to AdminExtractor to make sure a basic model is present:

```php
$admin->setSubject($admin->getNewInstance());
```

Or am I missing something?

**Comment by VincentLanglet** [comment]
I agree, for instance, in RetrieveAutocompleteItemsAction:
```
// subject will be empty to avoid unnecessary database requests and keep autocomplete function fast
$admin->setSubject($admin->getNewInstance());
```

Do you want to make the PR @jorrit ?
