### ISSUE TITLE
[NEXT_MAJOR] Remove `AbstractAdmin::validate` method and all validation-related methods.

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6233]
As explained in the AdminInterface, the `validate` method doesn't work well (we have bug issue) and is useless since Symfony have his own form validation.
```
    /**
     * NEXT_MAJOR: remove this method.
     *
     * @param object $object
     *
     * @deprecated this feature cannot be stable, use a custom validator,
     *             the feature will be removed with Symfony 2.2
     */
    public function validate(ErrorElement $errorElement, $object);
```

I create this issue because we only added one `NEXT_MAJOR` comment but there is no real removal-plan, we'll have at least to:
- remove AbstractAdmin::attachInlineValidator.
- remove AbstractAdmin::validate.
- remove AbstractAdminExtension::validate.
- remove AdminExtensionInterface::validate.
- update the UPGRADE.md file.

We should also add a deprecation in 3.x.

**Comment by tambait** [comment]
@VincentLanglet When listed methods are removed, is there anything more to be done (for example is there need to add Symfony's `ValidatorInterface` somewhere)? I tried to search to see where validate method is called throughout the code, `SetObjectFieldValueAction` uses `ValidatorInterface` and the rest is in the list you provided

**Comment by VincentLanglet** [comment]
> @VincentLanglet When listed methods are removed, is there anything more to be done (for example is there need to add Symfony's `ValidatorInterface` somewhere)? I tried to search to see where validate methods are called throughout the code, `SetObjectFieldValueAction` uses `ValidatorInterface` and the rest is in the list you provided.

We want to remove all the `validation` features from the Admin, so there is nothing to add.

I look at `SetObjectFieldValueAction` and we should keep it.

So it require to add in 3.x
```
/**
 * NEXT_MAJOR: Remove this methods.
 *
 * @deprecated since sonata-admin/admin-bundle 3.x
 */
```
In the interface for all the validate-related methods,  with an upgrade note and to remove all these methods in master.

**Comment by tambait** [comment]
And what about `defineFormBuilder` method in `AbstractAdmin` it calls `attachInlineValidator`? I'll remove that line but not sure if any additional action is needed.

**Comment by VincentLanglet** [comment]
Only the call `$this->attachInlineValidator();` should be removed in `defineFormBuilder`
