### ISSUE TITLE
Filter objects should provide a way to be built with a proper state

### ISSUE THREAD

**Issue by phansys** [sonata-project/SonataAdminBundle#6268]
## Feature Request

Since there is a specific state required for the filter objects (the classes implementing `Sonata\AdminBundle\Filter\FilterInterface`) to work, we should provide a way to ensure their state is ready to use, at least in our own implementation.
I think we have 2 choices:
1. Add a `__construct()` method at `Sonata\AdminBundle\Filter\Filter` and set the required state there;
2. Transform `Sonata\AdminBundle\Filter\Filter::initialize()` method into a singleton and set the required state there.

This feature request is created to avoid situations like the exposed in [this comment](https://github.com/sonata-project/SonataAdminBundle/pull/6259/files#r467570293).

**TO DO**:
- [ ] Decide what option we should adopt.

**Comment by VincentLanglet** [comment]
Should we add the 4.0 milestone ?

**Comment by phansys** [comment]
I think we could provide some of the required changes from 3.x.

**Comment by VincentLanglet** [comment]
The FilterFactory is doing:
```
public function create(string $name, string $type, array $options = []): FilterInterface
    {
        if (!$this->container->has($type)) {
            throw new \RuntimeException(sprintf('No attached service to type named `%s`', $type));
        }

        $filter = $this->container->get($type);

        if (!$filter instanceof FilterInterface) {
            throw new \RuntimeException(sprintf('The service `%s` must implement `FilterInterface`', $type));
        }

        $filter->initialize($name, $options);

        return $filter;
    }
```

How do you want to use the construct instead ?

And how would work a singleton ?

**Comment by VincentLanglet** [comment]
Friendly ping @phansys 

Can you detail the two choices you gave ?
Currently the initialize method is used here:
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Filter/FilterFactory.php#L33-L48

To me constructor cannot be used since we're loading the filter as a service in the container (because it can depends on some others services). And I dunno what you had in mind by `initialize as a singleton`.

**Comment by VincentLanglet** [comment]
Closing due to lack of interest
