### ISSUE TITLE
FieldDescriptionInterface should not expose getParentAssociationMappings and getAssociationMappings methods or there should stop returning an array

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6274]
## Feature Request

Currently FieldDescriptionInterface::parentAssociationMappings() and associationMappings() methods are returning array.

Thanks to https://github.com/sonata-project/SonataAdminBundle/pull/6219#issuecomment-671688958, I discovered that the array keys are not the same for our different storage bundle. This means that these array should not be used in SonataAdminBundle.

I found two solutions
- Exposing some methods like getParentAssociationFieldName(), getAssociationFieldName(), ... instead.
- Exposing a new AssociationMapping interface, which will be implemented by storage bundle. And getParentAssociationMappings/getAssociationMappings should return this interface instead.

The second solution seems better, but this can't be done in a BC-way isn't it ? @sonata-project/contributors

**Comment by kirya-dev** [comment]
Hello!
First of all needs define global difference between `getParentAssociationFieldName()`
 & `getAssociationFieldName()`.

Maybe second metod name must be `getChildAssociationFieldName()`?

P.S. Im my opinion using array as return value no good practice - we can get any structed data

**Comment by VincentLanglet** [comment]
I think the easier would be to introduce a class
```
class Mapping extends ArrayAccess
```
with a `getFieldName` method and a `getOption` one.

I let https://github.com/sonata-project/SonataAdminBundle/pull/7677 as an example

**Comment by VincentLanglet** [comment]
Closing due to lack of interest
