### ISSUE TITLE
Revision/Audit features are too much related to EntityAuditBundle.

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6279]
## Feature Request

Related to https://github.com/sonata-project/SonataAdminBundle/pull/6261#discussion_r468524145

AuditReaderInterface has methods returning `object`, but we're using these object like it was a `Revision` from the EntityAuditBundle https://github.com/simplethings/EntityAuditBundle/blob/master/src/SimpleThings/EntityAudit/Revision.php

https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/views/CRUD/base_history.html.twig

We should instead create our own `Revision` class, the storage bundle will then return a SonataRevision instead of the current one.

**Comment by kirya-dev** [comment]
It seems that EntityAuditBundle is abounded. Need alternative way.
Also EntityAuditBundle trigger deprecated error when add column to audit table(Not compatible changes with DBAL 3.0). And ignore columns dont not work.
To many problems with abounded project. It 100% go away from this repo and use yourself fork?

**Comment by phansys** [comment]
About the columns not being ignored, see simplethings/EntityAuditBundle#329.

**Comment by kirya-dev** [comment]
> Create our own Revision interface.

What kind class must implements interface?

**Comment by VincentLanglet** [comment]
> > Create our own Revision interface.
> 
> What kind class must implements interface?

The AuditReaderInterface (https://github.com/sonata-project/SonataAdminBundle/blob/master/src/Model/AuditReaderInterface.php) should methods returning `Revision` or `Revision[]` instead of `object` and `object[]`.
