### ISSUE TITLE
Annotation mismatch with modifier

### ISSUE THREAD

**Issue by kirya-dev** [sonata-project/SonataAdminBundle#6314]
**SonataAdminBindle 3.74**

if search next string in admin bundle `@final since sonata-project/admin-bundle 3.` (any past version) we can see that methods and classes does not have final modifiers.

For example 
https://github.com/sonata-project/SonataAdminBundle/blob/d0faf8a2123876f41ac225580044877dcffd3092/src/Admin/AbstractAdmin.php#L1494-L1498

**Comment by VincentLanglet** [comment]
Writing 
```
final public function createQuery($context = 'list') 
```
would be a BC-break.

We add `@final` to softly warn `This will be final in next major`.

**Comment by kirya-dev** [comment]
Okay. Can close :)
