### ISSUE TITLE
Sonata admin bundle is not installing on symfony 5

### ISSUE THREAD

**Issue by virkse** [sonata-project/SonataAdminBundle#6317]
I'm having issue with installing the sonata bundle with symfony 5.
This is what i getting in terminal
-----------------------------------
**Problem 1
    - Installation request for sonata-project/admin-bundle ^3.74 -> satisfiable by sonata-project/admin-bundle[3.74.0].
    - sonata-project/admin-bundle 3.74.0 requires symfony/asset ^4.4 -> no matching package found.**

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by VincentLanglet** [comment]
See https://github.com/sonata-project/SonataAdminBundle/issues/5788
