### ISSUE TITLE
Render help

### ISSUE THREAD

**Issue by kirya-dev** [sonata-project/SonataAdminBundle#6319]
**SonataAdminBundle 3.73.0**

Edit form renders as:
![image](https://user-images.githubusercontent.com/30481080/91171174-be6c7e00-e6e2-11ea-83c7-d55c9b049dcc.png)

There has many problems:
1) paragraph inside inline-element (span)
2) empty span if no help
3) deprecation notice throws

TODO:
1) No inside. Use help_attr.class
2) Remove deprecate throws from \Sonata\AdminBundle\Admin\BaseFieldDescription::getHelp (add NEXT_MAJOR: Remove this method.)

**Comment by kirya-dev** [comment]
im use this configuration
https://symfony.com/blog/new-in-symfony-4-1-form-field-help

**Comment by kirya-dev** [comment]
Updgrades info dont prevent deprecation notice:
https://github.com/sonata-project/SonataAdminBundle/commit/26a887d7392715d7589b93fd8e1402f30a1527d4#diff-dcb51da20ad02d4fde6c4b5fb83819d0R4-R24

**Comment by kirya-dev** [comment]
before example must be:
```php
$formMapper
    ->add('field', null, [], [
        'help' => 'Help text <small>Please!</small>',
    ]);
```

**Comment by VincentLanglet** [comment]
Do you want to make a PR ?

**Comment by jordisala1991** [comment]
Bonus points if you provide screenshots on the before an after changes :)
