### ISSUE TITLE
Improve ModelAutocompleteFilter

### ISSUE THREAD

**Issue by kirya-dev** [sonata-project/SonataAdminBundle#6326]
## Feature Request

Using prefixes for resolve field name to searching entities from related admin.

Form here:
https://github.com/sonata-project/SonataAdminBundle/issues/6300#issuecomment-678812600

First question is: available prefix list it should be suggest in filter or is just hidden feature?

**Comment by jordisala1991** [comment]
I didnt mean it to add as a feature but as a how to in our documentation

**Comment by kirya-dev** [comment]
Add this here https://symfony.com/doc/master/bundles/SonataAdminBundle/reference/form_types.html?

**Comment by jordisala1991** [comment]
More like another file here: https://github.com/sonata-project/SonataAdminBundle/tree/3.x/docs/cookbook
