### ISSUE TITLE
Add option to load different Admin LTE skin

### ISSUE THREAD

**Issue by martinbroos** [sonata-project/SonataAdminBundle#6368]
## Feature Request

Sonata loads the black skin of admin LTE. But I rather load the blue-light skin, would be nice if this is an option.

To overcome this I can remove the black-skin stylesheet and add the blue-light skin stylesheet. But also the class on the body element must be changed. This could result in bugs when updates of sonata admin happen so I rather use a built in solution.
My guess is that is could be a setting with the name of the skin. As it matches the filename and the classname.

Any thoughts on this ?

**Comment by core23** [comment]
This is not an easy task because we have many customization(e.g. twig blocks), but feel free to provide a PR if you have a good idea.

**Comment by wbloszyk** [comment]
Curently we working on some change in assets and assets system. I mean all sonata bundles, not only AdminBundle. You can find it in [`sandbox webpack`](https://github.com/sonata-project/sandbox/tree/webpack)[(CONTRIBUTING_WEBPACK.md)](https://github.com/sonata-project/sandbox/blob/webpack/CONTRIBUTING_WEBPACK.md). We do it in sandbox to keep compatybility between ower bundles.

Webpack(SASS module) will allow in easy way to customize CSS, JS for user preference. 

Templates system is not discuse for now. We want add support for Bootstrap4 and AdminLTE3. We will discuse about when and if we do finish work on it. Any help will be appreciated.

**Comment by martinbroos** [comment]
Ok looks promising. I will look into into it to find out how I can help.

But is it ok to add this to the sonata 3.x branch so we can use it before releasing 4.x with admin lte 3 and webpack encore ?
It should only be small change, I can make a pull request so you can decide what to do with it. I didn't run into any problems with twig blocks.

**Comment by wbloszyk** [comment]
For now we are focus to add fully support webpack(in AdminLTE2 - `templates/SonataAdminBundle`, to keep BC). Curently sandbox is configured to work with it but some things is not move yet. You can help, for example, by find the way how to support form js from  `twig.form` files.
```yaml
twig:
    form_themes:
        - '@SonataFormatter/Form/formatter.html.twig'
        - '@SonataMedia/Form/media_widgets.html.twig'
        - '@SonataForm/Form/datepicker.html.twig'
```

**Comment by VincentLanglet** [comment]
> But is it ok to add this to the sonata 3.x branch so we can use it before releasing 4.x with admin lte 3 and webpack encore ?
> It should only be small change, I can make a pull request so you can decide what to do with it. I didn't run into any problems with twig blocks.

If you provide a PR to add this feature without BC-break on 3.x, we will happy to merge it ;)
