### ISSUE TITLE
For OneToMany, there is some concurrency between the form submission and row deletion

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6391]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              3.75.0 3.75.0 The missing Symfony Admin Generator
sonata-project/block-bundle              4.3.0  4.3.0  Symfony SonataBlockBundle
sonata-project/cache                     2.0.1  2.0.1  Cache library
sonata-project/doctrine-extensions       1.9.1  1.9.1  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.21.0 3.23.0 Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.3.0  2.3.0  Lightweight Exporter library
sonata-project/form-extensions           1.6.0  1.6.0  Symfony form extensions
sonata-project/twig-extensions           1.4.1  1.4.1  Sonata twig extensions
```

## Subject

![image](https://user-images.githubusercontent.com/9052536/93188557-67862180-f741-11ea-9cc6-d5cedad8f313.png)

When using a oneToMany, if you delete a line, fields are not required anymore.
But when I submit this form, I get an error because the form is trying to set the `null` BEFORE removing the entity ; and my setter doesn't accept `null`.

**Comment by kirya-dev** [comment]
Maybe need no process entity if them will be deleted?

**Comment by VincentLanglet** [comment]
> Maybe need no process entity if them will be deleted?

If you have any idea about how, and wanna make try. I'll be happy to see how you would implement it

**Comment by kirya-dev** [comment]
My project have same problem.. Now in process of found decisions

**Comment by kirya-dev** [comment]
Bug is come here:
https://github.com/sonata-project/form-extensions/blob/1.6.0/src/EventListener/ResizeFormListener.php

File 2 year without changes ((

**Comment by kirya-dev** [comment]
Bug in that incorrect choosed event.

Form mapps data and than call `ResizeFormListener::OnSubmit` who handle `_delete` flag

**Comment by kirya-dev** [comment]
Bug in appending (see `ResizeFormListener::preSubmit`) to `removed` in one event. And actually remove in other (see `ResizeFormListener::OnSubmit`).

Set null occurs between this dispatch this events in:
https://github.com/symfony/symfony/blob/b3a1851d43617c88aff68948554b0398fcdab07e/src/Symfony/Component/Form/Form.php#L620-L643

**Comment by kirya-dev** [comment]
In think that right solution is: do remove in `PRE_SET_DATA`.
Delete `removed` property and other foo code. Its a bad code(

**Comment by kirya-dev** [comment]
Same problem in symfony component: Remove data in `onSubmit` ():
`Symfony\Component\Form\Extension\Core\EventListener\ResizeFormListener`

https://github.com/symfony/symfony/blob/b3a1851d43617c88aff68948554b0398fcdab07e/src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php

**Comment by VincentLanglet** [comment]
> Same problem in symfony component: Remove data in `onSubmit` ():
> `Symfony\Component\Form\Extension\Core\EventListener\ResizeFormListener`
> 
> https://github.com/symfony/symfony/blob/b3a1851d43617c88aff68948554b0398fcdab07e/src/Symfony/Component/Form/Extension/Core/EventListener/ResizeFormListener.php

Maybe this issue could be created on Symfony repository then.
You could provide a way to reproduce it.

**Comment by VincentLanglet** [comment]
Duplicate of https://github.com/sonata-project/SonataAdminBundle/issues/4348
