### ISSUE TITLE
Awesome changes in templates

### ISSUE THREAD

**Issue by wbloszyk** [sonata-project/SonataAdminBundle#6396]
## Current Template System

Now `Admin` use template from `TemplateRegistry` simmilar like before from `templates` array property. Each registred `Admin` have generated in DI own template registry set as service `%s.template_registry` where `%s` is admin service id. Also each registred as service template registry should have `sonata.admin.template_registry` tag. They set template from `sonata_admin.templates`. People can override template in admin definitoin by call `setTemplate` or `setTemplates`.

## Currently made change

- changed `getTemplateRegistry` to public
- deprecated `setTemplate()` and `setTemplates()` in `AbstractAdmin`

### template registry pool and `supports()` method

`TemplateRegistryPool` (with `supports(): bool` method) will allow mark many template registries to one admin, where change it will be allowed directly on site.  For example"
- `sonata.admin.default_template_registry` will display product in table (show page),
- `sonata.admin.my_custom_template_registry_for_product.admin_lte2` - will display product view like in front page.

### base template registry

- `sonata.admin.default_template_registry` - for set in bundle option
- `sonata.admin.template_registry.admin_lte2` - last part will be like layout name
- `sonata.admin.template_registry.admin_lte3`

This will also allow to add other `layouts` like `admin_lte3`.

### buttons

Button like `show` should provide `dropdown` in admin support more then one template registry. 

### Summary

- each `Admin` will be have `sonata.admin.default_template_registry` as primary template registry
- people can override primary template registry by `setTemplateRegistry` in admin definition
- people can set own `sonata.admin.default_template_registry` by bundle option
- set own template will be harder (require create template registry instead only call setTemplate)
- template managment will be much more powerfull

**Comment by kirya-dev** [comment]
What is your strategy guys? Im every release get anyone deprecation's notices and broken logic.
