### ISSUE TITLE
Minor Translation Problems

### ISSUE THREAD

**Issue by pulzarraider** [sonata-project/SonataAdminBundle#640]
Hi, first of all, thanks for this Admin Bundle. It's awesome.

I'm creating localized administration for my page and I've found some problems:

- **Title in top of each page defined in app/config.yml is untranslatable**
Problem: no translation filter is used in template ```Sonata\AdminBundle\Resources\views\standard_layout.html.twig```.
This can be fixed by adding trans filter with translation domain defined in ```app/config.yml```. New configuration parameter ```translation_domain``` should be added.

~~- **Title of groups in dashboard and top menu is untranslatable** ~~
~~Problem: In template ```Sonata\AdminBundle\Resources\views\Block\block_admin_list.html.twig``` is used  ```SonataAdminBundle``` translation domain instead of some custom domain. ```{{ group.label|trans({}, 'SonataAdminBundle') }}```~~

This can be solved with ```label_catalogue``` parameter. It should be added to documentation.

```xml
        <service id="some_service" class="Some\Class">
            <tag name="sonata.admin" manager_type="orm" group="deal_group" label_catalogue="admin" label="Cities" />
            <argument />
             ...

        </service>
```

~~- **Title of column " Action" in view part contains space at begining.** It took me a lot of time to find out why my translation is not used.~~ Fixed with #1386

Maybe these bugs can be solved with custom templates, but it would be great if the default template would be usable as much as possible.

**Comment by core23** [comment]
Ping @pulzarraider  Ticket is very old. Has this been solved?
