### ISSUE TITLE
Use Symfony user security creation instead of FosUser

### ISSUE THREAD

**Issue by nachocifu** [sonata-project/SonataAdminBundle#6455]
## Feature Request
Following [this guide](https://symfony.com/doc/current/security.html) you end up with a user system with roles and i believe everything necessary for common use cases.
I think fos user no longer appears on the Symfony 5 docs and has been replaced by the given link as the way to add user support. 
Would it be possible for sonata admin to use that implmentation instead of Fos?

**Comment by VincentLanglet** [comment]
SonataAdminBundle does not provide any user system.
In my project I don't user FosUser for instance.

Are you talking about SonataUserBundle ?

**Comment by wbloszyk** [comment]
IMO you talking about https://github.com/sonata-project/SonataUserBundle/issues/1112. Can we close it or you mean something else?

**Comment by nachocifu** [comment]
My bad. Wrong repo and issue already exists.
