### ISSUE TITLE
How can I Customize sonata Collection form type with add new button.

### ISSUE THREAD

**Issue by zhasan0** [sonata-project/SonataAdminBundle#6459]
## Feature Request

I have this. But I want to customize collectionType template. How can I do this.
Look like that. Reference- https://symfony.com/doc/4.4/form/form_collections.html

`
->add('purchase_details', CollectionType::class, [
                    'btn_add' => 'Add Product',
                    'attr' => [
                        'class' => 'purchase'
                    ],
                    'by_reference' => false,
                    'label' => false,
                    'type_options' => [
                        'delete' => false,
                    ]], [
                    'edit' => 'inline',
                    'sortable' => 'position',
                    'inline' => 'table',
                    'multiple' => true,
                    //                    'type_options' => ['btn_add' => true],
                    'admin_code' => 'sdro_purchase.admin.purchase_details'
                ])
`

**Comment by kirya-dev** [comment]
Possible you need override block `sonata_type_native_collection_widget`

**Comment by zhasan0** [comment]
@kirya-dev Please give some reference or provide proper example.

**Comment by VincentLanglet** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only.

- Please have a look at the sonata docs
- Use StackOverflow for general support and help others as well
- Join #sonata on the symfony-devs slack for immediate help

In your case, I think it's in the Symfony docs.

**Comment by kirya-dev** [comment]
@zhasan0 for some improvements you can research source code of sonata-admin. Its so right way to customize or approve any bug.. For ex searching `sonata_type_native_collection_widget` im get:
![image](https://user-images.githubusercontent.com/30481080/95678554-249b5a80-0bd6-11eb-8f69-2294ab5b8c2e.png)
