### ISSUE TITLE
How to add a custom column to the list?

### ISSUE THREAD

**Issue by mikemix** [sonata-project/SonataAdminBundle#6488]
### Environment

Docker `php:7.3-apache`

#### Sonata packages
Sonata 3.76

## Subject

When adding a column to a non existing value:

```
            ->add('type', null, [
                'label' => 'Type',
                'template' => '@SonataAdmin/CRUD/Cms/list_article_type.html.twig',
            ])
```

I get:

>  User Deprecated: Accessing a non existing value is deprecated since sonata-project/admin-bundle 3.67 and will throw an exception in 4.0.

How to do this properly? All I want is to add a custom column to the list.

**Comment by napestershine** [comment]
You need to define a getter for it in Entity.

**Comment by VincentLanglet** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only.

- Please have a look at the sonata docs
- Use StackOverflow for general support and help others as well
- Join #sonata on the symfony-devs slack for immediate help

And @napestershine gave you the answer
