### ISSUE TITLE
sonata_type_collection and __construct() with parameters => error 500

### ISSUE THREAD

**Issue by tristanbes** [sonata-project/SonataAdminBundle#657]
Hi,

In my object Article, i have a 

    public function __construct($user)
    {
        $this->creator = $user;
    }

So, to avoid errors when i create a new object via `AdminBundle` i added : 

    public function getNewInstance()
    {
        $class = $this->getClass();
        return new $class($this->securityContext->getToken()->getUser());
    }

But, in my form, i have a `sonata_type_collection` that adds as many links as I want on the article.

As soon as i click on the `+` button, the ajax response gives a 500 because i don't know why, but it tries to do a `new Article()` without passing the parameter causing this `error 500`.

Is that a cfg i'm missing or is that a known bug ?

**Comment by core23** [comment]
ping @tristanbes

**Comment by tristanbes** [comment]
Closing the issue and will reopen with more details if that happens again.
