### ISSUE TITLE
Return iterable instead of array in PagerInterface::getResults

### ISSUE THREAD

**Issue by franmomu** [sonata-project/SonataAdminBundle#6620]
## Feature Request

Instead of 

https://github.com/sonata-project/SonataAdminBundle/blob/eddec2648cc1d3bb15f3343a2dc0e1156885244c/src/Datagrid/PagerInterface.php#L60-L65

it would be interesting to return `iterable<object>` since for example the mongodb implementation usually returns an iterator in its queries.

**Comment by VincentLanglet** [comment]
@franmomu What is needed for this PR ? Updating the phpdoc in 3.x and the return typehint in master ?

**Comment by franmomu** [comment]
Hmm I think that this also meant changing `DatagridInterface::getResults`, that's the only "extra" thing I remember.
