### ISSUE TITLE
[RFC] Use Pool just as a registry

### ISSUE THREAD

**Issue by franmomu** [sonata-project/SonataAdminBundle#6624]
## Feature Request

Looking at [Pool class](https://github.com/sonata-project/SonataAdminBundle/blob/fd2cd0450e5f71d942bd92a2395e1ceaa12b21fd/src/Admin/Pool.php) we can improve it in some ways, these are my thoughts:

- [x] Extract `title`, `logo` and `options` to a `Configuration` class, these parameters are used as configuration for the whole project, they shouldn't be needed for instantiate a Pool. https://github.com/sonata-project/SonataAdminBundle/pull/6640
- [x] Remove PropertyAccessor, [it was added for reuse](https://github.com/sonata-project/SonataAdminBundle/pull/3488), but after that [cache was added to the component](https://github.com/symfony/symfony/commit/ce28a869cc2aefd4168f0c1f97fdfcae30512784), so we can remove it and inject PropertyAccessor where is needed. https://github.com/sonata-project/SonataAdminBundle/pull/6634
- [ ] Inject a `ServiceLocator` with only the admin services, so we wouldn't need them to be public. https://github.com/sonata-project/SonataAdminBundle/pull/6733

After this the Pool class would be use just a registry for admin classes which I think it was meant to be.

The last one I guess it cannot be done with BC, but the other two we can deprecate those parameters in the Pool class.

WDYT? @sonata-project/contributors

**Comment by VincentLanglet** [comment]
> * Remove PropertyAccessor, [it was added for reuse](https://github.com/sonata-project/SonataAdminBundle/pull/3488), but after that [cache was added to the component](https://github.com/symfony/symfony/commit/ce28a869cc2aefd4168f0c1f97fdfcae30512784), so we can remove it and inject PropertyAccessor where is needed.

I strongly agree with this.
The AdminHelper has a dependency on the pool only to use the PropertyAccessor. This seems overkill.

Will you have some time to provide a PR ?

**Comment by franmomu** [comment]
I'll make a couple of PR, I started making these changes, just wanted to check to keep going.

**Comment by VincentLanglet** [comment]
Hi @franmomu, do you plan/want to do the last point before the 4.0 release ?

**Comment by franmomu** [comment]
I have both Pool related issues half way done, I'll try to make the PRs today.
