### ISSUE TITLE
Short link with filters

### ISSUE THREAD

**Issue by kirya-dev** [sonata-project/SonataAdminBundle#6642]
When im using filter im get too long link with all filters. We can add to link only changed(not default) parameters?

**Comment by VincentLanglet** [comment]
> When im using filter im get too long link with all filters. We can add to link only changed(not default) parameters?

Can you develop ? Maybe with screenshot ?

**Comment by haivala** [comment]
one solution is described here https://github.com/sonata-project/SonataAdminBundle/issues/689

**Comment by kirya-dev** [comment]
> one solution is described here #689

Just replacing `value` on `v` we dont escape providing other filters. And we also get url encoded `[` as `%5B`

Some systems using json representation or own developed representation of query structure.

**Comment by kirya-dev** [comment]
What kind use joined filter names instead of array substructure?

For ex:
`https://gfdaog.demo.sonata-project.org/admin/app/news-comment/list?filter_name_value=Gunnar`

**Comment by haivala** [comment]
I meant the jquery version

**Comment by kirya-dev** [comment]
> I meant the jquery version

You didnt says that you meant =(

And now we have two problems:
1) Extra params - resolves by jQuery
2) Url encoded symbols - use prefixes sturcture.

**Comment by kirya-dev** [comment]
@VincentLanglet How do you think its possible?

**Comment by VincentLanglet** [comment]
> I meant the jquery version

Removing the empty filters since a great start.

Do you want to try a PR with this @kirya-dev ?

**Comment by kirya-dev** [comment]
Of course. Im can. Im invent that:
For determine valid state of filters we need:
1) Use JS for submiting form. Variants:
1.a) Use window.location = '...';
1.b) Disable unmodified inputs and before submit.
1.c) Create fake form and submit it.
2) Store default filter values at form attribute for determine changed filters - first variable in AbstractAmin:getFilterParamaterts
3) Comparing algorithm with form values and submitted

Im think prefer 1.a point in 1 step

**Comment by kirya-dev** [comment]
Using `window.location = '..` allows no encode url charapters such as `[` & `]`
