### ISSUE TITLE
Make Pool immutable

### ISSUE THREAD

**Issue by franmomu** [sonata-project/SonataAdminBundle#6709]
## Feature Request

Since 3.83, Pool is just used as a registry for admin instances, but it still has `setAdminServiceIds`, `setAdminGroups` and `setAdminClasses`. 

We could add these parameters in the constructor (I think these methods are always called in `AddDependencyCallsCompilerPass`) and there will be no need of setters anymore.

**Comment by VincentLanglet** [comment]
Do you plan/want to do this in 4.0 release ? :)
