### ISSUE TITLE
Renaming `Pager::getNbResults` method

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6710]
Cf https://github.com/sonata-project/SonataAdminBundle/pull/6541#discussion_r532515190
And https://github.com/sonata-project/SonataAdminBundle/pull/6541#discussion_r543306726

@sonata-project/contributors Let's discuss about the name, current options are
- count() allows to implements Countable, but how is it clear to know if it's the count of pages or the count of results ?
- countResults()

**Comment by kirya-dev** [comment]
Pager has bugs. Please use Doctrine Paginator

**Comment by VincentLanglet** [comment]
> Pager has bugs. Please use Doctrine Paginator

- If there is bugs, report them correctly in an issue. This message doesn't help.
- This bundle works with multiple persistence bundle. Not only DoctrineORM.

**Comment by dmaicher** [comment]
> count() allows to implements Countable, but how is it clear to know if it's the count of pages or the count of results ?

yeah I also find that confusing. I would vote for `countResults`.

**Comment by VincentLanglet** [comment]
> > count() allows to implements Countable, but how is it clear to know if it's the count of pages or the count of results ?
> 
> yeah I also find that confusing. I would vote for `countResults`.

Do you want to provide the PR @dmaicher ? :)

**Comment by OskarStark** [comment]
I would also vote 🗳 for countResults()

**Comment by dmaicher** [comment]
I checked a bit and this will not be sooo easy to deprecate in a clean way on 3.x.

Everywhere we call `->getNbResults()` we need to check if the method `countResults()` exists and if not trigger a deprecation? We also call that method in twig templates :confused: 

After all people could have their own `PagerInterface` implementations.
