### ISSUE TITLE
Please change requirements for php8

### ISSUE THREAD

**Issue by grekpg** [sonata-project/SonataAdminBundle#6739]
i change php to 8 everythink work , but composer update 

Problem 1
    - This package requires php ^7.4 but your PHP version (8.0.0) does not satisfy that requirement.
  Problem 2
    - sonata-project/admin-bundle 3.55.0 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.
    - sonata-project/admin-bundle 3.55.0 requires php ^7.1 -> your PHP version (8.0.0) does not satisfy that requirement.

**Comment by VincentLanglet** [comment]
Currently we can't.

SonataAdmin has a lot of dependencies, some of them doesn't support php8 currently.
For instance SonataAdmin requires SonataBlock which require the sonata cache.
So first the Sonata should support php8: https://github.com/sonata-project/cache/pull/165

**Comment by hamza-grichi** [comment]
Hello 
Today we can use sonata-project/admin-bundle with PHP 8.2?

Thanks ;)

**Comment by jordisala1991** [comment]
Yes, you can, completely compatible, and tested on Github Actions.
