### ISSUE TITLE
ListMapper $fieldDescriptionOptions as a callable

### ISSUE THREAD

**Issue by vladyslavstartsev** [sonata-project/SonataAdminBundle#6741]
## Feature Request

I have a case, when I want to check if user has referrals. Referrals is a doctrine collection.
What I need to display is if user has or has no referrals.
Currently what I can do is https://symfony.com/doc/current/bundles/SonataAdminBundle/reference/action_list.html#displaying-a-non-model-field

But when I want to do this without changing query I would like to get something like this

```php

            ->add('hasReferrals', null, [
                'code' => function (User $user): bool {
                    return $user->getReferrals()->isEmpty();
                }
            ])
```

this way building admin panel becomes faster

Currently for the feature I want to have I see 

```text
method_exists() expects parameter 2 to be string, object given
```
sonata-project/admin-bundle/src/Admin/BaseFieldDescription.php (line 393) (my current version is 3.83)

**Comment by VincentLanglet** [comment]
Here: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Admin/BaseFieldDescription.php#L423-L449

We could do something like
```
        foreach ($getters as $getter) {
            if (\is_callable($getter)) {
                return $getter($object, ...$parameters);
            elseif (\is_string($getter)) {
                if (method_exists($object, $getter) && \is_callable([$object, $getter])) {
                    $this->cacheFieldGetter($object, $fieldName, 'getter', $getter);

                    return $object->{$getter}(...$parameters);
                }
            } else {
                throw exception() // We support only callable and string
            }
        }
```

Do you want to do the PR @vladyslavstartsev ?

**Comment by vladyslavstartsev** [comment]
Yes, weekends
