### ISSUE TITLE
Unfixable `sonata.deprecated_text.twig.extension`

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6745]
When I follow this
https://github.com/sonata-project/SonataAdminBundle/blob/3.x/UPGRADE-3.x.md#upgrade-from-363-to-364

I get both
User Deprecated: The "sonata.deprecated_text.twig.extension" service is deprecated since sonata-project/admin-bundle 3.70. You should stop using it, as it will be removed in 4.0.

and
The child node "legacy_twig_text_extension" at path "sonata_admin.options" is deprecated since sonata-project/admin-bundle 3.70 and will be removed in 4.0.

I assume it's because of https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/Resources/config/twig_string.php#L29

@franmomu

**Comment by franmomu** [comment]
The unavoidable deprecation was added in https://github.com/sonata-project/SonataAdminBundle/pull/6145

**Comment by VincentLanglet** [comment]
Ping @wbloszyk then

There is two things: 
- Using legacy_twig_text_extension shouldn't throw an exception
- `legacy_twig_text_extension: false` doesn't remove the exception for .`sonata.deprecated_text.twig.extension`

I could make the PR for the first point, but I don't know how to fix the second one.

**Comment by wbloszyk** [comment]
> Ping @wbloszyk then
> 
> There is two things:
> 
> * Using legacy_twig_text_extension shouldn't throw an exception
> * `legacy_twig_text_extension: false` doesn't remove the exception for .`sonata.deprecated_text.twig.extension`
> 
> I could make the PR for the first point, but I don't know how to fix the second one.

First:
Remove `setDeprecated` from `sonata.deprecated_text.twig.extension` option and add note about delete this option in `UPGRADE-4.0.md`.

Second:
`sonata.deprecated_text.twig.extension` should not be load (or should be remove) when `legac_twig_text_extension` is false in `SonataAdminExtension::configureTwigTextExtension()`.
