### ISSUE TITLE
Custom Controller with SonataAdmin Forms

### ISSUE THREAD

**Issue by MagePsycho** [sonata-project/SonataAdminBundle#6771]
Sometimes we may just want to display the Form for some actions like:

- To generate PDF based on inputs
- To generate code based on inputs
- To redirect to any third-party page based on inputs
- Any custom action based on the post controller

For this purpose, just creating a CRUD controller looks overhead.

**One solution** is to create a custom controller with a form view but it comes with the caveats:
- Form design will not match with the SonataAdmin theme
- Cannot leverage the power of `FormMapper::add()` methods for form generation
- Other power of SonataAdmin

Is there a way to have a custom controller with the SonataAdmin form design? 
This feature would make the SonataAdmin a killer bundle.

*Note that I am using Symfony 5.x*

**Comment by VincentLanglet** [comment]
Why not using a Symfony form ?

 > * Form design will not match with the SonataAdmin theme

You can use the SonataAdmin theme for custom Symfony forms.

> * Cannot leverage the power of `FormMapper::add()` methods for form generation

```
public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('type', ...)
            ->add('value', ...)
        ;
    }
```
Is pretty similar
