### ISSUE TITLE
Update recipe for 4.0

### ISSUE THREAD

**Issue by franmomu** [sonata-project/SonataAdminBundle#6808]
## Feature Request

Update https://github.com/symfony/recipes-contrib/tree/master/sonata-project/admin-bundle/ for 4.0, what should be done is to remove:

https://github.com/symfony/recipes-contrib/blob/e94bdd3d4da70b65705744b72b60217b4f486bfa/sonata-project/admin-bundle/3.64/config/packages/sonata_admin.yaml#L7

I haven't checked, maybe something else.

**Comment by dmaicher** [comment]
See https://github.com/symfony/recipes-contrib/pull/1084

Could not see any other things that need to be updated for 4.0

**Comment by VincentLanglet** [comment]
Does dev-master will use this recipe ?

**Comment by dmaicher** [comment]
> Does dev-master will use this recipe ?

If https://github.com/symfony/recipes-contrib/pull/1084 would be merged I guess it would be used - yes.

**Comment by dmaicher** [comment]
https://github.com/symfony/recipes-contrib/pull/1084 was merged. So we can close here?

**Comment by travis00001** [comment]
after updating to this^ merge,

```
  - Configuring sonata-project/admin-bundle (>=4.0): From github.com/symfony/recipes-contrib:master
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!
!!    The service "sonata.twig.flashmessage.manager" has a dependency on a non-ex
!!    istent service "session". Did you mean one of these: "debug.argument_resolv
!!    er.session", "debug.argument_resolver.session.inner"?
!!
!!
!!
Script @auto-scripts was called via post-update-cmd

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by dmaicher** [comment]
> after updating to this^ merge,
> 
> ```
>   - Configuring sonata-project/admin-bundle (>=4.0): From github.com/symfony/recipes-contrib:master
> Executing script cache:clear [KO]
>  [KO]
> Script cache:clear returned with error code 1
> !!
> !!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
> !!
> !!    The service "sonata.twig.flashmessage.manager" has a dependency on a non-ex
> !!    istent service "session". Did you mean one of these: "debug.argument_resolv
> !!    er.session", "debug.argument_resolver.session.inner"?
> !!
> !!
> !!
> Script @auto-scripts was called via post-update-cmd
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.
> ```

hm on Symfony 5.x the `session` service was deprecated... but it should still exist :confused:

**Comment by dmaicher** [comment]
@travis00001 I just tested it on a fresh symfony 5.2 project: works fine for me. No idea whats causing your issue. Anyway not related to the recipe I believe

**Comment by franmomu** [comment]
@travis00001 feel free to open a new issue if you still have the problem.

Thanks @dmaicher!

**Comment by travis00001** [comment]
> @travis00001 feel free to open a new issue if you still have the problem.
> 
> Thanks @dmaicher!

https://github.com/sonata-project/SonataAdminBundle/issues/6836
