### ISSUE TITLE
crud list

### ISSUE THREAD

**Issue by aboodalfar** [sonata-project/SonataAdminBundle#6811]
how optimize  crud list:
i have sql query have 4 join i don't wont every record from crud to excuate   single query 

i try to do that in admin class :

`
public function createQuery($context = 'list') {
        $query = parent::createQuery($context);
        $query
                ->innerJoin($query->getRootAlias() . '.PortalUser', 'p')
                ->innerJoin($query->getRootAlias().'.Platform','plat')    
                ->innerJoin('p.UserLogs','log')
                ->innerJoin('log.FosUser','fosUser')   
                ->select($query->getRootAlias().'.login,plat.code,fosUser.username as fosUserName')
                ->andWhere( 'log.body like :body')
                ->setParameter('body', '%creation of trading account #%')
                ;
        return $query;
        //$proxyQuery = new \Sonata\DoctrineORMAdminBundle\Datagrid\ProxyQuery($query);
    }
` 

**i have error when add ->select(** 

<img src="https://i.ibb.co/QkW943R/Screenshot-2021-01-26-An-exception-has-been-thrown-during-the-rendering-of-a-template-Warning-Illega.png" alt="Screenshot-2021-01-26-An-exception-has-been-thrown-during-the-rendering-of-a-template-Warning-Illega" border="0">

i dont wont crud object i want only when add 

->select($query->getRootAlias().'.login,plat.code,fosUser.username as fosUserName')
to render this list in crud

**Comment by VincentLanglet** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
