### ISSUE TITLE
Override ModelListType modal

### ISSUE THREAD

**Issue by marvoh** [sonata-project/SonataAdminBundle#6812]
I have a one-to-many relationship between parent and child on the same entity. Because the list is long, the ModelListType is easier to use because it allows searching and selecting.

However, I need to prevent a situation where when editing a parent, the user can accidentally select a child would lead into cyclic dependency.

````
protected function configureFormFields(FormMapper $formMapper): void
{
        $formMapper
            ->add('name')
            ->add('parent', ModelListType::class, [
            'label' => 'Parent Level',
            ]);
}
````

Since ModelListType class has no query property, I am thinking I can overwrite the list_select.html.twig template to be able to disable the items that should not be selected.

How would I overwrite this since it's not a field that is available for which I can create a custom template for directly?

I have attached an image of the modal with selects I would like to hide.

![photo_2021-01-27_10-34-42](https://user-images.githubusercontent.com/5451142/105962115-6fab8180-6090-11eb-9a90-490c421c3323.jpg)

**Comment by VincentLanglet** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. I recommend you instead to

- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
