### ISSUE TITLE
Add consistency in signature of AdminExtensionInterface method dealing with array or create specific classes

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6826]
In the AdminExtensionInterface we have:

Some methods have only the admin as parameters, and returns an array which is merged with the admin values.
```
 * @method array getAccessMapping(AdminInterface $admin)
 * @method array getPersistentParameters(AdminInterface $admin)
```

Some methods are taking the admin and the array as parameters ; they modify the array and returns it.
```
 * @method array configureBatchActions(AdminInterface $admin, array $actions)
 * @method array configureExportFields(AdminInterface $admin, array $fields)
 * @method array configureActionButtons(AdminInterface $admin, array $list, string $action, object $object)
```

Some methods are taking the admin and the array as parameters ; they modify the array by reference.
```
 * @method void  configureDefaultFilterValues(AdminInterface $admin, array &$filterValues)
 * @method void  configureDefaultSortValues(AdminInterface $admin, array &$sortValues)
 * @method void  configureFormOptions(AdminInterface $admin, array &$formOptions)
```

I think we should add consistency on this and choose only one way to do it @sonata-project/contributors.
Which one do you prefer ? I prefer the third one.
And I would rename getAccessMapping/getPersistentParameters as configureAccessMapping/configurePersistentParameters.

**Comment by franmomu** [comment]
IMHO if we are going to change this, we could create specific classes for each case like: 

`configureBatchActions(AdminInterface $admin, BatchActions $actions)`
`configureExportFields(AdminInterface $admin, ExportFields $actions)`

**Comment by VincentLanglet** [comment]
> IMHO if we are going to change this, we could create specific classes for each case like:
> 
> `configureBatchActions(AdminInterface $admin, BatchActions $actions)`
> `configureExportFields(AdminInterface $admin, ExportFields $fields)`

I was thinking about a simpler change, from
```
 * @method void  configureDefaultFilterValues(AdminInterface $admin, array &$filterValues)
 * @method void  configureDefaultSortValues(AdminInterface $admin, array &$sortValues)
 * @method void  configureFormOptions(AdminInterface $admin, array &$formOptions)
```
to
```
 * @method array  configureDefaultFilterValues(AdminInterface $admin, array $filterValues)
 * @method array  configureDefaultSortValues(AdminInterface $admin, array $sortValues)
 * @method array  configureFormOptions(AdminInterface $admin, array $formOptions)
```

WDYT @sonata-project/contributors ?

**Comment by wbloszyk** [comment]
Lets make the less change as we can. IMHO 4.0 we should close API. Things like improve functionality we should move to 5.0 where we should also focus on some standards like KISS, SOLID and DRY.

**Comment by VincentLanglet** [comment]
Creating specific classes was already proposed for BatchActions https://github.com/sonata-project/SonataAdminBundle/issues/4677
We may have multiple step to improve the current situation.

**Comment by core23** [comment]
Maybe we can combine both ideas. When using the `configureBatchActions(AdminInterface $admin, BatchActions $actions)` method signature, we could create a `BatchActions` class which implements the `ArrayAccess` interface. 

Also this requires only a signature change in the implementing method, but the method body could stay the same: https://3v4l.org/F3vG3
