### ISSUE TITLE
Deprecate "code" option in BaseFieldDescription in favor of "property_path"

### ISSUE THREAD

**Issue by franmomu** [sonata-project/SonataAdminBundle#6831]
## Feature Request

I have never used this `code` option, but apparently I think it could be changed for a `property_path` option [similar to the one used in forms](https://symfony.com/doc/4.4/reference/forms/types/form.html#property-path) (so it would be familiar for the user), in this case just to read (using `PropertyPathAccessor`).

**Comment by VincentLanglet** [comment]
I think the `code` option should be renamed indeed but I'm not sure `property_path` is the right thing.

Currently the `code` option must be a method name
```
'code' => 'getFooBar'
```
But there is a request for allowing a callable
https://github.com/sonata-project/SonataAdminBundle/issues/6741

The feature request wouldn't be possible with the `property_path` option isn't it ?

I would prefer something more similar to `choice_value` https://symfony.com/doc/current/reference/forms/types/choice.html#choice-value which allow a string, a callable, or a propertyPath.

Shouldn't we rename this option `value`, 'field_value' or something like this ?

**Comment by franmomu** [comment]
In that specific case, I think it would work with the path `referals.empty`, but I guess `callable` is useful too (if we allow `callable`, `property_path` does not make sense).

My concern with names ended in `value` is that I expect the final value there, like `"field_value" => true` or `"field_value" => "hello"` (but that's maybe me).

**Comment by VincentLanglet** [comment]
> My concern with names ended in `value` is that I expect the final value there, like `"field_value" => true` or `"field_value" => "hello"` (but that's maybe me).

`getter` maybe then ?

**Comment by phansys** [comment]
"accessor" or "callable" are more generic IMO, but "getter" is fine too.
