### ISSUE TITLE
Rise static analysis level to max for 4.0

### ISSUE THREAD

**Issue by vladyslavstartsev** [sonata-project/SonataAdminBundle#6833]
## Feature Request

For the next major (4.0), since we can break things, I would like to see `phpstan` and `psalm` levels to max.

**Comment by VincentLanglet** [comment]
Do you have some time to help @vladyslavstartsev ?

**Comment by vladyslavstartsev** [comment]
@VincentLanglet sorry, I can't promise

**Comment by VincentLanglet** [comment]
Phpstan is now max level. And psalm level 4. Not sure we will do more.
