### ISSUE TITLE
too many filters results in urls that are too long

### ISSUE THREAD

**Issue by haggertypat** [sonata-project/SonataAdminBundle#689]
As discussed [here](http://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url) and [here](http://www.danrigsby.com/blog/index.php/2008/06/17/rest-and-max-url-size/), IE doesn't support urls that are longer than about 2000 characters, and Apache's limit is 4000.

Even in Firefox I am experiencing strange behavior with 3500 character urls.

SonataAdmin urls get long very quickly.  Each filter uses at least 33 characters: `&filter[][type]=&filter[][value]=`.  Assume an average field name length of 8 and this number is close to 50 for each filter.  This limits us to only 40 filters.  Take into account domain names, extra characters for date filters, base SonataAdmin urls, and SonataAdmin programmers adding custom url parameters and this number is much lower.

40 or even 35 filters may seem high but I have an application in development with over 50.

**Comment by webdevilopers** [comment]
:+1:

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.

**Comment by webdevilopers** [comment]
Sorry, but I'm no longer working on this project.
