### ISSUE TITLE
Allow admin extension to define templates

### ISSUE THREAD

**Issue by yann-eugone** [sonata-project/SonataAdminBundle#6890]
## Feature Request

As a developper, when I create an admin extension, I sometime need a template for what the extension add.

Example :

```
My extension introduce a new route.
That route is covered with an action in a controller trait.
In that action, I will render the response using a template.
```

-----

The problem is that there is no hook in the extension that is called everytime an admin is required (think `AbstractAdmin::initialize`).

So far, I ended with this code (in the controller action) :

```php
$template = 'path/to/default.html.twig';
if ($this->admin->getTemplateRegistry()->hasTemplate('my_extension_template')) {
    $template = $this->admin->getTemplateRegistry()->getTemplate('my_extension_template');
}

return $this->renderWithExtraParams($template, []);
```

-----

I usually don't use admin service definition calls to setup my template (admin are auto-registered).

I prefer overriding the `AbstractAdmin::configure` and configure my templates here, calling `setTemplate` myself.

A solution would be that the admin extension do have a the same `configure` method, called in `AbstractAdmin::initialize` :

```php
abstract class AbstractAdmin
{
    public function initialize()
    {
        //...
        
        foreach ($this->getExtensions() as $extension) {
            $extension->configure($this);
        }

        $this->configure();
    }
}

interface AdminExtensionInterface
{
    /**
     * @return void
     */
    public function configure(AdminInterface $admin);
}
```

-----

I can of course create a PR, if you like the idea.

**Comment by VincentLanglet** [comment]
This seems useful indeed.
Can you provide a PR @yann-eugone ?
