### ISSUE TITLE
custom add new button

### ISSUE THREAD

**Issue by floran974** [sonata-project/SonataAdminBundle#6892]
## Feature Request

Hi it's possible to custom add new button  to automatically add 10 empty lines with each click to make the entry easier. 

exemple have a  add  +10  new  button

Thank's you

**Comment by kirya-dev** [comment]
As im know FormResizer prevents this ability

**Comment by VincentLanglet** [comment]
I think it's too specific to be added in SonataAdmin.
You can implement you own FormType for this.
