### ISSUE TITLE
Add search to list view

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataAdminBundle#6918]
## Feature Request

I'm planing to add a new feature which adds a new search field on each admin list. You can search for entities that may contain the searched value.

![Screenshot 2021-03-07 at 16 32 35](https://user-images.githubusercontent.com/3440437/110245274-c5622c00-7f62-11eb-8a81-77d7ee04f712.png)

This can be done via a new `SearchableAdminInterface`:

```php
interface SearchableAdminInterface
{
    /**
     * List of fields that are searchable
     * 
     * @return string[]
     */
    public function getSearchFields(): array;
}

class SomeAdmin extends AbstractAdmin implements SearchableAdminInterface
{
    public function getSearchFields(): array 
   {
       return ['address', 'name', 'description'];
   }
}
```

**Comment by phansys** [comment]
I agree with the resulting feature, but I think we should consider the current implementation we have around the `global_search` option in the field description.

**Comment by VincentLanglet** [comment]
HI @core23, I saw the bot added the stale label. Do you still work on this feature ?

**Comment by core23** [comment]
I got this feature running on my local machine, but I need some time to integrate this into the existing sonata code.

**Comment by VincentLanglet** [comment]
Hi @core23, are you still able to provide a PR for this feature ?
