### ISSUE TITLE
AbstractAdmin::getFilterParameters is final on 4.0/master

### ISSUE THREAD

**Issue by dmaicher** [sonata-project/SonataAdminBundle#6921]
## Feature Request

On master/4.0 the method `AbstractAdmin::getFilterParameters` was made final but I actually overwrite it on my projects for 2 admins.

I'm overwriting it do restrict sorting as the admins are used for entities that have > 10 million database rows currently.

So it looks like this

```php
    public function getFilterParameters(): array
    {
        $params = parent::getFilterParameters();

        // without any reviewConfig filter we only ever allow sorting by id
        // as otherwise it can be incredibly slow for millions of reviews
        if (!($params['reviewConfig']['value'] ?? null) && $params['_sort_by'] !== 'id') {
            $this->flashMessageManager->addFlash(
                'error',
                sprintf('Sorting by "%s" is only possible when a reviewConfig filter is active.', $params['_sort_by'])
            );
            $params['_sort_by'] = 'id';
        }

        return $params;
    }
```

Would it be possible to revert the change of making the method final? I did not find any other easy way of achieving this differently. Or maybe someone has an idea?

**Comment by VincentLanglet** [comment]
Imho, we should keep as final all (or the most possible) public method.

What about introducing a protected method `configureFilterParameters` @dmaicher ?

**Comment by dmaicher** [comment]
yes @VincentLanglet this would also work I guess :+1: I will have a look
