### ISSUE TITLE
Unable to find %s object with id: %s - while admin child used

### ISSUE THREAD

**Issue by mareckigit** [sonata-project/SonataAdminBundle#6948]
#### Sonata packages

<details><summary>show</summary>
<p>

```
sonata-project/admin-bundle              3.93.0
```

</p>
</details>

## Subject

Unable to find %s object with id: %s. 

CRUDController.php
`final protected function assertObjectExists(Request $request): void` is executed and parent ID is used to find child by ID.

Here is used class of child and ID of parent:
`$this->getModelManager()->find($this->getClass(), $id); `

It worked well in my previous version of Sonata Admin Bundle: 3.77 

## Steps to reproduce

Go to a tab of child admin with empty related objects. For example: if there is a new Thread and there is no Comments related to the Thread. 

## Expected results

Empty grid.

## Actual results

404: Unable to find %s object with id: %s

**Comment by phansys** [comment]
How are you configuring the child admins? What is the URL path and the route name where you are experiencing this issue?
