### ISSUE TITLE
Make public services private

### ISSUE THREAD

**Issue by franmomu** [sonata-project/SonataAdminBundle#6962]
## Feature Request

We have a lot of public services that I think we can make them private, [in Symfony `5.1` there is a tag for deprecating a public service to make it private](https://symfony.com/blog/new-in-symfony-5-1-deprecate-public-services-into-private-services), but since we're supporting Symfony `4.4`, we could maybe [copy the compiler pass as internal class](https://github.com/symfony/symfony/blob/d39596edaba715d4c7b4bbef8efbb1c6c4e916f0/src/Symfony/Component/DependencyInjection/Compiler/AliasDeprecatedPublicServicesPass.php) and add a custom tag to deprecate them.

**Comment by eerison** [comment]
case anyone is working on this issue, I can get 😃

**Comment by franmomu** [comment]
Thanks @eerison! I started, but something else came up and I forgot about it, this is what I started doing: https://github.com/franmomu/SonataAdminBundle/commit/3d58eaf243052c1b9523c71244dd8cb8b6e57c02

So feel free to use it or use another approach.

**Comment by eerison** [comment]
Nice then I'll take a look and i'll keeping here up to date about the progress

**Comment by eerison** [comment]
@franmomu or @VincentLanglet do you know how do I use my repository instead of `sonata-project/admin-bundle` ?

I'm trying to use it in my `composer.json` but it's not working

```json
    "repositories": [
        {
            "type": "package",
            "package": {
                "version": "3.76.0",
                "name": "sonata-project/admin-bundle",
                "source": {
                    "url": "https://github.com/eerison/SonataAdminBundle.git",
                    "type": "git",
                    "reference": "dev-master"
                }
            }
        }
    ]
```

**Comment by franmomu** [comment]
Let's say you've created a `deprecate_public_services` branch, then:

```json
"repositories": [{
    "type": "vcs",
    "url": "https://github.com/eerison/SonataAdminBundle"
}],
```

and to use it (the `as 3.95` in case other package needs it):

```json
    "require": {
        "sonata-project/admin-bundle": "dev-deprecate_public_services",
        "sonata-project/admin-bundle": "dev-deprecate_public_services as 3.95"
    },
```

**Comment by eerison** [comment]
> Let's say you've created a `deprecate_public_services` branch, then:
> 
> ```json
> "repositories": [{
>     "type": "vcs",
>     "url": "https://github.com/eerison/SonataAdminBundle"
> }],
> ```
> 
> and to use it (the `as 3.95` in case other package needs it):
> 
> ```json
>     "require": {
>         "sonata-project/admin-bundle": "dev-deprecate_public_services",
>         "sonata-project/admin-bundle": "dev-deprecate_public_services as 3.95"
>     },
> ```

Thank you @franmomu 

it's working now 🚀 

```
xmb00559:user-service erison.silva$ docker-compose run --rm php composer info sonata-project/admin-bundle
Creating user-service_php_run ... done
name     : sonata-project/admin-bundle
descrip. : The missing Symfony Admin Generator
keywords : admin, admin-generator, admin-lte, bundle, sonata, symfony
versions : * dev-master, 4.x-dev
type     : symfony-bundle
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://sonata-project.org/bundles/admin
source   : [git] https://github.com/eerison/SonataAdminBundle.git 7f07a8e25b90451125a9820d391747e49dd1f485
dist     : [zip] https://api.github.com/repos/eerison/SonataAdminBundle/zipball/7f07a8e25b90451125a9820d391747e49dd1f485 7f07a8e25b90451125a9820d391747e49dd1f485
path     : /usr/src/app/vendor/sonata-project/admin-bundle
names    : sonata-project/admin-bundle
```

**Comment by VincentLanglet** [comment]
@franmomu Not fully related but I recently got an error 
```
Cannot autowire service "AssuranceVie\AdminRepository\ClientAdminRepository": argument "$modelManager" of method "AssuranceVie\AdminRepository\AbstractAdminRepository::setManager()" references interface "Sonata\AdminBundle\Model\ModelManagerInterface" but no such service exists. You should maybe alias this interface to the existing "sonata.admin.manager.orm" service.
```

Should we declare an alias for the interface in every persistence bundle config ?
https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/3.x/src/Resources/config/doctrine_orm.xml#L8-L11

**Comment by franmomu** [comment]
hmm what do you mean by recently? Was working before?

Looks strange to set the manager in a repository, what I do when there is no alias defined is to bind the argument like: https://symfony.com/doc/4.4/service_container.html#binding-arguments-by-name-or-type

In case we want to create an alias, I guess we should create interfaces (as markers) in each persistence bundle, otherwise there will be a collision with the service id `Sonata\AdminBundle\Model\ModelManagerInterface` when using multiple persistence bundles.

**Comment by VincentLanglet** [comment]
> hmm what do you mean by recently? Was working before?

No, it's 100% related to a change in my code.

> Looks strange to set the manager in a repository, 

It's not a real repository, just something with a wrong name.

> what I do when there is no alias defined is to bind the argument like: https://symfony.com/doc/4.4/service_container.html#binding-arguments-by-name-or-type
> 
> In case we want to create an alias, I guess we should create interfaces (as markers) in each persistence bundle, otherwise there will be a collision with the service id `Sonata\AdminBundle\Model\ModelManagerInterface` when using multiple persistence bundles.

Yeah, I bind too, but I was wondering if we could provide a 0 config solution ^^
