### ISSUE TITLE
Check `service_container` usages

### ISSUE THREAD

**Issue by franmomu** [sonata-project/SonataAdminBundle#6963]
## Feature Request

[We are using `service_container` in](https://github.com/sonata-project/SonataAdminBundle/search?q=service_container):
- [x] [InlineValidator](https://github.com/sonata-project/SonataAdminBundle/blob/137ffd9f6053fa0b734c2e1dd7db86d6c3b94aed/src/Resources/config/validator.php#L27) For what I remember, the validation was removed from admins, so I don't know if this service is longer needed. **Update**: deprecated in https://github.com/sonata-project/SonataAdminBundle/pull/6998
- [x] [SonataAdminExtension](https://github.com/sonata-project/SonataAdminBundle/blob/128941fd9aa4d17adaa46165ba3df48067de3c9a/src/Resources/config/twig.php#L60) This one should have been marked to me removed, in `4.x` is already removed.
- [x] [RenderElementExtension](https://github.com/sonata-project/SonataAdminBundle/blob/128941fd9aa4d17adaa46165ba3df48067de3c9a/src/Resources/config/twig.php#L107) I think this is no longer needed, it is used to fetch the template registry associated to an admin, but IIRC there is a `getTemplateRegistry` in the admin. **Update**: made it in https://github.com/sonata-project/SonataAdminBundle/pull/6996
- [x] [Pool](https://github.com/sonata-project/SonataAdminBundle/blob/8a48504af9b98c6f56dff9cc4674f12485d942d6/src/Resources/config/core.php#L54) This one is already a Service Locator in `4.x`.
- [x] [AdminPoolLoader](https://github.com/sonata-project/SonataAdminBundle/blob/8a48504af9b98c6f56dff9cc4674f12485d942d6/src/Resources/config/core.php#L76) I have no idea about this one, [looking at the use](https://github.com/sonata-project/SonataAdminBundle/blob/a7ebeaa05573bf42d80f5c7531e4e8219df3923b/src/Route/AdminPoolLoader.php#L74-L77) I would say it is not needed anymore, but I'm not sure. **Updated**: done in `4.x`.
- [x] [FilterFactory](https://github.com/sonata-project/SonataAdminBundle/blob/8a48504af9b98c6f56dff9cc4674f12485d942d6/src/Resources/config/core.php#L97) It would be nice to create a ServiceLocator for this one so filters don't need to be public.
- [x] [AuditManager](https://github.com/sonata-project/SonataAdminBundle/blob/8a48504af9b98c6f56dff9cc4674f12485d942d6/src/Resources/config/core.php#L189) Looks like a tag could be created to inject a service locator with the related services. **Updated**: done in `4.x`.

**Comment by VincentLanglet** [comment]
Speaking on `SonataAdminExtension`, the only remaining method is 
https://github.com/sonata-project/SonataAdminBundle/blob/b737b64feea99be925af9b970bc42dca26d7587f/src/Twig/Extension/SonataAdminExtension.php#L64

But I find no usage, do you think we can deprecate the full extension ? @franmomu

**Comment by franmomu** [comment]
The method is not directly used, but it's used as a filter: https://github.com/search?q=org%3Asonata-project+sonata_urlsafeid&type=code.

In some places there is no admin, so I guess we should keep it for now.

**Comment by jordisala1991** [comment]
But we have another filter called this same way: https://github.com/sonata-project/twig-extensions/blob/1.x/src/Extension/TemplateExtension.php

Which one are we using?

**Comment by franmomu** [comment]
Interesting, I guess it depends on the project, on which bundle it is registered last.

**Comment by VincentLanglet** [comment]
This issue can be closed.
But should we open one about the `sonata_urlsafeid` duplicate ?
