### ISSUE TITLE
Option to get small `link_action` buttons. 

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#6970]
## Feature Request

What do you think about an option to get the actions buttons with only the icons @sonata-project/contributors ?
Has it already been discussed ?

It would render something like
![image](https://user-images.githubusercontent.com/9052536/112489822-1a81a880-8d7f-11eb-9429-ac339be203fc.png)

**Comment by franmomu** [comment]
It was discussed in https://github.com/sonata-project/SonataAdminBundle/pull/4968, but the initial idea was to make it mandatory, so optional is fine.
