### ISSUE TITLE
Method validate doesn't executed when form saving

### ISSUE THREAD

**Issue by shtumi** [sonata-project/SonataAdminBundle#698]
Branch: master.
I added 
    public function validate(ErrorElement $errorElement, $object)
    {
        var_dump (1232);
        die();
    }
to my admin class. But it executed never.

**Comment by saifrehman15** [comment]
I have the same issue. I am using vich file uploader to upload a file. I just want to validate the file size and throw an error if file size greater than 500kb.
Any help is much appreciated. Thanks .

**Comment by kunicmarko20** [comment]
@saifrehman15 did you try using `preValidate`:

https://github.com/sonata-project/SonataAdminBundle/blob/3a5f85ee9909c0fa20623394450e06b96174a32c/src/Admin/AbstractAdmin.php#L2975

**Comment by saifrehman15** [comment]
@kunicmarko20 thanks for the reply. But how can I throw the error like I do in validate method . My function is as follow. 

public function preValidate( $object)
    {
        parent::preValidate($object); // TODO: Change the autogenerated stub


        if($object->getProfileImage()){  // getsize return the result in bytes. adding restruction to 5kb
            if($object->getProfileImage()->getSize() > 500000 ){
                //throw new \Exception('Please return and upload a file less than or equal to 5kb in size.');
            }

        }

    }
I want to throw the error as follow. 

$error = 'Recurrence field is required!';
$errorElement->with('recurrence')->addViolation($error)->end();
$this->getRequest()->getSession()->getFlashBag()->add("menu_type_check", $error);

the above lines are not working in preValidate hook.

**Comment by catasoft** [comment]
@saifrehman15 Any solution to this issue? It is a bit old, but just now have I encountered it. 
I can't find a way to invalidate some data conditionally (like in your example), and also mark fields as "in error state" automatically.
Thank you for your help.

**Comment by sarim** [comment]
For future googlers and future me and @catasoft 

I solved it by calling `$this->getForm()->addError`

```php
  protected function preValidate(object $object): void
  {
      $customService = .....................;

      if (!$customService ->isValid($object)) {
          $this->getForm()->addError(new FormError('configuration not valid'));
      }
  }
```
