### ISSUE TITLE
restore protected to $listModes in AbstractTaggedAdmin

### ISSUE THREAD

**Issue by RobinDev** [sonata-project/SonataAdminBundle#7035]
On master, since `$listModes` in [AbstractTaggedAdmin](https://github.com/sonata-project/SonataAdminBundle/blob/master/src/DependencyInjection/Admin/AbstractTaggedAdmin.php) is `private` (before it was protected), I can't figure how to customize the listModes.

I am not sure if it's a bug or if it's the expected behaviour (and I can't find  how to customize listModes since this update).

Thanx.

**Comment by VincentLanglet** [comment]
What's your usage ?

Currently the show mosaic button option is provided from the configuration
```
        $showMosaicButton = $overwriteAdminConfiguration['show_mosaic_button']
            ?? $attributes['show_mosaic_button']
            ?? $container->getParameter('sonata.admin.configuration.show.mosaic.button');
        $definition->addMethodCall('showMosaicButton', [$showMosaicButton]);
```

The method exposed are
```
    final public function showMosaicButton(bool $isShown): void
    {
        if ($isShown) {
            $this->listModes['mosaic'] = ['class' => static::MOSAIC_ICON_CLASS];
        } else {
            unset($this->listModes['mosaic']);
        }
    }

    final public function getListModes(): array
    {
        return $this->listModes;
    }
```

I think it could be better to expose instead
```
    final public function setListModes(array $listModes): void
    {
        $this->listModes = $listModes;
    }

    final public function getListModes(): array
    {
        return $this->listModes;
    }
```

**Comment by RobinDev** [comment]
I am adding a third view (tree) wich is done by creating a new admin action. Currently (or before), I was symply adding

```

        $this->listModes['tree'] = ['class' => 'fa fa-sitemap'];
```

in my admin constructor.

I vote for your proposal ! I can do a PR if it's okay for you ?

**Comment by VincentLanglet** [comment]
Sure, some help about the PR is welcomed !

**Comment by axzx** [comment]
@RobinDev 
how are you setting it now: 
`$this->listModes['tree'] = ['class' => 'fa fa-sitemap'];`
?

@jordisala1991 
I think it would be nice to write in the documentation how to extend the listModes

**Comment by VincentLanglet** [comment]
Just use the getter getListModes and the setter setListModed

**Comment by axzx** [comment]
> Just use the getter getListModes and the setter setListModed

where?

Cannot override final method AbstractTaggedAdmin->setListModes(listModes: array)

**Comment by VincentLanglet** [comment]
All the admin configuration can be done in the `configure` method.

**Comment by axzx** [comment]
> All the admin configuration can be done in the `configure` method.

ok, thanks:)

```
public function configure()
    {
        parent::configure();

        $this->listModes = [
            'list' => ['class' => 'fa fa-list fa-fw'],
            'tree' => ['class' => 'fa fa-sitemap'],
        ];
    }
```

**Comment by VincentLanglet** [comment]
> ```
> public function configure()
> {
>     parent::configure();
> 
>     $this->setListModes([
>         'list' => ['class' => 'fa fa-list fa-fw'],
>         'tree' => ['class' => 'fa fa-sitemap'],
>     ]);
> }
> ```
