### ISSUE TITLE
ModelType dont wor'k

### ISSUE THREAD

**Issue by epci** [sonata-project/SonataAdminBundle#7058]
Hello,

When i try to use Sonata\AdminBundle\Form\Type\ModelType

I have an error "An exception has been thrown during the rendering of a template ("Field "FIELDS" has already been rendered, save the result of previous render call to a variable and output that instead.")."

thank you

**Comment by VincentLanglet** [comment]
Hello

There is a bug template, please fill it with all the necessary information or no help can't be provided and this issue will be closed.

Thanks you

**Comment by epci** [comment]
Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Field "groups" has already been rendered, save the result of previous render call to a variable and output that instead.")." at /srv/users/serverpilot/apps/tools-starter5/vendor/sonata-project/admin-bundle/src/Resources/views/CRUD/Association/edit_many_to_many.html.twig line 110
{
    "exception": {}
}

**Comment by epci** [comment]
An exception has been thrown during the rendering of a template ("Field "groups" has already been rendered, save the result of previous render call to a variable and output that instead.").
Exceptions 2 Logs 1 Stack Traces 2
Twig\Error\
RuntimeError
in vendor/sonata-project/admin-bundle/src/Resources/views/CRUD/Association/edit_many_to_many.html.twig (line 110)
            {% include '@SonataAdmin/CRUD/Association/edit_one_script.html.twig' %}        {% else %}            <div id="field_container_{{ id }}" class="field-container">                <span id="field_widget_{{ id }}" >                    {{ form_widget(form) }}                </span>                <span id="field_actions_{{ id }}" class="field-actions">                    {% if sonata_admin.field_description.associationadmin.hasRoute('create')                        and sonata_admin.field_description.associationadmin.hasAccess('create')

**Comment by VincentLanglet** [comment]
I'm talking about the following bug template. I'm sorry but without these information, the issue will be closed.





### Environment

#### Sonata packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'sonata-project/*'
# Put the result here.
```

</p>
</details>

#### Symfony packages

<details><summary>show</summary>
<p>

```
$ composer show --latest 'symfony/*'
# Put the result here.
```

</p>
</details>

#### PHP version

```
$ php -v
# Put the result here.
```

## Subject



## Minimal repository with the bug

## Steps to reproduce

## Expected results

## Actual results
