### ISSUE TITLE
Fail fast when using ACL as security handler without `security.acl.provider` service

### ISSUE THREAD

**Issue by franmomu** [sonata-project/SonataAdminBundle#7097]
## Feature Request

From https://github.com/sonata-project/SonataAdminBundle/issues/7086

If a user is using ACL as security handler, then the `sonata.admin.security.handler.acl` service receives the `security.acl.provider` service as argument 3.

It would be nice to check if the user has chosen ACL as security handler and there is no `security.acl.provider`, then fail fast when parsing configuration.

**Comment by VincentLanglet** [comment]
We just have to add the check here: https://github.com/sonata-project/SonataAdminBundle/blob/3.x/src/DependencyInjection/SonataAdminExtension.php#L174 isn't it ? @franmomu

**Comment by franmomu** [comment]
Yep, I think so
