### ISSUE TITLE
OneToMany's owning side not updated when saving CollectionType

### ISSUE THREAD

**Issue by drm** [sonata-project/SonataAdminBundle#710]
I have found that this is (or at least should be) fixed in the Symfony Form component with the [MergeCollectionListener on CollectionType fields in 2.1](https://github.com/symfony/symfony/pull/3819), but in the SonataAdmin this is still an issue.

When you use the sonata_collection_type on a OneToMany field, the changes in the collection are not reflected at the owning (inverse) side of the relation, so when adding or removing items from the collection these changes are not persisted, resulting in the "delete" checkbox not working and the "add" button not persisting the ManyToOne side value of the relation.

I have a quick fix solution for this, which is dirty in many obvious ways. There might be someone to help me figure out a better solution or even help integrating with (a backport of) the MergeCollectionListener from symfony 2.1. For now this solves my problem so I'll just use the patched code, but any help integrating the solution would be greatly appreciated (not only be me, I am sure).

I'll attach the changes in a PR.

**Comment by webdevilopers** [comment]
:+1: @drm

**Comment by webdevilopers** [comment]
My solution was to set `by_reference` to `false as suggested by @webmozart here:
https://github.com/symfony/symfony/issues/1540#issuecomment-1849307

**Comment by core23** [comment]
This issue is very old should be fixed in the latest master version. Please have a look at the docs.

If this is still present, feel free to reopen this issue @drm
