### ISSUE TITLE
Default to lastPage when pager is looking for a non-existent page (for v.3.97)

### ISSUE THREAD

**Issue by lizazz** [sonata-project/SonataAdminBundle#7122]
There was an error
`- When accessing on a non-existent List page, it displays a link to go to page 1 instead of a button to create a new entity.` 

-  in https://github.com/sonata-project/SonataAdminBundle/pull/6500
and it has been marked as fixed in the sonata-admin 3.78.

Also, I have seen commit, which should fix the error, 

https://github.com/sonata-project/SonataDoctrineORMAdminBundle/pull/1046/commits/fb956f3bd4849ff072f488f3e15f53f6353966d8

but it hasn't been apply to any version

but I found the same error in v.3.78, 3.79, and 3.97.
I would like to reopen this issue.

**Comment by VincentLanglet** [comment]
This should fix the issue @lizazz https://github.com/sonata-project/SonataAdminBundle/pull/7128
