### ISSUE TITLE
UI bug with select

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#7165]
I'm using SonataAdmin 3.98.2 but the problems was already here in 3.96.

I recently have the following UI issue
![image](https://user-images.githubusercontent.com/9052536/117163376-dfce4f80-adc3-11eb-8ed2-7c04520593e1.png)

One or multiple select list are opened in the top left corner of the page.
This happen a lot on list pages, with the filter selects.

I'm am the only one @sonata-project/contributors ?

**Comment by jordisala1991** [comment]
Can you change... the default admin css for the one without plugins? (check how I did for 4.0 branch)

**Comment by dmaicher** [comment]
I cannot reproduce this on any of my admins

**Comment by VincentLanglet** [comment]
Seems solved for me in Sonata 4
