### ISSUE TITLE
Aplha 4 sidenav hamburger not working

### ISSUE THREAD

**Issue by JustDylan23** [sonata-project/SonataAdminBundle#7180]
### Environment
Ubuntu lts 20.04

#### Sonata packages
sonata-project/admin-bundle              4.0.0-alpha-1   4.0.0-alpha-1      The missing Symfony Admin Generator
sonata-project/block-bundle              4.x-dev 9417d9b dev-master 37683c0 Symfony SonataBlockBundle
sonata-project/cache                     2.1.1           2.1.1              Cache library
sonata-project/doctrine-extensions       1.12.0          1.12.0             Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 4.0.0-alpha-1   4.0.0-alpha-1      Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/exporter                  2.6.2           2.6.2              Lightweight Exporter library
sonata-project/form-extensions           1.9.0           1.9.0              Symfony form extensions
sonata-project/twig-extensions           1.5.1           1.5.1              Sonata twig extensions

#### Symfony packages
symfony/apache-pack                v1.0.1  v1.0.1  A pack for Apache support in Symfony
symfony/asset                      v5.2.7  v5.2.7  Manages URL generation and versioning of web assets such as CSS stylesheets, JavaScript files and image files
symfony/cache                      v5.2.7  v5.2.7  Provides an extended PSR-6, PSR-16 (and tags) implementation
symfony/cache-contracts            v2.4.0  v2.4.0  Generic abstractions related to caching
symfony/config                     v5.2.7  v5.2.7  Helps you find, load, combine, autofill and validate configuration values of any kind
symfony/console                    v5.2.7  v5.2.7  Eases the creation of beautiful and testable command line interfaces
symfony/debug-bundle               v5.2.4  v5.2.4  Provides a tight integration of the Symfony Debug component into the Symfony full-stack framework
symfony/dependency-injection       v5.2.7  v5.2.7  Allows you to standardize and centralize the way objects are constructed in your application
symfony/deprecation-contracts      v2.4.0  v2.4.0  A generic function and convention to trigger deprecation notices
symfony/doctrine-bridge            v5.2.7  v5.2.7  Provides integration for Doctrine with various Symfony components
symfony/dotenv                     v5.2.4  v5.2.4  Registers environment variables from a .env file
symfony/error-handler              v5.2.7  v5.2.7  Provides tools to manage errors and ease debugging PHP code
symfony/event-dispatcher           v5.2.4  v5.2.4  Provides tools that allow your application components to communicate with each other by dispatching events and listening to them
symfony/event-dispatcher-contracts v2.4.0  v2.4.0  Generic abstractions related to dispatching event
symfony/expression-language        v5.2.7  v5.2.7  Provides an engine that can compile and evaluate expressions
symfony/filesystem                 v5.2.7  v5.2.7  Provides basic utilities for the filesystem
symfony/finder                     v5.2.4  v5.2.4  Finds files and directories via an intuitive fluent interface
symfony/flex                       v1.12.2 v1.12.2 Composer plugin for Symfony
symfony/form                       v5.2.7  v5.2.7  Allows to easily create, process and reuse HTML forms
symfony/framework-bundle           v5.2.7  v5.2.7  Provides a tight integration between Symfony components and the Symfony full-stack framework
symfony/http-client                v5.2.7  v5.2.7  Provides powerful methods to fetch HTTP resources synchronously or asynchronously
symfony/http-client-contracts      v2.4.0  v2.4.0  Generic abstractions related to HTTP clients
symfony/http-foundation            v5.2.7  v5.2.7  Defines an object-oriented layer for the HTTP specification
symfony/http-kernel                v5.2.7  v5.2.7  Provides a structured process for converting a Request into a Response
symfony/intl                       v5.2.7  v5.2.7  Provides a PHP replacement layer for the C intl extension that includes additional data from the ICU library
symfony/maker-bundle               v1.31.0 v1.31.0 Symfony Maker helps you create empty commands, controllers, form classes, tests and more so you can forget about writing boilerplate code.
symfony/mime                       v5.2.7  v5.2.7  Allows manipulating MIME messages
symfony/monolog-bridge             v5.2.7  v5.2.7  Provides integration for Monolog with various Symfony components
symfony/monolog-bundle             v3.7.0  v3.7.0  Symfony MonologBundle
symfony/options-resolver           v5.2.4  v5.2.4  Provides an improved replacement for the array_replace PHP function
symfony/polyfill-intl-grapheme     v1.22.1 v1.22.1 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-icu          v1.22.1 v1.22.1 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-intl-idn          v1.22.1 v1.22.1 Symfony polyfill for intl's idn_to_ascii and idn_to_utf8 functions
symfony/polyfill-intl-normalizer   v1.22.1 v1.22.1 Symfony polyfill for intl's Normalizer class and related functions
symfony/polyfill-mbstring          v1.22.1 v1.22.1 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73             v1.22.1 v1.22.1 Symfony polyfill backporting some PHP 7.3+ features to lower PHP versions
symfony/polyfill-php80             v1.22.1 v1.22.1 Symfony polyfill backporting some PHP 8.0+ features to lower PHP versions
symfony/property-access            v5.2.4  v5.2.4  Provides functions to read and write from/to an object or array using a simple string notation
symfony/property-info              v5.2.7  v5.2.7  Extracts information about PHP class' properties using metadata of popular sources
symfony/proxy-manager-bridge       v5.2.4  v5.2.4  Provides integration for ProxyManager with various Symfony components
symfony/routing                    v5.2.7  v5.2.7  Maps an HTTP request to a set of configuration variables
symfony/security-acl               v3.1.2  v3.1.2  Symfony Security Component - ACL (Access Control List)
symfony/security-bundle            v5.2.7  v5.2.7  Provides a tight integration of the Security component into the Symfony full-stack framework
symfony/security-core              v5.2.7  v5.2.7  Symfony Security Component - Core Library
symfony/security-csrf              v5.2.7  v5.2.7  Symfony Security Component - CSRF Library
symfony/security-guard             v5.2.4  v5.2.4  Symfony Security Component - Guard
symfony/security-http              v5.2.7  v5.2.7  Symfony Security Component - HTTP Integration
symfony/serializer                 v5.2.7  v5.2.7  Handles serializing and deserializing data structures, including object graphs, into array structures or other formats like XML and JSON.
symfony/service-contracts          v2.4.0  v2.4.0  Generic abstractions related to writing services
symfony/stopwatch                  v5.2.7  v5.2.7  Provides a way to profile code
symfony/string                     v5.2.6  v5.2.6  Provides an object-oriented API to strings and deals with bytes, UTF-8 code points and grapheme clusters in a unified way
symfony/translation                v5.2.7  v5.2.7  Provides tools to internationalize your application
symfony/translation-contracts      v2.4.0  v2.4.0  Generic abstractions related to translation
symfony/twig-bridge                v5.2.7  v5.2.7  Provides integration for Twig with various Symfony components
symfony/twig-bundle                v5.2.4  v5.2.4  Provides a tight integration of Twig into the Symfony full-stack framework
symfony/validator                  v5.2.7  v5.2.7  Provides tools to validate values
symfony/var-dumper                 v5.2.7  v5.2.7  Provides mechanisms for walking through any arbitrary PHP variable
symfony/var-exporter               v5.2.7  v5.2.7  Allows exporting any serializable PHP data structure to plain PHP code
symfony/web-link                   v5.2.5  v5.2.5  Manages links between resources
symfony/web-profiler-bundle        v5.2.7  v5.2.7  Provides a development tool that gives detailed information about the execution of any request
symfony/webpack-encore-bundle      v1.11.2 v1.11.2 Integration with your Symfony app & Webpack Encore!
symfony/yaml                       v5.2.7  v5.2.7  Loads and dumps YAML files

#### PHP version
PHP 8.0.6 (cli) (built: May  7 2021 20:55:41) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.6, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.6, Copyright (c), by Zend Technologies

## Subject
The hamburger icon on the top left that is used for opening and closing the sidenav no longer responds to clicks.

**Comment by dmaicher** [comment]
> I think @dmaicher is using the alpha, but he said nothing to me about some UI bug.

@VincentLanglet I just upgraded my biggest project to it and made tests pass :smile: I'm not using it on production yet. Waiting for fixes in the alpha-2

**Comment by VincentLanglet** [comment]
> This will be fixed on next alpha

Closing then, the alpha is released
