### ISSUE TITLE
Use checkbox instead of icon for filters

### ISSUE THREAD

**Issue by franmomu** [sonata-project/SonataAdminBundle#7187]
## Feature Request

When using font awesome 5, `fas` icons are solid and we are using icons for the checkbox in filters:

![image](https://user-images.githubusercontent.com/720690/118000532-2da80200-b346-11eb-97b0-ded89882eb3c.png)

That makes checkboxes look strange to me, we could use a `<input type='checkbox'>` instead.

**Comment by VincentLanglet** [comment]
@franmomu Maybe using the `fal` icon could be a solution
https://fontawesome.com/v5.15/icons/square?style=light

**Comment by franmomu** [comment]
The problem is that apparently only `fab` and `fas` are free: https://fontawesome.com/v5.15/how-to-use/on-the-web/referencing-icons/basic-use

**Comment by VincentLanglet** [comment]
My bad, the regular should be used here
https://fontawesome.com/v5.15/icons/square?style=regular

It doesn't have the `Pro` label because of https://fontawesome.com/v5/cheatsheet/free/regular#why-regular

**Comment by VincentLanglet** [comment]
@franmomu @dmaicher Can someone try changing to `<i class="far fa-square"></i>` on his project to see if it's better ?

**Comment by dmaicher** [comment]
@VincentLanglet changing


```diff
-<i class="fas {{ filterDisplayed ? 'fa-check-square' : 'fa-square' }}"></i>
+<i class="far {{ filterDisplayed ? 'fa-check-square' : 'fa-square' }}"></i>
``` 

looks better:

![Screenshot at 2021-08-03 09-51-23](https://user-images.githubusercontent.com/921145/127978692-22c545dc-c1f8-43ba-9db4-063a84e37c8f.png)

**Comment by VincentLanglet** [comment]
Let's go with this then https://github.com/sonata-project/SonataAdminBundle/pull/7358
