### ISSUE TITLE
refreshNavbarStuckClass leads to scroll lag on safari

### ISSUE THREAD

**Issue by moostrich** [sonata-project/SonataAdminBundle#7192]
#### Sonata packages

```
$ composer show --latest 'sonata-project/*'
sonata-project/admin-bundle              dev-master 23df35c dev-master 23df35c The missing Symfony Admin Generator
sonata-project/block-bundle              4.5.3              4.5.3              Symfony SonataBlockBundle
sonata-project/cache                     2.1.1              2.1.1              Cache library
sonata-project/doctrine-extensions       1.12.0             1.12.0             Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle dev-master b59f9e5 dev-master b59f9e5 Integrate Doctrine ORM into the SonataAdminB...
sonata-project/exporter                  2.6.2              2.6.2              Lightweight Exporter library
sonata-project/form-extensions           1.9.0              1.9.0              Symfony form extensions
sonata-project/twig-extensions           1.5.1              1.5.1              Sonata twig extensions
```

</p>
</details>

## Subject

The `refreshNavbarStuckClass` function in `assets/js/admin.js` leads to nasty scroll lag on Safari whenever the corresponding waypoint is reached. Responsible is this part:

https://github.com/sonata-project/SonataAdminBundle/blob/01677b25381aa3c3d87dfaf7fe8699d9bc4744f3/src/Resources/public/Admin.js#L722

Safari does not seem to handle this kind of runtime injection of global styles very well.
This does not occur on Firefox, on Chrome I had the issue in the past but it resolved itself.
In the past I had Safari issues like this on other machines as well, but it might be machine specific to some degree.

This bug leads to a bad UX on some machines. I will create a PR to fix it.

**Comment by jordisala1991** [comment]
Fixed
