### ISSUE TITLE
Allow flash error messages to be verbose

### ISSUE THREAD

**Issue by vyshkant** [sonata-project/SonataAdminBundle#7195]
Currently, default flash errors for different kinds of actions are not really saying anything about the error. It is usually something like: `An error has occurred during the creation of item "%name%".`.

For most cases, this is just great behavior, but for some cases, we might want to make these error messages more verbose. We may think of it, as the possibility to enrich these messages with some extra information from the exception that caused the error.

My suggestion is to make it possible to configure this behavior in some way.

I'll gladly provide a PR for such functionality if you consider this is a good idea.

**Comment by VincentLanglet** [comment]
> My suggestion is to make it possible to configure this behavior in some way.

You can override the translation key in your project if needed.
But adding extra information is not a bad idea.

> I'll gladly provide a PR for such functionality if you consider this is a good idea.

PR are always welcomed.
