### ISSUE TITLE
Extract the way we choose `base_template` for actions

### ISSUE THREAD

**Issue by franmomu** [sonata-project/SonataAdminBundle#7242]
## Feature Request

We have repeated code [in `CRUDController` and in some actions ](https://github.com/sonata-project/SonataAdminBundle/search?l=PHP&q=base_template) for resolving which is the base template to use, something like:

```php
'base_template' => $request->isXmlHttpRequest() 
    ? $this->templateRegistry->getTemplate('ajax') 
    : $this->templateRegistry->getTemplate('layout')
```

It would be nice to move this logic somewhere else, to a service (maybe listener?) or resolve it in twig, having always in mind that a user should be able to specify the `base_template`.

Ref: https://github.com/sonata-project/SonataAdminBundle/pull/7238#issuecomment-856770819

**Comment by VincentLanglet** [comment]
IMHO when this issue will be solved, we should deprecate `addRenderExtraParams`.
