### ISSUE TITLE
Official site is down

### ISSUE THREAD

**Issue by Deuchnord** [sonata-project/SonataAdminBundle#7244]
Hi there

It looks like the website at https://sonata-project.org/ is down. When I try to access it, I am getting the following page:

![ Error 526 - Invalid SSL certificate](https://user-images.githubusercontent.com/7600265/121320356-60c1bf00-c90d-11eb-821d-ba40edf8004f.png)

**Comment by OskarStark** [comment]
@rande can you please check the SSL certificate? Thanks

**Comment by rande** [comment]
Fixed, thanks for reporting the issue.
