### ISSUE TITLE
Broken standard_layout

### ISSUE THREAD

**Issue by kirya-dev** [sonata-project/SonataAdminBundle#7256]
Layout **src/Resources/views/standard_layout.html.twig** includes deprecated SonataCore templates.
When im remove SonataCoreBundle get error:
```Unable to find one of the following templates: "@SonataCore/FlashMessage/render.html.twig", "@SonataTwig/FlashMessage/render.html.twig" in SonataAdminBundle::standard_layout.html.twig at line 297.```

Actually in sonata-project/admin-bundle (3.101.0)

**Comment by VincentLanglet** [comment]
Please fill correctly the issue with all your dependencies.
I don't use the CoreBundle and it works fine for me.

The template to use is this one: https://github.com/sonata-project/twig-extensions/tree/1.x/src/Bridge/Symfony/Resources/views/FlashMessage

Did you correctly add the twig-extension to your project ?

**Comment by kirya-dev** [comment]
After register ```Sonata\Twig\Bridge\Symfony\SonataTwigBundle::class => ['all' => true], ``` solve this issue and im receive same problem
https://github.com/sonata-project/sonata-doctrine-extensions/issues/218

And what about show help messages for that package need registry?

**Comment by VincentLanglet** [comment]
> After register `Sonata\Twig\Bridge\Symfony\SonataTwigBundle::class => ['all' => true], ` solve this issue and im receive same problem
> [sonata-project/sonata-doctrine-extensions#218](https://github.com/sonata-project/sonata-doctrine-extensions/issues/218)

It was fixed in https://github.com/sonata-project/sonata-doctrine-extensions/pull/298
it will be soon release.

> And what about show help messages for that package need registry?

Already in the installation doc.
https://symfony.com/doc/current/bundles/SonataAdminBundle/getting_started/installation.html
