### ISSUE TITLE
select2 not working on v4 alpha 2

### ISSUE THREAD

**Issue by JustDylan23** [sonata-project/SonataAdminBundle#7260]
There is no input box for me to type in that gives autocompletion.
![image](https://user-images.githubusercontent.com/27694850/122094469-81f24600-ce0c-11eb-9fc3-c84bcf361d02.png)

The documentation says that select2 is integrated with sonata admin and that it is enabled on every select without doing anything

```
->add('owner', ModelType::class, [
    'property' => 'username',
])
```
I honestly have no clue why it isn't showing up

I have both the admin-bundle and the doctrine-orm-bunde on version 4.0.0-alpha-2 currently.

**Comment by JustDylan23** [comment]
![image](https://user-images.githubusercontent.com/27694850/122094848-e8776400-ce0c-11eb-84c6-a601719f5802.png)
as far as I am aware it should look something like this

**Comment by VincentLanglet** [comment]
Isnt the ModelAutocompleteType made for this ?

**Comment by JustDylan23** [comment]
ModelAutocompleteType works by calling an endpoint

**Comment by JustDylan23** [comment]
In one of our projects at work some of the model type inputs have search boxes and others dont. I am really not sure what the deciding factor is to whether you get a searchbox or not.

**Comment by haivala** [comment]
There is search box only if there is enough choices. I don't know how many but I have noticed this in 3.* and haven't even tested 4

**Comment by franmomu** [comment]
Based on https://github.com/sonata-project/SonataAdminBundle/blob/82afd8a37ef233a9b00d5751f679f9810de05a57/src/Resources/public/Admin.js#L104-L132

Looks like it shows the search box when there are more than 10 results and you can modify it with the `data-sonata-select2-maximumSelectionSize` attribute like https://symfony.com/doc/current/bundles/SonataAdminBundle/cookbook/recipe_select2.html#disable-select2-on-some-form-elements

**Comment by JustDylan23** [comment]
It would be pretty nice to have this documented somewhere, can somebody edit the documentation?

**Comment by VincentLanglet** [comment]
> It would be pretty nice to have this documented somewhere, can somebody edit the documentation?

You're welcome to do it ;)
