### ISSUE TITLE
Make AbstractFormContractor a non abstract class and refacto others builders

### ISSUE THREAD

**Issue by VincentLanglet** [sonata-project/SonataAdminBundle#7313]
## Feature Request

@franmomu The AbstractFormContractor in master is
- fully implementing the `FormContractorInterface`.
- full of final methods.
- Extending as if, in persistence bundle: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/blob/master/src/Builder/FormContractor.php

I think we should change it to a real class instead.

**Comment by franmomu** [comment]
👍 I have pending when I find some time to see the other builders, at least `ListBuilder` and `ShowBuilder` I remember they seemed easy to replace (no need to do it before 4.0).

**Comment by VincentLanglet** [comment]
I just had to improve the fixtures in tests of the ListBuilder and ShowBuilder in order to correctly support
`FieldDescriptionInterface::TYPE_ARRAY`
https://github.com/sonata-project/SonataAdminBundle/pull/7448/commits/8ef3ea91e249f1bec3d9b5594f4101352b2be027

There is definitely something to do
I discovered we provide an abstract extension in SonataAdmin to be used by persistence bundles
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/DependencyInjection/AbstractSonataAdminExtension.php

It would be nice to move the `template.types.show/list` config from persistence to admin bundle and to have a default support for all the `FieldDescriptionInterface::TYPE_*` field, since the constant and the template is provided by SonataAdmin.
