### ISSUE TITLE
Error if don't define the translation_domain

### ISSUE THREAD

**Issue by vguardiola** [sonata-project/SonataAdminBundle#7318]
After the change to validate a false value for translation_domain(#7277) it break if you don't have defined the translation_domain on the array for a batch_action

![image](https://user-images.githubusercontent.com/572270/125438978-4c9077ed-00ff-48a8-bf6a-8d67c85a566a.png)

**Comment by VincentLanglet** [comment]
Hi @vguardiola Can you provide a PR to fix this ?

**Comment by vguardiola** [comment]
Hi @VincentLanglet I will try to do this afternoon or tomorrow morning after/before my job hours
