### ISSUE TITLE
Object of class DateTime could not be converted to string

### ISSUE THREAD

**Issue by PoisonousJohn** [sonata-project/SonataAdminBundle#737]
I have this error in listAction when adding field that has orm type  date or datetime. Has anyone idea how to fix this?

Render fails on 20 string of base_list_field.htm.twig. Object passes here instead of string.

```
        {%- block field %}{{ value }}{% endblock -%}
```

I have no clue where to look for reason of error. Maybe some kind of a data transformer missing

**Comment by damesad** [comment]
Although you can use the

<code> date : {{ game.gameDate|date('Y-m-d') }} </code>
result
<code>  date :  2015-01-01</code>

Solution view <a href="http://stackoverflow.com/questions/8318914/how-to-render-a-datetime-object-in-a-twig-template#answer-10196625">http://stackoverflow.com/questions/render-datetime</a>
