### ISSUE TITLE
Make twig extensions lazy

### ISSUE THREAD

**Issue by dmaicher** [sonata-project/SonataAdminBundle#7474]
## Feature Request

Currently our twig extensions are not using lazy runtimes. Which means whenever the twig environment is bootstrapped on apps all extension services (and all related dependencies) are instantiated although probably for non-admin requests those are rarely/never used.

To improve the performance there we could use [lazy-loaded extensions](https://symfony.com/doc/current/templating/twig_extension.html#creating-lazy-loaded-twig-extensions).

~~Since the extension classes are final this could be done on 4.x without a BC break I think?~~

EDIT: or actually maybe it cannot be done without a BC break :confused:  as it would mean removing public methods from the extensions and moving them to Runtimes.

**Comment by VincentLanglet** [comment]
> EDIT: or actually maybe it cannot be done without a BC break 😕 as it would mean removing public methods from the extensions and moving them to Runtimes.

I think it can be BC.
We can stop using the public method in 4.x in favor of the Runtimes, deprecating them and removing them in next major.
It's not because there is a non-used method in the twigExtension it's not lazy, isn't it ?

**Comment by dmaicher** [comment]
> We can stop using the public method in 4.x in favor of the Runtimes, deprecating them and removing them in next major.

We could do this. But it would mean that we don't have a performance benefit yet until we fully remove the methods and don't inject dependencies anymore into the extensions.

**Comment by franmomu** [comment]
We marked the twig extension constructors as internal, so we can remove the dependencies.

**Comment by dmaicher** [comment]
> We marked the twig extension constructors as internal, so we can remove the dependencies.

Well yes but calling the public methods defined on the extensions should still work, right? At least if we want to strictly keep BC. Maybe someone decorated the extension for whatever reason.

**Comment by jordisala1991** [comment]
> > We marked the twig extension constructors as internal, so we can remove the dependencies.
> 
> Well yes but calling the public methods defined on the extensions should still work, right? At least if we want to strictly keep BC. Maybe someone decorated the extension for whatever reason.

I think the internal method are not suposed to be called by anyone outside the bundle that defines it. So in this case, if someone calls it because it is decorating or something, he/she already knows that it could change because it is internal.

**Comment by franmomu** [comment]
> Well yes but calling the public methods defined on the extensions should still work, right? At least if we want to strictly keep BC.

Yep, you are right (when I saw it, I thought there where static calls).
