### ISSUE TITLE
Documentation: disable sticky forms

### ISSUE THREAD

**Issue by rene-roesch-blg** [sonata-project/SonataAdminBundle#7481]
## Feature Request

Sonata uses sticky forms by default. Sticky forms are a feature that has the form actions in an edit view render the action buttons at the bottom of the page, but scroll upwards below the form when scrolling up.
This feature can easily be disabled via sonata_admin.yml package config. This option is not documented however. (as opposed to  e.g. disabling Select2.

I'd be happy the extend the docs/cookbook, but am not quite sure on where to put that information. 
Maybe a new section regarding these options that affect javascript beaviour would be accurate? There's way more than just select and sticky_forms to yet be documented properly.
Any suggestions? :)

Examples.
With sticky forms:
![with_sticky_forms](https://user-images.githubusercontent.com/33286651/132819297-2fe9f42b-1b65-4b41-b536-91bf49b240b8.png)

Without sticky forms:
![without_sticky_forms](https://user-images.githubusercontent.com/33286651/132819326-0792031a-d6a1-4569-90fd-c509bdff6ecc.png)

**Comment by VincentLanglet** [comment]
There is already some documentation about some others options
https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/cookbook/recipe_select2/
https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/cookbook/recipe_icheck/

I feel like adding a recipe for sticky form would be too much since there is not a lot to say.

Maybe it would be better to group them under another title (related to form options ?)
And it would be easy to add a sticky form section then.

**Comment by rene-roesch-blg** [comment]
Oh you're right. 
Since those are global options though, that affect all elements in the application, I'd agree to have it documented somewhere else.
Also, explaining what the sticky_forms option does might help. I don't think it's as self explanatory as e.g. "use_select".

**Comment by VincentLanglet** [comment]
Do you still plan to make a documentation PR @rene-roesch-blg ? :)

**Comment by ghost** [comment]
I absolutely do, just wasn't available for the last couple of weeks. I'll link the PR in here as soon as possible.

**Comment by VincentLanglet** [comment]
> I absolutely do, just wasn't available for the last couple of weeks. I'll link the PR in here as soon as possible.

Did you find time to make something ? :)
