### ISSUE TITLE
Business logic when using ROLE_SUPER_ADMIN

### ISSUE THREAD

**Issue by fliespl** [sonata-project/SonataAdminBundle#7484]
Hi everyone, glad to finally see 4.0 released to the public! 

With this release we had to adjust our code quite a lot due to final methods being applied almost everywhere in AbstractAdmin class. We have managed to do it and while I mostly agree with this approach, I still have doubts about isGranted method in conjuction with ROLE_SUPER_ADMIN and how to properly handle cases as described below.

I totally understand that ROLE_SUPER_ADMIN is like a "god mode" in Sonata, yet it feels like it should somehow be possible to hide / limit certain functionality to this role. Up till now to achieve this we have used isGranted function to not only check if user has access to specific action on this object, but also if object is in proper state to be modified by some action.

Let's take for example such case like:
a) sending data to external webservice - in this case we assume that external webservice handle validation and won't accept same object again - in this case allowing ROLE_SUPER_ADMIN to see (button) and trigger SEND (action) again makes no sense in my opinion.

```php
        if (in_array($name, ['SEND'], true) && $object->isSent()) {
                return false;
        }
```

b) multi-step acceptance - in this case we expect two superior users (super_admin) to accept / reject proposed action. Role super admin would always see option to accept / reject change no matter at which stage it is (or had done it already).

Untortunately due to the fact how role security handler works (super admin "gets it all" as first step) we are unlucky. Voters won't do a trick here as well since it will never be voted due to `isAnyGranted($this->superAdminRoles)`

Do I understand correctly that with the release of 4.0 our options to hide content from super admin are:
a) do not use super_admin role
drawback: with complex system where there are only single exceptions for super admin it adds a lot of complexity to role definition yml
b) "somehow" hack the role security handler to also trigger some voters to happen before checking role_super_admin one? or in conjuction with it?
c) built separate templates for each item with custom logic,
d) accept the fact that super admin is god and deal with it ;)

Hope we can discuss this, so we can get better understanding how it should be handled.

**Comment by VincentLanglet** [comment]
> b) "somehow" hack the role security handler to also trigger some voters to happen before checking role_super_admin one? or in conjuction with it?

With 
```
security
    access_decision_manager:
        strategy: unanimous
```
All voter supporting the situation should be ok, so there is no need for doing the check before the super_admin one.

I personnaly have situation where the super admin cannot do things because of voters.

**Comment by fliespl** [comment]
@VincentLanglet do you have a full code example of such voter?

In our case voter doesn't run for role_super_admin while it does for others.


```
class DatabaseRecordSendAdminVoter extends Voter
{
    public const ATTRIBUTE = 'ROLE_APP_ADMIN_SURVEY_DATABASE_RECORDS_SEND';

    protected function supports(string $attribute, $subject)
    {
        return self::ATTRIBUTE === $attribute;
    }

    /**
     * @param DatabaseRecordAdmin $subject
     */
    protected function voteOnAttribute(string $attribute, $subject, TokenInterface $token)
    {
        /** @var Database $database */
        $database = $subject->getParent()->getSubject();

        if (Database::STATUS_NEW !== $database->getStatus() || 0 === $database->getRecords()->count()) {
            return false;
        }

        return true;
    }
}
```

We of course have:

```
access_decision_manager:
    strategy: unanimous
```

**Comment by VincentLanglet** [comment]
I think I had custom routes in mind, with @IsGranted annotation.

For the `AbstractAdmin::isGranted` method, you can still override it.
This method rely on `$this->getSecurityHandler()->isGranted`.
And by default the `RoleSecurityHandler` is used, but you can create your own service with his own logic.

**Comment by fliespl** [comment]
@VincentLanglet so that's what I said in point "b" - override role security handler.

Yet I find hard time to think of best implementation here. Previously it was possible to be on specific Admin class.

It looks strange since I would need to trigger another isAnyGranted (inclusive) call with custom role and affirtmative voter call by default.

I.e. something like this:

```
        try {
$role = $this->createPriorityCheckRoleForVoter($x, $y); // i.e. ROLE_APP_ADMIN_SURVEY_DATABASE_RECORDS_SEND_PRIORITY_CHECK ?
            return $this->isAnyGranted($role, $object) 
            
            && ($this->isAnyGranted($this->superAdminRoles)
                || $this->isAnyGranted($attributes, $object)
                || $useAll && $this->isAnyGranted([$allRole], $object));
        } catch (AuthenticationCredentialsNotFoundException $e) {
            return false;
        }
```

It doesn't feel right... What do you think?

**Comment by fliespl** [comment]
> I don't know if it could help to change
> 
> ```
> $this->isAnyGranted($this->superAdminRoles)
> ```
> 
> to
> 
> ```
> $this->isAnyGranted($this->superAdminRoles, $object)
> ```

Not really - since it doesn't provide me with context of what action was executed (EDIT, DELETE, SEND). I only know that super_admin wants to do "something" about object. Not what it actually wants.

**Comment by VincentLanglet** [comment]
> Yet I find hard time to think of best implementation here. Previously it was possible to be on specific Admin class.

You can still use a spectific SecurityHandler for a specific admin.

**Comment by fliespl** [comment]
But isn't it too much to implement for such a trivial functionality? SecurityHandler shouldn't validate logic, so I would also need to create custom voter with some attribute and trigger it.

Feels too much. Especially since can be probably done by redoing voters calls in this class while keeping BC.

I am not trying to argue in here. I simply find ROLE_SUPER_ADMIN to be overpowerful compared to 3.X (too much changes required to achieve something).

I can also do it like that:

```
        try {
if($admin instanceof CustomLoginInterface) {
   if(!$admin->amIableToDoIt($attributes, $action)) { return false; }
}
```

But it misses whole point of voters :)

**Comment by VincentLanglet** [comment]
> But isn't it too much to implement for such a trivial functionality? SecurityHandler shouldn't validate logic, so I would also need to create custom voter with some attribute and trigger it.
> Feels too much. Especially since can be probably done by redoing voters calls in this class while keeping BC.

I would say you took bad habits because it wasn't final before.
Admin classes shouldn't have such logic about authorization.

It's a good practice to split class by responsability, and something we like to try for the next major.

> I am not trying to argue in here. I simply find ROLE_SUPER_ADMIN to be overpowerful compared to 3.X

Then don't use the Super_admin role.

I'm sorry, but I think there are enough solutions for this problem, so we won't revert the final keyword.

**Comment by fliespl** [comment]
@VincentLanglet I think you totally misunderstood this issue. It was never about removing final keyword in the first place... Rather rethinking called voters, their orders.

> I would say you took bad habits because it wasn't final before.
> Admin classes shouldn't have such logic about authorization.
> It's a good practice to split class by responsability, and something we like to try for the next major.
Correct - we had used it wrong before. And now we wanted to use voters proper way as suggested. Many SecurityHandlers add complexity. Makes no sense in my opinion since I should be able to do it correctly with voters (provided they are called in thoughtful manner).

> I'm sorry, but I think there are enough solutions for this problem, so we won't revert the final keyword.
Yeah, there are - provided some of them in my initial post, asked about opinion and shared my doubts. 

I was hoping for some productive discussion over this subject. Got nothing in return to be honest.

Oh wait - I got this:
> Then don't use the Super_admin role.

**Comment by VincentLanglet** [comment]
The SUPER_ADMIN_ROLE by definition can do everything.

You want a ROLE who can do everything, except some things ; 
I don't see other solution than
- Using another role.
- Using another security handler to have a specific logic.

Changing the default security handler behavior would be a BC-break and might not satisfy the other 99% of users who is using it. But if you think you have a solution, feel free to open a PR.

> I was hoping for some productive discussion over this subject. Got nothing in return to be honest.

If you take it like this, it's not worth I take more time on this subject then.
