### ISSUE TITLE
The documentation lacks information on how to inject a service into the Admin class and how to get the user

### ISSUE THREAD

**Issue by axzx** [sonata-project/SonataAdminBundle#7520]
## Feature Request

The documentation lacks information on how to inject a service into the Admin class and how to get the user.

**Comment by core23** [comment]
Do you mean the symfony dependency injection? There is nothing special for this bundle.

**Comment by axzx** [comment]
> Do you mean the symfony dependency injection? There is nothing special for this bundle.

Yes.
I have custom service and I want use it in admin. 

I would also like to download a logged in user. 

I think such topics can be useful in the documentation.

**Comment by haivala** [comment]
https://symfony.com/doc/current/service_container/injection_types.html#constructor-injection
and with that you can inject Security to the Admin service and get the user from it.

**Comment by axzx** [comment]
> https://symfony.com/doc/current/service_container/injection_types.html#constructor-injection and with that you can inject Security to the Admin service and get the user from it.

OK, I'll explain my case.

I have 30 admin classes.
I have BaseAdmin in which I have the same logic.

Do you have an idea how to automatically inject admin to all classes?

**Comment by core23** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. This is a general question how to use symfony dependency injection.

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help

**Comment by axzx** [comment]
@core23
someone has already asked such a question and there is no answer 
https://stackoverflow.com/questions/68823032/how-to-get-container-instance-in-sonata-admin-class-v-4-0-0-rc-1

**Comment by haivala** [comment]
@axzx  I gave you answer how to do it and you can add it to that overflow as an answer
