### ISSUE TITLE
Nested CollectionTypes

### ISSUE THREAD

**Issue by TheFox** [sonata-project/SonataAdminBundle#7538]
I have a similar problem to #6777. In the latest version 3.105.3 in AdminHelper, the line

`$childFormBuilder = $this->getChildFormBuilder($formBuilder, $elementId);`

in is returning null when I am using nested `Sonata\Form\Type\CollectionType`.

In my Entity I have to expose the Collection

```
public function getAnswers(): Collection
{
    return $this->answers;
}
```

instead of only the array

```
/**
 * @return array<Answer>
 */
public function getAnswers(): array
{
    return $this->answers->toArray();
}
```

Otherwise it will not work because the else block is reached in the AdminHelper class.

In the loop of `getChildFormBuilder` the value for `$elementId` is `s616839720b0e2_questions_0_answers`. But there is only a `s616839720b0e2_questions` in the array (iterator). Not sure if this is the case of the problem.

**Comment by VincentLanglet** [comment]
It seems the right way to me to always expose the Collection. Especially for something called a CollectionType.
Never used an array instead of Collection for my entities.

**Comment by TheFox** [comment]
@VincentLanglet Depends on who you ask. If you ask the SensioLabs guys the collection should not be exposed. In my opinion it shouldn't matter. But who am I, right?

It shouldn't matter if you want to use `array` or `Collection` or any other array-like object. If Sonata would use `ArrayAccess` it shouldn't matter at all.

Instead of calling

```
$collection->add(new $modelClassName());
```

you could easily change it to

```
$collection[] = new $modelClassName();
```

This would be compatible and easy to change. `Doctrine\Common\Collections\Collection` already extends from `ArrayAccess`. And the code would be compatible with other array like objects/interfaces.

You could even remove the check

```
if (!($collection instanceof Collection))
```

~or just change it to~

```
if (!($collection instanceof \ArrayAccess))
```

Edit: you have to remove

```
if (!($collection instanceof Collection))
```

Native array is not an instanceof \ArrayAccess.

**Comment by TheFox** [comment]
@jordisala1991 @VincentLanglet Thank you for the support for ArrayAccess.

I just wondered if all the locations in the code where Collection is used is now supposed to be supported by ArrayAccess, or only this one case in AdminHelper. For example here it is still only Collection, no ArrayAccess:
https://github.com/sonata-project/SonataAdminBundle/blob/1f22334f3b55330d7b86d709a187db19cfc2f44c/src/Form/EventListener/MergeCollectionListener.php#L36
