### ISSUE TITLE
Many-to-Many & sonata_type_model not storing selection

### ISSUE THREAD

**Issue by thanosp** [sonata-project/SonataAdminBundle#757]
Using master code:

I have two entities Channel and Subject linked with a Many-to-Many relationship.

I'm using the simplest way to achieve that:

``` php
// Channel Entity
    /**
     * @ORM\ManyToMany(targetEntity="Subject")
     */
    public $subjects;
```

Within ChannelAdmin::configureFormFields I have:

``` php
$formMapper->add('subjects', 'sonata_type_model');
```

Upon updating the result is not stored. Even worse any selections will be cleared.

I would have guessed it is a configuration problem but the following will work just fine (but without the ajax addition of a new subject)

``` php
$formMapper->add('subjects', null);
```

**Comment by ureimers** [comment]
A little late to the party, but still thanks @thanosp to get back and write your sollution. That just saved me a big headache.

**Comment by OskarStark** [comment]
Should we mention this in the docs?

**Comment by ureimers** [comment]
You mean somewhere around here: https://sonata-project.org/bundles/admin/master/doc/reference/form_types.html?

Might be a good idea. My problem is that I still haven't read up on how to create a PR.
