### ISSUE TITLE
Textarea with TinyMce - required validation doesn't work properly

### ISSUE THREAD

**Issue by thomas2411** [sonata-project/SonataAdminBundle#764]
I use StfalconTinyMceBundle for some textarea fields. I add class tinymce css class to textarea field in Admin class. I overwrite base_edit template and I add link to tinymce JavaScript at the end of  the template.

When I have Textarea with Tinymce field that is required and a user doesn't fill this field, error is shown but below the end of the page. So it isn't  visible. I saw it cause I have Aero in Windows so the bottom browser belt is transparent.
Then if user fill this TinyMce field still he cannot save as the Empty field bug appears below the end of the page.

What is very weird, when I get this bug, when I fill TinyMce field and I go to Symfony profiler and then go back, I can save it properly

**Comment by Civile** [comment]
It should be fixed using an onchange event to copy the content of your wysiwyg to the textarea. Having a textarea with a specified ID I do this way: 
     
 setup:function(ed) {
       ed.on('change', function(e) {
           $("#"+ed.id).text(ed.getContent());
       });
      }

Each time i write something in tinymce it will be copied in the hidden textarea
