### ISSUE TITLE
Documentation Translation to PT-BR

### ISSUE THREAD

**Issue by guicunha** [sonata-project/SonataAdminBundle#7645]
## Feature Request

Hello,

I noticed that it doesn't have documentation in Portuguese for the project. I would like to start contributing to the project by translating the documentation into Portuguese and thus possibly bringing more supporters to it. Do you have a manual on how to proceed to carry out this PR.

**Comment by core23** [comment]
I'm not sure if we can maintain this docs in a long term after your initial translation.

**Comment by VincentLanglet** [comment]
We only have english documentation for our project and it's already hard to have a good documentation.
I dont think maintaining multiple language are a good idea for this project...

But thanks for the proposition. Any improvement to the english doc is welcomed.
