### ISSUE TITLE
Default sorting options - ignores non-list fields

### ISSUE THREAD

**Issue by viliam-husar** [sonata-project/SonataAdminBundle#768]
Setting default sorting fields and ordre via $datagridValues worked correctly until last few weeks. Today I finnaly decided to find what is wrong and why it is ignored. The problem is that Datagrid igonres fields which are not configured in list.

        if (isset($this->values['_sort_by'])) {
            foreach ($this->getColumns()->getElements() as $fieldDescription){
                if ($fieldDescription->isSortable() && $fieldDescription->getName() == $this->values['_sort_by']) {
                    $this->query->setSortBy($fieldDescription->getParentAssociationMappings(), $fieldDescription->getSortFieldMapping());
                    $this->query->setSortOrder(isset($this->values['_sort_order']) ? $this->values['_sort_order'] : null);

                    break;
                }
            }
        }

This whole block seems a bit wierd to me (iterating over all fields just to find name match...). Any explenation or suggestion?

**Comment by core23** [comment]
I think this is fixed. Can you check this please @viliam-husar

**Comment by greg0ire** [comment]
@viliam-husar please reopen if this isn't fixed.
