### ISSUE TITLE
Help option is duplicate for ModelListType

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataAdminBundle#7750]
<img width="256" alt="Screenshot 2022-02-19 at 22 22 01" src="https://user-images.githubusercontent.com/6358755/154819543-d0b42170-783f-4677-8d23-8e445e1d80a7.png">

Help option is showing duplicate for `ModelListType`

```php
                ->add('parent', ModelListType::class, [
                    'help' => 'Category parent help'
                ])
```

I tested with other type like `ModelType` and it works fine!

sonata 4.8.1
symfony 6.0
php 8.1

**Comment by VincentLanglet** [comment]
Can you play a little with the following code ?
https://github.com/sonata-project/SonataAdminBundle/blob/21372857df0b6ca6103117f9b7a22b7b24967ede/src/Resources/views/Form/form_admin_fields.html.twig#L545-L645

Maybe you just have to remove the following line
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/Resources/views/Form/form_admin_fields.html.twig#L628
