### ISSUE TITLE
Error when I try to create a new register with entities that use InheritanceType

### ISSUE THREAD

**Issue by eerison** [sonata-project/SonataAdminBundle#7755]
<img width="981" alt="Screenshot 2022-02-26 at 18 17 58" src="https://user-images.githubusercontent.com/6358755/155852599-e08d43e0-4e20-439b-8bfe-71d868045978.png">

User entity

```php
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[ORM\InheritanceType('JOINED')]
#[ORM\DiscriminatorColumn(name: 'discr', type: Types::STRING)]
#[ORM\DiscriminatorMap(['user' => User::class, 'customer' => Customer::class])]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{.....
```

Customer entity

```php
#[ORM\Entity(repositoryClass: CustomerRepository::class)]
class Customer extends User
```

when I try to register a new `customer`  I'm getting this error

```
Typed property App\Entity\User::$email must not be accessed before initialization
```

- sonata 4.8.1
- symfony 6.0
- php 8.1

Edit 1: it's happen only when I use typehint (private `string` $email)

**Comment by eerison** [comment]
hmmm maybe it can help somehow: https://github.com/symfony/symfony/issues/44525#issuecomment-989914868

**Comment by VincentLanglet** [comment]
I would need the whole entity to confirm this, but I would not consider this like a bug.
When using a Symfony Form you would have the same issue.

When accessing to the create view of the Customer, all the `getter` are called.
You're asking the `getEmail` to return `$this->email` but:
- Either you didn't set the value before. And removing the `string` property typehint would cause a similar issue (`getEmail` return `null` but the typehint say it should return `null`)
- Either you set the value as a param of the constructor, but then how Sonata could do for creating a new entity and passing a value to the constructor BEFORE you submit any form ?

The "right" way to typehint your entity here is
```
private ?string password = null;

public function getEmail(): ?null;

public function setEmail(string $password): self;
```
