### ISSUE TITLE
default_translation_domain deprecation does not trigger

### ISSUE THREAD

**Issue by Tobion** [sonata-project/SonataAdminBundle#7789]
The deprecation for default_translation_domain when the config is not defined does not trigger.

https://github.com/sonata-project/SonataAdminBundle/blob/942989200df9f5c20d23e50d5703188d6d4dfc8d/src/DependencyInjection/Configuration.php#L341-L356

This is because if the config is not set, the node validate callback method is also not called at all.
The only way to do this unfortunately is to validate the parent, root node. As an example see https://github.com/symfony/symfony/pull/45989/files

**Comment by VincentLanglet** [comment]
HI, Can you provide a PR ?

**Comment by Tobion** [comment]
This was closed but I don't think it's fixed yet.

**Comment by VincentLanglet** [comment]
Feel free to provide a PR
