### ISSUE TITLE
Add docker

### ISSUE THREAD

**Issue by mpoiriert** [sonata-project/SonataAdminBundle#7821]
## Feature Request

To help contribution it would be helpful to have a docker (docker-compose) set up in the project.

**Comment by mpoiriert** [comment]
I myself don't install my development environment on my computer anymore. I have a basic docker setup (only for dev) on all my open source project and clients project.

I could setup the basic of the docker project.

This would help be contribute on other issues for sonata. All my clients rely on it so my knowledge is decent to contribute.

**Comment by VincentLanglet** [comment]
We have a dev-kit project which dispatch all common files to all the sonata projects
https://github.com/sonata-project/dev-kit/tree/master/templates/project

Maybe this should be done there, so the Dockerfile would be shared between all projects.

**Comment by VincentLanglet** [comment]
Closing in favor of https://github.com/sonata-project/dev-kit/issues/2032
