### ISSUE TITLE
Make AdminExtension be aware of the AdminClass in addition to the model class

### ISSUE THREAD

**Issue by Hanmac** [sonata-project/SonataAdminBundle#7858]
## Feature Request

Currently AdminExtension either can be:
* configured over tags (using `global` or `target`) 
* Or other Configuration where you can use `implements`, `uses` and other where it checks the ModelClass of the Admin.

i would like more options available that i can use tag attributes to check if the AdminClass itself does extend/implement/uses a given class/interface/trait name.

A Possible Use Case would be if i make an Extension `AbcExt`, and say it should be added to all Admins that does implement Interface `AbcInterface`.

with that in place, the User only would need to implement that Interface, and the Extension would be added without the need of extra config.

**Comment by VincentLanglet** [comment]
This shouldn't be too hard to implements, the changes need to be done here: https://github.com/sonata-project/SonataAdminBundle/blob/4.x/src/DependencyInjection/Compiler/ExtensionCompilerPass.php
