### ISSUE TITLE
SonataAdminBundle and  symfony 5.4

### ISSUE THREAD

**Issue by mmoqiseh** [sonata-project/SonataAdminBundle#7904]
Hi
i want to use this bundle and  i have some questions
does Sonatabundle works well with Symfony 5.4? 
and is it recommended to use for new projects ? i mean is this still being supported?

**Comment by VincentLanglet** [comment]
Hi, you can found all the answer here:
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/composer.json#L41-L65
Means that Symfony 5.4 is supported

https://github.com/sonata-project/SonataAdminBundle/releases/tag/4.16.0
The fact the last release was made 11 days ago means it's still maintained
