### ISSUE TITLE
Questionning about sonata.admin.action.retrieve_form_field_element

### ISSUE THREAD

**Issue by ec-ecss** [sonata-project/SonataAdminBundle#7918]
Admin Bundle 4.13.0

I'm not sure if it's a bug so I put it on feature request
on vendor/sonata-project/admin-bundle/src/Action/RetrieveFormFieldElementAction.php
A handleRequest is made
Is the handleRequest necessary ? It seems that the ajax request that need handleRequest to modify the entity is already executed in the precedent call, and it's just a refresh call to update client html.
The context : I was implementing a n-n file upload, and the only solution to made work it properly is to override the service   sonata.admin.action.retrieve_form_field_element , with the same code but without the handleRequest.
Without that,  I've got a empty field.
I can make a PR if you think the handleRequest is not needed

Thanks !

**Comment by VincentLanglet** [comment]
Best would be to provide a failing test, to prove that the handleRequest need to be removed.

But I never got any issue with this action.

**Comment by eerison** [comment]
As it's a question and not an issue, and there isn't any interaction from @CaptainKant , IMO we can close this issue :)
