### ISSUE TITLE
pixSortableBehaviorBundle is abandoned 

### ISSUE THREAD

**Issue by dmitryuk** [sonata-project/SonataAdminBundle#7923]
A lot of documentations says that a developer can use [pixSortableBehaviorBundle](https://github.com/pix-digital/pixSortableBehaviorBundle). But it abandoned - last update 5 years ago
Doesn't support of Symfony v5 and Sonata Admin v4
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/docs/cookbook/recipe_sortable_listing.rst
https://symfony.com/bundles/SonataAdminBundle/current/cookbook/recipe_sortable_listing.html
Finally I can suggest to rewrite documentation to use a fork `https://github.com/Runroom/RunroomSortableBehaviorBundle` as official.
What do you think?

**Comment by VincentLanglet** [comment]
We should at least remove the section about pix indeed.

For RunroomSortableBehaviorBundle I let @jordisala1991 the decision since he's maintaining it.

Will you want to do the PR @dmitryuk ?

**Comment by jordisala1991** [comment]
For me its okay, I actively maintain `runroom-packages` and that `RunroomSortableBehaviorBundle` is included, so it will work okay. Also the bundle is updated and supports a wide range of versions.

I will let @dmitryuk do the PR tho, because I don't have a lot of time.

**Comment by dmitryuk** [comment]
@VincentLanglet, ok I will do it
