### ISSUE TITLE
Support display/hidden fields in `configureListFields`

### ISSUE THREAD

**Issue by onEXHovia** [sonata-project/SonataAdminBundle#7968]
At the moment in `configureListFields` method you can specify only the fields that will be displayed in the list, but often there are a lot of them and the table is heavily overloaded. But removing unnecessary fields from the list is also not a solution, since they are sometimes needed when filtering or sorting.

Suggestion to add the ability to hide fields that are not needed. The list of fields is customizable for each user. An example of what I mean can be seen here https://demo.laravel-admin.org/

<img width="1540" alt="" src="https://user-images.githubusercontent.com/3332033/200131096-fc19ebf2-5fb7-44f3-b309-a557570788c6.png">

<img width="1126" alt="" src="https://user-images.githubusercontent.com/3332033/200308702-696cb004-c804-4367-9351-d43281a58826.png">
<img width="805" alt="" src="https://user-images.githubusercontent.com/3332033/200308714-c0761b43-a7cc-4bec-936f-3ba484b4bec6.png">
<img width="679" alt="" src="https://user-images.githubusercontent.com/3332033/200309580-c5f9531c-aeeb-4d45-9415-20d3203c9e23.png">

**Comment by VincentLanglet** [comment]
The example you gave is reloading the whole page when we're trying to hide/show a list column.

We have a similar feature for filters, and they are displayed/hidden dynamically thanks to javascript.
This might be better to use javascript for this feature request rather than reloading the page everytime.

Do you want to give a try ?

**Comment by onEXHovia** [comment]
> We have a similar feature for filters, and they are displayed/hidden dynamically thanks to javascript.
> This might be better to use javascript for this feature request rather than reloading the page everytime.

The filter after reloading the page loses the selected fields.

The very purpose of display/hidden fields in configureListFields is to be able to have different settings for different user roles.

We, as developers, set up all possible fields in configureListFields by default. Further, the content manager can set up a list for himself that he needs, since sometimes there are a lot of service fields.

Therefore, we need some service that stores the configuration data(FilesystemStore, CookierStore etc).

**Comment by VincentLanglet** [comment]
> The very purpose of display/hidden fields in configureListFields is to be able to have different settings for different user roles.

You can already do this
```
if ($this->isGranted('CUSTOM_ROLE')) {
    $listMapper->add('field');
}
```

**Comment by onEXHovia** [comment]
Let's consider example, there is a service field `views` we not show content to managers

```
if (!$this->isGranted('CONTENT_MANAGER')) {
    $listMapper->add('view');
}
```

Next, they write to us how we can see the most viewed posts in the admin panel, hardcoded conditions are useless. This feature is just a convenience of content administration, where each user can customize the fields. 

Many fields are not needed in content administration, mainly for some kind of export or check. I hope I explained the idea 😊

**Comment by onEXHovia** [comment]
Updated the first post, added more examples from others cms/cmf(wordpress, magento, 1c-bitrix), this is a fairly common setting.

**Comment by VincentLanglet** [comment]
Do you want to start the PR ?

**Comment by haivala** [comment]
I would argue that hardcoded conditions are better than giving the control to the user. Of course it is bit more work so that you can understand what the user needs but with combination of https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/cookbook/recipe_row_templates/ you can get the data in really small display size and show exactly what they need.

**Comment by VincentLanglet** [comment]
> I would argue that hardcoded conditions are better than giving the control to the user. 

Both are valid.
- If you want to hide some informations to some users, it should be hardcoded.
- If you want to allow to see some informations but not always, they should have control.

Sure it can be done with a custom template. But if @onEXHovia get something which works and look nice, it can be a nice feature to add to this project.

**Comment by haivala** [comment]
> Sure it can be done with a custom template. But if @onEXHovia get something which works and look nice, it can be a nice feature to add to this project.

I agree!
