### ISSUE TITLE
Type error caused by `FormBuilderIterator`

### ISSUE THREAD

**Issue by dmaicher** [sonata-project/SonataAdminBundle#7984]
### Environment

- PHP 8.1
- latest Symfony 6.1
- latest Sonata packages

## Subject

Type error caused by `FormBuilderIterator`

## Minimal repository with the bug

?

## Steps to reproduce

I have an inline admin where I can add new items in a table view. If I press the "add" button then I get a type error since I moved to Symfony 6. It worked fine with Symfony 5.4 as there was no `string` typehint on Symfony's `FormBuilder::get`.

## Actual results

![Screenshot from 2022-12-08 13-09-45](https://user-images.githubusercontent.com/921145/206444324-ecb7ea00-8849-4a48-b83f-85185cd11a3f.png)

A dump of

```php
    public function current(): FormBuilderInterface
    {
        if ($this->iterator->current() === 0) {
            dd($this);
        }

        return $this->formBuilder->get($this->iterator->current());
    }
``` 

![Screenshot from 2022-12-08 13-10-26](https://user-images.githubusercontent.com/921145/206444341-298f63cf-2dac-4388-b788-4b2dd339d37e.png)

From what I can tell we cannot guarantee that `$this->iterator->current()` within `FormBuilderIterator` will actually be a string. In my case its an integer and this seems legit. The problematic form field is an expanded choice field with checkboxes and the children of this form are indexed with integers.

I checked it and casting to string there solves the issue for me. Shall I create a PR for this?

```php
    public function current(): FormBuilderInterface
    {
        return $this->formBuilder->get((string) $this->iterator->current());
    }
```

**Comment by dmaicher** [comment]
Might be related to https://github.com/symfony/symfony/issues/46698 @VincentLanglet :thinking:

**Comment by VincentLanglet** [comment]
Yeah, it was reported here https://github.com/sonata-project/form-extensions/issues/368#issuecomment-1337562206
