### ISSUE TITLE
Unknown "sonata_form_canonicalize_locale_for_moment" function

### ISSUE THREAD

**Issue by jgrygierek** [sonata-project/SonataAdminBundle#7988]
Hi, since `SonataAdmin 4.12` I'm getting this error:

```
[critical] Uncaught PHP Exception Twig\Error\SyntaxError: "Unknown "sonata_form_canonicalize_locale_for_moment" function. Did you mean "canonicalize_locale_for_moment"?" at /var/www/sonata-test-bundle/vendor/sonata-project/admin-bundle/src/Resources/views/standard_layout.html.twig line 69
```

It was ok when I used `SonataAdmin 4.11.1`.

php 8.1
Symfony 6.2

**Comment by VincentLanglet** [comment]
I assume the form-extensions is not correctly declared in your project
https://docs.sonata-project.org/projects/form-extensions/en/1.x/reference/installation/

**Comment by jgrygierek** [comment]
Yeah, you are right. Thanks.
