### ISSUE TITLE
How to overide  admin.js in v4 ?

### ISSUE THREAD

**Issue by askuiop** [sonata-project/SonataAdminBundle#7989]
How to overide  admin.js in v4 ?

**Comment by VincentLanglet** [comment]
Sorry, but we try to keep github issues for feature requests and bugs only. 

- Please have a look at the [sonata docs](https://sonata-project.org/bundles/)
- Use [StackOverflow](http://stackoverflow.com/questions/tagged/sonata) for general support and help others as well
- Join #sonata on [the symfony-devs slack](https://symfony.com/slack-invite) for immediate help
