### ISSUE TITLE
Remove assert of Exporter instance in CRUDController

### ISSUE THREAD

**Issue by pkameisha** [sonata-project/SonataAdminBundle#7992]
## Feature Request
I have an issue in project while upgrading to the symfony 5.4 and latest sonata packages.
In our microservices we have replaced Exporter class with our class for our needs. 
But with the new update there is a row, that breakes all our export features.
`\assert($exporter instanceof Exporter);`

I suggest to remove this line or just check if `$exporter` is class.
Of course, the best solution is to add Interface, don't you think?

**Comment by VincentLanglet** [comment]
You mean
```
$exporter = $this->container->get('sonata.exporter.exporter');
\assert($exporter instanceof Exporter);
```
?

I would be ok introducing an interface for the class
https://github.com/sonata-project/exporter/blob/3.x/src/Exporter.php#L22

I would require to drop the 2.x support of sonata-exporter too which wouldn't be an issue
https://github.com/sonata-project/SonataAdminBundle/blob/4.x/composer.json#L38

Do you want to do the PR on both sonata-exporter and sonata-admin @pkameisha ?

**Comment by pkameisha** [comment]
Yeah, that's what I mean
```
$exporter = $this->container->get('sonata.exporter.exporter');
\assert($exporter instanceof Exporter);
```
Sure, I can do PRs

**Comment by VincentLanglet** [comment]
3.1.0 is release so you can now do the sonataAdmin PR 
https://github.com/sonata-project/exporter/releases/tag/3.1.0

**Comment by pkameisha** [comment]
As I see, PR is merged. Could you create a new tag?

**Comment by VincentLanglet** [comment]
Done
