### ISSUE TITLE
CSRF token is invalid [Sonata Admin]

### ISSUE THREAD

**Issue by nicolasjaco** [sonata-project/SonataAdminBundle#8015]
Hello,

I'm opening this issue because we have an issue with CSRF token in Sonata Admin (4.8.1).
We use Symfony (5.4) with PHP (7.3.33).

Currently we deactivate the csrf token to make work the Back Office but it's a temporary measure. We don't want to let the csrf deactivated but we don't know how to handle this issue.

I attach the screen of the issue.

Our config file is like this :
  framework:
      session:
          storage_factory_id: session.storage.factory.native
          handler_id: null

Let me know if you need more information
Thanks in advance for help

<img width="376" alt="img" src="https://user-images.githubusercontent.com/58025105/222393311-be48958b-d65d-4615-921c-ddce13622957.png">

**Comment by jordisala1991** [comment]
Can you provide a repository that reproduces the problem? Or at least the steps you followed to get the error?

Looks like a configuration problem on your side with the info you provided.

**Comment by tschelhas** [comment]
I recently had the same issue.
In my case the reason was a big formular with a lot of multiple choice elements so the post action exceeded the php config value for "max_input_vars".

So u should check this config parameter against your posted values.

**Comment by rafa0805** [comment]
Hi folks!

I'm facing seemingly the same trouble after updating sonata-project/admin-bundle.
It seems that the following release of symfony/security-http is breaking something.
https://github.com/symfony/security-http/releases/tag/v5.4.31


versions of packages in my project is fixed to:
- sonata-project/admin-bundle: 4.29.1
- symfony/security-http: 5.4.31

**Comment by VincentLanglet** [comment]
> It seems that the following release of symfony/security-http is breaking something. [symfony/security-http@`v5.4.31` (release)](https://github.com/symfony/security-http/releases/tag/v5.4.31)

If it's related to a symfony update, you should report this to symfony instead.
