### ISSUE TITLE
Unknown column type json requested

### ISSUE THREAD

**Issue by vazgen** [sonata-project/SonataAdminBundle#811]
Hello, 

I have update this bundle and now get an error:

```
[Doctrine\DBAL\DBALException]        
Unknown column type json requested.
```

It seems that I have to install SonataDoctrineExtensions to fix this.  Is it required?  

Thanks.

**Comment by halfa** [comment]
thanks @Glideh

**Comment by birchandra** [comment]
for Symfony3, insert the following code in config.yml
doctrine:
    dbal:
        #     ....
        types:
            json: Sonata\Doctrine\Types\JsonType
