### ISSUE TITLE
SAML SSO and SCIM to the Admin Panel

### ISSUE THREAD

**Issue by iMonZ** [sonata-project/SonataAdminBundle#8122]
## Feature Request

An Awesome feature would be if SAML SSO support for secure authentication would be possible
https://www.microsoft.com/en-us/security/business/security-101/what-is-security-assertion-markup-language-saml
https://techcommunity.microsoft.com/t5/security-compliance-and-identity/provisioning-with-scim-getting-started/ba-p/880010

**Comment by core23** [comment]
Not sure if this is a feature request for the admin bundle. This looks more like a security / user bundle feature
