### ISSUE TITLE
Using SubClasses in admins create either not handable translation ids or urly urls

### ISSUE THREAD

**Issue by BA-JBI** [sonata-project/SonataAdminBundle#8128]
## Problem
Rererring to:
https://symfony.com/bundles/SonataAdminBundle/current/reference/advanced_configuration.html#inherited-classes

**Variant A**

```
App\Admin\ExampleAdmin:
    tags:
        -   name:            sonata.admin
#            [...]
    calls:
      - ['setSubClasses', [{
             class_a: App\Entity\SubClassA,
             class_b: App\Entity\SubClassB
      }]]
```

Is resulting in 
![image](https://github.com/sonata-project/SonataAdminBundle/assets/31063297/494eca67-4bf1-4f86-b81b-800c199cbc2d)
![image](https://github.com/sonata-project/SonataAdminBundle/assets/31063297/b8aa929d-203c-4572-8530-3c18b2df032f)

Those translation labels are not great to handle

---
**Variant B**

```
App\Admin\ExampleAdmin:
    tags:
        -   name:            sonata.admin
#            [...]
    calls:
      - ['setSubClasses', [{
             app.my_class.subclass.class_a: App\Entity\SubClassA,
             app.my_class.subclass.class_b: App\Entity\SubClassB
      }]]
```

creates nice translation labels but ugly create url:

```
https://my.app.example/admin/entity/namespace/create?subclass=app.my_class.subclass.class_a
```

---

## My suggested solution:

https://github.com/sonata-project/SonataAdminBundle/blob/75d71162b5bdd590afc105bcd0e8112f4cced224/src/Resources/views/Button/create_button.html.twig#L25

Change to: 
```
                    {{ 'link_action_create'|trans({}, 'SonataAdminBundle') }} {{ admin.translationLabel(subclass,'subclass')|trans({}, admin.translationDomain) }}
```

**Comment by VincentLanglet** [comment]
That would be a BC break and would require a new major version.
Doesn't seems worth it.
