### ISSUE TITLE
Overriding createQuery doesn't seem to be a thing anymore

### ISSUE THREAD

**Issue by vulkanosaure** [sonata-project/SonataAdminBundle#8131]
I want to modify the list query,
after spending an hour searching google, the consensus seems to be overriding the `createQuery`,
even the sonata official documentation states so, 
but in my bundle version` 4.28`, that method is final and overriding doesn't seem to be possible, so i assume this is probably a recent change.

Has there been any update in the documentation regarding that breaking change ?

**Comment by zyberspace** [comment]
Hey @vulkanosaure ,

it's `configureQuery` now: https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/action_list/#customizing-the-query-used-to-generate-the-list :)

**Comment by vulkanosaure** [comment]
Ok thanks !
