### ISSUE TITLE
symfony 7 compatibility

### ISSUE THREAD

**Issue by stayeronglass** [sonata-project/SonataAdminBundle#8132]
./composer.json has been updated
Running composer update sonata-project/admin-bundle
Loading composer repositories with package information
Restricting packages listed in "symfony/symfony" to "7.0.*"
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonata-project/admin-bundle 4.29.0 requires symfony/security-acl ^3.1 -> satisfiable by symfony/security-acl[v3.1.0, ..., v3.3.2].
    - sonata-project/admin-bundle 2.0.0 requires sonata-project/jquery-bundle dev-master -> found sonata-project/jquery-bundle[dev-master, 1.9.x-dev (alias of dev-master)] but it does not match your minimum-stability.
    - sonata-project/admin-bundle[2.1.0, ..., 2.1.1] require twig/twig >=1.10,<2.0-dev -> found twig/twig[v1.10.0, ..., v1.44.7] but it conflicts with your root composer.json require (^2.12|^3.0).
    - sonata-project/admin-bundle[2.2.0, ..., 2.2.2] require twig/twig >=1.12,<2.0-dev -> found twig/twig[v1.12.0, ..., v1.44.7] but it conflicts with your root composer.json require (^2.12|^3.0).
    - sonata-project/admin-bundle[2.2.3, ..., 2.2.13] require twig/twig ~1.12 -> found twig/twig[v1.12.0, ..., v1.44.7] but it conflicts with your root composer.json require (^2.12|^3.0).
    - sonata-project/admin-bundle[2.3.0, ..., 2.3.1] require twig/twig ~1.15 -> found twig/twig[v1.15.0, ..., v1.44.7] but it conflicts with your root composer.json require (^2.12|^3.0).
    - sonata-project/admin-bundle[2.3.2, ..., 2.3.10] require symfony/expression-language ~2.4 -> found symfony/expression-language[v2.4.0, ..., v2.8.52] but it conflicts with your root composer.json require (7.0.*).
    - sonata-project/admin-bundle[3.0.0, ..., 3.23.0] require php ^5.3 || ^7.0 -> your php version (8.2.7) does not satisfy that requirement.
    - sonata-project/admin-bundle[3.24.0, ..., 3.63.0] require php ^7.1 -> your php version (8.2.7) does not satisfy that requirement.
    - sonata-project/admin-bundle[3.25.0, ..., 3.43.0] require php ^5.6 || ^7.0 -> your php version (8.2.7) does not satisfy that requirement.
    - sonata-project/admin-bundle[3.64.0, ..., 3.79.0] require php ^7.2 -> your php version (8.2.7) does not satisfy that requirement.
    - sonata-project/admin-bundle[3.80.0, ..., 3.87.0] require php ^7.3 -> your php version (8.2.7) does not satisfy that requirement.
    - sonata-project/admin-bundle[3.88.0, ..., 3.107.3, 4.0.0, ..., 4.20.0] require doctrine/collections ^1.6 -> found doctrine/collections[v1.6.0, ..., 1.8.0] but the package is fixed to 2.1.4 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - sonata-project/admin-bundle[4.21.0, ..., 4.22.4] require symfony/asset ^4.4 || ^5.4 || ^6.0 -> found symfony/asset[v4.4.0, ..., v4.4.46, v5.4.0, ..., v5.4.31, v6.0.0, ..., v6.4.0] but it conflicts with your root composer.json require (7.0.*).
    - sonata-project/admin-bundle[4.22.5, ..., 4.22.6] require symfony/asset ^4.4 || ^5.4 || ^6.2 -> found symfony/asset[v4.4.0, ..., v4.4.46, v5.4.0, ..., v5.4.31, v6.2.0, ..., v6.4.0] but it conflicts with your root composer.json require (7.0.*).
    - sonata-project/admin-bundle[4.23.0, ..., 4.28.1] require symfony/asset ^5.4 || ^6.2 -> found symfony/asset[v5.4.0, ..., v5.4.31, v6.2.0, ..., v6.4.0] but it conflicts with your root composer.json require (7.0.*).
    - symfony/security-acl[v3.1.0, ..., v3.1.2] require symfony/security-core ^3.4|^4.4|^5.0 -> found symfony/security-core[v3.4.0, ..., v3.4.49, v4.4.0, ..., v4.4.48, v5.0.0, ..., v5.4.30] but the package is fixed to v7.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - symfony/security-acl v3.2.0 requires symfony/security-core ^4.4|^5.0 -> found symfony/security-core[v4.4.0, ..., v4.4.48, v5.0.0, ..., v5.4.30] but the package is fixed to v7.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - symfony/security-acl[v3.3.0, ..., v3.3.2] require symfony/security-core ^4.4|^5.0|^6.0 -> found symfony/security-core[v4.4.0, ..., v4.4.48, v5.0.0, ..., v5.4.30, v6.0.0, ..., v6.4.0] but the package is fixed to v7.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - Root composer.json requires sonata-project/admin-bundle * -> satisfiable by sonata-project/admin-bundle[2.0.0, ..., 2.3.10, 3.0.0, ..., 3.107.3, 4.0.0, ..., 4.29.0].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require sonata-project/admin-bundle:*" to figure out if any version is installable, or "composer require sonata-project/admin-bundle:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

#### Symfony packages

 Symfony                                                         
 -------------------- ------------------------------------------- 
  Version              7.0.0                                      
  Long-Term Support    No                                         
  End of maintenance   07/2024 (in +244 days)                     
  End of life          07/2024 (in +244 days)                     
 -------------------- ------------------------------------------- 
  Kernel                                                          
 -------------------- ------------------------------------------- 
  Type                 App\Kernel                                 
  Environment          dev                                        
  Debug                true                                       
  Charset              UTF-8                                      
  Cache directory      ./var/cache/dev (9.3 MiB)                  
  Build directory      ./var/cache/dev (9.3 MiB)                  
  Log directory        ./var/log (32 KiB)                         
 -------------------- ------------------------------------------- 
  PHP
 -------------------- -------------------------------------------
  Version              8.2.7
  Architecture         64 bits
  Intl locale          n/a
  Timezone             Europe/Moscow (2023-11-30T21:15:16+03:00)
  OPcache              false
  APCu                 false
  Xdebug               false
 -------------------- -------------------------------------------

#### PHP version

```
$ php -v
PHP 8.2.7 (cli) (built: Jun 19 2023 22:29:21) (NTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.2.7, Copyright (c) Zend Technologies

**Comment by core23** [comment]
Please don't be that lazy. We have 3 open PRs and one of those is about symfony 7 support.
