### ISSUE TITLE
  Problem 1     - symfony/security-acl[v3.1.0, ..., v3.1.2] require symfony/security-core ^3.4|^4.4|^5.0 -> found symfony/security-core[v3.4.0, ..., v3.4.49, v4.4.0, ..., v4.4.48, v5.0.0, ..., v5.4.30] but it conflicts with your root composer.json require (7.0.*).

### ISSUE THREAD

**Issue by vaigtech** [sonata-project/SonataAdminBundle#8135]
#### Symfony and  Sonata packages

<details><summary>show</summary>
<p>

```
composer create-project symfony/skeleton:"7.0.*@dev" symfony
composer require sonata-project/admin-bundle

```

</p>
</details>

#### PHP version

```
$ php -v
# PHP 8.2.13
```

## Subject

  Problem 1
    - symfony/security-acl[v3.1.0, ..., v3.1.2] require symfony/security-core ^3.4|^4.4|^5.0 -> found symfony/security-core[v3.4.0, ..., v3.4.49, v4.4.0, ..., v4.4.48, v5.0.0, ..., v5.4.30] but it conflicts with your root composer.json require (7.0.*).
    - symfony/security-acl v3.2.0 requires symfony/security-core ^4.4|^5.0 -> found symfony/security-core[v4.4.0, ..., v4.4.48, v5.0.0, ..., v5.4.30] but it conflicts with your root composer.json require (7.0.*).
    - symfony/security-acl[v3.3.0, ..., v3.3.2] require symfony/security-core ^4.4|^5.0|^6.0 -> found symfony/security-core[v4.4.0, ..., v4.4.48, v5.0.0, ..., v5.4.30, v6.0.0, ..., v6.4.0] but it conflicts with your root composer.json require (7.0.*).
    - sonata-project/admin-bundle 4.29.0 requires symfony/security-acl ^3.1 -> satisfiable by symfony/security-acl[v3.1.0, ..., v3.3.2].
    - Root composer.json requires sonata-project/admin-bundle 4.29.0 -> satisfiable by sonata-project/admin-bundle[4.29.0].

**Comment by vaigtech** [comment]
Please help to solve the problem  Thanks in advance

**Comment by VincentLanglet** [comment]
It's not on our side, but on symfony/security-acl side https://github.com/symfony/security-acl/pull/111
