### ISSUE TITLE
status of runroom sortable behavior

### ISSUE THREAD

**Issue by mvhirsch** [sonata-project/SonataAdminBundle#8178]
I recently took a look in my project's dependencies and noticed we're using `runroom/sortable-behaviour`. While nothing is wrong with that, I looked into the [project's source](https://github.com/Runroom/RunroomSortableBehaviorBundle) and it looks abandoned to me (since it's marked as [READ-ONLY]). Not sure if it's still updated (can't ask there, as Issues is turned off), but since [SonataAdminBundle's official docs](https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/cookbook/recipe_sortable_listing/#the-recipe) still use this in it's recipes, I'm wondering: 

@jordisala1991 what's the status of this bundle? Will it receive updates (e.g. if I contribute them) like Symfony v7?

**Comment by VincentLanglet** [comment]
Looking at the repo it's said
```
The sources of this package are contained in the Runroom monorepo. We welcome contributions for this package on [runroom/runroom-packages](https://github.com/Runroom/runroom-packages).
```
and https://github.com/Runroom/runroom-packages is not abandoned.

Anyway, issue should be created on this repo instead https://github.com/Runroom/runroom-packages/issues

**Comment by mvhirsch** [comment]
I should have read more carefully. Thank you!
