### ISSUE TITLE
ListField translations based on Enums

### ISSUE THREAD

**Issue by MathisBurger** [sonata-project/SonataAdminBundle#8211]
## Feature Request

Currently, I have to use a workaround to properly translate enums. 
For ListViews I need to use `Enum::Variant->value` for `choices` index.
Furthermore, I need to provide an extra getter to my entity, I want to display, that returns `$this->enum->value` (the enums value as string) in order to translate the Enum variant properly.

It would be cool to just have the enum variants (without `->value`) in the `choices` array, as well as the option to simply pass the enum getter to the list field.

Possible solution:
- Check whether the `type` of the added list field is `FieldDescriptionInterface::TYPE_CHOICE`
- If it is, check if the provided value is an instance of an [String backed enum](https://www.php.net/manual/en/language.enumerations.backed.php)
- If it is, perform `->value` on the provided value and all indexes of the `choices` array

**Comment by zyberspace** [comment]
Hi @MathisBurger ,

have you seen the enum field type? `FieldDescriptionInterface::TYPE_ENUM`  
https://docs.sonata-project.org/projects/SonataAdminBundle/en/4.x/reference/field_types/#fielddescriptioninterface-type-enum

If i understand you correctly, the following should do the trick:

```php
protected function configureListFields(ListMapper $list): void
{
    $list
        ->add('myEnumProperty', FieldDescriptionInterface::TYPE_ENUM, [
            'use_value' => true,
            'enum_translation_domain' => 'messages', // Or whatever translation domain you are using
        ])
    ;
}
```

**Comment by MathisBurger** [comment]
Hi @zyberspace,
yes I was already aware of the enum field type. 
The problem I have if the following:
- I have my translations organized within one domain in YAML format.
- The enum list types required the values of the enum to be exactly the translation key, which does not seem elegant to me
- I want a mapping similar to the choice type that maps the enum values to their translation keys

**Comment by zyberspace** [comment]
@MathisBurger Ok, so you have basically the same problem i had with the enum field type.

I don't understand the last point with the choice type, but what i do in my projects is the following:

- For forms, i use symfony's [EnumType](https://symfony.com/doc/current/reference/forms/types/enum.html). This is basically the choice type, but it generates the choices automatically from the enum.
- By default the `EnumType` will use the case name as label, however by implementing the `TranslatableInterface` interface on the enum and providing a custom `trans()` method, you can basically translate the enum in any way you like.  
  e.g.:
  ```php
  enum MyEnum implements TranslatableInterface
  {
      /* case ... = ...; */

      public function trans(TranslatorInterface $translator, ?string $locale = null): string
      {
          // Implement your custom enum translation logic here
          return $translator->trans('enum.myEnum.'.$this->value, locale: $locale);
      }
  }
  ```
  If your enums implements the `TranslatableInterface` the result of the `trans()` method will instead be used as label for the choices instead.

Only problem with this approach is, that sonata's enum field type completely ignores this. To fix this i requently opened a PR: #8212 

In the meantime, you can fix this yourself by overriding the `display_enum.html.twig` file in your project:

```twig
{# Add this file under templates/bundles/SonataAdminBundle/CRUD/display_enum.html.twig to override
   the original template by sonata admin. May have to use `bin/console cache:clear` for symfony to
   detect the override. #}

{# TODO: Can be removed once this is merged: https://github.com/sonata-project/SonataAdminBundle/pull/8212 #}
{% if value.trans is defined %}
    {# Translatable enum #}
    {{ value|trans }}
{% else %}
    {{ include('@!SonataAdmin/CRUD/display_enum.html.twig') }}
{% endif %}
```

I hope this helps.

**Comment by MathisBurger** [comment]
@zyberspace That seems like an good approach. 
I think the part you mentioned you couldn’t understand is the one about the translation mapping being similar to the choice type.

What I meant was something similar to this: [TranslatableChoiceType Documentation](https://docs.sonata-project.org/projects/form-extensions/en/3.x/reference/form_types/#translatablechoicetype).

It would be ideal to have a map that links each enum value to a translation key. However, your approach also seems appropriate.

**Comment by VincentLanglet** [comment]
Is this issue solved by https://github.com/sonata-project/SonataAdminBundle/pull/8212 ?

**Comment by MathisBurger** [comment]
Yes, it is
