### ISSUE TITLE
Deleting an object with ACL only deletes the ACL and not the object itself

### ISSUE THREAD

**Issue by tristanbes** [sonata-project/SonataAdminBundle#845]
Hi,

I'm using ACL to administrate some part of the backend.

**The problem :**
Deleting an object with ACL only deletes the ACL and not the object itself (sometimes)

**The scenario :**

1° When a campaign is created, we must enter an email admin to manage this campaign.

2° When the user is connetced, it compares its email address and the one from the campaign. If it matches, the code grants him the ADMIN role(to access the dashboard) and gives him the OPERATOR rights on this campaign.

3° When I go in the administration, i can delete an object contained in the campaign ( by testing the user against the campaign in the `isGranted` method. ( http://screencast.com/t/FxjaQgsDE1)

4° Now, supposing I want to delete the campaign : http://screencast.com/t/BleznKaobRID then error : http://screencast.com/t/hy9cFDZ0cL

but **when watching to the BD Queries**  : http://screencast.com/t/3ZdpH8Xn

So it results that I'm no longer able to edit/delete nor the Campaign, nor the Objects contained in the campaign **because the ACL right has been deleted**.

(PS: I do have cascade={"DELETE"} on the $objects contained in the Campaign class.)

Did i missed something ? (I'm on SF2.0)
Thanks.

**Comment by core23** [comment]
Issue still ative? @tristanbes

**Comment by tristanbes** [comment]
it dates back so much (Symfony 2.0), closing and re opening if still occurs.
