### ISSUE TITLE
Some bug in MergeCollectionListener class

### ISSUE THREAD

**Issue by suncat2000** [sonata-project/SonataAdminBundle#854]
I found some bugs in class `MergeCollectionListener` when used `ManyToMany` relationship between entities. Changes in relationships are not saved.

The problem in the method `onBind`:

```
...
$collection = $event->getForm()->getData();
$data = $event->getData();
...
```

`$collection` and `$data` is references to the same object. I test with `===` operator.

I found two solutions:

**A**. In `Sonata\AdminBundle\Form\EventListener\MergeCollectionListener` after lines:

```
...
public function onBind (FilterDataEvent $event)
     {
         $collection = $event->getForm()->getData();
         $data = $event->getData();
```

add the line:

`$data = is_object ($data)? clone $data: $data;`

it will make $collection and $data different instances of the object

**B**. In `Sonata\AdminBundle\Form\Type\ModelType` instead:

`use Sonata\AdminBundle\Form\EventListener\MergeCollectionListener;`

use:

`use Symfony\Component\Form\Extension\Core\EventListener\MergeCollectionListener;`

and in the `buildForm` method add subscriber instanceof `Symfony\Component\Form\Extension\Core\EventListener\MergeCollectionListener`:

```
...
if ($ options ['multiple']) {
             $ builder
                 -> addEventSubscriber (new MergeCollectionListener (true, true))
...
```

**Which solutions is more correct?**
**Will you fix this bug or I can do PR?**

**Comment by core23** [comment]
@suncat2000 Issue still active?

**Comment by core23** [comment]
This issue is very old. Can you please check this against the latest stable / master version? 

Feel free to reopen, if the error still exists. 

A PR would be welcome if you reopen this issue.
