### ISSUE TITLE
Nested filter form name contains illegal character(~)

### ISSUE THREAD

**Issue by frankdavid** [sonata-project/SonataAdminBundle#919]
I have a filter named user.address.location which filters by the location of the user's address. When I open the form, I get a symfony error: 

> The name "user~address~location" contains illegal characters. Names should start with a letter, digit or underscore and only contain letters, digits, numbers, underscores ("_"), hyphens ("-") and colons (":").

There is this method in Sonata\AdminBundle\Filter\Filter:
```php
     public function getFormName()
     {
          /* Symfony default form class sadly can't handle
            form element with dots in its name (when data
           get bound, the default dataMapper is a PropertyPathMapper).
           So use this trick to avoid any issue.
        */
        return str_replace('.', '~', $this->name);
    }
```

The ```~``` should be replaced by ```__``` or anything that symfony accepts.

**Comment by core23** [comment]
@frankdavid Issue still active?

**Comment by frankdavid** [comment]
@core23 Sorry, I no longer develop Symfony apps, hence I cannot confirm. I think let's close it for now and reopen it if someone encounters the problem later on.
