### ISSUE TITLE
Broken field description when using subclasses

### ISSUE THREAD

**Issue by inssein** [sonata-project/SonataAdminBundle#924]
FormMapper.php line 119: 
```php
$fieldDescription = $this->admin->getModelManager()->getNewFieldDescriptionInstance(
            $this->admin->getClass(),
            $name instanceof FormBuilder ? $name->getName() : $name,
            $fieldDescriptionOptions
        );
```

Because we passing in $this->admin->getClass(), the field descriptions don't know anything about the active sub class. My current solution is to extend the AdminInterface and add a getActiveClass (for the lack of a better name), and then in Admin.php, I added the code below. Finally, I changed the above getClass() call to getActiveClass().

```php
public function getActiveClass()
{
    return $this->getActiveSubClass() ?: $this->getClass();
}
```

I didn't submit a pull request because I don't think this is the correct solution, nor do I have the naming right. I am also very new to github, so any help on what to do next is very much appreciated.

**Comment by rande** [comment]
@aleno It is fixed here: https://github.com/sonata-project/SonataDoctrineORMAdminBundle/commit/501e0dcec17f8d847623b3c73310f258c052e5e2
