### ISSUE TITLE
[2.0] OneToMany, sonata_type_collection and by_reference - either duplicates rows or doesn't save

### ISSUE THREAD

**Issue by RobMasters** [sonata-project/SonataAdminBundle#931]
This issue is probably very similar to #929, but for the 2.0 branch - and I've tested that orphanRemoval doesn't have any effect on the problem.

I'm trying to add many "StoryHasMedia" entities to my "Story" entity, along the same lines as how the GalleryAdmin is configured within the SonataMediaBundle. Here is the relevant snippet:

``` php
->add('storyHasMedia', 'sonata_type_collection', array(
        'required' => false,
        'by_reference' => false,
        'label' => 'Media items'
    ), array(
        'edit' => 'inline',
        'inline' => 'table',
        'sortable'  => 'position',
        'link_parameters' => array('context' => 'default'),
        'help' => 'Optionally add or select media items for the story text.'
    )
)
```

It appears as though I need to set `by_reference` to false or else I end up with StoryHasMedia rows in the database with `story_id` set to NULL, which is of no use. 

But when `by_reference` is false, clicking the add icon to create a new row always duplicates the row(s) that are currently in the form - both currently saved rows and new ones - and then appends another empty row at the end. This is very frustrating, and I'm getting constant complaints about it from the people trying to use the system. Here are some screengrabs that show the problem:

Story with 2 media items, before clicking add...
![Before clicking add](http://joe.ie/img/story_media_1.png)

...and after clicking add a single time...
![After clicking add](http://joe.ie/img/story_media_2.png)

I've spent longer than I care to think about trawling through my debugger to find the cause of this problem but am still none the wiser...could somebody please let me know how to go about fixing this, or even better submit a fix for it? Or let me know if it's something I'm doing wrong - it seems as though this must be possible as it's working fine in SonataMediaBundle's GalleryAdmin.

**Comment by Matheuss-oliveira** [comment]
@rande, I might have the same problem but I didn't understand very well the solution you proposed.

Could you give a little example of what it could be missing in the code? Thank you very much.
